### ISSUE TITLE
add jenkins run for pip install without any dependencies preinstalled

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#100]
To ensure continuous integration of pip installs

**Comment by marscher** [comment]
this would take a lot of time, so we should do this on our own Jenkins

**Comment by franknoe** [comment]
is this resolved?

**Comment by marscher** [comment]
not yet. I'd be given access to our new build system at the end of last 
week - so far I had not time migrating all the jenkins jobs - since it 
is somehow a fragile system depending very much on the underlying system.

Since we do not officially recommend the usage of PyPI, this issue has 
low priority for me.

**Comment by franknoe** [comment]
ok, I was just trying to clean up things

Am 01/09/15 um 13:52 schrieb Martin K. Scherer:

> not yet. I'd be given access to our new build system at the end of last
> week - so far I had not time migrating all the jenkins jobs - since it
> is somehow a fragile system depending very much on the underlying system.
> 
> Since we do not officially recommend the usage of PyPI, this issue has
> low priority for me.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/100#issuecomment-136686360.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
done
