### ISSUE TITLE
Question on active set definition

### ISSUE THREAD

**Issue by giopina** [markovmodel/PyEMMA#1001]
How is the active set defined? 

I assume that groups of states that are entered but never left (or viceversa) are marked as non-active.

However I have a discrete trajectory  that enters in a state and leaves it after a short time, but this state is not included in the active set.

I noticed that the time spend in the state by the trajectory is smaller than the lagtime I'm using. I guess this must be the reason for its exclusion. Is this interpretation correct?

Thanks in advance

**Comment by marscher** [comment]
By default it is defined as the largest connected set. So you can have trap states, because they are still reachable (once).

**Comment by marscher** [comment]
So it can be that the state gets disconnected, if you choose a too large lag time, because if it exceeds the time to enter/leave the state, you can not observe any counts into it.

**Comment by giopina** [comment]
I think I understood what's going on. The event is actually very close (<tau) to the beginning of the trajectory, so there's actually no entering event.

Thanks!
