### ISSUE TITLE
Please document how tests are run

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#102]
It's not obvious to me how to run all pyEMMA tests (API+IMPL). Please document this at the development page.

**Comment by marscher** [comment]
Am 08.03.2015 um 18:38 schrieb Frank Noe:
> It's not obvious to me how to run all pyEMMA tests (API+IMPL). Please
> document this at the development page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/102>.
>
There are several ways:

1. python setup.py test
2. run nosetests in pyemma dir
3. execute individual tests with python

Will scatch that in devel docs.
