### ISSUE TITLE
Please check for correctness

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#103]
In pyemma.msm.analysis.dense.pcca_test, please check if this way of storing a test file and referencing it is correct:
        P = np.loadtxt('./pyemma/msm/analysis/tests/P_rev_251x251.dat')

since this is a local directory, it depends from where you run the tests. I have assumed that they are run from the pyemma main directory, but I'm not sure.

**Comment by marscher** [comment]
Am 08.03.2015 um 18:41 schrieb Frank Noe:
> In pyemma.msm.analysis.dense.pcca_test, please check if this way of
> storing a test file and referencing it is correct:
> P = np.loadtxt('./pyemma/msm/analysis/tests/P_rev_251x251.dat')
>
> since this is a local directory, it depends from where you run the
> tests. I have assumed that they are run from the pyemma main directory,
> but I'm not sure.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/103>.
>

relative paths are problematic. We used the __file__ attribute to get 
path from location of the module, which uses the file.

**Comment by franknoe** [comment]
thanks, done.
