### ISSUE TITLE
Expose only API functions

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#104]
Is it possible to expose only functions that are supposed to be api functions? For example, in ipython it's possible to do

import pyemma.msm.analysis as msmana

and then

msmana.dense.pcca.opt_soft(...)

etc. But that is supposed to be an implementation function that should not be visible to the user. In the API function we ensure that impl functions are called with meaningful inputs, but if we expose everything, we would have to check everything at every level. 

Can we hide functions like these and expose only API functions?

**Comment by marscher** [comment]
API functions are exposed over the __all__ variable, which means that 
those functions are "visible". If we really want to hide the impl, we 
would need to import them in the actual API function, which is not 
supposed to be efficient.

But we can do an alias import in the api module like this:

     import dense as _dense

so it is clear that this is impl detail and shall not be used directly.

**Comment by franknoe** [comment]
Would it help to import locally (in the function the submodule is used) and/or only import the function that is needed?

**Comment by trendelkampschroer** [comment]
Hi,

I strongly vote against trying to hide stuff by force. As marscher said, what you put in __all__ is what the user is supposed to safely use. 

I would not import stuff locally in functions if it can be avoided. I personally think it makes code unreadable and harder to maintain. As marscher said it can also be inefficient. 

There is no way to make things truly private in python anyway. I think if we take care of populating the namespace correctly by using __all__ correctly than any user who decides to import something from below API-level is doing it at his own risk. 

We only document API-functions anyway so a user who reads the docs should automatically be pointed to the right import for the task he wants to achieve.

**Comment by franknoe** [comment]
Yes, but most people seem to explore+use pyEMMA trough ipython, so what 
is shown in autocomplete is what people think they should use. And that 
should be minimally confusing. I definitely do not want to expose all 
functions to the outside. Some functions in e.g. the pcca module are 
only meant to be used from inside. If we exposed everything there would 
be no difference between Impl and API.

So, let's use the all = [...] and underscore names for modules that 
shouldn't be used. I think this solves the problem for the ipython users.

Thanks
Frank.



Am 09/03/15 um 09:59 schrieb Benjamin Trendelkamp-Schroer:
>
> Hi,
>
> I strongly vote against trying to hide stuff by force. As marscher 
> said, what you put in *all* is what the user is supposed to safely use.
>
> I would not import stuff locally in functions if it can be avoided. I 
> personally think it makes code unreadable and harder to maintain. As 
> marscher said it can also be inefficient.
>
> There is no way to make things truly private in python anyway. I think 
> if we take care of populating the namespace correctly by using *all* 
> correctly than any user who decides to import something from below 
> API-level is doing it at his own risk.
>
> We only document API-functions anyway so a user who reads the docs 
> should automatically be pointed to the right import for the task he 
> wants to achieve.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/104#issuecomment-77818992>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
https://github.com/ipython/ipython/issues/70/ It seems Ipython does not respect __all__, but only hides names which begin with an underscore...

**Comment by marscher** [comment]
as i've discussed with Ben, we have noticed that literally all impl modules also needed to be renamed to the underscore pattern. The question remains if that is really necessary, since it should be clear only to use documented functions

**Comment by franknoe** [comment]
I think it's necessary - otherwise we don't need the api.
This only involves changes in the API modules and there are only a few 
of them.

Am 09/03/15 um 14:26 schrieb Martin K. Scherer:
>
> as i've discussed with Ben, we have noticed that literally all impl 
> modules also needed to be renamed to the underscore pattern. The 
> question remains if that is really necessary, since it should be clear 
> only to use documented functions
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/104#issuecomment-77852163>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
> This only involves changes in the API modules and there are only a few
> of them.

No, autocomplete will also list impl modules, so its not that simple.
