### ISSUE TITLE
Guille's clustering bug

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#106]
Guille tried to cluster trajectories in-memory with nonuniform trajectory lengths. This led to an error. Try to reproduce and fix.

**Comment by gph82** [comment]
IndexError                                Traceback (most recent call last)
<ipython-input-8-876ed8cc36a5> in <module>()
----> 1 pyemma.coordinates.regspace(chi_cont_trajs_M, dmin=5.)

/home/guille/anaconda/lib/python2.7/site-packages/pyEMMA-1.1.1-py2.7-linux-x86_64.egg/pyemma/coordinates/api.pyc in regspace(data, dmin)
    206     res = RegularSpaceClustering(dmin)
    207     if data is not None:
--> 208         inp = DataInMemory(data)
    209         res.data_producer = inp
    210         res.parametrize()

/home/guille/anaconda/lib/python2.7/site-packages/pyEMMA-1.1.1-py2.7-linux-x86_64.egg/pyemma/coordinates/io/data_in_memory.pyc in __init__(self, _data)
     36             # ensure all trajs have same dim
     37             ndims = np.fromiter(([np.shape(_data[i])[1]
---> 38                                   for i in xrange(len(_data))]), dtype=int)
     39             ndim_eq = ndims == np.shape(_data[0][1])
     40             if not np.all(ndim_eq):

IndexError: tuple index out of range

**Comment by marscher** [comment]
@gph82 need the shape of the input data to get a clue whats going on

**Comment by gph82** [comment]
np.shape(chi_cont_trajs_M)
(163,)

is a list of arrays
Here's a small example that also fails:
test_array = ( np.array([1,2,3,4,5]), 
                      np.array([6,7,8,9]))

**Comment by marscher** [comment]
this used to be an error in DataInMemory, which is now fixed
