### ISSUE TITLE
Publishing release notes

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#107]
Can we automatically publish a list of bugfixes with issue/links with every release?
I've seen such lists in other software, and probably they are not manually generated.

**Comment by marscher** [comment]
It would be really great to have this. While developing on JPype, we've 
done this manually (having a CHANGELOG file in repo). If we would like 
to generate this manually, we would need to annotate the release (or 
version) tag with a good summary of what have been changed.

We should also discuss whether to have only a developer changelog and/or 
have release notes (release tag annotation).

**Comment by franknoe** [comment]
OK, I'm fine with a changelog for now. Is it standard markdown?

Am 08/03/15 um 20:26 schrieb Martin K. Scherer:
> It would be really great to have this. While developing on JPype, we've
> done this manually (having a CHANGELOG file in repo). If we would like
> to generate this manually, we would need to annotate the release (or
> version) tag with a good summary of what have been changed.
>
> We should also discuss whether to have only a developer changelog and/or
> have release notes (release tag annotation).
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/107#issuecomment-77769093>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 08.03.2015 um 20:41 schrieb Frank Noe:
> OK, I'm fine with a changelog for now. Is it standard markdown?

it can literally have any format, but I would suggest using markdown.

https://github.com/originell/jpype/blob/master/doc/CHANGELOG.rst

**Comment by franknoe** [comment]
OK, I've started one for the forthcoming release.
