### ISSUE TITLE
'finding connected set' progress bar not properly removed

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/PyEMMA#1098]
The progress bar shown for finding the connected set in a TRAM estimation is not properly removed after the estimation terminates.

**Comment by marscher** [comment]
Does the progress bar created updates until all the registered work steps are really performed. If it converges prior to that point, you have to call progress_bar._progress_force_finish(step="whatever_you_have_registered_before")

**Comment by marscher** [comment]
Is this a release blocker or not?

**Comment by fabian-paul** [comment]
This is only cosmetic,  so no release blocker.
Is it safe to call progress_bar._progress_force_finish(step="whatever_you_have_registered_before") even if the progess bar has already grown to its maximum value? That is, can I just add this call before the function finishes?
