### ISSUE TITLE
msm.ui module is untested

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#110]

**Comment by franknoe** [comment]
Added some tests for its.
Some test cases will need to wait for refactoring of the high-level API (see other issues)

**Comment by franknoe** [comment]
Added quite exhaustive tests for msm.
Nonreversible estimation is still untested.

**Comment by franknoe** [comment]
Extended Ben's cktest.
Together with Ben's other tests, I consider this (general) issue to be done. A few more specific issues remain that will be dealt with separately.
