### ISSUE TITLE
dtram problem

### ISSUE THREAD

**Issue by giopina** [markovmodel/PyEMMA#1110]
In the latest github version ('2.4+18.g5a95a0f') the dtram function uses by default connectivity='reversible_pathways', which apparently is not available for dtram.
The following is the output error
<details>
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-42-9fa2475b2dca> in <module>()
----> 1 get_ipython().magic('time dtram_prova2=thermo.dtram(thermo_list,dtrajs_sf+dtrajs_us,                               state_bias,lag=20,save_convergence_info=1,maxiter=100000)')

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2156         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2157         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2158         return self.run_line_magic(magic_name, magic_arg_s)
   2159 
   2160     #-------------------------------------------------------------------------

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2077                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2078             with self.builtin_trap:
-> 2079                 result = fn(*args,**kwargs)
   2080             return result
   2081 

<decorator-gen-59> in time(self, line, cell, local_ns)

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/IPython/core/magics/execution.py in time(self, line, cell, local_ns)
   1183         else:
   1184             st = clock2()
-> 1185             exec(code, glob, local_ns)
   1186             end = clock2()
   1187             out = None

<timed exec> in <module>()

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/pyEMMA-2.4+18.g5a95a0f-py3.6-linux-x86_64.egg/pyemma/thermo/api.py in dtram(ttrajs, dtrajs, bias, lag, unbiased_state, count_mode, connectivity, maxiter, maxerr, save_convergence_info, dt_traj, init, init_maxiter, init_maxerr)
    886             maxiter=maxiter, maxerr=maxerr, save_convergence_info=save_convergence_info,
    887             dt_traj=dt_traj, init=init, init_maxiter=init_maxiter,
--> 888             init_maxerr=init_maxerr).estimate((ttrajs, dtrajs)) for _lag in lags]
    889     _assign_unbiased_state_label(dtram_estimators, unbiased_state)
    890     # return

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/pyEMMA-2.4+18.g5a95a0f-py3.6-linux-x86_64.egg/pyemma/thermo/api.py in <listcomp>(.0)
    886             maxiter=maxiter, maxerr=maxerr, save_convergence_info=save_convergence_info,
    887             dt_traj=dt_traj, init=init, init_maxiter=init_maxiter,
--> 888             init_maxerr=init_maxerr).estimate((ttrajs, dtrajs)) for _lag in lags]
    889     _assign_unbiased_state_label(dtram_estimators, unbiased_state)
    890     # return

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/pyEMMA-2.4+18.g5a95a0f-py3.6-linux-x86_64.egg/pyemma/thermo/estimators/DTRAM_estimator.py in estimate(self, trajs)
    182 
    183         """
--> 184         return super(DTRAM, self).estimate(trajs)
    185 
    186     def _estimate(self, trajs):

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/pyEMMA-2.4+18.g5a95a0f-py3.6-linux-x86_64.egg/pyemma/_base/estimator.py in estimate(self, X, **params)
    367         if params:
    368             self.set_params(**params)
--> 369         self._model = self._estimate(X)
    370         self._estimated = True
    371         return self

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/pyEMMA-2.4+18.g5a95a0f-py3.6-linux-x86_64.egg/pyemma/thermo/estimators/DTRAM_estimator.py in _estimate(self, trajs)
    207         C_sum = self.count_matrices_full.sum(axis=0)
    208         # TODO: use improved cset
--> 209         _, cset = _cset.compute_csets_dTRAM(self.connectivity, self.count_matrices_full)
    210         self.active_set = cset
    211         # correct counts

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/thermotools/cset.py in compute_csets_dTRAM(connectivity, count_matrices, nn, callback)
    195     state_counts =  _np.maximum(count_matrices.sum(axis=1), count_matrices.sum(axis=2))
    196     return _compute_csets(
--> 197         connectivity, state_counts, count_matrices, None, None, None, nn=nn, callback=callback)
    198 
    199 def _overlap_BAR_variance(a, b, factor=1.0):

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma-devel/lib/python3.6/site-packages/thermotools/cset.py in _compute_csets(connectivity, state_counts, count_matrices, ttrajs, dtrajs, bias_trajs, nn, equilibrium_state_counts, factor, callback)
    344             'Unknown value "%s" of connectivity. Should be one of: \
    345             summed_count_matrix, strong_in_every_ensemble, neighbors, \
--> 346             post_hoc_RE or BAR_variance.' % connectivity)
    347 
    348 def restrict_to_csets(

Exception: Unknown value "reversible_pathways" of connectivity. Should be one of:             summed_count_matrix, strong_in_every_ensemble, neighbors,             post_hoc_RE or BAR_variance.
</details>

**Comment by fabian-paul** [comment]
You have to update thermotools.

**Comment by giopina** [comment]
Ok I solved it. It was actually a problem of conflicts between different versions.
