### ISSUE TITLE
Specify weights as arrays in TICA + LaggedCovariance

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#1113]
We need the ability to specify weights as an available weight array or list of arrays in TICA + LaggedCovariance. I thought we had decided to do that but it now seems that it's only possible to have constant weights or weights that can be computed as a function like ``weights(X)``. However, in some cases weights cannot be computed like this. For example, when the weighting comes from Metadynamics, the weight is a function of the timestep, but not of ``X``. 

It seems like a simple request, but I'm not sure how to marry it with the case that the data itself is being streamed in chunks. Suggestions?

Pinging @fnueske, @marscher and @fabian-paul .

**Comment by fabian-paul** [comment]
I think, we had a solution for this: https://github.com/markovmodel/PyEMMA/issues/1060#issuecomment-288060766 We just have to put this into pyemma. Maybe into the tica api function?

**Comment by marscher** [comment]
On 06/04/2017 09:46 AM, fabian-paul wrote:
> I think, we had a solution for this: #1060 (comment)
> <https://github.com/markovmodel/PyEMMA/issues/1060#issuecomment-288060766>
> We just have to put this into pyemma. Maybe into the tica api function?
Actually this is already released, isn't it?

**Comment by franknoe** [comment]
OK, I see. That would work now, but it's workaround, not a solution. This usage makes assumptions about how the estimator works internally. The meaning of the weights(X) function is to translate X into weights by a function F(X). You're creating a class with an internal state that assumes the estimators iterates along the trajectory and calls every X only once. There is no guarantee for that in general. If we want time-ordered weights you have to be able to specify the entire weight trajectory or pass the weights along with the data or add time information to the weights.

**Comment by marscher** [comment]
okay I see your point. I'll add a PR for this.

**Comment by marscher** [comment]
I think this one is a bit tricky to implement for partial_fit, because in this case we don't have a time information. But in general it is possible. I would wrap the given weights list in a class I've just proposed. This of course assumes again, that every chunk will be passed only once and in linear time. I think we make this assumption internally in LaggedCovariance, because we pass an Iterable and consume it in a linear fashion from the beginning to the end.
