### ISSUE TITLE
A database (?) error on pyemma.coordinates.source()

### ISSUE THREAD

**Issue by rafwiewiora** [markovmodel/PyEMMA#1119]
Hit a problem while trying to do k-means on my TICA-projected trajs, `pyemma.coordinates.source(glob.glob('*.npy'))` errors, while it worked perfectly ok on the featurized trajs (arrays are even same dimensions, keeping all TICs). 

Here's the error:
```python
In [108]: source = pyemma.coordinates.source(glob.glob('*.npy'))
Obtaining file info:   1% (  76/5020) [#                                                                             ] eta 03:02 |13-06-17 12:58:31 pyemma.coordinates.data.util.traj_info_cache INFO     Cleaning database because it has too much entries or is too large.
Entries: 50084. Size: 24.15MB. Configured max_entires: 50000. Max_size: 500MB
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/traj_info_cache.py in __getitem__(self, filename_reader_tuple)
    186         try:
--> 187             info = self._database.get(key)
    188             if not isinstance(info, TrajInfo):

/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/traj_info_backends.py in get(self, key)
    222         if not row:
--> 223             raise KeyError()
    224         info = self._create_traj_info(row)

KeyError: 

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
<ipython-input-108-9d3c8ffd8f2f> in <module>()
----> 1 source = pyemma.coordinates.source(glob.glob('*.npy'))

/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/api.py in source(inp, features, top, chunk_size, **kw)
    346             isinstance(inp, (list, tuple))
    347             and (any(isinstance(item, (list, tuple, _string_types)) for item in inp) or len(inp) is 0)):
--> 348         reader = create_file_reader(inp, top, features, chunk_size=chunk_size if chunk_size is not None else 100, **kw)
    349 
    350     elif isinstance(inp, _np.ndarray) or (isinstance(inp, (list, tuple))

/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/reader_utils.py in create_file_reader(input_files, topology, featurizer, chunk_size, **kw)
    103                 else:
    104                     if suffix in ['.npy', '.npz']:
--> 105                         reader = NumPyFileReader(input_list, chunksize=chunk_size)
    106                     # otherwise we assume that given files are ascii tabulated data
    107                     else:

/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/numpy_filereader.py in __init__(self, filenames, chunksize, mmap_mode)
     62 
     63         self.mmap_mode = mmap_mode
---> 64         self.filenames = filenames
     65 
     66     def _create_iterator(self, skip=0, chunk=0, stride=1, return_trajindex=False, cols=None):

/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/datasource.py in filenames(self, filename_list)
    114             for filename in filename_list:
    115                 if config.use_trajectory_lengths_cache:
--> 116                     info = TrajectoryInfoCache.instance()[filename, self]
    117                 else:
    118                     info = self._get_traj_info(filename)

/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/traj_info_cache.py in __getitem__(self, filename_reader_tuple)
    204             info.abs_path = abs_path
    205             # store info in db
--> 206             self.__setitem__(info)
    207 
    208             # save forcefully now

/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/traj_info_cache.py in __setitem__(self, traj_info)
    245 
    246     def __setitem__(self, traj_info):
--> 247         self._database.set(traj_info)
    248 
    249     def clear(self):

/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/traj_info_backends.py in set(self, traj_info)
    215                             % (self.num_entries, (current_size*1.0 / 1024**2),
    216                                config.traj_info_max_entries, config.traj_info_max_size))
--> 217                 self._clean(n=self.clean_n_entries)
    218 
    219     def get(self, key):

/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/traj_info_backends.py in _clean(self, n)
    349         cur = self._database.execute(stmnt)
    350         self._database.commit()
--> 351         assert cur.rowcount == len(ids), "deleted not as many rows(%s) as desired(%s)" %(cur.rowcount, len(ids))
    352 
    353         # iterate over all LRU databases and delete those ids, we've just deleted from the main db.

AssertionError: deleted not as many rows(1) as desired(15025)
```

Interestingly, this hack makes it work:

```python
fnames = glob.glob('*.npy')

for i in np.arange(1, len(fnames)):                   
    try:
        source = pyemma.coordinates.source(fnames[0:i])
    except:
        source = pyemma.coordinates.source(fnames[0:i])
```

(i.e keep making the list of files longer by one and repeat when it fails) - I tried this once, started failing at 43 files, and then on every single file addition if fails once, works another time and so on:

```python
Obtaining file info:  97% (42/43) [################################################################################  ] eta 00:01 |13-06-17 12:56:33 pyemma.coordinates.data.util.traj_info_cache INFO     Cleaning database because it has too much entries or is too large.
Entries: 50057. Size: 24.15MB. Configured max_entires: 50000. Max_size: 500MB
Obtaining file info:  97% (43/44) [################################################################################  ] eta 00:01 -13-06-17 12:56:35 pyemma.coordinates.data.util.traj_info_cache INFO     Cleaning database because it has too much entries or is too large.
(...)
```

Only got it up to 88 files now, and keeps doing this fail-work pattern. I think I'm going to try running with this hack on all 5020 trajectories and seeing if that works (EDIT: this of course turned out to take way too much time to be reasonable) and if I can get those k-means running asap.

**Comment by rafwiewiora** [comment]
A quick thought - the very first k-means job I run earlier today worked ok, but all further ones failed with this error. When I try to re-run on the trajectories that the first job worked on - it fails now too (although this is convoluted by a fact that in the progress of trying to figure this out I also re-made the TICA projected trajectories). And it seems like there's some database somewhere that should've been erased but wasn't? I tried removing PyEMMA and re-installing - same error - but maybe just removing PyEMMA doesn't remove that database which is sitting somewhere else?

**Comment by rafwiewiora** [comment]
I should also mention a potentially related database problem. Last week I was doing TICA with many parameter choices, on many featurization choices - i.e. a lot of jobs running at the same time. Many of those were failing with:

```python
  File "dist_time_tica.py", line 11, in <module>
    source = pyemma.coordinates.source(glob.glob('../data_cut_start_noH_stride10_featurized/dist_time_soft/*/*.npy'))
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/api.py", line 348, in source
    reader = create_file_reader(inp, top, features, chunk_size=chunk_size if chunk_size is not None else 100, **kw)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/reader_utils.py", line 105, in create_file_reader
    reader = NumPyFileReader(input_list, chunksize=chunk_size)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/numpy_filereader.py", line 64, in __init__
    self.filenames = filenames
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/datasource.py", line 116, in filenames
    info = TrajectoryInfoCache.instance()[filename, self]
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/traj_info_cache.py", line 187, in __getitem__
    info = self._database.get(key)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/traj_info_backends.py", line 225, in get
    self._update_time_stamp(key)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/util/traj_info_backends.py", line 272, in _update_time_stamp
    conn.execute("update usage set last_read=? where hash=?", (time.time(), hash_value))
sqlite3.OperationalError: database is locked
```

which seemed to be caused by two jobs starting at exactly the same time and trying to access this database at the same time? (at least some of them would have probably been running on the same cluster nodes). After I re-run those jobs, and let the first one finish going through the `pyemma.coordinates.source` before starting more - everything works ok.

**Comment by franknoe** [comment]
I see. The database stores trajectory indexing information, so it's supposed to reduce runtimes whenever you read a trajectory more than once. However it's also supposed to be failsafe and fall back to default behavior whenever connection fails. Thanks for reporting this and please work with @marscher to resolve it. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by jchodera** [comment]
@rafwiewiora: Were you also attempting to have multiple instances of pyemma run concurrently when this happened?

**Comment by rafwiewiora** [comment]
> @rafwiewiora: Were you also attempting to have multiple instances of pyemma run concurrently when this happened?

Yes - the job that was started as the first one worked, all others (in fact I had 40 jobs that should have been running then) failed after short time running with the error reported.

`rm -rf ~/.pyemma` appears to have helped - I just started one job which is running without error, will see if more jobs will work ok.

**Comment by rafwiewiora** [comment]
> The database stores trajectory indexing information, so it's supposed to reduce runtimes whenever you read a trajectory more than once.

To this I should mention that my featurized and my TICA-projected trajectories have the same names: integers between 0-5020 + .npy, maybe that causes problems too.

**Comment by rafwiewiora** [comment]
I and @jchodera wonder: is there some environmental variable to set different pyemma instances to use a different temp folder / database, to avoid all of these problems?

**Comment by marscher** [comment]
There is indeed the option to set a temporary (or permanent) configuration directory by setting PYEMMA_CFG_DIR to an existing directory. But since it is undocumented, please don't expect it to work as expected (at least you will get an error, if the dir is not existent).

May I ask how many jobs you are using concurrently? Sqlite allows only for one job to write to the database at the same time. If there are many, the write queue will be long. Sqlite itself tries a couple of times to obtain the exclusive lock and then die happily.

The first stack trace you've posted is related to the fact that you've successfully (more or less...) processed 50000 distinct trajectories - congrats!

Actually the behaviour of of hitting this limit is tested (max_trajectory_entries). I think this triggered assertion is some debug leftover, which can be safely removed. In any case the cleaning operation of the database is a costly operation (in terms of runtime and IO effort), which accumulates in case of many workers, which will all trigger the cleanup (there is no way around it, without a server process).

So I suggest to share a cfg directory for only a couple of workers (eg. 20-50 should be fine) and to increase the database size.

**Comment by marscher** [comment]
btw @rafwiewiora if you find the time, could you please have a look at your requested feature in #1106?

**Comment by rafwiewiora** [comment]
Ok, so `rm -rf ~/.pyemma` resolved the 50000 trajectories problem - how do I increase the database size though?

I thought the problem with some jobs failing if many run at the same time was that they were starting at the exact same time and at the same point accessing the database - but from the failures I saw again with this approach: (all failing with `sqlite3.OperationalError: database is locked`)

```
-bash-4.1$ qstat -u rafal.wiewiora

hal-sched1.local: 
                                                                                  Req'd    Req'd       Elap
Job ID                  Username    Queue    Jobname          SessID  NDS   TSK   Memory   Time    S   Time
----------------------- ----------- -------- ---------------- ------ ----- ------ ------ --------- - ---------
8627576.hal-sched1.loc  rafal.wiewi batch    dist_cross_tica   57772     1      1   20gb 144:00:00 R  97:20:00
8634457.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        85293     1     16   20gb 144:00:00 C       -- 
8634458.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        23037     1     16   20gb 144:00:00 C       -- 
8634459.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        85382     1     16   20gb 144:00:00 R  00:25:47
8634460.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        23115     1     16   20gb 144:00:00 C       -- 
8634461.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        85694     1     16   20gb 144:00:00 C       -- 
8634462.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        24550     1     16   20gb 144:00:00 R  00:21:19
8634463.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        11864     1     16   20gb 144:00:00 C       -- 
8634464.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        31914     1     16   20gb 144:00:00 C       -- 
8634465.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        18271     1     16   20gb 144:00:00 C       -- 
8634466.hal-sched1.loc  rafal.wiewi batch    dih_kmeans         2758     1     16   20gb 144:00:00 R  00:19:10
8634467.hal-sched1.loc  rafal.wiewi batch    dih_kmeans         5000     1     16   20gb 144:00:00 C       -- 
8634468.hal-sched1.loc  rafal.wiewi batch    dih_kmeans         8317     1     16   20gb 144:00:00 C       -- 
8634469.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        18393     1     16   20gb 144:00:00 C       -- 
8634470.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        20834     1     16   20gb 144:00:00 R  00:16:51
8634471.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        19457     1     16   20gb 144:00:00 R  00:16:20
8634472.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        21294     1     16   20gb 144:00:00 C       -- 
8634473.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        32242     1     16   20gb 144:00:00 C       -- 
8634474.hal-sched1.loc  rafal.wiewi batch    dih_kmeans         5502     1     16   20gb 144:00:00 R  00:14:30
8634476.hal-sched1.loc  rafal.wiewi batch    dih_kmeans        12612     1     16   20gb 144:00:00 C       -- 
```

Before this I see a very long ETA for the `pyemma.coordinates.source()`:
```
-bash-4.1$ tail -f dih_kmeans.o8634458
Obtaining file info:  86% (4356/5020) [########################    ] eta 29:35 |^C
-bash-4.1$ tail -f dih_kmeans.o8634459
Obtaining file info:  81% (4074/5020) [######################      ] eta 39:09 -^C
-bash-4.1$ tail -f dih_kmeans.o8634476
Obtaining file info:   0% (  25/5020) [                          ] eta 2:56:22 /^C
```

All this now makes sense after reading your reply @marscher.

so it seems like what I really need to do is to wait until a previous job has finished the `pyemma.coordinates.source()` before starting a next one?

**Comment by rafwiewiora** [comment]
One more question:
> share a cfg directory for only a couple of workers (eg. 20-50 should be fine)

Would doing a cfg directory per every single worker be a good idea so no workers have to wait in the queue / potentially fail?

**Comment by marscher** [comment]
On 13.06.2017 22:12, Rafal Wiewiora wrote:
> Ok, so |rm -rf ~/.pyemma| resolved the 50000 trajectories problem - how 
> do I increase the database size though?
http://www.emma-project.org/latest/Configuration.html#pyemma.util._config.Config.traj_info_max_entries

pyemma.config.save()
> 
> I thought the problem with some jobs failing if many run at the same 
> time was that they were starting at the exact same time and at the same 
> point accessing the database - but from the failures I saw again with 
> this approach: (all failing with |sqlite3.OperationalError: database is 
> locked|)
Yes, but the database will be locked even for a longer time, if the 
capacity is reached.
> 
> |-bash-4.1$ qstat -u rafal.wiewiora hal-sched1.local: Req'd Req'd Elap 
> Job ID Username Queue Jobname SessID NDS TSK Memory Time S Time 
> ----------------------- ----------- -------- ---------------- ------ 
> ----- ------ ------ --------- - --------- 8627576.hal-sched1.loc 
> rafal.wiewi batch dist_cross_tica 57772 1 1 20gb 144:00:00 R 97:20:00 
> 8634457.hal-sched1.loc rafal.wiewi batch dih_kmeans 85293 1 16 20gb 
> 144:00:00 C -- 8634458.hal-sched1.loc rafal.wiewi batch dih_kmeans 23037 
> 1 16 20gb 144:00:00 C -- 8634459.hal-sched1.loc rafal.wiewi batch 
> dih_kmeans 85382 1 16 20gb 144:00:00 R 00:25:47 8634460.hal-sched1.loc 
> rafal.wiewi batch dih_kmeans 23115 1 16 20gb 144:00:00 C -- 
> 8634461.hal-sched1.loc rafal.wiewi batch dih_kmeans 85694 1 16 20gb 
> 144:00:00 C -- 8634462.hal-sched1.loc rafal.wiewi batch dih_kmeans 24550 
> 1 16 20gb 144:00:00 R 00:21:19 8634463.hal-sched1.loc rafal.wiewi batch 
> dih_kmeans 11864 1 16 20gb 144:00:00 C -- 8634464.hal-sched1.loc 
> rafal.wiewi batch dih_kmeans 31914 1 16 20gb 144:00:00 C -- 
> 8634465.hal-sched1.loc rafal.wiewi batch dih_kmeans 18271 1 16 20gb 
> 144:00:00 C -- 8634466.hal-sched1.loc rafal.wiewi batch dih_kmeans 2758 
> 1 16 20gb 144:00:00 R 00:19:10 8634467.hal-sched1.loc rafal.wiewi batch 
> dih_kmeans 5000 1 16 20gb 144:00:00 C -- 8634468.hal-sched1.loc 
> rafal.wiewi batch dih_kmeans 8317 1 16 20gb 144:00:00 C -- 
> 8634469.hal-sched1.loc rafal.wiewi batch dih_kmeans 18393 1 16 20gb 
> 144:00:00 C -- 8634470.hal-sched1.loc rafal.wiewi batch dih_kmeans 20834 
> 1 16 20gb 144:00:00 R 00:16:51 8634471.hal-sched1.loc rafal.wiewi batch 
> dih_kmeans 19457 1 16 20gb 144:00:00 R 00:16:20 8634472.hal-sched1.loc 
> rafal.wiewi batch dih_kmeans 21294 1 16 20gb 144:00:00 C -- 
> 8634473.hal-sched1.loc rafal.wiewi batch dih_kmeans 32242 1 16 20gb 
> 144:00:00 C -- 8634474.hal-sched1.loc rafal.wiewi batch dih_kmeans 5502 
> 1 16 20gb 144:00:00 R 00:14:30 8634476.hal-sched1.loc rafal.wiewi batch 
> dih_kmeans 12612 1 16 20gb 144:00:00 C -- |
> 
> Before this I see a very long ETA for the |pyemma.coordinates.source()|:
> 
> |-bash-4.1$ tail -f dih_kmeans.o8634458 Obtaining file info: 86% 
> (4356/5020) [######################## ] eta 29:35 |^C -bash-4.1$ tail -f 
> dih_kmeans.o8634459 Obtaining file info: 81% (4074/5020) 
> [###################### ] eta 39:09 -^C -bash-4.1$ tail -f 
> dih_kmeans.o8634476 Obtaining file info: 0% ( 25/5020) [ ] eta 2:56:22 /^C |
> 
> so it seems like what I really need to do is to wait until a previous 
> job has finished the |pyemma.coordinates.source()| before starting a 
> next one?
No actually not, one job reads/writes to the database, then frees the 
lock immediately. I've only tested this with < 20 jobs.

You can also disable this caching feature completely (see the config 
documentation).

In principal there is no good workaround other than what I've already 
pointed out.

**Comment by marscher** [comment]
On 13.06.2017 22:18, Rafal Wiewiora wrote:
> One more question:
> 
>     share a cfg directory for only a couple of workers (eg. 20-50 should
>     be fine)
> 
> Would doing a cfg directory per every single worker be a good idea so no 
> workers have to wait in the queue / potentially fail?
this would be absolutely fail safe, but no speed up will be gained (eg. 
every worker has to read in the files again, which will also cause the 
file system to block).

**Comment by rafwiewiora** [comment]
Thanks @marscher! Now I get what this does finally. So let me just write out exactly what I was doing (sorry I didn't reply above about how many jobs I had). I had two cases:

1) 5 featurization choices / 5 sets of trajs - do 20 choices of TICA parameters per each - so 100 jobs total - as far as I remember I tried to run maybe up to 40 if not 50 at the same time, when some of them failed with `sqlite3.OperationalError: database is locked` - so I'm guessing this was just too many jobs at the same time?

2) What I was doing today - for just 1 of the 5 featurization choices - but that is 20 separate sets of trajectories (20 TICA parameter choices, 20 x 5020 trajs) - 20 k-means jobs at the same time. So the caching can't help here at all - none of the trajectory sets are used by more than one worker. Switched the caching off - works like a dream.

**Comment by marscher** [comment]
I think we have sorted this out. The file based database can not handle that many concurrent jobs. The options are either to turn of caching completely or using separate configuration directories for a subset of jobs (< 20).

**Comment by franknoe** [comment]
I don't think it's sorted out, because it seems impossible for anybody running into this problem to sort it out without asking us. I would consider it sorted out once we have documented the solution in some place that can be found by a non-expert, or turning off database usage is made simple. @rafwiewiora , do you have a suggestion for what solution would work from an informed-user-but-not-developer perspective? 
Alternatively - and that would be my preferred solution - the database should be robust to failures like this. I.e. if running into an exception it should simply go back to default behavior and open files as normal.

**Comment by jchodera** [comment]
>  if running into an exception it should simply go back to default behavior and open files as normal.

That does sound like a great fallback solution!

**Comment by rafwiewiora** [comment]
> >if running into an exception it should simply go back to default behavior and open files as normal.
That does sound like a great fallback solution!

Agreed. 

How about a short section in the Docs on 'multiprocessing' - info about the existence of this database + anything else one should know before running many instances of PyEMMA? That way I would have definitely known this before running into the problem I think.

**Comment by marscher** [comment]
On 06/16/2017 05:20 PM, Rafal Wiewiora wrote:
>         if running into an exception it should simply go back to default
>         behavior and open files as normal.
>         That does sound like a great fallback solution!
> 
> Agreed.
> 
> How about a short section in the Docs on multiprocessing - info about
> the existence of this database + anything else one should know before
> running many instances of PyEMMA.
how about you open up a PR on that, since you seem to be the user with
the most pyemma multiprocessing experience?

In principle things should work out of the box... #1112 improves this
assumption.


I'd be happy if you could re-run one of your jobs (eg. only the creation
of the source:

conda create -n test_failsafe_lru pyemma
source activate test_failsafe_lru
# inst proposed change
pip install git+https://github.com/marscher/pyemma@trajdb_failsafe

**Comment by rafwiewiora** [comment]
Alright will do both!
