### ISSUE TITLE
TRAM error message: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by giopina** [markovmodel/PyEMMA#1132]
I'm getting the following error message when calling pyemma.thermo.estimate_umbrella_sampling(...)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-318-1e04cbb7f93c> in <module>()
----> 1 wham_obj=thermo.estimate_umbrella_sampling([tr[:,0] for tr in traj_usb]+[tr[:,0] for tr in traj_usx],                                 cl_obj.dtrajs,us_centers=[u for u in umbrella_centers[:54]]*2,                                  us_force_constants=[5.0]*108,kT=0.96,save_convergence_info=1,                                 estimator='wham')

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma/lib/python3.6/site-packages/pyemma/thermo/api.py in estimate_umbrella_sampling(us_trajs, us_dtrajs, us_centers, us_force_constants, md_trajs, md_dtrajs, kT, maxiter, maxerr, save_convergence_info, estimator, lag, dt_traj, init, init_maxiter, init_maxerr, width, **kwargs)
    234     # data preparation
    235     ttrajs, btrajs, umbrella_centers, force_constants, unbiased_state = _get_umbrella_sampling_data(
--> 236         us_trajs, us_centers, us_force_constants, md_trajs=md_trajs, kT=kT, width=width)
    237     estimator_obj = None
    238     # estimation

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma/lib/python3.6/site-packages/pyemma/thermo/util/util.py in get_umbrella_sampling_data(us_trajs, us_centers, us_force_constants, md_trajs, kT, width)
    273         raise ValueError('Unmatching number of width components.')
    274     btrajs = _get_umbrella_bias_sequences(
--> 275         us_trajs + md_trajs, umbrella_centers, force_constants, width)
    276     return ttrajs, btrajs, umbrella_centers, force_constants, unbiased_state
    277 

/group/ag_cmb/scratch/giopina/software/miniconda/envs/pyemma/lib/python3.6/site-packages/pyemma/thermo/util/util.py in _get_umbrella_bias_sequences(trajs, umbrella_centers, force_constants, width)
    216                 i, traj.shape[1], dimension))
    217         bias_sequences.append(
--> 218             _get_umbrella_bias(traj, umbrella_centers, force_constants, width))
    219     return bias_sequences
    220 

ext/util/util.pyx in util.get_umbrella_bias (ext/util/util.c:6456)()

ValueError: ndarray is not C-contiguous

**Comment by giopina** [comment]
I manage to get rid of the error message.

Here's what I did:
**old code:**
`thermo.estimate_umbrella_sampling(us_trajs= [ tr[:,0] for tr in traj_usb], ... )`
**new code:**
`thermo.estimate_umbrella_sampling(us_trajs= [ np.array(tr[:,0],dtype=np.double) for tr in traj_usb], ... )`

Maybe this can be useful for other users

**Comment by fabian-paul** [comment]
Let's replace line
https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/thermo/util/util.py#L218
by
bias_sequences.append(
   np.require(traj, requirements='C')
   np.require(umbrella_centers, requirements='C')
   np.require(force_constants, requirements='C')
   np.require(width, requirements='C')
)

**Comment by marscher** [comment]
this will of course work, but it will also double the memory requirements for the data, if it is passed as single precision. This could potentially blow the memory, so I would suggest to force the user to pass double precision data, if it is a requirement, to avoid this "silent" source of failure.
