### ISSUE TITLE
energy_trajs for estimate_multi_temperature

### ISSUE THREAD

**Issue by liyigerry** [markovmodel/PyEMMA#1138]
I try to use estimate_multi_temperature to analysis trajectories generated from high temperature simulation using Gromacs.

I notice this function requires potential energy by parameter energy_trajs.
Is there some ways to extract potential energy from trajectories files?

**Comment by thempel** [comment]
Gromacs can write the energy trajectory as well. If saved, it should be written to an .edr file, and you can extract it with some gromacs tools.

**Comment by marscher** [comment]
please feel free to re-open, if the answer is not sufficient.

**Comment by liyigerry** [comment]
@thempel 
I know Gromacs can print out the potential energy in .edr file.
But it seems to be the potential energy of the system consists of protein and water.

Based on my understanding, I think the potential energy of protein is needed here.
So, I specified the format of energy group, getting different interaction between protein and protein.

These different forms of potential energy seem to too large for my system, in which the free energy is about -150 kj/mol.

```
Energy                      Average   Err.Est.       RMSD  Tot-Drift
-------------------------------------------------------------------------------
Potential                -1.81635e+06         --     1449.2   -1680.54  (kJ/mol)
Coul-SR:Protein-Protein  -2.18812e+06         --    2184.31   -1142.18  (kJ/mol)
LJ-SR:Protein-Protein        261994         --    1312.53   -300.414  (kJ/mol)
Coul-14:Protein-Protein     77592.3         --    211.115    292.325  (kJ/mol)
LJ-14:Protein-Protein       7694.46         --    60.6539   -14.0125  (kJ/mol)
```

I posted this issue here to seek some other ways to extract potential energy.

**Comment by liyigerry** [comment]
@marscher I can not reopen it.

**Comment by franknoe** [comment]
Your question is a basic MD and maybe Gromacs question. This is an issuetracker for PyEMMA software questions.

Short answer: Yes, you should use the potential energy of the whole system. No, there nothing like a too large
potential energy, because the absolute value of the potential energy is undefined.

**Comment by liyigerry** [comment]
@franknoe Ok, thanks.
It means estimate_multi_temperature handle the difference of potential energy?
I will look at it.
Thanks.

**Comment by liyigerry** [comment]
@franknoe @marscher 

I try to read the reweighting [doc](http://docs.markovmodel.org/reweighting.html).
For the example 2 for parallel tempering, I think estimate_multi_temperature function can be used for high temperature simulations.

In my case, a protein was used for high temperature simualtions at 300k,373k,423k,473k,523k,573k,623k,673k,723k. Each temperature has 30ns production run.

```
tram = pyemma.thermo.estimate_multi_temperature(
    energy_trajs, temp_trajs, dtrajs,
    maxiter=25000, maxerr=1.0E-15, save_convergence_info=10,
    energy_unit='kJ/mol', temp_unit='K', estimator='tram', lag=lags,
    init='mbar', init_maxiter=5000, init_maxerr=1.0E-12)
```

I used the total energy of system as energy_trajs, clusters based on collective variables as dtrajs.

Can I handle this trajectories like this?

It runs very, very slow in my machine with 72  Intel(R) Xeon(R) CPU E5-2699 v3 @ 2.30GHz.
