### ISSUE TITLE
Change in kmeans clustering - Documentation on how to cluster?

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#114]
When and why did this stop to work?
pyemma.coordinates.clustering.kmeans (filelist, 1000, maxiter=10)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-bbc5913338b6> in <module>()
      4 #    np.savetxt(fname, traj)
      5 #    flist.append(fname)
----> 6 pyemma.coordinates.clustering.kmeans (flist, 1000, maxiter=10, )
TypeError: 'module' object is not callable

Now clustering algorithms don't work **either** in memory **nor** via files...? 

This docu does not provide examples, so I am bit lost:
http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.clustering.KmeansClustering.html#pyemma.coordinates.clustering.KmeansClustering 

Any pointers?

**Comment by franknoe** [comment]
oh my god.. please set up test cases!!!

Am 11/03/15 um 12:21 schrieb gph82:
>
> When and why did this stop to work?
>
>
>     pyemma.coordinates.clustering.kmeans (filelist, 1000, maxiter=10)
>
> TypeError Traceback (most recent call last)
> in ()
> 4 # np.savetxt(fname, traj)
> 5 # flist.append(fname)
> ----> 6 pyemma.coordinates.clustering.kmeans (flist, 1000, maxiter=10, )
> TypeError: 'module' object is not callable
>
> Now clustering algorithms don't work *either* in memory *nor* via 
> files...?
>
> This docu does not provide examples, so I am bit lost:
> http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.clustering.KmeansClustering.html#pyemma.coordinates.clustering.KmeansClustering 
>
>
> Any pointers?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/114>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
I think this is actually the old API.

now in-memory clustering would be using

     pyemma.coordinates.kmeans(data = None, k=100, maxiter=10)

For the filelist you need to constuct a pipeline object

Am 11/03/15 um 12:21 schrieb gph82:
>
> When and why did this stop to work?
>
>
>     pyemma.coordinates.clustering.kmeans (filelist, 1000, maxiter=10)
>
> TypeError Traceback (most recent call last)
> in ()
> 4 # np.savetxt(fname, traj)
> 5 # flist.append(fname)
> ----> 6 pyemma.coordinates.clustering.kmeans (flist, 1000, maxiter=10, )
> TypeError: 'module' object is not callable
>
> Now clustering algorithms don't work *either* in memory *nor* via 
> files...?
>
> This docu does not provide examples, so I am bit lost:
> http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.clustering.KmeansClustering.html#pyemma.coordinates.clustering.KmeansClustering 
>
>
> Any pointers?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/114>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Addition: please make sure that docs are up to date!

Am 11/03/15 um 12:21 schrieb gph82:
>
> When and why did this stop to work?
>
>
>     pyemma.coordinates.clustering.kmeans (filelist, 1000, maxiter=10)
>
> TypeError Traceback (most recent call last)
> in ()
> 4 # np.savetxt(fname, traj)
> 5 # flist.append(fname)
> ----> 6 pyemma.coordinates.clustering.kmeans (flist, 1000, maxiter=10, )
> TypeError: 'module' object is not callable
>
> Now clustering algorithms don't work *either* in memory *nor* via 
> files...?
>
> This docu does not provide examples, so I am bit lost:
> http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.clustering.KmeansClustering.html#pyemma.coordinates.clustering.KmeansClustering 
>
>
> Any pointers?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/114>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
the docs are updated in repository, but since the conda guys broke ipython (new major relase 3.0 is there) the docs could not be automatically be updated. I'm working on a fix.

**Comment by marscher** [comment]
http://pythonhosted.org/pyEMMA/api/coordinates.api.html now its there
