### ISSUE TITLE
pip install of devel branch on MacOSX

### ISSUE THREAD

**Issue by psolsson** [markovmodel/PyEMMA#1148]
Installing the current devel version of PyEMMA using pip install fails on my mac. There's a omp.h dependency which I cannot seem to resolve. I initially also had a pybind11 dependency which I could resolve with homebrew.

An error-dump:
[...]    
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/solsson/miniconda3/include -arch x86_64 -I/Users/solsson/miniconda3/lib/python3.5/site-packages/mdtraj/core/lib -I/Users/solsson/miniconda3/lib/python3.5/site-packages/numpy/core/include -I/Users/solsson/miniconda3/include/python3.5m -Ipyemma/coordinates/clustering/include -I/Users/solsson/miniconda3/include/python3.5m -c pyemma/coordinates/clustering/src/clustering_module.cpp -o build/temp.macosx-10.9-x86_64-3.5/pyemma/coordinates/clustering/src/clustering_module.o -std=c++11 -O3 -fvisibility=hidden
    In file included from pyemma/coordinates/clustering/src/clustering_module.cpp:5:
    In file included from pyemma/coordinates/clustering/include/regspace.h:9:
    In file included from pyemma/coordinates/clustering/include/Clustering.h:12:
    In file included from pyemma/coordinates/clustering/include/bits/../metric_base.h:96:
    pyemma/coordinates/clustering/include/bits/metric_base_bits.h:12:10: fatal error: 'omp.h' file not found
    #include <omp.h>
             ^
    1 error generated.
    error: command 'gcc' failed with exit status 1

Temporary work-around: install an earlier egg.

**Comment by marscher** [comment]
OSX symlinks clang (which does not have proper OpenMP support) to gcc. We can not fix that. Install gcc with conda to workaround this dirty OSX hack. The missing pybind dependency is indeed a bug, because it should be dragged in automatically by setuptools...

**Comment by marscher** [comment]
can you share the command you used to install?

**Comment by psolsson** [comment]
Thanks. I'll give the conda gcc a shot.
The command that gave me the errormessage
`pip install git+https://github.com/markovmodel/PyEMMA.git`
what i ended up doing
`pip install git+https://github.com/markovmodel/PyEMMA.git@7eef75c938`

**Comment by marscher** [comment]
I don't see why specifying a commit id would change the situation. The problem with pybind is that the temporary install of pip ends up with a flat file installation, which can not be used as an include directory during extension building: https://github.com/pybind/pybind11/pull/1028
