### ISSUE TITLE
MSM object slows autocomplete after estimating

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#1167]
Most exotic so far, best described with this gif:
https://drive.google.com/file/d/0BwZRaTvNiSkvVXRmM2drdWs4Qkk/view?usp=sharing

After having estimated an MSM object with a large dataset (10K trajs, 200 frames mean), the autocomplete-function (Tab-key) of that object (and only of that object) gets slowed down (+2 min!). If I re-estimate with less data, the autocomplete is back to normal

This happens in notebooks and console alike. 

Have not seen any error or warning messages in the debugging console or the terminal.

2.4+302.ga7c531bd
```
import numpy as np, pyemma
dtrajs = [dtraj for dtraj in np.load('test.npy')]
iMSM = pyemma.msm.MaximumLikelihoodMSM(lag=60)
iMSM.estimate(dtrajs)
```

[test.npy.zip](https://github.com/markovmodel/PyEMMA/files/1368490/test.npy.zip)

**Comment by marscher** [comment]
I think this is completely unrelated to pyemma.

https://www.google.de/search?hl=de&source=hp&biw=&bih=&q=jupyter+notebook+hangs+autocomplete&btnG=Google-Suche&gbv=1

**Comment by gph82** [comment]
Yupp, looks like it is an ipython 5 vs 6 problem:
https://github.com/ipython/ipython/issues/10493
Just checked with an ipython=5.3, pyemma=2.4 env and it works. 

Thanks for the pointer!
