### ISSUE TITLE
Consider SVD for computing covariance matrices

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#117]
I'm not sure how to do this when the data does not fit into memory (chunked access). Moreover, what is the numerical or computational advantage of this approach?

But anyway here an excerpt from an email that Ben forwarded:

Another method which is less known is to use the SVD. It can also be 
used to compute the corrcoef. Here for real values and rowvar=False:

```python
def cov(X, ddof):
     nx,p = X.shape
     mean = X.mean(axis=0)
     CX = X - mean[None,:]
     u,s,pc = np.linalg.svd(CX/np.sqrt(nx-ddof), full_matrices=False)
     s2 = s**2
     tmp = np.eye(p) * s2[:,None]
     return np.dot(pc.T,np.dot(tmp,pc))
```

**Comment by marscher** [comment]
I think you've mentioned that SVD would be prohibitively slow the last time we've discussed the new covartools module. Can we close this?

**Comment by franknoe** [comment]
Yes, and we have "considered" it. You can close it, thanks.

Am 26/11/15 um 20:00 schrieb Martin K. Scherer:

> I think you've mentioned that SVD would be prohibitively slow the last 
> time we've discussed the new covartools module. Can we close this?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/117#issuecomment-159977471.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Thanks for the considerations.
