### ISSUE TITLE
OOM count matrix

### ISSUE THREAD

**Issue by zhanghaomiao** [markovmodel/PyEMMA#1175]
When using the OOM to calculate count matrix, the formula is 

![formula](
https://latex.codecogs.com/gif.latex?%24%24s%28i%29%20%3A%3D%20%5Cfrac%7B1%7D%7Bk-2%5Ctau%7D%5Csum_%7Bk%3D1%7D%5E%7Bk-2%5Ctau%7D%5Cchi_i%28X_k%29%24%24%20%5C%5C%20%24%24%20S%5E%7B%5Ctau%7D%28i%2C%20j%29%20%3A%3D%20%5Cfrac%7B1%7D%7BK%20-%202%5Ctau%7D%20%5Csum_%7Bk%3D1%7D%5E%7Bk-2%5Ctau%7D%20%5Cchi_i%28X_k%29%20%5Cchi_j%28X_%7Bk&plus;%5Ctau%7D%29%24%24%5C%5C%20%24%24%20S_r%5E%7B2%5Ctau%7D%28i%2Cj%29%20%3A%3D%20%5Cfrac%7B1%7D%7Bk-2%5Ctau%7D%5Csum_%7Bk%3D1%7D%5E%7Bk-2%5Ctau%7D%20%5Cchi_i%28X_k%29%20%5Cchi_r%28X_%7Bk&plus;%5Ctau%7D%29%5Cchi_j%28X_%7Bk&plus;2%5Ctau%7D%29%24%24)

but the pyemma code 
```python
 c = np.sum(Ct_svd, axis=1)
 self._C_full = dtrajstats.count_matrix() 
 Xi, omega, sigma, l = oom_components(self._C_full.toarray(), C2t, rank_ind=rank_ind,             
                                          lcc=self.active_set)
```
And  the time's range is [1, K-\tau],
It seem's that the three matrices don't use the same part of the data
-  So, is it a problem or there is something that I have ignored?

**Comment by marscher** [comment]
@fnueske can you comment on that, please?

**Comment by fnueske** [comment]
Hi @travelalone , the code is using the same part of the data for all matrices. The count matrix at lag time \tau is estimated in pyemma/msm/estimators/maximum_likelihood_msm.py/OOMReweightedMSM/_estimate as follows:

```
# remove last lag steps from dtrajs:
        dtrajs_lag = [traj[:-self.lag] for traj in dtrajs]

        # get trajectory counts. This sets _C_full and _nstates_full
        dtrajstats = self._get_dtraj_stats(dtrajs_lag)
        self._C_full = dtrajstats.count_matrix() 
```

The last \tau steps are removed from each discrete trajectory before estimating the count matrix. I hope this helps.

Best,
Feliks

**Comment by marscher** [comment]
Thank you Feliks
