### ISSUE TITLE
cktest should accept P-matrix or msm as input

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#119]
pyemma.msm.cktest currently does its own estimation. This is not desired because it does not give users flexibility how to estimate their MSM (e.g. reversible, given fixed pi, using TRAM etc...). 

In order to have all connectivity information, the lag time used, and the discrete trajectories available, it would probably be most useful to construct the cktest using an msm object. Or alternatively we could think about making cktest a member function of the msm object - or both as it is often practiced in numpy functions such as numpy.sum and numpy.ndarray.sum.

**Comment by trendelkampschroer** [comment]
[msm] tpt API-function takes MSM object as input. Added unit test

    devel
    (#108)
commit 50d55044fbcf367fa76c55281945274bdcc497c2 1 parent 3d9614c
@trendelkampschroer trendelkampschroer authored 2 days ago

In pyemma.msm cktest takes msm object
In pyemme.msm.ui cktest takes P-matric, largest connected set and discretized trajectories

**Comment by franknoe** [comment]
thanks!

Am 27/03/15 um 21:24 schrieb Benjamin Trendelkamp-Schroer:
>
> [msm] tpt API-function takes MSM object as input. Added unit test
>
> |devel
> (#108)
> |
>
> commit 50d5504 
> <https://github.com/markovmodel/PyEMMA/commit/50d55044fbcf367fa76c55281945274bdcc497c2> 
> 1 parent 3d9614c 
> <https://github.com/markovmodel/PyEMMA/commit/3d9614c1c63def6ed0ef7359acab7acc8507bda2>
> @trendelkampschroer <https://github.com/trendelkampschroer> 
> trendelkampschroer authored 2 days ago
>
> In pyemma.msm cktest takes msm object
> In pyemme.msm.ui cktest takes P-matric, largest connected set and 
> discretized trajectories
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/119#issuecomment-87078073>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
