### ISSUE TITLE
thermo.estimate_multi_temperature() return object has no attribute 'msm'

### ISSUE THREAD

**Issue by TensorDuck** [markovmodel/PyEMMA#1204]
pyemma: 2.4 / np111py27_1 from conda-forge
RedHat Linux Version: Linux version 2.6.32-642.6.2.el6.x86_64 (mockbuild@x86-031.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-17) (GCC) ) #1 SMP Mon Oct 24 10:22:33 EDT 2016

When using thermo.estimate_multi_temperature(), the returned object is of type TRAM and not MEMM or MultiThermModel, as the documentation here suggests: http://emma-project.org/latest/api/generated/thermo-api/pyemma.thermo.estimate_multi_temperature.html#pyemma.thermo.estimate_multi_temperature

I then run into the issue that the returned object has its attribute `msm` = `None`, which the tutorial (http://emma-project.org/latest/generated/PyEMMA.thermo.estimate_multi_temperatur_-_asymmetric_double_well.html) suggests should be not `None` with this returned object. Also, I am not sure if this is an issue, but the object's `TRAM.models[0].stationary_distribution` is not the same as the `TRAM.stationary_distribution`. I think I am missing something so please do let me know what to do differently to get the resultant MSM from the TRAM estimation.

An example in a tar-ball is attached, the script run_test.py will print out the difference between the standard deviation and the type of the objects that were produced, as well as return the output of `thermo.estimate_multi_temperature()` if you want to test it further. It also has a list of my conda list in "conda_list.txt" in the main directory. 

[debug_send.tar.gz](https://github.com/markovmodel/PyEMMA/files/1566203/debug_send.tar.gz)

**Comment by cwehmeyer** [comment]
> When using thermo.estimate_multi_temperature(), the returned object is of type TRAM and not MEMM or MultiThermModel, as the documentation here suggests: http://emma-project.org/latest/api/generated/thermo-api/pyemma.thermo.estimate_multi_temperature.html#pyemma.thermo.estimate_multi_temperature

The function `pyemma.thermo.estimate_multi_temperature(estimator='tram')` returns a `pyemma.thermo.TRAM` object which itself is derived from `pyemma.thermo.MEMM`, i.e., a `TRAM` object is also an `MEMM` object.

> I then run into the issue that the returned object has its attribute msm = None, which the tutorial (http://emma-project.org/latest/generated/PyEMMA.thermo.estimate_multi_temperatur_-_asymmetric_double_well.html) suggests should be not None with this returned object. Also, I am not sure if this is an issue, but the object's TRAM.models[0].stationary_distribution is not the same as the TRAM.stationary_distribution. I think I am missing something so please do let me know what to do differently to get the resultant MSM from the TRAM estimation.

The `msm` attribute is `not None` **only when unbiased data is present**. In case of `pyemma.thermo.estimate_multi_temperature(estimator='tram')`, this means that you need simulations which were performed at the given `reference_temperature` (which defines what is considered unbiased).

Let's have a look at your example. When running the script `run_test.py`, you first create a `TestMSM` object and then call its `compute_msm_thermo` method:

```python
if __name__ == "__main__":
    tester = TestMSM()
    tester.compute_msm_thermo(newT=125)
```

Please note the supplied parameter `newT=125` which differs from the default in this method:

```python
def compute_msm_thermo(self, oldT=120, newT=120, max_error=2.*(10**-14)):
    ...
    energy_files = []
    for i_set in range(self.n_sets):
        energy_files.append("%s/iteration_0/energy_potential_%d.xvg" % (self.cwd, i_set))
    all_energies = []
    all_t_rows = []
    all_dtrajs = self.get_tica_results()
    for i_set in range(self.n_sets):
        energy_file = energy_files[i_set]
        energies = np.loadtxt(energy_file, comments=["#", "@"])[:,1]
        all_energies.append(energies)
        all_t_rows.append(np.ones(np.shape(energies)) * oldT)   # HERE!
    new_model = thermo.estimate_multi_temperature(
        all_energies, all_t_rows, all_dtrajs, energy_unit="kJ/mol", estimator="tram",
        lag=self.msmlag, maxerr=1e-10, maxiter=20000, reference_temperature=newT)
```

Going through this method, we can see that `TRAM` assumes that all your trajectories have been simulated at `oldT=120`. By setting the parameter `reference_temperature=newT=125`, you tell `TRAM` that there are no unbiased simulations and, thus, `TRAM` does not provide an unbiased MSM. Further, `TRAM` computes the unbiased `stationary_distribution` for the `reference_temperature=newT=125`, whereas `TRAM.models[0].stationary_distribution` has been computed for `oldT=120`.

That is why `TRAM.msm = None` and `TRAM.stationary_distribution != TRAM.models[0].stationary_distribution`.

Do you need to use a `reference_temperature` which is not present among the supplied trajectories?

**Comment by TensorDuck** [comment]
Thanks for the very clear explanation, i see the TRAM object is a MEMM subclass. 

As for the temperature i need to use, i would like to use a reference temperature that is outside of a simulated temperature. Is that okay? Or should I resimulate at the desired temperature?

**Comment by cwehmeyer** [comment]
That is OK if you are only interested in the unbiased stationary distribution. If you need kinetics for the reference temperature, you do not need to resimulate everything but add some simulations at the desired temperature.

**Comment by TensorDuck** [comment]
Okay, that makes sense. 

As a final aside, I tried again with the reference temperature set to the same value as the simulation temperatures, and I still get the `TRAM.msm` attribute as None. I have an updated python script where I added an assertion check to verify. Is there something else I'm missing in my script?

[debug_send.tar.gz](https://github.com/markovmodel/PyEMMA/files/1569251/debug_send.tar.gz)

**Comment by TensorDuck** [comment]
So I ran more tests and unfortunately I am confused once again. I have another example simulated at multiple temperatures and re-weighted to one of the simulated temperatures. The skeleton example is attached. I've clustered onto 500 states and computed a MSM on those states. I simulated temperatures `T=range(115,126)`, and re-weighted to `T=120`. I found that:

1. The `TRAM.msm = None` still, despite using a temperature contained in the possible values. 
2. The `TRAM.models[5].stationary_distribution`, which is the unbiased simulation, has an identical stationary distribution to the `TRAM.stationary_distribution`, and is of the same length (500). 
3. However, the transition matrix and active set of the unbiased simulation is smaller. It is missing ~ 20% (exactly 95) of the states. This means the `ThermoMSM.transition_matrix` is only on a subset of states, as seen by the dimensions of the transition matrix.

I think I'm a little confused at this behavior and I think I've misunderstood how this should've worked. I was under the impression from our previous discussion that `TRAM.msm` should not be None, but it still is for some reason. Furthermore, I also thought that the `ThermoMSM` would still construct a MSM on all the states, regardless if that state was seen in the unbiased distribution or not. In that case, I thought `len(ThermoMSM.stationary_distribution) == np.shape(ThermoMSM.transition_matrix)[0] == len(ThermoMSM.active_set) == 500` . 

I have the skeleton example attached that should compute relatively quickly, but the `output.txt` file has a list of all the printed output from the script. Do let me know if I've done something wrong and what you think on all of this.

[debug_send_1.tar.gz](https://github.com/markovmodel/PyEMMA/files/1594990/debug_send_1.tar.gz)

**Comment by fabian-paul** [comment]
Hi Justin,

the problem was on our side, PR #1214 should fix it.

Concerning your point (3): in general  `len(ThermoMSM.stationary_distribution) != np.shape(ThermoMSM.transition_matrix)[0] `
The stationary distribution is computed by reweighting across all ensembles, so it will contain information for all Markov states. The transition matrix for ensemble _k_ however is only computed from the transitions observed in ensemble _k_ . Here TRAM only uses reweighting to infer the probabilities of the transitions that have the reverse direction of the transitions observed in ensemble _k_. Transition probabilities are not reweighted across ensembles.

Best,
Fabian

**Comment by TensorDuck** [comment]
Hi Fabian, 

Thanks for the fix. I will try it out.

As for the fact that some states are not seen in the unbiased simulation. If I want to compute kinetics and state memberships, the unobserved states are not included in there. Is there any way to perform pcca and get a partitioning of metastable memberships on all the discrete states, even the ones not seen in the unbiased simulation? Or is this not a reasonable question to ask? 

-Justin

**Comment by fabian-paul** [comment]
You can reweight kinetics across ensembles with rate models (see for example the paper by Lukas  Stelzl: http://pubs.acs.org/doi/abs/10.1021/acs.jctc.7b00373) . After reweighting kinetics, one could do PCCA on the whole set of Markov  states. Rate models are not unique and need user intervention (there is the choice between equations 27 to 30 in that paper).
There are plans to implement Lukas' method  in Pyemma in the future. @lukas-stelzl, any news on that?
