### ISSUE TITLE
Re:BPTI msm. Shouldnt there be some bpti_ca_1ms_dt10ns.xtc files in /data? (data/bpti_ca.pdb is there)

### ISSUE THREAD

**Issue by dlbeveridge** [markovmodel/PyEMMA#1212]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [ ] PyEMMA version and operating system versions
- [ ] Minimal example if possible, a Python script, zipped input data (if not too large)

**Comment by marscher** [comment]
This data has a restrictive license, this is why we can not share it. http://www.deshawresearch.com/downloads/download_trajectory.cgi/
