### ISSUE TITLE
TICA object unpicklable when partial_fit with ndarrays

### ISSUE THREAD

**Issue by justinrporter** [markovmodel/PyEMMA#1215]
> - [x] Include a detailed description of the bug or suggestion.

When `pyemma.coordinates.transform.TICA` is fit using `partial_fit` and `np.ndarray`s rather than e.g. `NumPyFileReader`, it cannot be pickled because of (it looks to me like) the dummy progress reporter: `ProgressReporter._progress_register.<locals>.dummy`. The alternative is that there needs to be some invocation of solve?

A minimal example isolating the issue follows below.

> - [x] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).

[piplist.txt](https://github.com/markovmodel/PyEMMA/files/1610280/piplist.txt)
[condalist.txt](https://github.com/markovmodel/PyEMMA/files/1610281/condalist.txt)

> - [x] PyEMMA version and operating system versions

```
In [16]: pyemma.__version__
Out[16]: '2.4'
```

```
$ cat /etc/system-release
CentOS Linux release 7.3.1611 (Core)
```

> - [x] Minimal example if possible, a Python script, zipped input data (if not too large)

```
In [12]: import pickle
    ...: import numpy as np
    ...:
    ...: from glob import glob
    ...: from pyemma.coordinates.transform import TICA
    ...:
    ...: tica = TICA(lag=10)
    ...:
    ...: for i in range(10):
    ...:     n = np.random.normal(0, 1, size=(100, 3))
    ...:     tica.partial_fit(n)
    ...:
    ...: with open('./tica.pkl', 'wb') as f:
    ...:     pickle.dump(tica, f)
    ...:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-f83f6612fc9b> in <module>()
     12
     13 with open('./tica.pkl', 'wb') as f:
---> 14     pickle.dump(tica, f)
     15

AttributeError: Can't pickle local object 'ProgressReporter._progress_register.<locals>.dummy'
```

Interestingly, the following code _does_ work:

```
In [10]: import pickle
    ...: import numpy as np
    ...:
    ...: from glob import glob
    ...: from pyemma.coordinates.transform import TICA
    ...:
    ...: tica = TICA(lag=10)
    ...:
    ...: n = [np.random.normal(0, 1, size=(100, 3)) for i in range(10)]
    ...: tica.partial_fit(n)
    ...:
    ...: print(tica.eigenvectors)
    ...:
    ...: with open('./tica.pkl', 'wb') as f:
    ...:     pickle.dump(tica, f)
```

Thanks for the great library, and cheers!

**Comment by marscher** [comment]
Thanks for your report. We've changed what is pickled in the current devel branch and this will be released shortly. I think this issue will not pop up again, since only mandatory attributes will be stored.

**Comment by marscher** [comment]
Your provided test script (thanks a lot for this) runs fine with the devel branch. Expect the new release in the next couple of days.
