### ISSUE TITLE
regspace (and probably other clustering methods) can't work with 1D data directly

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#122]
This loads 1D trajectory data:
X = np.loadtxt('./data/2well_traj_100K.dat')

The data is 1D:
print X.shape
(100000,)

and of type float
print X.dtype
float64

This raises an error. I assume this is because X is a 1D-array. I suggest to reformat the input into a standard way (similar to dtrajs treatment)
coor.regspace(data=X, dmin = 10)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-39-d7510b0c692f> in <module>()
----> 1 coor.regspace(data=X, dmin = 10)

/Users/noe/anaconda/lib/python2.7/site-packages/pyEMMA-1.0.1_332_g3c2480b-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/api.pyc in regspace(data, dmin, max_centers)
    304         inp = DataInMemory(data)
    305         res.data_producer = inp
--> 306         res.parametrize()
    307     return res
    308 

/Users/noe/anaconda/lib/python2.7/site-packages/pyEMMA-1.0.1_332_g3c2480b-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/transform/transformer.pyc in parametrize(self)
    176                     # first chunk
    177                     add_data_finished = self.param_add_data(
--> 178                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y)
    179                     first_chunk = False
    180                     # increment time

/Users/noe/anaconda/lib/python2.7/site-packages/pyEMMA-1.0.1_332_g3c2480b-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/clustering/regspace.pyc in param_add_data(self, X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y)
     85             for x in X:
     86                 dist = np.fromiter((np.linalg.norm(x - c, 2)
---> 87                                     for c in self._clustercenters), dtype=np.float32)
     88 
     89                 if len(self._clustercenters) > self.max_clusters:

/Users/noe/anaconda/lib/python2.7/site-packages/pyEMMA-1.0.1_332_g3c2480b-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/clustering/regspace.pyc in <genexpr>((c,))
     85             for x in X:
     86                 dist = np.fromiter((np.linalg.norm(x - c, 2)
---> 87                                     for c in self._clustercenters), dtype=np.float32)
     88 
     89                 if len(self._clustercenters) > self.max_clusters:

/Users/noe/anaconda/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in norm(x, ord, axis)
   2134             raise ValueError("Invalid norm order for matrices.")
   2135     else:
-> 2136         raise ValueError("Improper number of dimensions to norm.")

ValueError: Improper number of dimensions to norm.

**Comment by marscher** [comment]
@franknoe 
is this still present in latest version, you are using 1.0.1, but we are already behind 1.1.1

**Comment by franknoe** [comment]
I am using an install fetched from the github devel branch - is this not 
supposed to be to latest one?

Am 16/03/15 um 14:11 schrieb Martin K. Scherer:
>
> @franknoe <https://github.com/franknoe>
> is this still present in latest version, you are using 1.0.1, but we 
> are already behind 1.1.1
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/122#issuecomment-81652950>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 16.03.2015 um 14:15 schrieb Frank Noe:
> I am using an install fetched from the github devel branch - is this not
> supposed to be to latest one?
Sure it is, but the version string from the backtrace refers to an old
version.

**Comment by franknoe** [comment]
Hmm, weird. Let us check later.

Am 16/03/15 um 14:17 schrieb Martin K. Scherer:
> Am 16.03.2015 um 14:15 schrieb Frank Noe:
> > I am using an install fetched from the github devel branch - is this not
> > supposed to be to latest one?
> Sure it is, but the version string from the backtrace refers to an old
> version.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/122#issuecomment-81658867>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
We should at a most common point ensure data has correct shape for passing it through the pipeline. Maybe in Transformer.parametrize()?

**Comment by franknoe** [comment]
Yes.

Although that is not directly on this issue - that issue could be 
resolved by reshaping the array in the DataInMemory constructor

Am 16/03/15 um 20:17 schrieb Martin K. Scherer:
>
> We should at a most common point ensure data has correct shape for 
> passing it through the pipeline. Maybe in Transformer.parametrize()?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/122#issuecomment-81881753>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Please fix: This test failure seems to be exactly due to this issue:

======================================================================
ERROR: test_1d_data (pyemma.coordinates.tests.test_kmeans.TestKmeans)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/noe/data/software_projects/pyemma/pyemma/coordinates/tests/test_kmeans.py", line 38, in test_1d_data
    kmeans = cluster_kmeans(data, k=7)
  File "/Users/noe/data/software_projects/pyemma/pyemma/coordinates/api.py", line 788, in cluster_kmeans
    res.parametrize()
  File "/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.py", line 223, in parametrize
    X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
  File "/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/kmeans.py", line 75, in _param_add_data
    self.algo.partial_fit(X)
  File "/Users/noe/anaconda/lib/python2.7/site-packages/sklearn/cluster/k_means_.py", line 1314, in partial_fit
    x_squared_norms=x_squared_norms, init_size=self.init_size)
  File "/Users/noe/anaconda/lib/python2.7/site-packages/sklearn/cluster/k_means_.py", line 551, in _init_centroids
    "n_samples=%d should be larger than k=%d" % (n_samples, k))
ValueError: n_samples=1 should be larger than k=7

**Comment by marscher** [comment]
yes that's why I've added this test :)

Unluckily this is burrowed in the logic of sklearn kmeans impl. It needs
at least k chunks.

So I fear we can not fix it with this impl. @clonker told me, that he is
not sure if their kmeans impl is memory leak free, so I would suggest
keeping sklearn impl and warn the user, that 1d data is currently
unsupported.

Regspace works by the way.

**Comment by franknoe** [comment]
Why can't we repack the input into an appropriately shaped list or array 
in our api method? That's what I meant - very similar to the dtraj 
interface in count_matrix, msm etc.

Am 08/04/15 um 15:04 schrieb Martin K. Scherer:
> yes that's why I've added this test :)
>
> Unluckily this is burrowed in the logic of sklearn kmeans impl. It needs
> at least k chunks.
>
> So I fear we can not fix it with this impl. @clonker told me, that he is
> not sure if their kmeans impl is memory leak free, so I would suggest
> keeping sklearn impl and warn the user, that 1d data is currently
> unsupported.
>
> Regspace works by the way.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/122#issuecomment-90908301>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
kmeans has also been fixed by 5c8cac5
