### ISSUE TITLE
plot_cktest set title hassle

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#1229]
The legend is always placed on top and matplotlib places a figure suptitle such that it overdraws the legend. I came up with a very ugly workaround, which involves moving the bounding box of the legend after is has been drawn. 
![screenshot_20180124_182729](https://user-images.githubusercontent.com/170287/35347069-48a6f290-0134-11e8-946a-e0958ac3a592.png)

Probably the warning is significant here...
```
matplotlib/figure.py:1743: UserWarning: This figure includes Axes that are not compatible with tight_layout, so its results might be incorrect.
  warnings.warn("This figure includes Axes that are not "
```

**Comment by thempel** [comment]
Quick workaround (with some bounding box problems if saved to pdf):
```python
fig, axes = pyemma.plots.plot_cktest(ckt, diag=True)
box = axes[0].get_position()
fig.legends[0].set_bbox_to_anchor((box.x0 +  box.width, box.y0 + 1.1* box.height))
plt.suptitle('ASDF', y=1.1)
```

**Comment by PawarKishori** [comment]
@thempel  I am using Pyemma for cktest MSM validation purpose. I was wondering if I can export a PNG  image generated by mplt.plot_cktest. As of now its returning a tuple object.

Please help me to get this issue resolved.

**Comment by thempel** [comment]
Hi @PawarKishori, I believe I answered this in your other issue #1277.
