### ISSUE TITLE
regspace clustering is slow

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#123]
I don't have an exact timing but regspace clustering (in memory) with 100.000 1D-datapoints takes several seconds. In comparison k-means (which is in principle more expensive but uses probably the sklearn impl) is much faster.

I guess the looping is expensive. Track down performance leaks - if they can't be tackled with python maybe we need to write a small C-extension here.

**Comment by marscher** [comment]
Yes this is gonna to be cythonized soon. Shall we also support different 
norms?

**Comment by franknoe** [comment]
You mean different distance metrics?

I think Euclidean distance metric is covering most cases.

Traditionally people used minimal pairwise RMSD - I don't know if 
there's a simple way to call that from the C-side. Perhaps mdtraj has a 
callable min rmsd-distance interface. I would recommend against using 
this option, but in terms of supporting features it is the second-most 
relevant one. So unless it's trivial make it a separate low-priority issue.

The third option are circular norms to handle angles. This is not so 
important, because it can be avoided by first doing a cos/sin transform 
(formally doubling the dimension), and then computing Euclidean distances.



Am 14/03/15 um 14:46 schrieb Martin K. Scherer:
> Yes this is gonna to be cythonized soon. Shall we also support different
> norms?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/123#issuecomment-80487491>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by rmcgibbo** [comment]
MDTraj >= 1.2 compiles a static library (.a on unix, .lib on windows) that
implements the min-rmsd calculation, that other python package's c
extensions can link against to get access to that function without python
function call overhead.

**Comment by franknoe** [comment]
Nice! Thanks Robert.

Am 14/03/15 um 20:35 schrieb Robert T. McGibbon:
> MDTraj >= 1.2 compiles a static library (.a on unix, .lib on windows) that
> implements the min-rmsd calculation, that other python package's c
> extensions can link against to get access to that function without python
> function call overhead.
>
> On Sat, Mar 14, 2015 at 6:59 AM, Frank Noe <notifications@github.com> 
> wrote:
>
> > You mean different distance metrics?
> >
> > I think Euclidean distance metric is covering most cases.
> >
> > Traditionally people used minimal pairwise RMSD - I don't know if
> > there's a simple way to call that from the C-side. Perhaps mdtraj has a
> > callable min rmsd-distance interface. I would recommend against using
> > this option, but in terms of supporting features it is the second-most
> > relevant one. So unless it's trivial make it a separate low-priority 
> issue.
> >
> > The third option are circular norms to handle angles. This is not so
> > important, because it can be avoided by first doing a cos/sin transform
> > (formally doubling the dimension), and then computing Euclidean 
> distances.
> >
> >
> >
> > Am 14/03/15 um 14:46 schrieb Martin K. Scherer:
> > > Yes this is gonna to be cythonized soon. Shall we also support 
> different
> > > norms?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/markovmodel/PyEMMA/issues/123#issuecomment-80487491
> > >.
> > >
> >
> >
> > --
> >
> > ----------------------------------------------
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> >
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > Mail: Arnimallee 6, 14195 Berlin, Germany
> > ----------------------------------------------
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/markovmodel/PyEMMA/issues/123#issuecomment-80498913>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/123#issuecomment-80689625>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
BTW, you can probably speed up the Euclidean distance metric calculation a lot by using a single-step numpy calculation of all n*T distances where n is the number of centers and T is the current chunk size length. Only if a new center is created part of the calculation needs to be repeated.
