### ISSUE TITLE
serialization tests

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#1259]
We need to store saved models somewhere, and restore them with the current devel in order to ensure we did not break compatibility. We can collect all of the saved models in the unit tests, and save them in a branch for this version.
A separate test suite will then load all of these branches and compare the models. The big question is how to ensure all important attributes are in place and have meaningful values. We do not want to hard code this, as it would be hard to maintain (every change would have to make sure it also updates the tests, which is kind of impossible to do for inexperienced people).
The collection and storage can be somehow automatized via conftest.py (hooks into pytest). The latter is difficult to achieve and we need to think about this.

**Comment by clonker** [comment]
I propose to drop the guaranteed forward-compatibility support, this would likely make the testing as well as the maintaining and codebase a lot simpler.
