### ISSUE TITLE
Memory error when using pyemma.coordinates.api.kmeans

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#126]
Hi, 

the new kmeans implementation seems to be having trouble with large datasets. Can somebody check this out? 

hTheta = np.load('/group/ag_cmb/scratch/gph82/work/CMB/hierarchical_TICA/bpti-shaw/DESRES-Trajectory-bpti-c-alpha/hTheta.l.lag.001000.Ns.10.npy')
K10 = pyemma.coordinates.api.kmeans(hTheta, k=500, max_iter=10, )

**Comment by marscher** [comment]
this is being tracked by #129
