### ISSUE TITLE
featurizer does not count label 

### ISSUE THREAD

**Issue by MamtaMohan** [markovmodel/PyEMMA#1262]
Dear PyEMMA Team,

I would appreciate your help to resolve an issue I run into.

Issue:
Protein  is labelled at two places and residue name used is CYR1 instead of standard residue name. Label CYR1 is a modified Cysteine with label added to it. Label used is MTSL spin-label. I am trying to build a list of backbone C-alpha atoms to build model. 

When I try to build C-alpha atom list, label CA atom indices  are skipped and rest of the information is there.

I am attaching a pdb file, 10 frame dcd file.
[pdb_and_dcd_10_frames.zip](https://github.com/markovmodel/PyEMMA/files/1759577/pdb_and_dcd_10_frames.zip)

These are the commands I gave to build backbone C-alpha atom list:

feat = coor.featurizer(top)
bkb = feat.select_Backbone()
ca = feat.select_Ca()
ca.inds = []
ca_inds = np.intersect1d(bkb, ca)

feat.add_selection(ca_inds)
feat.describe()[:10]
feat.dimension()
486 ---it should be 164 * 3 = 492. It is 162 * 3 = 486
feat.describe()[:216]
'ATOM:ASP 70 CA 1106 x',
 'ATOM:ASP 70 CA 1106 y',
 'ATOM:ASP 70 CA 1106 z',
 'ATOM:VAL 71 CA 1118 x',
 'ATOM:VAL 71 CA 1118 y',
 'ATOM:VAL 71 CA 1118 z',
 'ATOM:ALA 73 CA 1171 x',
 'ATOM:ALA 73 CA 1171 y',
 'ATOM:ALA 73 CA 1171 z']
index 1134 is and 2091 are missing in the list.

I would appreciate your response.

Mamta

**Comment by marscher** [comment]
Hi Mamta,
I think this caused by the non-standard residue name. You would have to select these residues/c-alpha atoms manually (by calling add_selection on the appropriate indices). Note that you would also need to define the angles manually, which can be some kind of a hassle.
This is caused by mdtrajs handling of the topology and there is nothing we can do about that.

**Comment by MamtaMohan** [comment]
Thank you for your response.

Mamta
