### ISSUE TITLE
Question: TICA variance

### ISSUE THREAD

**Issue by MamtaMohan** [markovmodel/PyEMMA#1263]
Dear PyEMMA Team,

I am trying to build MSM for input data of a protein labelled at two sites with spin-label MTSL. Trajectory length is 27 ns with time-step = 1ps.

I am trying to build TICA object, which builds ok, but when I check the cumulative variance it is very low (first 4 values :  0.01256361,  0.0251269 ,  0.03768877,  0.0502468 ). I tried various combination of parameters but it does not improve. Please find a list attached of combinations I tried.

After tica object is build I can see clusters separated (I am following Tutorial for Pentapeptide).

However when I try to calculate Implied time (its) I am getting warnings and errors like:
estimating MaximumLikelihoodMSM:  57%|████████████████████████▊                   | 13/23 [00:00<00:00, 21.99it/s]27-02-18 14:18:21 pyemma.msm.estimators.maximum_likelihood_msm.MaximumLikelihoodMSM[106] WARNING  Ignored error during estimation: Stationary distribution contains entries smaller than 1e-15 during iteration
'Error at lag time 710: Stationary distribution contains entries smaller than 1e-15 during iteration'

Which I think is due to poor tica coordiate.

I would like to ask if there is something obvious I am missing? Or Is it trajectory length? Or something else.

I would appreciate your response.

Mamta
[tica_obj_params.txt](https://github.com/markovmodel/PyEMMA/files/1764419/tica_obj_params.txt)

**Comment by marscher** [comment]
On 27.02.2018 20:49, MamtaMohan wrote:
> Dear PyEMMA Team,
> 
> I am trying to build MSM for input data of a protein labelled at two sites with spin-label MTSL. Trajectory length is 27 ns with time-step = 1ps.
> 
> I am trying to build TICA object, which builds ok, but when I check the cumulative variance it is very low (first 4 values :  0.01256361,  0.0251269 ,  0.03768877,  0.0502468 ). I tried various combination of parameters but it does not improve. Please find a list attached of combinations I tried.
> 
> After tica object is build I can see clusters separated (I am following Tutorial for Pentapeptide).
> 
> However when I try to calculate Implied time (its) I am getting warnings and errors like:
> estimating MaximumLikelihoodMSM:  57%|████████████████████████▊                   | 13/23 [00:00<00:00, 21.99it/s]27-02-18 14:18:21 pyemma.msm.estimators.maximum_likelihood_msm.MaximumLikelihoodMSM[106] WARNING  Ignored error during estimation: Stationary distribution contains entries smaller than 1e-15 during iteration
> 'Error at lag time 710: Stationary distribution contains entries smaller than 1e-15 during iteration'
> 
> Which I think is due to poor tica coordiate.
> 
> I would like to ask if there is something obvious I am missing? Or Is it trajectory length? Or something else.
> 
> I would appreciate your response.
> 
> Mamta
> [tica_obj_params.txt](https://github.com/markovmodel/PyEMMA/files/1764419/tica_obj_params.txt)
> 
> 

Hi Mamta,

your guess about the poor TICA coordinates is indeed correct. The data 
is most likely only consisting of noise. Your data set also seems to be 
very short, you would probably only be able to capture very short lived 
processes.
BTW I can not read your attached txt file (seems to be another format).

Cheers,
Martin

**Comment by MamtaMohan** [comment]
Dear Martin,

Thank you for your response.

How long a dataset should be on an averages for TICA to give meaningful results?

I have attached new document.

Mamta
[tica_obj_params.txt](https://github.com/markovmodel/PyEMMA/files/1765241/tica_obj_params.txt)

**Comment by thempel** [comment]
There is no general answer as to how much sampling you need for your particular problem. It should be enough to capture all the processes you are interested in. How much this is in nanoseconds depends on the system you are simulating (and less on the coordinate transform). For a protein, like @marscher pointed out, 27ns does not sound sufficient to sample the slow processes, but of course we are not familiar with your system. If you are only seeing noise, you might additionally want to check your input data. 

Since this seems to be a question more related to general MD and not so much to pyEMMA, I'm closing this issue.

**Comment by MamtaMohan** [comment]
Thank you.

**Comment by fabian-paul** [comment]
As an alternative to the TICA variance you could also check how many TICA-implied timescales are larger than the lag time. Processes with implied time scales smaller than the lag time are often poorly resolved by the TICA order parameters.

**Comment by MamtaMohan** [comment]
Thank you. I will try that.
