### ISSUE TITLE
Decide whether to allow recycling of elements of a pipeline

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#127]
Consider e.g a TICA instance which the user passes to multiple pipelines with changing lag times. Shall we allow this or raise an error? If we allow it, we would need to check everything for consistency (have dataproducers changed, different chunksize or lag time)

**Comment by marscher** [comment]
another important purpose is to change parameters of clustering and having already parametrized transformers in pipeline:

now you have chosen a high cutoff for regspace and you end up to re-run the whole pipeline only to change dmin to a smaller value.

**Comment by marscher** [comment]
which sanity checks are the minimum requirement for this to work properly? Only introducing a parametrized attribute is not sufficient, since the previous elements in the pipeline also might have changed, which should trigger a re-parametrization.

**Comment by marscher** [comment]
at least we have to handle this somehow, since users might manually call parameterize twice, which leads to undefined behaviour in current state.

**Comment by fabian-paul** [comment]
It think we solved this partially for TICA in pull request #140. The lag time parameter can be changed and the data producer can be changed too. We may easily add support for the change of clustering parameters.
You mentioned that some user might use the same instance of TICA in two chains. This must be avoided. I think this confusion comes from the fact that there are two ways to link transfomers to a chain.
* the data_producer attribute
* the chain class that encapsulates a list of transformes

I would suggest that we don't provide two ways how the user can join transformes. The user should either use the chain object or change the data_producer property. Doing both should no be allowed.
This is related to the question whether we like to have a chain object at all. If we want that, setting data_producer should not be allowed for the user.

**Comment by franknoe** [comment]
I think we definitely need a chain object (or pipeline - that's the 
same, right?), because we need an object that is able to inspect the 
entire pipeline. Otherwise it's impossible to make decisions such as 
memory allocation.

Additionally I find a construction such as

     p = pipeline(feature_reader, tica, kmeans)

more revealing to the user. Something like

     f = feature_reader(....)
     #do something with f
     t = tica(f)
     # do something
     k = kmeans(t)
     # do something

seems too cluttered for me. I guess fine for people that are used to 
object-oriented programming, but most people are not.

Am 26/03/15 um 13:29 schrieb fabian-paul:
>
> It think we solved this partially for TICA in pull request #140 
> <https://github.com/markovmodel/PyEMMA/pull/140>. The lag time 
> parameter can be changed and the data producer can be changed too. We 
> may easily add support for the change of clustering parameters.
> You mentioned that some user might use the same instance of TICA in 
> two chains. This must be avoided. I think this confusion comes from 
> the fact that there are two ways to link transfomers to a chain.
>
>   * the data_producer attribute
>   * the chain class that encapsulates a list of transformes
>
> I would suggest that we don't provide two ways how the user can join 
> transformes. The user should either use the chain object or change the 
> data_producer property. Doing both should no be allowed.
> This is related to the question whether we like to have a chain object 
> at all. If we want that, setting data_producer should not be allowed 
> for the user.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/127#issuecomment-86489947>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by fabian-paul** [comment]
I wonder how this would go together with the api functions. The api function 'tica' as it is implemented now returns a transformer object (a TICA instance). There is a hidden reader which is created implicitly.
This made sense in a world without pipeline objects. But now? Shouldn't we change that such that the tica method returns a (short) pipeline? 
And then, how would the user read data from the pipeline? Should the pipeline provide some data extraction methods? How would the user access the eigenvalues from the pipeline?

**Comment by marscher** [comment]
Am 27.03.2015 um 16:16 schrieb fabian-paul:
> I wonder how this would go together with the api functions. The api
> function 'tica' as it is implemented now returns a transformer object (a
> TICA instance). There is a hidden reader which is created implicitly.
> This made sense in a world without pipeline objects. But now? Shouldn't
> we change that such that the tica method returns a (short) pipeline?
> And then, how would the user read data from the pipeline? Should the
> pipeline provide some data extraction methods? How would the user access
> the eigenvalues from the pipeline?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/127#issuecomment-86971330>.
> 
I vote against returning mini-pipelines, since it would be confusing
calling tica() and getting a pipeline with just two elements. The reader
is encapsulated in the TICA object, so we do not need a Pipeline.

If something on the TICA object changes (eg. the data_source) it is
ensured that it will be re-parameterised.

This way it is also directly clear to the user of the object how to
access eigenvalues etc.

**Comment by franknoe** [comment]
I'm really against returning pipelines when you only compute something 
directly (such as tica directly on data). But of course there are ways 
to hide that behind api functions that map simple input to simple output

Am 27/03/15 um 16:16 schrieb fabian-paul:
>
> I wonder how this would go together with the api functions. The api 
> function 'tica' as it is implemented now returns a transformer object 
> (a TICA instance). There is a hidden reader which is created implicitly.
> This made sense in a world without pipeline objects. But now? 
> Shouldn't we change that such that the tica method returns a (short) 
> pipeline?
> And then, how would the user read data from the pipeline? Should the 
> pipeline provide some data extraction methods? How would the user 
> access the eigenvalues from the pipeline?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/127#issuecomment-86971330>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
fixed in last release.
