### ISSUE TITLE
Datasets Prinz energy get nan

### ISSUE THREAD

**Issue by zhanghaomiao** [markovmodel/PyEMMA#1272]
When I use the code

```python
from pyemma.datasets import get_quadwell_data
data = get_quadwell_data()
```
The `data` get an `nan`.
when I read the source code, It seems that you don't give the **PrinzModel** a boundary, such as (-1,1), so it goes into infinty.

**Comment by marscher** [comment]
Thanks for your report @travelalone! 
@Obudo, @amardt  which boundaries do you typically use?

**Comment by pasqualil** [comment]
We don't use boundaries, but this is an issue that arises from the generator's parameters, specifically dt and kt.
We usually set dt=0.001 and kt=1.0, try with those

**Comment by marscher** [comment]
Thanks! It works with kt=1 and dt=0.01. But shouldn't it also work for
higher temperatures?
