### ISSUE TITLE
weired hmm.stationary_distribution

### ISSUE THREAD

**Issue by yanhuaouyang** [markovmodel/PyEMMA#1275]
Hi,
I met some  problems when I was building MSMs following the pentapeptide tutorial. Firstly I build a MSM and next the MSM is coarse grained into a user-defined number of macrostates (n_sets=4). However, the results are weired as following:

hmm = M.coarse_grain(n_sets) 

M.metastable_sets
[array([], dtype=int64),
 array([  0,   2,   3,   5,   6,..]),
array([  1,   7,  10,  13,  14, ..]),
 array([  4,  11,  33,  36, ...,541])]

set(M.metastable_assignments)
{1, 2, 3}

hmm.stationary_distribution
array([ 0.,  0.,  0.,  1.])

hmm.transition_matrix
array([[ 0.99195984,  0.00633326,  0.0017069 ,  0.        ],
       [ 0.00732714,  0.98938238,  0.00197444,  0.00131605],
       [ 0.00150973,  0.00150949,  0.99698078,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

I am confused that why the MSM has only one macrostate and the other three macrostates have zero stationary_distribution. I changed the n_sets into 2 or 3, the results are the same. Does anyone know the problem?

**Comment by marscher** [comment]
Your system is non-reversible and one state absorbs all of the 
probability in the long term. Eg. you did not observe any transition 
escaping from that state.

**Comment by yanhuaouyang** [comment]
Thanks for your answer @marscher !
But I wonder that is it possible that the unreasonable MSMs parameters or the peptide sequence length lead to the system non-reversible? Because such non-reversible problem arise when I build MSMs on the middle segment of my peptide but not on the full length peptide.
