### ISSUE TITLE
Exporting images in Pyemma without jupyter ipython notebook 

### ISSUE THREAD

**Issue by PawarKishori** [markovmodel/PyEMMA#1277]
I am using Pyemma for cktest MSM validation purpose. I was wondering if I can export a PNG image generated by mplt.plot_cktest. As of now its returning a tuple object.

Please help me to get this issue resolved.

hanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [ ] PyEMMA version and operating system versions
- [ ] Minimal example if possible, a Python script, zipped input data (if not too large)

**Comment by thempel** [comment]
The pyemma plotting package uses matplotlib.pyplot in general. Specifically, the `mplt.plot_cktest()` function returns a tuple consisting of two matplotlib objects, the first is a  `Figure` object and the second is another tuple of axes (`Axis` objects with subplots), c.f. http://www.emma-project.org/latest/api/generated/pyemma.plots.plot_cktest.html#pyemma.plots.plot_cktest. You can get a PNG if you save those objects and call the `.savefig()` method of `Figure`, e.g.
```python
fig, axes = mplt.plot_cktest(your_cktest_object)
fig.savefig('my_file.png', dpi=300)  # adjust dpi for image quality
```
For more information about those objects, e.g. figure size, please refer to the matplotlib manual (https://matplotlib.org/) which explains everything in detail.
