### ISSUE TITLE
CK test plot interpretation

### ISSUE THREAD

**Issue by jeiros** [markovmodel/PyEMMA#1282]
Hello all, 

I am using the ck tests in pyemma to test the quality of my MSMs. I wanted just a quick verification of what the plots are telling me about convergence.

I have a ~100 microseconds aggregated dataset (unbiased MD produced with adaptive sampling) of a large protein (419 residues). I am focusing on a few residues to investigate conformational changes in a specific region of it. From my ITS plot I see convergence after 20 ns, but the CK test of a Bayesian MSM built at that lag time is:

![ck_test](https://user-images.githubusercontent.com/10696140/37897777-ef4c0ea8-30de-11e8-8798-42651c1b0a7a.png)

What is the meaning of the jumps seen in the estimate?

Also, if I specify the physical timestep with the `dt_traj` parameter in the `BayesianMSM` class, do I get the timescales from the `timescales()` method back in whatever units I passed? For instance, the frames in my trajectory are spaced by 200 ps. To build a Bayesian MSM with a lag time of 20 ns, I use:

```python
msm = BayesianMSM(lag=100, dt_traj='0.0002 us')
```
And the estimated timescales are:
```python
msm.timescales()[0:5]
array([ 5400.59102231,  1859.85396066,   162.38309152,    93.03792554,
           8.62658408])
```
I observe a gap between the 2nd and 3rd timescale. Am I right to interpret that these are already in microseconds? Because if they are, this means that the associated timescales are larger than my dataset by an order of magnitude, rendering my MSM analysis useless as it is unconverged.

Thanks for your help

Juan

Edit: Also I think is worth reporting, I get the following warning when doing the ck test:

```python
ck = msm.cktest(4, mlags=5, err_est=True)
```
```
/Users/je714/miniconda3/lib/python3.6/site-packages/pyemma/util/statistics.py:60: UserWarning: confidence interval for constant data is not meaningful
  warnings.warn('confidence interval for constant data is not meaningful')
```

**Comment by thempel** [comment]
About the CK-test:
From the ck-test plot one cannot really tell what is going wrong with the estimates. It could generally be several things. Can you estimate new models at the lagtimes that don't work? My guess would be that the PCCA coarse graining of your MSM  has found different metastable states for each lag time. Take a look at the metastable distributions and see if they match between the lagtimes.

**Comment by thempel** [comment]
About the CK-test:
From the ck-test plot one cannot really tell what is going wrong with the estimates. It could generally be several things. Can you estimate models at the lagtimes that don't work? My guess would be that the PCCA coarse graining of your MSM has found different metastable states for each lag time or that you are lacking data for very high lag times.

**Comment by thempel** [comment]
About the CK-test:
From the ck-test plot one cannot really tell what is going wrong with the estimates. It could generally be several things. Can you estimate models at the lagtimes that don't work? My guess would be that the PCCA coarse graining of your MSM has found different metastable states for each lag time or that you are lacking data for very high lag times.

**Comment by jeiros** [comment]
I think I know what you mean. My problem is most likely that I don't have near enough data to get clear transitions between macrostates.
I've been playing around with some toy models, this is what I get for a simple system with a very clear gap between the first and second timescale, then doing a CK test for two macrostates:

![ck_test_ideal](https://user-images.githubusercontent.com/10696140/37958410-60aae58c-31a8-11e8-89d5-a36b499a262d.png)

So ideally I should be seeing the same, a convergence to the populations of the stationary distribution of the PCCA, right?

In that case those weird jumps in the MD data that I have in my original plot means that at longer steps the macrostates are being recalculated and reassigned, hence the 'jump' back to probability ~1?

**Comment by thempel** [comment]
As I wrote, it's not completely clear from this plot what exactly the reason for the jumps is. I'm also not completely sure if I understand you right. The CK-test shows you the conditional transition probabilities between macrostates. More specifically, in the plots you showed in your first post, these are the probabilities to stay in a given macrostate. It does not tell you anything about being in the macrostate per se or about PCCA assignment to that state. Ideally, the plots look like the ones you show in your second post, yes. 
The estimates that display jumps in the transition probabilities can be checked e.g. by estimating MSMs for each lag time separately and plotting the metastable distributions. You'll see if this yields the same PCCA states for each lag time. 
Further, the timescales will be scaled according to `dt_traj='0.0002 us'`, so it's to be interpreted in microseconds. Timescales larger than your total trajectory length do not necessarily render your analysis useless. It's a reversible maximum likelihood estimate based on your data. If this estimate is larger than your trajectory time, the process is probably poorly sampled. But in principle you are of course right and one has to take care in cases where timescales become somewhat ridiculous. One order of magnitude should be fine though.
Concerning the warning about error intervals for constant data: Probably related to the jump in your CK-estimates, not a bug.
