### ISSUE TITLE
dtype handling

### ISSUE THREAD

**Issue by clonker** [markovmodel/PyEMMA#1286]
I think there is some inconsistency about how to handle data types of sources. 

It seems that data sources are intended to operate on float32, however the yielded data type when iterating is not always float32 (when e.g. passing float64 arrays into a `DataInMemory`). Also quite a few tests assume double precision and fail when single precision is enforced (this can be see when introducing

```python
array = array.astype(np.float32)
```

into `DataInMemory::_add_array_to_storage`).

What do you think is the right way to deal with this? Enforce a float dtype or not? And if not, how should we deal with data sources that yield different dtypes for different trajs? In that case I think we would need an `output_type` per traj and cannot treat it as global property of the data source anymore.

**Comment by marscher** [comment]
I do not think mixing data types within one data set is a good idea. We should probably enforce it within one set and make it possible to cast to a desired type. Clustering and covariance estimation is now implemented for multiple types, but at the moment float is assumed.
