### ISSUE TITLE
Silence pyemma version check

### ISSUE THREAD

**Issue by j3mdamas** [markovmodel/PyEMMA#1287]
Hi,

We want to silence pyemma version check in HTMD. I've seen here (https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/__init__.py#L82)
the recommendation. But importing the `config` to change the `check_version` property imports pyemma itself, so that defeats the purpose.

What would be recommended way then? I was thinking about repackaging pyemma with the check_version in https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/pyemma.cfg changed to False but there must be a better way, no?

Thanks,
João

**Comment by marscher** [comment]
you can save the config once after changing the attribute. So this
should only pop up once.

**Comment by marscher** [comment]
or you can import pyemma with a warnings.catch_warnings context. This is also pretty straight forward.

**Comment by j3mdamas** [comment]
I meant at a distribution level, so the end user would not need to mess with configuration files themselves.
I'll try the warnings. Thanks for the tip.
