### ISSUE TITLE
[progressbars] tqdm notebook api changed

### ISSUE THREAD

**Issue by yanhuaouyang** [markovmodel/PyEMMA#1292]
HI, 
I am faced with error as following when I running the clustering step. Does anyone know how to fix this problem?
commands: clustering = coor.cluster_kmeans(Y,k=500,fixed_seed=True)
TypeError: status_printer() takes from 1 to 3 positional arguments but 4 were given

Best regards,
Ouyang

**Comment by clonker** [comment]
Hi, this seems to be an issue with the most recent version of tqdm (`4.23.0`).
You should be able to work around it by installing tqdm version 4.22, i.e.,
```
conda install tqdm=4.22
```

**Comment by marscher** [comment]
On 20.04.2018 09:26, Moritz Hoffmann wrote:
> Hi, this seems to be an issue with the most recent version of tqdm (`4.23.0`).
> You should be able to work around it by installing tqdm version 4.22, i.e.,
> ```
> conda install tqdm=4.22
> ```
> 

This looks indeed like what @clonker suggested. I will release a new 
build of 2.5.2 in the meantime, while we adopt to the new tqdm version. 
Thank you very much for your report!

**Comment by marscher** [comment]
Fixed by https://github.com/conda-forge/pyemma-feedstock/pull/14

**Comment by marscher** [comment]
@yanhuaouyang in the mean time you can simply disable progress bars by:
import pyemma
pyemma.config.show_progress_bars = False

**Comment by yanhuaouyang** [comment]
@clonker  Thank you for your answer! I would try as what you have suggested.

**Comment by yanhuaouyang** [comment]
Dear Marscher, thank you for your solution, I would try it as you said. @marscher

**Comment by marscher** [comment]
On 23.04.2018 03:33, yanhuaouyang wrote:
> Dear Marscher, thank you for your solution, I would try it as you said. @marscher
> 
the fixed build is already online, please run conda update pyemma to get 
a contrained tqdm version, which works.

**Comment by yanhuaouyang** [comment]
@marscher Thank you so much. I have fixed the problem and have tried to build a MSM successfully!
