### ISSUE TITLE
CK test plot layout issue

### ISSUE THREAD

**Issue by philipyoung9561** [markovmodel/PyEMMA#1297]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [Function pyemma.plots.plot_cktest plot diagonal plots in the first row too ] Include a detailed description of the bug or suggestion
- [conda ] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [2.5.2 ] PyEMMA version and operating system versions
- [pyemma.plots.plot_cktest(ck, diag=True, figsize=(7,7), layout=(2,2), padding_top=0.1, y01=True, padding_between=0.3, dt=1)
[cktest.pdf](https://github.com/markovmodel/PyEMMA/files/1939893/cktest.pdf)
 ] Minimal example if possible, a Python script, zipped input data (if not too large)

**Comment by marscher** [comment]
On 23.04.2018 22:25, philipyoung9561 wrote:
> Thanks for submitting an issue!
> 
> Here's a quick checklist in what to include:
> 
> - [Function pyemma.plots.plot_cktest plot diagonal plots in the first row too ] Include a detailed description of the bug or suggestion
> - [conda ] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
> - [2.5.2 ] PyEMMA version and operating system versions
> - [pyemma.plots.plot_cktest(ck, diag=True, figsize=(7,7), layout=(2,2), padding_top=0.1, y01=True, padding_between=0.3, dt=1)
> [cktest.pdf](https://github.com/markovmodel/PyEMMA/files/1939893/cktest.pdf)
>   ] Minimal example if possible, a Python script, zipped input data (if not too large)
> 
> 

I have to admit, I do not really understand what is your concern here. 
Do you mean that diag=True should produce multiple rows?

**Comment by marscher** [comment]
please feel free to re-open this issue, if you can elaborate the issue a bit more.
