### ISSUE TITLE
H5reader random access duplicate elements not supported

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#1299]
For Numpy and MD data we support random access strides with duplicate elements within one trajectory. Unfortunately h5py is clever enough to disallow this behaviour. So we either forbid duplicate elements in RA strides completely or try to implement a workaround for the H5Iterator.
Since we already request that RA strides are sorted, this should be easy to implement.

However it seems to be a rare corner case - so it would probably not hurt anybody when we silently switch to forbidding this.

@clonker I'd appreciate your fifty cents on this one (when your holidays are over)

**Comment by marscher** [comment]
@gph82 Do you think that in save_traj(s) it sometimes happen that the same structure or frame is selected twice per set?

**Comment by marscher** [comment]
The implementation for filtering and restoring duplicated indices is quite complex, because it needs to store overlaps between chunks. So I'd encourage to solve this by disallowing duplicates.

**Comment by clonker** [comment]
Where would overlaps be involved? The way i see it all we'd need to do is run a `np.unique(X, return_inverse=True)` with X being the indices of the current random-access chunk. Even though this of course comes at some computational cost.

**Comment by marscher** [comment]
On 07.05.2018 11:10, Moritz Hoffmann wrote:
> Where would overlaps be involved? The way i see it all we'd need to do is run a `np.unique(X, return_inverse=True)` with X being the indices of the current random-access chunk. Even though this of course comes at some computational cost.
> 
Maybe the overlap case only applies for chunksize=1, which we are now
testing in the iterator refactoring branch?
