### ISSUE TITLE
unify assignment in clustering

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#130]
eg. have a c-extension which does it for all desired cases and call it from python. It should support assignment of whole chunks and different metrics (euclidean, min-rmsd etc).

Currently we're using super inefficient python for loops in assignment (one point assigned per iteration...)

**Comment by marscher** [comment]
this would also address #123

**Comment by marscher** [comment]
the assignment function should also take a function pointer for metrics. Min-RMSD can be used from mdtraj.capi()

**Comment by marscher** [comment]
current situation is the following:
regspace c extension defines assignment and its used in regspace and uniform time clustering.

In the future I would suggest to refactor regspace to clustering and also implement kmeans there to have everything in one place, since linking against own modules causes some headaches.

**Comment by franknoe** [comment]
Sorry, I this is not english. Do you mean that the regspace assignment 
is part of the regspace class or module and that k-means is using the 
regspace module to do the assignment? Then I agree that assignment 
should be implemented in a separate module.

Am 24/03/15 um 17:31 schrieb Martin K. Scherer:
>
> current situation is the following:
> regspace c extension defines assignment and its used in regspace and 
> uniform time clustering.
>
> In the future I would suggest to refactor regspace to clustering and 
> also implement kmeans there to have everything in one place, since 
> linking against own modules causes some headaches.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/130#issuecomment-85589917>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
