### ISSUE TITLE
Unexpected behaviour of pyemma.coor.source for ascii files

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#1300]
Hi,

I have been getting some very curious stop iteration errors and I think have now isolated the issue. 
Basically when I try and use `pyemma.coor.source()` on a list of ascii trajectories and then try and use an iterator over the data a stop iteration occurs. 

I found the issue originally in vampnets `data_generator.py`, but it seems to be an issue with pyemma.coor.source(). I have attached a minimal example loosely inspired by `build_generator_on_source()` in `data_generator.py`.

`issue.py` reproduces the issue. `trj0.dat` and `trj1.dat` and `out` is the output I get. 
[issue.txt](https://github.com/markovmodel/PyEMMA/files/1996575/issue.txt)
[trj0.txt](https://github.com/markovmodel/PyEMMA/files/1996576/trj0.txt)
[trj1.txt](https://github.com/markovmodel/PyEMMA/files/1996577/trj1.txt)
[out.txt](https://github.com/markovmodel/PyEMMA/files/1996578/out.txt)

**Comment by marscher** [comment]
Thanks for your detailed report. This seems to be an issue with the lagged iterator, which is fixed in this feature branch: https://github.com/marscher/PyEMMA/tree/refactor_iterators

**Comment by marscher** [comment]
fixed in #1315
