### ISSUE TITLE
Saving the structure of the cluster centroids after a clustering

### ISSUE THREAD

**Issue by eric-jm-lang** [markovmodel/PyEMMA#1304]
Hello,

Sorry this is likely to be a very basic question, but I do not seem to be able to find a way to do it.
I have selected a number of dihedrals as features for my trajectory, performed a TICA and then a k-means clustering (I am using PyEMMA 2.52).

```inp = pyemma.coordinates.source('../5-CC-Pent/2-MD/DPH_aligned2_site1.nc', feat)
tica_obj = pyemma.coordinates.tica(data=inp, lag=20, var_cutoff=0.95)
Y = tica_obj.get_output()
clustering = pyemma.coordinates.cluster_kmeans(Y, k=100, stride=1, max_iter=100)
dtrajs = clustering.dtrajs
```

Now, I would like to save the centroid of each cluster (or the structure the closest from the cluster centre calculated with k-means) as individual PDB files. Is there a way to do that?

I am aware that some instructions to do something similar are available in teh mdtraj docs (http://mdtraj.org/1.9.0/examples/centroids.html). However this relies on the rmsd as a metric, whereas I would like to use as a metric the result form the featurisation/TICA if it makes sense.

Would it also be possible to extract a set of random structures for each cluster? (I know this is possible with Sample_by_distribution once the MSM is created, but is there a way to do that at the clustering level?

Many thanks in advance for your help

**Comment by gph82** [comment]
Dear Eric,

you can use a related software called molpx that takes a PyEMMA clustering object as input and samples frames associated to that centers. I think that is exactly what you want:

https://molpx.readthedocs.io/en/latest/2.molPX_TICA_BPTI_Copy.html?highlight=cl#Use-a-clustering-object-as-input

**Comment by eric-jm-lang** [comment]
Hi Guillermo,

Thank you very much. It looks indeed exactly like what I want to do. I am playing with it to see if I can get what I need and might get back to you if I have problems.

Many thanks

**Comment by eric-jm-lang** [comment]
Hi Guillermo,
MolPX does exactly what I want. 
Superb programme!
Many thanks
Eric

**Comment by germanbarcenas** [comment]
Eric,

were you able to save clusters as pdb? Do you mind sharing how this is done? I'm trying to do this now as well.
