### ISSUE TITLE
in FeatureReader: .describe() not working with .featurizer.backbone_torsions()

### ISSUE THREAD

**Issue by sstolzen007** [markovmodel/PyEMMA#131]
from pyemma.coordinates.api import FeatureReader
reader = FeatureReader(tfs_WT,topfile_WT)
reader.featurizer.backbone_torsions()
reader.describe()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-35-58e399f5f0b0> in <module>()
----> 1 reader.describe()
      2 #reader.trajectory_lengths()
      3 #reader.chunksize=1000

/storage/mi/sstolzen/mypackages/PyEMMA/pyemma/coordinates/io/feature_reader.pyc in describe(self)
     83         :return:
     84         """
---> 85         return "Feature reader, features = ", self.featurizer.describe()
     86 
     87     def operate_in_memory(self):

/storage/mi/sstolzen/mypackages/PyEMMA/pyemma/coordinates/io/featurizer.pyc in describe(self)
    198 
    199         for f in self.active_features:
--> 200             labels.append(f.describe())
    201 
    202         return labels

/storage/mi/sstolzen/mypackages/PyEMMA/pyemma/coordinates/io/featurizer.pyc in describe(self)
    126         for ires in self._phi_inds:
    127             labels.append("PHI: %s %i" %
--> 128                           (self.topology.residue(ires).name, ires))
    129         for ires in self._psi_inds:
    130             labels.append("PSI: %s %i" %

/home/mi/sstolzen/mystore/mypackages/anaconda/lib/python2.7/site-packages/mdtraj/core/topology.pyc in residue(self, index)
    625             The `index`-th residue in the topology.
    626         """
--> 627         return self._residues[index]
    628 
    629     @property

TypeError: only integer arrays with one element can be converted to an index

**Comment by marscher** [comment]
whats the output of featurizer._phi_inds?

**Comment by marscher** [comment]
sorry, its:
assuming you selected backbone_torsions first:

      reader.featurizer.activate_features[0]._phi_inds

**Comment by sstolzen007** [comment]
this output looks fine:

print np.shape(reader.featurizer.active_features[0]._phi_inds)
print reader.featurizer.active_features[0]._phi_inds[:6]

(166, 4)
[[ 15  17  19  33]
 [ 33  35  37  49]
 [ 49  51  53  68]
 [ 68  70  72  87]
 [ 87  89  91 104]
 [104 106 108 114]]

**Comment by marscher** [comment]
ah I see. I'm extracting one row of inds which is a quadrupel, but we have to pass only index to residue()

**Comment by marscher** [comment]
fixed by edb6712

**Comment by sstolzen007** [comment]
OK, this is nice, but prints out lines in the format
PHI/PSI ResName First_AtomIndex_of_the_Angle

though for cosmetics, it would be more convenient to have the following:
PHI/PSI ResName ResID

Thanks

**Comment by marscher** [comment]
backbone_torsions describe now uses _atom_describe which might be too verbose, which gives 

"%s %i %s %i" % (at.residue.name, at.residue.index, at.name, at.index) where at is a mdtraj.Atom

@sstolzen007 
Please reopen, if you want this to be changed
