### ISSUE TITLE
Using the dihedral formed by the COM of groups of atoms as a feature

### ISSUE THREAD

**Issue by eric-jm-lang** [markovmodel/PyEMMA#1313]
Hello,

For the feature selection step, I would like to use the dihedrals (as well as angles and distances) formed by the centre of mass of groups of atoms. Is there a way to do that?

For example, lets say I would like to use the dihedral formed by the [COM of atoms 0, 1, 2, 3] , [atom 8], [atom 12] and the [COM of atom 16,17,18,19,20]

Currently, in `pyemma.coordinates.featurizer`, the method `add_dihedral` only accepts atom indices. Is there a way to replace indices with group of atoms?

For example, using the example above, doing something like `feature.add_dihedrals([[[0, 1, 2, 3],8,12,[6,17,18,19,20]]])` (although this currently returns an error).

Many thanks in advance for your help,

Eric

*I am using PyEMMA 2.5.2 installed via anaconda (python 3) on a Ubuntu 16.04.4 LTS computer*

**Comment by marscher** [comment]
I do not believe that this is possible with the aid of mdtraj. You should ask your question there, but I doubt that it is possible to even define center of mass dihedrals in a sane way.
