### ISSUE TITLE
How to project to a trajectory onto the TICA space obtained for another trajectory 

### ISSUE THREAD

**Issue by eric-jm-lang** [markovmodel/PyEMMA#1314]
Hello,

I would like to know if it is possible to create a TICA space for a given trajectory and then use this space to project a second trajectory?

For example, lets suppose I have a trajectory which exhibit exactly the conformational changes I am interested in. I do a featurization and then a TICA and obtain a TICA object which serve as the basis for some clustering. 

Now I have a second trajectory, I have the conformational changes I am interested in, but in addition, I occasionally have a very large conformational change in which I am not interested in. However, if I do a TICA on this second trajectory, I cannot see the changes that are of interest to me because the TICA component describe almost exclusively the occasional very large conformational change.

Is there a way to use the main TICA components from the first trajectory and allpy them to the second trajectory so I have a space describing the conformational changes I am interested in and I can so a clustering on it?

Many thanks in advance for your help,

Eric
  
*I am using PyEMMA 2.5.2 installed via anaconda (python 3) on a Ubuntu 16.04.4 LTS computer*

**Comment by thempel** [comment]
Hi Eric,
You can use the `transform()` method of the TICA object. If `A` is the dataset that only contains the processes you want to consider for your TICA projection and `B` is your second trajectory with the process you do not want to be taken into account by TICA, you could do
```python
tica = pyemma.coordinates.tica(A, lag)
B_tica_transformed = tica.transform(B)
```
If you want to have the projection of all data, you'd have to call `transform()` for both data sets. 

The corresponding entry in the documentation is http://www.emma-project.org/latest/api/generated/pyemma.coordinates.tica.html#pyemma.coordinates.transform.tica.TICA.transform
Cheers,
Tim

**Comment by eric-jm-lang** [comment]
Hi Tim,

Thanks a lot, I think this is exactly what I need.
However, when I try to use it I get the following error:
```
inp = pyemma.coordinates.source('../../traj1.nc', feat)
tica_obj= pyemma.coordinates.tica(data=inp, lag=20, var_cutoff=0.95)

inp2 = pyemma.coordinates.source('../../traj2.nc', feat)
tica_obj2 = tica_obj.transform(inp2)
```
I get the following error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-f54d6220d1c5> in <module>()
     17 inp2 = pyemma.coordinates.source('../../traj2.nc', feat)
     18 
---> 19 tica_obj2 = tica_obj.transform(inp2)
     20 
     21 print('TICA dimension ', tica_obj2.dimension())

~/Software/anaconda3/lib/python3.6/site-packages/pyemma/coordinates/data/_base/transformer.py in transform(self, X)
     78             raise TypeError('Input has the wrong type: %s '
     79                             '. Either accepting numpy arrays of dimension 2 '
---> 80                             'or lists of such arrays' % (str(type(X))))
     81 
     82     @abstractmethod

TypeError: Input has the wrong type: <class 'pyemma.coordinates.data.feature_reader.FeatureReader'> . Either accepting numpy arrays of dimension 2 or lists of such arrays
```

This is weird because based on the documentation both `pyemma.coordinates.tica` and `tica_obj.transform` expect the same input filetype. Any idea about what could be wrong?

I have attached the result of `conda list` [conda_list.txt](https://github.com/markovmodel/PyEMMA/files/2084771/conda_list.txt)

Many thanks in advance,

Eric

**Comment by thempel** [comment]
The transform method can only transform loaded data. You are passing a `source` object, also called a `reader` in the manual. If you have enough memory / your dataset is not too large, you can load the data into memory and transform it, e.g.
```python
tica_transformed_inp2 = tica_obj.transform(inp2.get_output())
```
Please note that this might exceed your memory, so this line comes without warranty since I don't know your data set. (I always start with high strides and see how my memory usage increases with decreasing the stride, just to be sure). 

Further (since I see your variable name...), `tica_obj.transform()` does not return a new `TICA` object but the transformed data itself.

**Comment by eric-jm-lang** [comment]
Ok, I understand my confusion now.. Thanks a lot for your help. It works and does exactly what I had in mined.
Many thanks
