### ISSUE TITLE
Clustering returns 0 structures for a highly populated region of the free energy landscape

### ISSUE THREAD

**Issue by eric-jm-lang** [markovmodel/PyEMMA#1327]
Hello,

*I am using PyEMMA 2.5.3 with Python 3.6 on an Ubuntu 16.04 computer. I have attached the conda list results: [conda_list.txt](https://github.com/markovmodel/PyEMMA/files/2145984/conda_list.txt)*

I am having troubles with the clustering of my trajectories. After performing a TICA analysis (with 2 dimensions describing 100% of the variance) I have a 2D energy surface on which I have clear energy wells. After doing a k-mean clustering, I clearly have cluster centres inside those energy basins. but for one of the basin, composed of three clusters, the clustering returns only 1 structure  

```
tica_obj = pyemma.coordinates.tica(data=inp, lag=20, var_cutoff=0.95)
print('TICA dimension ', tica_obj.dimension())
```
`TICA dimension  2`
```
tica_obj.cumvar
```
`array([ 0.58780609,  1.        ])`
```
Y = tica_obj.get_output()
n_clusters = 9 
clustering = pyemma.coordinates.cluster_kmeans(Y,k=n_clusters)
dtrajs = clustering.dtrajs
```
```
def plot_labels(ax=None):
    #if ax is None:
        #ax = gca()
    for i in range(0,len(clustering.clustercenters)):
        plt.text(clustering.clustercenters[i][0]+0.05, clustering.clustercenters[i][1]+0.05, i, fontsize=10, color='black')
```
```
plt.figure()
pyemma.plots.plot_free_energy(np.vstack(Y)[:, 0], np.vstack(Y)[:, 1])
cc_x = clustering.clustercenters[:, 0]
cc_y = clustering.clustercenters[:, 1]
plt.plot(cc_x, cc_y, linewidth=0, marker='o', markersize=5, color='black')
plot_labels()
```
![download](https://user-images.githubusercontent.com/15257860/42045763-432239da-7af4-11e8-8be6-83e6b5092a13.png)
I draw your attention to clusters 1, 2 and 7.
If I then do:
```
labels = clustering.dtrajs
mapping = defaultdict(lambda : [])
for i, label in enumerate(labels[0]):
    mapping[label].append(i)
for i in range(0,len(clustering.clustercenters)):
    print('size of cluster %d: %d structures' % (i, len(mapping[i])))
```
I get:

`size of cluster 0: 19537 structures`
`size of cluster 1: 1 structures`
`size of cluster 2: 0 structures`
`size of cluster 3: 1099 structures`
`size of cluster 4: 22 structures`
`size of cluster 5: 122 structures`
`size of cluster 6: 14709 structures`
`size of cluster 7: 0 structures`
`size of cluster 8: 4710 structures`

How is it possible that I get 0 structures for cluster 7 and 2 and only one for cluster 1? For the entire energy basin on the right-hand side I only have one structure from the clustering.

Do you have any ideas about what could be wrong. I can send you more data if required.

Many thanks in advance for your help!

Eric

**Comment by eric-jm-lang** [comment]
I obtain the same behaviour with other clustering methods, for example:
```
clustering = pyemma.coordinates.cluster_regspace(data=Y, dmin=1)
plt.figure()
pyemma.plots.plot_free_energy(np.vstack(Y)[:, 0], np.vstack(Y)[:, 1])
cc_x = clustering.clustercenters[:, 0]
cc_y = clustering.clustercenters[:, 1]
plt.plot(cc_x, cc_y, linewidth=0, marker='o', markersize=5, color='black')
plot_labels()
```
![download 1](https://user-images.githubusercontent.com/15257860/42047038-1cae9656-7af7-11e8-8c66-fb15c1314196.png)
```
labels = clustering.dtrajs
mapping = defaultdict(lambda : [])
for i, label in enumerate(labels[0]):
    mapping[label].append(i)
for i in range(0,len(clustering.clustercenters)):
    print('size of cluster %d: %d structures' % (i, len(mapping[i])))
```
I get
```
size of cluster 0: 290 structures
size of cluster 1: 197 structures
size of cluster 2: 32 structures
size of cluster 3: 402 structures
size of cluster 4: 315 structures
size of cluster 5: 7614 structures
size of cluster 6: 25113 structures
size of cluster 7: 5598 structures
size of cluster 8: 413 structures
size of cluster 9: 0 structures
size of cluster 10: 0 structures
size of cluster 11: 0 structures
size of cluster 12: 0 structures
size of cluster 13: 0 structures
size of cluster 14: 0 structures
size of cluster 15: 0 structures
size of cluster 16: 0 structures
size of cluster 17: 0 structures
size of cluster 18: 0 structures
size of cluster 19: 0 structures
size of cluster 20: 0 structures
size of cluster 21: 2 structures
size of cluster 22: 0 structures
size of cluster 23: 224 structures
```

**Comment by marscher** [comment]
Do you observe the same behaviour when setting n_jobs=1 during estimation/assignment?

**Comment by marscher** [comment]
Is the assignment reproducible? Eg. if you use the same centers array in pyemma.coordinates.assign_to_centers, do you observe exactly the same pattern?

I think we use to have some weirdness like this in an old version and it was related to threading. This was fixed a long time ago and also got a regression test to avoid this issue from popping up again.

**Comment by marscher** [comment]
Can you please confirm that the "bug" is reproducible in a fresh environment, created such:
conda create -n test_ -c conda-forge pyemma

I suspect not having conda-forge as highest channel priority could eventually cause problems.

**Comment by eric-jm-lang** [comment]
Hi Martin,

Thank you very much for your quick reply.
If I use ` n_jobs=1` for the clustering (is it what you had in mind? I also used it in `tica_obj = pyemma.coordinates.tica(data=inp, lag=20, var_cutoff=1,n_jobs=1 )`):
```
n_clusters = 9 
clustering = pyemma.coordinates.cluster_kmeans(Y,k=n_clusters, n_jobs=1)

plt.figure()
pyemma.plots.plot_free_energy(np.vstack(Y)[:, 0], np.vstack(Y)[:, 1])
cc_x = clustering.clustercenters[:, 0]
cc_y = clustering.clustercenters[:, 1]
plt.plot(cc_x, cc_y, linewidth=0, marker='o', markersize=5, color='black')
plot_labels()
```
I do not obtain the same clustering (which I find somewhat surprising)
![download 2](https://user-images.githubusercontent.com/15257860/42087564-76b77b9e-7b8e-11e8-9ce8-4b2bb7ed6bb8.png)
But I still get empty clusters for the same region of space (not even one structure this time):
```
labels = clustering.dtrajs
mapping = defaultdict(lambda : [])
for i, label in enumerate(labels[0]):
    mapping[label].append(i)
for i in range(0,len(clustering.clustercenters)):
    print('size of cluster %d: %d structures' % (i, len(mapping[i]))) 
```
```
size of cluster 0: 25 structures
size of cluster 1: 19665 structures
size of cluster 2: 1192 structures
size of cluster 3: 0 structures
size of cluster 4: 0 structures
size of cluster 5: 5101 structures
size of cluster 6: 14217 structures
size of cluster 7: 0 structures
size of cluster 8: 0 structures
```

**Comment by eric-jm-lang** [comment]
The error seems indeed reproducible when using `pyemma.coordinates.assign_to_centers`:
```
labels = pyemma.coordinates.assign_to_centers(Y, clustering.clustercenters)
mapping = defaultdict(lambda : [])
for i, label in enumerate(labels[0]):
    mapping[label].append(i)
for i in range(0,len(clustering.clustercenters)):
    print('size of cluster %d: %d structures' % (i, len(mapping[i]))
```
```
size of cluster 0: 25 structures
size of cluster 1: 19665 structures
size of cluster 2: 1192 structures
size of cluster 3: 0 structures
size of cluster 4: 0 structures
size of cluster 5: 5101 structures
size of cluster 6: 14217 structures
size of cluster 7: 0 structures
size of cluster 8: 0 structures
```
Is it the test you had in mind?

**Comment by eric-jm-lang** [comment]
It is indeed reproduced in a new environment created as `conda create -n test_ -c conda-forge pyemma` followed by `source activate test_` and open the jupyter notebook and re-run everything,
I get the following:
![download 3](https://user-images.githubusercontent.com/15257860/42088192-a79cef58-7b90-11e8-81b5-992f2c99083e.png)
```
size of cluster 0: 0 structures
size of cluster 1: 22923 structures
size of cluster 2: 197 structures
size of cluster 3: 1154 structures
size of cluster 4: 3 structures
size of cluster 5: 15802 structures
size of cluster 6: 0 structures
size of cluster 7: 121 structures
size of cluster 8: 0 structures
```

**Comment by eric-jm-lang** [comment]
Note that if, in the new environment, if I remove `n_jobs=1` from `(tica_obj = pyemma.coordinates.tica(data=inp, lag=20, var_cutoff=1)` and `clustering = pyemma.coordinates.cluster_kmeans(Y,k=n_clusters)`, I obtain the following clustering:
![download 4](https://user-images.githubusercontent.com/15257860/42088370-2cc2d8dc-7b91-11e8-98b7-f4a81b775b31.png)
As you can see this is very similar to what I had for the very first clustering posted. It looks like using `n_jobs=1` lead to 4 clusters found in the right-hand side basin, whereas without `n_jobs=1` I get 3 cluster in that same region.

**Comment by marscher** [comment]
Dear Eric,

thank you very much for your detailed report, but @cwehmeyer found the source of this mysterious problem. When you check the state population, you are only looking at the first discrete trajectory. Therefore it is quite possible that not all states are getting assigned.

``` python
labels = np.concatenate(clustering.dtrajs)
mapping = defaultdict(lambda : [])
for i, label in enumerate(labels):
    mapping[label].append(i)
for i in range(0,len(clustering.clustercenters)):
    print('size of cluster %d: %d structures' % (i, len(mapping[i])))
```

**Comment by eric-jm-lang** [comment]
I see, it makes sense now!! Thank you so much for your help with this!
It works perfectly now.
Is this difference of behaviour for the clustering with or without 'n_jobs=1' normal? Should I open a new issue regarding this?
Many thanks,
Eric

**Comment by marscher** [comment]
The multi threading behaviour is expected, thanks again for reporting back.
