### ISSUE TITLE
[plots] zorder parameter

### ISSUE THREAD

**Issue by thempel** [markovmodel/PyEMMA#1334]
For overplotting `pyemma.plots.plot_contour()` with `pyemma.plots.plot_flux()` or anything network plotting related, I keep getting unreadable figures due to arrows being hidden behind the contour. That spoils the pyemma_tutorials plots I was making. @cwehmeyer do you think we can fix this? `matplotlib.contourf()` does not naturally support `zorder` kwargs, if I'm not mistaken. 
![asdf](https://user-images.githubusercontent.com/12544861/42285442-ef9be1a6-7faf-11e8-89ec-759f7980d79d.png)

**Comment by cwehmeyer** [comment]
You can use the `alpha` parameter in `pyemma.plots.plot_contour()`.

**Comment by thempel** [comment]
-.-
