### ISSUE TITLE
[plots] plot_state_map

### ISSUE THREAD

**Issue by thempel** [markovmodel/PyEMMA#1335]
It seems that the `plot_state_map()` doesn't work properly, cf. the notebook example in pyemma_tutorials, notebook 05, 6 state HMM. Where's the sixth state in the plot below? It's definitely in the data... 

![index](https://user-images.githubusercontent.com/12544861/42313745-c1cc4fd8-8043-11e8-92d5-8cef7a3465cb.png)

Something is wrong with the colormap, I guess. State zero is not distinguished from state 1.

Further, I don't quite understand why the `plot_state_map()` function needs the `nstates` keyword argument. If I'm not mistaken, I deleted it some time ago and it was added again. A state map should be defined by the number of states in the list of labels that is passed to this function, right? Why should a user want to have a different number? 

tagging @cwehmeyer

**Comment by cwehmeyer** [comment]
Are you using the latest devel build? There has been an issue with a missing `ncountours` parameter in `plot_state_map` which has been resolved in #1331.

**Comment by thempel** [comment]
Ok, works with devel. Sorry.
