### ISSUE TITLE
cluster_mini_batch_kmeans error isfinite(sum) failed

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#1348]
For cluster_mini_batch_kmeans pyemma 2.5.4, python 2.7.14
```cl = pyemma.coordinates.cluster_mini_batch_kmeans(data=y, k=msm_states, max_iter=10, n_jobs=None)```

I get a fatal error:
```
kmeans iterations:   0% 0/10 [00:00<?, ?it/s]^[[A^Minitialize kmeans++ centers:   0% 1/300 [00:17<1:26:13, 17.30s/it]python2.7: pyemma/coordinates/clustering/include/bits/metric_base_bits.h:104: dtype euclidean_metric<dtype>::compute(const dtype*, const dtype*) [with dtype = float]: Assertion `std::isfinite(sum)' failed.
```

**Comment by marscher** [comment]
This is a very rare condition and says that during euclidean norm computation the sum of squares overflowed, eg did not fit into the float data type any more. This indicates that something is bogus with your input data.

**Comment by marscher** [comment]
a follow up issue of this one should be "released package on conda-forge uses debug flags for compilation"
