### ISSUE TITLE
covariance matrices as input for tica

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#1351]
I would like to run the function pyemma.coordinates.covariance_lagged for different trajectories on separate nodes, save the covariance matrices and in the next step combine them to calculate tica. 
Is there a way to give these covariance matrices as input for tica? And then map all input data? 
For many trajectories, I assume calculating the covariances takes some time which can be easily split across different nodes.
Would weights='koopman' make this more difficult?

**Comment by marscher** [comment]
you can create a TICAModel instance with your combined matrices and assign it to the model property of your tica instance. I do not know about the Koopman reweighting though, you should ask Feliqs about this. He wrote this part.

**Comment by euhruska** [comment]
is there a function to combine the covariance matrices from different trajectories (different lengths)?

**Comment by marscher** [comment]
On 9/4/18 9:00 PM, Eugen Hruska wrote:
> is there a function to combine the covariance matrices from different trajectories (different lengths)?
> 
no, I'd be happy to accept a PR implementing this.

**Comment by marscher** [comment]
https://github.com/markovmodel/feature_selection/blob/master/scripts/covariances.py#L158
