### ISSUE TITLE
Black line/grey area in ITS plot

### ISSUE THREAD

**Issue by and-tos** [markovmodel/PyEMMA#1358]
Hi, I was wondering what the black line/grey are in the ITS plots is supposed to mean? I looked for a hint in various publications but couldn't find any. Thanks a lot for any clarification!

**Comment by cwehmeyer** [comment]
The black line shows where an implied timescale is equal to the lag time. Thus, all implied timescales below (i.e., in the grey area) are not resolved by the MSM.
