### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by j3mdamas** [markovmodel/PyEMMA#1369]
Hi all,

Miniconda has now changed the default installer to python 3.7, so we're starting the change in HTMD to support it. Any idea on when the pyemma conda packages will support python 3.7?

Thanks!
João

**Comment by marscher** [comment]
First we have to get mdtraj ready for 3.7. But there is no schedule for 
this.

**Comment by j3mdamas** [comment]
thanks, we'll wait for it then :)

**Comment by marscher** [comment]
you can go ahead and steal the packages from conda-forge :grin:
