### ISSUE TITLE
Implement TICA test for many trajectory data

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#137]
Use e.g. Guillermo's data set to build a standard test for TICA, comparing resulting eigenvectors and timescales with a reference.

**Comment by marscher** [comment]
I think this is a candidate for our first integration test, since the data is so huge, we do not want to have it in git.

**Comment by fabian-paul** [comment]
I wrote an integration test where I have an analytical reference for the correlation matrices. See pull request #146. 
Isn't it a bit challenging to have a true reference for the eigenvectors? How to you know if your reference is right? I need some help/ideas here.

**Comment by franknoe** [comment]
I think the most important thing is to have sanity checks.

When we have an (in our opinion) reliable implementation say for 
in-memory tica (simplest case), we could set the eigenvectors resulting 
from this as a reference and then check that the result from the test 
runs deliver approximately the same (in-memory and by file/chunkbased). 
If we change / refactor the code we can run this test and see if we 
haven't messed anything up. I agree that there is often no exact 
reference, plus things will change if we employ other / better 
estimators (see last discussion), but I don't think that is needed at 
this level. These tests should show if we have messed up anything with 
the code.

Best
Frank.

Am 25/03/15 um 19:06 schrieb fabian-paul:
>
> I wrote an integration test where I have an analytical reference for 
> the correlation matrices. See pull request #146 
> <https://github.com/markovmodel/PyEMMA/pull/146>.
> Isn't it a bit challenging to have a true reference for the 
> eigenvectors? How to you know if your reference is right? I need some 
> help/ideas here.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/137#issuecomment-86152635>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by fabian-paul** [comment]
Ok, I have written a test that goes in that direction. See #146. First I generate random data and run TICA on it. Then I write out the IC trajectories as ascii files and run TICA on them. From theory we know what the entries of the instantaneous and the time-lagged correlation matrix of the ICs should be. I test this.
The test uses the feature reader, the DataInMemory reader, TICA estimation and TICA projection.

**Comment by marscher** [comment]
fixed by #146
