### ISSUE TITLE
Implied timescales from dTRAM/TRAM object

### ISSUE THREAD

**Issue by yunhuige** [markovmodel/PyEMMA#1373]
Hi PyEMMA,

I'm new to dTRAM/TRAM estimator and I have some questions here:

How can I get the implied timescales of the unbiased ensemble from dTRAM/TRAM? My understanding is that the dTRAM/TRAM object is a list of MSMs for each thermodynamic ensemble. After I have that object I need to go back to the list and find the implied timescales of the unbiased ensemble?

Here is an example of my scripts:

`time = dtram_obj[j].models[i].timescales(motion)`

`[j]` is the index of lagtime I used in dTRAM/TRAM object, and `[i]` is the index of thermodynamic ensemble in my simulations, `motion` is the number of slow motions I want to compute for implied timescale. 

So let's say my unbiased ensemble is the 0th ensemble and I want to find the unbiased implied timescale of 4 slow motions in my simulation at lagtime tau. 
Then I input dtrajs, ttrajs, bias of all thermodynamic ensembles for dTRAM/TRAM. 
Is `time = dtram_obj[tau].models[0].timescales(4)` the unbiased implied timescale considering all snapshots of all thermodynamic ensembles? 
If so, then what is the `dtram_obj[tau].models[i].timescales(4)` where i is the index of other thermodynamic ensembles? 
I hope I made my questions clear enough and thank you in advance.

Yunhui

**Comment by cwehmeyer** [comment]
Hello Yunhui,

welcome to multi-ensemble Markov models!

> My understanding is that the dTRAM/TRAM object is a list of MSMs for each thermodynamic ensemble.

A DTRAM/TRAM estimation returns an MEMM (multi-ensemble Markov model) object which **contains** a list of MSMs (`models`) where the model index also denotes the index of the corresponding thermodynamic state.

> After I have that object I need to go back to the list and find the implied timescales of the unbiased ensemble?

If you used data from the unbiased thermodynamic ensemble during the estimation, then `models` will contain an unbiased MSM. For convenience, a DTRAM/TRAM object has getter `msm` which returns the unbiased MSM (no need to look up the index); if no unbiased data was used, `msm` returns `None`.

> `time = dtram_obj[j].models[i].timescales(motion)`
>
>[j] is the index of lagtime I used in dTRAM/TRAM object, and [i] is the index of thermodynamic ensemble in my simulations, motion is the number of slow motions I want to compute for implied timescale.

Just for clarification, this is a special case where you have estimated several MEMMs at different lag times in one go. The estimation then returns a list of MEMM objects. If you estimate at a single lag time, the estimation returns a single MEMM and not a list.

> So let's say my unbiased ensemble is the 0th ensemble and I want to find the unbiased implied timescale of 4 slow motions in my simulation at lagtime tau.
Then I input dtrajs, ttrajs, bias of all thermodynamic ensembles for dTRAM/TRAM.
Is time = dtram_obj[tau].models[0].timescales(4) the unbiased implied timescale considering all snapshots of all thermodynamic ensembles?

Yes, this will give you the four slowest implied timescales for the unbiased MSM resulting from a (D)TRAM estimation.

> If so, then what is the dtram_obj[tau].models[i].timescales(4) where i is the index of other thermodynamic ensembles?

These are MSMs for the other thermodynamic ensembles.

I hope this answers your questions. Please ask if anything else is unclear.

Best
Chris

**Comment by yunhuige** [comment]
Thanks for the explanation! I do have some follow-up questions:

1/ How does the scripts figure out which ensemble is the unbiased ensemble? I noticed there is a argument in dTRAM/TRAM method --`unbiased_state`. Is that where I should set my unbiased ensemble index for the scripts? 

2/ Let's imagine a situation where I don't have any unbiased ensembles. Then what is the implied timescales of any MSM of the returned list? Or what is the physical meaning of those implied timescales? There may be different bias in each ensemble and the implied timescales of any of these MSMs are the prediction considering all of snapshots from ensembles but with the bias in that ensemble? 

I just want to fully understand how this MEMM works and make sure I'm on the right track. Thanks for your time again!

Best,
Yunhui

**Comment by cwehmeyer** [comment]
> 1/ How does the scripts figure out which ensemble is the unbiased ensemble? I noticed there is a argument in dTRAM/TRAM method --unbiased_state. Is that where I should set my unbiased ensemble index for the scripts?

PyEMMA only infers the unbiased state if you use the `estimate_umbrella_sampling()` or `estimate_multi_temperature()` functions. If you use the `tram()` or `dtram()` functions, you need to specify the unbiased state (index) using the `unbiased_state` parameter.

> 2/ Let's imagine a situation where I don't have any unbiased ensembles. Then what is the implied timescales of any MSM of the returned list? Or what is the physical meaning of those implied timescales?

You only get MSMs for the thermodynamic states in which you have data. If you do not have unbiased data, the estimation will not yield an unbiased MSM: the `msm` getter in your MEMM object will return `None` and, thus, there are not implied timescales for the unbiased ensemble. Note that the MEMM will still contain the unbiased stationary distribution.

> There may be different bias in each ensemble and the implied timescales of any of these MSMs are the prediction considering all of snapshots from ensembles but with the bias in that ensemble?

I am not sure what you want to ask, here. Could you please rephrase your question?

Best
Chris

**Comment by yunhuige** [comment]
I think now I'm clear about the questions I asked. Thanks a lot!

Best,
Yunhui
