### ISSUE TITLE
import pyemma 'no module named regspatial'

### ISSUE THREAD

**Issue by trendelkampschroer** [markovmodel/PyEMMA#139]
Hi,

I just pulled the latest version of 'devel' and now I get the following error message on import

/home/mi/trendelkamp/work/git/pyemma/pyemma/coordinates/__init__.py in <module>()
     44 
     45 """
---> 46 from .api import *

/home/mi/trendelkamp/work/git/pyemma/pyemma/coordinates/api.py in <module>()
      8 from pyemma.util.annotators import deprecated
      9 
---> 10 from discretizer import Discretizer
     11 # io
     12 from io.feature_reader import FeatureReader

/home/mi/trendelkamp/work/git/pyemma/pyemma/coordinates/discretizer.py in <module>()
      4 import numpy as np
      5 
----> 6 from pyemma.coordinates.clustering.interface import AbstractClustering
      7 from pyemma.coordinates.transform.transformer import Transformer
      8 from pyemma.coordinates.io.reader import ChunkedReader

/home/mi/trendelkamp/work/git/pyemma/pyemma/coordinates/clustering/__init__.py in <module>()
     15 """
     16 
---> 17 from .assign import AssignCenters
     18 from .kmeans import KmeansClustering
     19 from .regspace import RegularSpaceClustering

/home/mi/trendelkamp/work/git/pyemma/pyemma/coordinates/clustering/assign.py in <module>()
      4 @author: marscher
      5 '''
----> 6 from pyemma.coordinates.clustering.interface import AbstractClustering
      7 from pyemma.msm.io import read_matrix
      8 import numpy as np

/home/mi/trendelkamp/work/git/pyemma/pyemma/coordinates/clustering/interface.py in <module>()
     10 from pyemma.util.files import mkdir_p
     11 
---> 12 import regspatial
     13 
     14 log = getLogger('Clustering')

ImportError: No module named regspatial

Please let us try to keep the code in the remote-repo in a working state. This is very important!

**Comment by marscher** [comment]
The tests did not fail on travis, thats why I just merged those changes.

Have you recompiled the extension?

eg. by:

python setup.py develop

Am 23.03.2015 um 10:22 schrieb Benjamin Trendelkamp-Schroer:

**Comment by marscher** [comment]
can not reproduce locally.

**Comment by trendelkampschroer** [comment]
I thought that I did not need to rerun python setup.py develop. Apparently I need to do it once I pull new extension modules from remote. 

My mistake.

**Comment by gph82** [comment]
Hi, I don't know if this is worth re-opening, but will the average user know that "I need to do it once I pull new extension modules from remote". Just ran into this myself.

If I have been updating PyEmma via git pulls all this time, how I am supposed to know that after this one pull, I have to run setup.py?

**Comment by marscher** [comment]
Am 27.03.2015 um 12:01 schrieb gph82:
> Hi, I don't know if this is worth re-opening, but will the average user
> know that "I need to do it once I pull new extension modules from
> remote". Just ran into this myself.
>
> If I have been updating PyEmma via git pulls all this time, how I am
> supposed to know that after this one pull, I have to run setup.py?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/139#issuecomment-86900902>.
>
yes. If there is any changed/new extension, you will have to recompile 
it. So if stuff is failing, you just invoke setup.py develop and be 
brave all the other times it works silently....

**Comment by gph82** [comment]
On 27.03.2015 12:32, Martin K. Scherer wrote:
> So if stuff is failing,
can we at least issue a warning so it is clear that "setup.py develop"
is the cure for the very specific "stuff is failing" diagnosis?
-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776
http://userpage.fu-berlin.de/gph82/
--

**Comment by marscher** [comment]
> can we at least issue a warning so it is clear that "setup.py develop"
> is the cure for the very specific "stuff is failing" diagnosis?

In principle you should always invoke it after a pull to be safe. If you
do not do, its your own fault - sorry. It would be very complicated to
issue a warning in this case and so it remains the hard burden of a
developer to invoke this tiny command.

**Comment by franknoe** [comment]
Well at least I did not know this until now. And I doubt that the 
average user is above my technical level.

Is it really unavoidable? I thought setup install should also recompile 
extensions.
Should we just generally recommend to use setup develop for developers? 
I end up always doing it, because then I know it works.

Am 27/03/15 um 14:21 schrieb Martin K. Scherer:
> > can we at least issue a warning so it is clear that "setup.py develop"
> > is the cure for the very specific "stuff is failing" diagnosis?
>
> In principle you should always invoke it after a pull to be safe. If you
> do not do, its your own fault - sorry. It would be very complicated to
> issue a warning in this case and so it remains the hard burden of a
> developer to invoke this tiny command.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/139#issuecomment-86938265>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by trendelkampschroer** [comment]
Yes it is unavoidable and we have put that recommendation explicitly into the development-workflow. 

http://www.pythonhosted.org/pyEMMA/DEVELOPMENT.html

**Comment by marscher** [comment]
The average user will never develop from git. Install mode is different,
since it installs a snapshot of the current branch (eg. devel to your
python path).

You could also install after every pull, but this will clutter your
pythonhome with tons of development version.

So develop mode is now recommended and also documented in development.rst

**Comment by franknoe** [comment]
Thanks!

Just to clarify: After the first pull, when I am working in my branch 
and say change extensions, how should I best rebuild them? Again python 
setup.py develop?



-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 27.03.2015 um 16:53 schrieb Frank Noe:
> Thanks!
> 
> Just to clarify: After the first pull, when I am working in my branch
> and say change extensions, how should I best rebuild them? Again python
> setup.py develop?
exactly - this is always safe to do.

**Comment by franknoe** [comment]
OK, thanks.
