### ISSUE TITLE
PyEMMA load and save objects

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#1392]
Where is the ability to save and load PyEMMA objects documented? I tried to find it by parsing throught the docs or tutorials, but I couldn't. Things like this should be easy to find.

**Comment by marscher** [comment]
The save method is documented for every class, which is serializable (http://www.emma-project.org/latest/search.html?q=save&check_keywords=yes&area=default). There is a tutorial on this in the legacy section (the old example notebooks, http://www.emma-project.org/latest/generated/storage.html?highlight=save) and it is part of the new tutorials (devel version: http://www.emma-project.org/devel/generated/03-msm-estimation-and-validation.html#persisting-and-restoring-estimators)
However the API docs are really lacking the load function. 

But I admit, that this is too fragmented and hidden. I will add a new section at the highest level to drag more attention.
