### ISSUE TITLE
Outdated installation document using miniconda

### ISSUE THREAD

**Issue by p16i** [markovmodel/PyEMMA#1399]
Hi, 

I've installed PyEmma using the curl command provide inside a directory, i.e. `~/projects/pyemma-tutorial`. It seems the script install miniconda at `$HOME/miniconda` ([REF][install_target]). 

However, the script suggests to enable the installed environment using `source activate pyemma`. Should it be `source $HOME/miniconda/bin/activate pyemma` instead?

Here's a quick checklist in what to include:

- [x] Include a detailed description of the bug or suggestion
- [ ] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [ ] PyEMMA version and operating system versions
- [ ] Minimal example if possible, a Python script, zipped input data (if not too large)

[install_target]: https://github.com/markovmodel/PyEMMA/blob/devel/install_miniconda%2Bpyemma.sh#L17

**Comment by marscher** [comment]
hi, 

actually the source command should be agnostic of any installation prefix. Do you need to specify the full path to make it work? Did you enable conda in your shell init script (e.g. bashrc)?

**Comment by marscher** [comment]
actually in recent conda versions, one should use conda activate.

**Comment by p16i** [comment]
I didn't add condo to my shell. That is probably the reason?

**Comment by marscher** [comment]
On 17.02.19 15:23, Pattarawat Chormai wrote:
> I didn't add condo to my shell. That is probably the reason?
>
yes

**Comment by p16i** [comment]
thanks! I'm going to close it.
