### ISSUE TITLE
Compiling PyEMMA in powerPC

### ISSUE THREAD

**Issue by cescgina** [markovmodel/PyEMMA#1402]
I'm trying to compile PyEMMA in cluster with powerPC architechture and it fails saying that it can't find the theobald library. If I comment the line that imports it (linked below) it compiles fine.

https://github.com/markovmodel/PyEMMA/blob/aab5cd2019dc321e20a73659fbc109f281d886d6/setup.py#L123

However when I'm trying to use the clustering module it crashes with the following error:

    ImportError: /gpfs/projects/bsc72/lib/site-packages-cte/pyemma/coordinates/clustering/_ext.cpython-36m-powerpc64le-linux-gnu.so: undefined symbol: msd_atom_major

I guess it's related to the ignored library. Has anyone had any experience with PyEMMA in an IBM cluster/ is it even possible to use it even with reduced funcionality?

**Comment by clonker** [comment]
I suppose you have mdtraj installed right? theobald is a part of it. Could you run 
```
find /path/to/your/miniconda/env/ -name "*theobald*"
```
to see where and if it is installed? Thanks!

**Comment by marscher** [comment]
https://github.com/mdtraj/mdtraj/issues/1432

**Comment by cescgina** [comment]
Yes, I have mdtraj installed but due to the issue that @marscher referenced I have only built a subset of the mdtraj functionalities and the theobald is not there. What I wanted to know it's if I can use some PyEMMA functionalities without it. I assume that anything that involves RMSD calculation will not work but I was asking if there is a way to avoid using in the clustering or if it's used for more than only rmsd calculations

**Comment by marscher** [comment]
This should be possible, but not without changing the kmeans code not to be compiled with rmsd support

Am 19. Februar 2019 18:35:22 MEZ schrieb Joan Francesc Gilabert <notifications@github.com>:
>Yes, I have mdtraj installed but due to the issue that @marscher
>referenced I have only built a subset of the mdtraj functionalities and
>the theobald is not there. What I wanted to know it's if I can use some
>PyEMMA functionalities without it. I assume that anything that involves
>RMSD calculation will not work but I was asking if there is a way to
>avoid using in the clustering or if it's used for more than only rmsd
>calculations

**Comment by clonker** [comment]
A hacky workaround would consist of (assuming you are working on tag v2.5.5):

- (optional) create a new environment in which you can build pyemma
    ```
    conda create -y -n test_this -c conda-forge gxx_linux-64 gcc_linux-64 cython mdtraj pybind11  msmtools
    conda activate test_this
    ```
- make changes to `setup.py`: Comment out lines 118, 123, 124
- make changes to `pyemma/coordinates/clustering/include/bits/metric_base_bits.h`: Change lines 10 and 11 (containing `#include <center.h>` and `#include <theobald_rmsd.h>`) to 
    ```cpp
    template<typename... Args> void inplace_center_and_trace_atom_major(Args&&...) {}
    template<typename... Args> float msd_atom_major(Args&&...) {}
    ```
- change dir into pyemma and `python setup.py install`

**Comment by cescgina** [comment]
Many thanks @clonker! That seems to work perfectly for my needs.
