### ISSUE TITLE
Not able to get the benzamidine-trypsin trajectory-link https://codeload.github.com/markovmodel/PyEMMA_IPython/zip/devel not working. Kindly provide the trajectory dataset 

### ISSUE THREAD

**Issue by anuginu** [markovmodel/PyEMMA#1405]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [ ] PyEMMA version and operating system versions
- [ ] Minimal example if possible, a Python script, zipped input data (if not too large)

**Comment by fabian-paul** [comment]
Dear  user,

thanks for your interest in PyEmma!

I'm sorry to inform you that the Trypsin-Benzamidine example for the estimation of Hidden Markov Models is no longer available. The Trypsin-Benzamidine example has been replaced with the analysis of simulation data of a pentapeptide. If you want to learn about hidden Markov modelling, please have a look at the [new tutorial notebooks](http://www.emma-project.org/v2.5.5/generated/07-hidden-markov-state-models.html). See also the publication [Introduction to Markov state modeling with the PyEMMA software](https://doi.org/10.33011/livecoms.1.1.5965)

If you're more interested in the analysis of protein-ligand trajectories, I highly recommend to have a look at enhanced sampling techniques and how they can be combined with Markov modeling. As a starting point, I would recommend our publication about TRAM, the [Transition-based reweighting analysis method](https://doi.org/10.1073/pnas.1525092113). Notebooks that demonstrate TRAM can be found on the Github page of our [recent PyEmma workshop](https://github.com/markovmodel/pyemma-workshop/tree/master/notebooks). (memm notebooks).

Best,
Fabian
