### ISSUE TITLE
Error upgrading to v2.5.5

### ISSUE THREAD

**Issue by moldyn-nagel** [markovmodel/PyEMMA#1411]
I am not able to upgrade from PyEMMA v2.5.2-v2.5.4 to v2.5.5. I am using
`pip3 install pyemma`
which raises following error:
- RuntimeError: pybind11 headers not found

I uninstalled all versions of pyemma and tried a upgrade of a clean installation from all three version (.2-.4) and a direct installation. The error remains.
Logs are attached. Thank you for your help.
[log.txt](https://github.com/markovmodel/PyEMMA/files/3138134/log.txt)

OS: Debian 9

**Comment by marscher** [comment]
This is indeed a mistake from our side. We forgot to package pybind11 in 
the source distribution on PyPI. You can install pybind11 prior 
upgrading, then it should work. Sorry for the inconvenience.

**Comment by moldyn-nagel** [comment]
Thank you for your help, but installing `pybind11` doesn't change anything for me. I appended a list with my python env.
[pip_list.txt](https://github.com/markovmodel/PyEMMA/files/3140936/pip_list.txt)

**Comment by marscher** [comment]
You received the same output?

**Comment by moldyn-nagel** [comment]
At least the same error message. I'll send on Monday the new log file.

**Comment by marscher** [comment]
are you installing into your home directory or into a system global 
directory?

**Comment by moldyn-nagel** [comment]
Here is the error message and I am installing into my home directory (see log /home/user/...).

[pyemma_log2.txt](https://github.com/markovmodel/PyEMMA/files/3151153/pyemma_log2.txt)

**Comment by marscher** [comment]
including pybind11 as a submodule used to be the more error safe way of shipping it...

**Comment by marscher** [comment]
@moldyn-nagel expect a new version soon! Sorry for the inconvenience.

**Comment by marscher** [comment]
fixed by #1412
