### ISSUE TITLE
I have the biased and unbiased data. How can I calculate ttrajs, dtraj and bias for thermo.tram? 

### ISSUE THREAD

**Issue by Moutoshi** [markovmodel/PyEMMA#1415]
Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [ ] PyEMMA version and operating system versions
- [ ] Minimal example if possible, a Python script, zipped input data (if not too large)

**Comment by marscher** [comment]
please read the tutorials here: http://www.emma-project.org/v2.5.5/ipython.html#multi-ensemble-markov-state-models

have a look at other issues, there are related to your general question: https://github.com/markovmodel/PyEMMA/issues?q=is%3Aissue+ttraj+is%3Aclosed
