### ISSUE TITLE
global setting for parallelisation

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#1417]
Is there an easy way to generally set `n_jobs` to some number that is not the number of visible cores on the system? As in I want to restrict all multiprocessing computations to say 4 cores or something along those lines?

**Comment by marscher** [comment]
You can export the environment variable PYEMMA_NJOBS to an integer.

**Comment by marscher** [comment]
http://www.emma-project.org/latest/Configuration.html#parallel-setup

**Comment by ppxasjsm** [comment]
Excellent! Thank you!
