### ISSUE TITLE
Trajectories with different box sizes

### ISSUE THREAD

**Issue by and-tos** [markovmodel/PyEMMA#1422]
I want to analyze multiple NVT trajectories with periodic boundary conditions. I was wondering if there could be any problem if these trajectories have different box sizes when calculating a contact map.

Thanks a lot for your help!

**Comment by marscher** [comment]
On 6/12/19 11:46 AM, andt88 wrote:
> I want to analyze multiple NVT trajectories with periodic boundary 
> conditions. I was wondering if there could be any problem if these 
> trajectories have different box sizes when calculating a contact map.
> 
> Thanks a lot for your help!

That should not be a problem, since periodic boundaries are assumed by 
default during computing distances.

**Comment by and-tos** [comment]
Sorry I may have not stated my question correctly. I was pointing towards the fact that the individual trajectories I pass to the source function have different box sizes. So I was worried that it might assume the box size of the first trajectory it reads for all other trajectories too.

**Comment by marscher** [comment]
mdtraj, which is used by the source function, reads the box size of 
every frame in your trajectory. Does that answer your question?

**Comment by and-tos** [comment]
yes! Thanks a lot!
