### ISSUE TITLE
Solving of eigenvalue problems yield bogus results with OpenBLAS-0.3.5 on SkyLake X CPUs

### ISSUE THREAD

**Issue by thempel** [markovmodel/PyEMMA#1426]
Apparently, there is a problem with some dependencies that cause the eigendecomposition of sparse matrices to fail. In our debug-session, @marscher figured out that at least with newer versions of scipy / openblas, unit tests with sparse matrices fail. Eigendecompositions cannot be computed or produce random results. The issue will be reported upstream. 

A conda environment yaml file that reproduces the issue is attached [here](https://github.com/markovmodel/PyEMMA/files/3335589/env.zip). 
However, the issue could be reproduced with any clean installation of pyemma.

The problem can be avoided by using dense matrices (default behavior).

**Comment by thempel** [comment]
We pinned down the problem to a specific version of OpenBLAS, namely 3.8 from conda-forge. It seems like build number 7 is broken, while number 10 has been tested to work with PyEMMA.
```
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
```

**Comment by thempel** [comment]
Could be fixed with 
```
>>> conda install blas
The following NEW packages will be INSTALLED:

  blas               conda-forge/linux-64::blas-2.10-mkl
  liblapacke         conda-forge/linux-64::liblapacke-3.8.0-10_mkl

The following packages will be UPDATED:

  libblas                                  3.8.0-7_openblas --> 3.8.0-10_mkl
  libcblas                                 3.8.0-7_openblas --> 3.8.0-10_mkl
  liblapack                                3.8.0-7_openblas --> 3.8.0-10_mkl

```

**Comment by marscher** [comment]
quoting @isuruf 
> openblas 0.3.5 had issues with SkyLake X cpus. dgemm was broken there. 
I'll move 0.3.5 openblas to broken

This means, that we will not get any more broken installations, which is very good. But I have no clue how to deal with the problem, that some installations are already broken. We can not reach people properly and in the meantime they will have bogus results.
