### ISSUE TITLE
Error during featurizer step of tutorial notebook 00

### ISSUE THREAD

**Issue by mandar5335** [markovmodel/PyEMMA#1428]
Hi,
I am running tutorials notebook-00, but I am stuck at the step of featurizer due to the following error:

---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)

~/anaconda3/lib/python3.7/site-packages/pyemma/coordinates/data/util/traj_info_cache.py in __init__(self, database_filename)
    156             import sqlite3
    157             from pyemma.coordinates.data.util.traj_info_backends import SqliteDB
--> 158             self._database = SqliteDB(self.database_filename)
    159         except ImportError:
    160             warnings.warn("sqlite3 package not available, persistant storage of trajectory info not possible!")

~/anaconda3/lib/python3.7/site-packages/pyemma/coordinates/data/util/traj_info_backends.py in __init__(self, filename, clean_n_entries)
    120         self._database = sqlite3.connect(filename if filename is not None else ":memory:",
    121                                          detect_types=sqlite3.PARSE_DECLTYPES, timeout=5,
--> 122                                          isolation_level=None)
    123         self.filename = filename
    124 

OperationalError: unable to open database file

I have sqlite3 installed, and it shows in the bin folder of anaconda also. I have removed conda and reinstalled, but the error persists.
Any suggestion to solve this issue will be really helpful. I have attached condalist.txt file which contains an output of "conda list" command. 

details:
Ubuntu 18.04, pyEMMA 2.5.6
conda installation.

Thanks,
Mandar Kulkarni
[condalist.txt](https://github.com/markovmodel/PyEMMA/files/3503888/condalist.txt)

**Comment by clonker** [comment]
Hi, can you check your `~/.pyemma` directory whether you have a `traj_info.sqlite3` file in there? If you, try deleting it and check the permissions of that folder. If it does not exist you can try creating it.

A hacky workaround is just removing sqlite3 from your environment, it should gracefully fall back to an in-memory solution.

If that doesn't help, is this the full stack trace? If not, can you post the full thing?

**Comment by mandar5335** [comment]
Hi,
Thanks for your suggestions. There was no ~/.pyemma folder, so I created it with necessary permissions.  Still no luck !! 
Please see the full stack trace below:

---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-5-056eba3d775a> in <module>
      1 torsions_feat = pyemma.coordinates.featurizer(pdb)
      2 torsions_feat.add_backbone_torsions(cossin=True, periodic=False)
----> 3 torsions_data = pyemma.coordinates.load(files, features=torsions_feat)
      4 labels = ['backbone\ntorsions']
      5 

~/anaconda3/lib/python3.7/site-packages/pyemma/coordinates/api.py in load(trajfiles, features, top, stride, chunksize, **kw)
    241             and (any(isinstance(item, (list, tuple, str)) for item in trajfiles)
    242                  or len(trajfiles) is 0)):
--> 243         reader = create_file_reader(trajfiles, top, features, chunksize=cs, **kw)
    244         trajs = reader.get_output(stride=stride)
    245         if len(trajs) == 1:

~/anaconda3/lib/python3.7/site-packages/pyemma/coordinates/data/util/reader_utils.py in create_file_reader(input_files, topology, featurizer, chunksize, **kw)
    109 
    110                 reader = FeatureReader(input_list, featurizer=featurizer, topologyfile=topology,
--> 111                                        chunksize=chunksize)
    112             elif suffix in ('.npy', '.npz'):
    113                 reader = NumPyFileReader(input_list, chunksize=chunksize)

~/anaconda3/lib/python3.7/site-packages/pyemma/coordinates/data/feature_reader.py in __init__(self, trajectories, topologyfile, chunksize, featurizer)
     92         self._is_reader = True
     93         self.topfile = topologyfile
---> 94         self.filenames = trajectories
     95         self._return_traj_obj = False
     96 

~/anaconda3/lib/python3.7/site-packages/pyemma/coordinates/data/_base/datasource.py in filenames(self, filename_list)
    120                 for filename in filename_list:
    121                     if config.use_trajectory_lengths_cache:
--> 122                         info = TrajectoryInfoCache.instance()[filename, self]
    123                     else:
    124                         info = self._get_traj_info(filename)

~/anaconda3/lib/python3.7/site-packages/pyemma/coordinates/data/util/traj_info_cache.py in instance()
    142             else:
    143                 filename = os.path.join(config.cfg_dir, "traj_info.sqlite3")
--> 144             TrajectoryInfoCache._instance = TrajectoryInfoCache(filename)
    145 
    146         return TrajectoryInfoCache._instance

~/anaconda3/lib/python3.7/site-packages/pyemma/coordinates/data/util/traj_info_cache.py in __init__(self, database_filename)
    156             import sqlite3
    157             from pyemma.coordinates.data.util.traj_info_backends import SqliteDB
--> 158             self._database = SqliteDB(self.database_filename)
    159         except ImportError:
    160             warnings.warn("sqlite3 package not available, persistant storage of trajectory info not possible!")

~/anaconda3/lib/python3.7/site-packages/pyemma/coordinates/data/util/traj_info_backends.py in __init__(self, filename, clean_n_entries)
    120         self._database = sqlite3.connect(filename if filename is not None else ":memory:",
    121                                          detect_types=sqlite3.PARSE_DECLTYPES, timeout=5,
--> 122                                          isolation_level=None)
    123         self.filename = filename
    124 

OperationalError: unable to open database file

-------------------------------------------------------------------------------------------------------------------------

Any further suggestions to get pyemma working will be really appreciated. 
Thanks again,
Mandar Kulkarni

P.S. I have again uninstalled and reinstalled conda, so attached a new cond list output. But the 
[condalist_new.txt](https://github.com/markovmodel/PyEMMA/files/3513370/condalist_new.txt)
same problem persists.

**Comment by thempel** [comment]
Not sure what is causing this right now, did you install it using only the provided installation command? If not, could you try? 
```conda create -n pyemma_tutorials -c conda-forge pyemma_tutorials``` 

(More details about using conda environments, if needed, are [here](https://github.com/markovmodel/pyemma_tutorials#installation)  and [here](https://github.com/markovmodel/pyemma_tutorials#usage)).

If this doesn't work, could you please upload a yaml file of this environment? (`conda env export > environment.yml`). This can be directly imported with conda, so we could test it locally.

**Comment by mandar5335** [comment]
Hi, thanks for the reply. I did not installed pyemma-tutorials using above command but downloaded from this page
https://github.com/markovmodel/pyemma_tutorials 

I have installed now pyemma_tutorials
[environment.yml.txt](https://github.com/markovmodel/PyEMMA/files/3516046/environment.yml.txt)

 with above command and by setting environment as suggested on those pages. 

But still, the same error persists. I have attached the yaml file of the environment. By any chance, could it be related to the conda version? I have installed a new version of conda (2019.07) recently.

Thanks,
Mandar Kulkarni

**Comment by clonker** [comment]
You can try the following: Before doing anything with pyemma, call
```
import pyemma
pyemma.util.config.cfg_dir = "/home/mandar/.pyemma"
```

**Comment by thempel** [comment]
I just imported the environment from your yaml file and I cannot reproduce the error. Setting up a featurizer with backbone torsions works as expected.

**Comment by mandar5335** [comment]
@clonker and @thempel  thanks a lot for your answers.  
The problem was arising due to a faulty setting of default python (from /usr/bin). ~/.bashrc contains the anaconda path, but somehow default python was from /usr/bin

I changed default python to one from anaconda and now everything is working fine. 

Thanks again,
Mandar Kulkarni
