### ISSUE TITLE
Problem with PCCA+

### ISSUE THREAD

**Issue by tanmoyp635** [markovmodel/PyEMMA#1432]
Dear pyEMMA users,
                      It's Tanmoy from IIT Kharagpur, India. I was trying the MSM. But I am having some problem while executing PCCA+. While executing  :

## Cluster into macrostate 
nstates = 2
msm.pcca(nstates)
metastable_traj = msm.metastable_assignments[dtrajs_concatenated]

I am having the following error

**index 198 is out of bounds for axis 0 with size 196**

 It is coming due numpy array miss match, I guess. But I don't know how to fix this. Can you please help. I have attached the file with this mail.

regard
Tanmoy

**Comment by marscher** [comment]
Dear Tanmoy,

you should use dtrajs_active, which are restricted to the active set (e.g. largest connected set of states in all of your trajectories), to perform the mapping to metastable_assignments.

Kind regards,
Martin
