### ISSUE TITLE
version :  Pyemma 2.5.7   TypeError: expected str, bytes or os.PathLike object, not list

### ISSUE THREAD

**Issue by srp106** [markovmodel/PyEMMA#1436]
Hello Pyemma users,

I am running a notebook that located in pyemma tutorials (http://hpc3:8888/notebooks/pentapeptide_msm.ipynb).  and getting following error. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-08a789f1eac7> in <module>
----> 1 coor.save_trajs(inp, pcca_samples, outfiles = ['./data/pcca1_10samples.xtc','./data/pcca2_10samples.xtc','./data/pcca3_10samples.xtc','./data/pcca4_10samples.xtc'])

~/miniconda3/envs/pyemma/lib/python3.7/site-packages/pyemma/coordinates/api.py in save_trajs(traj_inp, indexes, prefix, fmt, outfiles, inmemory, stride, verbose)
    842         import os
    843 
--> 844         _, fmt = os.path.splitext(traj_inp.filenames[0])
    845     else:
    846         fmt = '.' + fmt

[error.txt](https://github.com/markovmodel/PyEMMA/files/3660921/error.txt)

~/miniconda3/envs/pyemma/lib/python3.7/posixpath.py in splitext(p)
    120 
    121 def splitext(p):
--> 122     p = os.fspath(p)
    123     if isinstance(p, bytes):
    124         sep = b'/'

TypeError: expected str, bytes or os.PathLike object, not list

Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion : added
- [ ] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue): added
- [ ] PyEMMA version and operating system versions : 2.5.7
- [ ] Minimal example if possible, a Python script, zipped input data (if not too large): pentapeptide_msm tutorials

**Comment by thempel** [comment]
Hello srp106,
Which notebook is this exactly? (The link you posted is a local one and can only be called from your machine.)  Can you please post the line that defines `inp = `? It would help us to identify the problem if you could provide a minimal example that reproduces the error message.

**Comment by thempel** [comment]
I am closing this issue as I assume it has been resolved. Feel free to re-open.
