### ISSUE TITLE
Custom feature for global angle (dihedral) caluclation using Center of mass atoms. 

### ISSUE THREAD

**Issue by srp106** [markovmodel/PyEMMA#1437]
Hello pyemma users,

Since I am new to pyemma. Can anyone help me to build and customize the feature for global angle (dihedral) calculations using the center of mass atoms ?.  Please share an example template, so that I can modify it as per my requirement.  

Thank you. 

Thanks for submitting an issue!

Here's a quick checklist in what to include:

- [ ] Include a detailed description of the bug or suggestion
- [ ] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [ ] PyEMMA version and operating system versions
- [ ] Minimal example if possible, a Python script, zipped input data (if not too large)

**Comment by marscher** [comment]
You can have a look in mdtraj on how to compute the dihedral based on positions. You then need to define a function, taking the mdtraj.Trajectory object and transform it into a 2d array.

There is tiny example over there: http://www.emma-project.org/latest/api/generated/pyemma.coordinates.data.CustomFeature.html?highlight=customfeature

https://github.com/mdtraj/mdtraj/blob/e41a92299990fa6586a8f35739653a1801e33c31/mdtraj/geometry/dihedral.py

**Comment by vas2201** [comment]
Really Appreciate your help.
