### ISSUE TITLE
linking regspace extension against mdtraj on windows fails

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#144]
see appveyor build:

https://ci.appveyor.com/project/marscher/pyemma/build/1.0.281/job/gb9vu3q88jm98tw8#L220

**Comment by marscher** [comment]
@rmcgibbo linkage against mdtraj.capi should be correct, would be kind if you take a short look:

relevant line in setup:
https://github.com/markovmodel/PyEMMA/blob/db071bf9248422ea6fbab39c5fdcc0f7a7732c35/setup.py#L110

output of linker:
LINK : fatal error LNK1181: cannot open input file 'theobald.lib'

**Comment by rmcgibbo** [comment]
I'm not sure.

We currently don't have the msmbuilder appveyor working, for a different (but unknown) reason. I always do our windows debugging and build before our releases on a EC2 virtual machine, because it usually requires some tinkering to figure out.

**Comment by fabian-paul** [comment]
solved by pull request  #178

**Comment by marscher** [comment]
Am 01.04.2015 um 15:34 schrieb fabian-paul:
> Closed #144 <https://github.com/markovmodel/PyEMMA/issues/144>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/144#event-270626793>.
>
Your PR actually fixed the linkage problem on Windows. The failed 
because other tests failed (like 7 tests on Windows and 1 unrelated on 
Linux)

Please merge it.

The output of the tests can be viewed if clicking on the status button 
next to the commit hash in the PR pane of Github.

**Comment by fabian-paul** [comment]
I don't understand. What do I have to merge?

**Comment by marscher** [comment]
Am 01.04.2015 um 16:46 schrieb fabian-paul:
> I don't understand. What do I have to merge?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/144#issuecomment-88510987>.
>
#178. Its working. Dunno why you have just closed it.

**Comment by marscher** [comment]
sorry my fault :)

**Comment by marscher** [comment]
@rmcgibbo under windows one have to use a libprefix instead of linking against "theobald" it becomes then "libtheobald", hope this helps!
