### ISSUE TITLE
setup.py needs  --remote option in git submodule update?

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#1446]
When trying to run `python setup.py develop`, I get the following errors:
```
fatal: reference is not a tree: e43e1cc01ae6d4e4e5ba10557a057d7f3d5ece0d
Unable to checkout 'e43e1cc01ae6d4e4e5ba10557a057d7f3d5ece0d' in submodule path 'ext/pybind11'
Traceback (most recent call last):
  File "setup.py", line 331, in <module>
    subprocess.check_call(cmd.format(mod=m).split(' '))
  File "/home/fab/opt/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', 'ext/pybind11']' returned non-zero exit status 1.
```
Looking into ext/pybind11, I realized that the directory was empty.
I fixed this by replacing in the command
"git submodule update --init {mod}"
in setup.py by
"git submodule update --remote --init {mod}"

Can you confirm that this is the correct fix?

**Comment by clonker** [comment]
On which platform are you? Did you try this from a clean clone? For me everything works as-is.

**Comment by fabian-paul** [comment]
Yeah, something messed up with my branches. [Downloaded a fresh copy of the project,](https://xkcd.com/1597/), then the error goes away...
