### ISSUE TITLE
make features hashable to avoid to calculate the same feature twice

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#145]
Currently the user is allowed to add the same feature (with same selection/indexes) to the featurizer. To avoid this, we have to implement __hash__ functions in the feature classes properly, so they can be distinguished by set class (which will then remove duplicates).

**Comment by trendelkampschroer** [comment]
+1 for that

**Comment by marscher** [comment]
see #153

**Comment by marscher** [comment]
done in #162
