### ISSUE TITLE
Extracting representative structures from the metastable states 

### ISSUE THREAD

**Issue by eric-jm-lang** [markovmodel/PyEMMA#1461]
Hello,

Once the metastable states have been identified with pcca, it is possible to get structure samples for each of the metastable state using `msm.sample_by_distributions()`

The metastable states include structures that are in the low energy bassin of the state, but also include high energy conformations that are away from the energy minima and connect to the other metastable states. 

I would like to extract sample conformations that are representative of the energy minima of each metastable states to calculate some properties. I am not really interested in the high energy conformations that, I feel, will simply increase the incertitude around the mean value of the properties I am interested in.

Is there a way to do that, for example to sample only the conformations of a metastable state that are within 1 kT of the energy minima of the state?

Alternatively, does `msm.sample_by_distributions()` extract conformations randomly from a state or does it extract conformations in a representative manner based on the density distribution for the region of the energy landscape covered by the metastable state? In which case the number of high energy conformations would be small compare to the number of the low energy conformation sampled.

Also, is there a way to select a single structure for each metastable state which as the lowest energy of the state?

Many thanks in advance,

Eric

**Comment by thempel** [comment]
This method `msm.sample_by_distributions(distributions, nsample)` samples from the distribution that you use as argument, e.g. metastable distributions from PCCA. So it's not per se a uniform sample from a crisp state assignment except you define it like that. If you want to restrict your sample to states that have a low energy, you could for example define a threshold above which you set the probability to zero and define some hand-made distributions accordingly. (No warranty about how meaningful the results are, but I believe it comes close to what you are describing). 

In my experience however, there are multiple factors that can cause representative structures to be non-optimal or different than expected from the free energy plot. For example, this could be degrees of freedom that haven't been modeled, metastable basins in high dimensional space that you don't see in the projected 2D free energy landscape, or sometimes I observe single PCCA states that account for all states that aren't included in the other PCCA states (like a state of "leftovers"). 

>  Also, is there a way to select a single structure for each metastable state which as the lowest energy of the state?

You can find the cluster center that is closest to that minimum by its coordinates and extract frames with that cluster assignment. The pyemma discretizers have a method for that with the nice name `sample_indexes_by_cluster`, here's the [reference](http://www.emma-project.org/v2.5.7/api/generated/pyemma.coordinates.clustering.KmeansClustering.html#pyemma.coordinates.clustering.KmeansClustering.sample_indexes_by_cluster).

**Comment by eric-jm-lang** [comment]
Many apologies for not replying earlier and many thanks for your help and suggestions, using `msm.sample_by_distributions(distributions, nsample)` proved to be sufficient.
Thanks again,
Eric
