### ISSUE TITLE
No possibility to understand what are the clusters considered for HMM

### ISSUE THREAD

**Issue by pl992** [markovmodel/PyEMMA#1463]
I've checked deeply the documentation but I couldn't find any method that gives the possibility to get the active sets used for building the metastable states in a HMM.
I'll try to be clearer:
Starting from discrete trajectories (discretized by let's say 1000 clusters) I built a HMM. This HMM considers only a subset of the previous set (so let's say only 500 clusters). I would like to know by which clusters are made the metastable sets but since I don't have the information of which clusters are used (which are the active sets) I cannot use the output of `hmsm.metastable_sets` (I cannot relate the numbers provided to the cluster numbers I built). 
If this function isn't present it would be great having this information, if it is present then I would report that from the documentation isn't clear how to get this information.
Thank you

**Comment by thempel** [comment]
Are you looking for [`hmsm.observable_set`?](http://www.emma-project.org/latest/api/generated/pyemma.msm.MaximumLikelihoodHMSM.html#pyemma.msm.MaximumLikelihoodHMSM.observable_set)

**Comment by pl992** [comment]
indeed, thank you very much. Just a personal opinion, I still think it's quite important information and it isn't that easy to find in the documentation. 
Anyway I'd like to congratulate with all the developers for such a powerful and complete tool!
