### ISSUE TITLE
include path for libstdc++ headers not found

### ISSUE THREAD

**Issue by RobertArbon** [markovmodel/PyEMMA#1468]
Hi folks, 

I'm getting this error message when I'm trying to do a developer install of PyEMMA. I'm up to date on the develop branch. 

```
building 'pyemma.coordinates.clustering._ext' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/robertarbon/opt/miniconda3/envs/pyemma_dev/include -arch x86_64 -I/Users/robertarbon/opt/miniconda3/envs/pyemma_dev/include -arch x86_64 -I/usr/local/opt/readline/include -I/Users/robertarbon/opt/miniconda3/envs/pyemma_dev/lib/python3.7/site-packages/mdtraj/core/lib -I/Users/robertarbon/Software/myPyEMMA/ext/pybind11/include -Ipyemma/coordinates/clustering/include -I/Users/robertarbon/opt/miniconda3/envs/pyemma_dev/lib/python3.7/site-packages/numpy/core/include -I/Users/robertarbon/opt/miniconda3/envs/pyemma_dev/include/python3.7m -c pyemma/coordinates/clustering/src/clustering_module.cpp -o build/temp.macosx-10.7-x86_64-3.7/pyemma/coordinates/clustering/src/clustering_module.o -DVERSION_INFO="2.4+2191.g44a87631.dirty" -std=c++14 -fvisibility=hidden -g0 -DNDEBUG
clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
In file included from pyemma/coordinates/clustering/src/clustering_module.cpp:5:
In file included from pyemma/coordinates/clustering/include/regspace.h:12:
pyemma/coordinates/clustering/include/Clustering.h:8:10: fatal error: 'cstdlib' file not found
#include <cstdlib>
         ^~~~~~~~~
1 error generated.

```

I'm using the latest version of clang/gcc although there is a problem with the install of gcc, the `--with-gxx-include-dir` flag points to a missing directory. I've asked about that [here](https://apple.stackexchange.com/questions/329446/gcc-with-gxx-include-dir-is-set-to-ios-11-4-simulator).  

Do you think this a problem with PyEMMA or my gcc?  If the former is there anything you suggest?  I've had a similar problem before here: #1195. 

As I understand it, the headers for the clustering extension are specified explicitly as coming from pybind11, mdtraj etc. which is why I ask here. 

I'm on the latest version of Catalina (10.15.6). 

My GCC: 
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Conda list and full error message attached:

[conda_list.txt](https://github.com/markovmodel/PyEMMA/files/5041640/conda_list.txt)
[setup.txt](https://github.com/markovmodel/PyEMMA/files/5041642/setup.txt)

Thanks in advance.

**Comment by clonker** [comment]
This might indeed be a problem with our setup. Can you try [this version](https://github.com/clonker/PyEMMA/blob/setup_fix/setup.py)?
Basically what it complains about is that it cannot find the c++ standard library headers which should be included/linked against.

**Comment by RobertArbon** [comment]
Thanks for that!  It got a bit further but encountered a similar problem: 

```
In file included from pyemma/coordinates/clustering/src/clustering_module.cpp:5:
In file included from pyemma/coordinates/clustering/include/regspace.h:12:
In file included from pyemma/coordinates/clustering/include/Clustering.h:8:
In file included from /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cstdlib:85:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/stdlib.h:93:15: fatal error: 'stdlib.h' file not found
#include_next <stdlib.h>
              ^~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1

```
This is particularly weird though as 'stdlib.h' is definitely in the folder `/Library/Developer/CommandLineTools/usr/include/c++/v1/`

**Comment by clonker** [comment]
That is puzzeling! If you havent done so already, can you try reinstalling xcode command line tools?
Something like this should trigger a clean install:
```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
```

**Comment by RobertArbon** [comment]
Thanks. OK, did that (while you were replying) and now I get this with your setup.py

```
g++ -bundle -undefined dynamic_lookup -L/Users/robertarbon/opt/miniconda3/envs/pyemma_dev/lib -arch x86_64 -L/Users/robertarbon/opt/miniconda3/envs/pyemma_dev/lib -arch x86_64 -L/usr/local/opt/readline/lib -I/usr/local/opt/readline/include -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/pyemma/coordinates/clustering/src/clustering_module.o -L/Users/robertarbon/opt/miniconda3/envs/pyemma_dev/lib/python3.7/site-packages/mdtraj/core/lib -ltheobald -o build/lib.macosx-10.7-x86_64-3.7/pyemma/coordinates/clustering/_ext.cpython-37m-darwin.so -stdlib=libc++ -mmacosx-version-min=10.7
ld: in /Users/robertarbon/opt/miniconda3/envs/pyemma_dev/lib/python3.7/site-packages/mdtraj/core/lib/libtheobald.a(theobald_rmsd.o), could not parse object file /Users/robertarbon/opt/miniconda3/envs/pyemma_dev/lib/python3.7/site-packages/mdtraj/core/lib/libtheobald.a(theobald_rmsd.o): 'Unknown attribute kind (62) (Producer: 'LLVM9.0.1' Reader: 'LLVM APPLE_1_1103.0.32.62_0')', using libLTO version 'LLVM version 11.0.3, (clang-1103.0.32.62)' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'g++' failed with exit status 1
```

I still get the original error message with the devel branch of PyEMMA. 

my gcc is: 

```
(pyemma_dev) ➜  myPyEMMA git:(setup_fix) ✗ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
this folder exists: `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include` but this doesn't `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++`

**Comment by clonker** [comment]
Ok so the devel setup seems borked in any case. In the updated version from my branch it cannot read a symbol from an already compiled binary. This is due to an incompatibility of LLVM versions if I am not mistaken (produced by LLVM9, you got LLVM11 running). 
Can you try to install `conda install -c conda-forge compilers` and see with `which clang` where it points? it then should point to a binary inside your environment and then you can try again to compile.
Sorry that this is causing so much headache BTW!

**Comment by RobertArbon** [comment]
Boom. That worked!  Ta da! I tried it on the devel branch. Not your fix version. 

`which clang` pointed to the conda clang (nice phrase), I installed bhmm and msmtools and there we go it worked! 

Thanks for your help.

**Comment by clonker** [comment]
Cool I am glad! Out of curiosity, does it also work with the branch version? I feel like it might be a bit more future-proof.

**Comment by RobertArbon** [comment]
Yes, both work. Thanks again.  I didn't know you could specify compilers in conda envs as well. That seems really useful.
