### ISSUE TITLE
Description of SideChainTorsions with cossin=True is incorrect

### ISSUE THREAD

**Issue by firsc** [markovmodel/PyEMMA#1471]
Hello,

I think I found a small bug in the `SideChainTorsions` class from `pyemma.coordinates.data.featurization.angles`. The [description](https://github.com/markovmodel/PyEMMA/blob/44a876314222b101a2ff4cf9d5b9e4da65e9f1ed/pyemma/coordinates/data/featurization/angles.py#L215) does not match the actual sidechain angles, if `cossin=True` (In my case there are duplicate dihedral names and some others, particularly higher order chi angles, are missing).

```python
    def describe(self):
        getlbl = lambda at: '%i %s %i' % (at.residue.chain.index, at.residue.name, at.residue.resSeq)
        prefixes = []
        for lengths, label in zip(self._prefix_label_lengths, self.options):
            if self.cossin:
                lengths *= 2
            prefixes.extend([label.upper()] * lengths)

        if self.cossin:
            cossin = ('COS({dih} {res})', 'SIN({dih} {res})')
            labels = [s.format(dih=prefixes[j+len(cossin)*i], res=getlbl(self.top.atom(ires[1])))
                      for i, ires in enumerate(self.angle_indexes)
                      for j, s in enumerate(cossin)]
        else:
            labels = ['{dih} {res}'.format(dih=prefixes[i], res=getlbl(self.top.atom(ires[1])))
                      for i, ires in enumerate(self.angle_indexes)]

        return labels
```

If I understand this correctly, this might be because of `lengths *= 2`, which should unnecessary since the list comprehension for `labels` already loops over both cos and sin strings (?)

Suggestion: Delete `lengths *= 2`.

I am using the latest pyEMMA version.

Cheers

**Comment by thempel** [comment]
Thanks for reporting this. It is indeed a bug in how the description list is made. I fixed it a while ago with #1457, but we haven't done a new Conda release so far. Will do that very soon! In the time being, you can [install the development version](http://www.emma-project.org/latest/INSTALL.html#for-developers) if you want.
