### ISSUE TITLE
Unclear  documentation for attribute active_state_indexes of pyemma.msm.MaximumLikelihoodMSM

### ISSUE THREAD

**Issue by pl992** [markovmodel/PyEMMA#1473]
The output is a list of 2D-arrays where is unclear what the second column represents. My guess is that the first column are the cluster indices but I'm not entirely sure. Moreover the `core_set ` attribute doesn't return anything... this has been tested also with your notebooks for tutorials (like 03-msm-estimation-validation)

**Comment by clonker** [comment]
For each state, `active_state_indexes` contains all trajectory and time indexes where this state occurs.
Each matrix has a number of rows equal to the number of occurrences of the corresponding state, with rows consisting of a tuple `(i, t)`, where i is the index of the trajectory and t is the time index within the trajectory.

`core_set` is only relevant if you are using milestoning.
