### ISSUE TITLE
HMM building finds a not weakly connected input matrix

### ISSUE THREAD

**Issue by pl992** [markovmodel/PyEMMA#1474]
Starting from a `pyemma.msm.MaximumLikelihoodMSM` I want to build a hmm with a defined number of states. I get the following error when I try to do it:
```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-97-3166dcd0dc21> in <module>
----> 1 hmm = msm.hmm(5)

~/miniconda3/lib/python3.7/site-packages/pyemma/msm/estimators/_msm_estimator_base.py in hmm(self, nhidden)
    860         estimator = MaximumLikelihoodHMSM(lag=self.lagtime, nstates=nhidden, msm_init=self,
    861                                           reversible=self.is_reversible, dt_traj=self.dt_traj)
--> 862         estimator.estimate(self.discrete_trajectories_full)
    863         return estimator.model
    864 

~/miniconda3/lib/python3.7/site-packages/pyemma/_base/estimator.py in estimate(self, X, **params)
    405         if params:
    406             self.set_params(**params)
--> 407         self._model = self._estimate(X)
    408         # ensure _estimate returned something
    409         assert self._model is not None

~/miniconda3/lib/python3.7/site-packages/pyemma/msm/estimators/maximum_likelihood_hmsm.py in _estimate(self, dtrajs)
    265         self._dtrajs_obs = dtrajs
    266         self.set_model_params(P=transition_matrix, pobs=observation_probabilities,
--> 267                               reversible=self.reversible, dt_model=self.timestep_traj.get_scaled(self.lag))
    268 
    269         # TODO: perhaps remove connectivity and just rely on .submodel()?

~/miniconda3/lib/python3.7/site-packages/pyemma/msm/models/hmsm.py in set_model_params(self, P, pobs, pi, reversible, dt_model, neig)
     94 
     95         """
---> 96         _MSM.set_model_params(self, P=P, pi=pi, reversible=reversible, dt_model=dt_model, neig=neig)
     97         # set P and derived quantities if available
     98         if pobs is not None:

~/miniconda3/lib/python3.7/site-packages/pyemma/msm/models/msm.py in set_model_params(self, P, pi, reversible, dt_model, neig)
    148         self.update_model_params(P=P)
    149         # pi might be derived from P, if None was given.
--> 150         self.update_model_params(pi=pi, dt_model=dt_model, neig=neig)
    151 
    152     def __eq__(self, other):

~/miniconda3/lib/python3.7/site-packages/pyemma/_base/model.py in update_model_params(self, **params)
     77         for key, value in params.items():
     78             if not hasattr(self, key):
---> 79                 setattr(self, key, value)  # set parameter for the first time.
     80             elif getattr(self, key) is None:
     81                 setattr(self, key, value)  # update because this parameter is still None.

~/miniconda3/lib/python3.7/site-packages/pyemma/msm/models/msm.py in pi(self, value)
    284         if value is None and self.P is not None:
    285             from msmtools.analysis import stationary_distribution as _statdist
--> 286             value = _statdist(self.P)
    287         elif value is not None:
    288             # check sum is one

~/miniconda3/lib/python3.7/site-packages/msmtools/analysis/api.py in stationary_distribution(T)
    342     # is the stationary distribution unique?
    343     if not is_connected(T, directed=False):
--> 344         raise ValueError("Input matrix is not weakly connected. "
    345                          "Therefore it has no unique stationary "
    346                          "distribution. Separate disconnected components "

ValueError: Input matrix is not weakly connected. Therefore it has no unique stationary distribution. Separate disconnected components and handle them separately

```

The `msm.active_state` contains all the states used for the input. I checked the connection of `msm.P` using  `scipy.sparse.csgraph.connected_components(msm.P)` and it does say it's connected. So which matrix is it referring to? How could I find those states that are said to be disconnected? Or how could I separate the disconnected components to handle them separately?

**Comment by clonker** [comment]
The problem is not the `msm.P` but rather the hidden transition matrix of the HMM you were trying to estimate - it has disconnected hidden states. You can try to reduce the number of hidden states, that should help. You stumble into this due to a bit unfortunate implementation detail. If you are feeling adventurous, there is a more stable and up-to-date implementation [here](https://deeptime-ml.github.io/notebooks/hmm.html) which eventually will be backported into pyemma and can currently be installed via `pip install git+https://github.com/deeptime-ml/deeptime-ml.git`.

**Comment by thempel** [comment]
I'd like to add that the estimation of an HMM from an MSM using `msm.hmm()` is possible but also requires validation measures for the HMM, like the implied timescales test. So the method `msm.hmm()` is a bit problematic as it suggests that the computed HMM is automatically valid if the MSM `msm` was valid, which is not the case. In my eyes we should deprecate and eventually remove the method. So what you could do instead is, after the analyses that you did with the MSM, start again with implied timescales estimation with HMMs. I'm assuming that the MSM helps you to determine the number of hidden states and to get an idea of the implied timescales that you refine by adding the HMM layer. Apart from the validation, estimating the HMM directly from the data has the advantage of the full HMM API, so you can actually control what you are doing. Under the hood, pyemma's HMM estimation also uses a regular MSM as an initial guess, which is probably what you were planning to do. If you want even more control, @clonker's recommendation to install deeptime is an excellent idea :)

**Comment by pl992** [comment]
Thank you very much! scikit-time is really interesting!
