### ISSUE TITLE
save_trajs outfile not accepting list - Jupyter Tutorial

### ISSUE THREAD

**Issue by Dan-Burns** [markovmodel/PyEMMA#1475]
I'm following the pentapeptide tutorial and trying to execute the "save_trajs" cell.

coor.save_trajs(inp, pcca_samples, outfiles=['./data/pcca1_10samples.xtc','./data/pcca2_10samples.xtc', 
                                             './data/pcca3_10samples.xtc','./data/pcca4_10samples.xtc'])

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-62-c58a572794da> in <module>
      1 coor.save_trajs(inp, pcca_samples, outfiles=['./data/pcca1_10samples.xtc','./data/pcca2_10samples.xtc', 
----> 2                                              './data/pcca3_10samples.xtc','./data/pcca4_10samples.xtc'])

/opt/anaconda3/envs/MD/lib/python3.7/site-packages/pyemma/coordinates/api.py in save_trajs(traj_inp, indexes, prefix, fmt, outfiles, inmemory, stride, verbose)
    842         import os
    843 
--> 844         _, fmt = os.path.splitext(traj_inp.filenames[0])
    845     else:
    846         fmt = '.' + fmt

/opt/anaconda3/envs/MD/lib/python3.7/posixpath.py in splitext(p)
    120 
    121 def splitext(p):
--> 122     p = os.fspath(p)
    123     if isinstance(p, bytes):
    124         sep = b'/'

TypeError: expected str, bytes or os.PathLike object, not list

Thank you,

Dan

**Comment by clonker** [comment]
Hi Dan, 
could you please let us know which operating system / python version / pyemma version / mode of installation (ie conda vs pip vs local) you were using? Also it would be helpful to know which version of the tutorials you were executing, i.e., whether you were obtaining them directly from the repository (https://github.com/markovmodel/pyemma_tutorials) or otherwise.
Thanks!

**Comment by Dan-Burns** [comment]
I'm on Mac OSX High Sierra, with Python 3.7.4.  I installed with conda and I downloaded the tutorials from http://www.emma-project.org/v2.5.2/ipython.html?highlight=tutorials.  

Thank you for looking at this!

Dan

**Comment by thempel** [comment]
Hi, 
The tutorials that you are linking to are from an outdated version of pyemma. The up-to-date set of tutorials is here: https://github.com/markovmodel/pyemma_tutorials  I've just run notebook `00-pentapeptide-showcase` on my Mac with python 3.7.6 (pyemma 2.5.7) and I cannot reproduce the error that you are posting, i.e. the cell containing `save_trajs` runs without throwing an error.

**Comment by clonker** [comment]
Hi, thanks for the info and thanks @thempel for spotting the outdated tutorials! Perhaps it might also be worth to update your pyemma installation if it sits in an older conda environment (`conda update -c conda-forge pyemma`). :slightly_smiling_face:

**Comment by Dan-Burns** [comment]
Thank you both!

**Comment by Dan-Burns** [comment]
Works with the github versions!
