### ISSUE TITLE
Saving model error

### ISSUE THREAD

**Issue by yossadh** [markovmodel/PyEMMA#1476]
I am going through the tutorial and everything works perfectly except when saving the model (Tutorial 03, 04). Here's the error:
With `cluster.save('nb4.pyemma', model_name='ala2tica_cluster', overwrite=True)`
```
~/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    188         if swmr and swmr_support:
    189             flags |= h5f.ACC_SWMR_READ
--> 190         fid = h5f.open(name, flags, fapl=fapl)
    191     elif mode == 'r+':
    192         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()
OSError: Unable to open file (file signature not found)
```

PyEMMA 2.5.7
Output of `conda list`: [conda_list.txt](https://github.com/markovmodel/PyEMMA/files/5596223/conda_list.txt)

Here's a quick checklist in what to include:
- [v] Include a detailed description of the bug or suggestion
- [v] `pip list` or `conda list` of the environment you are using (please attach a txt file to the issue).
- [v] PyEMMA version and operating system versions
- [v] Minimal example if possible, a Python script, zipped input data (if not too large)

**Comment by clonker** [comment]
This looks like a for some reason corrupted file. Have you tried changing the filename (like `nb4_2.pyemma'`)?

**Comment by yossadh** [comment]
That's what I gather too from googling, but this is saving file, not reading...
I tried anyway with different filenames, still same error. That `swmr` flag seems to be the problem. 

Edit: For a workaround, saving directly with pickle.dump works ok
