### ISSUE TITLE
deeptime hmm vs pyemma hmm

### ISSUE THREAD

**Issue by pl992** [markovmodel/PyEMMA#1482]
You suggested me to try using the deeptime library for the building of HMM instead of pyemma because it gives better control. I've tried deeply using both of them but I'm seeing some discrepancies which I cannot understand: 
using the very same data, lag time and number of metastable states I built 2 HMM using for pyemma the `pyemma.msm.estimate_hidden_markov_model` function with the other parameters set as default and for deeptime the `deeptime.markov.hmm.MaximumLikelihoodHMM` initiating the model using the `deeptime.markov.init.discrete.metastable_from_data`; again except for the lag time the number of metastable states and data everything else is set as default. 

The metastable assignments are quite similar but the largest and shocking difference regards the stationary distribution: for pyemma is 0 everywhere except for one metastable state while for deeptime makes more sense. 

I'm writing you since I would like to know whether in pyemma there's something that isn't working properly for the building of HMM or if my data are poor and deeptime will return somehow some data that are making surprisingly sense.

Thank you

**Comment by clonker** [comment]
Hi, is this concerning the stationary distribution of the hidden states or the stationary distribution over the observed states? In any case one could compare the the hidden transition matrix with the stationary distribution that comes out of the estimator via [this function](https://deeptime-ml.github.io/api/generated/deeptime.markov.tools.analysis.stationary_distribution.html#deeptime.markov.tools.analysis.stationary_distribution). In case of the stationary distribution over output states `stationary_distribution_obs`, this hidden stationary distribution is dotted with the output probabilities.
In general the code in deeptime is based on that of pyemma and i do recall fixing some issues with it. Eventually it is going to be re-integrated into pyemma.

**Comment by pl992** [comment]
Hi, thank you for your answer, so I've compared the transition matrices and the one returned by pyemma are a mess filled with `nan` values while the ones built using deeptime make sense. So could I trust much more the results coming from deeptime than from pyemma?

**Comment by clonker** [comment]
Well `nan` values do not seem right, although it could be that your data contains some nans which have propagated into the model. While I believe that the deeptime implementation is more robust, I have now added a function to the deeptime HMM that you can evaluate the likelihood of observing a time series given the estimated model. 
With that you can control via, e.g., a holdout set how well your model performs (train/validation split or even cross-validation). The likelihood can serve as a score in that case.

As a first step you can estimate the HMM on a portion of the data (say 80% of the data or so) and evaluate the likelihood of the remaining 20% given that estimated model. This likelihood you can compare to the likelihood that is stored inside the HMM from the estimation procedure, see [here](https://deeptime-ml.github.io/notebooks/hmm.html#Estimation) and [here](https://deeptime-ml.github.io/api/generated/deeptime.markov.hmm.HiddenMarkovModel.html#deeptime.markov.hmm.HiddenMarkovModel.compute_observation_likelihood):
```
hmm.likelihood
```
is the model's likelihood on the training data and
```
hmm.compute_observation_likelihood(remaining_data)
```
computes the likelihood on the holdout set.

You have to be aware however that if you used a submodel function (i.e., not all observed states are contained the model), then evaluating the likelihood on observations which include the excluded states is going to give you a significantly lower likelihood. If you didn't, then these values should be comparable.

**Comment by pl992** [comment]
thank you,
this is a really good suggestion for comparing hmms.
Anyway I should report that my data contain no nans, the way I checked the transition matrix of the observed states in pyemma is using the function `transition_matrix_obs()` and it does contain some nan value. In similar way I built the hmm using deeptime and no nan value are reported (using the same function `transition_matrix_obs()`. 

I'll take the occasion to point out also some weird behavior of the attribute `hidden_state_trajectories` of the class  `deeptime.markov.hmm.HiddenMarkovModel` . Once is built the output is really weird, I would expect a list of trajectories of the metastable states with the same size of the input data, but they're not. I obtain the right result using the function `compute_viterbi_paths(input_data)` but I understood that should be also what is contained in `hidden_state_trajectories`.

Thank you again for your time!

**Comment by clonker** [comment]
I agree that this is a bit confusing. the `hidden_state_trajectories` are the most likely hidden states for "effective" observations. The effective observations are computed by subsampling the data using stride and lagtime (see description of `stride` [here](https://deeptime-ml.github.io/api/generated/deeptime.markov.hmm.MaximumLikelihoodHMM.html#deeptime.markov.hmm.MaximumLikelihoodHMM)).
Under the hood this indeed calls the Viterbi path computation as you suspected. If you want to have a correspondence between your observations trajectory and the hidden trajectory I recommend using `compute_viterbi_paths` over the `hidden_state_trajectories` property (the latter is evaluated on the effective data). I guess this demands better documentation.

**Comment by pl992** [comment]
As I understood the "effective" observations are just evaluated with a 'larger stride', so I would still expect a list of trajectories with the same number of trajectories passed, the point is that it isn't the case since I get a number of trajectories much larger than the input

**Comment by clonker** [comment]
Yes exactly, the trajectories are being subsampled - which leads to a larger amount of data and works well for the maximum-likelihood estimate. In case you want uncertainties (Bayesian HMM), one needs to take greater care so that the transitions are approximately uncorrelated.
