### ISSUE TITLE
Features: vector coordinates? 

### ISSUE THREAD

**Issue by mohamedmarzouk22** [markovmodel/PyEMMA#1493]
I am using PyEMMA to study the dissociation of protein from complex with DNA and I want to use the vector coordinates ( 3 D coordinates) between DNA and protein as a feature. I checked the features of PyEMMA but it seems nothing to do so!! Is this right? or any other suggestion to do so?

**Comment by clonker** [comment]
The featurization is basically built on top of MDTraj if you are familiar with that. If there is nothing directly available you can add a [custom feature](http://www.emma-project.org/latest/api/generated/pyemma.coordinates.featurizer.html#pyemma.coordinates.data.featurization.featurizer.MDFeaturizer.add_custom_func).
