### ISSUE TITLE
Plotting TICA analysis

### ISSUE THREAD

**Issue by andresilvapimentel** [markovmodel/PyEMMA#1498]
The feature_labels in the pyemma.plots.plot_feature_histograms() must have the same dimension as tica_concatenated, howeve the tica_concatenated has dimension of 767.

The code is:
fig, axes = plt.subplots(1, 2, figsize=(10, 4))
pyemma.plots.plot_feature_histograms(
    tica_concatenated,
    ax=axes[0],
    feature_labels=['IC1', 'IC2', 'IC3', 'IC4', 'IC5', 'IC6', 'IC7', 'IC8', 'IC9', 'IC10'],
    ylog=True, ignore_dim_warning=True)
pyemma.plots.plot_density(*tica_concatenated[:, :2].T, ax=axes[1], logscale=True)
axes[1].set_xlabel('IC 1')
axes[1].set_ylabel('IC 2')
fig.tight_layout()

I got the following error message:
ValueError                                Traceback (most recent call last)
<ipython-input-40-0f8ce0a86fe7> in <module>()
      4     ax=axes[0],
      5     feature_labels=['IC1', 'IC2', 'IC3', 'IC4', 'IC5', 'IC6', 'IC7', 'IC8', 'IC9', 'IC10'],
----> 6     ylog=True, ignore_dim_warning=True)
      7 pyemma.plots.plot_density(*tica_concatenated[:, :2].T, ax=axes[1], logscale=True)
      8 axes[1].set_xlabel('IC 1')

/usr/local/lib/python3.7/dist-packages/pyemma/plots/plots1d.py in plot_feature_histograms(xyzall, feature_labels, ax, ylog, outfile, n_bins, ignore_dim_warning, **kwargs)
     76                                  'a pyemma featurizer object or None.')
     77         if not xyzall.shape[1] == len(feature_labels):
---> 78             raise ValueError('feature_labels must have the same dimension as the input data xyzall.')
     79 
     80     # make nice plots if user does not decide on color and transparency

ValueError: feature_labels must have the same dimension as the input data xyzall.

How can I solve this issue? Do I need to include 767 feature_labels here?Is there a way to circunvent it?

**Comment by andresilvapimentel** [comment]
When I reduced the number of features and dimensions, I could easily solve the problem by adding all the ICs.
But I am not sure if I can circuvent this issue in a different way.

**Comment by clonker** [comment]
You did the right thing. One should / could probably use a generator expression `feature_labels = [f"IC{i+1}" for i in range(number_of_ICs)]`, where you replace `number_of_ICs` with your output dimension.
