### ISSUE TITLE
Estimation and validation

### ISSUE THREAD

**Issue by andresilvapimentel** [markovmodel/PyEMMA#1500]
My code has an error in the following command:

for k, ax in enumerate(ax_ck):
    lest, lpred = _add_ck_subplot(cktest, test_index, ax, k, k, ipos=cktest.nsets - 1, dt=0.1, units='ns', linewidth=0.7)
    if k > 0:
        ax.set_yticks([])

The error message is:
NameError                                 Traceback (most recent call last)
<ipython-input-79-71e284e3f5a7> in <module>()
     23 
     24 for k, ax in enumerate(ax_ck):
---> 25     lest, lpred = _add_ck_subplot(cktest, test_index, ax, k, k, ipos=cktest.nsets - 1, dt=0.1, units='ns', linewidth=0.7)
     26     if k > 0:
     27         ax.set_yticks([])

NameError: name 'test_index' is not defined

Could you help me, please? What is the test_index?

**Comment by clonker** [comment]
Hi, could you let us know which PyEMMA version you are working with? And perhaps update to the latest one?

**Comment by thempel** [comment]
Setting `test_index = 0` should do the trick

**Comment by andresilvapimentel** [comment]
Thanks. It works now!!!
