### ISSUE TITLE
How to combine features from featurizer?

### ISSUE THREAD

**Issue by cgseitz** [markovmodel/PyEMMA#1501]
Hello,

I am trying to create an MSM with some tricky features. I would like my features to be the angles between three center of mass definitions. I know there are already functions for center of mass (```add_group_COM```) and angles (```add_angles```). I've considered trying to nest the COM inside the angles function, approximate the COM as individual atoms, or perhaps write a custom function. How would you recommend going about this problem?

Best,
Christian

**Comment by clonker** [comment]
Hello Christian,

you can write a custom feature function that internally uses the `pyemma.coordinates.data.featurization.misc.GroupCOMFeature` with a subsequent call to `mdtraj.geometry.angle.compute_angles`. You might have to wrap the output of the COM Feature into an MDTraj trajectory object.

Cheers,
Moritz

**Comment by cgseitz** [comment]
Hi Moritz,

Thanks for this info. I understand the overview, but how can I pass the COM features to an MDTraj trajectory object, when the COM features are not xyz coordinates? I am creating the COM features like this: 
```
feat_tilt = coor.featurizer(top)
group1 = [987, 518, 1456, 49]
group2 = [77, 1015, 546, 1484]
group3 = [list(range(90,468))]
feat_tilt.add_group_COM([group1])
feat_tilt.add_group_COM([group2])
feat_tilt.add_group_COM([group3])
```

Trying to load my trajectories as pyemma coordinates with the COM features ```pyemma.coordinates.load(trajs2, features=feat_tilt)``` results in an error: ```TypeError: 1D weights expected when shapes of a and weights differ.``` There must be some method of doing this I'm missing?

Best,
Christian

**Comment by clonker** [comment]
Something like this:
```python
feat = pyemma.coordinates.featurizer(pdbfile)

from pyemma.coordinates.data.featurization.misc import GroupCOMFeature
c1 = GroupCOMFeature(feat.topology, [[987, 518, 1456, 49]])
c2 = GroupCOMFeature(feat.topology, [[77, 1015, 546, 1484]])
c3 = GroupCOMFeature(feat.topology, [list(range(90,468))])

def feature_function(traj: mdtraj.Trajectory):
    centers1 = c1.transform(traj)  # yields ndarray
    centers2 = c2.transform(traj)  # yields ndarray
    centers3 = c3.transform(traj)  # yields ndarray
    xyz = np.hstack((centers1, centers2, centers3))
    traj = mdtraj.Trajectory(xyz.reshape(-1, 3, 3), topology=None)
    # this has shape (n_frames, 1)
    angles = mdtraj.compute_angles(traj, angle_indices=[[0, 1, 2]], periodic=True)
    return angles

feat.add_custom_func(feature_function, dim=1, description='tilt')
pyemma.coordinates.load(xtcfile, features=feat)
```

**Comment by cgseitz** [comment]
Fantastic, this works like a dream! thanks moritz

**Comment by clonker** [comment]
Glad it works for you, closing this issue

**Comment by vas2201** [comment]
Hi there, 
Can someone explain why we use (-1,3,3) in below code.
 traj = mdtraj.Trajectory(xyz.reshape(-1, 3, 3), topology=None)
Thank you in advance. 

Also, If possible, can you provide the code for global dihedrals using COM feature?.

**Comment by clonker** [comment]
The shape is composed of `(number_frames, number_atoms, number_dimensions)` -- the `-1` leads to 'filling up' the frames with `(3, 3)` blocks of data.
For dihedrals it should be very similar, using this: https://mdtraj.org/1.9.4/api/generated/mdtraj.compute_dihedrals.html

Untested code:

```python
def feature_function(traj: mdtraj.Trajectory):
    centers1 = c1.transform(traj)  # yields ndarray
    centers2 = c2.transform(traj)  # yields ndarray
    centers3 = c3.transform(traj)  # yields ndarray
    centers4 = c4.transform(traj)  # yields ndarray
    xyz = np.hstack((centers1, centers2, centers3, centers4))
    traj = mdtraj.Trajectory(xyz.reshape(-1, 4, 3), topology=None)
    # this has shape (n_frames, 1)
    return mdtraj.compute_dihedrals(traj, indices=[[0, 1, 2, 3]], periodic=True)
```

**Comment by vas2201** [comment]
Thanks a lot for your help. I am trying to get it done this work since last year. 
Finally you write the code in few minutes.

**Comment by clonker** [comment]
Glad that i could be if help, you're welcome!
