### ISSUE TITLE
Calculating uncertainty in free energy surface.

### ISSUE THREAD

**Issue by sperezconesa** [markovmodel/PyEMMA#1502]
Hello everyone,

I have calculated a MSM in the standard way done in the tutorials for my system using a bayesian MSM. With this MSM I have plotted the free energy surface of the system projected onto two CVs based on the weights. Is there a way to calculate the standard error of the FES? Ideally as a map of uncertainty of the surface or something like that. I'm using pyemma 2.5.9.

Thank you very much for your help and keep up the good work!!
Sergio

**Comment by clonker** [comment]
Hi Sergio,

you can access the bayesian samples via the `bmsm.samples` attribute. Each sample is a `MSM` itself so you can use the samples to compute FESs individually and subsequently check for its robustness.

Cheers!

**Comment by sperezconesa** [comment]
Hello Clonker,

Thanks for your anwer. So you suggest that instead of using the parent bmsm, I use the weights from bsms.samples to compute many FES and obtain a standard error of the mean? This would in some way generate the uncertainty of the FES as it relates the MSM. 

So maybe if I want the uncertainty in relation to the MSM and the sampling of the trajectory, I should bootstrap the data that is fed to the MSM?

Thank you very much for your help!

**Comment by clonker** [comment]
Hi Sergio,

yes exactly that is what i meant. It already reflects the sampling of the trajectory as it is based on the count matrix and the samples are 'feasible' MSMs which approximately could also have generated the input data. So this at least gives you a sense of the 'sharpness' of the FES given your data. If you add more samples/data, the sharpness should increase (ie standard deviation decrease if you were to fit a Gaussian to it).
You can also bootstrap your data (eg using [this](https://deeptime-ml.github.io/latest/api/generated/deeptime.markov.tools.estimation.bootstrap_trajectories.html)) but I do not think it is required.

Best,
Moritz

**Comment by sperezconesa** [comment]
Thank you so much Moritz! Do you happen to know any examples where this is done? I think I understand how to do it, but it is always best to follow an example.

**Comment by clonker** [comment]
Hey, I do not think there are any examples doing that out there. In the end visualizing it might be especially challenging.Computationally it should be straightforward though, as you just use the code that you were using for FES anyways but plug in a different sample each time. Do let me know if you get stuck and I will see if I can be of any help. :-)

**Comment by sperezconesa** [comment]
Good, thank you so much. You have definitelly sent me on the right track.

**Comment by clonker** [comment]
I assume you could resolve your problems, otherwise feel free to reopen.

**Comment by sperezconesa** [comment]
Yes! Sorry, I was on paternal leave :)

**Comment by clonker** [comment]
Glad it's resolved and congratulations on the addition to your family!
