### ISSUE TITLE
No module named 'pyemma.msm.analysis', 'pyemma.msm.generation'

### ISSUE THREAD

**Issue by MCVifpen** [markovmodel/PyEMMA#1507]
Hello,

I just installed PyEMMA in a conda environment, with no errors, and tried to run [your TICA example on this link](http://docs.markovmodel.org/lecture_tica.html). However, I am unable to import the pyemma.msm.analysis and pyemma.msm.generation libraries (i.e.: *No module named ...* message).

I installed PyEMMA version 2.5.7 with the conda installer. Please, find in [this link](https://github.com/markovmodel/PyEMMA/files/7038722/conda_list.txt) a txt file with the output of my "conda list" command. I can't see what it's missing.

Please, could you help me to find a solution ? Thank you very much for your help.

Kind regards,
MCV

**Comment by clonker** [comment]
Hi, this documentation is very old and no longer compatible with current PyEMMA versions. Please refer to [emma-project](http://www.emma-project.org/latest/) for a current documentation of PyEMMA or [deeptime](https://deeptime-ml.github.io/latest/index.html) as an alternative package.

**Comment by MCVifpen** [comment]
Hi,

Thank you for your quick reply. According to the current PyEMMA documentation, the FAQ that relates most closely to my situation is the one at the bottom of the [page](http://www.emma-project.org/latest/INSTALL.html#frequently-asked-questions-faq). Still, it doesn't make sense to me, as I installed PyEMMA in a linux machine and only one python executable file is available (version 3.8).

I would very much appreciate if you could give me a hint on this issue. Thanks again.

Regards,
MCV

**Comment by thempel** [comment]
Would you be so kind and post the exact code that you are trying to execute together with the error message that you are getting?

**Comment by MCVifpen** [comment]
Dear Thempel,

I simply did the following steps:

* conda installation (*conda install pyemma*), as explained in the documentation; executed with no error messages
* run the python interpreter at the prompt (version 3.8)
* run the first commands of  [your TICA example on this link](http://docs.markovmodel.org/lecture_tica.html)

Below there is a cut and paste of what I get.

Thank you.

Regards,
MCV

Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> import numpy as np
\>>> import pyemma.msm as msm
\>>> import pyemma.msm.generation as msmgen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ModuleNotFoundError: No module named 'pyemma.msm.generation'**
\>>> import pyemma.msm.analysis as msmana
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ModuleNotFoundError: No module named 'pyemma.msm.analysis'**
\>>> import pyemma.coordinates as coor
\>>> import matplotlib.pylab as plt
\>>>

**Comment by clonker** [comment]
As already mentioned, the tutorial you reference is very old and no longer compatible to recent pyemma versions. You can either downgrade to some version which was released in 2015 (I guess this is not even PyEMMA 2 but still PyEMMA 1) or pick a different tutorial. [This tutorial](http://www.emma-project.org/latest/tutorials/notebooks/02-dimension-reduction-and-discretization.html) highlights the current pyemma TICA api and [this tutorial](https://deeptime-ml.github.io/latest/notebooks/tica.html) contains the same example as in the old tutorial but with the deeptime api.

**Comment by MCVifpen** [comment]
OK. Thank you very much.
