### ISSUE TITLE
HMM timescale issue

### ISSUE THREAD

**Issue by orthonalmatrix** [markovmodel/PyEMMA#1508]
Hello,
I'm trying to get the HMM ITS to determine a lag time for my hmm. I've clustered (150 clusters)
and are now trying to compute the its via 
```
lags=5000
itshmm9 = pyemma.msm.timescales_hmsm(cluster.dtrajs, 9, lags=lags, errors='bayes')

```
But I get the following warning a lot
26-08-21 09:13:52 pyemma.msm.estimators.bayesian_hmsm.BayesianHMSM[1008] WARNING  Ignored error during 
estimation: Trying to initialize 9-state HMM from smaller 2-state MSM.

I did not estimate an MSM and so I do not understand the "from smaller 2-state MSM". In the example on the documentation page it computes the ITS directly from the trajectory without creating an msm (externally), and I don't see why and MSM is needed. This issue does not occur if the bayes error is not passed.

**Comment by thempel** [comment]
Hi, how many states does your discrete trajectory have?

**Comment by thempel** [comment]
Oh sorry, you already said 150 cluster centers. It might be that at high lag times, your states are not connected anymore (given the counting mode of a Bayesian MSM). That might be the issue if you are getting some results, but the ITS plot does not show all the lag times that you are requested. 

Background: The HMM is initialized by a regular MSM. So if there are only 2 states that are connected in this MSM, you will get the error message that you posted. In my experience, hidden MSMs often do not perform very well with very large lag times. Maybe you want to try smaller values than 5000 first and see how it behaves.

**Comment by orthonalmatrix** [comment]
Thank you! That fixed the issue and your explanation makes it clear why this is an issue.
