### ISSUE TITLE
VAMP2 score calculation error

### ISSUE THREAD

**Issue by Bazzinga18** [markovmodel/PyEMMA#1510]
During the calculation of VAMP2 score I got _RuntimeError: requested more output dimensions (10) than dimension of input data (1)_

I use the following code:
`def score_cv(data, dim, lag, number_of_splits=10, validation_fraction=0.5):
    # we temporarily suppress very short-lived progress bars
    with pyemma.util.contexts.settings(show_progress_bars=False):
        nval = int(len(data) * validation_fraction)
        scores = np.zeros(number_of_splits)
        for n in range(number_of_splits):
            ival = np.random.choice(len(data), size=nval, replace=False)
            vamp = pyemma.coordinates.vamp(
                [d for i, d in enumerate(data) if i not in ival], lag=lag, dim=dim)
            scores[n] = vamp.score([d for i, d in enumerate(data) if i in ival])
    return scores

dim = 10

fig, axes = plt.subplots(1, 3, figsize=(12, 3), sharey=True)
for ax, lag in zip(axes.flat, [5, 10, 20]):
    torsions_scores = score_cv(torsions_data, lag=lag, dim=dim)
    scores = [torsions_scores.mean()]
    errors = [torsions_scores.std()]
    positions_scores = score_cv(positions_data, lag=lag, dim=dim)
    scores += [positions_scores.mean()]
    errors += [positions_scores.std()]
    distances_scores = score_cv(distances_data, lag=lag, dim=dim)
    scores += [distances_scores.mean()]
    errors += [distances_scores.std()]
    ax.bar(labels, scores, yerr=errors, color=['C0', 'C1', 'C2'])
    ax.set_title(r'lag time $\tau$={:.1f}ns'.format(lag * 0.1))
    if lag == 5:
        # save for later
        vamp_bars_plot = dict(
            labels=labels, scores=scores, errors=errors, dim=dim, lag=lag)
axes[0].set_ylabel('VAMP2 score')
fig.tight_layout()`
Please help me out as i am new to this.
thanks

**Comment by clonker** [comment]
Can you post the full stack trace? Although from the information you have given I suspect that your data is lower-dimensional than 10-dimensional in which case you'd have to evaluate it with fewer dimensions (change the `dim` parameter). :)

**Comment by clonker** [comment]
Closing this now due to lack of response, feel free to reopen.
