### ISSUE TITLE
angle/dihedral features vs averaging

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#152]
should we convert them via sin/cos?
Maybe add a flag to toggle the behaviour?

**Comment by trendelkampschroer** [comment]
Hi,

this is a very important issue.

According to wikipedia radians is 'the standard unit' of angular data. So I think we should stick to it (in terms of units).

In terms of computations one has to distinguish between real-valued and circular data. Computation of many important quantities differ a lot, e.g. mean and covariances. If you are thinking about clustering then it is also important to discuss how to cluster angular data. 

It might be that a representation in terms of (cos, sin) paris does the trick in all relevant cases. I can refer to some literature if needed.

**Comment by marscher** [comment]
the mean calculation is not well defined in angular space. Think of -179 
and 179, the mean should be +-180, but in our impl it would be 0!

So whenever a mean gets calculated (PCA, TICA, Kmeans) this will fail!

**Comment by franknoe** [comment]
Ability to compute cos/sin would certainly be useful. I would say this 
is a different feature though.

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Am 27/03/15 um 21:17 schrieb Benjamin Trendelkamp-Schroer:
>
> According to wikipedia radians is 'the standard unit' of angular data. 
> So I think we should stick to it (in terms of units).
>
I would use a flag to switch between radians and degrees (but not 
between direct and cos/sin representation that I consider a different 
feature).

My feeling is that for MD people an angle is more commonly used than 
radians, but the default should probably be the one that is compatible 
with numpy operations on the data (probably radians). What do you think?



-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
I agree with Frank: sin,cos should be another feature. I mean, the user has to be capable of computing angles. Think of our many Di-Ala MSMs, all done in angular space. We want to still be able to do those with PyEmma, right?

I would also stick with radians,  but state that very clearly in the documentation. 

Regarding circular statistics, I remember reading some papers about it. in essence, they do the sin,cos transformation to arrive at a vectorial average for angles. But again, I doubt this is useful if the user has insisted in computing angles (as scalars and not vectors). 

Perhaps it's possible to warn the user if he is using "raw"-angles for a pipeline that includes TICA or PCA or any method that requires angles and covariances?

**Comment by franknoe** [comment]
Am 28/03/15 um 09:11 schrieb gph82:
>
> I agree with Frank: sin,cos should be another feature. I mean, the 
> user has to be capable of computing angles. Think of our many Di-Ala 
> MSMs, all done in angular space. We want to still be able to do those 
> with PyEmma, right?
>
> I would also stick with radians, but state that very clearly in the 
> documentation.
>
Yes. But actual angles should be computable by simply setting a flag.
>
> Regarding circular statistics, I remember reading some papers about 
> it. in essence, they do the sin,cos transformation to arrive at a 
> vectorial average for angles. But again, I doubt this is useful if the 
> user has insisted in computing angles (as scalars and not vectors).
>
> Perhaps it's possible to warn the user if he is using "raw"-angles for 
> a pipeline that includes TICA or PCA or any method that requires 
> angles and covariances?
>
The dataproducer could provide the possibility to inform about the type 
of feature. In the FeatureReader we have this possibility. If there is 
an angular feature being passed to TICA, PCA or kmeans they should 
either refuse to do the averaging or automatically do it right.



-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
We now have the option to either get radians or degrees.

Still open: averaging with angular coordinates. I am renaming the issue to make that clear.

**Comment by franknoe** [comment]
I think we have cossin now, so I'm closing this. @marscher is it working or is there still an open problem?
