### ISSUE TITLE
How to deal with many short trajectories

### ISSUE THREAD

**Issue by KrishnenduSinha12** [markovmodel/PyEMMA#1527]
I have like 30 short MD runs each of which is 50-100ns long. I would like to build MSM using these set of trajectories. Should I concatenate the trajectories before performing tica/pca based clustering. 
I would like to know if concatenation at the boundary would lead to any artefact in (i) TICA based clustering and (ii) construction of transition matrix.
Thanks

**Comment by clonker** [comment]
Hi, concatenation is definitely not the way to go here as it would indeed lead to the artifacts. Just leave them as list of trajectories and let pyemma deal with it internally.

PS: Only TICA/VAMP methods really rely on the trajectory structure being present, PCA for example does not make any use of the temporal structure of the data (and also isn't a recommended method in this setting). Clustering itself also doesn't make use of the temporal information, so here theoretically the data could be concatenated too. But to be on the safe side just leave them as they are (ie as list of trajectories) and let the library handle it.

**Comment by KrishnenduSinha12** [comment]
Thanks.
I have another question, if I have several short trajectories of different run length will that affect the results? Or is it recommended to use trajectories of similar run length?

**Comment by clonker** [comment]
You can use trajectories of different lengths, no problem. The ones which are shorter than `lag` are being skipped.
