### ISSUE TITLE
mfpt uncertainty

### ISSUE THREAD

**Issue by ccccclw** [markovmodel/PyEMMA#1532]
Hi, is there any api for getting the uncertainty of mean first passage time between two states? Thanks!

**Comment by thempel** [comment]
Yes, you can estimate a Bayesian MSM and get the posterior distribution of the MFPT between chosen sets of states. E.g.
```python
bayesian_msm.sample_f('mfpt', list_of_states_A, list_of_states_B)
```
There's an example here: https://github.com/markovmodel/pyemma_tutorials/blob/master/notebooks/05-pcca-tpt.ipynb

**Comment by ccccclw** [comment]
Thank you!
