### ISSUE TITLE
 generate a synthetic trajectory from markov model

### ISSUE THREAD

**Issue by jeromeRlon** [markovmodel/PyEMMA#1539]
Hi!

I'm using pyemma 2.1.10 and i am trying to generate a synthetic trajectory from markov model?

I did not see the tutorial about it in the documentation, could you tell me how to do this?

Thanks

**Comment by thempel** [comment]
Once you have an estimated MSM, you can call `msm.simulate(number_of_steps)`. Api docs are [here](http://www.emma-project.org/latest/api/generated/pyemma.msm.markov_model.html?highlight=simulate#pyemma.msm.models.msm.MSM.simulate).

**Comment by clonker** [comment]
I assume this is answered, otherwise please feel free to reopen
