### ISSUE TITLE
Errors in ckTest should be using statistically independent counts

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#154]
The errors computed for the ckTest via Equation:

![screen shot 2015-03-28 at 17 42 42](https://cloud.githubusercontent.com/assets/6495810/6881893/e7ae95f6-d571-11e4-9530-1522daee4590.png)

require that counts in the denominator are uncorrelated. That means one cannot use the full sliding-window count. Because we now handle MSM estimation and ckTest in objects this is no longer the user's duty but must be handled self-consistenly in these objects.

I suggest to supply statistically uncorrelated count matrices in the MSM object defined by c_ij/tau, where c_ij is the sliding estimate (see discussion about geometric mean estimator with Hao ... we'll also add this to the reversible estimation manuscript). The ckTest object should use these counts in its expressions.

**Comment by trendelkampschroer** [comment]
Hi,

we do not need to add an extra attribute to the MSM-objects, since the counts c_{ij}(k\tau) are computed within the cktest-function. I will ensure that they are divided by k*tau to make them uncorrelated.

**Comment by franknoe** [comment]
I think it would be useful because all algorithms computing statistical 
uncertainties would benefit from this.

Am 30/03/15 um 09:10 schrieb Benjamin Trendelkamp-Schroer:
>
> Hi,
>
> we do not need to add an extra attribute to the MSM-objects, since the 
> counts c_{ij}(k\tau) are computed within the cktest-function. I will 
> ensure that they are divided by k*tau to make them uncorrelated.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/154#issuecomment-87575309>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
