### ISSUE TITLE
Is transition time(mfpt) from one state to another may be different from time observed in MD simulations?

### ISSUE THREAD

**Issue by Bazzinga18** [markovmodel/PyEMMA#1542]
Hii,
For a particular protein it takes few microseconds to unfold its helix through the MD simulations but through MSM, mfpt for the folded state to the unfolded one is quite different. what was the reason for this??

**Comment by thempel** [comment]
Can you specify, what is "quite different"? In case the MFPT is extremely high compared to your observation, maybe the MSM is not connected - you may want to double-check that you have properly sampled both the folding and the unfolding.

**Comment by Bazzinga18** [comment]
from simulation the time for unfolding comes out to be around 6-8 microseconds and from msm it comes out to be in the range of 100 microseconds

**Comment by clonker** [comment]
I assume this has resolved itself and/or is no longer relevant, otherwise feel free to reopen. I concur with @thempel that this sounds like not connected MSMs or not enough data (as in, e.g., you observe only one direction of the process)
