### ISSUE TITLE
torsion feature for specific range

### ISSUE THREAD

**Issue by Bazzinga18** [markovmodel/PyEMMA#1543]
I want to define a feature in which i want to take backbone and sidechain torsions but for a specific residue range.
lets say size of my protein is 120 aa, and i want to consider the above feature from residue number 111 to 120. How one can define the feature?? please help.
I use the following code for whole sequence but i didnt know how to do for specific sequence range
`feat = pyemma.coordinates.featurizer(pdb)
feat.add_backbone_torsions(cossin=True, periodic=False)
feat.add_sidechain_torsions(which='chi1', cossin=True, periodic=False)`

**Comment by thempel** [comment]
In the manual of the functions that you are copying, you see that you can pass a selection string, e.g. `'residue 111 to 120'`.

http://www.emma-project.org/latest/api/generated/pyemma.coordinates.featurizer.html#pyemma.coordinates.data.featurization.featurizer.MDFeaturizer.add_backbone_torsions

http://www.emma-project.org/latest/api/generated/pyemma.coordinates.featurizer.html#pyemma.coordinates.data.featurization.featurizer.MDFeaturizer.add_sidechain_torsions

**Comment by Bazzinga18** [comment]
thanks;)
