### ISSUE TITLE
Extracting PDB structures from TICA plot or PCA plot in PyEMMA 2.5.7

### ISSUE THREAD

**Issue by satyabrata400** [markovmodel/PyEMMA#1544]
Hi ,
I am new to PyEMMA and I have don TICA from 14 independent trajectories (each of 500 ns) and plotted the first two ICs on Jupyter notebook. I wanted to know how I can extract a structure in PDB format from the density plot (especially from highest sample density region)?
Thanks

**Comment by thempel** [comment]
Hi, I tried to explain that in an older issue, maybe that helps? https://github.com/markovmodel/PyEMMA/issues/1533#issuecomment-1015395843
