### ISSUE TITLE
Python 3.10 release?

### ISSUE THREAD

**Issue by sroet** [markovmodel/PyEMMA#1547]
Background: PyEmma is a testing dependency for a package I maintain. We are trying to enable tests on python 3.10.

Currently when trying to run `conda install pyemma` in a python `3.10` environment, this fails with:

```
conda install pyemma
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                   

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pyemma -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.5,<3.6.0a0|3.4.*']

Your python: python=3.10
```

reproducer (assuming you have conda-forge added as a channel in conda):
```
conda create -n test python
conda activate test
conda install pyemma
```

What would be required for PyEMMA to be build on python 3.10 (other than the conda-forge bots doing their magic)?

**Comment by clonker** [comment]
Installation with pip works so I guess it is indeed a matter of conda-forge bots doing their magic. Perhaps there are one or more dependencies that are not yet python 3.10 capable, I will have to check.

**Comment by clonker** [comment]
At the very least `bhmm` has to be updated, too. Or we replace the pyemma implementation with deeptime. :slightly_smiling_face:

**Comment by marscher** [comment]
I'd replace it.

**Comment by clonker** [comment]
I agree, just someone has to do it :slightly_smiling_face:
