### ISSUE TITLE
Changing the units of the rate in plot_markov_model 

### ISSUE THREAD

**Issue by orthonalmatrix** [markovmodel/PyEMMA#1548]
Is there a simple way to change the rate units (or scale them)? My system has a frame unit of 20 ps, so as I understand it, my plot_markov_model shows the rates in 1/20 ps. Is there a way to scale all the values by 20 so I can have the rate be per ps?
Thanks!

**Comment by thempel** [comment]
In general, pyemma's Markov models encode transition probability matrices (which are not the same as rate matrices) which indicate conditional probabilities, i.e., are unit-less. In case you are referring to the arrow labels of that plot function, the [docs](http://www.emma-project.org/latest/api/generated/pyemma.plots.plot_markov_model.html?highlight=plot_markov_model#pyemma.plots.plot_markov_model) show that indeed just the transition probabilities will be printed by default. 

> arrow_labels ('weights', None or a ndarray(n,n) with label strings. Optional, default='weights') – Strings to be placed upon arrows. If None, no labels will be used. If ‘weights’, the elements of P will be used. If a matrix of strings is given by the user these will be used.

**Comment by orthonalmatrix** [comment]
My mistake! Thanks for the clarification!
