### ISSUE TITLE
CK test doesn't justify HMM

### ISSUE THREAD

**Issue by Bazzinga18** [markovmodel/PyEMMA#1549]
Hey everyone,
On performing CK test for HMM, the resultant plot doesn't show anything. what does this mean??
i am attaching the screenshot here:
![Screenshot from 2022-03-08 19-46-32](https://user-images.githubusercontent.com/61143449/157256084-c68071c4-d703-4e02-ad4e-3b6b13ba2561.png)

**Comment by thempel** [comment]
Maybe you want to look into the objects that you are plotting - what are the predictions and estimates of the CK-test, in numbers? That should help you to debug the model.
