### ISSUE TITLE
freader.featurizer.add_distances_ca() fails

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#155]
Apparently this is untested:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-f102cd3a9e7b> in <module>()
----> 1 freader.featurizer.add_distances_ca()

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/io/featurizer.pyc in add_distances_ca(self)
    254         self.distance_indexes = self.pairs(self.select_Ca())
    255 
--> 256         f = DistanceFeature(self.topology, atom_pairs=self.distance_indexes)
    257         self.active_features.append(f)
    258         self._dim += np.shape(self.distance_indexes)[0]

TypeError: __init__() got an unexpected keyword argument 'atom_pairs'

**Comment by marscher** [comment]
Am 28.03.2015 um 21:03 schrieb Frank Noe:
> Apparently this is untested:
>
> ------------------------------------------------------------------------
>
> TypeError Traceback (most recent call last)
> in ()
> ----> 1 freader.featurizer.add_distances_ca()
>
> /Users/noe/data/software_projects/pyemma/pyemma/coordinates/io/featurizer.pyc
> in add_distances_ca(self)
> 254 self.distance_indexes = self.pairs(self.select_Ca())
> 255
> --> 256 f = DistanceFeature(self.topology, atom_pairs=self.distance_indexes)
> 257 self.active_features.append(f)
> 258 self._dim += np.shape(self.distance_indexes)[0]
>
> TypeError: *init*() got an unexpected keyword argument 'atom_pairs'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/155>.
>
this is old code and already fixed.

**Comment by franknoe** [comment]
That was in the devel I pulled today!

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
I checked - latest devel branch

https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/io/featurizer.py

still has this line:

256     f = DistanceFeature(self.topology, atom_pairs=self.distance_indexes)

which is causing the problem (there is no parameter atom_pairs). There 
are actually *a lot* of bugs in the Featurizer. I have created a feature 
branch an am working on it now!

Frank.

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 29.03.2015 um 05:26 schrieb Frank Noe:
> I checked - latest devel branch
>
> https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/io/featurizer.py
>
> still has this line:
>
> 256 f = DistanceFeature(self.topology, atom_pairs=self.distance_indexes)
>
> which is causing the problem (there is no parameter atom_pairs). There
> are actually *a lot* of bugs in the Featurizer. I have created a feature
> branch an am working on it now!
>
> Frank.
>
> --
>
> ----------------------------------------------
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
>
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> Mail: Arnimallee 6, 14195 Berlin, Germany
> ----------------------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/155#issuecomment-87346530>.
>
Thanks, for doing double work, If you've checked the pull requests page 
- There is still need for discussion. I've fixed lots of bugs in the 
featurizer in this PR.

**Comment by franknoe** [comment]
Am 29/03/15 um 12:54 schrieb Martin K. Scherer:
>
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/markovmodel/PyEMMA/issues/155#issuecomment-87346530>.
> >
> Thanks, for doing double work, If you've checked the pull requests page
> - There is still need for discussion. I've fixed lots of bugs in the
> featurizer in this PR.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/155#issuecomment-87392357>.
>
Sorry if I did double work, will check more thoroughly in the future - I 
am still a starter with PR's.
I have checked the PR page but it was not obvious to me that there was a 
PR fixing bugs in the Featurizer.
Moreover I needed a quick fix, so it was easier for me to just do it 
rather than waiting until Europe is awake.

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 29.03.2015 um 17:24 schrieb Frank Noe:
> Am 29/03/15 um 12:54 schrieb Martin K. Scherer:
>>
>> > Reply to this email directly or view it on GitHub
>> >
>> <https://github.com/markovmodel/PyEMMA/issues/155#issuecomment-87346530>.
>> >
>> Thanks, for doing double work, If you've checked the pull requests page
>> - There is still need for discussion. I've fixed lots of bugs in the
>> featurizer in this PR.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/markovmodel/PyEMMA/issues/155#issuecomment-87392357>.
>>
> Sorry if I did double work, will check more thoroughly in the future - I
> am still a starter with PR's.
> I have checked the PR page but it was not obvious to me that there was a
> PR fixing bugs in the Featurizer.
> Moreover I needed a quick fix, so it was easier for me to just do it
> rather than waiting until Europe is awake.
Sure. Sorry it did not work as expected and thanks for the great job!

In future please create PR from your fork and not pushing new branches
to markovmodel, since it will clutter all other forks.

**Comment by franknoe** [comment]
OK

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
