### ISSUE TITLE
Progress stuck after ITS estimation

### ISSUE THREAD

**Issue by satyajitkhatua09** [markovmodel/PyEMMA#1553]
HI,

I am studying a system where I have successfully discretized the TICA coordinates to a number of different states using the k-means algorithm. But after first step of validation with ITS estimation, the progress for the step to determine a MSM for the specified lag time has been halted. For that neither the  progress was reflected nor any error message has been shown even for an entire day. It is running in my desktop without such problem. But because of memory issue during the order parameter estimation, I have to shift to the GPU machine with high end configurations. I didn't understand what I am doing wrong. I have attached a copy of the problem.

I am extracting the features using the featurizer from the uploaded trajectory that has some 3000 solvents in it. The GPU machine uses CentOS 7 version and the installed PyEMMA version is 2.5.7. Any help would be appreciated.

![lig_unbinding_from_traj-Jupyter-Notebook](https://user-images.githubusercontent.com/103630954/163379349-8a42e268-a6a0-44ef-a800-0fc4e655d75f.png)

**Comment by clonker** [comment]
This is likely a parallelization issue. Can you run `cktest` with the keyword argument `n_jobs=1` and report back if that fixed things?

**Comment by satyajitkhatua09** [comment]
Hi,
Thanks for the reply. Now, it is running perfectly. Thanks  a lot.

**Comment by clonker** [comment]
Glad this helped! In the future we are going to use the way it is implemented in deeptime so I am closing this.
