### ISSUE TITLE
unable to execute

### ISSUE THREAD

**Issue by debanjansen48** [markovmodel/PyEMMA#1554]
I installed it using pip3. but unable to execute from jupyter notebook or from command line. the error given bellow

**Command line error**
~/Desktop$ python3
Python 3.9.5 (default, Jun  4 2021, 12:28:51) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyemma
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/debanjan/amber20/miniconda/lib/python3.9/site-packages/pyemma/__init__.py", line 34, in <module>
    from . import msm
  File "/home/debanjan/amber20/miniconda/lib/python3.9/site-packages/pyemma/msm/__init__.py", line 83, in <module>
    from msmtools.analysis.dense.pcca import PCCA
  File "/home/debanjan/amber20/miniconda/lib/python3.9/site-packages/msmtools/__init__.py", line 41, in <module>
    from . import estimation
  File "/home/debanjan/amber20/miniconda/lib/python3.9/site-packages/msmtools/estimation/__init__.py", line 91, in <module>
    from .api import *
  File "/home/debanjan/amber20/miniconda/lib/python3.9/site-packages/msmtools/estimation/api.py", line 38, in <module>
    from . import dense
  File "/home/debanjan/amber20/miniconda/lib/python3.9/site-packages/msmtools/estimation/dense/__init__.py", line 24, in <module>
    from .mle import mle_trev, mle_trev_given_pi
  File "msmtools/estimation/dense/mle/mle_trev.pyx", line 1, in init msmtools.estimation.dense.mle.mle_trev
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
>>> 

**Jupyter notebook issue**
!pip3 install pyemma
Requirement already satisfied: pyemma in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (2.5.11)
Requirement already satisfied: tqdm>=4.23 in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (from pyemma) (4.62.3)
Requirement already satisfied: psutil>=3.1.1 in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (from pyemma) (5.8.0)
Requirement already satisfied: mdtraj>=1.9.2 in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (from pyemma) (1.9.7)
Requirement already satisfied: decorator>=4.0.0 in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (from pyemma) (5.1.1)
Requirement already satisfied: matplotlib in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (from pyemma) (3.5.0)
Requirement already satisfied: bhmm<0.7,>=0.6 in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (from pyemma) (0.6.3)
Requirement already satisfied: msmtools>=1.2 in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (from pyemma) (1.2.6)
.......................
......................
Requirement already satisfied: multiprocess>=0.70.12 in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (from pathos->pyemma) (0.70.12.2)
Requirement already satisfied: joblib>=0.11 in /home/debanjan/amber20/miniconda/lib/python3.9/site-packages (from scikit-learn->deeptime->pyemma) (1.1.0)

**import pyemma**
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3014/684328617.py in <module>
----> 1 import pyemma

ModuleNotFoundError: No module named 'pyemma'

Same with Mdshare

**Comment by clonker** [comment]
It looks like this is an incompatibility issue with msmtools. Can you install msmtools with conda instead of pip and try again?

**Comment by clonker** [comment]
Assuming this resolved itself, otherwise please feel free to reopen
