### ISSUE TITLE
Select subset of atoms as a feature

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#156]
Perhaps this is already in progress in one of the branches, but selecting all atoms or a subset of atoms should be an option in the coordinates featurizer.

**Comment by marscher** [comment]
isn't that done #162? Despite aligning to a reference structure.

**Comment by franknoe** [comment]
Yes, I wanted to wait for the merge with the close.

Am 30/03/15 um 13:17 schrieb Martin K. Scherer:
>
> isn't that done #162 <https://github.com/markovmodel/PyEMMA/pull/162>? 
> Despite aligning to a reference structure.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/156#issuecomment-87637732>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Done by the last merge
