### ISSUE TITLE
Different transition time in compare to experimental results.

### ISSUE THREAD

**Issue by Bazzinga18** [markovmodel/PyEMMA#1568]
Hi,
I have few trajectories with almost 30 ms of data of a protein which experimently proves to be unfolds after 10 ms.
When i modeled MSMs of about 20 ms of data the transition time between folded and unfolded metastable state came around 10 ms although when i took data of 30 ms this transition time between folded and unfolded metastable state increases by 3 folds.
Why is this so and what should i do to further to match this time with the experimental one?
thanks

**Comment by thempel** [comment]
Hi, it's a bit hard to tell without seeing the data, but here's some ideas: Based on the reported unfolding times and the amount of data, I'm guessing that you have sampled about 2 to 5 unfolding events -- this may not be a very large sample of such events. The MSM has to estimate the transition time (you mean the MFPT?) from these 2-5 observations, which naturally comes with some estimation error. Depending on the part of the data that the MSM was trained on, it may be estimated faster or slower. Maybe it is instructive to do some more systematic bootstrapping validation to obtain the estimation error, or to use a Bayesian MSM.
