### ISSUE TITLE
Basis of the active state fraction and active count fraction

### ISSUE THREAD

**Issue by Bazzinga18** [markovmodel/PyEMMA#1569]
Hello all,
As a beginner i want to ask what is the criteria or the basis of calculating the active state fraction and active count fraction.
how theses fraction comes 1?

**Comment by clonker** [comment]
To estimate a MSM all states need to be connected via observed transitions. So we subselect the largest connected set. Active state and count fraction are percentages expressing how many states (ie cluster centers) and how many transition counts are used in the model, respectively.

**Comment by Bazzinga18** [comment]
THANK YOU SO MUCH
