### ISSUE TITLE
how to import solvent accessible surface area as a feature in pyemma?

### ISSUE THREAD

**Issue by satyajitkhatua09** [markovmodel/PyEMMA#1586]
Hi, 

For one ligand unbinding, I want to use SASA as one of my CVs.  Is there a way to import this feature in PyEMMA? If yes, can you tell me how to do that? This may be a simple question, but I am unable to include this feature. Please help.

WIth regards,
Satyajit Khatua

**Comment by thempel** [comment]
Hi Satyajit Khatua,
you can use mdtraj to compute the SASA using their implementation of the Shrake-Rupley algorithm. It's documented [here](https://www.mdtraj.org/1.9.8.dev0/api/generated/mdtraj.shrake_rupley.html). This function computes the SASA from an mdtraj-`Trajectory`object, which is exactly what you need in order to implement your own custom feature. There's an example on how to do that here https://github.com/markovmodel/PyEMMA/issues/1566#issuecomment-1155126017, can you use that as a template?

**Comment by satyajitkhatua09** [comment]
Hi,

Thank you for the quick response. I will try to import the sasa as you have mentioned.  Will report you back.

Thanks again,
Satyajit Khatua


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by satyajitkhatua09** [comment]
Hi,

I have tried to calculate the SASA feature in these two different instances. The problems are attached herewith. I actually intended to calculate the SASA value for the ligand molecule, not all of the residues. That is where I am getting the errors. Can you help me with this? I have tried importing different options inside mdtraj.shrake_rupley() function. It seems nothing is working for me.

With regards,
Satyajit Khatua

![first_instance](https://user-images.githubusercontent.com/103630954/210358831-8859f4d9-39e8-4c6c-a63f-b3efaa95d2ac.png)
![second_instance](https://user-images.githubusercontent.com/103630954/210358851-10ad131a-a4bf-48e3-9168-dd4ec74f04fb.png)

**Comment by thempel** [comment]
The function call `shrake_rupley(traj, mode='residue')` returns an array of shape `(n_frames, n_residues)` that contains the SASA per residue for each time frame. You can select the SASA of your ligand if you know which residue-index your ligand has (make sure to use 0-based residue indexing as this is a numpy array). The code inside the function could look something like this: (CAUTION: I didn't check if it works! Please let me know if it does.)
```python
def custom_function(traj, ligand_resid=FIXME):
    # compute ligand sasa and select ligand
    # returns array with length n_frames
    ligand_sasa = mdtraj.shrake_rupley(traj, mode='residue')[:, ligand_resid]
    
    # expand dimension to (n_frames, 1) as required by pyemma and return
    return ligand_sasa[:, None]
```

**Comment by satyajitkhatua09** [comment]
Hi,

Thanks a lot. I have got the ligand sasa as per your suggestion.

With regards,
Satyajit Khatua

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
