### ISSUE TITLE
Develop a concept for dealing with meaningless eigenvalues / timescales

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#159]
Depending on the basis set, the lag time and the statistics many eigenvalues of a transition matrix, a TICA problem or a variational problem might be negative. They typically look like this:

![screen shot 2015-03-28 at 22 55 35](https://cloud.githubusercontent.com/assets/6495810/6883071/a5f7ea28-d59d-11e4-9d68-1d1f59d6ee18.png)

One has a bunch of positive eigenvalues, related to actual timescales and useful processes, and then there is a large number of eigenvalues that oscillate around zero. The amplitude of this oscillation can become quite large. Clearly, these are numerical artifacts and it makes no sense to convert them into actual timescales. Currently, we won't notice that because we always compute -tau / log(abs(lambda_i)), which is a meaningful definition by itself, but overlooks this problem.

Should we simply cut the spectrum (i.e. make a rank reduction) for every such model, cutting off all eigenvalues with norms smaller or equal to the largest negative eigenvalue? This would reduce the number of available eigenvalues that we can do anything with.
Downside: this will change the structure of our model. A transition matrix will no longer be a transition matrix after we have done this.

Alternative: Whenenver computing timescales or other spectral properties, prohibit (or warn) to use eigenvalues beyond this limit. Note that our "rule of thumb" to not use timescales that are smaller than tau is a way to deal with part of this problem, but it's neither a rigorous nor a complete solution.

**Comment by gph82** [comment]
What about an option for rank_reduction = False? This way, we give the user some freedom and also the pipeline knows about the T-matrix not being a T-matrix anymore etc.

**Comment by trendelkampschroer** [comment]
I don't think there is an automated solution to this problem and I vote against just cutting the spectrum and breaking everything downstream that relies on T being a transition matrix. 

Maybe we should rise awareness that these artifiacts are due to the fact that we are building a simplified model with the aim of capturing the dominant, i.e. slow, processes. In the situation when there is no spectral gap and one is unsure which eigenvalues can be trusted the user has to make a decision. I don't think we can and I think neither should we try to automate this. 

Each method that involves estimating the implied timescales has the 'k' keyword, asking the user to specify how many time-scales he wants to estimate. 

It might also help to advertise the analysis via mean-first passage times which allow to investigate selected processes seperately and also allow to deal with the effects of asymmetries in the free-energies.

**Comment by franknoe** [comment]
Am 30/03/15 um 09:41 schrieb Benjamin Trendelkamp-Schroer:
>
> I don't think there is an automated solution to this problem and I 
> vote against just cutting the spectrum and breaking everything 
> downstream that relies on T being a transition matrix.
>
> Maybe we should rise awareness that these artifiacts are due to the 
> fact that we are building a simplified model with the aim of capturing 
> the dominant, i.e. slow, processes. In the situation when there is no 
> spectral gap and one is unsure which eigenvalues can be trusted the 
> user has to make a decision. I don't think we can and I think neither 
> should we try to automate this.
>
I agree, it is an analysis issue. For variational problems (TICA etc) we 
are already doing a spectral truncation, but this is just to reduce the 
problem size to the rank that is supported by the overlap matrix, such 
that a numerical solution is possible. In analysis modules such as the 
implied timescales module we could take care of restricting the 
attention to eigenvalues that we think are trustworthy.
>
> Each method that involves estimating the implied timescales has the 
> 'k' keyword, asking the user to specify how many time-scales he wants 
> to estimate.
>
> It might also help to advertise the analysis via mean-first passage 
> times which allow to investigate selected processes seperately and 
> also allow to deal with the effects of asymmetries in the free-energies.
>
This is an interesting discussion. I am not sure yet if this is a 
replacement for a timescale analysis though, because having to define 
sets means you already have to know a lot about your system. Perhaps 
there is some automated way to include PCCA here? Would exit times be 
robust to boundary errors if we use PCCA sets? Is there any way to 
compute exit times when we have memberships rather than a crisp set?


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by RobertArbon** [comment]
Hi, 

I'm wondering whether I could bring up a related question here.  Specifically I'm talking about your comment: 

> Currently, we won't notice that because we always compute -tau / log(abs(lambda_i)), which is a meaningful definition by itself, but overlooks this problem.

The question is - why do you take the absolute value of eigenvalues when computing the implied timescales?  As far as I understand negative eigenvalues would correspond to some damped oscillations.  Is this really realistic to include these?

I'm not talking about the oscillatory behaviour you're talking about here however. 



Thanks, 

Rob
