### ISSUE TITLE
NotImplementedError: MSM estimation with connectivity='none' is currently not implemented.

### ISSUE THREAD

**Issue by Harshitasahni** [markovmodel/PyEMMA#1591]
I am trying to build a msm model by using 
"pyemma.msm.estimate_markov_model(data_clust.dtrajs, lag =1,  score_method='VAMP1', connectivity='none')"

If i don't have the connectivity set to 1, it uses "largest" with that i get another error when i do pcca, with nstates = 3, and active states = 3. 
I get the following error:
IndexError: index 3 is out of bounds for axis 0 with size 3

**Comment by thempel** [comment]
Apparently your MSM transition matrix is not connected. Before using PCCA and playing with the connectivity parameter, I would carefully look at the implied timescales convergence. You can also compute MSMs with the function you're using above (using default connectivity), but using different lag times, and check out the resulting active set or active state fraction (`msm.active_set` or `msm.active_state_fraction `).

**Comment by Harshitasahni** [comment]
Thank you. I understood.

**Comment by Harshitasahni** [comment]
Thank  you.
