### ISSUE TITLE
TICA and other heavy algorithms should give estimated runtime

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#160]
I have just experimented with BPTI data, and it's a bit user-unfriendly that one gets no idea how long an algorithm will run. There are some INFO printouts but depending on the data and the settings one of these steps takes ages. I suggest to give a rough estimate of the runtime once such an estimate is feasible.

Example: Data streaming processing with TICA. In my example there are 4 million frames and the chunksize was 100 by default. After processing one chunk TICA could tell me how many minutes or hours the calculation of the mean or the covariance matrices is expected to take - just measure the time of processing the first chunk and multiply it by the number of chunks.

Of course this doesn't help with in-memory operation (where we have one chunk), but perhaps the runtime is less of an issue if the data fits into memory.

Alternative: Each algorithm can provides an estimate of the number of operations (which is usually known, or an upper bound is known), and an estimate of the time duration per operation (by executing the basis operation a few times when starting - not to actually compute anything, but just to estimate the time on the current processor). Then produce a time estimate.

Time estimates could then be printed by INFO logging, e.g.
TICA    INFO    Computing mean. ETA: 17.5 sec ... DONE
TICA    INFO    Computing C(0), C(tau). ETA: 5.32 min ... 

The ... indicates that the calculation is running.

**Comment by fabian-paul** [comment]
Measuring the time it takes to process one chunk sounds good.
I think we should no worry too much about the "operate in memory" case. One can process the data as a sequence of chunks even when the data is held in memory, there is no fundamental problem here.

**Comment by franknoe** [comment]
... or always make the estimate after either the first chunk or t (e.g. 
100) time steps. In case if the chunksize is set very large.

Am 30/03/15 um 12:20 schrieb fabian-paul:
>
> Measuring the time it takes to process one chunk sounds good.
> I think we should no worry too much about the "operate in memory" 
> case. One can process the data as a sequence of chunks even when the 
> data is held in memory, there is no fundamental problem here.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/160#issuecomment-87623604>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
we can impl this maybe generally in Transformer.parameterize and include a description string from describe or impl __str__ method to get a name like "TICA". If you really want to know which quantity is currently calculating, have a look at the info log messages.

**Comment by franknoe** [comment]
Yes, that would be good!

Am 30/03/15 um 13:16 schrieb Martin K. Scherer:
>
> we can impl this maybe generally in Transformer.parameterize and 
> include a description string from describe or impl *str* method to get 
> a name like "TICA". If you really want to know which quantity is 
> currently calculating, have a look at the info log messages.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/160#issuecomment-87637640>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
I dont know if we can handle multi-pass algos that way, since each path most likely takes a different amount of time. Maybe add an _estimate_runtime method, which gets overridden by multipass algos?

**Comment by franknoe** [comment]
Sure, I was thinking of a separate estimate for each pass. A total 
estimate is not easily feasible in the beginning.

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
we can easily calculate an very precise estimate for chunked operations (update mean/cov). But for the diagonalisation we can only make a guess. We know the complexity is n^3, but we do not know the constant. Guessing that would involve approx. floating point operations and use timeit to measure the speed of those.
I've done the first part already, but need to think about the last one.

**Comment by franknoe** [comment]
I think we don't need a running estimate for that. The most 
time-consuming part is the estimation of the matrices rather than the 
diagonalization.

Estimation of a covariance matrix = T N^2
Diagonalization = N^3

But T >> N

Am 17/04/15 um 19:23 schrieb Martin K. Scherer:

> we can easily calculate an very precise estimate for chunked 
> operations (update mean/cov). But for the diagonalisation we can only 
> make a guess. We know the complexity is n^3, but we do not know the 
> constant. Guessing that would involve approx. floating point 
> operations and use timeit to measure the speed of those.
> I've done the first part already, but need to think about the last one.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/160#issuecomment-94031558.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Done by Martin's #264
