### ISSUE TITLE
pyemma doc is not compatible with sphinx 1.3.1+

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#163]
I've installed the new sphinx with pip and none of the generated rsts (autodocs) are being included in the html. So far sphinx 1.2.3 is stable, but I when 1.3.1 will be released, we have a problem...

**Comment by franknoe** [comment]
We can specifically ask for sphinx 1.2.3 in the install requirements.
Have you figured out what would need to be changed to be compatible with 
the new sphinx?

Am 29/03/15 um 17:59 schrieb Martin K. Scherer:
>
> I've installed the new sphinx with pip and none of the generated rsts 
> (autodocs) are being included in the html. So far sphinx 1.2.3 is 
> stable, but I when 1.3.1 will be released, we have a problem...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/163>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 29.03.2015 um 18:04 schrieb Frank Noe:
> We can specifically ask for sphinx 1.2.3 in the install requirements.
We can do that for the moment to ensure, the doc will work even if 1.3.1
will be default.
> Have you figured out what would need to be changed to be compatible with
> the new sphinx?
not yet. But I will investigate this soon.

**Comment by marscher** [comment]
pinned to 1.2.3 with commit dc27ac4

**Comment by marscher** [comment]
maybe this issue arises since I installed the new sphinx with pip, but left all dependencies installed by conda. Should try with a clean environment though.

**Comment by marscher** [comment]
can not reproduce now with sphinx 1.3.1. Closing it.

**Comment by marscher** [comment]
it seems all autosummary directives in the static index pages do not correctly link. They are completely empty in 1.3.1. I have no clue why this is the case.

**Comment by ppxasjsm** [comment]
I don't have that problem, on my deskop maschine but I have the problem when building on my Mac. I can go and hunt for some reasons.

**Comment by ppxasjsm** [comment]
Also I am almost done with the doc fixes, will try and finish them today.

**Comment by marscher** [comment]
That's interesting. On Linux I get empty (despite the static headings)
API index pages and a ton of warnings, that generated files are not
being included in any toctree.

**Comment by ppxasjsm** [comment]
I also get tonnes of warning, but they all seem to be included none the less. On the Mac everything is completely empty.

**Comment by ppxasjsm** [comment]
Plus tonnes more warnings

**Comment by ppxasjsm** [comment]
Oh no I take it all back. I am still on version 1.2.3 on my linux machine...I might just not upgrade then for now.

**Comment by ppxasjsm** [comment]
Ok I have done a bit of poking, but don't know where the problem might lie. The .rst files are all generated but somehow not linked properly. I don't really have more time to look into this though.

**Comment by marscher** [comment]
I'll try to build a minimal (non)-working example to get some help of a 
sphinx guru. Thanks for your effort!

**Comment by marscher** [comment]
we are suffering from this bug sphinx-doc/sphinx#1822. Until it will be fixed, we just pin down sphinx to 1.2.3
