### ISSUE TITLE
Featurizer.describe() should return list of strings, not list of list of strings

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#165]
To make it consistent with the feature vector returned (T x d)-array with T timesteps and d features, the describe method should return a list of d strings.

That means multiple feature descriptions should be appended to one list. This is a 30 sec - change, but I don't want to do it because there is an ongoing PR.

**Comment by marscher** [comment]
you are free to go, I've merged it.

**Comment by franknoe** [comment]
thanks, great!

Am 30/03/15 um 13:18 schrieb Martin K. Scherer:
>
> you are free to go, I've merged it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/165#issuecomment-87637814>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Done
