### ISSUE TITLE
refactor transformers impl detail methods to begin with underscore

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#169]
Problem is that the use will sometimes operate directly on these objects (eg. on TICA to have a look at eigenvalues and vectors), but he will definitely be confused by the mass of implementation detail methods and attributes (like self.t, self.itraj which are only internal counters) or methods like next_chunk, which are not supposed to call directly.

**Comment by franknoe** [comment]
I fully agree

Am 30/03/15 um 17:56 schrieb Martin K. Scherer:
>
> Problem is that the use will sometimes operate directly on these 
> objects (eg. on TICA to have a look at eigenvalues and vectors), but 
> he will definitely be confused by the mass of implementation detail 
> methods and attributes (like self.t, self.itraj which are only 
> internal counters) or methods like next_chunk, which are not supposed 
> to call directly.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/169>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
