### ISSUE TITLE
The right way to cross-project and cross-assign?

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#171]
While looking through Franks use cases of the coordinates module we (Martin, Guillermo and Fabian) saw that Frank proposed a map method in the transformer that takes some data as an argument
```Python
tica = ... # construct TICA transformer
ics = tica.map(data)
```
This feature is not available right now. The map function that Frank is referring to is not the one which is implemented and which only processes chunks but not trajectories.
Nevertheless this made us think about cases where such a function is needed, namely that you would project some data with TICA which is not the same data as TICA was parametrized with. This could occur in adaptive sampling where the TICA projection matrix is only updated every N iterations and data is projected with a "slightly outdated" projection matrix. The same applies to clustering: one could possibly assign data to cluster centers that were not inferred from the same data.

How should we implement this? The coordinate module doesn't provide the functionality to project other data than the one which was used in parametrization. (Except for some hacks like using the map-Method.)
I see two ways of dealing with this problem. 

1) Add a new method to the transfomer class that allows to temporarily change the data producer. We could call this method "map". Its single argument would be a second transformer object that is different from "self". But what should be the return value of map? The method has to work even when the data doesn't fit into memory. So returning trajectories is not viable. A more Pythonic solution could be to return an iterator.

2) Have "Linear_affine_projection" and "Assignment" transformers. These could be initialized with the pair (mean, projection_matrix) or cluster_centers respectively. The workflow would be as follows.
First the user parametrizes a TICA transformer or a clustering transformer with some data. Then the mean and projection matrix or the cluster centers are copied by the user (and possibly saved to a file). When new data needs to be projection, the user constructs a pipeline with a "Linear_affine_projection" or "Assignment" transfomers that is initialized with the old matrix/cluster centers.

**Comment by franknoe** [comment]
First of all, please confirm the skype call later.

map: I don't understand. Of course there is a map method, see e.g.

https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/transform/tica.py
     line 236-251.

and it is used in the transformer, e.g.

https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/transform/transformer.py
     line 293

I've introduced this method deliberately and it should definitely stay 
and is needed. Please *don't* remove a function without asking the 
person who created it (usually for a reason).

This is the very idea of a transformer that it can map arbitrary input 
data of the right format. It is not a hack and it should not be replaced 
by an iterator - I want the functionality to transform arbitrary data 
sets into arbitrary data sets (chunks, trajectories - the new 
functionality I ask for would be sets of trajectories).

The map method itself has nothing to do with pipeline processing 
(although it is used in pipeline processing - see reference to 
transformer above). It is meant for direct access to the transformer 
object, e.g. when it is created in memory by:

     tica = coordinates.tica(data=dataset1, lag=10, ndim=2)
     tica.map(dataset2)

There is also no memory problem here. The memory problems arise in how 
to use this method, i.e. what data set to input and to request. So if 
the user wants to map to an output size that doesn't fit their memory, 
that's the users problem and we should not interfere with this.



Am 31/03/15 um 12:34 schrieb fabian-paul:
>
> While looking through Franks use cases of the coordinates module we 
> (Martin, Guillermo and Fabian) saw that Frank proposed a map method in 
> the transformer that takes some data as an argument
>
> tica=  ...# construct TICA transformer
> ics=  tica.map(data)
>
> This feature is not available right now. The map function that Frank 
> is referring to is not the one which is implemented and which only 
> processes chunks but not trajectories.
> Nevertheless this made us think about cases where such a function is 
> needed, namely that you would project some data with TICA which is not 
> the same data as TICA was parametrized with. This could occur in 
> adaptive sampling where the TICA projection matrix is only updated 
> every N iterations and data is projected with a "slightly outdated" 
> projection matrix. The same applies to clustering: one could possibly 
> assign data to cluster centers that were not inferred from the same data.
>
> How should we implement this? The coordinate module doesn't provide 
> the functionality to project other data than the one which was used in 
> parametrization. (Except for some hacks like using the map-Method.)
>
I disagree - It's not a hack.
>
> I see two ways of dealing with this problem.
>
> 1) Add a new method to the transfomer class that allows to temporarily 
> change the data producer.
>
No, this has nothing to do with the data producer. In principle a 
transformation should not even need a data producer. Think of an 
alternative way of initializing TICA from known covariance matrices:
     tica = TICA(C0, Ctau)
     tica.map(X)
This is currently not implemented, but should be possible.
>
> We could call this method "map". Its single argument would be a second 
> transformer object that is different from "self". But what should be 
> the return value of map? The method has to work even when the data 
> doesn't fit into memory. So returning trajectories is not viable.
>
Yes it is, see above.
>
> A more Pythonic solution could be to return an iterator.
>
In addition OK, not as an alternative.
>
> 2) Have "Linear_affine_projection" and "Assignment" transformers. 
> These could be initialized with the pair (mean, projection_matrix) or 
> cluster_centers respectively.
>
No, this is an indirect solution, see above
>
> The workflow would be as follows.
> First the user parametrizes a TICA transformer or a clustering 
> transformer with some data. Then the mean and projection matrix or the 
> cluster centers are copied by the user (and possibly saved to a file). 
> When new data needs to be projection, the user constructs a pipeline 
> with a "Linear_affine_projection" or "Assignment" transfomers that is 
> initialized with the old matrix/cluster centers.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/171>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by fabian-paul** [comment]
Ok, I see. So we will just extend the map method to work with lists of ndarrays.

I'm not fully ok with your solution for the case when the data doesn't fit into memory. Did I understand you correctly that the user should split the data into smaller pieces and pass them sequentially to the map function? If so, I think this goes a bit against the philosophy of the pipeline. I thought that the pipeline should hide all the splitting, looping and data combining from the user. Why should "map" be an exception to that approach?

**Comment by franknoe** [comment]
Am 31/03/15 um 15:33 schrieb fabian-paul:
>
> Ok, I see. So we will just extend the map method to work with lists of 
> ndarrays.
>
yes. We could also provide a map_all for that case if you think that's 
cleaner.
>
> I'm not fully ok with your solution for the case when the data doesn't 
> fit into memory. Did I understand you correctly that the user should 
> split the data into smaller pieces and pass them sequentially to the 
> map function?
>
The user can do whatever he likes. Memory management is needed in 
complex processing steps that are beyond user control, but not in direct 
operations. Consider for example that I have a x-vector that is 1000000 
x 1. Numpy allows me to do np.dot(x, x.T), although that will likely 
blow up my memory. That's OK, because it's obvious what's the problem 
here. In contrast, within a processing pipeline there are many steps 
that the user has no access to, and therefore the memory management 
needs to be done to as to ensure that the pipeline can function.

My main point is that in most cases full trajectories and also 
transformer output will fit into memory, and then I also want to have it 
in memory because I might want to do various non-emma analyses with the 
data, such as plotting or putting them into other programs.

Let's discuss it later.
>
> If so, I think this goes a bit against the philosophy of the pipeline.
>
No, it is completely independent of the pipeline. There is no pipelining 
involved in this use-case.

The pipeline is one way of doing data processing that is meant for the 
case where data needs to be streamed. Perhaps it is also more convenient 
in some cases, although I'm not sure. But the direct operation should 
always be possible.
>
> I thought that the pipeline should hide all the splitting, looping and 
> data combining from the user. Why should "map" be an exception to that 
> approach?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/171#issuecomment-88087018>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
