### ISSUE TITLE
Featurizer default behavior

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#173]
In MDFeaturizer.map(), this behavior:

```python
        # if there are no features selected, return given trajectory
        if len(self.active_features) == 0:
            warnings.warn("You have no features selected. Returning plain coordinates.")
            return traj.xyz
```

is wrong, because the featurizer should return T features of length N, i.e. a two-dimensional array. This option would return a three-dimensional tensor. We need to flatten the xyz coordinates. I believe it is:

```python
return np.reshape(traj.xyz, (traj.xyz.shape[0], traj.xyz.shape[1]*traj.xyz.shape[2])
```

But I'm not sure if this copies the data or just returns a view. Returning just a view would be better.

**Comment by marscher** [comment]
fixed by a4f0f8c
