### ISSUE TITLE
pyemma/coordinates/util/patches.py, line 142, ValueError: need more than 3 values to unpack

### ISSUE THREAD

**Issue by sstolzen007** [markovmodel/PyEMMA#174]
Dear PyEmma-Gurus,

just downloaded the new version of PyEmma (0.13+dev).
Running my previously functional code again with this new version, I receive the following error (see below).
help(md.formats.dcd.DCDTrajectoryFile.read)

Would
xyz, _, _ = f.read(skip, atom_indices=atom_indices)
instead of 
xyz, _, _, _ = f.read(skip, atom_indices=atom_indices)
be the solution?

Thanks,
Sebastian

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-0aa587e5dcb6> in <module>()
      3     print mycnd
      4     ticareader[mycnd]=get_ticareader_from_trajs(trjIDs[mycnd],numnodes,indirstem)
----> 5     for_taus_do_tica(ticareader[mycnd])

<ipython-input-1-09348ab3e7c7> in for_taus_do_tica(myticareader)
     50     for i in range(len(l_tau)):
     51         tica.append(TICA(lag=l_tau[i], output_dimension=2, epsilon=0))
---> 52         run_chain(build_chain([myticareader,tica[i]], chunksize=1000))
     53         #print 1.*sum(abs(tica.eigenvalues)>0.5)/len(tica.eigenvalues)
     54         plt.figure()

/storage/mi/sstolzen/mypackages/PyEMMA/pyemma/coordinates/util/chaining.pyc in run_chain(chain)
     25     for c in chain:
     26         if hasattr(c, 'parametrize'):
---> 27             c.parametrize()

/storage/mi/sstolzen/mypackages/PyEMMA/pyemma/coordinates/transform/transformer.pyc in parametrize(self)
    173                                 "trajectory nr %i to short, skipping it" % itraj)
    174                             break
--> 175                         X, Y = self.data_producer.next_chunk(lag=lag)
    176                     L = np.shape(X)[0]
    177                     # last chunk in traj?

/storage/mi/sstolzen/mypackages/PyEMMA/pyemma/coordinates/io/feature_reader.pyc in next_chunk(self, lag)
    237                                                 skip=self.curr_lag)
    238             try:
--> 239                 adv_chunk = self.mditer2.next()
    240             except StopIteration:
    241                 # When mditer2 ran over the trajectory end, return empty chunks.

/storage/mi/sstolzen/mypackages/PyEMMA/pyemma/coordinates/util/patches.pyc in iterload(filename, chunk, **kwargs)
    140                 ptr = 0
    141                 if skip > 0:
--> 142                     xyz, _, _, _ = f.read(skip, atom_indices=atom_indices)
    143                     if len(xyz) == 0:
    144                         raise StopIteration()

ValueError: need more than 3 values to unpack

**Comment by marscher** [comment]
Am 31.03.2015 um 19:41 schrieb sstolzen007:
> Dear PyEmma-Gurus,
> 
> just downloaded the new version of PyEmma (0.13+dev).
Where did you get this version info from? (the version string does not
match to anything we have ever used.)
> Running my previously functional code again with this new version, I
> receive the following error (see below).
> help(md.formats.dcd.DCDTrajectoryFile.read)
> 
> Would
> xyz, _, _ = f.read(skip, atom_indices=atom_indices)
> instead of
> xyz, _, _, _ = f.read(skip, atom_indices=atom_indices)
> be the solution?
Yes. Actually that should be fixed. Maybe I forgot to merge something -
or you are on the wrong version. Please use latest devel for testing!

**Comment by marscher** [comment]
sorry, it was not fixed until now. Thanks for your report!

**Comment by sstolzen007** [comment]
Am 31.03.15 um 19:45 schrieb Martin K. Scherer:
> Am 31.03.2015 um 19:41 schrieb sstolzen007:
> > Dear PyEmma-Gurus,
> >
> > just downloaded the new version of PyEmma (0.13+dev).
> Where did you get this version info from? (the version string does not
> match to anything we have ever used.)

PyEMMA/versioneer.py

I just downloaded the latest version using git

**Comment by marscher** [comment]
> just downloaded the new version of PyEmma (0.13+dev).
>> Where did you get this version info from? (the version string does not
>> match to anything we have ever used.)
> 
> PyEMMA/versioneer.py
the version is queried like this:

import pyemma
print pyemma.__version__


> 
> I just downloaded the latest version using git
great :)

**Comment by sstolzen007** [comment]
thanks :-)

Am 31.03.15 um 20:28 schrieb Martin K. Scherer:
