### ISSUE TITLE
mm_ commands still use old API

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#175]
All of the following commands are nonfunctional because they are trying to use API that doesn't exist anymore:

* mm_discretize

    ```python
    from pyemma.coordinates.clustering.api import kmeans, regspace, kregspace, assign
    ```
* mm_cluster:

    ```python
        if args.algorithm == 'kmeans':
            clustering = kmeans(args.input, args.k, args.maxiterations)
        elif args.algorithm == 'regspace':
            clustering = regspace(args.input, args.dmin, args.metric)
    ```
    and
    ```python
        writer.addAll(clustering._jclustering.getClusterCenters())
    ```
* mm_tica

    ```python
    from pyemma.coordinates.transform.tica_amuse import Amuse
    ```
* mm_project

    ```python
    from pyemma.coordinates.transform.tica import Amuse, rename, log_loop
    ```

My PyCharm finds and points these errors without running. Please again: use a decent IDE and never release such code. There must be a way to do these simple code checks automatically.

All command line interfaces are in my opinion deprecated. We should probably entirely redesign them once the API is stable. I still assign this to Milestone v1.1.3 because we can't release broken code. Maybe we should remove them altogether until we have a new CLI concept.

**Comment by marscher** [comment]
I vote for deleting those scripts, they have never been used and are not 
really useful.

**Comment by trendelkampschroer** [comment]
Ok for me

**Comment by franknoe** [comment]
OK!

Am 01/04/15 um 14:52 schrieb Martin K. Scherer:
> I vote for deleting those scripts, they have never been used and are not
> really useful.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/175#issuecomment-88467617>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
