### ISSUE TITLE
Document how to write docs

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#187]
Please document how to write docs and also how to compile and view them here:

https://github.com/markovmodel/PyEMMA/blob/devel/doc/source/DEVELOPMENT.rst

**Comment by marscher** [comment]
Docstrings in RST/Numpy format are self-explaining. And we have tons of examples.

**Comment by marscher** [comment]
http://www.emma-project.org/latest/DEVELOPMENT.html?highlight=howto_document
