### ISSUE TITLE
Refactor "io" packages and "input" function to avoid shadowing system modules

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#191]
current situation

coordintates.io
msm.io

shadow builtin package "io" - We should think of a new name (eg. io_utils) to circumvent confusion.

Also:

coordinates.api.input shadows a python builtin

**Comment by marscher** [comment]
actually this problem only occurs, if a programmer writing internal modules for pyemma would try to import io (expecting the pyemma.something.io module, since he writes his module on the level of something, but he will get the system io module since it has a higher import priority). So we can keep it like this. I would consider this change a low-priority and not as urgent to have it 1.2 release!

**Comment by marscher** [comment]
but "input" really shadows a builtin (so one can not use python.__builtin__.input after import * from pyemma.coordinates), which is a blocker IMHO.

**Comment by franknoe** [comment]
OK, we have to resolve it now, because input is an API function and I 
want to avoid unnecessary API function name changes later. I'm currently 
lacking a better name, but will think about it.


Am 08/04/15 um 16:02 schrieb Martin K. Scherer:
>
> but "input" really shadows a builtin (so one can not use 
> python.*builtin*.input after import * from pyemma.coordinates), which 
> is a blocker IMHO.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/191#issuecomment-90926084>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
I renamed coordinates.io -> coordinates.data. This is more fitting anyway, because DataInMemory is not really doing IO.

**Comment by marscher** [comment]
Am 11.04.2015 um 13:28 schrieb Frank Noe:
> I renamed coordinates.io -> coordinates.data. This is more fitting
> anyway, because DataInMemory is not really doing IO.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/191#issuecomment-91829164>.
> 
where you done this refactoring? just asking to avoid merge headaches.

**Comment by franknoe** [comment]
In my feature branch (currently local) that I will send as a PR. It will come with the fix of input(...) and a few minor fixes in coordinates.api

**Comment by franknoe** [comment]
Also renamed coordinates.input -> coordinates.source

**Comment by marscher** [comment]
ok

**Comment by franknoe** [comment]
Moving msm.io out of this and closing this issue
