### ISSUE TITLE
New MSM object in dev_release_1.2 is incompatible with old cktest

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#193]
Hi, I will try to see if can get cktest
pyemma.msm.cktest 

to work with the new MSM-type object

**Comment by gph82** [comment]
@franknoe , this is what I mean:
http://page.mi.fu-berlin.de/gph82/cktest_with_new_MSM.html

**Comment by franknoe** [comment]
I honestly haven't tested this yet. Sorry, will do.

Am 07/04/15 um 20:47 schrieb Guillermo Pérez-Hernández:
>
> @franknoe <https://github.com/franknoe> , this is what I mean:
> http://page.mi.fu-berlin.de/gph82/cktest_with_new_MSM.html
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/193#issuecomment-90695493>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
Ok, I believe it's best if you do it yourself, since you have a better overview of the MSM's internal bookeeping

**Comment by franknoe** [comment]
Sure, no prob. I'll sort this out.

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Fixed. I've also included a test that uses the PCCA feature.
