### ISSUE TITLE
develop install of dev_release_1.2 fails on ubuntu 14.04

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#194]
I just tried to install pyemma on my work machine here in Edinburgh. The OS is a pretty vanilla ubuntu 14.04 version with conda installed. 

I just checked out the dev_release_1.2 branch in order to try and run an ipython notebook with it. 
Then do a develop install as described:
```python setup.py develop --user```
And then I get these lovely errors:
```
  File "Cython/Compiler/Visitor.py", line 279, in Cython.Compiler.Visitor.CythonTransform.__call__ (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:6411)
  File "Cython/Compiler/Visitor.py", line 262, in Cython.Compiler.Visitor.VisitorTransform.__call__ (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:6077)
  File "Cython/Compiler/Visitor.py", line 175, in Cython.Compiler.Visitor.TreeVisitor._visit (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:4504)
  File "Cython/Compiler/Visitor.py", line 173, in Cython.Compiler.Visitor.TreeVisitor._visit (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:4447)
  File "Cython/Compiler/Visitor.py", line 289, in Cython.Compiler.Visitor.CythonTransform.visit_Node (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:6603)
  File "Cython/Compiler/Visitor.py", line 241, in Cython.Compiler.Visitor.VisitorTransform.visitchildren (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:5530)
  File "Cython/Compiler/Visitor.py", line 214, in Cython.Compiler.Visitor.TreeVisitor._visitchildren (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:5231)
  File "Cython/Compiler/Visitor.py", line 186, in Cython.Compiler.Visitor.TreeVisitor._visitchild (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:4733)
  File "Cython/Compiler/Visitor.py", line 181, in Cython.Compiler.Visitor.TreeVisitor._visit (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:4623)
  File "Cython/Compiler/Visitor.py", line 140, in Cython.Compiler.Visitor.TreeVisitor._raise_compiler_error (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:3767)
Cython.Compiler.Errors.CompilerCrash: 
Error compiling Cython file:
------------------------------------------------------------
...

.. moduleauthor:: F. Paul <fabian DOT paul AT fu-berlin DOT de>

"""

import numpy
^
------------------------------------------------------------

pyemma/msm/estimation/dense/mle_trev_given_pi.pyx:7:0: Compiler crash in RemoveUnreachableCode

ModuleNode.body = StatListNode(mle_trev_given_pi.pyx:7:0)

Compiler crash traceback from this point on:
  File "Cython/Compiler/Visitor.py", line 173, in Cython.Compiler.Visitor.TreeVisitor._visit (-------src-dir-------/Cython-0.21/Cython/Compiler/Visitor.c:4456)
  File "/home/ppxasjsm/anaconda/lib/python2.7/site-packages/Cython/Compiler/ParseTreeTransforms.py", line 2163, in visit_StatListNode
    if not self.current_directives['remove_unreachable']:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Any thoughts?

**Comment by marscher** [comment]
try cython 0.22

**Comment by franknoe** [comment]
What means 'try' in this case? Isn't the cython version an install 
requirement for Emma?

Am 07/04/15 um 19:48 schrieb Martin K. Scherer:
>
> try cython 0.22
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/194#issuecomment-90670719>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
BTW, we are still working on the release branch, and I guess not all 
tests are working yet. So I guess there can still be problems until this 
is fixed - hopefully by tomorrow but the very latest end of the week.

In any case your compilation bug should not be part of this and should 
be sorted out separately. In the workshop we will do all installations 
through conda to avoid such issues, but I guess we have to wait for the 
release to do that.
Or can we do a pre-release to try things out, Martin?

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
try means: use the version we used to generate the sources (pyx to c conversion). Things horribly brake between versions - just believe me.

**Comment by marscher** [comment]
cython 0.22 should be required in setup though. I thinks its only 0.21 right now.

**Comment by marscher** [comment]
@ppxasjsm can you reproduce this with 0.22 or not?

**Comment by franknoe** [comment]
Isn't the error in the compilation of pyc to c? c is not a source but 
generated.

Am 07/04/15 um 20:01 schrieb Martin K. Scherer:
>
> try means: use the version we used to generate the sources (pyx to c 
> conversion). Things horribly brake between versions - just believe me.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/194#issuecomment-90678949>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by ppxasjsm** [comment]
This worked. Installed fine now.

**Comment by marscher** [comment]
nice. Thanks for your report. Added recent cython to requirements with 2702605

**Comment by franknoe** [comment]
Thanks. I didn't understand the problem though, because the sources are 
just py pyx and the called c code, not the generated c code - so nothing 
cython-version-specific should be in the repo. Can you explain a little 
more?

Am 07/04/15 um 20:09 schrieb Martin K. Scherer:
>
> nice. Thanks for your report. Added recent cython to requirements with 
> 2702605 
> <https://github.com/markovmodel/PyEMMA/commit/2702605591f03551d1520ea779285002ffa8b075>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/194#issuecomment-90683074>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
@franknoe Cythonizing pure python code does not make sense, right?

**Comment by marscher** [comment]
If you install via git, you have to use cython (Since we do not want to maintain the generated c code in the repo). If you install via pip, you download a source archive which contains pre-cythonized files.

**Comment by franknoe** [comment]
That doesn't answer my question. Of course you can't cythonize python 
code, but what exactly is version-specific in our code? Are you saying 
that the cython syntax has changed from 2.1 to 2.2?

Am 07/04/15 um 20:10 schrieb Martin K. Scherer:
>
> @franknoe <https://github.com/franknoe> Cythonizing pure python code 
> does not make sense, right?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/194#issuecomment-90683521>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 07.04.2015 um 20:13 schrieb Frank Noe:
> That doesn't answer my question. Of course you can't cythonize python
> code, but what exactly is version-specific in our code? Are you saying
> that the cython syntax has changed from 2.1 to 2.2?

Our code is not version specific (hopefully) - The output just looked
like some serious bug in Cythons conversion routine, which I suspected
to be already fixed.

Sorry for being unclear.

**Comment by franknoe** [comment]
OK thanks


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
