### ISSUE TITLE
save_trajs test is not windows compatible

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#195]
since it contains Unix paths

https://ci.appveyor.com/project/marscher/pyemma/build/1.0.384/job/45xpxlwvw87apqnd/tests

**Comment by franknoe** [comment]
Does Windows-python assume that you write actual backslashes? That would 
be not platform independent.

Or is the problem the leading /? Can we get out of this by using 
relative instead of absolute paths.

Am 07/04/15 um 20:28 schrieb Martin K. Scherer:
>
> since it contains Unix paths
>
> https://ci.appveyor.com/project/marscher/pyemma/build/1.0.384/job/45xpxlwvw87apqnd/tests
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/195>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
can you tell me how I fix this? Plus, isn't his going to be an issue for
other test?

On 07.04.2015 20:28, Martin K. Scherer wrote:
> since it contains Unix paths
> 
> https://ci.appveyor.com/project/marscher/pyemma/build/1.0.384/job/45xpxlwvw87apqnd/tests
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/195>.
> 

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776
http://userpage.fu-berlin.de/gph82/
--

**Comment by marscher** [comment]
you can use the tempfile module to create output files which are completely platform independent

**Comment by gph82** [comment]
will do.

On 07.04.2015 20:43, Martin K. Scherer wrote:
> you can use the tempfile module to create output files which are
> completely platform independent
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/195#issuecomment-90694771>.
> 

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776
http://userpage.fu-berlin.de/gph82/
--

**Comment by franknoe** [comment]
Is there also an issue with our input test files?, e.g.

testpath=abspath(join(abspath(__file__), pardir))+'/../../util/tests/data/'
importpyemma.util.discrete_trajectoriesasdt
self.dtraj=dt.read_discrete_trajectory(testpath+'2well_traj_100K.dat')


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
fixed with ab457b7
