### ISSUE TITLE
[coordinates.api.pipeline]: Trying to pass argument to parametrize function

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#196]
In line coordinates.api.pipeline the call:
        p.parametrize(param_stride)
is attempted, which results in an "Unexpected argument error" in PyCharm because Pipeline.parametrize does not accept arguments.

I'm not sure how to fix this, but if possible avoid passing arguments into parametrize.

**Comment by marscher** [comment]
I think @fabian-paul added this, because stride is a runtime variable and not an attribute of a Transformer. Where do we pass this information, if we want to parameterize with a stride?

**Comment by franknoe** [comment]
Well in the branch I have tested, there was no such Argument in 
parametrize() (which is why this error showed up). Has this changed now 
after a merge?

Since the API access to this option is through
     coordinates.api.pipeline()
I suggest to pass a param_stride to the constructor of the Pipeline, 
store it there and use it later. You don't neet to pass it to 
parametrize() (or estimate())


Am 08/04/15 um 15:58 schrieb Martin K. Scherer:
>
> I think @fabian-paul <https://github.com/fabian-paul> added this, 
> because stride is a runtime variable and not an attribute of a 
> Transformer. Where do we pass this information, if we want to 
> parameterize with a stride?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/196#issuecomment-90925086>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 08.04.2015 um 19:38 schrieb Frank Noe:
> Well in the branch I have tested, there was no such Argument in
> parametrize() (which is why this error showed up). Has this changed now
> after a merge?
The merge introduced stridden access:

https://github.com/markovmodel/PyEMMA/blob/dev_release_1.2/pyemma/coordinates/transform/transformer.py#L179

So either PyCharm has cached something or you are not up to date on this 
branch (but you stated, you updated after the merge).

I think the philosophy of not making the stride parameter an attribute 
is the same like having a lag parameter in _next_chunk. It provides more 
flexibility and is less error prone than having this statically for each 
instance.

**Comment by franknoe** [comment]
At the moment this is not a big deal, but that means we can't have a 
unique interface for estimators.

Am 08/04/15 um 21:01 schrieb Martin K. Scherer:
> Am 08.04.2015 um 19:38 schrieb Frank Noe:
> > Well in the branch I have tested, there was no such Argument in
> > parametrize() (which is why this error showed up). Has this changed now
> > after a merge?
> The merge introduced stridden access:
>
> https://github.com/markovmodel/PyEMMA/blob/dev_release_1.2/pyemma/coordinates/transform/transformer.py#L179
>
> So either PyCharm has cached something or you are not up to date on this
> branch (but you stated, you updated after the merge).
>
> I think the philosophy of not making the stride parameter an attribute
> is the same like having a lag parameter in _next_chunk. It provides more
> flexibility and is less error prone than having this statically for each
> instance.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/196#issuecomment-91005213>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Why not? Stride is an optional argument. If it is not given the callee 
does not have to care.

**Comment by franknoe** [comment]
I've thought about it some more, and I'm really convinced it should not 
be in parametrize.

This option should be set only once in the pipeline and not be changed 
afterwards. Having it in parametrize allows to use different strides 
after e.g. adding a stage and reparametrizing the pipeline. But leads to 
an ill-defined state, because the convention is that the entire pipeline 
is parametrized at the given stride, while in this case the old stages 
will be parametrized at the old stride, which leads to a different 
result than if you add everything at the beginning and run with the new 
stride.

For the same reason I think there is no danger in setting this parameter 
in the constructor. It is set once and used once, but never changed. 
What could go wrong?

This is different from the stride option in get_output, where it is no 
problem to use arbitrary strides every time because that doesn't affect 
the state of the object.


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
BTW - were we talking about two different things? I was talking about the pipeline that (still) does not seem to have a parameter. Maybe you were referring to the Transformer. The Transformer parametrize / estimate function is part of this discussion: #204

**Comment by franknoe** [comment]
I've just checked: this is still an issue.

coordinates.api, l. 286 calls:
```
    p.parametrize(param_stride)
```

But the pipeline does not have a any parameter there. In coordinates.pipelines, l 283+, we have
python```
    p = _Pipeline(stages)
    # TODO: store param_stride if we don't run the pipeline right now
    if run:
        p.parametrize(param_stride)
    return p
```

Suggested fix:
1. In Pipeline constructor, add the param_stride option and save it.
2. In coordinates.api, l. 283, pass param_stride to the constructor of Pipeline
3. Remove param_stride from coordinates.api. l 286
4. In coordinates.pipelines, l. 110 or before set param_stride in the transformers.

I really hope this concludes this discussion.

I guess the observation above also means the pipeline has not been tested yet - please do.

**Comment by marscher** [comment]
Indeed I thought you were talking about Transformer. Your supposed fix
is easy and should be done like that.

**Comment by franknoe** [comment]
Thanks.

**Comment by marscher** [comment]
how is doing this now?

**Comment by franknoe** [comment]
I can do it in a minute.

**Comment by franknoe** [comment]
Fixed in PR kmeans_quick_fix
