### ISSUE TITLE
Complete coordinates.api.input by adding memory options

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#197]
coordinates.api.input(...):

There are use-case for pipelines if coordinates are in memory. If I have, e.g. Cartesian coordinates in memory, but want to transform them to distances to do TICA etc, the data size will expand a lot. In this case I may need to do pipelining with chunking in order to avoid memory explosion. But with the discussed suggestion for the pipeline initialization, we don’t have the possibility to do that because files are expected. So we need more input options such as ndarrays, list of ndarrays etc. Overall this becomes too cluttered if we also allow to add pipeline stages and pipeline options. So I suggest to treat all these cases by coordinates.input(…) which is going to be a very flexible function and prepares the first stage for your pipeline.

Please implement this. I have drafted the code for input in comments. 
- Case 2 ((T, N, 3)-arrays)
- Case 3 

This is is not very urgent and not part of the 1.2 release!
The urgent part is in issue #198

**Comment by marscher** [comment]
1.2 source function can already handle this.
