### ISSUE TITLE
[coordinates.api.input]: Add load raw file option

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#198]
Replace this comment by actual code:

                # TODO: CASE 1.2: file types are raw data files
                # TODO: create raw data reader from file names

This should be done for the 1.2 release.

**Comment by marscher** [comment]
this case can very easily implemented with changes from #211

**Comment by marscher** [comment]
I asked @clonker to write a test for the api, but his PR (#206) causes very strange side effects (featurizer is broken, stridden access broken).

**Comment by clonker** [comment]
Should work fine with the above referenced PR except for the CSVReader stride and lag test.

**Comment by marscher** [comment]
done in 1.2
