### ISSUE TITLE
Add HMM package

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#203]
Started this in branch add_hmm_package

**Comment by marscher** [comment]
Now that bhmm is on PyPI we can engage this one.

**Comment by franknoe** [comment]
Thank you! I'll start this on friday.

Am 23/06/15 um 18:08 schrieb Martin K. Scherer:

> Now that bhmm is on PyPI we can engage this one.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/203#issuecomment-114558952.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
