### ISSUE TITLE
Propose to rename: parametrize -> estimate

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#204]
I have renamed compute() -> estimate() in MSM. I suggest to do the same with the transformers and pipeline, i.e.:

parametrize() -> estimate()

The advantage would be that we would have a common interface for all estimators, which would be useful for generic pipelining / chain processing.
This makes only sense of course if the current parametrize() does not have any parameters - if it does we won't have a common interface.

estimate is like any other word we have considered not perfect. It seems weird to call the process of clustering "estimate". But for most parametrizable objects it does make sense.

An alternative would be to keep a second (more fitting) name for methods where estimate is weird, and then just call estimate from there. The main purpose of this rename is to have a common interface for automatic (impl-based) processing.

**Comment by marscher** [comment]
the parametrize method is currently not public in Transformers. Do you suggest to add a new method then? I strongly vote for a common interface though. What might be also interesting for us is OSPrey (https://osprey.readthedocs.org/en/latest/index.html), since it enables users to find an optimal set of parameters for model building. If we are compatible with their interface, users can use OSPrey with Pyemma.

**Comment by franknoe** [comment]
The common interface would be at least to have a method estimate(), and that should be public (like now in EstimatedMSM). Maybe more but we don't know yet.

We don't need to be compatible with OSPrey at this stage. I'm not very happy with this approach - I can explain in some detail when I'm back.

**Comment by franknoe** [comment]
Leaving this for now. We can always add an estimate() later and call parametrize(). I need to see this in a bigger context than the current implementation.

**Comment by franknoe** [comment]
I will look into this tomorrow (together with sklearnization of our Transformers)

**Comment by franknoe** [comment]
Needs unifying concept with estimators. Closing this.
