### ISSUE TITLE
Unit test fails: Strided access to Transformer.get_output()

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#205]
Folgender Unit-Test schlägt fehl:

----------------------------------------------------------------------
ERROR: test_content_data_in_memory (__main__.TestStride)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pyemma/coordinates/tests/test_stride.py", line 84, in test_content_data_in_memory
    out_reader = reader.get_output(stride=stride)
  File "/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.py", line 527, in get_output
    trajs[itraj][t:t+chunk.shape[0],:] = chunk[:, dimensions]
ValueError: could not broadcast input array from shape (56,10) into shape (0,10)

----------------------------------------------------------------------

Habe es bisher nicht geschafft, das Problem zu lösen. Evtl. gibt es mehrere Probleme, die zusammenkommen. 

Probleme können m.E. in folgenden modulen liegen:
	pyemma/coordinates/io/feature_reader.py
	pyemma/coordinates/transform/transformer.py
Ich habe im Code TODO comments eingefügt um zu highlighten wo ein Problem liegen könnte.

Folgende Dinge sind m.E. issues oder mögliche Issues:

1) In get_output() fehlte m.E. an der mit *** markierten Stelle:
   ```
        # fetch data
        last_itraj = -1
        ***
        for itraj, chunk in self.iterator(stride=stride):
   ```
   ein 
   ```
   t = 0
   ```
   Ohne das wird die Zeit am Anfang der Trajektorie nicht initialisiert. Übrigens hab ich das nicht selbst gemerkt, sondern PyCharm hat mit darauf hingewiesen dass es nicht sicher initialisiert wird. Hab ich schon erwähnt, dass das ein nützlicher Editor ist?

2. Iterator wird nicht richtig initialisiert:
   In TransformerIterator.__init__ passiert zur Zeit kein
   ```
        transformer._reset()
   ```
   Kann ohne das sichergestellt werden, dass der Iterator am Anfang den richtigen Zustand hat? Z.B. transformer._itraj = 0? Hängt vielleicht von der Vorgeschichte ab. Ich hab ausprobiert das zu setzen - das schein den Fehler zu verändern aber nicht zu beheben. Mein Gefühl ist, dass das da rein muss, bitte abklären.

3. Die für das output-array angelegte Länge ist vielleicht falsch für stride > 1.
   Im Feature_Reader passiert bei trajectory_length mit stride-option sowas:
   ```
        return (self._lengths[itraj] - 1) // stride + 1
   ```
   verstehe ich auf Anhieb nicht. Ist das wirklich richtig?

**Comment by clonker** [comment]
I think the issue is rather the chunked mode of the DataInMemeory transformer. Instead of slicing like usual
```python
arr[::stride]
```
one there has an upper bound limit given by the chunk-size
```python
upper_bound = min(self._t + self._chunksize * stride, traj_len)
slice_x = slice(self._t, upper_bound, stride)
X = traj[slice_x]
```
which does not get respected in the length-calculation of the feature reader:
```python
(l - 1)//stride + 1
```

If one changes the chunk size to 0, the tests do not fail anymore.

**Comment by franknoe** [comment]
OK, that makes sense. Is this only an issue in DataInMemory, or also in 
FeatureReader?

BTW: I did think about the trajectory_length(stride) and it does make 
sense. Would be nice to comment this in the code, because it's not 
obvious what it does.

Am 08/04/15 um 11:08 schrieb Moritz Hoffmann:
>
> I think the issue is rather the chunked mode of the DataInMemeory 
> transformer. Instead of slicing like usual
>
> arr[::stride]
>
> one there has an upper bound limit given by the chunk-size
>
> upper_bound=  min(self._t+  self._chunksize*  stride, traj_len)
> slice_x=  slice(self._t, upper_bound, stride)
> X=  traj[slice_x]
>
> which does not get respected in the length-calculation of the feature 
> reader:
>
> (l-  1)//stride+  1
>
> If one changes the chunk size to 0, the tests do not fail anymore.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/205#issuecomment-90855235>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by clonker** [comment]
From what I can see, the chunk_size only gets used by the DataInMemory transformer.

**Comment by clonker** [comment]
This issue seems not to appear for the FeatureReader, but I am not quite sure about that.
A fix would be to change the failing line in the transformer class to
```python
shape_left = trajs[itraj][t:t + chunk.shape[0], :].shape
if shape_left[0] != 0:
    trajs[itraj][t:t+chunk.shape[0],:] = chunk[:, dimensions]
t += chunk.shape[0]
```
This however feels like avoiding the problem rather than really fixing it..

**Comment by marscher** [comment]
The reset method of Transformer is being called before the the instance of the iterator is returned. So it is ensured that all internal counters are reset. 

As far as I remember this test did not fail on Fabians feature branch, so I suspect myself to not having merged this correctly. Will have a deeper look.

**Comment by marscher** [comment]
the test worked on Fabians branch before merging.

**Comment by marscher** [comment]
The get_output method of Transformer used _next_chunk of DataInMemory in the failing test. The data access is now fixed.
