### ISSUE TITLE
msm.analysis and msm.analysis.sparse: Decompositions should treat special cases.

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#208]
Two cases with sparse matrix decompositions have come up that should be dealt with in msm.analysis and msm.analysis.sparse:
1. If a 2x2 matrix is given as sparse matrix, the sparse decomposition cannot be applied. E.g.:
 ``` python
   P = np.array([[0.9,0.1],[0.1,0.9]])
   Psparse = scipy.sparse.csr_matrix(P)
   msmana.rdl_decomposition(Psparse, k=1)
```
doesn't converge. This should be handled in msm.analysis.rdl_decomposition: If a 2x2 matrix is passed or if too many eigenvalues are asked for such that the sparse decomposition cannot be applied, convert to a dense matrix and use dense decomposition. This applies to all decompositions (rdl, left, right, eigenvalues).

2. If k > P.shape[0], a warning should be raised and as many eigenvalues as demanded should be returned. This should be handled in the msm.analysis.sparse routines because k is sparse-specific.

**Comment by marscher** [comment]
this is an issue in msmtools not pyemma.

**Comment by marscher** [comment]
https://github.com/markovmodel/msmtools/issues/105
