### ISSUE TITLE
kick msm.ui.TrajectoryViewer?

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#212]
File "C:\projects\pyemma\pyemma\msm\ui\viewer.py", line 2, in <module>
    from mdtraj.html import TrajectoryView, enable_notebook
ImportError: cannot import name TrajectoryView

It most probably does not work (It has also issues with ipython3) and I'm not sure if we want to support it.

**Comment by franknoe** [comment]
Yes, remove it at least for now. We have to discuss how to handle these 
things in the future, but I would probably go for supporting external 
viewers (VMD etc)

Am 09/04/15 um 18:58 schrieb Martin K. Scherer:
>
> File "C:\projects\pyemma\pyemma\msm\ui\viewer.py", line 2, in
> from mdtraj.html import TrajectoryView, enable_notebook
> ImportError: cannot import name TrajectoryView
>
> It most probably does not work (It has also issues with ipython3) and 
> I'm not sure if we want to support it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/212>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
