### ISSUE TITLE
[ pyemma.coordinates.input] does not recognize the following filename

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#221]
```
trajfile = ['/group/ag_cmb/scratch/gph82/work/CMB/hierarchical_TICA/MR121-GSGS-W/MR121-GSGS-W_dt10ps_traj1.oriented.2.xtc']
print type(trajfile), type(trajfile[0])
feat = coor.featurizer(topfile)
feat.add_all()
inp = coor.input(trajfile, feat)
```

will produce the following output, although trajfile is a list and its first element is a string
```
<type 'list'> <type 'str'>

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-34-dfaff7af5e27> in <module>()
      3 feat = coor.featurizer(topfile)
      4 feat.add_all()
----> 5 inp = coor.input(trajfile, feat)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/api.pyc in input(input, featurizer, topology)
    247             raise ValueError("Not all elements in the input list were of the type %s!" % suffix)
    248     else:
--> 249         raise ValueError("Input \"%s\" was no string or list of strings." % input)
    250     return reader
    251 

ValueError: Input "['/group/ag_cmb/scratch/gph82/work/CMB/hierarchical_TICA/MR121-GSGS-W/MR121-GSGS-W_dt10ps_traj1.oriented.2.xtc']" was no string or list of strings.
```

**Comment by marscher** [comment]
pyemma is a liar!

**Comment by franknoe** [comment]
I'll look into it and fix it

Am 11/04/15 um 16:04 schrieb Guillermo Pérez-Hernández:
> |trajfile = ['/group/ag_cmb/scratch/gph82/work/CMB/hierarchical_TICA/MR121-GSGS-W/MR121-GSGS-W_dt10ps_traj1.oriented.2.xtc']
> print type(trajfile), type(trajfile[0])
> feat = coor.featurizer(topfile)
> feat.add_all()
> inp = coor.input(trajfile, feat)
> |
>
> will produce the following output, although trajfile is a list and its 
> first element is a string
>
> |<type 'list'> <type 'str'>
>
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-34-dfaff7af5e27> in <module>()
>        3 feat = coor.featurizer(topfile)
>        4 feat.add_all()
> ----> 5 inp = coor.input(trajfile, feat)
>
> /home/mi/gph82/programs/PyEmma/pyemma/coordinates/api.pyc in input(input, featurizer, topology)
>      247             raise ValueError("Not all elements in the input list were of the type %s!" % suffix)
>      248     else:
> --> 249         raise ValueError("Input \"%s\" was no string or list of strings." % input)
>      250     return reader
>      251
>
> ValueError: Input "['/group/ag_cmb/scratch/gph82/work/CMB/hierarchical_TICA/MR121-GSGS-W/MR121-GSGS-W_dt10ps_traj1.oriented.2.xtc']" was no string or list of strings.
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/221>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
I'm I missing sth?

On 04/11/2015 04:05 PM, Martin K. Scherer wrote:
> pyemma is a liar!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/221#issuecomment-91849963>.
>

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by gph82** [comment]
This also fails:
```
trajfile = '/group/ag_cmb/scratch/gph82/work/CMB/hierarchical_TICA/MR121-GSGS-W/MR121-GSGS-W_dt10ps_traj1.oriented.2.xtc'
print type(trajfile), type(trajfile[0])
feat = coor.featurizer(topfile)
feat.add_all()
inp = coor.input(trajfile, feat)
```

**Comment by franknoe** [comment]
input doesn't exist anymore (see previous comment to Toni). It's now 
called source. It shouldn't even be allowed to call input.
Have you pulled the latest dev_release_1.2 and restarted the Kernel of 
your notebook?

Am 11/04/15 um 16:15 schrieb Guillermo Pérez-Hernández:
>
> This also fails:
>
> |trajfile = '/group/ag_cmb/scratch/gph82/work/CMB/hierarchical_TICA/MR121-GSGS-W/MR121-GSGS-W_dt10ps_traj1.oriented.2.xtc'
> print type(trajfile), type(trajfile[0])
> feat = coor.featurizer(topfile)
> feat.add_all()
> inp = coor.input(trajfile, feat)
> |
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/221#issuecomment-91851501>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
did not restart...
