### ISSUE TITLE
coordinates.featurizer: add distance calculation between groups of atoms

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#226]
For example minimal residue distance.

Actually, this seems to be handled by the mdtraj.compute_contacts function, which we are already using in the contacts featurizer. This featurizer needs to be reconsidered - I was at least not aware that it gives residue-residue contacts rather than atom contacts.

**Comment by marscher** [comment]
This has been done by @gph82, right?

**Comment by gph82** [comment]
yes it has, this can be closed (I'm working on the performance issue of #448)
