### ISSUE TITLE
clustering c module enforces usage of int64 for assignment

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#229]
int32 is sufficient.

**Comment by franknoe** [comment]
This has been fixed. Some issues are not closed automatically. @marscher you submitted the fix message fixes #229 which seemed to have no effect. Any ideas?

**Comment by marscher** [comment]
I think this is because we have merged this into the dev_release_1.2.1 
branch instead of the default branch. Github assumes all development 
being linearized in this branch, so the issue would have been closed 
automatically when we merge dev_rel into dev.

**Comment by marscher** [comment]
no, it has been merged into devel. So one can not close issues by a 
comment, the "fixes #number" has to go into one of the commit messages.
