### ISSUE TITLE
[coor.featurizer.add_selection] ...are the indices really x1, y1, z1 .. etc? Following error

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#235]
```
trajfile = ['/home/mi/gph82/gph82@groupscratch/work/CMB/hierarchical_TICA/MR121-GSGS-W/MR121-GSGS-W_dt10ps_traj1.oriented.2.xtc',
            '/home/mi/gph82/gph82@groupscratch/work/CMB/hierarchical_TICA/MR121-GSGS-W/MR121-GSGS-W_dt10ps_traj2.oriented.2.xtc']
topfile = '/home/mi/gph82/gph82@groupscratch/work/CMB/hierarchical_TICA/MR121-GSGS-W/solute.oriented.pdb'

feat = coor.featurizer(topfile)
# __, myselection = TRP_and_linker_indices(topfile) just to generete some indices
print myselection.shape, type(myselection)
print myselection
feat.add_selection(myselection)
```
This is how `myselection` looks:
```
(114,) <type 'numpy.ndarray'>
[  0   1   2   3   4   5   6   7   8  99 100 101 105 106 107 108 109 110
 111 112 113 114 115 116 120 121 122 123 124 125 126 127 128 132 133 134
 135 136 137 138 139 140 144 145 146 147 148 149 150 151 152 153 154 155
 159 160 161 162 163 164 165 166 167 171 172 173 174 175 176 177 178 179
 183 184 185 186 187 188 189 190 191 192 193 194 198 199 200 201 202 203
 207 208 209 210 211 212 216 217 218 222 223 224 228 229 230 234 235 236
 237 238 239 240 241 242]
```

Now to the error:
```
inp = coor.source(trajfile, feat)
print 'trajectory length = ',inp.trajectory_length(0)
print 'number of dimension = ',inp.dimension()

ndim = 10
PCA_obj = coor.pca(inp, ndim)

trajectory length =  400001
number of dimension =  342

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-40dbf024907b> in <module>()
      4 
      5 ndim = 10
----> 6 PCA_obj = coor.pca(inp, ndim)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/api.pyc in pca(data, dim, stride)
    662     """
    663     res = _PCA(dim)
--> 664     return _param_stage(data, res, stride=stride)
    665 
    666 

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/api.pyc in _param_stage(previous_stage, this_stage, stride)
    585     this_stage.data_producer = inputstage
    586     this_stage.chunksize = inputstage.chunksize
--> 587     this_stage.parametrize(stride=stride)
    588     return this_stage
    589 

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    221                     # iterate over times within trajectory
    222                     if lag == 0:
--> 223                         X = self.data_producer._next_chunk(stride=stride)
    224                         Y = None
    225                     else:

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/feature_reader.pyc in _next_chunk(self, lag, stride)
    237                 return chunk.xyz.reshape(shape_2d)
    238             else:
--> 239                 return self.featurizer.map(chunk)
    240         else:
    241             if len(self.featurizer.active_features) == 0:

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/featurizer.pyc in map(self, traj)
    722         # only worth it, if computation time dominates memory transfers
    723         for f in self.active_features:
--> 724             feature_vec.append(f.map(traj).astype(np.float32))
    725 
    726         return np.hstack(feature_vec)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/featurizer.pyc in map(self, traj)
    137     def map(self, traj):
    138         newshape = (traj.xyz.shape[0], 3 * self.indexes.shape[0])
--> 139         return np.reshape(traj.xyz[:, self.indexes, :], newshape)
    140 
    141     def __hash__(self):

IndexError: index 99 is out of bounds for axis 1 with size 81

```

**Comment by gph82** [comment]
Just to prioritize (since everybody is very busy), I think I know how to fix this, so nobody work on this until I update (in short)

**Comment by gph82** [comment]
Indeed, it was just misreading the docstring, which I suggest to improve (suggest to re-write), and as a TODO,  that we allow for selecting each individual 3*n_atoms trajectory

**Comment by franknoe** [comment]
Da steht:

array with selected atom indexes

Finde ich relativ eindeutig.


Am 13/04/15 um 14:04 schrieb Guillermo Pérez-Hernández:
>
> Indeed, it was just misreading the docstring, which I suggest to 
> improve (suggest to re-write), and as a TODO, that we allow for 
> selecting each individual 3*n_atoms trajectory
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/235#issuecomment-92328534>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
"Adds the selected atom coordinates to the feature list" ... was ist
selected, die atome oder die coordinates?

On 13.04.2015 15:20, Frank Noe wrote:
> Da steht:
> 
> array with selected atom indexes
> 
> Finde ich relativ eindeutig.
> 
> 
> Am 13/04/15 um 14:04 schrieb Guillermo Pérez-Hernández:
>>
>> Indeed, it was just misreading the docstring, which I suggest to
>> improve (suggest to re-write), and as a TODO, that we allow for
>> selecting each individual 3*n_atoms trajectory
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/markovmodel/PyEMMA/issues/235#issuecomment-92328534>.
>>
> 
> 
> -- 
> 
> ----------------------------------------------
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> Mail: Arnimallee 6, 14195 Berlin, Germany
> ----------------------------------------------
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/235#issuecomment-92349283>.
> 

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776
http://userpage.fu-berlin.de/gph82/
--

**Comment by franknoe** [comment]
OK. The coordinates of the selected atoms.

Am 13/04/15 um 15:23 schrieb Guillermo Pérez-Hernández:
> "Adds the selected atom coordinates to the feature list" ... was ist
> selected, die atome oder die coordinates?
>
> On 13.04.2015 15:20, Frank Noe wrote:
> > Da steht:
> >
> > array with selected atom indexes
> >
> > Finde ich relativ eindeutig.
> >
> >
> > Am 13/04/15 um 14:04 schrieb Guillermo Pérez-Hernández:
> >>
> >> Indeed, it was just misreading the docstring, which I suggest to
> >> improve (suggest to re-write), and as a TODO, that we allow for
> >> selecting each individual 3*n_atoms trajectory
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> 
> <https://github.com/markovmodel/PyEMMA/issues/235#issuecomment-92328534>.
> >>
> >
> >
> > --
> >
> > ----------------------------------------------
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> >
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > Mail: Arnimallee 6, 14195 Berlin, Germany
> > ----------------------------------------------
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/markovmodel/PyEMMA/issues/235#issuecomment-92349283>.
> >
>
> -- 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> http://userpage.fu-berlin.de/gph82/
> --
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/235#issuecomment-92350073>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
