### ISSUE TITLE
Usage assign_to_centers

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#243]
wouldn't if be better to return the discrete trajectories from assign_to_centers rather than the pipeline stage? 
What's the usecase for having a pipeline stage with fixed centers? Usually a pipeline is required when the estimation needs to be streamed, but for the fixed-centers Assignment there's nothing to be estimated.

**Comment by marscher** [comment]
you want to assign your terrabytes of trajectories to previously calculated centers?

**Comment by franknoe** [comment]
Nono, I am talking about the output mode. You could still feed a 
transformer or pipeline stage into coor.assign_to_centers

Am 13/04/15 um 21:44 schrieb Martin K. Scherer:
>
> you want to assign your terrabytes of trajectories to previously 
> calculated centers?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92474903>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
then you're right, we should return dtrajs. It is more convenient. I can do it.

**Comment by gph82** [comment]
Hi, shall I wait until you do this for testing ?

On 04/13/2015 09:47 PM, Martin K. Scherer wrote:
> then you're right, we should return dtrajs. It is more convenient. I can do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92475645>.
>

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by franknoe** [comment]
Guille, you can go ahead with the testing because it is merged.

Am 13/04/15 um 21:49 schrieb Guillermo Pérez-Hernández:
> Hi, shall I wait until you do this for testing ?
>
> On 04/13/2015 09:47 PM, Martin K. Scherer wrote:
> > then you're right, we should return dtrajs. It is more convenient. I 
> can do it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92475645>.
> >
>
> -- 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92476073>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Its actually a minor change. Do you make heavy usage from this?

**Comment by gph82** [comment]
ok

On 04/13/2015 09:50 PM, Frank Noe wrote:
> Guille, you can go ahead with the testing because it is merged.
>
> Am 13/04/15 um 21:49 schrieb Guillermo Pérez-Hernández:
>  > Hi, shall I wait until you do this for testing ?
>  >
>  > On 04/13/2015 09:47 PM, Martin K. Scherer wrote:
>  > > then you're right, we should return dtrajs. It is more convenient. I
>  > can do it.
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > >
>  > <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92475645>.
>  > >
>  >
>  > --
>  > Dr. Guillermo Pérez-Hernández
>  > Freie Universität Berlin
>  > Institute for Mathematics
>  > Arnimallee 6
>  > D-14195 Berlin
>  > tel 0049 30 838 75776
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  > <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92476073>.
>  >
>
>
> --
>
> ----------------------------------------------
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
>
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> Mail: Arnimallee 6, 14195 Berlin, Germany
> ----------------------------------------------
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92476258>.
>

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by gph82** [comment]
define heavy ;)

I don't know, but it's definetely not unsual to want to "re-use"  clustercenters 
with other data
different from the ones one used to parametrize them.

But I can wait. Gonna have dinner now, i'll look into it later

On 04/13/2015 09:50 PM, Martin K. Scherer wrote:
> Its actually a minor change. Do you make heavy usage from this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92476425>.
>

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by marscher** [comment]
I want to introduce a flag return_dtrajs=True in the api function. So it
is possible to get the object and access the dtrajs yourself.

**Comment by franknoe** [comment]
That works already. The difference is that now you do:

A = assign(data, centers)
    or
A = assign(source, centers)

and then A.dtrajs

and instead after the change you will be able to do

dtrajs = assign(data, centers)

directly.

Am 13/04/15 um 21:54 schrieb Guillermo Pérez-Hernández:
> define heavy ;)
>
> I don't know, but it's definetely not unsual to want to "re-use" 
> clustercenters
> with other data
> different from the ones one used to parametrize them.
>
> But I can wait. Gonna have dinner now, i'll look into it later
>
> On 04/13/2015 09:50 PM, Martin K. Scherer wrote:
> > Its actually a minor change. Do you make heavy usage from this?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92476425>.
> >
>
> -- 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92478916>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
OK

Am 13/04/15 um 21:55 schrieb Martin K. Scherer:
> I want to introduce a flag return_dtrajs=True in the api function. So it
> is possible to get the object and access the dtrajs yourself.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92479229>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
see #244

**Comment by gph82** [comment]
okay, here we go

On 04/13/2015 10:06 PM, Martin K. Scherer wrote:
> Closed #243 <https://github.com/markovmodel/PyEMMA/issues/243>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/243#event-280131885>.
>

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by gph82** [comment]
Do we want assign_centers to vi visible at the api level? coor.api.assign_centers *and* coor.api.assign_to_centers?

**Comment by franknoe** [comment]
I believe we can remove assign_centers because they were not in the last 
release.

Am 13/04/15 um 23:37 schrieb Guillermo Pérez-Hernández:
>
> Do we want assign_centers to vi visible at the api level? 
> coor.api.assign_centers /and/ coor.api.assign_to_centers?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92508569>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
How's it look? 
![voronoi](https://cloud.githubusercontent.com/assets/7518004/7126344/abe660f2-e238-11e4-802d-a93d9959799c.png)

**Comment by franknoe** [comment]
Looks good. Thanks!

Am 13/04/15 um 23:56 schrieb Guillermo Pérez-Hernández:
>
> How's it look?
> voronoi 
> <https://cloud.githubusercontent.com/assets/7518004/7126344/abe660f2-e238-11e4-802d-a93d9959799c.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92512082>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
Beautified:
![voronoi](https://cloud.githubusercontent.com/assets/7518004/7126422/5145c5d8-e239-11e4-8209-82d716b193bc.png)

**Comment by franknoe** [comment]
Beautiful.

Am 14/04/15 um 00:00 schrieb Guillermo Pérez-Hernández:
>
> Beautified:
> voronoi 
> <https://cloud.githubusercontent.com/assets/7518004/7126422/5145c5d8-e239-11e4-8209-82d716b193bc.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/243#issuecomment-92512917>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
