### ISSUE TITLE
pyemma.__version__  returns "unknown" for pyEMMA-1.2-py2.7-linux-x86_64.egg/ 

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#248]
installed with conda

**Comment by marscher** [comment]
found the issue. Expect updated conda packages soon

**Comment by franknoe** [comment]
thanks. I have pushed two minor bugfixes in devel. Will they be included?

Am 15/04/15 um 11:56 schrieb Martin K. Scherer:

> found the issue. Expect updated conda packages soon
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/248#issuecomment-93295340.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Unfortunately pypi has recently forbidden to edit already released files. So we could either release 1.2.1 or postpone these changes for a further release.

**Comment by franknoe** [comment]
Done by @marscher
