### ISSUE TITLE
left eigenvectors...rows or columns?

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#249]
Hi, I believe we discussed this issue yesterday. 

I brought it up because I remembered that left eigenvectors could be returned either as rows or columns depending on how they were computed. Shouldn't we unify this?

```
T is of class  <class 'pyemma.msm.ui.msm.MSM'>
T.transition_matrix
[[ 0.999  0.001  0.     0.   ]
 [ 0.002  0.995  0.003  0.   ]
 [ 0.     0.001  0.997  0.002]
 [ 0.001  0.001  0.5    0.498]]

T.eigenvectors_left()
[[  3.35309618e-01   1.66666667e-01   4.96047431e-01   1.97628458e-03]
 [ -8.24131911e-01  -1.82882024e-13   8.20855019e-01   3.27689235e-03]
 [  3.52341480e-01  -8.81917104e-01   5.27448814e-01   2.12680974e-03]
 [  1.98021364e-03  -2.04743344e-15   9.94059375e-01  -9.96039589e-01]]

pyemma.msm.analysis.eigenvectors(T.transition_matrix, right = False)
[[  5.39506188e-01  -7.08511154e-01   3.24338885e-01   1.40718672e-03]
 [  2.68163194e-01  -1.57148555e-13  -8.11826102e-01  -8.53499247e-16]
 [  7.98129979e-01   7.05693990e-01   4.85529437e-01   7.06402138e-01]
 [  3.17980071e-03   2.81716404e-03   1.95777999e-03  -7.07809324e-01]]
```

I've specifically avoided  any normalization so that we also realise that they're being returned with different norms. The graph shows that the first row of the first matrix is actually the first column of the second matrix times a constant
![rows-vs-columns](https://cloud.githubusercontent.com/assets/7518004/7149283/d58e0058-e30b-11e4-9f53-67c03c47aa53.jpg)

**Comment by franknoe** [comment]
Yes, they should always be returned as row vectors, because we return an 
eigenvector matrix. And the left eigenvector problem is defined as

L P = D L

or for a single Eigenvector it reads

l_i P = l_i d_i

where l_i must be a row vector and d_i is an Eigenvalue. The second 
equation makes clear why a left eigenvector cannot be a column.

So I guess the function

|pyemma.msm.analysis.eigenvectors|

should return the transpose.

Am 15/04/15 um 01:08 schrieb Guillermo Pérez-Hernández:

> Hi, I believe we discussed this issue yesterday.
> 
> I brought it up because I remembered that left eigenvectors could be 
> returned either as rows or columns depending on how they were 
> computed. Shouldn't we unify this?
> 
> |T is of class  <class 'pyemma.msm.ui.msm.MSM'>
> T.transition_matrix
> [[ 0.999  0.001  0.     0.   ]
>   [ 0.002  0.995  0.003  0.   ]
>   [ 0.     0.001  0.997  0.002]
>   [ 0.001  0.001  0.5    0.498]]
> 
> T.eigenvectors_left()
> [[  3.35309618e-01   1.66666667e-01   4.96047431e-01   1.97628458e-03]
>   [ -8.24131911e-01  -1.82882024e-13   8.20855019e-01   3.27689235e-03]
>   [  3.52341480e-01  -8.81917104e-01   5.27448814e-01   2.12680974e-03]
>   [  1.98021364e-03  -2.04743344e-15   9.94059375e-01  -9.96039589e-01]]
> 
> pyemma.msm.analysis.eigenvectors(T.transition_matrix, right = False)
> [[  5.39506188e-01  -7.08511154e-01   3.24338885e-01   1.40718672e-03]
>   [  2.68163194e-01  -1.57148555e-13  -8.11826102e-01  -8.53499247e-16]
>   [  7.98129979e-01   7.05693990e-01   4.85529437e-01   7.06402138e-01]
>   [  3.17980071e-03   2.81716404e-03   1.95777999e-03  -7.07809324e-01]]
> |
> 
> I've specifically avoided any normalization so that we also realise 
> that they're being returned with different norms. The graph shows that 
> the first row of the first matrix is actually the first column of the 
> second times a constant
> rows-vs-columns 
> https://cloud.githubusercontent.com/assets/7518004/7149283/d58e0058-e30b-11e4-9f53-67c03c47aa53.jpg
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/249.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
