### ISSUE TITLE
save_trajs doesn't work with msm.sample_by_distribution()

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#250]
save_trajs explicitly tests for a list:
    # Make sure indexes is a list
    if not isinstance(indexes, list):
        indexes = [indexes]
But the output of msm.sample_by_distribution() is not a list but a 1D array of 2D arrays. Therefore save_trajs packages the result in another list, and the subsequent check
        assert i_indexes.ndim == 2
fails because now the object i_indexes is one-dimensional. 

Of course we can make it work by putting in a list, but the error above is really uninterpretable because save_trajs has created the problem itself and the user knows nothing about it.

Checks and reformatting like that be done in a general way in util.types

**Comment by franknoe** [comment]
fixed

**Comment by gph82** [comment]
I thought we had agreed that series (of any sort) would always be lists
of arrays, no matter what.

If some functions return ndarray objects and others return lists with
one element (which is an ndarray)...

On 15.04.2015 01:27, Frank Noe wrote:

> because save_trajs has created the problem itself

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by franknoe** [comment]
I don't think I have subscribed to this, anyway it isn't necessary to do 
that and it is almost always unsafe in python to do explicit type 
testing of the sort
     isinstance(obj, type)
because it explicitly tests if the classes are identical, rather than 
the functionalities. Even if I create a subclass to list this will fail.

Am 15/04/15 um 11:15 schrieb Guillermo Pérez-Hernández:

> I thought we had agreed that series (of any sort) would always be lists
> of arrays, no matter what.
> 
> If some functions return ndarray objects and others return lists with
> one element (which is an ndarray)...
> 
> On 15.04.2015 01:27, Frank Noe wrote:
> 
> > because save_trajs has created the problem itself
> 
> ## 
> 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> 
> ## http://userpage.fu-berlin.de/gph82/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/250#issuecomment-93277337.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
