### ISSUE TITLE
consider using watson to synchronize TODO/FIXME tags with Github issues

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#262]
see the magic here:

http://goosecode.com/watson/

I think this would improve fixing stuff faster, since at least myself is not aware, there exists some issues in the code, if they are not open issues on Github.

**Comment by franknoe** [comment]
Looks great! Does it work for python?

We have to be careful not to overload the issues list though. Already 
now using milestones is quite important for being able to sort through 
issues. When suddenly all TODOs become issues, we may end up hunt 
needles in haystacks.
Same comment for branches. Would this create an issue for every TODO in 
every branch? I'm not sure if that's desirable, unless we could easily 
select by branch.

Am 16/04/15 um 20:23 schrieb Martin K. Scherer:

> see the magic here:
> 
> http://goosecode.com/watson/
> 
> I think this would improve fixing stuff faster, since at least myself 
> is not aware, there exists some issues in the code, if they are not 
> open issues on Github.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/262.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I think every todo will become an issue. But it should also be possible
to add a certain label to easily filter these. Of course it is not
desirable to track this for every branch. I will test it on a dummy repo
to check how good it is in practice.

**Comment by franknoe** [comment]
OK, thanks for pointing it out!

Am 16/04/15 um 20:32 schrieb Martin K. Scherer:

> I think every todo will become an issue. But it should also be possible
> to add a certain label to easily filter these. Of course it is not
> desirable to track this for every branch. I will test it on a dummy repo
> to check how good it is in practice.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/262#issuecomment-93809542.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
