### ISSUE TITLE
update changelog for 1.2

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#266]
please document user relevant changes.

**Comment by marscher** [comment]
and include changelog in sphinx doc

**Comment by franknoe** [comment]
I'm doing that now. Just for clarification: does it make sense to list 
individual features or do that rather "coarse"? We have major changes 
and new features in the coordinates and msm packages. If want to 
explicitly list them all it will be very long.

Am 19/04/15 um 21:25 schrieb Martin K. Scherer:

> please document user relevant changes.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/266.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I think the most relevant changes in sense of end-user experience should
be listed here. Every new single feature would probably be to verbose.

**Comment by franknoe** [comment]
Done, and directly pushed this minor change to devel
