### ISSUE TITLE
Doc question

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#269]
Which one is is the preferred way of documenting this?

```
Returns
-------
tica : a :class:`TICA <pyemma.coordinates.transform.TICA>` transformation object.
    Can be used to obtain the TICA eigenvalues and eigenvectors, and to
    perform a projection of input data to the dominant TICA eigenvectors.
```

Or:
    Returns
    -------
    obj : a :class:`PCA <pyemma.coordinates.transform.PCA>` transformation object

**Comment by marscher** [comment]
I would prefer to make the important information (which properties might
be of interest) to go up in the header or the notes section.

**Comment by trendelkampschroer** [comment]
The first way is (almost) the way to go, see also

https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

section 4.

According to this it should be

## Returns

tica : :class:`TICA <pyemma.coordinates.transform.TICA>` object
    Object for time-lagged independent component (TICA) analysis.
    TICA eigenvalues and eigenvectors, and the projection of input data to the dominant TICA  
    eigenvectors can be obtained via `tica`

 Or similar...

**Comment by ppxasjsm** [comment]
I am just asking because basically you have both versions in the API doc at the minute. I will stick to he numpy doc info then

**Comment by trendelkampschroer** [comment]
Thanks. I will put a section on preparing docstrings into the developers guide asap.

**Comment by ppxasjsm** [comment]
great!

**Comment by trendelkampschroer** [comment]
The link is already in the doc. Thanks Martin. 

It seems like not all the docstrings do currently  adhere to this standard, 'tat, tat,...' 

Thanks for pointing this out.

**Comment by ppxasjsm** [comment]
I am just going though all the docs now...

**Comment by ppxasjsm** [comment]
I get empty docs and lots of warnings...any ideas why? 
I am just running

```
make all
```

Is there anything I need to install, take care of in order to build the doc to check that my changes are ok?

**Comment by marscher** [comment]
pip install -r build-doc-requirements.txt
cd doc
make
$browser doc/build/html/index.html

I guess you opened up this issue, since it is not documented how to do it?
