### ISSUE TITLE
[pyemma.msm.generation.api.MarkovChainSampler] trajectories with the stop option

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#273]
My goal is to get a distribution of waiting times in state 0 before going to state 1

```
print mymat.A1
TTsampler = pyemma.msm.generation.api.MarkovChainSampler(mymat.A1)
TTsampler.trajectories(5, 10, start=0, stop=[1])

[[ 0.9  0.1]
 [ 0.5  0.5]]

[array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])]
```

I assume that each trajectory is being pre-allocated to a 1-D array of length 10 in the background, s.t. even if it stopped when the state 1 appeared, the rest of the array is shown as zeros. 

I find this behavior is a bit confusing:
- On has to operate further on the array to see how long it actually took get there, i.e., the length of the array and the length of the trajectory are different.  
- With zero almost always being a state in an MSM, giving the rest of the trajectory as zeroes (and not NaNs) can be dangerously misleading, because it will not give an error downstream.
- Lists of arrays are clearer and less prone to error, besides being closer to the use-case of input (MD)-trajectories of arbitrary lengths. Although having N trajectories of length L as NxL arrays is very practical for algebra, lists are more robust and always possible. 

I know there's pyemma.msm.analysis.mfpt for mean first passage times, but it does not return the array of waiting times, just the mean. Perhaps we could implement that?

**Comment by franknoe** [comment]
sorry, this is a bug. I'll do it.

Am 27/04/15 um 12:31 schrieb Guillermo Pérez-Hernández:

> My goal is to get a distribution of waiting times in state 0 before 
> going to state 1
> 
> |print mymat.A1
> TTsampler = pyemma.msm.generation.api.MarkovChainSampler(mymat.A1)
> TTsampler.trajectories(5, 10, start=0, stop=[1])
> 
> [[ 0.9  0.1]
>   [ 0.5  0.5]]
> 
> [array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
>   array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0]),
>   array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
>   array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0]),
>   array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])]
> |
> 
> I assume that each trajectory is being pre-allocated to a 1-D array of 
> length 10 in the background, s.t. even if it stopped when the state 1 
> appeared, the rest of the array is shown as zeros.
> 
> I find this behavior is a bit confusing:
> - On has to operate further on the array to see how long it actually
>   took get there, i.e., the length of the array and the length of
>   the trajectory are different.
> - With zero almost always being a state in an MSM, giving the rest
>   of the trajectory as zeroes (and not NaNs) can be dangerously
>   misleading, because it will not give an error downstream.
> - Lists of arrays are clearer and less prone to error, besides being
>   closer to the use-case of input (MD)-trajectories of arbitrary
>   lengths. Although having N trajectories of length L as NxL arrays
>   is very practical for algebra, lists are more robust and always
>   possible.
> 
> I know there's pyemma.msm.analysis.mfpt for mean first passage times, 
> but it does not return the array of waiting times, just the mean. 
> Perhaps we could implement that?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/273.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Thanks! 

BTW, I had not noticed that the output was already a list, so scratch my 3rd point!

**Comment by franknoe** [comment]
Fixed. BTW, you can call it like this:

``` python
    import pyemma.msm.generation as msmgen
    trajs = msmgen.generate_trajs(P, 10, 10, start=0, stop=[1])
```
