### ISSUE TITLE
[doc_fixes] References and links

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#274]
![screenshot from 2015-04-27 15 29 09](https://cloud.githubusercontent.com/assets/3668316/7349578/13fddfe4-ecf2-11e4-81c3-8cce7d582d52.png)

The hyperlinking and display is cleraly off, but I have no idea why.

**Comment by marscher** [comment]
I think the problem occurs because we re-use labels for references all
the time. Sphinx reports several warnings. Eg:

docstring of pyemma.msm.ui.EstimatedMSM.pcca:1: ERROR: Duplicate target
name, cannot be used as a unique reference: "1".

**Comment by marscher** [comment]
@ppxasjsm which functions docstring did you use to generate the screenshot?

**Comment by ppxasjsm** [comment]
This is from TICA. Also in the MSM package the references  are all over the place. Maybe it would be good to number them from [1]-[n] and not start with [1] again for each function? you can use bibtex with sphinx apparently, but I haven't looked into too much detail there.

**Comment by franknoe** [comment]
Is it possible to assign something else than numbers in the docstrings? 
It would be very annoying if we had to manage the reference enumeration 
system ourselves.

Am 28/04/15 um 20:55 schrieb ppxasjsm:

> This is from TICA. Also in the MSM package the references are all over 
> the place. Maybe it would be good to number them from [1]-[n] and not 
> start with [1] again for each function? you can use bibtex with sphinx 
> apparently, but I haven't looked into too much detail there.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/274#issuecomment-97169792.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I've used [author_year] and it worked (sphinx did not complain anymore). 
So I would prefer using that style.

**Comment by franknoe** [comment]
Is that then translated into a number in the link and the enumeration 
symbol, or does it show the string you use within [...]?

Am 29/04/15 um 00:02 schrieb Martin K. Scherer:

> I've used [author_year] and it worked (sphinx did not complain anymore).
> So I would prefer using that style.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/274#issuecomment-97239265.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 29.04.2015 um 00:04 schrieb Frank Noe:

> Is that then translated into a number in the link and the enumeration
> symbol, or does it show the string you use within [...]?
> good question, I do not know currently.

**Comment by ppxasjsm** [comment]
I hope you are making those changes to the doc_fixes branch? I can run it tomorrow to see what happens.

**Comment by marscher** [comment]
If we change the reference labels to author_year style, they also show up with whole label name in the text. I think this undesired. The sphinx-bibtex extension would solve this problem, but it also has some restrictions on where a bibliography can be contained. Since the output is correct and it only causes some (ugly) error messages in sphinx, I suggest to close this now.

**Comment by franknoe** [comment]
OK.

Just a related mini-issue: In the coordinates.tica docstring this sentence:

It was shown in [3] 
http://www.pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.tica.html#id8 
that when applied to molecular dynamics data, TICA is an approximation 
to the eigenvalues and eigenvectors of the true underlying dynamics.

Should instead reference [1]. (I guess the order has been changed somehow)

Am 27/05/15 um 19:10 schrieb Martin K. Scherer:

> If we change the reference labels to author_year style, they also show 
> up with whole label name in the text. I think this undesired. The 
> sphinx-bibtex extension would solve this problem, but it also has some 
> restrictions on where a bibliography can be contained. Since the 
> output is correct and it only causes some (ugly) error messages in 
> sphinx, I suggest to close this now.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/274#issuecomment-106000310.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Yes, I had merge conflicts due to the doc_fixes branch all over and since I had to resolve manully all the time it might had happened that I switched this. Thanks for pointing out.

**Comment by marscher** [comment]
fixed in 2aa8a0c
