### ISSUE TITLE
FeatureReader should (optionally) create an index cache (trajectory lengths) 

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#279]
This would avoid running over all trajs initially.
For dimensions we would only need to read the first frame. The index could be created as a hidden file (eg. .traj_x.index.txt) and it could be automatically checked if it exists. We should add a timestamp, when this lengths information has been generated to avoid the case of concatenated trajs being reported as the old cached length.

**Comment by marscher** [comment]
@franknoe Guille told me yesterday that you've figured out how to determine lengths in mdtraj without running over the whole file. I'm very curious if that is really possible :+1:

**Comment by franknoe** [comment]
I guess it depends on the file type if you read over it or not. I don't 
know what mdtraj does internally.

But the idea is this:

``` python
     traj = mdtraj.open(trajfile, topfile)
     print len(traj)
```

Am 30/04/15 um 16:13 schrieb Martin K. Scherer:

> @franknoe https://github.com/franknoe Guille told me yesterday that 
> you've figured out how to determine lengths in mdtraj without running 
> over the whole file. I'm very curious if that is really possible :+1:
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/279#issuecomment-97811709.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
