### ISSUE TITLE
enable doctests on travis

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#292]
Since we have not included them yet, we have unfortunately a lot of failures.

**Comment by fabian-paul** [comment]
Can you please post a link, so that we can see the error messages?

**Comment by marscher** [comment]
I suggest creating a branch, on which we enable the doctests so we will 
see the failures on travis.

**Comment by marscher** [comment]
done on #295

**Comment by marscher** [comment]
doctests are working on devel right now. But rebasing will cause a lot of merge conflicts I guess. I'll try to cherry-pick the needed commits.

**Comment by franknoe** [comment]
I really wanna avoid having to rebase dev_release_1.3 again on devel. 
That was really nontrivial. Can we just cherry-pick all devel commits 
that happened after the rebase into dev_release_1.3?

Am 27/07/15 um 20:11 schrieb Martin K. Scherer:

> doctests are working on devel right now. But rebasing will cause a lot 
> of merge conflicts I guess. I'll try to cherry-pick the needed commits.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/292#issuecomment-125291879.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Cherry-picking a range of commits will also cause problems, because we do not want to overwrite changes made on dev_release_1.3. But I think it we only need to pick a few ones to make this work.

**Comment by marscher** [comment]
done, there are now 8 failures left, which are due to numerical abbreviations in the results.

**Comment by marscher** [comment]
It should be avoided to test against results given by a Sampled*MSM,
since these are varying a lot.

**Comment by marscher** [comment]
only 3 left... This is the command to run the doctests:
nosetests --with-doctest
--doctest-options="+NORMALIZE_WHITESPACE,+ELLIPSIS" --exclude="._test._"
pyemma -vv --failed 2>&1|less

**Comment by marscher** [comment]
done
