### ISSUE TITLE
Examples for featurizing + coordinate loading and sourcing

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#294]
Assemble a notebook with examples for featurizing (selected coordinates, angles, distances) and load/source. Put this example into pyemma docs (not msmdocs because there's not associated theory), and add a link to the docs of the corresponding function.

I suggest that @marscher and @cwehmeyer or @fabian-paul  and @marscher do this. (When I suggest pairs like that my idea is that one person could write it and the other person review/correct it, but you can do it differently of course)

**Comment by fabian-paul** [comment]
I have started writing the tutorial, it's on the group home: /group/ag_cmb/scratch/fab/featurizer_tutorial

**Comment by franknoe** [comment]
Thanks, here some preliminary comments:

## General
- It took over 1 hour to download the data. I'm sure you can massively 
  downsample all data without loosing much. Furthermore we should select a 
  few data sets and keep using them for all example notebook files, such 
  that the user can download a compact package.
- Markdown text is preferred to explanations over code comments
- Some of the comments below suggest changes or improvements in pyEMMA's 
  API - In this case make these changes or turn them into an issue. It is 
  very good practice to iterate between developing or improving code and 
  using / illustrating it in such tutorial notebooks. Only when you take 
  the user's perspective you can make develop reasonable code.

## Alanine
- phi/psi featurizer description() output is wrong - I made an issue
- pyemma.coordinates.util.stat.hist - nobody will find a function that 
  is five levels down. This is not API. If you want to give something to 
  the user add it to the API (e.g. pyemma.plots), or else use a standard 
  plotting function.

## Trypsin-Benzamidine
- Better add a VMD-produced picture to show some structure and the 
  distances we are getting. This is very abstract
- featurizer.add_contacts command is too convoluted. Break into 2-3 
  lines. Better: We a simple function to do all pairs. E.g. the pairs() 
  function of the featurizer could have a second argument, and in that 
  case all pairs between the two selections are returned.
- contact figure is hard to read, too many similar colors. To make this 
  point only one contact would be needed
- not sure why the contacts and the distance are added to one 
  featurizer, because then you plot them separately. In order to should the
  combination of features I rather suggest to add add distances and angles 
  in the peptide example and then do something with it, such as pca.
- cartesian coordinates plot is too coarse to see anything.

## AVAVA

Not very informative RMSD because looks random. Is this exhibiting some 
sort of folding or does it have a distanct state? Then it would be more 
educative to use that state as a reference and show how the trajectory 
is close and far sometimes.

Am 08/05/15 um 17:21 schrieb fabian-paul:

> I have started writing the tutorial, it's on the group home: 
> /group/ag_cmb/scratch/fab/featurizer_tutorial
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/294#issuecomment-100271352.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ppxasjsm** [comment]
AVAVA:
It does not exhibit folding or have any particularly excitingly distinct states as far as I know. Maybe A10 would be a better example?

**Comment by franknoe** [comment]
sure, why not

Am 17/05/15 um 15:29 schrieb ppxasjsm:

> AVAVA:
> It does not exhibit folding or have any particularly excitingly 
> distinct states as far as I know. Maybe A10 would be a better example?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/294#issuecomment-102804448.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
actually good idea because we can use it as a TRAM example as well.

Am 17/05/15 um 15:29 schrieb ppxasjsm:

> AVAVA:
> It does not exhibit folding or have any particularly excitingly 
> distinct states as far as I know. Maybe A10 would be a better example?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/294#issuecomment-102804448.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
Concerning A10. Could you please send me the data (or a directory name?).
Actually I made the AVAVA example as a purely technical demontration because I can't say anything intelligent about the system.
It guess for A10 it's easier because it folds to a helix?

**Comment by ppxasjsm** [comment]
Yes it folds into a helix, which is clearly distinguishable and maybe a bit more satisfying to work with rather than some random states that don't seem to give you any particular insight into the system.
