### ISSUE TITLE
assign_to_centers fails if input is not of type float32

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#297]

**Comment by fabian-paul** [comment]
I can't reproduce the error. assign_to_centers works fine with any of data or centers having float32 or float64 format.

**Comment by marscher** [comment]
the error occured during doctesting coordinates.api forked from
dev_release_1.2.1

**Comment by franknoe** [comment]
I am not sure that branch is up to date. Do a rebase to devel.

Am 07/05/15 um 12:30 schrieb Martin K. Scherer:

> the error occured during doctesting coordinates.api forked from
> dev_release_1.2.1
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/297#issuecomment-99807658.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
I can't reproduce the error on dev_release_1.2.1 either. Can you send the code that fails? (Code in docstring?)

**Comment by marscher** [comment]
my fault.
