### ISSUE TITLE
Featurizer describe()

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#308]
Featurizer.describe() should return one string per feature, not per atom. Otherwise it's impossible to match features to the description.
Thus for the backbone torsions it should not return something like:

```
['PHI ACE 0 C 4',
 'PHI ALA 1 N 6',
 'PHI ALA 1 CA 8',
 'PHI ALA 1 C 14',
```

but a one-line description of that feature, e.g.

```
PHI 1 (ACE 0 C 4, ALA 1 N 6, ALA 1 CA 8, ALA 1 C 14)
```

It's a matter of taste what we want to write here. The purpose is e.g. to be able to find this feature in another program such as VMD, and for that reason it is useful to know which residues and atoms are involved.

**Comment by marscher** [comment]
The one line output is much more descriptive than the first. It may be more convenient if you want to parse those strings with VMD to directly support VMD selection language strings. To get those we could add a switch to the describe method and return VMD compatible selection strings, so the hassle of parsing these strings (which then should not change any more) is gone.

Currently we've separated components of single feature by dashes (eg. dihedrals) like this:

```
"DIH: %s - %s - %s - %s"
```

Shall we switch to the "Feature index (res_id, atom_id)" pattern?

**Comment by franknoe** [comment]
Hm, I haven't even though about using these descriptions as a selector, 
but I just though that this should provide a user-understandable way of 
finding out what feature #397 was, especially if we built a featurizer 
with mixed features (such as distances and angles).

I'm open for anything here, as long as it is still human readable. 
Wouldn't it be confusing if we have mdtraj selection and VMD selection 
language in the same package? Moreover we cannot do something like this 
for all features. Think of an RMSD or the cos/sin transform of an angle.

Am 18/05/15 um 17:00 schrieb Martin K. Scherer:

> The one line output is much more descriptive than the first. It may be 
> more convenient if you want to parse those strings with VMD to 
> directly support VMD selection language strings. To get those we could 
> add a switch to the describe method and return VMD compatible 
> selection strings, so the hassle of parsing these strings (which then 
> should not change any more) is gone.
> 
> Currently we've separated components of single feature by dashes (eg. 
> dihedrals) like this:
> 
> |"DIH: %s - %s - %s - %s"
> |
> 
> Shall we switch to the "Feature index (res_id, atom_id)" pattern?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/308#issuecomment-103087742.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Hi,

i think it's best if we keep the mdtraj format (when possible) and just
use an interpreter option when calling describe(visual='vmd'). I mean,
not everybody is using VMD. In time, we could then extend to other
molecular visualizers (most notably pymol). Actually, it would not
surprise me if mdtraj was already using pymol compatible strings.

Anyone knows about this?

On 18.05.2015 17:19, Frank Noe wrote:

> Hm, I haven't even though about using these descriptions as a selector,
> but I just though that this should provide a user-understandable way of
> finding out what feature #397 was, especially if we built a featurizer
> with mixed features (such as distances and angles).
> 
> I'm open for anything here, as long as it is still human readable.
> Wouldn't it be confusing if we have mdtraj selection and VMD selection
> language in the same package? Moreover we cannot do something like this
> for all features. Think of an RMSD or the cos/sin transform of an angle.
> 
> Am 18/05/15 um 17:00 schrieb Martin K. Scherer:
> 
> > The one line output is much more descriptive than the first. It may be
> > more convenient if you want to parse those strings with VMD to
> > directly support VMD selection language strings. To get those we could
> > add a switch to the describe method and return VMD compatible
> > selection strings, so the hassle of parsing these strings (which then
> > should not change any more) is gone.
> > 
> > Currently we've separated components of single feature by dashes (eg.
> > dihedrals) like this:
> > 
> > |"DIH: %s - %s - %s - %s"
> > |
> > 
> > Shall we switch to the "Feature index (res_id, atom_id)" pattern?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/308#issuecomment-103087742.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/308#issuecomment-103096064.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by marscher** [comment]
I vote against supporting multiple selection languages. But at least we can output indices, which are probably easy to handle in every selection lang.

**Comment by franknoe** [comment]
Yes

Am 19/05/15 um 15:37 schrieb Martin K. Scherer:

> I vote against supporting multiple selection languages. But at least 
> we can output indices, which are probably easy to handle in every 
> selection lang.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/308#issuecomment-103497453.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
For our selection yes, but for "describe", why not?

On 19.05.2015 15:46, Frank Noe wrote:

> Yes
> 
> Am 19/05/15 um 15:37 schrieb Martin K. Scherer:
> 
> > I vote against supporting multiple selection languages. But at least
> > we can output indices, which are probably easy to handle in every
> > selection lang.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/308#issuecomment-103497453.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/308#issuecomment-103500385.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by marscher** [comment]
also note Sebastians work here: #316
