### ISSUE TITLE
[test_save_trajs.py] was missing a '/' in the tmpdir creation...

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#311]
...so that 
    def tearDown(self):
        shutil.rmtree(self.subdir, ignore_errors=True)
was not actually tearing down anything. 

The fix:

self.subdir = tempfile.mkdtemp(suffix='save_trajs_test/')

This is not worth an entire bugfix branch + PR. @marscher , can you please patch this? Thanks

**Comment by marscher** [comment]
is this slash really necessary? Since the function only created directories, it just prepends the suffix in the name. Isn't that sufficient?

**Comment by gph82** [comment]
No, because teardown tries to remove the directory, which does not exist. What exist are files with the name
randdirrandfile.xtc instead of
randdir/randfile.xtc

rm -r randdir won't affect those. 

Run the test yourself and you'll see

## 

Sent from my phone. 
Apologies for typos, unusual tone or brevity 

-------- Original message --------

**Comment by marscher** [comment]
I see. So the prefix argument does essentially not what the docstring is
promising:

quote:

If you want files to be stored
    in a specific subfolder, simply specify the relative path in the
prefix, e.g. prefix='~/macrostates/pcca_'

So this I consider this behaviour as a bug!

**Comment by marscher** [comment]
done in 9405e71b18ccf3de98d494260f982f874681755a

**Comment by gph82** [comment]
sooo, do we close this?
