### ISSUE TITLE
[pyemma.coordinates.data.FeatureReader] dosctring for get_output says...

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#312]
Notes:
This function may be RAM intensive if stride is too large or too many dimensions are selected.

I understand what is meant, but since there's a parameter called stride, what you want to write is "stride is too low", or rephrase somehow. Otherwise it's confusing. 

I don't think one can use "stride" as a transitive verb (native speakers, please?), but everybody in the MD-community understands a sentence of the form:
"if the data is not sufficiently strided" or 
"is not sufficiently downsampled"

**Comment by marscher** [comment]
This docstring does not exist any more.
