### ISSUE TITLE
changelogs

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#318]
I'm a bit confused what should go to CHANGELOG.rst and what to CHANGELOG_dev.rst? The dev version seems outdated.

If we want to keep two separate versions of a changelog, we have to decide which criterion to apply to distinguish both.

**Comment by franknoe** [comment]
One is enough. I can't remember why there are two.

For the 1.2.1 version I really don't know what the changes are, so I 
guess you'll have to assemble them, and I can go over them before we 
release.

Am 20/05/15 um 20:05 schrieb Martin K. Scherer:

> I'm a bit confused what should go to CHANGELOG.rst and what to 
> CHANGELOG_dev.rst? The dev version seems outdated.
> 
> If we want to keep two separate versions of a changelog, we have to 
> decide which criterion to apply to distinguish both.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/318.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 20.05.2015 um 20:07 schrieb Frank Noe:

> One is enough. I can't remember why there are two.
> Agreed.
> 
> For the 1.2.1 version I really don't know what the changes are, so I
> guess you'll have to assemble them, and I can go over them before we
> release.
> I've already added some entries, which are important for users. It would
> be nice if you take a look before release. Thank you!
