### ISSUE TITLE
numpyfilereader does not close filehandles during init

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#320]

**Comment by marscher** [comment]
noticed by @gph82

**Comment by gph82** [comment]
+1
If people want to see the traceback:
http://page.mi.fu-berlin.de/gph82/too_many_filez.html

**Comment by marscher** [comment]
The current impl/doc states, that one could memory map npz files, which is not true. https://stackoverflow.com/questions/29080556/how-does-numpy-handle-mmaps-over-npz-files

If we want to support those, we have to load them into memory.

**Comment by marscher** [comment]
For a quick fix it would be easier to just drop support for npz and implement a new class in long term for this format.

**Comment by gph82** [comment]
Confirmed it works. One thing, could we also get an ETA widget? It might not be very meaningful if file-sizes vary a lot within the list of .npy files, but otherwise it would be very helpful
