### ISSUE TITLE
Docs orga for objects

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#321]
Many pyemma API functions return an object. It is currently difficult to match the function producing the object with the object itself in the docs. For example estimate_markov_model:

http://www.pythonhosted.org/pyEMMA/api/generated/pyemma.msm.estimate_markov_model.html#pyemma.msm.estimate_markov_model

In order to find out what the returned object provides I have to click on the link (and I have seen multiple times people overlooking that) to EstimatedMSM 

http://www.pythonhosted.org/pyEMMA/api/generated/pyemma.msm.ui.EstimatedMSM.html#pyemma.msm.ui.EstimatedMSM

where the constructor is again documented (it shouldn't be because we don't want to expose that to the user), and then the attributes and methods that are of interest.

Can we simply merge that information to one page? When clicking on msm.estimate_markov_model, I would like to have:
- API docs for that function (how to construct the object)
- List of Attributes
- List of Methods
- Examples, References
- Details of Attributes / Methods

The actual class name is not relevant for the user and can be a side-note (it doesn't need a separate doc page)

**Comment by marscher** [comment]
We can include the sphinx autodoc directive in the api docstring to list all members. The only refactoring we would then need is to move the description of the constructor back to ctor itself (currently it is located at class level) to avoid duplication with the api docstring.

**Comment by marscher** [comment]
Sphinx allows to hide special members in autodoc (like **init**).

**Comment by franknoe** [comment]
Yes, that's what I had in mind!

Then we can remove the class docs, i.e. "Classes" in these pages:

```
 http://www.pythonhosted.org/pyEMMA/api/index_coor.html
 http://www.pythonhosted.org/pyEMMA/api/index_msm.html
```

Am 22/05/15 um 17:47 schrieb Martin K. Scherer:

> We can include the sphinx autodoc directive in the api docstring to 
> list all members. The only refactoring we would then need is to move 
> the description of the constructor back to ctor itself (currently it 
> is located at class level) to avoid duplication with the api docstring.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/321#issuecomment-104695652.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Great, let's do it.

Am 22/05/15 um 17:48 schrieb Martin K. Scherer:

> Sphinx allows to hide special members in autodoc (like _init_).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/321#issuecomment-104695839.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
That way we also save a lot of links and see alsos.

Am 22/05/15 um 17:48 schrieb Martin K. Scherer:

> Sphinx allows to hide special members in autodoc (like _init_).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/321#issuecomment-104695839.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
I have experimented with this to see how one could include a table of contents into the generated api docs and it appears that the only solution which isn't overly hacky (like loading the html with javascript) is something along the lines of

```
.. autoclass:: pyemma.coordinates.transform.pca.PCA
        :members:
        :undoc-members:

        .. rubric:: Methods

        .. autosummary::

           ~pyemma.coordinates.transform.pca.PCA.__init__
           ~pyemma.coordinates.transform.pca.PCA.describe
           ~pyemma.coordinates.transform.pca.PCA.dimension
           ~pyemma.coordinates.transform.pca.PCA.get_output
           ~pyemma.coordinates.transform.pca.PCA.iterator
           ~pyemma.coordinates.transform.pca.PCA.map
           ~pyemma.coordinates.transform.pca.PCA.n_frames_total
           ~pyemma.coordinates.transform.pca.PCA.number_of_trajectories
           ~pyemma.coordinates.transform.pca.PCA.output_type
           ~pyemma.coordinates.transform.pca.PCA.parametrize
           ~pyemma.coordinates.transform.pca.PCA.trajectory_length
           ~pyemma.coordinates.transform.pca.PCA.trajectory_lengths

        .. rubric:: Attributes

        .. autosummary::

           ~pyemma.coordinates.transform.pca.PCA.chunksize
           ~pyemma.coordinates.transform.pca.PCA.covariance_matrix
           ~pyemma.coordinates.transform.pca.PCA.data_producer
           ~pyemma.coordinates.transform.pca.PCA.in_memory
           ~pyemma.coordinates.transform.pca.PCA.mean
```

... unless i have missed something. This is quite lengthy and almost the content of the classes' generated rst file, perhaps one could write a post processor that replaces the content? Any suggestions?

**Comment by marscher** [comment]
I think you can just use the directive autoclass in the api docstring to
get exactly this output.

**Comment by clonker** [comment]
The directive autoclass

```
.. autoclass:: pyemma.coordinates.transform.pca.PCA
```

gives an output like without a table of contents

![screenshot 2015-06-05 16 31 50](https://cloud.githubusercontent.com/assets/1685266/8008137/86fc7542-0ba0-11e5-96e6-dece37aead4e.png)

In comparison to the autosummary version above:

![screenshot 2015-06-05 16 28 05](https://cloud.githubusercontent.com/assets/1685266/8008260/51dbde9c-0ba1-11e5-8fb5-60d22d52b7a5.png)

**Comment by franknoe** [comment]
I would really vote for an automatic solution. If we have to manually 
add function/attribute names to be listed, this is destined to become 
inconsistent very soon.

Am 05/06/15 um 16:23 schrieb Moritz Hoffmann:

> I have experimented with this to see how one could include a table of 
> contents into the generated api docs and it appears that the only 
> solution which isn't overly hacky (like loading the html with 
> javascript) is something along the lines of
> 
> |.. autoclass:: pyemma.coordinates.transform.pca.PCA
>          :members:
>          :undoc-members:
> 
> ```
>      .. rubric:: Methods
> 
>      .. autosummary::
> 
>         ~pyemma.coordinates.transform.pca.PCA.__init__
>         ~pyemma.coordinates.transform.pca.PCA.describe
>         ~pyemma.coordinates.transform.pca.PCA.dimension
>         ~pyemma.coordinates.transform.pca.PCA.get_output
>         ~pyemma.coordinates.transform.pca.PCA.iterator
>         ~pyemma.coordinates.transform.pca.PCA.map
>         ~pyemma.coordinates.transform.pca.PCA.n_frames_total
>         ~pyemma.coordinates.transform.pca.PCA.number_of_trajectories
>         ~pyemma.coordinates.transform.pca.PCA.output_type
>         ~pyemma.coordinates.transform.pca.PCA.parametrize
>         ~pyemma.coordinates.transform.pca.PCA.trajectory_length
>         ~pyemma.coordinates.transform.pca.PCA.trajectory_lengths
> 
>      .. rubric:: Attributes
> 
>      .. autosummary::
> 
>         ~pyemma.coordinates.transform.pca.PCA.chunksize
>         ~pyemma.coordinates.transform.pca.PCA.covariance_matrix
>         ~pyemma.coordinates.transform.pca.PCA.data_producer
>         ~pyemma.coordinates.transform.pca.PCA.in_memory
>         ~pyemma.coordinates.transform.pca.PCA.mean
> ```
> 
> |
> |
> 
> ... unless i have missed something. This is quite lengthy and almost 
> the content of the classes' generated rst file, perhaps one could 
> write a post processor that replaces the content? Any suggestions?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/321#issuecomment-109308519.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
I have now written an extension to the auto summary directive, such that it can be called like

```
.. autoclass:: pyemma.coordinates.transform.pca.PCA
    :members:
    :undoc-members:

    .. rubric:: Methods

    .. autoautosummary:: pyemma.coordinates.transform.pca.PCA
       :methods:

    .. rubric:: Attributes

    .. autoautosummary:: pyemma.coordinates.transform.pca.PCA
        :attributes:
```

This still has some redundancy but until now i was unable to figure out how to create a "sphinx macro" that then calls autoclass with the correct parameters.

**Comment by franknoe** [comment]
cool! Can you make an example using this for example for the 
pyemma.msm.markov_model and msm.estimate_markov_model functions?

Am 11/06/15 um 12:44 schrieb Moritz Hoffmann:

> I have now written an extension to the auto summary directive, such 
> that it can be called like
> 
> |     .. autoclass:: pyemma.coordinates.transform.pca.PCA
>          :members:
>          :undoc-members:
> 
> ```
>      .. rubric:: Methods
> 
>      .. autoautosummary::
>         :methods:
> 
>         pyemma.coordinates.transform.pca.PCA
> 
>      .. rubric:: Attributes
> 
>      .. autoautosummary::
>          :attributes:
> 
>          pyemma.coordinates.transform.pca.PCA
> ```
> 
> |
> |
> 
> This still has some redundancy but until now i was unable to figure 
> out how to create a "sphinx macro" that then calls autoclass with the 
> correct parameters.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/321#issuecomment-111082814.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
I have made the examples and uploaded it into my [fork](https://github.com/clonker/PyEMMA/tree/sphinx_doc_autoautosummary). Since now the class documentation gets pulled as well, one should probably erase it or move it to __init__. The results are like the following:
[markov_model](https://www.dropbox.com/s/2xh9mkpnw9gf6o3/msmdocs.pdf?dl=0) and [estimate_markov_model](https://www.dropbox.com/s/w7inbj4zf1uckr5/msmdocs2.pdf?dl=0).

##### Docstring for markov_model

```
r"""Markov model with a given transition matrix

Returns a :class:`MSM <pyemma.msm.ui.MSM>` that contains the transition matrix
and allows to compute a large number of quantities related to Markov models.

Parameters
----------
P : ndarray(n,n)
    transition matrix
dt : str, optional, default='1 step'
    Description of the physical time corresponding to the lag. May be used by analysis algorithms such as
    plotting tools to pretty-print the axes. By default '1 step', i.e. there is no physical time unit.
    Specify by a number, whitespace and unit. Permitted units are (* is an arbitrary string):

    |  'fs',  'femtosecond*'
    |  'ps',  'picosecond*'
    |  'ns',  'nanosecond*'
    |  'us',  'microsecond*'
    |  'ms',  'millisecond*'
    |  's',   'second*'

Returns
-------
msm : A :class:`MSM <pyemma.msm.ui.msm.MSM>` object containing a transition matrix and various other MSM-related quantities.


.. autoclass:: pyemma.msm.ui.msm.MSM
    :members:
    :undoc-members:

    .. rubric:: Methods

    .. autoautosummary:: pyemma.msm.ui.msm.MSM
       :methods:

    .. rubric:: Attributes

    .. autoautosummary:: pyemma.msm.ui.msm.MSM
        :attributes:

See also
--------
MSM : A MSM object

"""
```

##### Docstring for estimate_markov_model

```
r"""Estimates a Markov model from discrete trajectories

Returns a :class:`EstimatedMSM <pyemma.msm.ui.EstimatedMSM>` that contains the estimated transition matrix
and allows to compute a large number of quantities related to Markov models.

Parameters
----------
dtrajs : list containing ndarrays(dtype=int) or ndarray(n, dtype=int)
    discrete trajectories, stored as integer ndarrays (arbitrary size)
    or a single ndarray for only one trajectory.
lag : int
    lagtime for the MSM estimation in multiples of trajectory steps
reversible : bool, optional, default = True
    If true compute reversible MSM, else non-reversible MSM
sparse : bool, optional, default = False
    If true compute count matrix, transition matrix and all derived quantities using sparse matrix algebra.
    In this case python sparse matrices will be returned by the corresponding functions instead of numpy
    arrays. This behavior is suggested for very large numbers of states (e.g. > 4000) because it is likely
    to be much more efficient.
connectivity : str, optional, default = 'largest'
    Connectivity mode. Three methods are intended (currently only 'largest' is implemented)
    'largest' : The active set is the largest reversibly connected set. All estimation will be done on this
        subset and all quantities (transition matrix, stationary distribution, etc) are only defined on this
        subset and are correspondingly smaller than the full set of states
    'all' : The active set is the full set of states. Estimation will be conducted on each reversibly connected
        set separately. That means the transition matrix will decompose into disconnected submatrices,
        the stationary vector is only defined within subsets, etc. Currently not implemented.
    'none' : The active set is the full set of states. Estimation will be conducted on the full set of states
        without ensuring connectivity. This only permits nonreversible estimation. Currently not implemented.
estimate : bool, optional, default=True
    If true estimate the MSM when creating the MSM object.
dt : str, optional, default='1 step'
    Description of the physical time corresponding to the lag. May be used by analysis algorithms such as
    plotting tools to pretty-print the axes. By default '1 step', i.e. there is no physical time unit.
    Specify by a number, whitespace and unit. Permitted units are (* is an arbitrary string):

    |  'fs',  'femtosecond*'
    |  'ps',  'picosecond*'
    |  'ns',  'nanosecond*'
    |  'us',  'microsecond*'
    |  'ms',  'millisecond*'
    |  's',   'second*'

**kwargs: Optional algorithm-specific parameters. See below for special cases
maxiter = 1000000 : int
    Optional parameter with reversible = True.
    maximum number of iterations before the transition matrix estimation method exits
maxerr = 1e-8 : float
    Optional parameter with reversible = True.
    convergence tolerance for transition matrix estimation.
    This specifies the maximum change of the Euclidean norm of relative
    stationary probabilities (:math:`x_i = \sum_k x_{ik}`). The relative stationary probability changes
    :math:`e_i = (x_i^{(1)} - x_i^{(2)})/(x_i^{(1)} + x_i^{(2)})` are used in order to track changes in small
    probabilities. The Euclidean norm of the change vector, :math:`|e_i|_2`, is compared to maxerr.

Returns
-------
An :class:`EstimatedMSM <pyemma.msm.ui.EstimatedMSM>` object containing a transition matrix and various other
MSM-related quantities.

Notes
-----
You can postpone the estimation of the MSM using compute=False and
initiate the estimation procedure by manually calling the MSM.estimate()
method.


.. autoclass:: pyemma.msm.ui.msm.EstimatedMSM
    :members:
    :undoc-members:

    .. rubric:: Methods

    .. autoautosummary:: pyemma.msm.ui.msm.EstimatedMSM
       :methods:

    .. rubric:: Attributes

    .. autoautosummary:: pyemma.msm.ui.msm.EstimatedMSM
        :attributes:

See also
--------
EstimatedMSM : An MSM object that has been estimated from data

"""
```

**Comment by franknoe** [comment]
That is very nice because it shows all relevant info without needing to 
click around but still provides the information which class we're in.
I would only list attributes first and methods second (unless there's a 
standard to do it the other way around), but that's just my personal taste.

Thanks. Good work Moritz!

Am 11/06/15 um 13:29 schrieb Moritz Hoffmann:

> I have made the examples and uploaded it into my fork 
> https://github.com/clonker/PyEMMA/tree/sphinx_doc_autoautosummary. 
> Since now the class documentation gets pulled as well, one should 
> probably erase it or move it to **init**. The results are like the 
> following:
> markov_model 
> https://www.dropbox.com/s/2xh9mkpnw9gf6o3/msmdocs.pdf?dl=0 and 
> estimate_markov_model 
> https://www.dropbox.com/s/w7inbj4zf1uckr5/msmdocs2.pdf?dl=0.
> 
> ```
>       Docstring for markov_model
> ```
> 
> |r"""Markov model with a given transition matrix
> 
> Returns a :class:`MSM <pyemma.msm.ui.MSM>` that contains the transition matrix
> and allows to compute a large number of quantities related to Markov models.
> 
> ## Parameters
> 
> P : ndarray(n,n)
>      transition matrix
> dt : str, optional, default='1 step'
>      Description of the physical time corresponding to the lag. May be used by analysis algorithms such as
>      plotting tools to pretty-print the axes. By default '1 step', i.e. there is no physical time unit.
>      Specify by a number, whitespace and unit. Permitted units are (\* is an arbitrary string):
> 
> ```
>  |  'fs',  'femtosecond*'
>  |  'ps',  'picosecond*'
>  |  'ns',  'nanosecond*'
>  |  'us',  'microsecond*'
>  |  'ms',  'millisecond*'
>  |  's',   'second*'
> ```
> 
> ## Returns
> 
> msm : A :class:`MSM <pyemma.msm.ui.msm.MSM>` object containing a transition matrix and various other MSM-related quantities.
> 
> .. autoclass:: pyemma.msm.ui.msm.MSM
>      :members:
>      :undoc-members:
> 
> ```
>  .. rubric:: Methods
> 
>  .. autoautosummary:: pyemma.msm.ui.msm.MSM
>     :methods:
> 
>  .. rubric:: Attributes
> 
>  .. autoautosummary:: pyemma.msm.ui.msm.MSM
>      :attributes:
> ```
> 
> ## See also
> 
> MSM : A MSM object
> 
> """
> |
> 
> ```
>       Docstring for estimate_markov_model
> ```
> 
> |r"""Estimates a Markov model from discrete trajectories
> 
> Returns a :class:`EstimatedMSM <pyemma.msm.ui.EstimatedMSM>` that contains the estimated transition matrix
> and allows to compute a large number of quantities related to Markov models.
> 
> ## Parameters
> 
> dtrajs : list containing ndarrays(dtype=int) or ndarray(n, dtype=int)
>      discrete trajectories, stored as integer ndarrays (arbitrary size)
>      or a single ndarray for only one trajectory.
> lag : int
>      lagtime for the MSM estimation in multiples of trajectory steps
> reversible : bool, optional, default = True
>      If true compute reversible MSM, else non-reversible MSM
> sparse : bool, optional, default = False
>      If true compute count matrix, transition matrix and all derived quantities using sparse matrix algebra.
>      In this case python sparse matrices will be returned by the corresponding functions instead of numpy
>      arrays. This behavior is suggested for very large numbers of states (e.g. > 4000) because it is likely
>      to be much more efficient.
> connectivity : str, optional, default = 'largest'
>      Connectivity mode. Three methods are intended (currently only 'largest' is implemented)
>      'largest' : The active set is the largest reversibly connected set. All estimation will be done on this
>          subset and all quantities (transition matrix, stationary distribution, etc) are only defined on this
>          subset and are correspondingly smaller than the full set of states
>      'all' : The active set is the full set of states. Estimation will be conducted on each reversibly connected
>          set separately. That means the transition matrix will decompose into disconnected submatrices,
>          the stationary vector is only defined within subsets, etc. Currently not implemented.
>      'none' : The active set is the full set of states. Estimation will be conducted on the full set of states
>          without ensuring connectivity. This only permits nonreversible estimation. Currently not implemented.
> estimate : bool, optional, default=True
>      If true estimate the MSM when creating the MSM object.
> dt : str, optional, default='1 step'
>      Description of the physical time corresponding to the lag. May be used by analysis algorithms such as
>      plotting tools to pretty-print the axes. By default '1 step', i.e. there is no physical time unit.
>      Specify by a number, whitespace and unit. Permitted units are (\* is an arbitrary string):
> 
> ```
>  |  'fs',  'femtosecond*'
>  |  'ps',  'picosecond*'
>  |  'ns',  'nanosecond*'
>  |  'us',  'microsecond*'
>  |  'ms',  'millisecond*'
>  |  's',   'second*'
> ```
> 
> **kwargs: Optional algorithm-specific parameters. See below for special cases
> maxiter = 1000000 : int
>      Optional parameter with reversible = True.
>      maximum number of iterations before the transition matrix estimation method exits
> maxerr = 1e-8 : float
>      Optional parameter with reversible = True.
>      convergence tolerance for transition matrix estimation.
>      This specifies the maximum change of the Euclidean norm of relative
>      stationary probabilities (:math:`x_i = \sum_k x_{ik}`). The relative stationary probability changes
>      :math:`e_i = (x_i^{(1)} - x_i^{(2)})/(x_i^{(1)} + x_i^{(2)})` are used in order to track changes in small
>      probabilities. The Euclidean norm of the change vector, :math:`|e_i|_2`, is compared to maxerr.
> 
> ## Returns
> 
> An :class:`EstimatedMSM <pyemma.msm.ui.EstimatedMSM>` object containing a transition matrix and various other
> MSM-related quantities.
> 
> ## Notes
> 
> You can postpone the estimation of the MSM using compute=False and
> initiate the estimation procedure by manually calling the MSM.estimate()
> method.
> 
> .. autoclass:: pyemma.msm.ui.msm.EstimatedMSM
>      :members:
>      :undoc-members:
> 
> ```
>  .. rubric:: Methods
> 
>  .. autoautosummary:: pyemma.msm.ui.msm.EstimatedMSM
>     :methods:
> 
>  .. rubric:: Attributes
> 
>  .. autoautosummary:: pyemma.msm.ui.msm.EstimatedMSM
>      :attributes:
> ```
> 
> ## See also
> 
> EstimatedMSM : An MSM object that has been estimated from data
> 
> """
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/321#issuecomment-111090429.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
Thanks! I was just listing the methods first because that is what the sphinx doc generates automatically for the classes. What about the classes documentation, should I move it to __init__?
