### ISSUE TITLE
numpyfilereader should cache memmapped arrays

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#324]
but it should avoid hitting the open file limit of the operating system. Now with the fixes introduced for #320 it reopens every file for every iteration, which might hurt performance, if the file list is not large.

**Comment by franknoe** [comment]
So the file is opened and closed once for a full file read? I think this 
is acceptable.

Am 22/05/15 um 17:51 schrieb Martin K. Scherer:

> but it should avoid hitting the open file limit of the operating 
> system. Now with the fixes introduced for #320 
> https://github.com/markovmodel/PyEMMA/issues/320 it reopens every 
> file for every iteration, which might hurt performance, if the file 
> list is not large.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/324.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
ok, then we can close this now.
