### ISSUE TITLE
plot_flux is broken for automatic layout

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#329]
I've added a test on marscher/PyEMMA@9cff6ad946 in plots/tests and it fails with:

```
Traceback (most recent call last):
  File "/home/marscher/workspace/pyemma/pyemma/plots/tests/test_networks.py", line 40, in test_flux
    plot_flux(r)
  File "/home/marscher/workspace/pyemma/pyemma/plots/networks.py", line 393, in plot_flux
    figpadding=figpadding, xticks=True, yticks=False)
  File "/home/marscher/workspace/pyemma/pyemma/plots/networks.py", line 104, in plot_network
    self.layout_automatic()
  File "/home/marscher/workspace/pyemma/pyemma/plots/networks.py", line 245, in layout_automatic
    self.pos, self.stress = self._find_best_positions(V, g, 10, 25)
  File "/home/marscher/workspace/pyemma/pyemma/plots/networks.py", line 212, in _find_best_positions
    best_pos[j,:] = V[j].view.xy
AttributeError: 'defaultview' object has no attribute 'xy'
```

@franknoe since you wrote this, can you please have look?

**Comment by marscher** [comment]
During the calculation of the positions there are some None values in the list, which are converted to NaN

**Comment by franknoe** [comment]
I'll check this tomorrow

Am 27/05/15 um 17:53 schrieb Martin K. Scherer:

> During the calculation of the positions there are some None values in 
> the list, which are converted to NaN
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-105971303.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
there is one tiny mistake in the helper class defaultview, which had no xy attribute btw.

**Comment by franknoe** [comment]
ah, so can you fix it yourself?

Am 27/05/15 um 18:19 schrieb Martin K. Scherer:

> there is one tiny mistake in the helper class defaultview, which had 
> no xy attribute btw.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-105983205.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
no this was just an syntax error, which I've fixed on the referenced
branch to get further into this. But I do not understand the details
(have no clue, why there are None values in the xy list).

**Comment by franknoe** [comment]
Ah. I don't understand grandalf very well either, because it has 
absolute no documentation or code comments. But if the problem still 
persists tomorrow I can try to look into it. I guess this is the only 
issue left for the 1.2.1 release?

Am 27/05/15 um 18:35 schrieb Martin K. Scherer:

> no this was just an syntax error, which I've fixed on the referenced
> branch to get further into this. But I do not understand the details
> (have no clue, why there are None values in the xy list).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-105986715.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 27.05.2015 um 18:42 schrieb Frank Noe:

> Ah. I don't understand grandalf very well either, because it has
> absolute no documentation or code comments. But if the problem still
> persists tomorrow I can try to look into it. I guess this is the only
> issue left for the 1.2.1 release?
> I wonder how you then came up with using this library? Aren't networkx
> or pydot more convenient to achieve this goal?

You're right, this is the last issue. If you want me to join the debug
session, I'll be there.

Thank you.

**Comment by franknoe** [comment]
I was particularly looking for a library that does an energy 
minimization of the graph Hamiltonian, and found this one. I'm sure that 
others do something like that too. I also wanted to avoid an additional 
dependency and this library seemed small enough to justify a copy. But I 
would be more than happy to consider using an excerpt of another one!

Am 27/05/15 um 18:46 schrieb Martin K. Scherer:

> Am 27.05.2015 um 18:42 schrieb Frank Noe:
> 
> > Ah. I don't understand grandalf very well either, because it has
> > absolute no documentation or code comments. But if the problem still
> > persists tomorrow I can try to look into it. I guess this is the only
> > issue left for the 1.2.1 release?
> > I wonder how you then came up with using this library? Aren't networkx
> > or pydot more convenient to achieve this goal?
> 
> You're right, this is the last issue. If you want me to join the debug
> session, I'll be there.
> 
> Thank you.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-105989575.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
I think that networkx has a code to do this.

https://networkx.github.io/documentation/latest/reference/generated/networkx.drawing.layout.spring_layout.html

**Comment by marscher** [comment]
Networkx is also available in conda and PyPI (and is most probable
better tested and documentated than grandalf).

**Comment by franknoe** [comment]
But then we would probably have to create a dependency on networkx, or 
do you think this function could be extracted? I think a dependency is a 
bit of an overkill if we end up using one function.

Am 27/05/15 um 19:04 schrieb Martin K. Scherer:

> Networkx is also available in conda and PyPI (and is most probable
> better tested and documentated than grandalf).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-105997700.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
File "/home/marscher/workspace/pyemma/pyemma/plots/networks.py", line 272, in layout_automatic
    self.pos, self.stress = self._find_best_positions(V, g, 10, 25)
  File "/home/marscher/workspace/pyemma/pyemma/plots/networks.py", line 221, in _find_best_positions
    dig = DigcoLayout(g.C[0], opt_x=(self.xpos is None), opt_y=(self.ypos is None))
  File "/home/marscher/workspace/pyemma/pyemma/plots/grandalf/layouts.py", line 707, in __init__
    assert hasattr(v,'view')

Since a view object is created for all vertices, I do not understand, why this assertion fails.

**Comment by marscher** [comment]
if one sets the xy attribute of defaulview to zero rather than None, it works, but the value is never touched. I do not think this is desired.

**Comment by marscher** [comment]
If one returns in bestpos in _find_best_positions before the rescaling
routine, the graph looks correct (proper endstate, no collapsed nodes),
but of course the scaling is a bit weird.

**Comment by marscher** [comment]
fixed on devel (disabled min-max-scaling, fixed some minor bugs [eg. xy attribute not available in defaultview, restore fontsize of matplotlib])

**Comment by franknoe** [comment]
thanks

Am 28/05/15 um 21:57 schrieb Martin K. Scherer:

> fixed on devel (disabled min-max-scaling, fixed some minor bugs [eg. 
> xy attribute not available in defaultview, restore fontsize of 
> matplotlib])
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106580517.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
If there are no other urgent things left on the list. I would like to
push the 1.2.1 release to PyPI and start building conda packages afterwards.

**Comment by franknoe** [comment]
I have no other feature requests or obvious bugfixes, but it would be 
good to work a bit with the devel version before releasing it.

Has guille tried using the Pipeline after your fix?

Am 28/05/15 um 21:59 schrieb Martin K. Scherer:

> If there are no other urgent things left on the list. I would like to
> push the 1.2.1 release to PyPI and start building conda packages 
> afterwards.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106580950.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
He thanked me for fixing it, so I guess he at least tried that the
observed error has gone. But I agree it will be better if some more
people use it before doing it. There also the possibility to release a
pre-version on pypi, which can then be easily installed and tested.

Or at least a git-pre-tag which can the be installed via pip:

pip install git+https://github.com/markovmodel/PyEMMA.git@v1.2.1-pre

if the tag name is "v1.2.1-pre"

**Comment by franknoe** [comment]
That sounds good. Can we do something similar on conda such that you 
could use 1.2.1 in Melbourne but we only officially release it when we 
feel its stable?

Am 28/05/15 um 22:11 schrieb Martin K. Scherer:

> He thanked me for fixing it, so I guess he at least tried that the
> observed error has gone. But I agree it will be better if some more
> people use it before doing it. There also the possibility to release a
> pre-version on pypi, which can then be easily installed and tested.
> 
> Or at least a git-pre-tag which can the be installed via pip:
> 
> pip install git+https://github.com/markovmodel/PyEMMA.git@v1.2.1-pre
> 
> if the tag name is "v1.2.1-pre"
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106583187.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 28.05.2015 um 22:13 schrieb Frank Noe:

> That sounds good. Can we do something similar on conda such that you
> could use 1.2.1 in Melbourne but we only officially release it when we
> feel its stable?

I do not know, if conda supports pre-releases like pip (there it is
implemented by special version numbers).
But we can use different software-channels on Binstar to hide it from
the main channel users will get their updates from, so they would have
to specify a different channel during install/update.

**Comment by franknoe** [comment]
Hm, sounds too complicated. Maybe you can build the conda package, 
Guille and I will play with a few things tomorrow and if everything is 
fine you can push

Am 28/05/15 um 22:20 schrieb Martin K. Scherer:

> Am 28.05.2015 um 22:13 schrieb Frank Noe:
> 
> > That sounds good. Can we do something similar on conda such that you
> > could use 1.2.1 in Melbourne but we only officially release it when we
> > feel its stable?
> 
> I do not know, if conda supports pre-releases like pip (there it is
> implemented by special version numbers).
> But we can use different software-channels on Binstar to hide it from
> the main channel users will get their updates from, so they would have
> to specify a different channel during install/update.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106585067.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
After Melbourne we have to assemble ipython notebook Tutorials and 
automatically run them before releasing.

Am 28/05/15 um 22:20 schrieb Martin K. Scherer:

> Am 28.05.2015 um 22:13 schrieb Frank Noe:
> 
> > That sounds good. Can we do something similar on conda such that you
> > could use 1.2.1 in Melbourne but we only officially release it when we
> > feel its stable?
> 
> I do not know, if conda supports pre-releases like pip (there it is
> implemented by special version numbers).
> But we can use different software-channels on Binstar to hide it from
> the main channel users will get their updates from, so they would have
> to specify a different channel during install/update.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106585067.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 28.05.2015 um 22:33 schrieb Frank Noe:

> After Melbourne we have to assemble ipython notebook Tutorials and
> automatically run them before releasing.
> Yes, that would be a release killer feature.

**Comment by marscher** [comment]
where is the difference between a pre-built version and a pip install,
except for extensions were already compiled? The code which is executed
is the same, despite binary extensions, but I presume compilers at least
guarantee deterministic program behaviour nowadays.

So the overhead of building conda pkgs before releasing it, is IMHO not
needed.

**Comment by marscher** [comment]
Of course we should test it before doing so.

**Comment by franknoe** [comment]
I just meant we play with the devel version without making any further 
changes to it tomorrow.
In the meantime you can do anything to prepare the release without 
actually doing the release.

Am 28/05/15 um 22:37 schrieb Martin K. Scherer:

> where is the difference between a pre-built version and a pip install,
> despite the extensions were already compiled? The code which is executed
> is the same, despite binary extensions, but I presume compilers at least
> guarantee deterministic program behaviour nowadays.
> 
> So the overhead of building conda pkgs before releasing it, is IMHO not
> needed.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106588845.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Hi, this issue has become a discussion about the release itself (not about the 
plot_flux fix), so I only now noticed the discussion.

I tried the pipeline after Martin's fix. Have not entirely played around with 
it, planned to do so tomorrow.

Plus, since we're on the release, could we merge my PR? Does not break anything 
and is extensively tested.

On 05/28/2015 10:39 PM, Frank Noe wrote:

> I just meant we play with the devel version without making any further
> changes to it tomorrow.
> In the meantime you can do anything to prepare the release without
> actually doing the release.
> 
> Am 28/05/15 um 22:37 schrieb Martin K. Scherer:
> 
> > where is the difference between a pre-built version and a pip install,
> > despite the extensions were already compiled? The code which is executed
> > is the same, despite binary extensions, but I presume compilers at least
> > guarantee deterministic program behaviour nowadays.
> > 
> > So the overhead of building conda pkgs before releasing it, is IMHO not
> > needed.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106588845.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106589272.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by franknoe** [comment]
ok for me

Am 28/05/15 um 23:13 schrieb Guillermo Pérez-Hernández:

> Hi, this issue has become a discussion about the release itself (not 
> about the
> plot_flux fix), so I only now noticed only now.
> 
> I tried the pipeline after Martin's fix. Have not entirely played 
> around with
> it, planned to do so tomorrow.
> 
> Plus, since we're on the release, coul'd we merge my PR? Does not 
> break anything
> and is extensively tested.
> 
> On 05/28/2015 10:39 PM, Frank Noe wrote:
> 
> > I just meant we play with the devel version without making any further
> > changes to it tomorrow.
> > In the meantime you can do anything to prepare the release without
> > actually doing the release.
> > 
> > Am 28/05/15 um 22:37 schrieb Martin K. Scherer:
> > 
> > > where is the difference between a pre-built version and a pip install,
> > > despite the extensions were already compiled? The code which is 
> > > executed
> > > is the same, despite binary extensions, but I presume compilers at 
> > > least
> > > guarantee deterministic program behaviour nowadays.
> > > 
> > > So the overhead of building conda pkgs before releasing it, is 
> > > IMHO not
> > > needed.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106588845.
> > 
> > ## 
> > 
> > ---
> > 
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> > 
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > 
> > ## Mail: Arnimallee 6, 14195 Berlin, Germany
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106589272.
> 
> ## 
> 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106601110.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
@gph82, sorry for being off topic here! Should have started a release issue!

I would really like to include your changes. Would you be so kind to
update the changelog, if you changed anything relevant to users?

**Comment by gph82** [comment]
:)

do I do that on my fork and then update the PR or on the devel branch?

On 05/28/2015 11:26 PM, Martin K. Scherer wrote:

> @gph82, sorry for being off topic here! Should have started a release issue!
> 
> I would really like to include your changes. Would you be so kind to
> update the changelog, if you changed anything relevant to users?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106604887.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by marscher** [comment]
just commit and push your branch again to our fork and the PR is being
updated in no time.

**Comment by gph82** [comment]
ok, I messed the PR up again. I'll do it tomorrow

On 05/28/2015 11:35 PM, Martin K. Scherer wrote:

> just commit and push your branch again to our fork and the PR is being
> updated in no time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/329#issuecomment-106606953.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776
