### ISSUE TITLE
plot_flux only supports plotting the netflux

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#334]
In the ancient pre 1.2 times in the tpt notebook we showed various fluxes (gross, net, percentage, ... ). Shouldn't we add an optional keyword which attribute of ReactiveFlux we want to visualize, which defaults to 'net_flux'?

**Comment by marscher** [comment]
@franknoe or is this directly possible via the NetworkPlot class?

**Comment by marscher** [comment]
It is, very nice. Should we expose the class to the API, with an example how to use it?

**Comment by franknoe** [comment]
sure, why not

Am 27/05/15 um 21:05 schrieb Martin K. Scherer:

> It is, very nice. Should we expose the class to the API, with an 
> example how to use it?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/334#issuecomment-106037766.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
First or second option or even both?

**Comment by franknoe** [comment]
we can use netflux=True. If True the netflux (=flux) is plotted. If 
False the gross flux is plotted.

Am 27/05/15 um 21:08 schrieb Martin K. Scherer:

> First or second option or even both?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/334#issuecomment-106038273.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
