### ISSUE TITLE
[coordinates.pipeline] error: "NotImplementedError: a reader is not meant to be parameterized by data"

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#335]
I am using a reader (created with `source`) that has `data.numpy_filereader.NumPyFileReader` as a `data_producer`. When using the reader in a transformer everything works. However, as part of a pipeline, I get the above error.

Is this really not implemented for pipelines? 

```
import pyemma
import numpy as np
% cd ~/gph82@grouphome/simulation-data/Opsin_FAH_Greg/IP_5226_atoms/

# Filelist
filelist='list_frame0.whole.Ca.NoLoop_mRMSD.225to250dist.dat'

# Load some files
filelist=open(filelist).read().splitlines()[:50]

FAH_IP_source =  pyemma.coordinates.source(filelist, chunk_size=50000)

# Instantiate transformer
TICA_transformer = pyemma.coordinates.tica(lag = 10, 
                                           dim = 10, 
                                           stride = 10)

# Instantiate pipeline
TICA_pipeline = pyemma.coordinates.pipeline([FAH_IP_source, 
                                             TICA_transformer,
                                             pyemma.coordinates.cluster_regspace(dmin = .1)
                                            ],
                                            run = False, stride = 10)
TICA_pipeline.chunksize = 5000

TICA_pipeline.parametrize()

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-7-35d1bdbe1899> in <module>()
     12 TICA_pipeline.chunksize = 5000
     13 
---> 14 TICA_pipeline.parametrize()

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/pipelines.pyc in parametrize(self)
    158         """
    159         for element in self._chain:
--> 160             element.parametrize(stride=self.param_stride)
    161 
    162         self._parametrized = True

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/transform/transformer.pyc in parametrize(self, stride)
    286                     # first chunk
    287                     return_value = self._param_add_data(
--> 288                         X, itraj, t, first_chunk, last_chunk_in_traj, last_chunk, ipass, Y=Y, stride=stride)
    289 
    290                     if not self._custom_param_progress_handling:

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/interface.pyc in _param_add_data(self, *args, **kwargs)
    150 
    151     def _param_add_data(self, *args, **kwargs):
--> 152         raise NotImplementedError("a reader is not meant to be parameterized by data")

NotImplementedError: a reader is not meant to be parameterized by data
```

**Comment by marscher** [comment]
Am 28.05.2015 um 17:15 schrieb Guillermo Pérez-Hernández:

> I am using a reader (created with |source|) that has
> |data.numpy_filereader.NumPyFileReader| as a |data_producer|. When using
> the reader in a transformer everything works. However, as part of a
> pipeline, I get the above error.
> 
> Is this really not implemented for pipelines?
> This error is caused, because the self._parametrized flag has been
> changed (somewhere) to False. Actually these methods should not be
> called and are causing unnecessary overhead, thats why I've added a
> raise there. I'm looking into it, why the status is being changed.

**Comment by franknoe** [comment]
Is it possible that the reader is a transformer? I guess it shouldn't be.

Anyhow this does not occur with xtc input, so I guess it is specifiy to 
some formats such as npy.

Am 28/05/15 um 17:21 schrieb Martin K. Scherer:

> Am 28.05.2015 um 17:15 schrieb Guillermo Pérez-Hernández:
> 
> > I am using a reader (created with |source|) that has
> > |data.numpy_filereader.NumPyFileReader| as a |data_producer|. When using
> > the reader in a transformer everything works. However, as part of a
> > pipeline, I get the above error.
> > 
> > Is this really not implemented for pipelines?
> > This error is caused, because the self._parametrized flag has been
> > changed (somewhere) to False. Actually these methods should not be
> > called and are causing unnecessary overhead, thats why I've added a
> > raise there. I'm looking into it, why the status is being changed.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/335#issuecomment-106402520.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
