### ISSUE TITLE
[coordinates.discretizer] visibility of the chain's object's properties 

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#336]
The code 

```
TICA_discretizer_pipeline = pyemma.coordinates.discretizer(FAH_IP_source, 
                                                           transform=TICA_transformer,
                                                           cluster = pyemma.coordinates.cluster_regspace(dmin = 1.5)
                                                            )
```

works fine. One can move on to use `TICA_discretizer_pipeline.dtrajs`  to compute timescales etc. 

However, to gain access to the properties of the clustering object (eg, coordinates of the actual clustercenters, or how much there are), on has to do sth. like

```
TICA_discretizer_pipeline._chain[2].clustercenters
```

or 

```
cluster_obj = TICA_discretizer_pipeline._chain[2]
```

and then continue with the cluster_obj object. 

Perhaps we can make some properties (not only of the clustering object) visible from the pipeline object? 
It is clear to me that one can always retrieve them via the ._chain[x] construct, but it is also nice that the pipeline is self contained  (and explained) with things like

`````` TICA_discretizer_pipeline.clustercenters```
```TICA_discretizer_pipeline.n_clusters```
```TICA_discretizer_pipeline.data_producer```

We should not clutter the object either, or replicate info that's available elsewhere, but I find this is a nice way to work (and think!) in terms of pipelines
``````

**Comment by franknoe** [comment]
No, it's simpler than that. Have a look at the London notebook.

You can use

``` python
source = ...
transform = pyemma.coordinates.tica(...)
cluster = pyemma.coordinates.cluster_regspace(dmin = 1.5)
p = pipeline([source, transform, cluster])

dtrajs = cluster.dtrajs
cl = cluster.clustercenters[]
```

The pipeline only parametrizes things. In fact you really don't need the 
pipeline object, because you can do ad-hoc pipelines as follows:

``` python
source = ...

transform = pyemma.coordinates.tica(source, ...)

cluster = pyemma.coordinates.cluster_regspace(transform, dmin = 1.5)

dtrajs = cluster.dtrajs
cl = cluster.clustercenters[]
```

Am 29/05/15 um 11:18 schrieb Guillermo Pérez-Hernández:

> The code
> 
> |TICA_discretizer_pipeline = pyemma.coordinates.discretizer(FAH_IP_source,
>                                                             transform=TICA_transformer,
>                                                             cluster = pyemma.coordinates.cluster_regspace(dmin = 1.5)
>                                                              )
> |
> 
> works fine. One can move on to use |TICA_discretizer_pipeline.dtrajs| 
> to compute timescales etc.
> 
> However, to gain access to the properties of the clustering object 
> (eg, coordinates of the actual clustercenters, or how much there are), 
> on has to do sth. like
> 
> |TICA_discretizer_pipeline._chain[2].clustercenters
> |
> 
> or
> 
> |cluster_obj = TICA_discretizer_pipeline._chain[2]
> |
> 
> and then continue with the cluster_obj object.
> 
> Perhaps we can make some properties (not only of the clustering 
> object) visible from the pipeline object?
> It is clear to me that one can always retrieve them via the ._chain[x] 
> construct, but it is also nice that the pipeline is self contained 
> (and explained) with things like
> 
> |`TICA_discretizer_pipeline.n_clusters`
> 
> ``` TICA_discretizer_pipeline.data_producer```
> 
> We should not clutter the object either, or replicate info that's available elsewhere, but I find this is a nice way to work (and think!) in terms of pipelines
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/336>.
> 
> 
> ```

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
" The pipeline only parametrizes things" I had not realized that the objects outside the pipeline would be parametrized by the pipeline. I guess it's a pythonic thing about "outside" and "inside". Perhaps we can write this in the docu.

Thanks!

**Comment by franknoe** [comment]
This concept exists (at least in some rudimentary way) in every 
programming language. In functional languages you can pass pointers. In 
object-oriented languages, you pass an object to a function and that 
function does something with the object. In fact you do that all the 
time. For example,

``` python
a = np.array([1,2,3])
np.sum(a)
```

The sum function takes an ndarray object, calls functions on it to get 
the elements (actually this probably happens on the C-level, but that is 
irrelevant to understand the concept), and in this case returns the sum 
of elements as a result.

Not the same thing you say? The following example is more similar to 
what the pipeline does:

``` python
a = np.array([1,2,3])
b = np.array([1,2,3])[:,None]
c = np.zeros((3,3))
np.dot(b, a, c)
```

np.dot takes objects a and b, computes the outer product and fills the 
result into the elements of object c, i.e. it parametrizes object c. Now 
you can access the content of c "outside"

``` python
np.sum(c)
```

Docs: Yes definitely. Please write tutorials and doc examples! I cannot 
do that alone, so I ask everyone who knows how something works and feels 
that the docs are insufficient on something to just go ahead and write it.

Am 29/05/15 um 11:34 schrieb Guillermo Pérez-Hernández:

> " The pipeline only parametrizes things" I had not realized that the 
> objects outside the pipeline would be parametrized by the pipeline. I 
> guess it's a pythonic thing about "outside" and "inside". Perhaps we 
> can write this in the docu.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/336#issuecomment-106758362.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
