### ISSUE TITLE
[pyemma.coordinates.cluster_regspace]  WARNING  Maximum number of cluster centers reached

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#337]
Do we really need one warning per iteration once the maximum has been reached? This is potentially generating an output large enough to crash the notebook...not being helpful at all. Can we just issue one?

**Comment by franknoe** [comment]
Shouldn't the clustering algorithm stop anyway once that happens?

Am 29/05/15 um 13:55 schrieb Guillermo Pérez-Hernández:

> Do we really need one warning per iteration once the maximum has been 
> reached? This is potentially generating an output large enough to 
> crash the notebook...not being helpful at all. Can we just issue one?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/337.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
it does not. I also find this behaviour strange

On 29.05.2015 13:57, Frank Noe wrote:

> Shouldn't the clustering algorithm stop anyway once that happens?
> 
> Am 29/05/15 um 13:55 schrieb Guillermo Pérez-Hernández:
> 
> > Do we really need one warning per iteration once the maximum has been
> > reached? This is potentially generating an output large enough to
> > crash the notebook...not being helpful at all. Can we just issue one?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/337.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/337#issuecomment-106782692.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by franknoe** [comment]
And generally I vote for being less verbose by default. Algorithms that 
show by progress bars what they are doing should not also show visible 
logging.

Am 29/05/15 um 13:55 schrieb Guillermo Pérez-Hernández:

> Do we really need one warning per iteration once the maximum has been 
> reached? This is potentially generating an output large enough to 
> crash the notebook...not being helpful at all. Can we just issue one?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/337.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
seems to be a serious bug in Transformer.parametrize, where we have the assumption that all algorithms will always run over the complete data set (at least once). The add_data_finished variable in regspace is being returned as True, if max_centers is reached, but the status of this only being checked in the most outer while loop, so in fact we would need to break there or check the status of add_data_finished in each inner while loop.

**Comment by marscher** [comment]
this is why being verbose sometimes also helps a lot :+1: Of course we should minimize logging messages, but this is also what different log levels are intended for.

**Comment by marscher** [comment]
As a quick fix I check the status of add_data_finished in parametrize again at the top of thin most inner loop, since kmeans etc. rely on being called with last_chunk=True. All tests are passing though.

**Comment by gph82** [comment]
still observing multiple warnings when using regspace. pyemma version 1.2-398-g209f9ad

**Comment by marscher** [comment]
unfortunately the version hash is not descriptive (which it should be).
Which branch are you working on?

**Comment by gph82** [comment]
Your branch is up-to-date with 'origin/dev_release_1.3'.

Last commit is:
commit 209f9ad0f6f80bc6a5006feb6613b534d4f4c21b
Author: marscher m.scherer@fu-berlin.de
Date:   Mon Jul 6 15:13:21 2015 +0200

```
[plots/networks] do not create a new figure inside the plot_network function to
enable users to stack plots.
```

**Comment by marscher** [comment]
mhm, actually we rebased dev_release on devel, which includes the fix
for this problem, but it is not there... hang on.

**Comment by marscher** [comment]
can you please pull dev_release again and rebase your branch on it?

**Comment by gph82** [comment]
Yeah, now it's ok. What happened, BTW?

**Comment by marscher** [comment]
I do not know, it was fucking hot in my office, when we did the rebase
with @clonker.
