### ISSUE TITLE
Consider importing joblib and using it for parallel calculation

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#338]
Extensively used in sklearn:

https://github.com/scikit-learn/scikit-learn/tree/master/sklearn/externals/joblib

**Comment by marscher** [comment]
we can also implement #147 with this library, so I really like to use it.

**Comment by franknoe** [comment]
really? I guess you have to explain when you're back, because I don't 
see the relationship to caching, but it sounds nice.

Am 02/06/15 um 06:04 schrieb Martin K. Scherer:

> we can also implement #147 
> https://github.com/markovmodel/PyEMMA/issues/147 with this library, 
> so I really like to use it.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/338#issuecomment-107794846.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
on https://pythonhosted.org/joblib/index.html The 3 main features are listed: second point "transparent disk-caching of the output values and lazy re-evaluation (memoize pattern)"

So it is possible to decorate functions (or methods) to store their results in an optional disk cache to avoid re-evaluation. Of course we have to think about, how to expose this feature to the API, since it is only sometimes desired and it should be flexible (cache location, maximum size etc).

**Comment by franknoe** [comment]
thanks, I wasn't aware of that.

Am 02/06/15 um 10:54 schrieb Martin K. Scherer:

> on https://pythonhosted.org/joblib/index.html The 3 main features are 
> listed: second point "transparent disk-caching of the output values 
> and lazy re-evaluation (memoize pattern)"
> 
> So it is possible to decorate functions (or methods) to store their 
> results in an optional disk cache to avoid re-evaluation. Of course we 
> have to think about, how to expose this feature to the API, since it 
> is only sometimes desired and it should be flexible (cache location, 
> maximum size etc).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/338#issuecomment-107872825.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I have successfully used joblib in parallelizing the boostrapping in ImpliedTimescales, but as I understood this is obsolete with the refactored MSM classes. So should consider using joblib in the refactor_msm branch.

**Comment by franknoe** [comment]
refactor_model_estimator. Yes, we should do this, but need to write this 
part of the code. I think this functionality will now be at a central 
position, e.g. here:

https://github.com/markovmodel/PyEMMA/blob/refactor_model_estimator/pyemma/_base/estimator.py

in estimate_param_scan

we could add an option nproc that defaults either to 1 (one processor) 
or -1 (all processors). Maybe 1 is more safe because for some algorithms 
the python parallelization actually makes it slower.

Am 07/07/15 um 13:40 schrieb Martin K. Scherer:

> I have successfully used joblib in parallelizing the boostrapping in 
> ImpliedTimescales, but as I understood this is obsolete with the 
> refactored MSM classes. So should consider using joblib in the 
> refactor_msm branch.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/338#issuecomment-119178712.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 07.07.2015 um 13:45 schrieb Frank Noe:

> refactor_model_estimator. Yes, we should do this, but need to write this
> part of the code. I think this functionality will now be at a central
> position, e.g. here:
> 
> https://github.com/markovmodel/PyEMMA/blob/refactor_model_estimator/pyemma/_base/estimator.py
> 
> in estimate_param_scan
> 
> we could add an option nproc that defaults either to 1 (one processor)
> or -1 (all processors). Maybe 1 is more safe because for some algorithms
> the python parallelization actually makes it slower.
> I have used None for all procs and default set to 1 so far. You're right
> when using multiprocessing module the overhead of transferring data
> around sometimes is not worth it.

**Comment by franknoe** [comment]
Ah, I think the -1 is a convention that comes either from joblib or 
sklearn (I don't remember). I guess the idea is similar like for -1 
being the last index of an array. But that's not a crucial question, 
because ideally the use won't have to fiddle around much with. We can 
decide which lower-level algos are worth parallelizing and then set 
nproc to a reasonable choice in higher-level algos such as the 
timescales estimator

Am 07/07/15 um 13:47 schrieb Martin K. Scherer:

> Am 07.07.2015 um 13:45 schrieb Frank Noe:
> 
> > refactor_model_estimator. Yes, we should do this, but need to write this
> > part of the code. I think this functionality will now be at a central
> > position, e.g. here:
> > 
> > https://github.com/markovmodel/PyEMMA/blob/refactor_model_estimator/pyemma/_base/estimator.py
> > 
> > in estimate_param_scan
> > 
> > we could add an option nproc that defaults either to 1 (one processor)
> > or -1 (all processors). Maybe 1 is more safe because for some algorithms
> > the python parallelization actually makes it slower.
> > I have used None for all procs and default set to 1 so far. You're right
> > when using multiprocessing module the overhead of transferring data
> > around sometimes is not worth it.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/338#issuecomment-119179636.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
BTW, there are two parallelization modes in joblib: multiprocessing and 
multithreading. The multithreading option sometimes seems to have better 
speedup properties (I guess threads can share data). However in my (very 
preliminary) tests multiprocessing was stable whereas mutlitthreading 
has crashed for reasons that I could not interpret. Unfortunately I 
don't know much about parallelization.

Am 07/07/15 um 13:47 schrieb Martin K. Scherer:

> Am 07.07.2015 um 13:45 schrieb Frank Noe:
> 
> > refactor_model_estimator. Yes, we should do this, but need to write this
> > part of the code. I think this functionality will now be at a central
> > position, e.g. here:
> > 
> > https://github.com/markovmodel/PyEMMA/blob/refactor_model_estimator/pyemma/_base/estimator.py
> > 
> > in estimate_param_scan
> > 
> > we could add an option nproc that defaults either to 1 (one processor)
> > or -1 (all processors). Maybe 1 is more safe because for some algorithms
> > the python parallelization actually makes it slower.
> > I have used None for all procs and default set to 1 so far. You're right
> > when using multiprocessing module the overhead of transferring data
> > around sometimes is not worth it.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/338#issuecomment-119179636.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 07.07.2015 um 13:52 schrieb Frank Noe:

> BTW, there are two parallelization modes in joblib: multiprocessing and
> multithreading. The multithreading option sometimes seems to have better
> speedup properties (I guess threads can share data). However in my (very
> preliminary) tests multiprocessing was stable whereas mutlitthreading
> has crashed for reasons that I could not interpret. Unfortunately I
> don't know much about parallelization.

Actually multithreading in Python is only useful if you make several
(parallizable) calls into an extension which releases the global
interpreter lock. Otherwise your runtime will multiply by the number of
threads. From the docs of joblib:

```
If you know that the function you are calling is based on a compiled
extension that releases the Python Global Interpreter Lock (GIL) during
most of its computation then it might be more efficient to use threads
instead of Python processes as concurrent workers. For instance this is
the case if you write the CPU intensive part of your code inside a `with
nogil`_ block of a Cython function.
```

**Comment by marscher** [comment]
merged.
