### ISSUE TITLE
Transformer.trajectory_length(s) should return numpy arrays

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#340]
That allows to do algebra on these quantities more easily. It will not brake the api, since a numpy array and a list are essentially api compatible from a duck typing point of view. This has been suggested by @gph82 recently.

**Comment by franknoe** [comment]
OK

Am 02/06/15 um 06:17 schrieb Martin K. Scherer:

> That allows to do algebra on these quantities more easily. It will not 
> brake the api, since a numpy array and a list are essentially api 
> compatible from a duck typing point of view. This has been suggested 
> by @gph82 https://github.com/gph82 recently.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/340.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
+1
