### ISSUE TITLE
DataInMemory doesn't respect chunk size (+/-1 ?)

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#344]
``` Python
import pyemma
import numpy as np
data = np.random.randn(200,2)
source = pyemma.coordinates.source(data,chunk_size=100)
source.chunksize = 100
for i,ch in source.iterator():
    print ch.shape
# (101, 2)
# (99, 2)
```

**Comment by gph82** [comment]
This has to do with the infamous +1/-1 we just had on the MMX_transformer?

**Comment by fabian-paul** [comment]
yep

**Comment by gph82** [comment]
something good always comes from these sessions...

On 04.06.2015 19:15, fabian-paul wrote:

> yep
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/344#issuecomment-108979663.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by fabian-paul** [comment]
With lag and stride it gets even funnier

``` Python
import pyemma
import numpy as np
data = np.random.randn(1000,10)
source = pyemma.coordinates.source(data)
for i,X,Y in source.iterator(stride=2,lag=16):
    print i, X.shape, Y.shape
```

Output:

```
0 (500L, 10L) (492L, 10L)
0 (250L, 10L) (242L, 10L)
0 (125L, 10L) (117L, 10L)
0 (63L, 10L) (55L, 10L)
0 (31L, 10L) (23L, 10L)
0 (16L, 10L) (8L, 10L)
0 (8L, 10L) (0L, 10L)
0 (4L, 10L) (0L, 10L)
0 (2L, 10L) (0L, 10L)
0 (1L, 10L) (0L, 10L)
```

**Comment by fabian-paul** [comment]
Could please somebody tell me what are the conventions for the simultaneous use of lag and stride, that you agreed upon?
What would be the equivalent operation in Python? Would it be (i)

``` Python
x[::stride][lag:]
```

or (ii)

``` Python
x[lag::stride]
```

?
For the feature reader as it exists in the devel branch, this seems to be (i). There were some rumours that you wanted to change it to (ii). What happened to that idea?

**Comment by marscher** [comment]
We agreed upon using the numpy style which is II, but we postponed it
after 1.2.1 (eg. Melbourne). If you are in the mood to change this now I
would really appreciate.

**Comment by gph82** [comment]
I raised this different options in #238

**Comment by fabian-paul** [comment]
Ok, I have changed the bahavior of "data in memory" to (i) in pull request #347 (together with a fix). That way the development branch is consistent within itself (feature reader and data in memory both use (i)).
Changing everything to (ii) is too much work for me now.
