### ISSUE TITLE
.pyemma is not writeable

### ISSUE THREAD

**Issue by euhruska** [markovmodel/PyEMMA#350]
I get a error when importing pyemma in a job on a cluster, it says ".pyemma is not writeable". But when I import pyemma in python it works without error. I tried making .pyemma directory chmod 777, but didn't help. Do you know how to fix this?

"""
raceback (most recent call last):
  File "/home/eh22/local/bin/lsdmap", line 3, in <module>
    import lsdmap.lsdm as lsdm
  File "/home/eh22/local/lib/python2.7/site-packages/lsdmap/lsdm.py", line 15, in <module>
    from lsdmap.util import metric as mt
  File "/home/eh22/local/lib/python2.7/site-packages/lsdmap/util/metric.py", line 7, in <module>
    import pyemma
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/**init**.py", line 31, in <module>
    from . import coordinates
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/coordinates/**init**.py", line 75, in <module>
    from .api import *
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/coordinates/api.py", line 32, in <module>
    from pyemma.util.log import getLogger as _getLogger
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/log.py", line 124, in <module>
    setupLogging()
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/log.py", line 60, in setupLogging
    from pyemma.util.config import conf_values
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/config.py", line 205, in <module>
    readConfiguration()
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/config.py", line 156, in readConfiguration
    pyemma_cfg_dir = create_cfg_dir(default_pyemma_conf)
  File "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/config.py", line 134, in create_cfg_dir
    raise RuntimeError("%s is not writeable" % pyemma_cfg_dir)
RuntimeError: /home/eh22/.pyemma is not writeable
"""

**Comment by franknoe** [comment]
Hi Eugen. Thanks for reporting this. I don't know what exactly went 
wrong in your case, but I don't think we actually need to write config 
files anymore. This seems to be a relict from an old version.
@marscher, can we remove this whole config-business? At least we 
shouldn't try to write files at import time because we probably can't 
control the access rights on an unknown file system.

Am 10/06/15 um 21:54 schrieb euhruska:

> I get a error when importing pyemma in a job on a cluster, it says 
> ".pyemma is not writeable". But when I import pyemma in python it 
> works without error. I tried making .pyemma directory chmod 777, but 
> didn't help. Do you know how to fix this?
> 
> """
> raceback (most recent call last):
> File "/home/eh22/local/bin/lsdmap", line 3, in
> import lsdmap.lsdm as lsdm
> File "/home/eh22/local/lib/python2.7/site-packages/lsdmap/lsdm.py", 
> line 15, in
> from lsdmap.util import metric as mt
> File 
> "/home/eh22/local/lib/python2.7/site-packages/lsdmap/util/metric.py", 
> line 7, in
> import pyemma
> File "/home/eh22/local/lib/python2.7/site-packages/pyemma/_init_.py", 
> line 31, in
> from . import coordinates
> File 
> "/home/eh22/local/lib/python2.7/site-packages/pyemma/coordinates/_init_.py", 
> line 75, in
> from .api import *
> File 
> "/home/eh22/local/lib/python2.7/site-packages/pyemma/coordinates/api.py", 
> line 32, in
> from pyemma.util.log import getLogger as _getLogger
> File 
> "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/log.py", 
> line 124, in
> setupLogging()
> File 
> "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/log.py", 
> line 60, in setupLogging
> from pyemma.util.config import conf_values
> File 
> "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/config.py", 
> line 205, in
> readConfiguration()
> File 
> "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/config.py", 
> line 156, in readConfiguration
> pyemma_cfg_dir = create_cfg_dir(default_pyemma_conf)
> File 
> "/home/eh22/local/lib/python2.7/site-packages/pyemma/util/config.py", 
> line 134, in create_cfg_dir
> raise RuntimeError("%s is not writeable" % pyemma_cfg_dir)
> RuntimeError: /home/eh22/.pyemma is not writeable
> """
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/350.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Eugen, I am trying to put a safeguard into the config file manager. What's happening here is this: when you import pyemma for the first time it tries to create a config file in your home directory (for me e.g. ~noe/.pyemma/pyemma.cfg), which can store personal settings such as how you want logging information to be shown. Apparently it can't create that file. Are you sure that file is writable and there is no such thing as a quota problem?

**Comment by euhruska** [comment]
Well, I put chmod 777 on that directory so it should be writable by anyone. I'm not sure I understand the quota problem, but the disk is not full. 
I tried deleting that .pyemma directory, but the directory was made new and produced the same error.
I was running the job on several cpus in parallel, now I'm looking if it works with 1 cpu.

**Comment by euhruska** [comment]
Looks like it works.

**Comment by franknoe** [comment]
check if the config file is there. If yes, try again with multiple CPUs

**Comment by franknoe** [comment]
Eugen, I think this is a file locking issue that occurs in combination with MPI or whatever you use as a parallel machinery. I think it would be best if @marscher looks at this, but he is traveling right now. Can you live with the serial version for a few days?

**Comment by euhruska** [comment]
yep, that might work

**Comment by franknoe** [comment]
OK. I have an intuition how this problem could be avoided, but I'm not sure, so let's wait. Thanks for reporting it!

**Comment by franknoe** [comment]
@marscher although I don't completely understand the source of this problem I vote for making config.py failsafe. There is no reason why we need to test for every import whether the file is writable and raise an exception if not. Only if it is not writeable but we actually try to set a config value that would be a problem, and that could generate a warning if the setting cannot be stored. For reading the conf, a reasonable default behavior is to return the default config file.

**Comment by marscher** [comment]
Am 11.06.2015 um 07:40 schrieb Frank Noe:

> @marscher https://github.com/marscher although I don't completely
> understand the source of this problem I vote for making config.py
> failsafe. There is no reason why we need to test for every import
> whether the file is writable and raise an exception if not. Only if it
> is not writeable but we actually try to set a config value that would be
> a problem, and that could generate a warning if the setting cannot be
> stored. For reading the conf, a reasonable default behavior is to return
> the default config file.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/350#issuecomment-110922626.
> 
> To clarify this, the config is not meant to be written back to file on
> exit. The current implementation is pretty failsafe. If the default
> directory in home directoy is not accessible it already fall back to a
> shipped default config (which is by the way documented in sphinx).

I was not aware of parallel environments, in which files are being locked.

The PR #350 makes the failures non-fatal and a warning is being shown.

BTW the config system is not a dinosaur from ancient times, but evolved
during time and is now used to configure the logging system,
progressbars, runtime behavior etc.

**Comment by franknoe** [comment]
OK thanks! I was under the impression writing config files was only 
necessary in conjunction with JVM. Anyway, we can discuss it next week.

Am 11/06/15 um 03:55 schrieb Martin K. Scherer:

> Am 11.06.2015 um 07:40 schrieb Frank Noe:
> 
> > @marscher https://github.com/marscher although I don't completely
> > understand the source of this problem I vote for making config.py
> > failsafe. There is no reason why we need to test for every import
> > whether the file is writable and raise an exception if not. Only if it
> > is not writeable but we actually try to set a config value that would be
> > a problem, and that could generate a warning if the setting cannot be
> > stored. For reading the conf, a reasonable default behavior is to return
> > the default config file.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/markovmodel/PyEMMA/issues/350#issuecomment-110922626.
> > 
> > To clarify this, the config is not meant to be written back to file on
> > exit. The current implementation is pretty failsafe. If the default
> > directory in home directoy is not accessible it already fall back to a
> > shipped default config (which is by the way documented in sphinx).
> 
> I was not aware of parallel environments, in which files are being locked.
> 
> The PR #350 makes the failures non-fatal and a warning is being shown.
> 
> BTW the config system is not a dinosaur from ancient times, but evolved
> during time and is now used to configure the logging system,
> progressbars, runtime behavior etc.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/350#issuecomment-110967556.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by euhruska** [comment]
Is pyemma  actually intended to run parallel, with multithreading?

**Comment by franknoe** [comment]
We do use python-based multiprocessing (multiple cores in one CPU), 
because a lot of algorithms benefit from trivial parallelization - but 
in practice parallel support is not yet found in many parts of the code.

We do not use things like MPI.

Am 13/06/15 um 07:30 schrieb euhruska:

> Is pyemma actually intended to run parallel, with multithreading?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/350#issuecomment-111673897.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
