### ISSUE TITLE
simplify pyemma.coordinates.tests.test_stride.TestStride 

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#353]
This test takes very long and clutters the test output. I'm sure it can be simplified.

**Comment by fabian-paul** [comment]
I would like to fix this but I don't know how. 
Is it possible to temporarily suppress displaying of the progress bar and log messages? 
I would like to write something like:

``` Python
with no_logging:
   t = tica(...)
   ...
```

Speeding up the test is easily done by reducing the range of strides that the function tests and by reducing the dimensions of the test data. 
Optimally, I would like to fix both issues in one PR.

**Comment by franknoe** [comment]
Am 12/06/15 um 10:33 schrieb fabian-paul:

> I would like to fix this but I don't know how.
> 
> I understood the problem. Sorry, this is from me, I was under the 
> impression it might have been one of your tests.
> The reason is that the test computes the wrong reference value by not 
> symmetrizing C(tau).
> 
> Is it possible to temporarily suppress displaying of the progress bar 
> and log messages?
> 
> I'm sure it is, but Martin or Moritz need to tell us how.
> 
> I would like to write something like:
> 
> with  no_logging:
>     t=  tica(...)
>     ...
> 
> Speeding up the test is easily done by reducing the range of strides 
> that the function tests and by reducing the dimensions of the test data.
> Optimally, I would like to fix both issues in one PR.
> 
> OK
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/353#issuecomment-111413343.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by clonker** [comment]
It is a config value

```
show_progress_bars = True
```

so setting this to False should disable the progress bars. If it is desired to disable them runtime-temporarily, try something like this:

``` python
from pyemma.util.config import conf_values

# to disable
conf_values['pyemma'].show_progress_bars = 'False'
# to enable
conf_values['pyemma'].show_progress_bars = 'True'
```

**Comment by franknoe** [comment]
I'm a bit confused with these config values. As far as I understand the 
config values are quasi-permanent, i.e. they are set for a certain user 
(in a config file), and then every time I set their value, I change the 
config file. Right?

I'm not sure this is desirable for progress bars. I would say the 
default behavior of progress bars should depends on the context in which 
I use the algorithms.
Since pyemma is a library I guess there should be by default no progress 
bar (e.g. running a python script on a server) but just logging. If I 
use pyemma in an interactive mode (ipython notebook or command line 
tools that we currently don't have), showing progress bars is a 
reasonable default. So that would mean:
- if pyemma is called from ipython (this can be checked I guess), show 
  he progress bar by default.
- if we build command line tools, we will have to switch progress bars 
  on by default.
- the user can always choose to force them switched on or off at runtime.

With this in mind it makes no sense to me to have this setting a config 
values. Imagine I am working on two notebooks at the same time, and in 
one notebook I decide to switch them off, then they would also be 
switched off in the other notebook. That's weird.

So, what do we need file-based config values for anyway? Same for 
logging. Why not just set a few global package variables, which are 
valid for the current instance and otherwise default. Somewhere in the 
config code it claims that is the more clean why of doing this, but I 
honestly don't see why. It's more a question of whether a config 
variable is a user or a session variable.

Am 12/06/15 um 14:50 schrieb Moritz Hoffmann:

> It is a config value
> 
> |show_progress_bars = True
> |
> 
> so setting this to False should disable the progress bars. If it is 
> desired to disable them runtime-temporarily, try something like this:
> 
> from  pyemma.util.configimport  conf_values
> 
> # to disable
> 
> conf_values['pyemma'].show_progress_bars=  'False'
> 
> # to enable
> 
> conf_values['pyemma'].show_progress_bars=  'True'
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/353#issuecomment-111480319.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
I agree with Frank, progress bars make only sense in an interactive session, like an ipython notebook or `istty()` is true. 
Additionally we need fine-grained control over the progress bars. Say you program some algorithm that uses many get_output and tica passes. Even though the user interaction might be interactive, you don't want to display tens or hundreds of progress bars. So I think by default, progress bars should be off. 
Maybe the concept of the "user API" can help us thinking about the uses cases:
If the user API was called, this would indicate that the user is using the functions interactively and directly. (That means that she/he didn't program a code that uses the pipeline only deeply within the guts of her/his code.) Then it would be adequate to show progress bars and logging info.
In contrast, if some code bypasses the user API this would indicate that the programmer is building something complex and that the programmer is now responsible for generating sensible status messages for the user.

**Comment by fabian-paul** [comment]
The speed issue is fixed in  PR #357.

**Comment by marscher** [comment]
Am 12.06.2015 um 15:27 schrieb Frank Noe:

> I'm a bit confused with these config values. As far as I understand the
> config values are quasi-permanent, i.e. they are set for a certain user
> (in a config file), and then every time I set their value, I change the
> config file. Right?
> No, you dont change the file. The values are indeed quasi permanent, you 
> can change them during runtime but if they are not manually written to 
> config file their value is lost.
> 
> I'm not sure this is desirable for progress bars. I would say the
> default behavior of progress bars should depends on the context in which
> I use the algorithms.
> Since pyemma is a library I guess there should be by default no progress
> bar (e.g. running a python script on a server) but just logging. If I
> use pyemma in an interactive mode (ipython notebook or command line
> tools that we currently don't have), showing progress bars is a
> reasonable default. So that would mean:
> - if pyemma is called from ipython (this can be checked I guess), show
>   he progress bar by default.
>   That sounds reasonable.
> - if we build command line tools, we will have to switch progress bars
>   on by default.
> - the user can always choose to force them switched on or off at runtime.
> 
> With this in mind it makes no sense to me to have this setting a config
> values. Imagine I am working on two notebooks at the same time, and in
> one notebook I decide to switch them off, then they would also be
> switched off in the other notebook. That's weird.
> You can still switch them off in the other notebook by not changing the 
> config file, but setting it directly in the other notebook as a runtime 
> setting (for which a config setting is definitely required).
> 
> So, what do we need file-based config values for anyway? Same for
> logging. Why not just set a few global package variables, which are
> valid for the current instance and otherwise default. Somewhere in the
> config code it claims that is the more clean why of doing this, but I
> honestly don't see why.
> Having the config values as plain variables in a module is the most 
> naive solution and I think it is not handy for running on a remote 
> system, where I want to setup such things globally instead of changing 
> them in every script I use.
> 
> It's more a question of whether a config
> variable is a user or a session variable.

It can be both. Thats even more flexible (but even more confusing to 
some people).

**Comment by franknoe** [comment]
I would probably prefer to have progress bars on by default in ipython 
but have an easy control over them. But we can discuss this.
There's is a similar issue with not cluttering the notebook with logging.

So what about the following:
- keep the config file to define defaults
- read their values at import time to set package variables (e.g. 
  pyemma.progressbar = True/False/'Auto', pyemma.logging = 
  True/False/'Auto' or use log level here)

It's then fairly straightforward to control:

``` python
import pyemma
pyemma.progressbar = False
```

It's a visualization setting just like %pylab inline. We can show this 
in various ipython examples, so it should be easy to pick up.

Am 15/06/15 um 11:43 schrieb fabian-paul:

> I agree with Frank, progress bars make only sense in an interactive 
> session, like an ipython notebook or |istty()| is true.
> Additionally we need fine-grained control over the progress bars. Say 
> you program some algorithm that uses many get_output and tica passes. 
> Even though the user interaction might be interactive, you don't want 
> to display tens or hundreds of progress bars. So I think by default, 
> progress bars should be off.
> Maybe the concept of the "user API" can help us thinking about the 
> uses cases:
> If the user API was called, this would indicate that the user is using 
> the functions interactively and directly. (That means that she/he 
> didn't program a code that uses the pipeline only deeply within the 
> guts of her/his code.) Then it would be adequate to show progress bars 
> and logging info.
> In contrast, if some code bypasses the user API this would indicate 
> that the programmer is building something complex and that the 
> programmer is now responsible for generating sensible status messages 
> for the user.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/353#issuecomment-111999506.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 15.06.2015 um 15:17 schrieb Frank Noe:

> I would probably prefer to have progress bars on by default in ipython
> but have an easy control over them. But we can discuss this.
> There's is a similar issue with not cluttering the notebook with logging.
> 
> So what about the following:
> - keep the config file to define defaults
> - read their values at import time to set package variables (e.g.
>   pyemma.progressbar = True/False/'Auto', pyemma.logging =
>   True/False/'Auto' or use log level here)
> 
> It's then fairly straightforward to control:
> 
> ``` python
> import pyemma
> pyemma.progressbar = False
> ```
> 
> The way you've described here, is already implemented. Only the setting
> of the trigger is a bit different.
> 
> ``` python
> pyemma.util.config.conf_values.pyemma.show_progress_bars = False
> ```

Can you please explain what you mean by the auto setting?

Maybe we should create a shortcut for that (eg. the dictionary for the
config values and document it properly).

**Comment by franknoe** [comment]
Ah, so I just got things wrong then. So it's just about making the 
access easier (as below), and changing the default behavior.
I suggest default behavior is to decide progress-bars are shown 
depending on the context (automatically), i.e. on in ipython, off elswhere.
For the logging we should think about how to make it non-redundant with 
progress-bars. If there are progress bars I don't want much of the 
logging (I can show you examples where 1 page of output is produced for 
algorithms that run rather fast). The logging level could be set 
automatically (less in ipython). Perhaps you can discuss this is bit in 
person and suggest a solution.

Am 15/06/15 um 15:25 schrieb Martin K. Scherer:

> Am 15.06.2015 um 15:17 schrieb Frank Noe:
> 
> > I would probably prefer to have progress bars on by default in ipython
> > but have an easy control over them. But we can discuss this.
> > There's is a similar issue with not cluttering the notebook with 
> > logging.
> > 
> > So what about the following:
> > - keep the config file to define defaults
> > - read their values at import time to set package variables (e.g.
> >   pyemma.progressbar = True/False/'Auto', pyemma.logging =
> >   True/False/'Auto' or use log level here)
> > 
> > It's then fairly straightforward to control:
> > 
> > ``` python
> > import pyemma
> > pyemma.progressbar = False
> > ```
> > 
> > The way you've described here, is already implemented. Only the setting
> > of the trigger is a bit different.
> > 
> > ``` python
> > pyemma.util.config.conf_values.pyemma.show_progress_bars = False
> > ```
> 
> Can you please explain what you mean by the auto setting?
> 
> Maybe we should create a shortcut for that (eg. the dictionary for the
> config values and document it properly).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/353#issuecomment-112069384.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 15.06.2015 um 15:32 schrieb Frank Noe:

> Ah, so I just got things wrong then. So it's just about making the
> access easier (as below), and changing the default behavior.
> I suggest default behavior is to decide progress-bars are shown
> depending on the context (automatically), i.e. on in ipython, off elswhere.
> This is now the case in PR #360.
> 
> For the logging we should think about how to make it non-redundant with
> progress-bars. If there are progress bars I don't want much of the
> logging (I can show you examples where 1 page of output is produced for
> algorithms that run rather fast). The logging level could be set
> automatically (less in ipython). Perhaps you can discuss this is bit in
> person and suggest a solution.

The log level is INFO at the moment, we should either consider lowering
the log level of messages like ("stuff is being computed") to DEBUG or
increase the level to ERROR in ipython notebook (which can be easily done).

**Comment by franknoe** [comment]
Am 15/06/15 um 15:41 schrieb Martin K. Scherer:

> Am 15.06.2015 um 15:32 schrieb Frank Noe:
> 
> > Ah, so I just got things wrong then. So it's just about making the
> > access easier (as below), and changing the default behavior.
> > I suggest default behavior is to decide progress-bars are shown
> > depending on the context (automatically), i.e. on in ipython, off 
> > elswhere.
> > This is now the case in PR #360.
> > OK, thanks! But in addition one should have a control to force the 
> > progress bars on or off.
> > 
> > For the logging we should think about how to make it non-redundant with
> > progress-bars. If there are progress bars I don't want much of the
> > logging (I can show you examples where 1 page of output is produced for
> > algorithms that run rather fast). The logging level could be set
> > automatically (less in ipython). Perhaps you can discuss this is bit in
> > person and suggest a solution.
> 
> The log level is INFO at the moment, we should either consider lowering
> the log level of messages like ("stuff is being computed") to DEBUG or
> increase the level to ERROR in ipython notebook (which can be easily 
> done).
> I agree. Some of the current INFO messages are actually DEBUG. For 
> example when computing TICA we get two progress bars for mean + Cov 
> computation. Then we want max. 1 more message that Eigenvalues are being 
> solved to understand why we are still waiting for the result.
> As a guidance, I would only show messages when there are considerable 
> waiting times or real Warnings.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/353#issuecomment-112074018.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
> OK, thanks! But in addition one should have a control to force the
> progress bars on or off.
> if you set the config value to True/False you can force control it, but
> only if the display is appropriate for showing them (ipynb or tty).

**Comment by franknoe** [comment]
Am 15/06/15 um 16:44 schrieb Martin K. Scherer:

> > OK, thanks! But in addition one should have a control to force the
> > progress bars on or off.
> > if you set the config value to True/False you can force control it, 
> > Yes, but we need a _simple_ way to do that such as pyemma.progressbars = 
> > False.
> > but
> > only if the display is appropriate for showing them (ipynb or tty).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/353#issuecomment-112094016.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
this has been fixed in dev_release_1.3
