### ISSUE TITLE
test_networks.TestNetworkPlot plots

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#354]
The test

test_networks.TestNetworkPlot

actually plots a figure during the test run. I'm sure that's not desired.

**Comment by marscher** [comment]
There seems no good possibility to switch the backend of matplotlib after it has been imported. The backend should be headless, so no GUI will popup during testing. But I would strongly recommend to test plots at least for exception safety (NetworkPlot eg had tons of failures due to wrong imports of grandalf library).

**Comment by franknoe** [comment]
We could do the following: use an option draw=True which triggers the 
plt.show() in the plotting function. In the test, use the plotting 
function with draw=False.

Grandalf-wise: I would be happy to switch to networkx if that's a better 
option. But I think this is more a cosmetic and could be moved until 
after the release that we use for the paper.

Am 15/06/15 um 12:51 schrieb Martin K. Scherer:

> There seems no good possibility to switch the backend of matplotlib 
> after it has been imported. The backend should be headless, so no GUI 
> will popup during testing. But I would strongly recommend to test 
> plots at least for exception safety (NetworkPlot eg had tons of 
> failures due to wrong imports of grandalf library).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/354#issuecomment-112016914.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 15.06.2015 um 14:48 schrieb Frank Noe:

> We could do the following: use an option draw=True which triggers the
> plt.show() in the plotting function. In the test, use the plotting
> function with draw=False.

Thats a good idea! In principle do we always return an Axes object or do
we always call show in our plot functions? I'm not sure if that is
consistently done in all of them.

If we always return the Axes or Figure object it is up to user what he
will do with it (and he also be able to modify it).

**Comment by franknoe** [comment]
Am 15/06/15 um 14:53 schrieb Martin K. Scherer:

> Am 15.06.2015 um 14:48 schrieb Frank Noe:
> 
> > We could do the following: use an option draw=True which triggers the
> > plt.show() in the plotting function. In the test, use the plotting
> > function with draw=False.
> 
> Thats a good idea! In principle do we always return an Axes object or do
> we always call show in our plot functions? I'm not sure if that is
> consistently done in all of them.
> It's probably not consistent. The plotting package is so rudimentary, 
> that I am not yet sure what consistent means.
> 
> If we always return the Axes or Figure object it is up to user what he
> will do with it (and he also be able to modify it).
> Always returning an Axes object sounds reasonable. But one could also 
> return a Figure object (I think the main differences are that a Figure 
> can contain multiple Axes, and a Figure has a size) in some cases. I am 
> not sure if we can find a general behavior here. I guess as long as by 
> default the figure is drawn the user won't worry about it too much at 
> this point and we can still change the output behavior.

In any case (even if the show() is triggered within the function and the 
Axes/Figures is not returned, the user can still modify the look of the 
plot by e.g. setting xlim(), semilogy(), axis ticks and labels etc. 
afterwards.

> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/354#issuecomment-112057564.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
