### ISSUE TITLE
Sparse reversible transition matrix MLE (C-extension) needs to work with float counts

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#356]
The C-extension for sparse reversible transition matrix maximum-likelihood estimation doesn’t work with fractional counts (raises an exception like 'stationary distribution is zero or none'). I think this goes through because the array is cast into integers (of type long), which probably rounds things such that connectivity is lost.

Anyway, we need the transition matrix estimation to work with floating-point counts. So use double or float (in principle float is probably sufficient)

**Comment by fabian-paul** [comment]
fix proposed in PR  #359

**Comment by franknoe** [comment]
Thanks Fabian
