### ISSUE TITLE
prepare for HMM package merge

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#364]
In the branch add_hmm_package I am using a dependency on the bhmm package. I am planning to prepare a PR in the near future, but we need to ensure that bhmm is installable, i.e. the dependencies are correctly resolved using either conda or pip. Please have a look and prepare for that.

Don't do any merges yet. I am still working on the HMM integration code.

**Comment by marscher** [comment]
we can use the same infrastructre as for pyemma. Do you have a conda recipe yet?

**Comment by franknoe** [comment]
I think John did that on omnia - bhmm is already there. But nothing is 
done yet for the pip version.

Am 16/06/15 um 14:28 schrieb Martin K. Scherer:

> we can use the same infrastructre as for pyemma. Do you have a conda 
> recipe yet?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/364#issuecomment-112408043.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
If the conda recipe is working so your setup.py script does and it is trivial to set it up for pypi, since it is automatized for pyemma release process already.

**Comment by marscher** [comment]
Actually we do not have to change anything in pyemma, so I will close this now and lets continue the progress in the bhmm repo

**Comment by franknoe** [comment]
Right now no. We just have to add the dependency to bhmm to use it. I'll 
try to do that in the add_hmm_package branch

Am 16/06/15 um 15:18 schrieb Martin K. Scherer:

> Actually we do not have to change anything in pyemma, so I will close 
> this now and lets continue the progress in the bhmm repo
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/364#issuecomment-112425159.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
For conda you should be fine, but pypi related things will definitely
fail on your branch then, which might be annoying if travis depends on
it and all your further pull requests will also fail.
