### ISSUE TITLE
Use eigh for reversible matrix decomposition

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#374]
In msm.analysis.(dense/sparse).decomposition, we have successfully used the reversible-option in eigenvalues in order to quickly compute eigenvalues of reversible matrices. Extend this functionality to eigenvector and RDL decomposition. The right/left eigenvectors can be computed from the eigenvectors of the symmetrized matrix by multiplying them by 1/sqrt(pi) or sqrt(pi), respectively.

**Comment by marscher** [comment]
This issue was moved to markovmodel/msmtools#6

**Comment by marscher** [comment]
This issue was moved to markovmodel/msmtools#8
