### ISSUE TITLE
consider using an automatic changelog generator

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#375]
https://skywinder.github.io/github-changelog-generator/ looks like a nice tool.

It generates a summary of all fixed issues and pull requests with links to the github history.

**Comment by marscher** [comment]
this tool works actually pretty well! See https://github.com/markovmodel/msmtools/blob/devel/CHANGELOG.md

I'd like to use it for pyemma too (or at least have a dev_changelog and a user changelog, by generating the first one and summarising manually the second.)

**Comment by marscher** [comment]
for pyemma it hits the maximum allowed github api calls per hour (because the changelog was too big)

**Comment by franknoe** [comment]
We can use it for the full changelog. We'd still need to write something 
for the majority of users that want a digest.

Am 14/07/15 um 20:31 schrieb Martin K. Scherer:

> this tool works actually pretty well! See 
> https://github.com/markovmodel/msmtools/blob/devel/CHANGELOG.md
> 
> I'd like to use it for pyemma too (or at least have a dev_changelog 
> and a user changelog, by generating the first one and summarising 
> manually the second.)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/375#issuecomment-121332761.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
