### ISSUE TITLE
estimate_param_scan doctest broken

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#394]
```
      File "<doctest pyemma._base.estimator.estimate_param_scan[4]>", line 1, in <module>
        estimate_param_scan(MaximumLikelihoodMSM, dtraj, param_sets, evaluate=['timescales', 'timescales_samples'])
      File "/home/marscher/workspace/pyemma/pyemma/_base/estimator.py", line 175, in estimate_param_scan
        params = param_sets[i]
    TypeError: 'ParameterGrid' object does not support indexing
```

**Comment by franknoe** [comment]
I see. This is not a list but some sklearn object. You can do

param_sets = list(param-sets)

inside estimate_param_scan to fix it.

Am 07/07/15 um 15:45 schrieb Martin K. Scherer:

> |       File "<doctest pyemma._base.estimator.estimate_param_scan[4]>", line 1, in <module>
>          estimate_param_scan(MaximumLikelihoodMSM, dtraj, param_sets, evaluate=['timescales', 'timescales_samples'])
>        File "/home/marscher/workspace/pyemma/pyemma/_base/estimator.py", line 175, in estimate_param_scan
>          params = param_sets[i]
>      TypeError: 'ParameterGrid' object does not support indexing
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/394.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
okay, fixed that. Now we've got:

```
      File "<doctest pyemma._base.estimator.estimate_param_scan[4]>", line 1, in <module>
        estimate_param_scan(MaximumLikelihoodMSM, dtraj, param_sets, evaluate=['timescales', 'timescales_samples'])
      File "/home/marscher/workspace/pyemma/pyemma/_base/estimator.py", line 196, in estimate_param_scan
        raise e  # raise an AttributeError
    AttributeError: 'MaximumLikelihoodMSM' object has no attribute 'timescales_samples'
```

**Comment by franknoe** [comment]
I'm not sure which branch you are referring to? the PR?

How do I run the doctests locally? It's not efficient to debug over github. Currently I always run `python setup.py test` that doesn't trigger doctests I think.

**Comment by marscher** [comment]
Am 09.07.2015 um 15:05 schrieb Frank Noe:

> I'm not sure which branch you are referring to? the PR?
> Yes, it affects the refactor_model_estimator branch.
> 
> How do I run the doctests locally? It's not efficient to debug over
> github. Currently I always run |python setup.py test| that doesn't
> trigger doctests I think.
> nosetests --with-doctests ...

The doctests are currently not enabled globally, since there are several
failures at the moment (most of them are caused by missing imports and
too fine-grained result checking).

**Comment by franknoe** [comment]
We either need a way to run this locally in order to do the debugging interactively or we'll ignore doctest failures for now. I don't have time to do debugging this way because every iteration takes at least minutes.

This failure is because 'timescales_samples' doesn't exist anymore.

**Comment by marscher** [comment]
In pydev one can enable doctesting within unittest, don't know how to
achieve this in Pycharm (but it should be possible).

How do one now obtain the sampled timescales? Or is this example obsolete?

**Comment by franknoe** [comment]
Am 09/07/15 um 15:23 schrieb Martin K. Scherer:

> In pydev one can enable doctesting within unittest, don't know how to
> achieve this in Pycharm (but it should be possible).
> I didn't mean Pycharm or anything IDE-specific but just how to do it on 
> the command line. I can run
>      nosetests --with-doctest pyemma/_base/estimator.py
> but this is only useful if I know where the problem is. In order to 
> ensure that a PR will work I need to be able to run the full test 
> locally. nosetests currently doesn't appear to be configured to do that, 
> so I cannot debug this at the moment.
> 
> How do one now obtain the sampled timescales? Or is this example obsolete?
> It still works but differently. Comment it out for now.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/394#issuecomment-119962732.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
