### ISSUE TITLE
six can be savely declared as dependency

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#396]
It is pure python and is being actively developed, so we should not import it to our source tree.

**Comment by franknoe** [comment]
I'll close this because we have discussed this in person. We'll leave six as a copy for now, because it is only used in the sklearn base module and was present as a copy there (I'm not sure if this will work with the latest six module)

**Comment by marscher** [comment]
it is also used in msmtools for py3k compatibility.
