### ISSUE TITLE
progress bar support to base for all estimators

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#400]
We'd also like to access progress bars or progress reports in the bhmm and pytram packages that should not depend on pyemma. Therefore I suggest to move progress bar support into the _base subpackage. This subpackage could be template for a future estimatorbase python package that we can separate out at a later stage. 

I suggest to make progress bar support more general and independent of actual progress bars. One way to do this is to make a base class that heavy algorithms like Estimators can derive from:

``` python
class ProgressReporter:
    def register()
        """ Registers the progress reporter """
        pass

    def update(fraction, stage=0)
        """ Updates the progress. Will update progress bars or other progress output.

        Parameters:
        ---------------
        fraction : float [0,1]
            fraction of work done in current stage
        stage : int, nonnegative, default=0
            Current stage of the algorithm, 0 or greater

        """
        pass

    @property
    def progress()
        """ Reports the progress

        Returns
        -----------
        p : progress (float)
        """
        pass

    @property
    def stage()
        """ Reports the stage

        Returns
        -----------
        s : stage (int)
```

With such a convention, an object deriving from ProgressReporter can report its progress. Progress bars can be requested / attached and configured from the outside (not by the object itself).

**Comment by marscher** [comment]
_base can be a git submodule/subtree shared by all projects, containing commonly shared code. I really encourage to use this pattern, otherwise you have to fix bugs in n locations, because it has just been copy pasted.

**Comment by franknoe** [comment]
Eventually yes, but certainly not now. At this point we have only a very 
rough idea what _base should be and even of the structure and API of the 
classes. In order to get to something stable that can become an package 
that we create dependencies upon we have to develop it, so it should 
stay in pyEMMA until it is sufficiently mature.

Once it is a separate package it needs a stable API, otherwise you still 
have to fix bugs in n locations plus you run into situations where the 
e.g. conda installs the newest estimatorbase package that uses new API 
that is not yet used in the package that uses the base, and you have an 
unfixable crash on the user side.

Just to reiterate my principle: _Every_ package dependency introduces 
sources of error on the user side. For me minimizing the chance of 
errors on the user side is an absolute priority. So package dependencies 
should be introduced when absolutely necessary and when the used package 
has a mature and stable API.

Am 08/07/15 um 18:29 schrieb Martin K. Scherer:

> _base can be a git submodule/subtree shared by all projects, 
> containing commonly shared code. I really encourage to use this 
> pattern, otherwise you have to fix bugs in n locations, because it has 
> just been copy pasted.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/400#issuecomment-119650994.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
If we make the reporter interface independent from the actual progressbar, every class or their users will then be responsible for instantiating and showing the progressbar. I like the idea of having an independent interface, but I have to think about on how reporting classes can easily show the progress then.

If register is called, we should register a callback function to inform the registering object about the progress made. This way it does not have to poll for changes.
