### ISSUE TITLE
Extensive Estimator/Model Tests

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#407]
- Integration Tests for ITS
- Integration Tests for Chapman-Kolmogorow
- Generalize Testing for Model and SampledModel (currently we do not test all combinations)

**Comment by franknoe** [comment]
Added integration tests for ImpliedTimescales with four estimators (MSM, Bayesian MSM, HMM, Bayesian HMM) in #410

**Comment by marscher** [comment]
Can we close this, since the PR is merged?

**Comment by franknoe** [comment]
No, I need to add more tests.

Am 14/07/15 um 20:27 schrieb Martin K. Scherer:

> Can we close this, since the PR is merged?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/407#issuecomment-121331057.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
With the automatically tested IPython notebooks I consider this OK for now.
