### ISSUE TITLE
Exclude data files from count in lines of code and contributions

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#411]
The git statistics for lines of code and contributions include data files used for testing. This makes the statistics nearly useless. Can we exclude files with specific endings such as .dat or .txt from the statistics?

**Comment by marscher** [comment]
I don't think so. Use binary files (eg .npy) if you do not want to be 
counted in sloccount (which github presumely uses).

**Comment by franknoe** [comment]
ok

Am 10/07/15 um 10:44 schrieb Martin K. Scherer:

> I don't think so. Use binary files (eg .npy) if you do not want to be
> counted in sloccount (which github presumely uses).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/411#issuecomment-120302818.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Actually there is a way:
https://github.com/github/linguist#overrides

By putting some of those paths (eg. external) to .gitattributes file:

_external_ linguist-vendored

everything which matches "_external_" will be marked as vendored (e.g) 
generated or library code.

But who wants to maintain this stuff? We have to make sure for every 
pull request, people are not "cheating".

**Comment by franknoe** [comment]
what's to maintain? Can we not simply put *.dat, *.pyc and *.txt there 
to avoid non-code to be counted in the stats?

I'm not worried about cheating, but the statistics can be very 
misleading if large test files are counted.

Am 10/07/15 um 10:53 schrieb Martin K. Scherer:

> Actually there is a way:
> https://github.com/github/linguist#overrides
> 
> By putting some of those paths (eg. external) to .gitattributes file:
> 
> _external_ linguist-vendored
> 
> everything which matches "_external_" will be marked as vendored (e.g)
> generated or library code.
> 
> But who wants to maintain this stuff? We have to make sure for every
> pull request, people are not "cheating".
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/411#issuecomment-120304634.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 10.07.2015 um 10:56 schrieb Frank Noe:

> what's to maintain? Can we not simply put *.dat, *.pyc and *.txt there
> to avoid non-code to be counted in the stats?

*.pyc files are not being maintained in the repo anyway.

I'm not sure, if this not only excludes the file from the language 
statistic but from the lines a user contributed to the project. Most 
likely only the first applies.

**Comment by janosh** [comment]
There's a related discussion over at https://github.com/github/linguist/discussions/5164. Tl;dr from that: it's not possible to exclude test files from line changes since as @marscher suspected, the number GH displays comes directly from `git diff`.

If someone knows a way to tell `git` to ignore certain files when counting which also translates to GH, please share.
