### ISSUE TITLE
ReactiveFlux: msmtools vs pyEMMA

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#416]
I suggest the following separation for the flux / ReactiveFlux stuff between msmtools and pyEMMA (currently that's all in msmtools):
1. move `msmtools/flux/reactive_flux.py` to `pyemma/msm/model`
2. move the function `tpt` in `msmtools/flux/api.py` to `pyemma/msm/api.py`
3. move `msmtools/flux/reactive_flux_test.py` to `pyemma/msm/test`

In short, msmtools retains the low-level flux calculation stuff (i.e. committor calculations etc), and the object goes to pyEMMA. In a second step, the ReactiveFlux would become a real pyEMMA Model (i.e. a few extra functionalities would be added), but I can take it from there.

@trendelkampschroer and @marscher  what do you think?

**Comment by marscher** [comment]
That pattern fits perfectly into the new model/estimator thing. But the same thing would then apply for TPT and in my opinion these objects are handy and makes it more usable. TPT is even used in the impl of the low-level API functions, so we should leave it alone and maybe just derive it in pyemma.models somehow. This would then not brake the API again.

**Comment by franknoe** [comment]
Not needed for 2.0. I'll look into this again and maybe include it in the next release.
