### ISSUE TITLE
Make pyemma.util.discrete_trajectories a subpackage of msmtools

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#417]
pyemma.util.discrete_trajectories contains various tools for discrete trajectories (counting, histogramming, sampling indexes, I/O). I suggest to make this the api of a new msmtools subpackage, e.g. named `dtraj`. 

There are other functionalities that we may want to move there, such as `msmtools.estimate.count_states` and `msmtools.estimate.number_of_states`.

**Comment by marscher** [comment]
done and released
