### ISSUE TITLE
Clean up pyemma.msm.util.mapping

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#418]
`pyemma.msm.util.mapping` is in part deprecated and in other parts probably not at the right place. I think the whole module can be removed from pyEMMA, but let's see:
- `from_lcc_labels` and `to_lcc_labels`: Seems to be something that is (or should be) part of the msm object. Anyway these functions are one-lines, so do we need them? Maybe part of msmtools?
- `regroup_RAM` and `PCCA_disctrajs` are deprecated and can be removed in the next release.
- `regroup_DISK` should definitely not be in the msm package, but in some coordinate package utility module.

So I propose to:
1. Anyone familiar with `regroup_DISK` to suggest a new home in coordinates and put it there.
2. I'm currently rebasing the Chapman-Kolmogorow Test onto the new Estimator structure. This will avoid using the `_lcc_labels` functions.
3. Once 1. and 2. are done we can remove the module.

OK?

**Comment by marscher** [comment]
agreed. I think regroup_DISK has been written by @fabian-paul for the first workshop. I think we should move into coordinates.util

**Comment by fabian-paul** [comment]
regroup_DISK is superseded by  pyemma.coordinates.save_trajs. I think I made the mistake of not labeling it as deprecated. The function should be removed in the future. Sorry for the confusion.  regroup_RAM and PCCA_disctrajs are already marked as deprecated and can be removed.

**Comment by franknoe** [comment]
Then the entire module can now be removed. I will do this and include it 
in my latest PR.

Am 17/07/15 um 10:11 schrieb fabian-paul:

> regroup_DISK is superseded by pyemma.coordinates.save_trajs. I think I 
> made the mistake of not labeling it as deprecated. The function should 
> be removed in the future. Sorry for the confusion. regroup_RAM and 
> PCCA_disctrajs are already marked as deprecated and can be removed.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/418#issuecomment-122212047.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
