### ISSUE TITLE
1.3 -> py3 compatible?

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#419]
... wouldn't that be nice?
I think bhmm needs to be compatible too then.

**Comment by franknoe** [comment]
Yes. Let's start with bhmm.

Am 14/07/15 um 20:20 schrieb Martin K. Scherer:

> ... wouldn't that be nice?
> I think bhmm needs to be compatible too then.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/419.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
bhmm is py3k compatible for now. Starting with pyemma

**Comment by marscher** [comment]
almost done. Python3 complains that mdtraj.Topology is not hashable, but is should be...
