### ISSUE TITLE
first pyEMMA import is slow

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#420]
The first pyEMMA import in a given python interpreter is rather slow. Any idea why, and can we change that?

**Comment by marscher** [comment]
I also noticed that quite some time ago and tried to investigate it.

msmtools takes 0.5s, if the files are cached, 2.5s otherwise. I've heard 
that using binary python package formats (egg) are at least shipping 
around the io bounded problem, but compiled extensions has to be 
extracted for that. Setuptools provides transparent support for that, it 
might worth trying it out.

On the other hand we can try to minimize the heavy imports like 
matplotlib (why should we import it, if the user is not going to plot 
something. He/she will then wait a little period, if we do the import 
locally during a plot function call). This will save another 0.5s.

mdtraj takes 1.2s uncached. We might also consider using it with lazy 
import (eg. a featurizer can hold the instance to the module).

It is also worth noting that improving this performance has no impact on 
multiprocessing subprocess spawning time, since the process memory is 
being copied to the forked process image.

disclaimer: the timings given here are from a network filesystem (which 
will most likely gain most of the binary package option, since only one 
file has to be transfered to the local system). On a ssd of course this 
does not have such an impact.

**Comment by marscher** [comment]
quote from setuptools documentation:

You can pass a True or False value for the zip_safe argument to the 
setup() function, or you can omit it. If you omit it, the bdist_egg 
command will analyze your project’s contents to see if it can detect any 
conditions that would prevent it from working in a zipfile. It will 
output notices to the console about any such conditions that it finds.

Currently, this analysis is extremely conservative: it will consider the 
project unsafe if it contains any C extensions or datafiles whatsoever. 
This does not mean that the project can’t or won’t work as a zipfile! It 
just means that the bdist_egg authors aren’t yet comfortable asserting 
that the project will work. If the project contains no C or data files, 
and does no **file** or **path** introspection or source code 
manipulation, then there is an extremely solid chance the project will 
work when installed as a zipfile. (And if the project uses pkg_resources 
for all its data file access, then C extensions and other data files 
shouldn’t be a problem at all. See the Accessing Data Files at Runtime 
section above for more information.)

**Comment by franknoe** [comment]
On my mac it's probably a bit faster, but notably slow. It would be good 
if we can speed this up, because people are getting worried when they 
try to import and nothing moves for a while.

Does this problem also occur with the conda install?

Importing mdtraj and matplotlib on demand seems like a good idea, 
because we are only using these in a few places. But we can't do that 
for msmtools which is used in almost all modules of the msm package, so 
we should find another solution for that.

This is not super-high priority but would be nice to have.

Am 15/07/15 um 01:26 schrieb Martin K. Scherer:

> I also noticed that quite some time ago and tried to investigate it.
> 
> msmtools takes 0.5s, if the files are cached, 2.5s otherwise. I've heard
> that using binary python package formats (egg) are at least shipping
> around the io bounded problem, but compiled extensions has to be
> extracted for that. Setuptools provides transparent support for that, it
> might worth trying it out.
> 
> On the other hand we can try to minimize the heavy imports like
> matplotlib (why should we import it, if the user is not going to plot
> something. He/she will then wait a little period, if we do the import
> locally during a plot function call). This will save another 0.5s.
> 
> mdtraj takes 1.2s uncached. We might also consider using it with lazy
> import (eg. a featurizer can hold the instance to the module).
> 
> It is also worth noting that improving this performance has no impact on
> multiprocessing subprocess spawning time, since the process memory is
> being copied to the forked process image.
> 
> disclaimer: the timings given here are from a network filesystem (which
> will most likely gain most of the binary package option, since only one
> file has to be transfered to the local system). On a ssd of course this
> does not have such an impact.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/420#issuecomment-121426383.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
I think some of the overhead stems from the fact that we have to 'lift' all api functions into their package namespace usinf from .api import \* which triggers all imports in api.py. 

So even if I do only want to use analysis.stationary_distribution the python interpreter will import almost everything located in analysis + some other functions.

**Comment by franknoe** [comment]
Not sure if I get the point. For example 'import numpy' is fast although 
numpy has a lot more functions readily imported than msmtools.

Am 15/07/15 um 09:24 schrieb Benjamin Trendelkamp-Schroer:

> I think some of the overhead stems from the fact that we have to 
> 'lift' all api functions into their package namespace usinf from .api 
> import \* which triggers all imports in api.py.
> 
> So even if I do only want to use analysis.stationary_distribution the 
> python interpreter will import almost everything located in analysis + 
> some other functions.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/420#issuecomment-121513702.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
They do not have a numpy.linalg.api.py that needs to import all the submodules in numpy.linalg.dense 
once import numpy.linalg is triggered. 

I do not know how/if this effect gets propagated to when calling import msmtools, but this could be a possible source for the import overhead.

**Comment by franknoe** [comment]
Mh, I would be surprised if that is so slow, but if it is: we don't need 
to do the imports on top of msmtools.analysis.api.py and 
msmtools.estimation.api.py. That could be done in the api functions 
using these submodules. Or we could just import the submodule functions 
that are being used.

Am 15/07/15 um 09:46 schrieb Benjamin Trendelkamp-Schroer:

> They do not have a numpy.linalg.api.py that needs to import all the 
> submodules in numpy.linalg.dense
> once import numpy.linalg is triggered.
> 
> I do not know how/if this effect gets propagated to when calling 
> import msmtools, but this could be a possible source for the import 
> overhead.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/420#issuecomment-121520064.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
import of coordinates subpackage takes another 0.4s, maybe we can reduce this, by lazily importing things.

**Comment by franknoe** [comment]
I think importing the core packages by standard makes sense, i.e.

```
import pyemma
pyemma.coordinates.tica(...)
```

should work. Or are you talking about imports inside the coordinates 
subpackage that should be made lazy?

Am 26/11/15 um 20:13 schrieb Martin K. Scherer:

> import of coordinates subpackage takes another 0.4s, maybe we can 
> reduce this, by lazily importing things.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/420#issuecomment-159978756.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Of course this has to work. The lazy import would mean to move the imports into the API functions needing those class definitions. 
At the moment we're dragging in every impl detail (implicitly) at api.py, which is not needed, because most likely the user is not calling every single api function.

**Comment by marscher** [comment]
I found and fixed a major slow down, which has been introduced via an inefficient  stack inspection in the deprecated decorator. This is still present in the latest release of msmtools, so we should also make a new release to sort this out. The necessary changes are already merged there.

**Comment by marscher** [comment]
@franknoe Shall we cut a new msmtools release for this purpose?

**Comment by franknoe** [comment]
Sure, why not.

**Comment by marscher** [comment]
with the fix in msmtools it is now much quicker to import.

**Comment by franknoe** [comment]
thanks.
