### ISSUE TITLE
coordinates.Transformer: rename map to transform

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#427]
For name consistency with sklearn (and perhaps also to improve general understandability), I suggest to rename the method map to transform(X). We can keep map for a while but deprecate it, and call transform from there.
The hidden method _map can be renamed to _transform immediately.

Note that an sklearn base Transformer doesn't have transform but just fit_transform, but it's then pretty straightforward what transform means.

**Comment by marscher** [comment]
shall we really rename it or just add a wrapper to achieve this compatibility?

**Comment by franknoe** [comment]
I think transform is a better name. Do you think we need to maintain map 
for backward compatibility, or is no-one calling map directly?

Am 28/07/15 um 18:40 schrieb Martin K. Scherer:

> shall we really rename it or just add a wrapper to achieve this 
> compatibility?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/427#issuecomment-125674724.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Yes the name is much better, but we should at least deprecate the old
method then.

**Comment by franknoe** [comment]
OK, good. Then we'll use transform(X) and _transform(x), map(X) calls 
transform(X) and delivers a deprecation warning.

Am 28/07/15 um 18:47 schrieb Martin K. Scherer:

> Yes the name is much better, but we should at least deprecate the old
> method then.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/427#issuecomment-125676400.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I will look into this tomorrow (together with sklearnization of our Transformers)
