### ISSUE TITLE
[featurizer] check for duplicate distances - worth hashing/checking individually?

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#429]
By hashing the entire lists of distances, the following redundancy is not detected:

``` python
my_FEAT = pyemma.coordinates.featurizer(ref_1U19)
my_FEAT.add_distances(contacts)
my_FEAT.add_distances(contacts[:-1])
for line in my_FEAT.describe():
    print line

# DIST: MET 0 HA 5 - ASN 1 H 20
# DIST: THR 3 N 40 - SER 21 OG 327
# DIST: THR 3 OG1 50 - SER 21 HB2 326
# DIST: MET 0 HA 5 - ASN 1 H 20
# DIST: THR 3 N 40 - SER 21 OG 327
```

I think it's already pretty cool that we check for duplicates, and I know the input is not "exactly" duplicated. 

Any interest/thoughts if it might be worth hashing/checking each "column/coordinate" separately?

**Comment by franknoe** [comment]
Of course we need to check by feature. For each basic feature type (e.g. 
distances) we need to remember which atom pairs, triples or quadruples 
have been added already. Probably that problem be generalized in a way 
that avoids writing duplicate code.

I'm not sure what the hashing does. Is it just to exclude adding 
identical feature objects twice? Maybe this can be checked initially in 
order to quickly discard an attempt of calling the same thing twice, but 
it doesn't address the aim of not having the same feature twice.

BTW, there is a "self.top" on l. 328 of featurizer.py that has no effect

Am 20/07/15 um 11:43 schrieb Guillermo Pérez-Hernández:

> By hashing the entire lists of distances, the following redundancy is 
> not detected:
> 
> my_FEAT=  pyemma.coordinates.featurizer(ref_1U19)
> my_FEAT.add_distances(contacts)
> my_FEAT.add_distances(contacts[:-1])
> for  linein  my_FEAT.describe():
>      print  line
> 
> # DIST: MET 0 HA 5 - ASN 1 H 20
> 
> # DIST: THR 3 N 40 - SER 21 OG 327
> 
> # DIST: THR 3 OG1 50 - SER 21 HB2 326
> 
> # DIST: MET 0 HA 5 - ASN 1 H 20
> 
> # DIST: THR 3 N 40 - SER 21 OG 327
> 
> I think it's already pretty cool that we check for duplicates, and I 
> know the input is not "exactly" duplicated.
> 
> Any interest/thoughts if it might be worth hasing/checking each 
> "column/coordinate" separately?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/429.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Of course we need to check by feature
So I thought.

I'm not sure what the hashing does
Right now the entire feature call is hashed, so that only features with identical calls are actually flagged as duplicates. @marscher and myself already gave some thought to this when thinking about distinguishing trajectory objects creating from loading the same file (has to do with how mdtraj hashes the object and its attribubtes natively), so we can sit down again and think about a general scheme for "deep" duplicate-checking (beyond the one for identical feature calls)

IDK where the self.top came from, I'll edit it out in the next PR of featurizer.py

Should this be in for the release?

**Comment by franknoe** [comment]
You can label it milestone 1.3. We can speak about priorities tomorrow.

Am 20/07/15 um 12:05 schrieb Guillermo Pérez-Hernández:

> Of course we need to check by feature
> So I thought.
> 
> I'm not sure what the hashing does
> Right now the entire feature call is hashed, so that only features 
> with identical calls are actually flagged as duplicates. @marscher 
> https://github.com/marscher and myself already gave some thought to 
> this when thinking about distinguishing trajectory objects creating 
> from loading the same file (has to do with how mdtraj hashes the 
> object and its attribubtes natively), so we can sit down again and 
> think about a general scheme for "deep" duplicate-checking (beyond the 
> one for identical feature calls)
> 
> IDK where the self.top came from, I'll edit it out in the next PR of 
> featurizer.py
> 
> Should this be in for the release?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/429#issuecomment-122834345.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
what we should do is merge features of the same type (eg. merge all instances of DistanceFeature) and use numpy.unique on the index array.

**Comment by marscher** [comment]
This would also minimize the Python and C calls we need to make to process the feature list.

**Comment by gph82** [comment]
+1

On 20.07.2015 18:56, Martin K. Scherer wrote:

> what we should do is merge features of the same type (eg. merge all
> instances of DistanceFeature) and use numpy.unique on the index array.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/429#issuecomment-122949654.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by franknoe** [comment]
But a distance and an inverse distance of the same pair are different 
features.

Am 20/07/15 um 18:56 schrieb Martin K. Scherer:

> what we should do is merge features of the same type (eg. merge all 
> instances of DistanceFeature) and use numpy.unique on the index array.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/429#issuecomment-122949654.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 20.07.2015 um 22:20 schrieb Frank Noe:

> But a distance and an inverse distance of the same pair are different
> features.
> sure, we have to check for the exact type of course.

**Comment by marscher** [comment]
#688 should add value ^= hash(len(self.indexes)) to catch this

**Comment by marscher** [comment]
each feature is compared individually.
