### ISSUE TITLE
coord.source function does not take a stride argument

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#430]
but it should. The load function support it and there is no reason, why we should not define a stridden reader. The only possibility is currently to use a Pipeline/Discretizer object, but it is not needed.

**Comment by gph82** [comment]
+1 ... how did I only notice this now? This is actually pretty important...can we add it to 1.3?

**Comment by franknoe** [comment]
Why source? Source only specifies the input, stride is a property of the 
algorithm, or not?
Source is different from load in this respect.

Am 21/07/15 um 15:31 schrieb Guillermo Pérez-Hernández:

> +1 ... how did I only notice this now? This is actually pretty 
> important...can we add it to 1.3?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/430#issuecomment-123304428.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
I thought of that, but if you have a feature object, and source object,
and your data is to big for load...where else would you have it?

An alternative would be when initializing the featurizer.

I know that in a sense that is what pipelines are for, but I think it is
useful to have the stride option outside the pipeline, for simple
analysis for which the pipeline is a bit of an overkill for non-expert users

On 21.07.2015 15:32, Frank Noe wrote:

> Why source? Source only specifies the input, stride is a property of the
> algorithm, or not?
> Source is different from load in this respect.
> 
> Am 21/07/15 um 15:31 schrieb Guillermo Pérez-Hernández:
> 
> > +1 ... how did I only notice this now? This is actually pretty
> > important...can we add it to 1.3?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/430#issuecomment-123304428.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/430#issuecomment-123304765.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by marscher** [comment]
Actually we decided that the data consumer (eg. tica, clusterer etc) is
responsible for requesting stridden data (because the stride argument is
being pushed backwards through the pipeline). So If the reader already
has a "static" stride argument this might lead to further confusion. I'm
not sure if it is really a good idea...

**Comment by gph82** [comment]
And i just noticed that the .get_output of the source object has this
option...

On 21.07.2015 15:39, Martin K. Scherer wrote:

> Actually we decided that the data consumer (eg. tica, clusterer etc) is
> responsible for requesting stridden data (because the stride argument is
> being pushed backwards through the pipeline). So If the reader already
> has a "static" stride argument this might lead to further confusion. I'm
> not sure if it is really a good idea...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/430#issuecomment-123307692.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by franknoe** [comment]
That's correct. The data consumer decides how to stride.

BTW, it's "strided" non "stridden"

Am 21/07/15 um 15:39 schrieb Martin K. Scherer:

> Actually we decided that the data consumer (eg. tica, clusterer etc) is
> responsible for requesting stridden data (because the stride argument is
> being pushed backwards through the pipeline). So If the reader already
> has a "static" stride argument this might lead to further confusion. I'm
> not sure if it is really a good idea...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/430#issuecomment-123307692.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I'm sorry ... stridden seems to be correct.

Am 21/07/15 um 15:39 schrieb Martin K. Scherer:

> Actually we decided that the data consumer (eg. tica, clusterer etc) is
> responsible for requesting stridden data (because the stride argument is
> being pushed backwards through the pipeline). So If the reader already
> has a "static" stride argument this might lead to further confusion. I'm
> not sure if it is really a good idea...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/430#issuecomment-123307692.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
OK, there might be weird US/UK thing going on, but as I understand it 
'stridden' is the past perfect of to stride, but strided in the word 
used in computer science:

```
 http://dictionary.reference.com/browse/strided
```

Am 21/07/15 um 15:39 schrieb Martin K. Scherer:

> Actually we decided that the data consumer (eg. tica, clusterer etc) is
> responsible for requesting stridden data (because the stride argument is
> being pushed backwards through the pipeline). So If the reader already
> has a "static" stride argument this might lead to further confusion. I'm
> not sure if it is really a good idea...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/430#issuecomment-123307692.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
interesting discussion. I'll close it, because the data consumer decides which stride it wants to use.
