### ISSUE TITLE
fix doc tests on devel and make 1.2.2 release

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#436]
If possible, also provide a way to run the doctests locally (see bhmm package - there it works)

**Comment by marscher** [comment]
most of the failing doctests are in msmtools now. I'd discourage fixing them both in separately in pyemma and msmtools.

**Comment by franknoe** [comment]
I don't understand. msmtools and pyEMMA are disjoint pieces of code. So 
why is fixing the doctests in both packages not a good idea?

Am 23/07/15 um 17:13 schrieb Martin K. Scherer:

> most of the failing doctests are in msmtools now. I'd discourage 
> fixing them both in separately in pyemma and msmtools.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/436#issuecomment-124136131.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Actually it is, but the packages already have started to diverge. For example the io package moved to dtraj in msmtools. We have to fix the doctests either in pyemma@devel or msmtools and create a patch, where we reflect the refactorings.

**Comment by franknoe** [comment]
yes, now it's clear.
