### ISSUE TITLE
[coor] does not complain about top and traj file when they are different

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#438]
I accidentally read in a topology file with solvent and trajectory files without solvent. Up to the stage of using TICA I didn't get any errors. TICA then complained with a very cryptic error. Maybe a sanity check or warning would be good here. 

```
/home/mi/ppxasjsm/Software/anaconda/lib/python2.7/site-packages/mdtraj-1.3.0-py2.7-linux-x86_64.egg/mdtraj/core/trajectory.pyc in xyz(self, value)
    809 
    810         value = ensure_type(value, np.float32, 3, 'xyz', shape=shape,
--> 811                             warn_on_cast=False, add_newaxis_on_deficient_ndim=True)
    812         self._xyz = value
    813         self._rmsd_traces = None

/home/mi/ppxasjsm/Software/anaconda/lib/python2.7/site-packages/mdtraj-1.3.0-py2.7-linux-x86_64.egg/mdtraj/utils/validation.pyc in ensure_type(val, dtype, ndim, name, length, can_be_none, shape, warn_on_cast, add_newaxis_on_deficient_ndim)
    146             if a != b:
    147                 # check for equality
--> 148                 raise error
    149 
    150     return val

ValueError: xyz must be shape (Any, 23044, 3). You supplied  (100, 103, 3)
```

**Comment by franknoe** [comment]
This is an mdtraj error. Of course the error can't be raised before one 
actually attempts to read something, and I guess that happened in your 
case when you did TICA

Am 22/07/15 um 00:38 schrieb ppxasjsm:

> I accidentally read in a topology file with solvent and trajectory 
> files without solvent. Up to the stage of using TICA I didn't get any 
> errors. TICA then complained with a very cryptic error. Maybe a sanity 
> check or warning would be good here.
> 
> |/home/mi/ppxasjsm/Software/anaconda/lib/python2.7/site-packages/mdtraj-1.3.0-py2.7-linux-x86_64.egg/mdtraj/core/trajectory.pyc in xyz(self, value)
>      809
>      810         value = ensure_type(value, np.float32, 3, 'xyz', shape=shape,
> --> 811                             warn_on_cast=False, add_newaxis_on_deficient_ndim=True)
>      812         self._xyz = value
>      813         self._rmsd_traces = None
> 
> /home/mi/ppxasjsm/Software/anaconda/lib/python2.7/site-packages/mdtraj-1.3.0-py2.7-linux-x86_64.egg/mdtraj/utils/validation.pyc in ensure_type(val, dtype, ndim, name, length, can_be_none, shape, warn_on_cast, add_newaxis_on_deficient_ndim)
>      146             if a != b:
>      147                 # check for equality
> --> 148                 raise error
>      149
>      150     return val
> 
> ValueError: xyz must be shape (Any, 23044, 3). You supplied  (100, 103, 3)
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/438.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ppxasjsm** [comment]
Maybe I misunderstood what source does then.

**Comment by franknoe** [comment]
Source just defines your input, but doesn't read anything yet. In 
principle one could try to read something at this stage.

Does anyone know if there is a way to ask mdtraj to do a sanity check on 
a trajectory/topology pair?

Am 22/07/15 um 00:45 schrieb ppxasjsm:

> Maybe I misunderstood what source does then.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/438#issuecomment-123500984.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
mdtraj checks it internally with this: 

``` python
def ensure_type(val, dtype, ndim, name, length=None, can_be_none=False, shape=None,
    warn_on_cast=True, add_newaxis_on_deficient_ndim=False):
    """Typecheck the size, shape and dtype of a numpy array, with optional
    casting."""
```

but I think we can just afford to loose 1.5 ms when initializing the source object. That value is for a molecule of ca 5K atoms in xtc format:

``` python
%%timeit
f = md.open(xtc_list[0],'r')
xyz, __, __, __ = f.read(n_frames=1)
f.close()
assert xyz.shape[1] == reftop.n_atoms, "Topology and trajectory files have to contain the same number of atoms"
# 1000 loops, best of 3: 1.44 ms per loop
```

**Comment by franknoe** [comment]
OK, so let's do that. BTW, where is the top file in your code snippet?

Am 22/07/15 um 10:29 schrieb Guillermo Pérez-Hernández:

> mdtraj checks it internally with this:
> 
> def  ensure_type(val,dtype,ndim,name,length=None,can_be_none=False,shape=None,
>      warn_on_cast=True,add_newaxis_on_deficient_ndim=False):
>      """Typecheck the size, shape and dtype of a numpy array, with optional
>      casting."""
> 
> but I think we can just afford to loose 1.5 ms when initializing of 
> the source object. That value is for a molecule of ca 5K atoms in xtc 
> format:
> 
> %%timeit
> f=  md.open(xtc_list[0],'r')
> xyz, __, __, __=  f.read(n_frames=1)
> f.close()
> assert  xyz.shape[1]==  reftop.n_atoms,"Topology and trajectory files have to contain the same number of atoms"
> 
> # 1000 loops, best of 3: 1.44 ms per loop
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/438#issuecomment-123615127.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
I did not put it, but it is loaded in the cell just above

**Comment by gph82** [comment]
I think this assertion will go best in the create_file_reader of reader_utils.py, which is the one returning the reader object in case a list of filenames was given. Anything else (=lists of arrays) do not need topology since the arrays already come formatted with n_atoms rows. Agree?

**Comment by franknoe** [comment]
If this is used in both source and load I agree.

Am 22/07/15 um 10:56 schrieb Guillermo Pérez-Hernández:

> I think this assertion will go best in the create_file_reader of 
> reader_utils.py, which is the one returning the reader object in case 
> a list of filenames was given. Anything else (=lists of arrays) do not 
> need topology since the arrays already come formatted with n_atoms 
> rows. Agree?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/438#issuecomment-123627170.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Another thing...do we want this check for every file in the list (which costs ~3secs for every 1K files), or just preemptively in the 1st file? I think just the first file is enough, since the worst case is the user is parsing trajfiles which differ in their n_atoms **among themselves**...which should be very infrequent

**Comment by franknoe** [comment]
No, just a Stichprobe

Am 22/07/15 um 11:00 schrieb Guillermo Pérez-Hernández:

> Another thing...do we want this check for every file in the list 
> (which costs ~3secs for every 1K files), or just preemptively in the 
> 1st file? I think just the first file is enough, since the worst case 
> is the user is parsing trajfiles which differ in their n_atoms _among 
> themselves_...which should be very infrequent
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/438#issuecomment-123629089.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
ok. and yes, create_file_reader is used in both load and source

**Comment by gph82** [comment]
Actually, I think it's better to have the check in FeatureReader (in coordinates.data.feature_reader.py), because create_file_reader calls FeatureReader if the parsed input is a list of MD trajfiles.

Aslo, FeatureReader is where we decide which topology to use, the one of the featurizer or the one of used when calling load/source. So I think it's better to check here
