### ISSUE TITLE
HMM error in sample_by_observation_probabilities

### ISSUE THREAD

**Issue by nsplattner** [markovmodel/PyEMMA#449]
The sample_by_observation probability function of the hidden Markov model object (obtained by estimate_hidden_markov_model) exits with a strange error. Maybe a problem with using the largest connected set? Error message details:

```
/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in sample_by_observation_probabilities(self, nsample)
    199         """
    200         import pyemma.util.discrete_trajectories as dt
--> 201         return dt.sample_indexes_by_distribution(self.observable_state_indexes, self.observation_probabilities, nsample)

/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in observable_state_indexes(self)
    172             import pyemma.util.discrete_trajectories as dt
    173 
--> 174             self._observable_state_indexes = dt.index_states(self.discrete_trajectories_obs)
    175             return self._observable_state_indexes
    176 

/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in index_states(dtrajs, subset)
    253             raise ValueError('Selected subset is not a subset of the states in dtrajs.')
    254     # histogram states
--> 255     hist = count_states(dtrajs)
    256     # efficient access to which state are accessible
    257     is_requested = np.ndarray((n), dtype=bool)

/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in count_states(dtrajs)
    169     bcs = []
    170     for i in range(len(dtrajs)):
--> 171         bc = np.bincount(dtrajs[i])
    172         nmax = max(nmax, bc.shape[0])
    173         bcs.append(bc)

ValueError: The first argument of bincount must be non-negative
```

**Comment by franknoe** [comment]
Thanks, I will check it tomorrow!

Am 27/07/15 um 14:29 schrieb nsplattner:

> The sample_by_observation probability function of the hidden Markov 
> model object (obtained by estimate_hidden_markov_model) exits with a 
> strange error. Maybe a problem with using the largest connected set? 
> Error message details:
> 
> |/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in sample_by_observation_probabilities(self, nsample)
>      199         """
>      200         import pyemma.util.discrete_trajectories as dt
> --> 201         return dt.sample_indexes_by_distribution(self.observable_state_indexes, self.observation_probabilities, nsample)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in observable_state_indexes(self)
>      172             import pyemma.util.discrete_trajectories as dt
>      173
> --> 174             self._observable_state_indexes = dt.index_states(self.discrete_trajectories_obs)
>      175             return self._observable_state_indexes
>      176
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in index_states(dtrajs, subset)
>      253             raise ValueError('Selected subset is not a subset of the states in dtrajs.')
>      254     # histogram states
> --> 255     hist = count_states(dtrajs)
>      256     # efficient access to which state are accessible
>      257     is_requested = np.ndarray((n), dtype=bool)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in count_states(dtrajs)
>      169     bcs = []
>      170     for i in range(len(dtrajs)):
> --> 171         bc = np.bincount(dtrajs[i])
>      172         nmax = max(nmax, bc.shape[0])
>      173         bcs.append(bc)
> 
> ValueError: The first argument of bincount must be non-negative
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/449.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Yep, definitely a connected set problem. I'll fix this tomorrow. Maybe 
you can try using the option "observe_active = False" for now

Am 27/07/15 um 14:29 schrieb nsplattner:

> The sample_by_observation probability function of the hidden Markov 
> model object (obtained by estimate_hidden_markov_model) exits with a 
> strange error. Maybe a problem with using the largest connected set? 
> Error message details:
> 
> |/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in sample_by_observation_probabilities(self, nsample)
>      199         """
>      200         import pyemma.util.discrete_trajectories as dt
> --> 201         return dt.sample_indexes_by_distribution(self.observable_state_indexes, self.observation_probabilities, nsample)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in observable_state_indexes(self)
>      172             import pyemma.util.discrete_trajectories as dt
>      173
> --> 174             self._observable_state_indexes = dt.index_states(self.discrete_trajectories_obs)
>      175             return self._observable_state_indexes
>      176
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in index_states(dtrajs, subset)
>      253             raise ValueError('Selected subset is not a subset of the states in dtrajs.')
>      254     # histogram states
> --> 255     hist = count_states(dtrajs)
>      256     # efficient access to which state are accessible
>      257     is_requested = np.ndarray((n), dtype=bool)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in count_states(dtrajs)
>      169     bcs = []
>      170     for i in range(len(dtrajs)):
> --> 171         bc = np.bincount(dtrajs[i])
>      172         nmax = max(nmax, bc.shape[0])
>      173         bcs.append(bc)
> 
> ValueError: The first argument of bincount must be non-negative
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/449.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I mean in the HMM estimation.

Am 27/07/15 um 14:29 schrieb nsplattner:

> The sample_by_observation probability function of the hidden Markov 
> model object (obtained by estimate_hidden_markov_model) exits with a 
> strange error. Maybe a problem with using the largest connected set? 
> Error message details:
> 
> |/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in sample_by_observation_probabilities(self, nsample)
>      199         """
>      200         import pyemma.util.discrete_trajectories as dt
> --> 201         return dt.sample_indexes_by_distribution(self.observable_state_indexes, self.observation_probabilities, nsample)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in observable_state_indexes(self)
>      172             import pyemma.util.discrete_trajectories as dt
>      173
> --> 174             self._observable_state_indexes = dt.index_states(self.discrete_trajectories_obs)
>      175             return self._observable_state_indexes
>      176
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in index_states(dtrajs, subset)
>      253             raise ValueError('Selected subset is not a subset of the states in dtrajs.')
>      254     # histogram states
> --> 255     hist = count_states(dtrajs)
>      256     # efficient access to which state are accessible
>      257     is_requested = np.ndarray((n), dtype=bool)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in count_states(dtrajs)
>      169     bcs = []
>      170     for i in range(len(dtrajs)):
> --> 171         bc = np.bincount(dtrajs[i])
>      172         nmax = max(nmax, bc.shape[0])
>      173         bcs.append(bc)
> 
> ValueError: The first argument of bincount must be non-negative
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/449.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Sorry, my last comment about using observe_active=False is probably not 
applicable to what you are doing. If you get the HMM by 
MSM.coarse_grain(), observe_active=False is currently not an option.

But anyway, I can probably fix this quickly.

Am 27/07/15 um 14:29 schrieb nsplattner:

> The sample_by_observation probability function of the hidden Markov 
> model object (obtained by estimate_hidden_markov_model) exits with a 
> strange error. Maybe a problem with using the largest connected set? 
> Error message details:
> 
> |/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in sample_by_observation_probabilities(self, nsample)
>      199         """
>      200         import pyemma.util.discrete_trajectories as dt
> --> 201         return dt.sample_indexes_by_distribution(self.observable_state_indexes, self.observation_probabilities, nsample)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in observable_state_indexes(self)
>      172             import pyemma.util.discrete_trajectories as dt
>      173
> --> 174             self._observable_state_indexes = dt.index_states(self.discrete_trajectories_obs)
>      175             return self._observable_state_indexes
>      176
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in index_states(dtrajs, subset)
>      253             raise ValueError('Selected subset is not a subset of the states in dtrajs.')
>      254     # histogram states
> --> 255     hist = count_states(dtrajs)
>      256     # efficient access to which state are accessible
>      257     is_requested = np.ndarray((n), dtype=bool)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in count_states(dtrajs)
>      169     bcs = []
>      170     for i in range(len(dtrajs)):
> --> 171         bc = np.bincount(dtrajs[i])
>      172         nmax = max(nmax, bc.shape[0])
>      173         bcs.append(bc)
> 
> ValueError: The first argument of bincount must be non-negative
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/449.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
That should be working now. Please pull again.

Am 27/07/15 um 14:29 schrieb nsplattner:

> The sample_by_observation probability function of the hidden Markov 
> model object (obtained by estimate_hidden_markov_model) exits with a 
> strange error. Maybe a problem with using the largest connected set? 
> Error message details:
> 
> |/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in sample_by_observation_probabilities(self, nsample)
>      199         """
>      200         import pyemma.util.discrete_trajectories as dt
> --> 201         return dt.sample_indexes_by_distribution(self.observable_state_indexes, self.observation_probabilities, nsample)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in observable_state_indexes(self)
>      172             import pyemma.util.discrete_trajectories as dt
>      173
> --> 174             self._observable_state_indexes = dt.index_states(self.discrete_trajectories_obs)
>      175             return self._observable_state_indexes
>      176
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in index_states(dtrajs, subset)
>      253             raise ValueError('Selected subset is not a subset of the states in dtrajs.')
>      254     # histogram states
> --> 255     hist = count_states(dtrajs)
>      256     # efficient access to which state are accessible
>      257     is_requested = np.ndarray((n), dtype=bool)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in count_states(dtrajs)
>      169     bcs = []
>      170     for i in range(len(dtrajs)):
> --> 171         bc = np.bincount(dtrajs[i])
>      172         nmax = max(nmax, bc.shape[0])
>      173         bcs.append(bc)
> 
> ValueError: The first argument of bincount must be non-negative
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/449.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by nsplattner** [comment]
There still seems to be a connected set problem. The new error message is:

```
IndexError                                Traceback (most recent call last)
<ipython-input-55-8894fb5a0d6c> in <module>()
----> 1 hmm_samples = hmm.sample_by_observation_probabilities(10)

/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in sample_by_observation_probabilities(self, nsample)
    199         """
    200         import pyemma.util.discrete_trajectories as dt
--> 201         return dt.sample_indexes_by_distribution(self.observable_state_indexes, self.observation_probabilities, nsample)

/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in observable_state_indexes(self)
    172             import pyemma.util.discrete_trajectories as dt
    173 
--> 174             self._observable_state_indexes = dt.index_states(self.discrete_trajectories_obs)
    175             return self._observable_state_indexes
    176 

/storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in index_states(dtrajs, subset)
    277             if is_requested[s]:
    278                 k = full2states[s]
--> 279                 res[k][counts[k],0] = i
    280                 res[k][counts[k],1] = t
    281                 counts[k] += 1

IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by franknoe** [comment]
OK, weird I didn't not run into this problem while testing.

Please switch to branch

```
 fix_hmm_framesampling
```

and try again. If it works, I'll do a pull request to dev_release_1.3

Am 28/07/15 um 15:26 schrieb nsplattner:

> There still seems to be a connected set problem. The new error message is:
> 
> |IndexError                                Traceback (most recent call last)
> <ipython-input-55-8894fb5a0d6c> in <module>()
> ----> 1 hmm_samples = hmm.sample_by_observation_probabilities(10)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in sample_by_observation_probabilities(self, nsample)
>      199         """
>      200         import pyemma.util.discrete_trajectories as dt
> --> 201         return dt.sample_indexes_by_distribution(self.observable_state_indexes, self.observation_probabilities, nsample)
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/msm/estimators/estimated_hmsm.pyc in observable_state_indexes(self)
>      172             import pyemma.util.discrete_trajectories as dt
>      173
> --> 174             self._observable_state_indexes = dt.index_states(self.discrete_trajectories_obs)
>      175             return self._observable_state_indexes
>      176
> 
> /storage/mi/nplattner/miniconda/envs/PyE-devR/lib/python2.7/site-packages/pyemma/util/discrete_trajectories.pyc in index_states(dtrajs, subset)
>      277             if is_requested[s]:
>      278                 k = full2states[s]
> --> 279                 res[k][counts[k],0] = i
>      280                 res[k][counts[k],1] = t
>      281                 counts[k] += 1
> 
> IndexError: index 1 is out of bounds for axis 0 with size 1
> |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/449#issuecomment-125605426.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by nsplattner** [comment]
Now it works! :-) You can merge it.

**Comment by franknoe** [comment]
thanks for reporting!

Am 28/07/15 um 17:19 schrieb nsplattner:

> Now it works! :-) You can merge it.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/449#issuecomment-125650307.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
