### ISSUE TITLE
Add support for stationary distribution for disconnected transition matrices

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#45]
Decompose into subsets, compute stationary distribution for each of them, and put them together. Scaling should be set in a well-defined way, i.e. by set size.

Although we don't know the right scaling for disconnected matrices this functionality will be useful as a guess of the stationary distribution for some algorithms.

Apply to initalization of HMMs (computation of chi from the PCCA membership matrix)

**Comment by marscher** [comment]
https://github.com/bhmm/bhmm/blob/master/bhmm/estimators/_tmatrix_disconnected.py
