### ISSUE TITLE
source archive is very large on pypi (~50mb) because of shipped ipython notebooks data

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#454]
- It would be okay, if the notebooks would be useable in an easy way (the command line interface for this has been deleted quite some time ago).
- Just for installing the software it is far too large.
- Consider having the examples as a separate package (in git it already is) and depend on pyemma and ipython-notebook (seems to be the cleanest solution).

**Comment by franknoe** [comment]
I agree that the data shouldn't be an install requirement for pyEMMA. I guess you just need some way to build the docs consistently. But even for that waiting for the ipython notebooks to complete at every docs build is not desirable, so we need to be able to turn that off.

I'm not sure about the package solution. Is it necessary or useful to have a python package for that? For the users we could just package a zip archive with the Tutorials and put it on the webpage for download.

**Comment by marscher** [comment]
The simplest way of providing an archive (containing all notebooks), is to use Github "download as archive" feature. We just need to make sure, the version matches the one used in the docs.
