### ISSUE TITLE
Featurizer: support all flexible torsions

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#456]
Currently we have phi/psi and chi1 torsions. Why only chi1? Can we do something like add all sidechain torsions?

**Comment by marscher** [comment]
We should add something like this:
https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/featurizer/featurizer.py#L265

**Comment by franknoe** [comment]
That's nice, but can we automatically get all flexible torsions of a 
sidechain from mdtraj? In principle that information should be available.

Am 27/07/15 um 20:09 schrieb Martin K. Scherer:

> We should add something like this:
> https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/featurizer/featurizer.py#L265
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/456#issuecomment-125291425.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
ping @gph82
