### ISSUE TITLE
Merge hitting problems into one module

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#46]
Proposed refactoring: Merge the three mini-modules for hitting problems

hitting_probability
mean_first_passage_time
committor

into a single module called "hitting_problems"

**Comment by marscher** [comment]
Are you considering moving all those implementations in one module or
only their corresponding API functions? The later would clean up the API
a bit. I'am voting against merging the impl (and probably their tests?),
since I do not see any advantage of mixing well clean up code.

**Comment by franknoe** [comment]
Am 27/01/15 um 21:16 schrieb Martin K. Scherer:
> Are you considering moving all those implementations in one module or
> only their corresponding API functions? The later would clean up the API
> a bit. I'am voting against merging the impl (and probably their tests?),
> since I do not see any advantage of mixing well clean up code.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/46#issuecomment-71719660>.
>
The API functions are in api, so this is only about the impl.

Why mixing? The question is what defines one module, and these three 
problems are all hitting problems, so in my opinion they belong 
together. It's arguable what should be splitted and merged, but in my 
opinion we currently have too many mini-modules.



-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
The question is what defines one module, and these three
> problems are all hitting problems, so in my opinion they belong
> together. It's arguable what should be splitted and merged, but in my
> opinion we currently have too many mini-modules.
In which way does a mini-module hurt somebody? Despite a clean 
separation of code. Think of one class per file idom of java. Are 
mini-modules harder to maintain than huge ones?

**Comment by franknoe** [comment]
Closing because we did not agree on changing it.
