### ISSUE TITLE
[tica] attributes missing in doc? 

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#460]
The following attributes
 'cov',
 'cov_tau',
 'cumvar',
 'eigenvalues',
 'eigenvectors',
 'mu',

 do not appear in any the html-doc-pages of the TICA object
http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.tica.html#pyemma.coordinates.tica
or
http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.transform.TICA.html#pyemma.coordinates.transform.TICA

**Comment by marscher** [comment]
Am 28.07.2015 um 17:14 schrieb Guillermo Pérez-Hernández:

**Comment by gph82** [comment]
ahhh...got it. Don't we want to make the user aware that these are
available somehow?

On 28.07.2015 17:27, Martin K. Scherer wrote:

> Am 28.07.2015 um 17:14 schrieb Guillermo Pérez-Hernández:
> 
> > The following attributes
> > 'cov',
> > 'cov_tau',
> > 'cumvar',
> > 'eigenvalues',
> > 'eigenvectors',
> > 'mu',
> > 
> > do not appear in any the html-doc-pages of the TICA object
> > 
> > http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.tica.html#pyemma.coordinates.tica
> > or
> > 
> > http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.transform.TICA.html#pyemma.coordinates.transform.TICA
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/460.
> > 
> > These are not properties, so they do not have a docstring currently.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/460#issuecomment-125654090.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by franknoe** [comment]
Sure. Go ahead

Am 28/07/15 um 17:29 schrieb Guillermo Pérez-Hernández:

> ahhh...got it. Don't we want to make the user aware that these are
> available somehow?
> 
> On 28.07.2015 17:27, Martin K. Scherer wrote:
> 
> > Am 28.07.2015 um 17:14 schrieb Guillermo Pérez-Hernández:
> > 
> > > The following attributes
> > > 'cov',
> > > 'cov_tau',
> > > 'cumvar',
> > > 'eigenvalues',
> > > 'eigenvectors',
> > > 'mu',
> > > 
> > > do not appear in any the html-doc-pages of the TICA object
> > 
> > http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.tica.html#pyemma.coordinates.tica
> > 
> > > or
> > 
> > http://pythonhosted.org/pyEMMA/api/generated/pyemma.coordinates.transform.TICA.html#pyemma.coordinates.transform.TICA
> > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/markovmodel/PyEMMA/issues/460.
> > > 
> > > These are not properties, so they do not have a docstring currently.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/markovmodel/PyEMMA/issues/460#issuecomment-125654090.
> 
> ## 
> 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> 
> ## http://userpage.fu-berlin.de/gph82/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/460#issuecomment-125654740.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Closed by #464
