### ISSUE TITLE
ipython notebooks still don't show up in docs

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#467]
and release still seems to be 1.2.1

http://pythonhosted.org/pyEMMA/ipython.html#msm-estimation-and-validation

Please fix asap.

Thanks

**Comment by marscher** [comment]
Am 30.07.2015 um 16:18 schrieb Frank Noe:

**Comment by marscher** [comment]
uploaded again, lets see how long it survives.

**Comment by franknoe** [comment]
Oh no. So pythonhosted doesn't remember the redirect? That's a severe 
issue, if it happens again, please contact their helpdesk.

Am 31/07/15 um 13:30 schrieb Martin K. Scherer:

> Am 30.07.2015 um 16:18 schrieb Frank Noe:
> 
> > Assigned #467 https://github.com/markovmodel/PyEMMA/issues/467 to
> > @marscher https://github.com/marscher.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/467#event-369500000.
> > 
> > Actually I blame pythonhosted.org servers, since I've fixed several days
> > ago. It is a caching issue. The docs are up to date on
> > www.emma-project.org and pythonhosted should just redirect to that. The
> > upload of the redirect index.html returned 503 http error, but did the
> > job for me for lets say 1 day. After that the old docs got replicated
> > back to previous state (for no understandable reason).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/467#issuecomment-126660115.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 31.07.2015 um 14:29 schrieb Frank Noe:

> Oh no. So pythonhosted doesn't remember the redirect? That's a severe
> issue, if it happens again, please contact their helpdesk.
> will do. So far it works.
