### ISSUE TITLE
Add fixed stationary distribution option to MSM estimator

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#469]
- Please add an option statdist= or pi= to the MSM estimator, and if given call the reversible estimator with fixed pi.
- Please add that test case to msm/tests/test_msm.py

**Comment by trendelkampschroer** [comment]
Do you want to have the statdist on the full set of states or on the repective set of states specified in the connectivity mode as input?

**Comment by trendelkampschroer** [comment]
The second one probably makes no sense since the average user will not know the connectivity explicitly beforehand.

**Comment by franknoe** [comment]
Good point. Since estimation with respect to a fixed stationary 
distribution changes the meaning connectivity (we only need simply 
connectivity), I think we can only ask the user to provide the 
stationary distribution on the full set. We need to ask him to set any 
unknowns to 0.

Am 25/08/15 um 17:27 schrieb Benjamin Trendelkamp-Schroer:

> Do you want to have the statdist on the full set of states or on the 
> repective set of states specified in the connectivity mode as input?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/469#issuecomment-134626463.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
