### ISSUE TITLE
Defaults for TICA

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#472]
It has been a bit unclear how to use TICA so as to produce kinetic maps and truncate by kinetic variance. Since I think this is the generally right way to do it, I would suggest to set this to a default. I think the following settings would be good defaults in the TICA object and in the tica API function:
- kinetic_map = True
- var_cutoff = 0.95

and correspondingly for PCA / pca:
- var_cutoff = 0.95

Any worries about changing the default here? Careful, changing the defaults may affect some unit tests which assume certain defaults.

Moreover, what about renaming (while keeping the old keyword in deprecated mode for a while) `var_cutoff` to `retained_var` or `var_retained`. Is that more clear?

**Comment by gph82** [comment]
I understand the logic behind the name "kinetic_map" and its connection with diffusion_maps, but can I suggest  
- kinetic_rescale = True 
  as more illuminating for users not familiar with kinetic_maps or diffusion_maps

As for the cutoff argument, I don't have an opinion there. But since it's late and we're brainstorming, I think that subspace_var is also informative

Cheers

**Comment by ppxasjsm** [comment]
`var_cutoff` is the clearest I think. `kinetic_rescale` or `kinetic_map` mean equally as little to me.

**Comment by marscher** [comment]
done

**Comment by franknoe** [comment]
Defaults are not consistent between the TICA object and the coordinates 
API function.

Am 10/08/15 um 18:07 schrieb Martin K. Scherer:

> done
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/472#issuecomment-129511014.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I've fixed that one already. See the referenced commit. Maybe it is not
yet merged with devel.
