### ISSUE TITLE
Check if Estimator is estimated

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#484]
... and raise informative error message when using results if not estimated.

Estimator objects such as ImpliedTimescales must be first parametrized with `estimate(X)`. If using a model property before one gets an error which is hard to interpret if the user is not familiar with the Estimator concept. We should check if estimated and if not while trying to call results raise an informative error message

Since that problem is the same for all estimators it would be great if we could come up with a general solution that doesn't require us to write extra code for every possible model property/method or estimator result.

**Comment by marscher** [comment]
We can set a flags self._estimated and wrap the property decorator such, that is checks self._estimated and raise an error, if it is not the case.

I do not have any better ideas right now.

**Comment by marscher** [comment]
well that approach does not work for methods... Maybe some **getattribute** voodoo will do the trick

**Comment by franknoe** [comment]
Not a problem when working with API functions. Postponing this.

**Comment by marscher** [comment]
we have a decorator to handle this now, but I'm not sure if is used everywhere.
