### ISSUE TITLE
[featurizer] Custom feature - not tested

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#485]
Am I doing anything wrong?

``` python
def returns_X_of_first_atom(traj):
    return traj.xyz[:,0,0]

my_feat = pyemma.coordinates.featurizer(pdbfile)
my_feat.add_custom_func(returns_X_of_first_atom, 1)
my_feat.map(test_traj)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-39-4b5f64c60cf5> in <module>()
      1 my_feat = pyemma.coordinates.featurizer(pdbfile)
      2 my_feat.add_custom_func(returns_X_of_first_atom, 1)
----> 3 my_feat.map(test_traj)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/featurizer.py in map(self, traj)
   1319             if isinstance(f, CustomFeature):
   1320                 # NOTE: casting=safe raises in numpy>=1.9
-> 1321                 vec = f.map(traj).astype(np.float32, casting='safe')
   1322                 if vec.shape[0] == 0:
   1323                     vec = np.empty((0, f.dimension))

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/featurizer.py in map(self, traj)
    249 
    250     def map(self, traj):
--> 251         feature = self._func(traj, *self._args, **self._kwargs)
    252         if not isinstance(feature, np.ndarray):
    253             raise ValueError("your function should return a NumPy array!")

TypeError: returns_X_of_first_atom() takes exactly 1 argument (3 given)
```

Tests for the custom feature functionality only include some sanity checks and duplicate checking

**Comment by gph82** [comment]
I think I that the call to CustomFeature has to be changed from:

``` python
f = CustomFeature(func, args, kwargs, dim=dim)
```

to

``` python
f = CustomFeature(func, dim=dim, *args, **kwargs)
```

to properly expand the tuples.

edit: seems to be working, preparing a PR with a proper test

**Comment by franknoe** [comment]
Hm, it looks wrong to me too, but I didn't write that code and don't 
really understand it at the moment. I guess Martin or Fabian might be 
able to help. Or alternatively, please try to fix it if you can.

Am 05/08/15 um 18:06 schrieb Guillermo Pérez-Hernández:

> I think I that the call to CustomFeature has to be changed from:
> 
> f=  CustomFeature(func, args, kwargs,dim=dim)
> 
> to
> 
> f=  CustomFeature(func,dim=dim,_args,_*kwargs)
> 
> to properly expand the tuples.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/485#issuecomment-128051929.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
since the edit of comment won't show, @franknoe , I got it and I'm preparing a PR and tests

**Comment by gph82** [comment]
got the fix but cannot PR because of conflicts in my local tree.
