### ISSUE TITLE
Remove print out of default JVM path on import

### ISSUE THREAD

**Issue by trendelkampschroer** [markovmodel/PyEMMA#49]
Hi,

I am getting a printout of my default JVM path whenever I import pyemma for the first time in a python script. I think this is due to some print statement in jpype. Is there a quick fix for it?

**Comment by marscher** [comment]
yes, update pystallone

**Comment by trendelkampschroer** [comment]
That is pystallone from github, so the one that is shipped with emma is 'out of date'?

**Comment by marscher** [comment]
There is no pystallone shipped with emma. Its a separate package, udpate
it with pip.

**Comment by trendelkampschroer** [comment]
Thanks will try that
