### ISSUE TITLE
Change license to LGPL

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#499]
As discussed in the last Omnia meeting. LGPL is a little less permissive than BSD and ensures that people making changes/improvements to our code have to contribute these changes. 

Honestly, I have no idea what it means to change the license in a running project. I guess all code from previous versions is still effectively under BSD because BSD is more permissive. 

In the current project state I don't think this makes any differences, but might be relevant later and is useful for license compatibility with other Omnia packages.

**Comment by marscher** [comment]
The previous code base is still licensed under BSD. But in order to change the license we would have to ask all contributors (even if they changed just one line of code) for their permission to do so, since a judge could see a copyright holder.

As one of the copyright holders, I'm fine with the change.

We also have to make sure that all external code, we have taken is compatible with the new license then and preserves their license headers:
https://softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html

**Comment by franknoe** [comment]
OK, since all people who made contributions to PyEMMA are watching us we 
can assume that everyone agrees unless they explicitly disagree by 
Friday, midnight MEST. The license change from BSD to LGPL is very 
minor, so I don't expect any practical problems.

In terms of external code, I believe this only applies to the sklearn 
base module (sklearn is BSD, so no problem), and the networkx spring 
algorithm (I don't know details about that).

Am 26/08/15 um 20:06 schrieb Martin K. Scherer:

> The previous code base is still licensed under BSD. But in order to 
> change the license we would have to ask all contributors (even if they 
> changed just one line of code) for their permission to do so, since a 
> judge could see a copyright holder.
> 
> As one of the copyright holders, I'm fine with the change.
> 
> We also have to make sure that all external code, we have taken is 
> compatible with the new license then and preserves their license headers:
> https://softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/499#issuecomment-135126189.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
I don't know if this is needed, by I'm also fine

this=me saying it, not the change itself 
On 08/26/2015 08:50 PM, Frank Noe wrote:

> OK, since all people who made contributions to PyEMMA are watching us we
> can assume that everyone agrees unless they explicitly disagree by
> Friday, midnight MEST. The license change from BSD to LGPL is very
> minor, so I don't expect any practical problems.
> 
> In terms of external code, I believe this only applies to the sklearn
> base module (sklearn is BSD, so no problem), and the networkx spring
> algorithm (I don't know details about that).
> 
> Am 26/08/15 um 20:06 schrieb Martin K. Scherer:
> 
> > The previous code base is still licensed under BSD. But in order to
> > change the license we would have to ask all contributors (even if they
> > changed just one line of code) for their permission to do so, since a
> > judge could see a copyright holder.
> > 
> > As one of the copyright holders, I'm fine with the change.
> > 
> > We also have to make sure that all external code, we have taken is
> > compatible with the new license then and preserves their license headers:
> > https://softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/499#issuecomment-135126189.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/499#issuecomment-135137401.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by trendelkampschroer** [comment]
According to http://networkx.lanl.gov/reference/legal.html networkx is BSD.

**Comment by franknoe** [comment]
I think we have a consent. @marscher Can you do this?

**Comment by marscher** [comment]
done
