### ISSUE TITLE
coordinates substructure

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#50]
Create coordinates substructure and refactor:

- io
- transform
- cluster

**Comment by marscher** [comment]
please wait with this until I've merged my changes.

**Comment by franknoe** [comment]
Am 27/01/15 um 20:10 schrieb Martin K. Scherer:
>
> please wait with this until I've merged my changes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/50#issuecomment-71707883>.
>
OK

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
