### ISSUE TITLE
Deterministic option in kmeans/kmeans++

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#505]
kmeans seems to have a random outcome, probably due to the initial selection of cluster centers in the kmeans++ initialization. In order to write tutorial notebooks with reproducible results it would be great to have an option to avoid that randomness, without giving up on the quality of the discretization.

Is it possible to fix that initial selection by an optional kwarg and still have the kmeans++ advantage, or is kmeans++ inherently stochastic, i.e. also after the first selection? 

I realize that init_strategy='uniform' may be doing something like that (Documentation needs to be clearer on this point), but then we would loose the kmeans++ advantage.

**Comment by clonker** [comment]
The centers are chosen at random for kmeans++ as well as for uniform (just different distributions), but one could try to fix the seed or provide a set of initial cluster centers in the beginning.

**Comment by franknoe** [comment]
What about choosing them uniformly in time when requesting a 
deterministic outcome?

Am 26/08/15 um 12:08 schrieb Moritz Hoffmann:

> The centers are chosen at random for kmeans++ as well as for uniform 
> (just different distributions), but one could try to fix the seed or 
> provide a set of initial cluster centers in the beginning.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/505#issuecomment-134932557.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Oh, and I meant this as an additional option, i.e. it should work 
together with kmeans++

Am 26/08/15 um 12:08 schrieb Moritz Hoffmann:

> The centers are chosen at random for kmeans++ as well as for uniform 
> (just different distributions), but one could try to fix the seed or 
> provide a set of initial cluster centers in the beginning.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/505#issuecomment-134932557.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
I was about to suggest regspace, but is more time-consuming that regtime
and you cannot control the number of centers

On 08/26/2015 12:11 PM, Frank Noe wrote:

> Oh, and I meant this as an additional option, i.e. it should work
> together with kmeans++
> 
> Am 26/08/15 um 12:08 schrieb Moritz Hoffmann:
> 
> > The centers are chosen at random for kmeans++ as well as for uniform
> > (just different distributions), but one could try to fix the seed or
> > provide a set of initial cluster centers in the beginning.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/505#issuecomment-134932557.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/505#issuecomment-134933097.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

## http://userpage.fu-berlin.de/gph82/

**Comment by franknoe** [comment]
No, we don't need anything fancy because kmeans++ does the job. Just 
offer a way to take the randomness out.

Am 26/08/15 um 12:13 schrieb Guillermo Pérez-Hernández:

> I was about to suggest regspace, but is more time-consuming that regtime
> and you cannot control the number of centers
> 
> On 08/26/2015 12:11 PM, Frank Noe wrote:
> 
> > Oh, and I meant this as an additional option, i.e. it should work
> > together with kmeans++
> > 
> > Am 26/08/15 um 12:08 schrieb Moritz Hoffmann:
> > 
> > > The centers are chosen at random for kmeans++ as well as for uniform
> > > (just different distributions), but one could try to fix the seed or
> > > provide a set of initial cluster centers in the beginning.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > https://github.com/markovmodel/PyEMMA/issues/505#issuecomment-134932557.
> > 
> > ## 
> > 
> > ---
> > 
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> > 
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > 
> > ## Mail: Arnimallee 6, 14195 Berlin, Germany
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/markovmodel/PyEMMA/issues/505#issuecomment-134933097.
> 
> ## 
> 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> 
> ## http://userpage.fu-berlin.de/gph82/
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/505#issuecomment-134933843.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
then I'd go with the seed always set to ...42!

**Comment by franknoe** [comment]
Is a seed a platform-independent way to reproduce the same random number 
sequence? If not, what's wrong with choosing uniform in time, which is 
very simple.

Am 26/08/15 um 12:15 schrieb Guillermo Pérez-Hernández:

> then I'd go with the seed always set to ...42!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/505#issuecomment-134934544.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
I was thinking of situations in which (as one of your notebooks explained at one time) regtime can result in criminally bad discretization. If kmeans(++) can work with that as a starting point, then there's no problem. I dunno about plattform independence of the random number generators.

**Comment by clonker** [comment]
Fixing the seed fixes the sequence of random numbers when drawing samples (platform-independent) The uniform option means that the centers get initialized uniformly distributed and one of course looses the nice kmeans++ center initialization.

**Comment by franknoe** [comment]
I meant to initialize kmeans++ with a time-uniform selection which is 
the same as a specific seed. But if the seed solves it in a 
platform-independent way, that's fine too.

Am 26/08/15 um 12:21 schrieb Moritz Hoffmann:

> Fixing the seed fixes the sequence of random numbers when drawing 
> samples, so the same random number sequence gets obtained 
> (platform-independent). The uniform option means that the centers get 
> initialized uniformly distributed and one of course looses the nice 
> kmeans++ center initialization.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/505#issuecomment-134935426.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
merged
