### ISSUE TITLE
test_its_bmsm fails randomly

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#509]
eg. here: https://travis-ci.org/markovmodel/PyEMMA/jobs/77351704#L1612

**Comment by marscher** [comment]
By which change this has been resolved?

**Comment by franknoe** [comment]
By changing the reference value for the BHMM calculation (resulting from 
different prior). However, I have seen this happen again, so please 
reopen it and push it to 2.1. This is not a trivial issue, but not a 
dealbreaker for the 2.0 release.

Am 01/09/15 um 13:53 schrieb Martin K. Scherer:

> By which change this has been resolved?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/509#issuecomment-136686443.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
