### ISSUE TITLE
Feature selection as a transform

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#51]
Rewrite feature selection as a transform.

This will be different from other transforms, because we use mdtraj's feature computation functions directly, and therefore do not actually implement the mapping
   X -> Y
Does it still make sense to write this as a transform?

How do we deal with multiple feature transforms?

**Comment by marscher** [comment]
@franknoe  is this still in consideration?

**Comment by franknoe** [comment]
Not sure, we have to discuss it tomorrow.

Am 18/03/15 um 16:45 schrieb Martin K. Scherer:
>
> @franknoe <https://github.com/franknoe> is this still in consideration?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/51#issuecomment-83027563>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
We can bind the featurizer to the API in that way:

featurizer(trajs, topology)

where the featurizer internally sets its data_producer with a FeatureReader. We should then refactor the FeatureReader to ChunkedMDReader or something. This makes the code more modular, since if you simply want the coordinates, you do not have the overhead of calling the featurizer for no reason.

Maybe it is also more obvious for users on how to select/extract features, if its not a nested class.

**Comment by franknoe** [comment]
Exactly. Just that you don't need trajs (see previous email)

Am 30/03/15 um 13:22 schrieb Martin K. Scherer:
>
> We can bind the featurizer to the API in that way:
>
> featurizer(trajs, topology)
>
> where the featurizer internally sets its data_producer with a 
> FeatureReader. We should then refactor the FeatureReader to 
> ChunkedMDReader or something. This makes the code more modular, since 
> if you simply want the coordinates, you do not have the overhead of 
> calling the featurizer for no reason.
>
> Maybe it is also more obvious for users on how to select/extract 
> features, if its not a nested class.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/51#issuecomment-87638414>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
