### ISSUE TITLE
Full flux decomposition doesn't work

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#511]
I thought this was fixed, but apparently the full flux decomposition still causes problems. This may be a msmtools issue - I'm not sure.

``` python
from pyemma import msm
P = np.array([[0.8,  0.15, 0.05,  0.0,  0.0],
              [0.1,  0.75, 0.05, 0.05, 0.05],
              [0.05,  0.1,  0.8,  0.0,  0.05],
              [0.0,  0.2, 0.0,  0.8,  0.0],
              [0.0,  0.02, 0.02, 0.0,  0.96]])
M = msm.markov_model(P)
tpt = msm.tpt(M, [0], [4])
tpt.pathways()
```

raises the following exception. Note that asking just for a fraction of pathways, e.g. tpt.pathways(0.99), works.

Please also include a unittest once this is fixed.

``` python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-c0fe262f6e42> in <module>()
      6 M = msm.markov_model(P)
      7 tpt = msm.tpt(M, [0], [4])
----> 8 tpt.pathways()

/Users/noe/data/software_projects/msmtools/msmtools/flux/reactive_flux.pyc in pathways(self, fraction, maxiter)
    207         """
    208         return tptapi.pathways(self.net_flux, self.A, self.B,
--> 209                                fraction=fraction, maxiter=maxiter)
    210 
    211     def _pathways_to_flux(self, paths, pathfluxes, n=None):

/Users/noe/data/software_projects/msmtools/msmtools/flux/api.pyc in pathways(F, A, B, fraction, maxiter)
    544         return sparse.pathways.pathways(F, A, B, fraction=fraction, maxiter=maxiter)
    545     elif isdense(F):
--> 546         return sparse.pathways.pathways(csr_matrix(F), A, B, fraction=fraction, maxiter=maxiter)
    547     else:
    548         raise _type_not_supported

/Users/noe/data/software_projects/msmtools/msmtools/flux/sparse/pathways.pyc in pathways(F, A, B, fraction, maxiter)
    287     while True:
    288         """Find dominant pathway of flux-network"""
--> 289         path = pathway(F, A, B)
    290         """Compute capacity of current pathway"""
    291         c = capacity(F, path)

/Users/noe/data/software_projects/msmtools/msmtools/flux/sparse/pathways.pyc in pathway(F, A, B)
    174                           "obtained from a reversible transition meatrix."))
    175     else:
--> 176         wL = pathway(F, A, [b1, ])
    177     if np.any(B == b2):
    178         wR = [b2, ]

/Users/noe/data/software_projects/msmtools/msmtools/flux/sparse/pathways.pyc in pathway(F, A, B)
    170         wL = [b1, ]
    171     elif np.any(B == b1):
--> 172         raise ValueError(("Roles of vertices b1 and b2 are switched."
    173                           "This should never happen for a correct flux network"
    174                           "obtained from a reversible transition meatrix."))

ValueError: Roles of vertices b1 and b2 are switched.This should never happen for a correct flux networkobtained from a reversible transition meatrix.
```

**Comment by trendelkampschroer** [comment]
@franknoe: Danke fuer den Bug-Report. Ich schau mir das umgehend an.

**Comment by trendelkampschroer** [comment]
@franknoe: Die obige Matrix ist nicht reversibel. Der Algorithmus funktioniert nur fuer eine reversible Matrix. Da das ReactiveFlux Objekt schon mit dem netflux initialisiert wird, kann es nicht wissen ob die Matrix von der aus dieser Flux erzeugt wurde reversibel war.

Am einfachsten waere es, wenn ReactiveFlux ein keyword reversible=True/False bekommt, dass beim Aufruf durch tpt gesetzt wird. Dann kann eine Fehler 'geraist' werden wenn pathways fuer ein nicht-reversibles Flussnetzwerk angefordert wird.

Auf lange Sicht sollte aber ReactiveFlux ebenfalls mit der Signatur (T, A, B, mu=None, qminus=None, qplus=None) aufgerufen werden, damit ReactiveFlux direkt checken kann ob T reversibel oder nicht.

**Comment by franknoe** [comment]
I can try to make the matrix reversible, but it would definitely be 
desireable to have an algorithm that works for a nonreversible matrix. 
There is no reason why you can't make a flux decomposition for a 
nonreversible matrix. In reversible matrices, the flux is formally 
decomposable into A->B pathways. In nonreversible matrices, you will 
have intermediate cycle fluxes left, but still at some point the A->B 
pathway part has been entirely removed, and that is what the function 
should do. In both cases the fraction of the A->B pathways harvested can 
be read off from the flux out of A / into B, so I don't see a 
fundamental problem.

Even if the matrix is reversible, the fact that we continuously subtract 
numbers by removing fluxes will mean that this problem is likely to 
occur for system with many paths simply resulting from numerical errors. 
In this case we'd still like the function to be have properly, so I 
think the case leading to this exception should be caught and then the 
pathway decomposition should be considered to be terminated.

Am 28/08/15 um 13:37 schrieb Benjamin Trendelkamp-Schroer:

> @franknoe https://github.com/franknoe: Die obige Matrix ist nicht 
> reversibel. Der Algorithmus funktioniert nur fuer eine reversible 
> Matrix. Da das ReactiveFlux Objekt schon mit dem netflux initialisiert 
> wird, kann es nicht wissen ob die Matrix von der aus dieser Flux 
> erzeugt wurde reversibel war.
> 
> Am einfachsten waere es, wenn ReactiveFlux ein keyword 
> reversible=True/False bekommt, dass beim Aufruf durch tpt gesetzt 
> wird. Dann kann eine Fehler 'geraist' werden wenn pathways fuer ein 
> nicht-reversibles Flussnetzwerk angefordert wird.
> 
> Auf lange Sicht sollte aber ReactiveFlux ebenfalls mit der Signatur 
> (T, A, B, mu=None, qminus=None, qplus=None) aufgerufen werden, damit 
> ReactiveFlux direkt checken kann ob T reversibel oder nicht.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/511#issuecomment-135746018.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
The issue with the numerical errors was addressed in the fix for

https://github.com/markovmodel/PyEMMA/issues/251

which results in an algorithm that is able decompose the flux into A->B pathways up to numerical tolerance. 

As far as I understand the algorithm the property of having no cycles in the flux network is a prerequisite for it to work. If there is a different algorithm available that can also handle the non-reversible case that would be interesting.

I think Ralph B. has worked for some time on reaction pathways in non-reversible flux networks during his PhD. Maybe he would be willing to contribute his algorithm.

**Comment by franknoe** [comment]
But I think the issue only appears when A and B have been detached from 
the flux and thus only cycles are left, and thus the algorithm is done. 
The aim of this algorithm is not to find the cycles, so I don't think 
Ralph's algorithm is needed here. We should just stop the pathway 
finding process and exit without raising an exception.

Am 28/08/15 um 15:54 schrieb Benjamin Trendelkamp-Schroer:

> The issue with the numerical errors was addressed in the fix for
> 
> #251 https://github.com/markovmodel/PyEMMA/issues/251
> 
> which results in an algorithm that is able decompose the flux into 
> A->B pathways up to numerical tolerance.
> 
> As far as I understand the algorithm the property of having no cycles 
> in the flux network is a prerequisite for it to work. If there is a 
> different algorithm available that can also handle the non-reversible 
> case that would be interesting.
> 
> I think Ralph B. has worked for some time on reaction pathways in 
> non-reversible flux networks during his PhD. Maybe he would be willing 
> to contribute his algorithm.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/511#issuecomment-135780665.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
P.S.: I can make the function work with requesting pathways(0.99), which 
gives me all A->B pathways. So it works in principle, it just runs into 
an unnecessary exception when there is really nothing left to do.

Am 28/08/15 um 15:54 schrieb Benjamin Trendelkamp-Schroer:

> The issue with the numerical errors was addressed in the fix for
> 
> #251 https://github.com/markovmodel/PyEMMA/issues/251
> 
> which results in an algorithm that is able decompose the flux into 
> A->B pathways up to numerical tolerance.
> 
> As far as I understand the algorithm the property of having no cycles 
> in the flux network is a prerequisite for it to work. If there is a 
> different algorithm available that can also handle the non-reversible 
> case that would be interesting.
> 
> I think Ralph B. has worked for some time on reaction pathways in 
> non-reversible flux networks during his PhD. Maybe he would be willing 
> to contribute his algorithm.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/511#issuecomment-135780665.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
Okay, this is strange. I'll go ahead as you suggested.

**Comment by franknoe** [comment]
thanks!

Am 28/08/15 um 17:16 schrieb Benjamin Trendelkamp-Schroer:

> Okay, this is strange. I'll go ahead as you suggested.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/511#issuecomment-135802127.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Done by Benjamin. Thanks a lot!
