### ISSUE TITLE
Reconcile coordinates and msm APIs

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#52]
The coordinate transformations and MSM construction should be made easily combinable.

Previously suggested API:
----
Here's a rough suggestion for the high-level API and functionality of coordinates and msm:

    from pyemma.coordinates import transforms,clustering,Discretizer
    import pyemma.msm as msm
    import pyemma.plot as msmplot

    # First we load the trajectory data
    trajs = os.list("./*.dcd")
    trajdata = TrajData(trajs, "bpti.top")

    # Now we select features
    trajdata.feature.distances("name CA")

    # Now construct a discretizer
    tica = transforms.tica(100, 2)
    kmeans = clustering.kmeans(100)
    disc = Discretizer(trajdata, transform = tica, cluster = kmeans)
    disc.run() # do we need that as an extra command?

    # Now build an MSM
    msm = msm.MSM(disc)

    # look at its
    its = msm.implied_timescales([1,2,5,10,20,50,100,200,500])
    msmplot.implied_timescales(its)

    # estimate at lag 100
    msm.estimate(100)
    P = msm.transition_matrix()
    mu = msm.stationary_distribution()

Alternative
----------
Construct pipelines where the estimators are at the end (e.g. MSM, HMM). Need to make sure that input and output types match at each stage of the pipeline.

**Comment by marscher** [comment]
I would suggest having a run method on Discretizer as you should not enforce users to run the computation instantly during object creation.

**Comment by franknoe** [comment]
This is outdated.
