### ISSUE TITLE
Consisent progress bar handling

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#525]
- Some progress bars close after 2 sec, others don't (it looks like the msm package PB's close, the coordinate-package PB's don't, but the differences might be more subtle). It would be good to have a consistent behavior.
- Progress bars can be activated with 'True' and deactivated with 'False' or False. But they can't be activated with True (Boolean), which would be the intuitive way. Is that possible?

This is 2.0.1, so no hurry.

**Comment by marscher** [comment]
second point is a no-brainer. I'll commit it just to devel

**Comment by franknoe** [comment]
thanks

Am 30/08/15 um 20:16 schrieb Martin K. Scherer:

> second point is a no-brainer. I'll commit it just to devel
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/525#issuecomment-136165736.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Actually I've tested the first point and the behaviour is currently the following: If the ETA of a progress is below 1s, a thread will be started after 2s to close this one. This does not require the user of ProgressReporter to forcefully finish the progress. The check is performed for every progress update, so in principle there are no exceptions to this rule.

**Comment by franknoe** [comment]
Ah, now I understand, but it's a bit unclear to the user why some 
progress bars stay and others disappear. I actually like it if they 
disappear after a while because that cleans up the notebook, so maybe we 
could generally do this? Maybe you can discuss this tomorrow if there is 
consent which behavior is desired. If there is no clear consent, let's 
leave it as it is for now.

Am 30/08/15 um 20:19 schrieb Martin K. Scherer:

> Actually I've tested the first point and the behaviour is currently 
> the following: If the ETA of a progress is below 1s, a thread will be 
> started after 2s to close this one. This does not require the user of 
> ProgressReporter to forcefully finish the progress. The check is 
> performed for every progress update, so in principle there are no 
> exceptions to this rule.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/525#issuecomment-136166953.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
