### ISSUE TITLE
Make convergence information available in MaximumLikelihoodMSM

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#527]

**Comment by marscher** [comment]
@franknoe Is this done or should it be postponed to the next release?

**Comment by franknoe** [comment]
Am 30/03/16 um 15:38 schrieb Martin K. Scherer:

> @franknoe https://github.com/franknoe Is this done or should it be 
> postponed to the next release?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/527#issuecomment-203437376
> 
> postpone

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Hi, I'm starting to need this feature...any ideas it's best? With some pointers I can gladly start implementing myself

**Comment by marscher** [comment]
I guess you would need to expose this info from the low level estimator in msmtools and bind it in pyemmas class.

**Comment by gph82** [comment]
This is somewhat related: what about starting by exposing some arguments of MaximumLikelihoodMSM (or BayesianMSM) like maxiterations? I mean, at least after its reports no convergence one could repeat the estimation wit more iterations, right? What do you think, @franknoe ?

**Comment by marscher** [comment]
Am 26.05.2016 um 18:01 schrieb Guillermo Pérez-Hernández:

**Comment by gph82** [comment]
sure, but not at the moment of calling msm.its, right? Because I don't know which one of the models is behind the "not-converged" logging message. Or am I missing something

**Comment by franknoe** [comment]
yes, but it would restart estimating from scratch. There is currently no 
way to continue the iteration. I'm also not sure what would be the 
sklearny way to doing this.

Am 26/05/16 um 18:05 schrieb Martin K. Scherer:

> Am 26.05.2016 um 18:01 schrieb Guillermo Pérez-Hernández:
> 
> > This is somewhat related: what about starting by exposing some 
> > arguments of MaximumLikelihoodMSM (or BayesianMSM) like maxiterations? 
> > I mean, at least after its
> > reports no convergence one could repeat the estimation wit more 
> > iterations, right?
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub 
> > https://github.com/markovmodel/PyEMMA/issues/527#issuecomment-221915546
> > 
> > max_iter is already an estimation parameter. You can always increase it.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/527#issuecomment-221916612

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 26.05.2016 um 18:06 schrieb Guillermo Pérez-Hernández:

> sure, but not at the moment of calling msm.its, right? Because I don't know which one of the models is behind the "not-converged" logging message. Or am I
> missing something

A simple solution would be to introduce a converged attribute which is a list of booleans. We catch the msmtools.NotConvergedWarning and set the flags 
accordingly. Or a dictionary keyed by lag time?

**Comment by gph82** [comment]
at the moment, what can I do with the "not-converged" info after an ITS estimation? Not much, because I do not know which ones are converged and which don't. Don't mind restarting from scratch if I can help cure that (on the other hand, I think my pathological case won't be helped by this). It's kind of limiting that many of the nice properties of the MSM estimation cannot be controlled when using msm.its...

**Comment by gph82** [comment]
@marscher , that's exactly what I had in mind https://github.com/markovmodel/PyEMMA/issues/527#issuecomment-221917979

**Comment by franknoe** [comment]
Yeah, I think memorizing the results (convergence info, likelihood, ...) 
of the low-level estimation in the Estimator is the right way to do 
this. Then you can inspect it a posteriori.

Am 26/05/16 um 18:11 schrieb Guillermo Pérez-Hernández:

> at the moment, what can I do with the "not-converged" info after an 
> ITS estimation? Not much, because I do not know which ones are 
> converged and which don't. Don't mind restarting from scratch if I can 
> help cure that (on the other hand, I think my pathological case won't 
> be helped by this). It's kind of limiting that many of the nice 
> properties of the MSM estimation cannot be controlled when using 
> msm.its...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/527#issuecomment-221918342

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
that would enable the identification of the non-converged lagtime and the repetition of the estimation for only that model. Would something like this work automagically?:

``` python
its = msm.its(dtrajs, lags=[1,2,3])
print(its.model_converged) # new feature 
# [True, True, False] #ah, the last one needs more iters
iMSM = its.models[2]
iMSM.estimate(maxiter=2e5)
```

**Comment by franknoe** [comment]
See above - the convergence info should be a property of the 
**Estimator**, not of the timescales command. Currently timescales are 
used with Estimators where convergence info could be available, but this 
is not going to be valid in the future.

Am 26/05/16 um 18:17 schrieb Guillermo Pérez-Hernández:

> that would enable the identification of the non-converged lagtime and 
> the repetition of the estimation for only that model. Would something 
> like this work automagically?:
> 
> its=  msm.its(dtrajs,lags=[1,2,3])
> print(its.model_converged)# new feature
> 
> # [True, True, False] #ah, the last one needs more iters
> 
> iMSM=  its.models[2]
> iMSM.estimate(maxiter=2e5)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/527#issuecomment-221920016

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 26.05.2016 um 18:17 schrieb Guillermo Pérez-Hernández:

> that would enable the identification of the non-converged lagtime and the repetition of the estimation for only that model. Would something like this work
> automagically?:
> yes. And one could also simply assign the re-computed model to the models list for the appropriate index, so there is no re-estimation of the whole thing needed.

**Comment by gph82** [comment]
ok, of the estimator then, as long as I can reach them through something like its.model[2].converged, i'm happy. Plus, other estimators might not have the convergence attribute, so yeah, makes more sens.

**Comment by franknoe** [comment]
This will make no sense if e.g. in the future we use TICA with an 
estimator command. It's also unclear what convergence means with a 
Bayesian estimator - certainly it isn't a boolean quantity in that case. 
Convergence-Info (including if and what kind of convergence info is 
available) is highly estimator specific. Let's say we add an attribute 
`converged` to `MaximumLikelihoodMSM`, meaning that we achieved the 
error threshold within the maximum number of iterations. Then you could do

``` python
its = msm.its(dtrajs, lags=[1, 2, 3])
for estimator in its.estimators:
     print estimator.lag, estimator.converged
```

Am 26/05/16 um 18:17 schrieb Guillermo Pérez-Hernández:

> that would enable the identification of the non-converged lagtime and 
> the repetition of the estimation for only that model. Would something 
> like this work automagically?:
> 
> its=  msm.its(dtrajs,lags=[1,2,3])
> print(its.model_converged)# new feature
> 
> # [True, True, False] #ah, the last one needs more iters
> 
> iMSM=  its.models[2]
> iMSM.estimate(maxiter=2e5)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/527#issuecomment-221920016

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
