### ISSUE TITLE
mdtraj warning triggered by pyemma.coordinates.save_traj

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#546]
This mdtraj warning seems to be triggered by our coordinate.save_traj function (this screenshot is from the PyEMMA BPTI tutorial). I haven't seen this before, so it's either new in a recent mdtraj release or some code changes recently made in save_traj. Any ideas?

![screen shot 2015-09-02 at 17 20 15](https://cloud.githubusercontent.com/assets/6495810/9635490/ff202514-5196-11e5-8a32-2f69f8b1e936.png)

**Comment by gph82** [comment]
off the top of my head (and looking at the errormsg) his might be the way that 
dummy geometries are created, with a dummy box of 0  0  0.

This warning must by new in mdtraj

On 09/02/2015 05:23 PM, Frank Noe wrote:

> This mdtraj warning seems to be triggered by our coordinate.save_traj function
> (this screenshot is from the PyEMMA BPTI tutorial). I haven't seen this before,
> so it's either new in a recent mdtraj release or some code changes recently made
> in save_traj. Any ideas?
> 
> screen shot 2015-09-02 at 17 20 15
> https://cloud.githubusercontent.com/assets/6495810/9635490/ff202514-5196-11e5-8a32-2f69f8b1e936.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/546.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by franknoe** [comment]
Why use a dummy box with 0 0 0? Don't we have box information available 
from the input? What if you have explicit solvent included in the input 
trajectories and want to keep them in save_traj, e.g. to seed new 
simulations?

Am 02/09/15 um 17:25 schrieb Guillermo Pérez-Hernández:

> off the top of my head (and looking at the errormsg) his might be the 
> way that
> dummy geometries are created, with a dummy box of 0 0 0.
> 
> This warning must by new in mdtraj
> 
> On 09/02/2015 05:23 PM, Frank Noe wrote:
> 
> > This mdtraj warning seems to be triggered by our 
> > coordinate.save_traj function
> > (this screenshot is from the PyEMMA BPTI tutorial). I haven't seen 
> > this before,
> > so it's either new in a recent mdtraj release or some code changes 
> > recently made
> > in save_traj. Any ideas?
> > 
> > screen shot 2015-09-02 at 17 20 15
> > 
> > https://cloud.githubusercontent.com/assets/6495810/9635490/ff202514-5196-11e5-8a32-2f69f8b1e936.png
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/546.
> 
> ## 
> 
> Dr. Guillermo Pérez-Hernández
> Freie Universität Berlin
> Institute for Mathematics
> Arnimallee 6
> D-14195 Berlin
> tel 0049 30 838 75776
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/546#issuecomment-137130575.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I think if the box is not provided mdtraj will guess it from the data. 
So you do not have to initialize it.

**Comment by gph82** [comment]
This is a comment that I sent to frank thinking I was answering to the issues:
"as I said, its the that geometries are created. Then all the information that you mention below/above is copied into them. We're not explictily throwing that information away, to the contrary:
https://github.com/markovmodel/PyEMMA/blob/92936654fcf52d1ea697a9a253d4e011e2a3d69d/pyemma/coordinates/data/util/reader_utils.py copy_traj_attributes "

**Comment by franknoe** [comment]
Is this fixed in the current devel?

**Comment by gph82** [comment]
It has stopped appearing AFAIK, but I did not do anything

**Comment by marscher** [comment]
so it has been fixed upstream in a newer mdtraj release. Closing this
