### ISSUE TITLE
FeatureReader._assert_toptraj_consistency fails for non-XTC files

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#547]
``` python
def _assert_toptraj_consistency(self):
    r""" Check if the topology and the trajfiles of the reader have the same n_atoms"""
    with mdtraj.open(self.trajfiles[0],'r') as fh:
        xyz, __, __, __ = fh.read(n_frames=1)
    assert xyz.shape[1] == self.featurizer.topology.n_atoms, "Mismatch in the number of atoms between the topology" \
                                                            " and the first trajectory file, %u vs %u"% \
                                                            (self.featurizer.topology.n_atoms, xyz.shape[1])
```

fails because for non-XTC files read does not always return a 4-tuple.

**Comment by franknoe** [comment]
http://pyemma.org/latest now has the right changelog, but there's no 2.0.1 version button.

**Comment by marscher** [comment]
> http://pyemma.org/latest now has the right changelog, but there's no
> 2.0.1 version button.

I just noticed another issue. If one directly enters the stated url, one 
gets a 404 error on /latest.

This is most likely due to the double redirect from pyemma.org -> 
pythonhosted.org -> emma-project.org. I'll suggest to remove the 
intermediate.

If the site is accessed from the emma-project.org url, it works like 
expected.

**Comment by franknoe** [comment]
done

Am 07/09/15 um 17:11 schrieb Martin K. Scherer:

> > http://pyemma.org/latest now has the right changelog, but there's no
> > 2.0.1 version button.
> 
> I just noticed another issue. If one directly enters the stated url, one
> gets a 404 error on /latest.
> 
> This is most likely due to the double redirect from pyemma.org ->
> pythonhosted.org -> emma-project.org. I'll suggest to remove the
> intermediate.
> 
> If the site is accessed from the emma-project.org url, it works like
> expected.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/547#issuecomment-138321941.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
