### ISSUE TITLE
[featurizer.py] Check all features for emptiness and raise/warn if thats the case

### ISSUE THREAD

**Issue by ag1989** [markovmodel/PyEMMA#549]
There seems to be a bug in featurizer.py when it tries to unpack the values to variables. This error only occurs if you call the add_chi1_torsions() function.

``` python
    707     def __init__(self, topology, selstr=None, deg=False, cossin=False):
    708         ft = fake_traj(topology)
--> 709         _, indices = _get_indices_chi1(ft)
    710         if not selstr:
    711             dih_indexes = indices
ValueError: need more than 0 values to unpack
```

**Comment by franknoe** [comment]
thanks. I have definitely used that function before with success. Does 
your topology include sidechain rotamers? (e.g. for BPTI it can't work 
because this is a Ca-trajectory).

Am 03/09/15 um 12:05 schrieb ag1989:

> There seems to be a bug in featurizer.py when it tries to unpack the 
> values to variables. This error only occurs if you call the 
> add_chi1_torsions() function.
> 
> ```
>  707      def  __init__(self, topology,selstr=None,deg=False,cossin=False):
>  708          ft=  fake_traj(topology)
> ```
> 
> -->  709          _, indices=  _get_indices_chi1(ft)
>      710          if  not  selstr:
>      711              dih_indexes=  indices
> ValueError: need more than0  values to unpack
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/549.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ag1989** [comment]
Ups.. okay this has been my problem... tanks!

I totally forgot about this property of the BPTI-traj.

Interestingly the backbone dihedrals work without any failure but don't gave any values (as one would  expect for Ca atoms). Maybe a zero selection warning would be nice?

**Comment by franknoe** [comment]
I agree, we need better checks and more informative errors messages. So 
I'll leave this open.

Am 03/09/15 um 13:10 schrieb ag1989:

> Ups.. okay this has been my problem... tanks!
> 
> Interestingly the backbone dihedrals work without any failure but 
> don't gave any values (as one would expect for Ca atoms). Maybe a zero 
> selection warning would be nice?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/549#issuecomment-137409690.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
You get one warning if your feature list is empty (due to meaningless features). But we should fail as early as possible (e.g in feature constructors check the index array, raise if it is empty)
