### ISSUE TITLE
remove pyemma.msm.$(msmtools subpackages)

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#550]
Due to experience in the workshop it is confusing to users, if high-level objects and low-level API mix up in autocomplete (they've chosen to use the low level api, because the naming of desired quantities are more promising).

**Comment by marscher** [comment]
Or at least we should trigger a warning, if these functions are used

**Comment by franknoe** [comment]
I think that's a good point. PyEMMA has evolved from these low-level 
functions, but now that we have a systematic object structure we might 
consider msmtools to be completely separate. People can still use them 
via import msmtools. It would certainly lead to more well-defined 
packages. Let's discuss this after MolKin.

Am 03/09/15 um 14:05 schrieb Martin K. Scherer:

> Due to experience in the workshop it is confusing to users, if 
> high-level objects and low-level API mix up in autocomplete (they've 
> chosen to use the low level api, because the naming of desired 
> quantities are more promising).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/550.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Just to be clear: You want to remove these imports in `msm.__init__` - correct?

```
from msmtools import analysis, estimation, generation, dtraj, flux
```

**Comment by marscher** [comment]
Exactly - this should go to the next minor release, since it changes the api.

**Comment by franknoe** [comment]
I agree

**Comment by marscher** [comment]
We haven't deprecated these packages yet. So removing them now will break the code of your users without a prior warning. So we should post-pone this to eg. 2.2

**Comment by franknoe** [comment]
yes

Am 22/03/16 um 12:54 schrieb Martin K. Scherer:

> We haven't deprecated these packages yet. So removing them now will 
> break the code of your users without a prior warning. So we should 
> post-pone this to eg. 2.2
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/550#issuecomment-199777647

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
