### ISSUE TITLE
progressbars in ipython notebook 4.0 are drawn with console backend

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#551]
most probably the imports from ipython to detect an interactive session have changed.

**Comment by marscher** [comment]
conda install ipywidgets is needed, but do we really enforce this via dependencies then? (we would need to require also ipython/ipython-notebook then).

This will drag in these dependenices:

```
The following NEW packages will be INSTALLED:

    certifi:            14.05.14-py27_0
    decorator:          4.0.2-py27_0   
    ipykernel:          4.0.3-py27_0   
    ipython:            4.0.0-py27_0   
    ipython_genutils:   0.1.0-py27_0   
    ipywidgets:         4.0.2-py27_0   
    jinja2:             2.8-py27_0     
    jsonschema:         2.4.0-py27_0   
    jupyter_client:     4.0.0-py27_0   
    jupyter_core:       4.0.4-py27_0   
    libsodium:          0.4.5-0        
    markupsafe:         0.23-py27_0    
    mistune:            0.7.1-py27_0   
    nbconvert:          4.0.0-py27_0   
    nbformat:           4.0.0-py27_0   
    notebook:           4.0.4-py27_0   
    path.py:            7.6-py27_0     
    pexpect:            3.3-py27_0     
    pickleshare:        0.5-py27_0     
    ptyprocess:         0.4-py27_0     
    pygments:           2.0.2-py27_0   
    pyzmq:              14.7.0-py27_0  
    simplegeneric:      0.8.1-py27_0   
    ssl_match_hostname: 3.4.0.2-py27_0 
    terminado:          0.5-py27_0     
    tornado:            4.2.1-py27_0   
    traitlets:          4.0.0-py27_0   
    zeromq:             4.0.5-0
```

However the plain text progress bars also works. I vote to enforce it with conda, but leave PyPI out, since it would be annoying compiling all these deps.

**Comment by franknoe** [comment]
I am totally for avoiding to enforce these dependencies if the nice 
progress bars are still shown if you happen to fulfill them.

Am 03/09/15 um 14:55 schrieb Martin K. Scherer:

> conda install ipywidgets is needed, but do we really enforce this via 
> dependencies then? (we would need to require also 
> ipython/ipython-notebook then).
> 
> This will drag in these dependenices:
> 
> |The following NEW packages will be INSTALLED: certifi: 14.05.14-py27_0 
> decorator: 4.0.2-py27_0 ipykernel: 4.0.3-py27_0 ipython: 4.0.0-py27_0 
> ipython_genutils: 0.1.0-py27_0 ipywidgets: 4.0.2-py27_0 jinja2: 
> 2.8-py27_0 jsonschema: 2.4.0-py27_0 jupyter_client: 4.0.0-py27_0 
> jupyter_core: 4.0.4-py27_0 libsodium: 0.4.5-0 markupsafe: 0.23-py27_0 
> mistune: 0.7.1-py27_0 nbconvert: 4.0.0-py27_0 nbformat: 4.0.0-py27_0 
> notebook: 4.0.4-py27_0 path.py: 7.6-py27_0 pexpect: 3.3-py27_0 
> pickleshare: 0.5-py27_0 ptyprocess: 0.4-py27_0 pygments: 2.0.2-py27_0 
> pyzmq: 14.7.0-py27_0 simplegeneric: 0.8.1-py27_0 ssl_match_hostname: 
> 3.4.0.2-py27_0 terminado: 0.5-py27_0 tornado: 4.2.1-py27_0 traitlets: 
> 4.0.0-py27_0 zeromq: 4.0.5-0 |
> 
> However the plain text progress bars also works. I vote to enforce it 
> with conda, but leave PyPI out, since it would be annoying compiling 
> all these deps.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/551#issuecomment-137430797.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
