### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#554]
http://www.emma-project.org/latest/api/generated/msmtools.flux.mfpt.html?highlight=mfpt#msmtools.flux.mfpt

> Returns:  
> kAB – The reaction rate (per time step of the Markov chain)

It returns the mfpt, not the reaction rate.

**Comment by trendelkampschroer** [comment]
@stefdoerr: thx for spotting

**Comment by trendelkampschroer** [comment]
I have created a pull request with a fix.

**Comment by stefdoerr** [comment]
http://www.emma-project.org/latest/api/generated/pyemma.msm.BayesianHMSM.html?highlight=cktest#pyemma.msm.BayesianHMSM.cktest

cktest returns a Chapman-Kolmogorov validator. It's missing in the docs of both HMSM and MSM.

**Comment by franknoe** [comment]
thanks for spotting!

Am 04/09/15 um 12:01 schrieb Stefan:

> http://www.emma-project.org/latest/api/generated/pyemma.msm.BayesianHMSM.html?highlight=cktest#pyemma.msm.BayesianHMSM.cktest
> 
> cktest returns a Chapman-Kolmogorov validator. It's missing in the 
> docs of both HMSM and MSM.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/554#issuecomment-137694324.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I didn't spot any PRs handling this. @trendelkampschroer do you have these changes on a local branch?

**Comment by trendelkampschroer** [comment]
No I just fixed the one in msmtools.
