### ISSUE TITLE
[coor.cluster.regspace] why dmin=-1 as default?

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#557]
Hi, perhaps I'm missing something, but why do we have this behavior? 

If the user is forced to give it a value, should it not be a positional argument?

**Comment by marscher** [comment]
The very simple reason for this is that the first argument data is optional, so dmin also has to be optional or it has to be first argument. Because we do not want to switch the order of arguments in an API function (very confusing) we use this pattern.
