### ISSUE TITLE
[thermo] subsampling for WHAM

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#558]
Since uncorrelated data are needed for a WHAM estimate, we need to do some kind of subsampling based on statistical inefficiency. It is not clear where this subsampling should be implemented. Are there any options available already to do this? Should this be implemented within the estimator itself or somewhere outside?

**Comment by franknoe** [comment]
I don't think we necessarily need to subsample for the MLE. We need to 
subsample if we want error intervals.

I think in the low-level API we could expect that the subsampling has 
been done before. In the PyEMMA estimator class we could use a stride=1 
argument to do optional subsampling.

Am 11/09/15 um 18:12 schrieb ppxasjsm:

> Since uncorrelated data are needed for a WHAM estimate, we need to do 
> some kind of subsampling based on statistical inefficiency. It is not 
> clear where this subsampling should be implemented. Are there any 
> options available already to do this? Should this be implemented 
> within the estimator itself or somewhere outside?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/558.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
