### ISSUE TITLE
documentation of double-named functions

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#56]
The documentation of msm.estimation.transition_matrix and msm.estimation.tmatrix are not identical. Is there a way to create an alias without manually copying the documentation?
If not, just copy it (in this case transition_matrix has the full doc), and check for other "doubles" if the same problem exists.

**Comment by marscher** [comment]
a function alias should reference the docstring of the referenced
function like this:

def long_long_function_name(*args):
   """ very descriptive docstring """
   pass


alias_f = long_long_function_name
alias_f.__doc__ = long_long_function_name.__doc__

This pattern avoids copy paste docstrings and increases maintainability.
