### ISSUE TITLE
PCCA should warn or raise when more states are requested than matrix spectrum admits

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#564]
I was trying to use the pyemma.msm.MaximumLikelihoodMSM.pcca method and I am getting weird results:

```
ipdb> M.pcca(2)
<msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b0ee3c8>
ipdb> set(M.metastable_assignments)
{0, 1}
ipdb> M.pcca(3)
<msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b0988d0>
ipdb> set(M.metastable_assignments)
{0, 1, 2}
ipdb> M.pcca(5)
<msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9afe2710>
ipdb> set(M.metastable_assignments)
{0, 1, 2, 3, 4}
ipdb> M.pcca(6)
<msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b0988d0>
ipdb> set(M.metastable_assignments)
{0, 2, 3, 4, 5}
ipdb> M.pcca(7)
<msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b044240>
ipdb> set(M.metastable_assignments)
{0, 1, 2, 4, 5, 6}
ipdb> M.pcca(8)
<msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9afe2710>
ipdb> set(M.metastable_assignments)
{0, 1, 5, 6}
```

Why am I getting only 4 macrostates when I am requesting 8?

**Comment by franknoe** [comment]
I will look into this.

Am 23/09/15 um 17:05 schrieb Stefan:

> I was trying to use the pyemma.msm.MaximumLikelihoodMSM.pcca method 
> and I am getting weird results:
> 
> |ipdb> M.pcca(2) <msmtools.analysis.dense.pcca.PCCA object at 
> 0x7f2a9b0ee3c8> ipdb> set(M.metastable_assignments) {0, 1} ipdb> 
> M.pcca(3) <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b0988d0> 
> ipdb> set(M.metastable_assignments) {0, 1, 2} ipdb> M.pcca(5) 
> <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9afe2710> ipdb> 
> set(M.metastable_assignments) {0, 1, 2, 3, 4} ipdb> M.pcca(6) 
> <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b0988d0> ipdb> 
> set(M.metastable_assignments) {0, 2, 3, 4, 5} ipdb> M.pcca(7) 
> <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b044240> ipdb> 
> set(M.metastable_assignments) {0, 1, 2, 4, 5, 6} ipdb> M.pcca(8) 
> <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9afe2710> ipdb> 
> set(M.metastable_assignments) {0, 1, 5, 6} |
> 
> Why am I getting only 4 macrostates when I am requesting 8?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/564.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Can you try if you get the same problem when using msmtools.analysis.pcca?

Am 23/09/15 um 17:05 schrieb Stefan:

> I was trying to use the pyemma.msm.MaximumLikelihoodMSM.pcca method 
> and I am getting weird results:
> 
> |ipdb> M.pcca(2) <msmtools.analysis.dense.pcca.PCCA object at 
> 0x7f2a9b0ee3c8> ipdb> set(M.metastable_assignments) {0, 1} ipdb> 
> M.pcca(3) <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b0988d0> 
> ipdb> set(M.metastable_assignments) {0, 1, 2} ipdb> M.pcca(5) 
> <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9afe2710> ipdb> 
> set(M.metastable_assignments) {0, 1, 2, 3, 4} ipdb> M.pcca(6) 
> <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b0988d0> ipdb> 
> set(M.metastable_assignments) {0, 2, 3, 4, 5} ipdb> M.pcca(7) 
> <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9b044240> ipdb> 
> set(M.metastable_assignments) {0, 1, 2, 4, 5, 6} ipdb> M.pcca(8) 
> <msmtools.analysis.dense.pcca.PCCA object at 0x7f2a9afe2710> ipdb> 
> set(M.metastable_assignments) {0, 1, 5, 6} |
> 
> Why am I getting only 4 macrostates when I am requesting 8?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/564.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
Yes but I think it's less a bug and more that I have wrong expectations from PCCA+?
If I assume you just argmax the membership probabilities to choose the assignments:

```
ipdb> k = pcca(P ,8)
ipdb> y = np.argmax(k,axis=1)
ipdb> set(y)
{0, 1, 5, 6}
```

I get the same results. It seems like there is no microstate with maximum membership in the other 4 states. 

From the simple PCCA I remember that each eigenvector would create one more macrostate, taking microstates from the previous macrostates, guaranteeing that you would not have empty macrostates.
Seems like this doesn't apply to PCCA+. I wonder however then how PCCA+ works in MSMBuilder because there it seems to give me at the minimum one micro per macro.

**Comment by stefdoerr** [comment]
Maybe because in MSMBuilder in the implementation they are optimizing a crisp metastability?

> Return the crisp_metastability PCCA+ objective function.
> crisp_metastability: try to make the resulting crisp msm metastable.
> This is the recommended choice.  This is the metastability (trace)
> of a transition matrix computed by forcing a crisp (non-fuzzy)
> microstate mapping.  Defined in ref. [2].

**Comment by franknoe** [comment]
Hm, I really don't know about msmbuilder. As far as I know, crisp and 
PCCA+ are two different worlds.

Anyway, I agree that should get 8 macrostates if you ask for 8 and the 
matrix admits that. So could you send me the matrix to test that? I'd 
like to take a closer look.

Am 23/09/15 um 17:55 schrieb Stefan:

> Maybe because in MSMBuilder in the implementation they are optimizing 
> a crisp metastability?
> 
> ```
> Return the crisp_metastability PCCA+ objective function.
> crisp_metastability: try to make the resulting crisp msm metastable.
> This is the recommended choice. This is the metastability (trace)
> of a transition matrix computed by forcing a crisp (non-fuzzy)
> microstate mapping. Defined in ref. [2].
> ```
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/564#issuecomment-142646674.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
Okay, I sent it now by mail

**Comment by franknoe** [comment]
I had a look. As you say, the behavior is completely consistent. The problem is that for this matrix you just cannot ask for more than four metastable states. Its largest eigenvalues are

```
array([ 1.        ,  0.90177763,  0.55348811,  0.50648116, -0.44862964,
        0.44637256,  0.43579228,  0.42375328, -0.42374972,  0.41667612])
```

so the radius of useful eigenvalues is about 0.5. The rest is numerically garbage and not meaningful for any metastability analysis. This typically happens when the lag time is larger than the timescales of the processes. In your case only four processes are slow enough that they resolved at your lagtime. That also means that if any other method gives you more than four metastable states, you cannot trust the results.

I agree that the behavior of the PCCA implementation in this case is confusing though. The spectrum of the matrix should be checked and a warning should be raised if you request more metastable states that the matrix admits. I'll leave this issue open and change its title accordingly.

**Comment by stefdoerr** [comment]
Yes true, the timescales were indeed bad. I was just playing around with the code, not doing a real analysis. But yes, a warning would be great as well.

On September 24, 2015 3:39:28 PM GMT+02:00, Frank Noe notifications@github.com wrote:

> I had a look. As you say, the behavior is completely consistent. The
> problem is that for this matrix you just cannot ask for more than four
> metastable states. Its largest eigenvalues are
> 
> ```
> array([ 1.        ,  0.90177763,  0.55348811,  0.50648116, -0.44862964,
>       0.44637256,  0.43579228,  0.42375328, -0.42374972,  0.41667612])
> ```
> 
> so the radius of useful eigenvalues is about 0.5. The rest is
> numerically garbage and not meaningful for any metastability analysis.
> This typically happens when the lag time is larger than the timescales
> of the processes. In your case only four processes are slow enough that
> they resolved at your lagtime. That also means that if any other method
> gives you more than four metastable states, you cannot trust the
> results.
> 
> I agree that the behavior of the PCCA implementation in this case is
> confusing though. The spectrum of the matrix should be checked and a
> warning should be raised if you request more metastable states that the
> matrix admits. I'll leave this issue open and change its title
> accordingly.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/markovmodel/PyEMMA/issues/564#issuecomment-142930029

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefdoerr** [comment]
Actually it would also be very helpful if you could number the macrostates incrementally in that case. So instead of having set {0, 1, 5, 6} to have set {0, 1, 2, 3}
