### ISSUE TITLE
Distance units

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#565]
Are the units produced by featurizer.add_distance actually in nanometers? I assumed it would return distances in Angstrom but it consistently reports me 1/10th of the Angstrom distance I get in my code.
Is it maybe an issue with reading the xtc files?

**Comment by stefdoerr** [comment]
Assuming the featurizer returns distances in the units used in the trajectory file, you have a bug in your xtc reader. 
VMD shows the distances correctly/consistently with my code.

**Comment by franknoe** [comment]
I think this is an issue to be answered by Guillermo. We use mdtraj for 
I/O and most of the featurization, which I think uses nm by default, and 
we just pass those distances on.

Am 25/09/15 um 14:58 schrieb Stefan:

> Are the units produced by featurizer.add_distance actually in 
> nanometers? I assumed it would return distances in Angstrom but it 
> consistently reports me 1/10th of the Angstrom distance I get in my code.
> Is it maybe an issue with reading the xtc files?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/565.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Hi, it's Nanometers, the units of mdtraj

On 09/25/2015 03:43 PM, Frank Noe wrote:

> I think this is an issue to be answered by Guillermo. We use mdtraj for
> I/O and most of the featurization, which I think uses nm by default, and
> we just pass those distances on.
> 
> Am 25/09/15 um 14:58 schrieb Stefan:
> 
> > Are the units produced by featurizer.add_distance actually in
> > nanometers? I assumed it would return distances in Angstrom but it
> > consistently reports me 1/10th of the Angstrom distance I get in my code.
> > Is it maybe an issue with reading the xtc files?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/565.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/565#issuecomment-143228019.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by stefdoerr** [comment]
Okay, thanks :) Maybe add it to the docs so people don't get confused

**Comment by gph82** [comment]
will do

On 09/25/2015 04:43 PM, Stefan wrote:

> Okay, thanks :) Maybe add it to the docs so people don't get confused
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/565#issuecomment-143241913.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776
