### ISSUE TITLE
TICA input data types

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#566]
The implementation of TICA in pyEMMA only accepts float arrays. However I have had some success in the past using TICA on protein-ligand contacts (although I do find it weird, given how coarse-grained contacts are).
So what if I want to feed it a sparse boolean matrix? I tried converting my data to float but it fills up the memory. 
Would it make sense to extend it to accept more data types as input?

**Comment by gph82** [comment]
Hi Stefan, this feature will be added in short. Please have patience ;)

On 09/25/2015 03:56 PM, Stefan wrote:

> The implementation of TICA in pyEMMA only accepts float arrays. However I have
> had some success in the past using TICA on protein-ligand contacts (although I
> do find it weird, given how coarse-grained contacts are).
> So what if I want to feed it a sparse boolean matrix? I tried converting my data
> to float but it fills up the memory.
> Would it make sense to extend it to accept more data types as input?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/566.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by giadefa** [comment]
Hi, Guillermo,
sorry when is short? days, weeks? Just to understand what we need to do (eventually do our own) as we use contacts all the time.

**Comment by gph82** [comment]
We're talking about two different things: "sparse" and "boolean". The sparse feature we have ready just needs to be pulled to devel (I am not the owner of the repo in which we developed that feature). 
That will get done next week no problem. 

The "boolean", by which I guess you mean some nd.array of type=int, will take a bit more time. As of now that is all the info i can provide.

In any event, should not be longer two weeks or so.

**Comment by giadefa** [comment]
sparse int would be fine

**Comment by gph82** [comment]
great, we're working on these things now.

As for now, if you run into memory problems, which typically the use of 
contact-schemes of the type "all" (http://goo.gl/1djllV) can generate, a clever 
use of thresholding and chunksize can help (in my experience)

On 09/25/2015 05:54 PM, giadefa wrote:

> sparse int would be fine
> 
> On Fri, Sep 25, 2015 at 5:10 PM, Guillermo Pérez-Hernández <
> notifications@github.com> wrote:
> 
> > We're talking about two different things: "sparse" and "boolean". The
> > sparse feature we have ready just needs to be pulled to devel (I am not the
> > owner of the repo in which we developed that feature).
> > That will get done next week no problem.
> > 
> > The "boolean", by which I guess you mean some nd.array of type=int, will
> > take a bit more time. As of now that is all the info i can provide.
> > 
> > In any event, should not be longer two weeks or so.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/566#issuecomment-143248398.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/566#issuecomment-143259814.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776

**Comment by gph82** [comment]
Hi, @giadefa and @stefdoerr , we're reviewing part of the sparse-featurizer here #569

**Comment by franknoe** [comment]
I'm a fan of extending features from dense to sparse matrices. That 
would not only save memory but computation timewhen with sparse 
coordinates such as contacts. We would have to make some changes to the 
Transformer object. If the consuming transformer can't deal with sparse 
arrays, we would need to transform the feature chunks to dense before 
feeding them into the consuming transformer (as a fallback option).

I don't understand why you are having memory problems. In PyEMMA, 
trajectories are streamed in chunks, so it sounds unlikely that you can 
get a memory overflow. Are you trying to load full trajectories in your 
usage of PyEMMA?

Am 25/09/15 um 15:56 schrieb Stefan:

> The implementation of TICA in pyEMMA only accepts float arrays. 
> However I have had some success in the past using TICA on 
> protein-ligand contacts (although I do find it weird, given how 
> coarse-grained contacts are).
> So what if I want to feed it a sparse boolean matrix? I tried 
> converting my data to float but it fills up the memory.
> Would it make sense to extend it to accept more data types as input?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/566.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
I do the featurization myself and store all featurized trajectories in
memory. Hence the memory problem :)

**Comment by franknoe** [comment]
I see. Yes, I think accepting a sparse matrix is the way to go.

Am 26/10/15 um 10:01 schrieb Stefan:

> I do the featurization myself and store all featurized trajectories in
> memory. Hence the memory problem :)
> 
> On Sun, Oct 25, 2015 at 5:59 PM, Frank Noe notifications@github.com 
> wrote:
> 
> > I'm a fan of extending features from dense to sparse matrices. That
> > would not only save memory but computation timewhen with sparse
> > coordinates such as contacts. We would have to make some changes to the
> > Transformer object. If the consuming transformer can't deal with sparse
> > arrays, we would need to transform the feature chunks to dense before
> > feeding them into the consuming transformer (as a fallback option).
> > 
> > I don't understand why you are having memory problems. In PyEMMA,
> > trajectories are streamed in chunks, so it sounds unlikely that you can
> > get a memory overflow. Are you trying to load full trajectories in your
> > usage of PyEMMA?
> > 
> > Am 25/09/15 um 15:56 schrieb Stefan:
> > 
> > > The implementation of TICA in pyEMMA only accepts float arrays.
> > > However I have had some success in the past using TICA on
> > > protein-ligand contacts (although I do find it weird, given how
> > > coarse-grained contacts are).
> > > So what if I want to feed it a sparse boolean matrix? I tried
> > > converting my data to float but it fills up the memory.
> > > Would it make sense to extend it to accept more data types as input?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/markovmodel/PyEMMA/issues/566.
> > 
> > ## 
> > 
> > ---
> > 
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> > 
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > 
> > ## Mail: Arnimallee 6, 14195 Berlin, Germany
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/markovmodel/PyEMMA/issues/566#issuecomment-150942553.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/566#issuecomment-151066957.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
@stefdoerr Writing a "ScipySparseReader" should be pretty straight forward with the new infrastructure. I'd be happy to accept a PR for that.

**Comment by franknoe** [comment]
covartools automatically uses sparsity if it's present. There is not much speed to gain by using sparse matrices at the TICA level (but much to loose). The memory issue that Stefan is facing is mostly easily solved by implementing a partial_fit (which offers essentially a workaround for people that don't want to use our StreamingEstimator because they might read their data not through PyEMMA).

So I think this can be closed.

**Comment by marscher** [comment]
ok
