### ISSUE TITLE
Consider trajectory weights for TICA/PCA

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#570]
Simulations started from out-of-equilibrium distributions sometimes come with the possibility to estimate trajectory weights (sometimes through an independent method that PyEMMA doesn't need to know about). It would be good if estimators such as the covariance estimator in TICA/PCA could take such weights into account. Suggested by @euhruska.

The quick solution would be to add weights to lines 278-279, 289, 306, 332, 334 of the TICA module and give these weights as an input to the Transformer constructor, but I have the feeling that we should first think about a refactor that separates Estimators (e.g. covariance matrix estimator) and Transformers (e.g. linear or affine transform with given transformation matrix) before making the code even more complicated.

**Comment by marscher** [comment]
closing in favor of #749
