### ISSUE TITLE
Support fragmented trajectory input

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#572]
Anton trajectories are generally segmented into multiple parts. Also in other applications this might happen, e.g. when different trajectory parts are being produced on different machines (e.g. GPUgrid), or simply because a simulation had crashed and been restarted. In some of these cases it is very annoying to have to concatenate the trajectory (e.g. in the Anton case, where you would create a huge file and double the required disk space if you wanna keep your original snippets).

It could thus be useful to allow fragmented trajectory input into PyEMMA, without having to manually concatenate the fragments beforehand. Since we already allow chunked trajectory processing, I imagine this is not very difficult. However, I am not sure how to handle this on the API level. If the options are just either many separate trajectories or a single fragmented trajectory, then it's easy because we could just introduce a flag `concatenate=False` into `source` and `load`, but if several fragmented trajectories can be used, it may become a mess (e.g. dealing with lists of lists...).

**Comment by marscher** [comment]
We can also provide a naming pattern on API level, since I guess one 
would organize fragmented trajectories according to a certain naming 
convention. If the user provides this pattern, the reader can then group 
these transparently.

Of course this assumes, that the naming pattern is consistent, because 
there is no way to check this automatically.

Otherwise one could give a dictionary {index: [trajs] } to set up the 
mapping.

**Comment by franknoe** [comment]
The naming pattern idea sounds a bit dangerous. On the other hand, 
providing a service function that generates a list of filenames or dict 
from a naming pattern would be fair, because that way you can still 
inspect the result before reading.

I've not completely understood the dict idea. Currently, we specify 
input by a list of strings, i.e. usually 1 string = 1 trajectory. Do you 
mean to replace a string (optionally) by a dict? Isn't that even more 
complex than just supplying a list of string for a fragmented file? Or 
do you mean to replace the current list of strings (optionally) by a 
dict? Then I don't understand what {index: [trajs] } are. What's the index?

Suppose you have two trajectories, and the first one is fragmented into 
two pieces, i.e.:

```
traj1_part1.xtc
traj1_part2.xtc
traj2.xtc
```

How do you suggest to encode reading these?

Am 01/10/15 um 18:11 schrieb Martin K. Scherer:

> We can also provide a naming pattern on API level, since I guess one
> would organize fragmented trajectories according to a certain naming
> convention. If the user provides this pattern, the reader can then group
> these transparently.
> 
> Of course this assumes, that the naming pattern is consistent, because
> there is no way to check this automatically.
> 
> Otherwise one could give a dictionary {index: [trajs] } to set up the
> mapping.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/572#issuecomment-144774550.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
You're right, we do not need a dictionary with an index, since a list already has this implicitly. A utility function can be provided to create the following nested lists for the input data:

``` python
[['traj1_part1.xtc', 'traj1_part2.xtc']], ['traj2.xtc']]
```

We could use to longest common prefix to match these. Or use something more complex like Jaro-Winkler distance, which measures the edit-distance between two strings and takes the common prefix into account.

**Comment by franknoe** [comment]
Alright, so we would support lists of lists. But we should still support 
flat lists, i.e.

```

[['traj1_part1.xtc','traj1_part2.xtc']],'traj2.xtc']

```

should also work. I think we can do this right away. I'm less sure about 
the utility function, but the above functionality would already help people.

Am 06/10/15 um 16:38 schrieb Martin K. Scherer:

> You're right, we do not need a dictionary with an index, since a list 
> already has this implicitly. A utility function can be provided to 
> create the following nested lists for the input data:
> 
> [['traj1_part1.xtc','traj1_part2.xtc']], ['traj2.xtc']]
> 
> We could use to longest common prefix to match these. Or use something 
> more complex like Jaro-Winkler distance, which measures the 
> edit-distance between two strings and takes the common prefix into 
> account.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/572#issuecomment-145876643.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
It turned out that implementing this in the current design supporting lagged, stridden chunk based access is rather difficult. Maybe @clonker or @fabian-paul can also comment on this. We should add this use case to the feature list of #604 in the wiki to consider it while drafting the new design.

**Comment by franknoe** [comment]
OK!

Am 05/11/15 um 11:58 schrieb Martin K. Scherer:

> It turned out that implementing this in the current design supporting 
> lagged, stridden chunk based access is rather difficult. Maybe 
> @clonker https://github.com/clonker or @fabian-paul 
> https://github.com/fabian-paul can also comment on this. We should 
> add this use case to the feature list of #604 
> https://github.com/markovmodel/PyEMMA/issues/604 in the wiki to 
> consider it while drafting the new design.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/572#issuecomment-154030223.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
BTW, if you feel that there is a more convenient way of making these 
development notes than the github wiki, feel free to suggest something 
else. I don't like it very much, but I also haven't found a more 
convenient and integrated solution.

Am 05/11/15 um 11:58 schrieb Martin K. Scherer:

> It turned out that implementing this in the current design supporting 
> lagged, stridden chunk based access is rather difficult. Maybe 
> @clonker https://github.com/clonker or @fabian-paul 
> https://github.com/fabian-paul can also comment on this. We should 
> add this use case to the feature list of #604 
> https://github.com/markovmodel/PyEMMA/issues/604 in the wiki to 
> consider it while drafting the new design.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/572#issuecomment-154030223.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
If there is a nice editor to work with, I'd be fine with using a wiki. Since Github wikis are used alot and it is markdown based, we should be able to find a good one.

**Comment by franknoe** [comment]
The text editing is not really a problem. What I found particularly 
annoying is the complicated and non-integrated way of getting figures in.
I'd love to have a way to write equations as well, but that is a less 
important aspect.

Am 05/11/15 um 12:02 schrieb Martin K. Scherer:

> If there is a nice editor to work with, I'd be fine with using a wiki. 
> Since Github wikis are used alot and it is markdown based, we should 
> be able to find a good one.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/572#issuecomment-154030966.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
done
