### ISSUE TITLE
[clustering.interface]: Transformer dimensions always 1? 

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#575]
The dimension of the clustering algorithm is hard-coded to be always = 1 (https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/clustering/interface.py#L135) 

I don't know why but I assume there is a good reason. 

Getting dimension=1 on the clustering object was a bit alarming, as if the clustering had actually occurred in a 1D-space by mistake. 

However: 

``` python
print cl_km.dimension()
print cl_km.clustercenters.shape
#1
# (2000, 178)
```

Perhaps the actual dimension can be included as a string in the  .describe() method?:

``` python
print cl_km.describe()
# [Kmeans, k=2000]
# Could be changed to sth like [Kmeans, k=2000, dim=178]
```

**Comment by franknoe** [comment]
1 is correct, because it's a transformer giving you a Tx1 array. You 
could argue whether a Clustering should be a Transformer, but that's a 
code design issue.

Am 09/10/15 um 11:58 schrieb Guillermo Pérez-Hernández:

> The dimension of the clustering algorithm is hard-coded to be always = 
> 1 
> (https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/clustering/interface.py#L135) 
> 
> I don't know why but I assume there is a good reason.
> 
> Getting dimension=1 on the clustering object was a bit alarming, as if 
> the clustering had actually occurred in a 1D-space by mistake.
> 
> However:
> 
> print  cl_km.dimension()
> print  cl_km.clustercenters.shape
> 
> # 1
> 
> # (2000, 178)
> 
> Perhaps the actual dimension can be included as a string in the 
> .describe() method?:
> 
> print  cl_km.describe()
> 
> # [Kmeans, k=2000]
> 
> # Could be changed to sth like [Kmeans, k=2000, dim=178]
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/575.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
I did not say it was incorrect. I am not arguing. I am saying, do we want it in the description?

**Comment by franknoe** [comment]
Ah, now I see what you mean. dimension() is always the dimension of the 
output.
If I remember correctly, there is no defined way of the describe() 
string in Transformers (as opposed to the Featurizer), it is purely 
informative. Then what you want should be clearly marked as input 
dimension, i.e. input_dim=178

Am 09/10/15 um 11:58 schrieb Guillermo Pérez-Hernández:

> The dimension of the clustering algorithm is hard-coded to be always = 
> 1 
> (https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/clustering/interface.py#L135) 
> 
> I don't know why but I assume there is a good reason.
> 
> Getting dimension=1 on the clustering object was a bit alarming, as if 
> the clustering had actually occurred in a 1D-space by mistake.
> 
> However:
> 
> print  cl_km.dimension()
> print  cl_km.clustercenters.shape
> 
> # 1
> 
> # (2000, 178)
> 
> Perhaps the actual dimension can be included as a string in the 
> .describe() method?:
> 
> print  cl_km.describe()
> 
> # [Kmeans, k=2000]
> 
> # Could be changed to sth like [Kmeans, k=2000, dim=178]
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/575.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
Yupp, something along those lines, but only if we feel it's necessary design-wise. 

I mean, one can always look up the actual dimensions of the clustercenters themselves. However, the current behavior, though strictly correct (BTW, thanks, now I know why ;), leads to the following:

``` python
print my_TICA.dimension()
print cl_km.dimension()
178
1
```

which is a bit misleading since my_TICA was used to instantiate the clustering object. So, since we already have a "describe" method, I can just add the "input_dim=178" to the string.

**Comment by franknoe** [comment]
ok

Am 09/10/15 um 12:29 schrieb Guillermo Pérez-Hernández:

> Yupp, something along those lines, but only if we feel it's necessary 
> design-wise.
> 
> I mean, one can always look up the actual dimensions of the 
> clustercenters themselves. However, the current behavior, though 
> strictly correct (BTW, thanks, now I know why ;), leads to the following:
> 
> print  my_TICA.dimension()
> print  cl_km.dimension()
> 178
> 1
> 
> which is a bit misleading since my_TICA was used to instantiate the 
> clustering object. So, since we already have a "describe" method, I 
> can just add the "input_dim=178" to the string.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/575#issuecomment-146828682.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
