### ISSUE TITLE
Memory consumption of pyemma.msm.its

### ISSUE THREAD

**Issue by giopina** [markovmodel/PyEMMA#583]
The api call to pyemma.msm.its, with errors='bayes', results in huge memory usage, expecially when using many lagtimes and increasing the parameter nsamples. Can this be caused by the fact that the object is storing all the sampled models?

**Comment by franknoe** [comment]
Yes, correct. It would be possible to not store all objects and throw 
them away once the uncertainties have been computed, but this would 
require some refactoring, because right now ImpliedTimescales first 
estimates all models and then analyzes them. That would need to be 
iterated.
In general, 100 samples should be enough because they are approximately 
uncorrelated. How many Markov states do you have?

Am 21/10/15 um 11:20 schrieb giopina:

> The api call to pyemma.msm.its, with errors='bayes', results in huge 
> memory usage, expecially when using many lagtimes and increasing the 
> parameter nsamples. Can this be caused by the fact that the object is 
> storing all the sampled models?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/583.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
Hi,

I think that could be the case. To circumvent this you can do the following

i) Loop over all lagtimes
    ii) For each lagtime compute the largest connected count-matrix (msmtools.estimation.cmatrix,   msmtools.estimation.connected_cmatrix)
   iii) Create a sampler object for the current count-matrix (msmtools.estimation.tmatrix_sampler)
   iv) Loop over the number of timescales-samples you want to have
      v) Call sampler.sample() to get a single transition matrix
      vi) Compute the timescales for the just sampled transition matrix
      vii) Store the sampled timescales

**Comment by giopina** [comment]
I'm using 1000 states and 200 samples.

**Comment by franknoe** [comment]
1000 states is a lot, probably way to much for your data. sqrt(N) is a 
good rule of thumb, where N is the number of samples. The memory scales 
as K*N^2, where K is the number of samples in your case.

Benjamin: in principle we should be able to use the sparse=True mode 
here, which would be a minimal change to do. Do you think that should 
work or is there any functionality missing for using sparsity in this 
context?

Am 21/10/15 um 11:27 schrieb giopina:

> I'm using 1000 states and 200 samples.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/583#issuecomment-149834262.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by giopina** [comment]
@franknoe The convergence of the implied timescales seems to keep improving when passing going from 100 to 500 and to 1000 states. We can have a look to them together if you want.

@trendelkampschroer  Your solution seems nice but I'm not sure about how to set the same counting mode that I have in the pyemma.msm.its case (which I think is "effective" when using errors='bayes'). In the msmtools.estimation.cmatrix I can only set sliding=True or False (where False should correspond to the 'sample' count mode)

**Comment by trendelkampschroer** [comment]
@franknoe: Yes it should be possible to store sparse MSMs rather than dense MSMs.

the sampler works only with dense matrices, but direct conversion of the dense sample into a sparse one is not a problem.

**Comment by marscher** [comment]
If the model is not sparse, there will be no benefit (it could consume even more memory). So the best solution would be to just store the timescales in its.

The refactoring would involve the evaluation of the model directly after its estimation (and we need to ensure, the returned arrays have a compatible shape).

**Comment by trendelkampschroer** [comment]
@marscher: The point is exactly this. Draw a random, dense transition matrix, convert to sparse, create a sparse MSM object

**Comment by trendelkampschroer** [comment]
@giopina: You can use msmtools.estimation.effective_count_matrix instead of msmtools.estimation.cmatrix to be consistent with the ITS object

**Comment by franknoe** [comment]
Am 21/10/15 um 15:15 schrieb Benjamin Trendelkamp-Schroer:

> @franknoe https://github.com/franknoe: Yes it should be possible to 
> store sparse MSMs rather than dense MSMs.
> 
> the sampler works only with dense matrices, but direct conversion of 
> the dense sample into a sparse one is not a problem.
> 
> Haven't we used the sparse sampling code that I wrote at some point? Or 
> do you mean that the matrices get converted to dense at some point?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/583#issuecomment-149890305.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
There is an somewhat easier solution along the lines of Benjamin's 
suggestion. You can use msm.bayesian_markov_model in PyEMMA, and just 
run them for a set of lag times. For each resulting Markov model you can 
get the timescales by using `timescales()` and the sampled 
confidence intervals by `sample_conf('timescales')`. You can store 
these results and then throw the model away to save memory. Should be 
doable in a few lines.

Am 21/10/15 um 12:20 schrieb giopina:

> @franknoe https://github.com/franknoe The convergence of the implied 
> timescales seems to keep improving when passing going from 100 to 500 
> and to 1000 states. We can have a look to them together if you want.
> 
> @trendelkampschroer https://github.com/trendelkampschroer Your 
> solution seems nice but I'm not sure about how to set the same 
> counting mode that I have in the pyemma.msm.its case (which I think is 
> "effective" when using errors='bayes'). In the 
> msmtools.estimation.cmatrix I can only set sliding=True or False 
> (where False should correspond to the 'sample' count mode)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/583#issuecomment-149847733.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
