### ISSUE TITLE
featurizer._pair_wise_input uses itertools.combinations

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#585]
This function is intended to iterate over the output (generator pattern), but to create an index array it is prohibitively memory consuming, since the intermediate has to be converted to a Python list (which will create a Python object for every index involved in the pairing).

There must be a simple pure numpy solution to this.

**Comment by marscher** [comment]
``` python
contact_pairs_npy = np.transpose([np.tile(x, len(y)), numpy.repeat(y, len(x))])
contact_pairs_iter =  np.array([pair for pair in itertools.product(x,y)])

assert np.all( contact_pairs_npy == contact_pairs_iter)

%timeit np.transpose([np.tile(x, len(y)), numpy.repeat(y, len(x))])
1000 loops, best of 3: 1.83 ms per loop

%timeit contact_pairs_iter =  np.array([pair for pair in itertools.product(x,y)])
10 loops, best of 3: 59.8 ms per loop
```

The timing is negligible but the memory consumption of the numpy version is much lower than the pythonic one.

**Comment by gph82** [comment]
OK, then let's do it with numpy.

On 10/27/2015 04:15 PM, Martin K. Scherer wrote:

> contact_pairs_npy = np.transpose([np.tile(x, len(y)), numpy.repeat(y, len(x))])
> contact_pairs_iter =  np.array([pair for pair in itertools.product(x,y)])
> 
> assert np.all( contact_pairs_npy == contact_pairs_iter)
> 
> %timeit np.transpose([np.tile(x, len(y)), numpy.repeat(y, len(x))])
> 1000 loops, best of 3: 1.83 ms per loop
> 
> %timeit contact_pairs_iter =  np.array([pair for pair in itertools.product(x,y)])
> 10 loops, best of 3: 59.8 ms per loop
> 
> The timing is negligible but the memory consumption of the numpy version
> is much lower than the pythonic one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/585#issuecomment-151536750.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75775

## http://userpage.fu-berlin.de/gph82/
