### ISSUE TITLE
statistical efficiency function copy pasted from/to msmtools

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#593]
We should only keep the version in msmtools to make this more maintainable.

**Comment by franknoe** [comment]
Where is it copy/pasted in PyEMMA?

Am 27/10/15 um 17:38 schrieb Martin K. Scherer:

> We should only keep the version in msmtools to make this more 
> maintainable.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/593.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 27.10.2015 um 17:40 schrieb Frank Noe:

> Where is it copy/pasted in PyEMMA?

pyemma.util.statistics

**Comment by franknoe** [comment]
I see. It's not really a msmtools thing either, but would rather go to a 
stats superpackage that we haven't yet built. I'd leave this as is for now.

Am 27/10/15 um 18:41 schrieb Martin K. Scherer:

> Am 27.10.2015 um 17:40 schrieb Frank Noe:
> 
> > Where is it copy/pasted in PyEMMA?
> 
> pyemma.util.statistics
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/593#issuecomment-151582921.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
