### ISSUE TITLE
msm.estimators.estimated_msm.effective_count_matrix: store Ceff_full?

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#595]
otherwise it looks like it will compute it from scratch every time one calls it, right?  

Can we do sth like

``` python
if  self._Ceff_full is None:
    self._Ceff_full = msmest.effective_count_matrix(self._dtrajs_full, self.lag)
```

**Comment by franknoe** [comment]
if _Cell_full is set in the initializer, yes. Otherwise use getattr.
