### ISSUE TITLE
set bhmm==0.5.2 in setup

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#599]
The new release should use the bhmm bugfix, and for that the bhmm version number should be fixed to 0.5.2.

Addition to release file:
- Fixed bug in hidden MSMs that occurred with trajectories of different lengths

**Comment by marscher** [comment]
I'll suggest to pin it to <0.6, so if we have to release a micro or minor of bhmm to fix bugs, we are not forced to release a new pyemma version. If you intend to break the api of bhmm, we will release 0.6.

**Comment by franknoe** [comment]
OK, good call!

Am 30/10/15 um 15:52 schrieb Martin K. Scherer:

> I'll suggest to pin it to <0.6, so if we have to release a micro or 
> minor of bhmm to fix bugs, we are not forced to release a new pyemma 
> version. If you intend to break the api of bhmm, we will release 0.6.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/599#issuecomment-152546429.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Wait ... wouldn't that prevent a re-installation if one has 0.5.1 already?

Am 30/10/15 um 15:52 schrieb Martin K. Scherer:

> I'll suggest to pin it to <0.6, so if we have to release a micro or 
> minor of bhmm to fix bugs, we are not forced to release a new pyemma 
> version. If you intend to break the api of bhmm, we will release 0.6.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/599#issuecomment-152546429.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
don't think so, conda will just trigger an upgrade of bhmm then.

**Comment by franknoe** [comment]
ok

Am 30/10/15 um 15:57 schrieb Martin K. Scherer:

> don't think so, conda will just trigger an upgrade of bhmm then.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/599#issuecomment-152547741.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
