### ISSUE TITLE
pyemma.msm.flux.pathways hangs

### ISSUE THREAD

**Issue by trendelkampschroer** [markovmodel/PyEMMA#60]
Hi,

I have tried to perform a pathway decomposition of a system with ~ 2100 states. The algorithm fails with 

 line 76, in nextPathway
    p = self.PD.nextPathway() # returns int[]
jpype._jexception.ArrayIndexOutOfBoundsExceptionPyRaisable: java.lang.ArrayIndexOutOfBoundsException: 1426

 I can gladly provide the estimated transition matrix as well as with the definition of the starting set, A, and the target set, B for debugging.

Ben

**Comment by fabian-paul** [comment]
try:
         p = self.PD.nextpathway()
     except JavaException as je:
          print je.stacktrace()

**Comment by marscher** [comment]
since we have a new impl now, i'm going to close this now :+1:
