### ISSUE TITLE
Fluxes on coarse-grained model

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#601]
Hi, I was looking at your tutorial for Benzamidine and I wanted to try the fluxes plot at the end. 
I am however not using a HMM, I am using a normal MSM with pcca.
It seems that msm.tpt given my normal MSM calculates the fluxes between microstates not macrostates. Also it does not have an option to calculate the fluxes between macrostates. 
So I assume msm.tpt only gives macrostate fluxes when given an HMSM?

**Comment by gph82** [comment]
Hi Stefan,

you can coarse grain the tpt object on the pcca sets.

http://www.emma-project.org/latest/api/generated/msmtools.flux.ReactiveFlux.html#msmtools.flux.ReactiveFlux.coarse_grain

On 10/30/2015 05:16 PM, Stefan wrote:

> Hi, I was looking at your tutorial for Benzamidine and I wanted to try
> the fluxes plot at the end.
> I am however not using a HMM, I am using a normal MSM with pcca.
> It seems that msm.tpt given my normal MSM calculates the fluxes between
> microstates not macrostates. Also it does not have an option to
> calculate the fluxes between macrostates.
> So I assume msm.tpt only gives macrostate fluxes when given an HMSM?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/601.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75775

## http://userpage.fu-berlin.de/gph82/

**Comment by stefdoerr** [comment]
Ah perfect, I was looking for an option in msm.tpt not in its result.
Thanks!

**Comment by stefdoerr** [comment]
But wait, then if I do
tpt = msm.tpt(msm, [0], [1])
tpt.coarse_grain(msm.metastable_sets)

Then does the 0 and 1 correspond to microstate or macrostate indexes?

**Comment by gph82** [comment]
macro, but it has changed the order (or even added more sets), so that the set that contains [A] is 0 and [B]  is 1. From the docs:
Returns:    (sets, tpt) – sets contains the sets tpt is computed on. The tpt states of the new tpt object correspond to these sets of states in this order. Sets might be identical, if the user has already provided a complete partition that respects the boundary between A, B and the intermediates. If not, Sets will have more members than provided by the user, containing the “remainder” states and reflecting the splitting at the A and B boundaries. tpt contains a new tpt object for the coarse-grained flux. All its quantities (gross_flux, net_flux, A, B, committor, backward_committor) are coarse-grained to sets.

**Comment by gph82** [comment]
@stefdoerr , do we close this?

**Comment by stefdoerr** [comment]
Well it's not an "issue" so you can close it. 

But I don't really understand the documentation on this (how the metastable sets would change).
so if I give 
`tpt = msm.tpt(msm, [3], [5])`
it will change the id of my macrostates from 3 to 0 and from 5 to 1? Why and how can I get the matching?

> Sets might be identical, if the user has already provided a complete partition that respects the boundary between A, B and the intermediates.

Well, A and B are my macrostate indexes so how could the states not respect the boundary between A and B? How would you know that they don't, since I only gave you the metastable sets and the indexes of the source and sink set.

**Comment by gph82** [comment]
Hi Stefan, this really weird? What does "msm" mean? is it an object or a pyemma namespace?

**Comment by gph82** [comment]
And, [3] and [5]...are the microstate indices or macrostate indices...and if macrostate...of what macrostate definition exactly? Can you provide a minimal working example of what troubles you?

**Comment by stefdoerr** [comment]
Eh yes ok sorry I made the example confusing

``` python
mymodel = msm.estimate_markov_model(dtraj, lag)
mymodel.pcca(8)
# Now I want to know the fluxes between macrostate 5 and 7
tpt = msm.tpt(mymodel, [5], [7]) 
z = tpt.coarse_grain(mymodel.metastable_sets)
mplt.plot_flux(z[1], show_committor=False)
```

**Comment by gph82** [comment]
Yeah, I think I spot  a problem already...[5] and [7] are understood in terms of microstates, not pcca sets...you need to coarse grain the model first. If you notice, the quantitites of the tpt object have the same number of microstates as your original msm

**Comment by stefdoerr** [comment]
But I did coarse-grain the model by calling `mymodel.pcca(8)` no?

**Comment by gph82** [comment]
well...yes and no. You provided the msm-object with a definition of macrostates (mymsm.metastable..), but the object itself is still defined in micro. Check the size of its quantities (P, pi...etc). From the docs:
"After calling this method you can access metastable_memberships(), metastable_distributions(), metastable_sets() and metastable_assignments()." But the object is _still_ in microstates

**Comment by gph82** [comment]
What you want is the the pcca object itself, which is returned, like this:
mypcca = mymodel.pcca(8)
and then you play around with mypcca
http://www.emma-project.org/latest/api/generated/pyemma.msm.PCCA.html#pyemma.msm.PCCA

**Comment by stefdoerr** [comment]
Yes sure, I saw those quantities. I just assumed that if I gave tpt my metastable_sets it would know how to coarse-grain the model.

So if I want to create a coarse-grained model with my pcca metastable sets how would I make it? Should I map the `dtraj` to macrostates and call again 

```
myCoarseModel = msm.estimate_markov_model(macro_dtraj, lag)
```

or is there some more elegant solution?

**Comment by gph82** [comment]
yeah, there is, see above

**Comment by stefdoerr** [comment]
Ah ok perfect thanks

**Comment by stefdoerr** [comment]
you can close now ;)

**Comment by gph82** [comment]
feel free to reopen if this is not clear!

**Comment by gph82** [comment]
One last thing, you can coarse the tpt object itself:
http://www.emma-project.org/latest/api/generated/msmtools.flux.ReactiveFlux.html#msmtools.flux.ReactiveFlux.coarse_grain

**Comment by stefdoerr** [comment]
Well that's what I tried before at:
https://github.com/markovmodel/PyEMMA/issues/601#issuecomment-153022785
But then I didn't know if my 5 and 7 indexes corresponded to micro or macrostates

**Comment by stefdoerr** [comment]
> What you want is the the pcca object itself, which is returned, like this:
> mypcca = mymodel.pcca(8)
> and then you play around with mypcca
> http://www.emma-project.org/latest/api/generated/pyemma.msm.PCCA.html#pyemma.msm.PCCA

But mypcca is not a MSM class object. So I cannot pass it to msm.tpt

``` python
mymodel = msm.estimate_markov_model(dtraj, lag)
mypcca = mymodel.pcca(8)

tpt = msm.tpt(mypcca, [5], [7])  # ERROR: 'PCCA' object has no attribute 'stationary_distribution'
mplt.plot_flux(tpt[1], show_committor=False)
```

So how do I really obtain a coarse grained MSM class object?

PS. storing the metastable sets both on the PCCA class and the MSM class is quite confusing...

**Comment by ppxasjsm** [comment]
Has this question ever been solved? I seem to have encountered the same problem just now and don't quite understand some of the explanation above. I am trying to understand how my coarse grained fluxes correspond to my PCCA sets, so I can actually plot total fluxes in a meaningful way that I know which structure belongs to which set. Indexing seems to have changed, but I don't quite understand how I can achieve the mapping. 

As in:
```python
fluxAB_mut = msm.tpt(M_mut_bayes, pcca_sets_mut[1], pcca_sets_mut[2])
cg, cgflux_mut = fluxAB_mut.coarse_grain(pcca_sets_mut)
mplt.plot_flux(cgflux_mut,flux_scale=100.0/fluxAB_mut.total_flux, arrow_label_format="%3.2f", show_committor=False,state_scale=0.1)
```

The plot looks like this:
![example](https://user-images.githubusercontent.com/3668316/29879907-53f49ddc-8d9e-11e7-8f72-1b9a16a385a7.png)

How do I know which PCCA state corresponds to 0 and which one to 1, or how can I verify that A and B are indeed pcca_sets_mut[1] and pcca_sets_mut[2].

**Comment by marscher** [comment]
since you've put in your set A as pcca_sets_mut[1] and B as pcca_sets_mut[2], these are state labels A and B. The actual indices of the flux matrices remain unchanged, we just changed the labels in the plotting. Do you think this is causing more confusion?

**Comment by ppxasjsm** [comment]
So ppca[0] ->0 and pcca[3]->1? And based on my input pcca[1]-> A pcca[2]-> B
Looking at cgflux_mut object things get a bit confusing to me. 
```python
cgflux_mut.A
>>>[0]
cgflux_mut.B
>>>[3]
```
The above output I find confusing.

**Comment by marscher** [comment]
yes that is indeed very confusing. We should maintain this order somehow. I'll have to look into the code for this.

**Comment by thempel** [comment]
(As a temporary workaround, you could compare the microstate indices returned by fluxAB_mut.coarse_grain(), `cg' in your code, with the pcca sets with some set comparison function, e.g. with numpy.setdiff1d(). But I agree, it's very confusing!)
