### ISSUE TITLE
Redesign reading/featurization/transformation concept

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#604]
In order to get towards a more general and efficient concept of reading data (either streamed or random access), featurizing it (using dense/sparse, floats, ints or bools, whichever is more suitable), and controlling the estimation logic (one or multiple passes, one or multiple data consumers), I have started a Wiki page with some brainstorming:

https://github.com/markovmodel/PyEMMA/wiki

**Comment by marscher** [comment]
I think we've handled that via the coordinates refactoring branch merged already in 2.1

**Comment by franknoe** [comment]
yes

Am 13/05/16 um 02:31 schrieb Martin K. Scherer:

> I think we've handled that via the coordinates refactoring branch 
> merged already in 2.1
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/604#issuecomment-218923216

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
