### ISSUE TITLE
Large lag times cause error

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#606]
When using msm.its with a large lag-time I get the error: 

```
msmtools/estimation/sparse/mle_trev.pyx in msmtools.estimation.sparse.mle_trev.mle_trev (msmtools/estimation/sparse/mle_trev.c:2008)()
Exception: Some row and corresponding column of C have zero counts.
```

Indeed, if I debug, the active set consists of a single state and the C matrix is a single integer (because the lag was 1199 with 1200 length frame trajectories). 
Could you handle this in a more soft manner than throwing an error? Like setting the timescale to 0 or NaN and possibly throwing a warning? 
When doing calculations unattended this causes the program to stop which is quite impractical.

**Comment by marscher** [comment]
> Could you handle this in a more soft manner than throwing an error? Like
> setting the timescale to 0 or NaN and possibly throwing a warning?
> When doing calculations unattended this causes the program to stop which
> is quite impractical.
> You're right, this exception should be handled accordingly.

**Comment by franknoe** [comment]
I think @fabian-paul should respond to this.

**Comment by stefdoerr** [comment]
Could this be looked at please? I just noticed that it gives an even more obscure error when running it in parallel. Took me a while to realize the problem was the C matrix. Thought it was a new bug.

``` python
import pyemma.plots as mplt
import pyemma.msm as msm
its = msm.its(model1.data.St, lags=model1._defaultLags(), errors=None, nits=10, n_jobs=4)

File "<string>", line unknown
SyntaxError: invalid or missing encoding declaration for '/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/estimation/sparse/mle_trev.cpython-34m.so'
```

**Comment by franknoe** [comment]
What's in model1._defaultLags()? Are those lags within what the 
trajectories permit?

If yes, can you provide a self-contained example to reproduce the bug? I 
think we would need the dtrajs and the lags.

Am 30/11/15 um 12:02 schrieb Stefan:

> Could this be looked at please? I just noticed that it gives an even 
> more obscure error when running it in parallel. Took me a while to 
> realize the problem was the C matrix. Thought it was a new bug.
> 
> import  pyemma.plotsas  mplt
> import  pyemma.msmas  msm
> its=  msm.its(model1.data.St,lags=model1._defaultLags(),errors=None,nits=10,n_jobs=4)
> 
> File"<string>", line unknown
> SyntaxError: invalidor  missing encoding declarationfor  '/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/estimation/sparse/mle_trev.cpython-34m.so'
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/606#issuecomment-160598670.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
Yes, the defaultLags does roughly this:

``` python
modelen = stats.mode([np.size(x, 0) for x in self.data.dat]).mode - 1 
lags = np.append(1, np.round(np.linspace(10, modelen, 25)))
```

So it calculates the mode length of all my trajectories (-1 because otherwise it was giving me a warning). Then creates a linear range from 10 to the end.
I mean sure, it's nearly pointless to test such large lag times, but in my opinion it should not give an error, just return 0s or NaNs as I said before.

I can provide you with the data but I think you can replicate it without my data by just asking for a lag time that is close to the length of your trajectories (length-1 if you want)

**Comment by stefdoerr** [comment]
Especially considering that it could happen with even lower lag times that a state ends up with 0 counts, it should not be an error.

**Comment by franknoe** [comment]
We test such a case in the unit tests. I think we need a more concrete 
example. Can you reproduce it with a simple sequence that you can post here?

Am 30/11/15 um 12:11 schrieb Stefan:

> Yes, the defaultLags does roughly this:
> 
> modelen=  stats.mode([np.size(x,0)for  xin  self.data.dat]).mode-  1  
> lags=  np.append(1, np.round(np.linspace(10, modelen,25)))
> 
> So it calculates the mode length of all my trajectories (-1 because 
> otherwise it was giving me a warning). Then creates a linear range 
> from 10 to the end.
> I mean sure, it's nearly pointless to test such large lag times, but 
> in my opinion it should not give an error, just return 0s or NaNs as I 
> said before.
> 
> I can provide you with the data but I think you can replicate it 
> without my data by just asking for a lag time that is close to the 
> length of your trajectories (length-1 if you want)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/606#issuecomment-160600289.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
``` python
import pyemma.msm as msm
arr = array([965, 908, 271, 521, 620, 821, 862, 627, 908, 746, 965, 271, 965,
       627, 603, 965,  31, 579, 150, 190])
its = msm.its([arr], lags=[19], errors=None, nits=1, n_jobs=1)
```

Is this good?

**Comment by franknoe** [comment]
thanks.

Am 30/11/15 um 12:18 schrieb Stefan:

> arr=  array([965,908,271,521,620,821,862,627,908,746,965,271,965,
>         627,603,965,31,579,150,190])
> its=  msm.its([arr],lags=[19],errors=None,nits=1,n_jobs=1)
> 
> Is this good?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/606#issuecomment-160602510.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
Seems like anything over `lag=7` gives the error in this example

**Comment by franknoe** [comment]
In these examples the connected set consist of one state, so there is no 
relaxation time scale. So it's correct that there is an error, but I 
agree that the error message is confusing.
Which behavior would be most useful in your opinion? Of course we can 
generate a different error message, but I guess you need something that 
you can catch specificially and treat it in your code.

Am 30/11/15 um 12:21 schrieb Stefan:

> Seems like anything over lag=7 gives the error in this example
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/606#issuecomment-160603260.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
The issue is that for passing a single "wrong" lag time, you don't get any results from msm.its.

Ideally for me the msm.its could throw a warning and return either a truncated array or set the values it could not compute to 0 or NaN.

Otherwise the user needs to play around with lag-time arrays until he gets one that does not produce the error.

We actually had this happen in the workshop (our fault for not testing it enough beforehand obviously) :P Finding the correct lag-time array which did not produce the error, so as to get the timescales, was frustrating.

**Comment by franknoe** [comment]
OK, we'll have a look. However, in this example I'm not sure if even 
returning NaNs or 0s is meaningful as there is no timescale for these 
settings. So how many NaNs would one return?

For your use case I would agree that going to lag times equal to the 
length of your trajectories makes little sense. In this case you have 
almost no data to work with and would usually suffer from such 
disconnectivity problems.

Am 30/11/15 um 12:32 schrieb Stefan:

> The issue is that for passing a single "wrong" lag time, you don't get 
> any results from msm.its.
> 
> Ideally for me the msm.its could throw a warning and return either a 
> truncated array or set the values it could not compute to 0 or NaN.
> 
> Otherwise the user needs to play around with lag-time arrays until he 
> gets one that does not produce the error.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/606#issuecomment-160605737.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
As many as the number of ITS the user requested.

You could preallocate the timescale array:

``` python
a = np.empty((nlags, nits))
a[:] = numpy.NAN
```

Any value that cannot be computed stays at NaN.

**Comment by franknoe** [comment]
I don't think that makes sense in all cases. If we have two states and 
the user requests 1000 lag times, do you return a big array with NaN?s I 
think an exception is the right way to handle this - it should just be 
more informative. You have to handle it either way: either by checking 
for NaNs or catching the exception (which is more typical in Python btw).

Am 30/11/15 um 12:46 schrieb Stefan:

> As many as the number of ITS the user requested.
> 
> You could preallocate the timescale array:
> 
> a=  np.empty((nlags, nits))
> a[:]=  numpy.NAN
> 
> Any value that cannot be computed stays at NaN.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/606#issuecomment-160608012.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
> If we have two states and the user requests 1000 lag times

that would produce a 1000x1 array. I guess you mean that you start with many states and in the last lag times you end up with 2 left? 

Still I don't see a problem for an array with many NaNs. NaNs don't need checking. When you plot the timescales just calculate the mean with np.nanmean and the std with np.nanstd and you're done.

Take an example when your timescale calculation takes 15 minutes. Do you really want to have to redo it from the beginning because your last X lagtimes had too few states connected?

I find it okay that the MLE estimator raises an exception, but in my opinion the exception should be handled (and ignored) by msm.its.
If msm.its really should raise an exception it should definitely report which lag-time caused the problem.

**Comment by franknoe** [comment]
I agree with you that in the case when at least some lag times are 
working, the partial result should be returned. I would only consider 
raising an exception when there is no result at all (as in your 
mini-example).

Am 30/11/15 um 13:24 schrieb Stefan:

> ```
> If we have two states and the user requests 1000 lag times
> that would produce a 1000x1 array. I guess you mean that you start
> with many states and in the last lag times you end up with 2 left?
> ```
> 
> Still I don't see a problem for an array with many NaNs. NaNs don't 
> need checking. When you plot the timescales just calculate the mean 
> with np.nanmean and the std with np.nanstd and you're done.
> 
> Take an example when your timescale calculation takes 15 minutes. Do 
> you really want to have to redo it from the beginning because your 
> last X lagtimes had too few states connected?
> 
> I find it okay that the MLE estimator raises an exception, but in my 
> opinion the exception should be handled (and ignored) by msm.its.
> If msm.its really should raise an exception it should definitely 
> report which lag-time caused the problem.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/606#issuecomment-160615732.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
