### ISSUE TITLE
PyEMMA broken with mdtraj 1.5

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#613]
PyEMMA is using hidden variables and functions in mdtraj. In the 1.5 release some of those have changed or disappeared, such that PyEMMA is broken with mdtraj 1.5. For example:

``` python
/Users/noe/data/software_projects/pyemma/pyemma/coordinates/data/featurizer.py in <module>()
     24 
     25 import mdtraj
---> 26 from mdtraj.geometry.dihedral import (_get_indices_phi,
     27                                       _get_indices_psi,
     28                                       _atom_sequence,
```

We need to avoid using hidden variables and functions. These are not API functions and we can't blame the mdtraj guys for changing those.

This needs to be fixed asap and go into 2.0.2.

**Comment by marscher** [comment]
They have reminded us that they will remove it in https://github.com/mdtraj/mdtraj/pull/972

@gph82 you were maybe surprised how fast they pushed their new release?

We can trigger a new build of Pyemma-2.0.1 with updated dependencies (mdtraj<1.5) to avoid this trouble till we have 2.0.2

**Comment by gph82** [comment]
yes, I guess that is the best solution. I thought that "lifting" code from mdtraj would be more dangerous than using hidden variables. Obviously, I was wrong :)
