### ISSUE TITLE
Chunking vs efficiency for TICA and PCA

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#616]
We are chunking data in the transformers in order to safeguard against memory problems. We had discussed early on what a good chunk size is such that you wouldn't loose efficiency by computational overheads. Clearly this depends on the algorithm and on whether I/O or the subsequent processing are time-limiting, but somehow we came up with chunksizes between 100 and 1000 depending on the data source.

Here is a study of the effect of chunking the PCA / TICA operation of taking a matrix product between two rectangular matrices. The data matrix X is of size t x m (with t data points and m dimensions), and I'm computing the matrix product X^T X. This done for many different values of m and t, and we always compute the processing time divided by t, i.e. the time per data point. Since matrix multiplication is O(m^2 t), this should ideally be constant. I've used the following test code on my Mac:

``` python
%pylab inline
M = [10, 50, 100, 500, 1000, 5000]
T = [10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000]
times = np.zeros((len(M), len(T)))
for i,m in enumerate(M):
    for j,t in enumerate(T):
        X=np.random.rand(t, m)
        nrep = max(1, 1000000/(m*t))
        t1 = time.time()
        for k in range(nrep):
            np.dot(X.T, X)
        t2 = time.time()    
        time_per_t = 1000000.0*(t2-t1)/(nrep*t)
        times[i, j] = time_per_t
        print m, t, time_per_t, 'microseconds'
```

Visualizing results as follows yields:

``` python
for i,m in enumerate(M):
    plot(T, times[i,:], label='M='+str(M[i]))
xlabel('number of samples')
ylabel('time per sample (microseconds)')
semilogx()
semilogy()
legend(ncol=2)
```

![index](https://cloud.githubusercontent.com/assets/6495810/11017763/418be568-85aa-11e5-8ee9-dd8c8c51cffa.png)
Note the logarithmic scaling. This result might be platform-dependent, but at least on my machine we need to take at least 1000, better 5000 samples (if we have them) to avoid loosing time. By choosing chunksizes of only 100 we can loose an order of magnitude in processing speed! I'm not entirely sure about the reason for this behavior. Maybe one needs a certain size combined with the algorithms being used in order to optimally use the cache.

In order to optimize the processing performance, we should probably increase default chunksizes. We could add a safety check that uses a smaller chunksize if the data would already not (or hardly) fit in free memory with the default chunk size. For data that already is in memory, we should probably refrain from chunking it at all, because that would just make the performance worse.

**Comment by marscher** [comment]
Your result shows NumPys behaviour of splitting the input array into multiple chunks and calculate the dot product with multiple threads. If the array is too small, this chunking would make no sense, therefore you will not gain any speed up due to parallelization.
How do you want to make sure that in-memory data operations will not blow up the memory if you suggest to avoid chunking at all? Because the dot product X^T X can be fairly large and will be computed for a whole trajectory.
The default of 100 (for io-based, 5000 for data in memory) may be set to low for certain data sets. It it has been chosen conservatively in terms of safety vs. speed. We once thought about having a little benchmark inside the pipeline with a very sparse set (1% of data) and set the chunksize automatically. During this benchmark we can handle MemoryError exceptions accordingly and choose smaller chunksizes then. Maximizing the chunksize without measuring the runtime internally is actually not the thing to go for, because at a certain point performance will suffer from cache misses (which will dominate the runtime again).

**Comment by franknoe** [comment]
Am 08/11/15 um 13:44 schrieb Martin K. Scherer:

> Your result shows NumPys behaviour of splitting the input array into 
> multiple chunks and calculate the dot product with multiple threads. 
> If the array is too small, this chunking would make no sense, 
> therefore you will not gain any speed up due to parallelization.
> 
> Can you explain where multiple threads are being used in this algorithm? 
> I am only computing X^T X for different shapes of X, and based on this I 
> make a statement what a good minimal size of X is in order to avoid 
> loosing efficiency. Perhaps numpy does some internal parallelization in 
> the dot product, but would that change the statement?
> 
> How do you want to make sure that in-memory data operations will not 
> blow up the memory if you suggest to avoid chunking at all? Because 
> the dot product X^T X can be fairly large and will be computed for a 
> whole trajectory.
> 
> There is no memory concern for X^T X, because that is the covariance 
> matrix which we need to store anyway (at least with the current 
> algorithms), so if X is already in memory, this aspect is not a reason 
> to do chunking.
> 
> The default of 100 (for io-based, 5000 for data in memory) may be set 
> to low for certain data sets. It it has been chosen conservatively in 
> terms of safety vs. speed.
> 
> I see - 5000 appears to be a good choice, but there is still the 
> question why we need to chunk at all when the data is in memory. I 
> remember this was a discussion point in the beginnings of the coordinate 
> package, but I forgot the details and I'm not sure if there still is an 
> issue.
> Based on the tests above, 100 looks certainly too small and will waste a 
> lot of time. I think in many cases we can easily afford to load much 
> larger chunks, and it appears reasonable to make the default chunksize 
> dependent on the feature size in order to have a fixed default memory 
> consumption for storing the features. For example, when we have 1000 
> features (which is probably a typical size), chunk sizes of 10000 (40 MB 
> as float) would use 1% of a typical main memory of 4 GB.
> 
> We once thought about having a little benchmark inside the pipeline 
> with a very sparse set (1% of data) and set the chunksize 
> automatically. During this benchmark we can handle MemoryError 
> exceptions accordingly and choose smaller chunksizes then. Maximizing 
> the chunksize without measuring the runtime internally is actually not 
> the thing to go for, because at a certain point performance will 
> suffer from cache misses (which will dominate the runtime again).
> 
> It's not so easy to predict when cache misses will occur. The BLAS dot 
> product is so ridiculously fast because it subdivides X in such a way 
> that you have a good chance for cache hits, and this algorithm does not 
> seem to suffer from cache misses when X is large. I think the benchbark 
> above demonstrates that - otherwise the runtime would become worse for 
> large T which is not observed.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/616#issuecomment-154822286.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by fabian-paul** [comment]
I think too that the chunk size should by defined in units of floating point numbers and not in units of frames. 100 frames from a three-dimensional trajectory is very different from 100 frames from a 10000-dimensional trajectory.
I suspect however that we can't just redefine the chunksize parameter because this would break some code. (I remember @clonker saying that his new code relies on the chunksize parameter).

If I remember correctly, the only requirement is that a transformer never returns _more_ frames than specified by the chunksize parameter. Is this still true?
If so, we could always use a very large chunksize. If the reader or the the featurizer notices that they are using too much memory (or are going to use too much memory) they could always return less data, independent of the chunksize. This could be used to as a workaround to implement a smarter solution right now. Does this make sense?

**Comment by franknoe** [comment]
Am 09/11/15 um 11:37 schrieb fabian-paul:

> I think too that the chunk size should by defined in units of floating 
> point numbers and not in units of frames. 100 frames from a 
> three-dimensional trajectory is very different from 100 frames from a 
> 10000-dimensional trajectory.
> I suspect however that we can't just redefine the chunksize parameter 
> because this would break some code. (I remember @clonker 
> https://github.com/clonker saying that his new code relies on the 
> chunksize parameter).
> 
> I think we could translate a memory size to the number of frames - at 
> least after the point when the data input has been set.

If we don't want to change the semantics of the chunksize parameter we 
could also set the default chunksize to None (which means "whatever is 
possible") and introduce an additional parameter for the maximum memory 
size for frames.

> If I remember correctly, the only requirement is that a transformer 
> never returns /more/ frames than specified by the chunksize parameter. 
> Is this still true?
> If so, we could always use a very large chunksize. If the reader or 
> the the featurizer notices that they are using too much memory (or are 
> going to use too much memory) they could always return less data, 
> independent of the chunksize. This could be used to as a workaround to 
> implement a smarter solution right now. Does this make sense?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/616#issuecomment-155024703.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I've changed the chunksize parameter recently to None by default in Transformers. The actual chunksize is now only known by the reader and could in principle change. So in #610 relies on constant chunksizes?

**Comment by clonker** [comment]
Not anymore, i just updated the PR such that the chunk size of the fragmented-trajectory-reader is allowed to be changed on the fly.

**Comment by marscher** [comment]
Ah thank you!

**Comment by marscher** [comment]
We have the maximum allowed chunksize in the config right now. I think 2 mb is sufficient for good performance, but I will perform another benchmark.
