### ISSUE TITLE
branch feature_msmrevpi

### ISSUE THREAD

**Issue by trendelkampschroer** [markovmodel/PyEMMA#620]
Hi,

according to github the branch feature_msmrevpi is ahead of devel, but according to 

fb40f50e8f437b000a6303b0b3231c53da260b39
and 
2e11ddb03aa247286ab1f4fdabed47cf69f6e033

the two missing commits have already been merged into devel. Is feature_msmrevpi is stale? In that case I'd like to remove it.

@marscher and @franknoe: Can you have a look at this.

Also I would like to add the statdist keyword to BayesianMSM also, I think this would be a very easy modification, what do you think?

**Comment by franknoe** [comment]
Hmm, I don't remember. I still have a local copy of this branch, but it 
seems to be the same version that is online. So if there is no un-merged 
functionality in that branch, I am fine with deleting it.

The fixed-pi functionality is already included in 
estimate_transition_matrix and tested, right?
Good idea to also include it in BayesianMSM and the corresponding API 
function! I think we should then also include it in the timescale_msm / 
its functions, which would just pass the parameter on.

Thanks!

Am 09/11/15 um 14:36 schrieb Benjamin Trendelkamp-Schroer:

> Hi,
> 
> according to github the branch feature_msmrevpi is ahead of devel, but 
> according to
> 
> fb40f50 
> https://github.com/markovmodel/PyEMMA/commit/fb40f50e8f437b000a6303b0b3231c53da260b39
> and
> 2e11ddb 
> https://github.com/markovmodel/PyEMMA/commit/2e11ddb03aa247286ab1f4fdabed47cf69f6e033
> 
> the two missing commits have already been merged into devel. Is 
> feature_msmrevpi is stale? In that case I'd like to remove it.
> 
> @marscher https://github.com/marscher and @franknoe 
> https://github.com/franknoe: Can you have a look at this.
> 
> Also I would like to add the statdist keyword to BayesianMSM also, I 
> think this would be a very easy modification, what do you think?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/620.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
It is in my commit to feature_msmrevpi.

**Comment by franknoe** [comment]
It's possible we had cherry-picked those commits. But then I don't 
understand why that branch is supposed to be ahead of devel.

Am 09/11/15 um 14:54 schrieb Benjamin Trendelkamp-Schroer:

> It is in my commit to feature_msmrevpi.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/620#issuecomment-155068316.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by trendelkampschroer** [comment]
My question exactly...

**Comment by marscher** [comment]
It seems like this branch has been merged with resolved conflicts, therefore it can not be detected as included in devel branch (an edited commit will get a new commit id). If you are sure everything is included, please go ahead and delete this branch.
