### ISSUE TITLE
Continuous Time MSM

### ISSUE THREAD

**Issue by SBolo** [markovmodel/PyEMMA#623]
Good morning everyone, 
for my Phd I'm currently involved in a project which requires the construction of a Continuous Time Markov State Model from MD trajectories. I had a look to the documentation of PyEMMA's page and didn't found a specific function for doing this. Would this be possible?In the specific, what I would need is the transition rate matrix for the MSM instead of the transition probability matrix. 

Thank you for your support.
Simone

**Comment by franknoe** [comment]
We have code for this, but it isn't merged yet. @fabian-paul , can you and Simone get in touch? Perhaps you can give him a preliminary solution until this is accessible through a release.

**Comment by SBolo** [comment]
Thank you very much for your help! I'm waiting for an email then.

Simone

**Comment by SBolo** [comment]
@franknoe if you have some time, I also have some questions about the optimization of the "free" parameters for theTICA. Let me know.

**Comment by franknoe** [comment]
OK, let's do this by email: frank.noe@fu-berlin.de

Am 10/11/15 um 10:40 schrieb SBolo:

> @franknoe https://github.com/franknoe if you have some time, I also 
> have some questions about the optimization of the "free" parameters 
> for theTICA. Let me know.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/623#issuecomment-155370473.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
BTW we should at some point add this to msmtools. I think now we can do that easier because of the recent scipy release.
