### ISSUE TITLE
[coor/pca] when using NumpyFileReader

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#631]
Hi, I am observing this behavior...seems like Xm and self._dot_prod_tmp have different dimensions?
![snap10](https://cloud.githubusercontent.com/assets/7518004/11277823/80472cee-8ee8-11e5-80be-cfcb5f4a5961.png)

**Comment by marscher** [comment]
Does this happen on the first or last chunk?

**Comment by marscher** [comment]
Do both files have the same length? Default chunksize?

**Comment by gph82** [comment]
No, different lengths. But TICA  does not fail 

---

## Sent from my phone. Apologies for typos or brevity.

-------- Original message --------

**Comment by marscher** [comment]
Yes, because it does not try to save the temporary for the dot product. What about my other questions?

**Comment by gph82** [comment]
Sorry I'm outside. Everything else is whatever the default values are

---

## Sent from my phone. Apologies for typos or brevity.

-------- Original message --------
