### ISSUE TITLE
PyEMMA breaks my logging

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#639]
I was wondering why my logging messages started disappearing after some point in my analysis and it seems like it's caused by importing PyEMMA into HTMD.

``` python
ipdb> logger.info('est')
2015-11-30 14:42:25,792 - htmd.model - INFO - est
ipdb> import pyemma
ipdb> logger.info('est')
```

I attach my own logging configuration. But I don't see a reason why the two loggers should collide. My logger_htmd should catch the logging from it's submodules and call my consoleHandler correctly. Does anyone have some more experience in this than me?

``` ini
[loggers]
keys=root,htmd

[handlers]
keys=consoleHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=WARNING
handlers=consoleHandler

[logger_htmd]
level=INFO
handlers=consoleHandler
qualname=htmd
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=simpleFormatter
args=(sys.stdout,)

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=
```

**Comment by stefdoerr** [comment]
Unless PyEMMA maybe loads it's own loggin config file and that then overwrites my own config?
I tried loading my own config back in after PyEMMA but it doesn't seem to resolve the issue:

``` python
logging.config.fileConfig('logging.ini')
```

**Comment by marscher** [comment]
you can override the logging config file in .pyemma.cfg. It seems like the documentation is not as clear as It should be about this.

**Comment by marscher** [comment]
http://emma-project.org/latest/Configuration.html#default-configuration-file

**Comment by stefdoerr** [comment]
Hm but what if I want both the logging of PyEMMA and my own? Should be possible in theory no? They should not collide.

**Comment by stefdoerr** [comment]
Ok I guess I will have to make a combined configuration file for PyEMMA and HTMD and pass that to PyEMMA through the config. Hopefully then it will work.
I find it strange however that they don't go along together well, as they define logging rules for different modules.

**Comment by franknoe** [comment]
Please improve the docs then

Am 30/11/15 um 15:46 schrieb Martin K. Scherer:

> you can override the logging config file in .pyemma.cfg. It seems like 
> the documentation is not as clear as It should be about this.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/639#issuecomment-160650276.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
I actually find it explanatory enough in the docs.
I will try my solution and report back if it works.

**Comment by franknoe** [comment]
OK, thanks. Is there a standard way to handle multiple loggers and avoid 
collissions?

Am 30/11/15 um 16:00 schrieb Stefan:

> I actually find it explanatory enough in the docs.
> I will try my solution and report back if it works.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/639#issuecomment-160653898.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I think this has to be possible. One way could be not to configure the root logger (from which all children derive their configuration from), but only a "pyemma" logger. This way we should not interfere with other loggers (as long they are not touching the root logger, which was for instance a problem with earlier IPython versions).

I'll prepare a PR for this. Thanks @stefdoerr for noticing!

**Comment by stefdoerr** [comment]
I removed your root logger from the logging.yaml but it still breaks my logger. So it doesn't seem like this is the reason. Still looking into it.

**Comment by stefdoerr** [comment]
By the way, why did you decide not to use the recommended way of logging (at least that's what I saw suggested everywhere) where you start each file like this:

``` python
import logging
logger = logging.getLogger(__name__)
```

So that your loggers all use the module name. Like 'pyemma', 'pyemma.msm' etc and then you can add rules in the hierarchy.

**Comment by marscher** [comment]
we also use hierarchical names. But they are truncated to inner package names (ommit pyemma). Maybe this is the root of all evil.

How do you initialize the logging system in your package?

**Comment by stefdoerr** [comment]
In my top level `__init__.py` (i.e. `pyemma/__init__.py`) I just call 

``` python
logging.config.fileConfig(os.path.join(home(), 'logging.ini'))
```

with the ini config file I gave in the first post.
home() just returns the installation path of our software.

If they are only truncated to inner package names I still see no reason why it would mess up my logging. They should be independent loggers with their own rules. Also my own logging should never even reach the root logger. My htmd logger has propagate=0 and a handler so the messages should stay there.
Really weird stuff.

**Comment by franknoe** [comment]
I agree, if there's a standard we should follow it.

Am 30/11/15 um 17:11 schrieb Stefan:

> By the way, why did you decide not to use the recommended way of 
> logging (at least that's what I saw suggested everywhere) where you 
> start each file like this:
> 
> import  logging
> logger=  logging.getLogger(**name**)
> 
> So that your loggers all use the module name. Like 'pyemma', 
> 'pyemma.msm' etc and then you can add rules in the hierarchy.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/639#issuecomment-160673929.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
maybe fileConfig overrides everything?
https://stackoverflow.com/questions/7819718/python-logging-different-behavior-between-using-fileconfig-and-programmatic-con

**Comment by marscher** [comment]
emma uses logging.dictConfig, which also seems to override everything...

**Comment by stefdoerr** [comment]
Ah ok that would explain my logging disappearing. 

However if I try to reload my logging using fileConfig it does not fix it. Although at that point it might simply be too late.

**Comment by marscher** [comment]
Can you try to modify the last line in pyemma/util/log.py of function setupLogging:

``` python
    D.setdefault('version', 1)
    dictConfig(D, disable_existing_loggers=False)
```

**Comment by marscher** [comment]
yes, once the logging system is initialized, only a module reload of logging helps

**Comment by stefdoerr** [comment]
``` python
TypeError: dictConfig() got an unexpected keyword argument 'disable_existing_loggers'
```

Doesn't seem to be an option. Where did you read that dictConfig disables existing loggers? Cannot find it in the docs.

**Comment by marscher** [comment]
Sorry I got this wrong. You've to add this option to the actual logging config file (e.g logging.yml of pyemma).

**Comment by marscher** [comment]
you can override this in your instance of the logging file: ~/.pyemma/logging.yml

**Comment by stefdoerr** [comment]
Yeeeeeeeeeeeeeeeeees :D That was it. Thanks! 
That's a damn sneaky default option... Disable it please on the pyemma release if you don't mind.

**Comment by stefdoerr** [comment]
``` yaml
# PyEMMA's default logging settings
# If you want to enable file logging, uncomment the file related handlers and handlers
# 

disable_existing_loggers: False

formatters:
    simpleFormater:
        format: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
        datefmt: '%d-%m-%y %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        formatter: simpleFormater
        level: INFO 
        stream: ext://sys.stdout
#    file:
#        class : logging.FileHandler
#        formatter: simpleFormater
#        level: INFO
#        filename: pyemma.log

loggers:
    clogger:
        level: INFO
        handlers: [console]
    #flogger:
    #    level: INFO
    #    handlers: [file]

root:
# global log level
    level: INFO
    handlers: [console] #, file]
```

**Comment by franknoe** [comment]
So, what was the reason why we shouldn't do loggin like Stefan suggested?

import  logging
logger=  logging.getLogger(**name**)

Am 30/11/15 um 17:58 schrieb Stefan:

> Yeeeeeeeeeeeeeeeeees :D That was it. Thanks!
> That's a damn sneaky default option... Disable it please on the pyemma 
> release if you don't mind.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/639#issuecomment-160689469.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Because I'd like to have one logger per instance. If the output is mixed within instances, it is very hard to read the log files. The only thing to obey is to use a hierarchical names (a.b.c)

**Comment by franknoe** [comment]
ok, thanks.

Am 30/11/15 um 18:04 schrieb Martin K. Scherer:

> Because I'd like to have one logger per instance. If the output is 
> mixed within instances, it is very hard to read the log files. The 
> only thing to obey is to use a hierarchical names (a.b.c)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/639#issuecomment-160690866.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
This pattern is perfectly fine to setup a "global" logger for a module.

**Comment by stefdoerr** [comment]
So are you planning on adding the 
`disable_existing_loggers: False`
to the new pyemma release? Also what happens to people who already have pyemma installed, since you copy the conf file to ~/.pyemma/ ? WIll you have to make a version 2 file and load that one instead?

**Comment by marscher** [comment]
This version flag has to remain 1, since it indicates the general scheme of the config. If Python standard library is about changing that, they will increment it to distinguish the formats.

I'll be adding a PR, which does not disable existing loggers default by firstly adding this to the default config and in addition, if it is not yet set in an existing config, I'll set my own default.
