### ISSUE TITLE
HMM timescales warnings / error

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#640]
``` python
/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.py:199: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  ' It is possible that the resulting HMM is inaccurate. Handle with caution.')
01-12-15 11:19:45 msm.estimators.MaximumLikelihoodHMSM[1] WARNING  Requested coarse-grained model with 5 metastable states at lag=1.The ratio of relaxation timescales between 5 and 6 states is only 1.76364857191 while we recommend at least 2.  It is possible that the resulting HMM is inaccurate. Handle with caution.
/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/dense/decomposition.py:378: RuntimeWarning: invalid value encountered in sqrt
  R = R / np.sqrt(s[np.newaxis, :])
```

The first is the typical deprecation warning about warn method so you can fix that if you want.
The warning about the sqrt I don't know how to interpret.
Lastly, the calculation just crashes with this value error.

``` python
/shared/sdoerr/Work/pyHTMD/htmd/modelhmm.py in plotTimescales(self, lags, errors, nits, results, plot)
    106 
    107         from htmd.config import _config
--> 108         its = msm.timescales_hmsm(self.data.St, self.macronum, lags=lags, errors='bayes', nsamples=250, n_jobs=_config['ncpus'])
    109 
    110         if plot:

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/api.py in timescales_hmsm(dtrajs, nstates, lags, nits, reversible, connected, errors, nsamples, n_jobs, show_progress)
    609     itsobj = _ImpliedTimescales(estimator, lags=lags, nits=nits, n_jobs=n_jobs,
    610                                 show_progress=show_progress)
--> 611     itsobj.estimate(dtrajs)
    612     return itsobj
    613 

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/_base/estimator.py in estimate(self, X, **params)
    354         if params:
    355             self.set_params(**params)
--> 356         self._model = self._estimate(X)
    357         self._estimated = True
    358         return self._model

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/estimators/implied_timescales.py in _estimate(self, data)
    181         if issubclass(self._models[0].__class__, SampledModel):
    182             # samples
--> 183             timescales_samples = [m.sample_f('timescales') for m in self._models]
    184             nsamples = np.shape(timescales_samples[0])[0]
    185             self._its_samples = np.zeros((nsamples, len(self._lags), self.nits))

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/estimators/implied_timescales.py in <listcomp>(.0)
    181         if issubclass(self._models[0].__class__, SampledModel):
    182             # samples
--> 183             timescales_samples = [m.sample_f('timescales') for m in self._models]
    184             nsamples = np.shape(timescales_samples[0])[0]
    185             self._its_samples = np.zeros((nsamples, len(self._lags), self.nits))

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/_base/model.py in sample_f(self, f, *args, **kwargs)
    186         """
    187         self._check_samples_available()
--> 188         return [call_member(M, f, *args, **kwargs) for M in self.samples]
    189 
    190     def sample_mean(self, f, *args, **kwargs):

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/_base/model.py in <listcomp>(.0)
    186         """
    187         self._check_samples_available()
--> 188         return [call_member(M, f, *args, **kwargs) for M in self.samples]
    189 
    190     def sample_mean(self, f, *args, **kwargs):

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/util/reflection.py in call_member(obj, f, *args, **kwargs)
     45     # handle cases
     46     if inspect.ismethod(method):
---> 47         return method(*args, **kwargs)
     48 
     49     # attribute or property

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/models/msm.py in timescales(self, k)
    365         """
    366         if k is None:
--> 367             self._ensure_eigenvalues()
    368         else:
    369             self._ensure_eigenvalues(neig=k+1)

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/models/msm.py in _ensure_eigenvalues(self, neig)
    253         except:
    254             # no eigendecomposition yet - compute:
--> 255             self._compute_eigenvalues(neig)
    256 
    257     def _compute_eigendecomposition(self, neig):

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/models/msm.py in _compute_eigenvalues(self, neig)
    237         if self.reversible:
    238             self._eigenvalues = anaeig(self.transition_matrix, k=neig, ncv=self.ncv,
--> 239                                        reversible=True, mu=self.stationary_distribution)
    240         else:
    241             self._eigenvalues = anaeig(self.transition_matrix, k=neig, ncv=self.ncv, reversible=False)

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/api.py in eigenvalues(T, k, ncv, reversible, mu)
    405         return sparse.decomposition.eigenvalues(T, k, ncv=ncv, reversible=reversible, mu=mu)
    406     else:
--> 407         return dense.decomposition.eigenvalues(T, k, reversible=reversible, mu=mu)
    408 
    409 

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/dense/decomposition.py in eigenvalues(T, k, reversible, mu)
     75     """
     76     if reversible:
---> 77         evals = eigenvalues_rev(T, k=k, mu=mu)
     78     else:
     79         evals = eigvals(T)

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/dense/decomposition.py in eigenvalues_rev(T, k, mu)
    121     S = smu[:,None] * T / smu
    122     """ symmetric eigenvalue problem """
--> 123     evals = eigvalsh(S)
    124     return evals
    125 

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/scipy/linalg/decomp.py in eigvalsh(a, b, lower, overwrite_a, overwrite_b, turbo, eigvals, type, check_finite)
    687                 overwrite_a=overwrite_a, overwrite_b=overwrite_b,
    688                 turbo=turbo, eigvals=eigvals, type=type,
--> 689                 check_finite=check_finite)
    690 
    691 

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/scipy/linalg/decomp.py in eigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals, type, check_finite)
    290 
    291     """
--> 292     a1 = _asarray_validated(a, check_finite=check_finite)
    293     if len(a1.shape) != 2 or a1.shape[0] != a1.shape[1]:
    294         raise ValueError('expected square matrix')

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/scipy/_lib/_util.py in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok)
    133             raise ValueError('masked arrays are not supported')
    134     if check_finite:
--> 135         a = np.asarray_chkfinite(a)
    136     else:
    137         a = np.asarray(a)

/shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/numpy/lib/function_base.py in asarray_chkfinite(a, dtype, order)
    666     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
    667         raise ValueError(
--> 668             "array must not contain infs or NaNs")
    669     return a
    670 

ValueError: array must not contain infs or NaNs
```

**Comment by franknoe** [comment]
That's in my code. It will take a week until I can look into it, but I 
will need a reproducible example. Can you send dtrajs in a zipped file?

Am 01/12/15 um 11:24 schrieb Stefan:

> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.py:199:DeprecationWarning: The'warn'  methodis  deprecated, use'warning' instead ' It is possible that the resulting HMM is 
> inaccurate. Handle with caution.') 01-12-15 11:19:45 
> msm.estimators.MaximumLikelihoodHMSM[1] WARNING Requested 
> coarse-grained model with 5 metastable states at lag=1.The ratio of 
> relaxation timescales between 5 and 6 states is only 1.76364857191 
> while we recommend at least 2. It is possible that the resulting HMM 
> is inaccurate. Handle with caution. 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/dense/decomposition.py:378: 
> RuntimeWarning: invalid value encountered in sqrt R = R / 
> np.sqrt(s[np.newaxis, :])
> 
> The first is the typical warning about warn method so you can fix that 
> if you want.
> The warning about the sqrt I don't know how to interpret.
> Lastly, the calculation just crashes with this value error.
> 
> /shared/sdoerr/Work/pyHTMD/htmd/modelhmm.pyin  plotTimescales(self, lags, errors, nits, results, plot)
>      106  
>      107          from  htmd.configimport  _config
> -->  108          its=  msm.timescales_hmsm(self.data.St,self.macronum,lags=lags,errors='bayes',nsamples=250,n_jobs=_config['ncpus'])
>      109  
>      110          if  plot:
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/api.pyin  timescales_hmsm(dtrajs, nstates, lags, nits, reversible, connected, errors, nsamples, n_jobs, show_progress)
>      609      itsobj=  _ImpliedTimescales(estimator,lags=lags,nits=nits,n_jobs=n_jobs,
>      610                                  show_progress=show_progress)
> -->  611      itsobj.estimate(dtrajs)
>      612      return  itsobj
>      613  
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/_base/estimator.pyin  estimate(self, X,**params)
>      354          if  params:
>      355              self.set_params(**params)
> -->  356          self._model=  self._estimate(X)
>      357          self._estimated=  True
>      358          return  self._model
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/estimators/implied_timescales.pyin  _estimate(self, data)
>      181          if  issubclass(self._models[0].__class__, SampledModel):
>      182              # samples
> -->  183              timescales_samples=  [m.sample_f('timescales')for  min  self._models]
>      184              nsamples=  np.shape(timescales_samples[0])[0]
>      185              self._its_samples=  np.zeros((nsamples,len(self._lags),self.nits))
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/estimators/implied_timescales.pyin  <listcomp>(.0)
>      181          if  issubclass(self._models[0].__class__, SampledModel):
>      182              # samples
> -->  183              timescales_samples=  [m.sample_f('timescales')for  min  self._models]
>      184              nsamples=  np.shape(timescales_samples[0])[0]
>      185              self._its_samples=  np.zeros((nsamples,len(self._lags),self.nits))
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/_base/model.pyin  sample_f(self, f,_args,__kwargs)
>      186          """
> 187 self._check_samples_available()
> --> 188 return [call_member(M, f, *args, *_kwargs) for M in self.samples]
> 189
> 190 def sample_mean(self, f, _args, *_kwargs):
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/_base/model.py 
> in <listcomp>(.0)
> 186 """
>      187          self._check_samples_available()
> -->  188          return  [call_member(M, f,_args,__kwargs)for  Min  self.samples]
>      189  
>      190      def  sample_mean(self, f,_args,**kwargs):
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/util/reflection.pyin  call_member(obj, f,_args,__kwargs)
>       45      # handle cases
>       46      if  inspect.ismethod(method):
> --->  47          return  method(_args,**kwargs)
>       48  
>       49      # attribute or property
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/models/msm.pyin  timescales(self, k)
>      365          """
> 366 if k is None:
> --> 367 self._ensure_eigenvalues()
> 368 else:
> 369 self._ensure_eigenvalues(neig=k+1)
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/models/msm.py 
> in _ensure_eigenvalues(self, neig)
> 253 except:
> 254 # no eigendecomposition yet - compute:
> --> 255 self._compute_eigenvalues(neig)
> 256
> 257 def _compute_eigendecomposition(self, neig):
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/models/msm.py 
> in _compute_eigenvalues(self, neig)
> 237 if self.reversible:
> 238 self._eigenvalues = anaeig(self.transition_matrix, k=neig, 
> ncv=self.ncv,
> --> 239 reversible=True, mu=self.stationary_distribution)
> 240 else:
> 241 self._eigenvalues = anaeig(self.transition_matrix, k=neig, 
> ncv=self.ncv, reversible=False)
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/api.py 
> in eigenvalues(T, k, ncv, reversible, mu)
> 405 return sparse.decomposition.eigenvalues(T, k, ncv=ncv, 
> reversible=reversible, mu=mu)
> 406 else:
> --> 407 return dense.decomposition.eigenvalues(T, k, 
> reversible=reversible, mu=mu)
> 408
> 409
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/dense/decomposition.py 
> in eigenvalues(T, k, reversible, mu)
> 75 """
>       76      if  reversible:
> --->  77          evals=  eigenvalues_rev(T,k=k,mu=mu)
>       78      else:
>       79          evals=  eigvals(T)
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/dense/decomposition.pyin  eigenvalues_rev(T, k, mu)
>      121      S=  smu[:,None]\*  T/  smu
>      122      """ symmetric eigenvalue problem """
> -->  123      evals=  eigvalsh(S)
>      124      return  evals
>      125  
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/scipy/linalg/decomp.pyin  eigvalsh(a, b, lower, overwrite_a, overwrite_b, turbo, eigvals,type, check_finite)
>      687                  overwrite_a=overwrite_a, overwrite_b=overwrite_b,
>      688                  turbo=turbo, eigvals=eigvals,type=type,
> -->  689                  check_finite=check_finite)
>      690  
>      691  
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/scipy/linalg/decomp.pyin  eigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals,type, check_finite)
>      290  
>      291      """
> --> 292 a1 = _asarray_validated(a, check_finite=check_finite)
> 293 if len(a1.shape) != 2 or a1.shape[0] != a1.shape[1]:
> 294 raise ValueError('expected square matrix')
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/scipy/_lib/_util.py 
> in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok)
> 133 raise ValueError('masked arrays are not supported')
> 134 if check_finite:
> --> 135 a = np.asarray_chkfinite(a)
> 136 else:
> 137 a = np.asarray(a)
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/numpy/lib/function_base.py 
> in asarray_chkfinite(a, dtype, order)
> 666 if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
> 667 raise ValueError(
> --> 668 "array must not contain infs or NaNs")
> 669 return a
> 670
> 
> ValueError: array must not contain infs or NaNs
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/640.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Short answer: I suggest to limit the lag time to less than 1/4 of the 
trajectory length.

Longer answer: HMM estimation doesn't work well with lag times that are 
on the same order as the trajectory length. In your case (length 200 
steps), when you use a lag time of 101 or more steps, then each 
trajectory consists of two steps (each trajectory is rewritten into 
trajectories of steplength tau, e.g. [0, 101], [1, 102],... ). In the 
HMM algorithm, the hidden state variables are initialized from some 
probability distribution (e.g. equilibrium distribution), and that 
belief is then propagated. But in this example, there is only one step 
to propagate, and that will still be conterminated by the 
initialization. I believe this is the reason why HMM timescales can 
overshoot and diverge earlier than MSM likelihoods. The good thing about 
HMMs is that they will also converge earlier, if discretization and 
statistics are acceptable, so you may not need to go to long lag times. 
So the problem already arises at maximum-likelihood estimation.

What caused the error is the following: The estimation produces 
spuriously large timescales that are longer than the simulation time. 
This causes the Bayesian sampling algorithm to produce hidden state 
trajectories that are not connected, and basicly diagonal transition 
matrices. The only thing that connects them is a weak prior. For 
numerical reasons, the second eigenvalue can sometimes be 1 or larger 
than 1 and then gives infinite timescales.

I am still thinking whether something can be done to improve the 
situation. It's not an easy problem to solve, but it can be handled when 
it occurs. In the maximum-likelihood step one can raise a warning if the 
lag time is too large. In the Bayesian sampling step it's essentially 
already too late. Only accepting connected HMM samples trajectory 
samples would be conceptually right, but is not really an option, 
because the parameters can be such that sampling connected trajectories 
is extremely unlikely. Probably the cleanest solution is to not return 
results for lag times where this problem occurs, like in the MSM case 
where too long lag times cause total loss of connectivity.

Am 01/12/15 um 11:24 schrieb Stefan:

> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.py:199:DeprecationWarning: The'warn'  methodis  deprecated, use'warning' instead ' It is possible that the resulting HMM is 
> inaccurate. Handle with caution.') 01-12-15 11:19:45 
> msm.estimators.MaximumLikelihoodHMSM[1] WARNING Requested 
> coarse-grained model with 5 metastable states at lag=1.The ratio of 
> relaxation timescales between 5 and 6 states is only 1.76364857191 
> while we recommend at least 2. It is possible that the resulting HMM 
> is inaccurate. Handle with caution. 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/dense/decomposition.py:378: 
> RuntimeWarning: invalid value encountered in sqrt R = R / 
> np.sqrt(s[np.newaxis, :])
> 
> The first is the typical warning about warn method so you can fix that 
> if you want.
> The warning about the sqrt I don't know how to interpret.
> Lastly, the calculation just crashes with this value error.
> 
> /shared/sdoerr/Work/pyHTMD/htmd/modelhmm.pyin  plotTimescales(self, lags, errors, nits, results, plot)
>      106  
>      107          from  htmd.configimport  _config
> -->  108          its=  msm.timescales_hmsm(self.data.St,self.macronum,lags=lags,errors='bayes',nsamples=250,n_jobs=_config['ncpus'])
>      109  
>      110          if  plot:
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/api.pyin  timescales_hmsm(dtrajs, nstates, lags, nits, reversible, connected, errors, nsamples, n_jobs, show_progress)
>      609      itsobj=  _ImpliedTimescales(estimator,lags=lags,nits=nits,n_jobs=n_jobs,
>      610                                  show_progress=show_progress)
> -->  611      itsobj.estimate(dtrajs)
>      612      return  itsobj
>      613  
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/_base/estimator.pyin  estimate(self, X,**params)
>      354          if  params:
>      355              self.set_params(**params)
> -->  356          self._model=  self._estimate(X)
>      357          self._estimated=  True
>      358          return  self._model
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/estimators/implied_timescales.pyin  _estimate(self, data)
>      181          if  issubclass(self._models[0].__class__, SampledModel):
>      182              # samples
> -->  183              timescales_samples=  [m.sample_f('timescales')for  min  self._models]
>      184              nsamples=  np.shape(timescales_samples[0])[0]
>      185              self._its_samples=  np.zeros((nsamples,len(self._lags),self.nits))
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/estimators/implied_timescales.pyin  <listcomp>(.0)
>      181          if  issubclass(self._models[0].__class__, SampledModel):
>      182              # samples
> -->  183              timescales_samples=  [m.sample_f('timescales')for  min  self._models]
>      184              nsamples=  np.shape(timescales_samples[0])[0]
>      185              self._its_samples=  np.zeros((nsamples,len(self._lags),self.nits))
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/_base/model.pyin  sample_f(self, f,_args,__kwargs)
>      186          """
> 187 self._check_samples_available()
> --> 188 return [call_member(M, f, *args, *_kwargs) for M in self.samples]
> 189
> 190 def sample_mean(self, f, _args, *_kwargs):
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/_base/model.py 
> in <listcomp>(.0)
> 186 """
>      187          self._check_samples_available()
> -->  188          return  [call_member(M, f,_args,__kwargs)for  Min  self.samples]
>      189  
>      190      def  sample_mean(self, f,_args,**kwargs):
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/util/reflection.pyin  call_member(obj, f,_args,__kwargs)
>       45      # handle cases
>       46      if  inspect.ismethod(method):
> --->  47          return  method(_args,**kwargs)
>       48  
>       49      # attribute or property
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/models/msm.pyin  timescales(self, k)
>      365          """
> 366 if k is None:
> --> 367 self._ensure_eigenvalues()
> 368 else:
> 369 self._ensure_eigenvalues(neig=k+1)
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/models/msm.py 
> in _ensure_eigenvalues(self, neig)
> 253 except:
> 254 # no eigendecomposition yet - compute:
> --> 255 self._compute_eigenvalues(neig)
> 256
> 257 def _compute_eigendecomposition(self, neig):
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/pyEMMA-2.0.2-py3.4-linux-x86_64.egg/pyemma/msm/models/msm.py 
> in _compute_eigenvalues(self, neig)
> 237 if self.reversible:
> 238 self._eigenvalues = anaeig(self.transition_matrix, k=neig, 
> ncv=self.ncv,
> --> 239 reversible=True, mu=self.stationary_distribution)
> 240 else:
> 241 self._eigenvalues = anaeig(self.transition_matrix, k=neig, 
> ncv=self.ncv, reversible=False)
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/api.py 
> in eigenvalues(T, k, ncv, reversible, mu)
> 405 return sparse.decomposition.eigenvalues(T, k, ncv=ncv, 
> reversible=reversible, mu=mu)
> 406 else:
> --> 407 return dense.decomposition.eigenvalues(T, k, 
> reversible=reversible, mu=mu)
> 408
> 409
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/dense/decomposition.py 
> in eigenvalues(T, k, reversible, mu)
> 75 """
>       76      if  reversible:
> --->  77          evals=  eigenvalues_rev(T,k=k,mu=mu)
>       78      else:
>       79          evals=  eigvals(T)
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/msmtools/analysis/dense/decomposition.pyin  eigenvalues_rev(T, k, mu)
>      121      S=  smu[:,None]\*  T/  smu
>      122      """ symmetric eigenvalue problem """
> -->  123      evals=  eigvalsh(S)
>      124      return  evals
>      125  
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/scipy/linalg/decomp.pyin  eigvalsh(a, b, lower, overwrite_a, overwrite_b, turbo, eigvals,type, check_finite)
>      687                  overwrite_a=overwrite_a, overwrite_b=overwrite_b,
>      688                  turbo=turbo, eigvals=eigvals,type=type,
> -->  689                  check_finite=check_finite)
>      690  
>      691  
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/scipy/linalg/decomp.pyin  eigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals,type, check_finite)
>      290  
>      291      """
> --> 292 a1 = _asarray_validated(a, check_finite=check_finite)
> 293 if len(a1.shape) != 2 or a1.shape[0] != a1.shape[1]:
> 294 raise ValueError('expected square matrix')
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/scipy/_lib/_util.py 
> in _asarray_validated(a, check_finite, sparse_ok, objects_ok, mask_ok)
> 133 raise ValueError('masked arrays are not supported')
> 134 if check_finite:
> --> 135 a = np.asarray_chkfinite(a)
> 136 else:
> 137 a = np.asarray(a)
> 
> /shared/sdoerr/Software/anaconda3/lib/python3.4/site-packages/numpy/lib/function_base.py 
> in asarray_chkfinite(a, dtype, order)
> 666 if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
> 667 raise ValueError(
> --> 668 "array must not contain infs or NaNs")
> 669 return a
> 670
> 
> ValueError: array must not contain infs or NaNs
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/640.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
