### ISSUE TITLE
Residue out of range

### ISSUE THREAD

**Issue by ParkerdeWaal** [markovmodel/PyEMMA#645]
Hi Everyone,

I've come across a residue range error while trying to add a subset of residues involved in salt-bridge formation. Specifically, 

```
File "/home/parker.dewaal/applications/miniconda2/lib/python2.7/site-packages/mdtraj/geometry/contact.py", line 132, in compute_contacts
    raise ValueError('contacts requests a residue that is not in the permitted range')
ValueError: contacts requests a residue that is not in the permitted range
```

and the code that generates this error can be found here, 

```
import pyemma
import pyemma.coordinates as coor
import numpy as np

# 
topfile =  '../snap1.pdb'
feat = coor.featurizer(topfile)

# select phosphate residue and nearby basic residues
phosphoResidue = 338
basicResidues = [505, 519, 790, 791]

# generate residue selection array
ind_arr = np.zeros((len(basicResidues),2))
for idx, residue in enumerate(basicResidues):
    ind_arr[idx][0] = str(phosphoResidue)
    ind_arr[idx][1] = str(residue)
print(ind_arr)

feat.add_residue_mindist(residue_pairs=ind_arr, scheme='closest-heavy', threshold=0.5)
feat.describe()[:10]
```

Without attaching my pdb file, we can see that all of these residues are within the range,

```
ATOM      1  N   MET A   1      44.062  12.263  94.817  1.00  0.00           N
ATOM      2  HT1 MET A   1      43.870  13.233  94.966  1.00  0.00           H
ATOM      3  HT2 MET A   1      44.056  12.040  93.842  1.00  0.00           H
ATOM      4  CA  MET A   1      45.301  11.795  95.419  1.00  0.00           C
ATOM      5  HA  MET A   1      45.096  11.471  96.429  1.00  0.00           H
ATOM      6  CB  MET A   1      45.759  10.560  94.625  1.00  0.00           C
ATOM      7  HB1 MET A   1      44.841  10.062  94.246  1.00  0.00           H
ATOM      8  HB2 MET A   1      46.334  10.793  93.704  1.00  0.00           H
ATOM      9  CG  MET A   1      46.522   9.545  95.478  1.00  0.00           C
ATOM     10  HG1 MET A   1      45.860   9.329  96.344  1.00  0.00           H
ATOM     11  HG2 MET A   1      46.560   8.641  94.834  1.00  0.00           H
ATOM     12  SD  MET A   1      48.160  10.228  95.873  1.00  0.00           S
ATOM     13  CE  MET A   1      48.993   9.440  94.465  1.00  0.00           C
ATOM     14  HE1 MET A   1      48.636   9.987  93.565  1.00  0.00           H
ATOM     15  HE2 MET A   1      50.094   9.571  94.519  1.00  0.00           H
ATOM     16  HE3 MET A   1      48.728   8.362  94.422  1.00  0.00           H
...
...
...
ATOM  10944  N   GLN B 849      33.567   8.343   8.674  1.00  0.00           N
ATOM  10945  HN  GLN B 849      32.801   7.783   8.369  1.00  0.00           H
ATOM  10946  CA  GLN B 849      34.737   8.179   7.868  1.00  0.00           C
ATOM  10947  HA  GLN B 849      35.605   8.366   8.484  1.00  0.00           H
ATOM  10948  CB  GLN B 849      34.619   6.796   7.206  1.00  0.00           C
ATOM  10949  HB1 GLN B 849      33.571   6.583   6.907  1.00  0.00           H
ATOM  10950  HB2 GLN B 849      35.236   6.682   6.289  1.00  0.00           H
ATOM  10951  CG  GLN B 849      35.066   5.664   8.133  1.00  0.00           C
ATOM  10952  HG1 GLN B 849      34.509   5.539   9.086  1.00  0.00           H
ATOM  10953  HG2 GLN B 849      34.833   4.723   7.590  1.00  0.00           H
ATOM  10954  CD  GLN B 849      36.581   5.664   8.284  1.00  0.00           C
ATOM  10955  OE1 GLN B 849      37.372   5.393   7.382  1.00  0.00           O
ATOM  10956  NE2 GLN B 849      37.108   5.993   9.494  1.00  0.00           N
ATOM  10957 1HE2 GLN B 849      36.587   6.160  10.330  1.00  0.00           H
ATOM  10958 2HE2 GLN B 849      38.099   6.124   9.529  1.00  0.00           H
ATOM  10959  C   GLN B 849      34.859   9.179   6.728  1.00  0.00           C
ATOM  10960  OT1 GLN B 849      34.123   9.309   5.763  1.00  0.00           O
ATOM  10961  OT2 GLN B 849      35.943  10.052   6.874  1.00  0.00           O
ATOM  10962  HT2 GLN B 849      35.923  10.652   6.124  1.00  0.00           H
```

I'm wondering if this is an issue with selecting from different chains by residue id?
Any help would be appreciated.

**Comment by franknoe** [comment]
@gph82 , can you have a look?

Am 08/12/15 um 23:41 schrieb Parker de Waal:

> Hi Everyone,
> 
> I've come across a residue range error while trying to add a subset of 
> residues involved in salt-bridge formation. Specifically,
> 
> |File 
> "/home/parker.dewaal/applications/miniconda2/lib/python2.7/site-packages/mdtraj/geometry/contact.py", 
> line 132, in compute_contacts raise ValueError('contacts requests a 
> residue that is not in the permitted range') ValueError: contacts 
> requests a residue that is not in the permitted range |
> 
> and the code that generates this error can be found here,
> 
> |import pyemma import pyemma.coordinates as coor import numpy as np # 
> topfile = '../snap1.pdb' feat = coor.featurizer(topfile) # select 
> phosphate residue and nearby basic residues phosphoResidue = 338 
> basicResidues = [505, 519, 790, 791] # generate residue selection 
> array ind_arr = np.zeros((len(basicResidues),2)) for idx, residue in 
> enumerate(basicResidues): ind_arr[idx][0] = str(phosphoResidue) 
> ind_arr[idx][1] = str(residue) print(ind_arr) 
> feat.add_residue_mindist(residue_pairs=ind_arr, 
> scheme='closest-heavy', threshold=0.5) feat.describe()[:10] |
> 
> Without attaching my pdb file, we can see that all of these residues 
> are within the range,
> 
> |ATOM 1 N MET A 1 44.062 12.263 94.817 1.00 0.00 N ATOM 2 HT1 MET A 1 
> 43.870 13.233 94.966 1.00 0.00 H ATOM 3 HT2 MET A 1 44.056 12.040 
> 93.842 1.00 0.00 H ATOM 4 CA MET A 1 45.301 11.795 95.419 1.00 0.00 C 
> ATOM 5 HA MET A 1 45.096 11.471 96.429 1.00 0.00 H ATOM 6 CB MET A 1 
> 45.759 10.560 94.625 1.00 0.00 C ATOM 7 HB1 MET A 1 44.841 10.062 
> 94.246 1.00 0.00 H ATOM 8 HB2 MET A 1 46.334 10.793 93.704 1.00 0.00 H 
> ATOM 9 CG MET A 1 46.522 9.545 95.478 1.00 0.00 C ATOM 10 HG1 MET A 1 
> 45.860 9.329 96.344 1.00 0.00 H ATOM 11 HG2 MET A 1 46.560 8.641 
> 94.834 1.00 0.00 H ATOM 12 SD MET A 1 48.160 10.228 95.873 1.00 0.00 S 
> ATOM 13 CE MET A 1 48.993 9.440 94.465 1.00 0.00 C ATOM 14 HE1 MET A 1 
> 48.636 9.987 93.565 1.00 0.00 H ATOM 15 HE2 MET A 1 50.094 9.571 
> 94.519 1.00 0.00 H ATOM 16 HE3 MET A 1 48.728 8.362 94.422 1.00 0.00 H 
> ... ... ... ATOM 10944 N GLN B 849 33.567 8.343 8.674 1.00 0.00 N ATOM 
> 10945 HN GLN B 849 32.801 7.783 8.369 1.00 0.00 H ATOM 10946 CA GLN B 
> 849 34.737 8.179 7.868 1.00 0.00 C ATOM 10947 HA GLN B 849 35.605 
> 8.366 8.484 1.00 0.00 H ATOM 10948 CB GLN B 849 34.619 6.796 7.206 
> 1.00 0.00 C ATOM 10949 HB1 GLN B 849 33.571 6.583 6.907 1.00 0.00 H 
> ATOM 10950 HB2 GLN B 849 35.236 6.682 6.289 1.00 0.00 H ATOM 10951 CG 
> GLN B 849 35.066 5.664 8.133 1.00 0.00 C ATOM 10952 HG1 GLN B 849 
> 34.509 5.539 9.086 1.00 0.00 H ATOM 10953 HG2 GLN B 849 34.833 4.723 
> 7.590 1.00 0.00 H ATOM 10954 CD GLN B 849 36.581 5.664 8.284 1.00 0.00 
> C ATOM 10955 OE1 GLN B 849 37.372 5.393 7.382 1.00 0.00 O ATOM 10956 
> NE2 GLN B 849 37.108 5.993 9.494 1.00 0.00 N ATOM 10957 1HE2 GLN B 849 
> 36.587 6.160 10.330 1.00 0.00 H ATOM 10958 2HE2 GLN B 849 38.099 6.124 
> 9.529 1.00 0.00 H ATOM 10959 C GLN B 849 34.859 9.179 6.728 1.00 0.00 
> C ATOM 10960 OT1 GLN B 849 34.123 9.309 5.763 1.00 0.00 O ATOM 10961 
> OT2 GLN B 849 35.943 10.052 6.874 1.00 0.00 O ATOM 10962 HT2 GLN B 849 
> 35.923 10.652 6.124 1.00 0.00 H |
> 
> I'm wondering if this is an issue with selecting from different chains 
> by residue id?
> Any help would be appreciated.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/645.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ParkerdeWaal** [comment]
If it helps, here is a printout of the ind_arr array,

```
[[ 338.  505.]
 [ 338.  519.]
 [ 338.  790.]
 [ 338.  791.]]
```

and the full error message, 

```
/home/parker.dewaal/applications/miniconda2/lib/python2.7/site-packages/pyEMMA-2.0.2-py2.7-linux-x86_64.egg/pyemma/coord                                    inates/data/featurizer.py:1187: FutureWarning: elementwise comparison failed; returning scalar instead, but in the futur                                    e will perform elementwise comparison
  if scheme != 'ca' and residue_pairs == 'all':
Traceback (most recent call last):
  File "input.py", line 23, in <module>
    feat.add_residue_mindist(residue_pairs=ind_arr, scheme='closest', threshold=0.5)
  File "/home/parker.dewaal/applications/miniconda2/lib/python2.7/site-packages/pyEMMA-2.0.2-py2.7-linux-x86_64.egg/pyem                                    ma/coordinates/data/featurizer.py", line 1191, in add_residue_mindist
    f = ResidueMinDistanceFeature(self.topology, residue_pairs, scheme, ignore_nonprotein, threshold)
  File "/home/parker.dewaal/applications/miniconda2/lib/python2.7/site-packages/pyEMMA-2.0.2-py2.7-linux-x86_64.egg/pyem                                    ma/coordinates/data/featurizer.py", line 441, in __init__
    ignore_nonprotein=ignore_nonprotein)
  File "/home/parker.dewaal/applications/miniconda2/lib/python2.7/site-packages/mdtraj/geometry/contact.py", line 132, i                                    n compute_contacts
    raise ValueError('contacts requests a residue that is not in the permitted range')
ValueError: contacts requests a residue that is not in the permitted range
```

**Comment by franknoe** [comment]
thanks, we'll have a look

Am 08/12/15 um 23:45 schrieb Parker de Waal:

> If it helps, here is a printout of the ind_arr array,
> 
> |[[ 338. 505.] [ 338. 519.] [ 338. 790.] [ 338. 791.]] |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/645#issuecomment-163045142.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ParkerdeWaal** [comment]
I've figured out the error,

in my PDB the residue number is not continuous. i.e. Chain A runs from 1-332 while chain B runs from 501-883. featureizer assumes the residue numbers are without gaps. to fix I simply put an offset in my atom selection to make up for the difference.

I guess this means that featuerizer doesn't actually read the residue numbers from the PDB?

**Comment by gph82** [comment]
@ParkerdeWaal , there has been some discussion in our group already as to weather the selection should be done using monotonic, sequential residue indices or what you are referring to as residue number (which is actually the resSeq-entry of the pdb, see http://mdtraj.org/latest/atom_selection.html).

We've decided to stick with the former, because that is mdtraj's convention for the selection (they use the "resid" attribute rather than the "residue" attribute). However, we changed the indices that are shown in the description. See this PR #561 . Why don't you post the output of feat.describe() and see if it's what you want?

**Comment by gph82** [comment]
As a side, note, some time ago I prepared a commit that did the selection that you had expected (via the resSeq index) here https://github.com/gph82/PyEMMA/commit/5a20cb4b80c92f4fd342f6df0b4406dce38f41e4, but then we decided to leave it out for the above reasons. You can follow part of the discussion here https://github.com/markovmodel/PyEMMA/pull/514

**Comment by marscher** [comment]
@gph82 Has this issue been addressed in #605?

**Comment by gph82** [comment]
Partially. This is a non-issue insofar as there is no bug in the code or anything. I suggest we close it

**Comment by marscher** [comment]
Alright.
