### ISSUE TITLE
Predefined subspace comparison

### ISSUE THREAD

**Issue by ParkerdeWaal** [markovmodel/PyEMMA#665]
Hello everyone,

Is it possible to use PyEMMA to compare two independent trajectories in the same TICA subspace?

For example:
Perform TICA Ca coord transformation for TrajA, apply the same transformation operation to TrajB to perform a direct comparison of the two trajectories.

Cheers,
Parker

**Comment by franknoe** [comment]
Yes, you can estimate a TICA transformation with

`tica_transform = pyemma.coordinates.tica(...)`

and then apply

``` tica_transform.transform(X)```

to another coordinate set.

Am 04/01/16 um 23:04 schrieb Parker de Waal:
>
> Hello everyone,
>
> Is it possible to use PyEMMA to compare two independent trajectories 
> in the same TICA subspace?
>
> For example:
> Perform TICA Ca coord transformation for TrajA, apply the same 
> transformation operation to TrajB to perform a direct comparison of 
> the two trajectories.
>
> Cheers,
> Parker
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/665>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

```

**Comment by marscher** [comment]
This question has been answered.
