### ISSUE TITLE
[coor_refactor] should estimate method be able to override any ctor argument?

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#667]
The signature of the scikit-learn estimate interface allows passing in arbitrary (**kw) arguments. So in principle the user could override any argument set before in the constructor. Currently this is not fully implemented (eg. only for "stride").
In my opinion, we should fully support this and even warn, when the arguments are not being handled by the method to avoid confusion.

**Comment by marscher** [comment]
Actually this is already implemented via the estimate(X, **kw) -> set_params(**kw); _estimate(X) logic.

**Comment by franknoe** [comment]
yes

Am 06/01/16 um 19:32 schrieb Martin K. Scherer:

> Actually this is already implemented via the estimate(X, _kw) -> 
> set_params(_kw); _estimate(X) logic.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/667#issuecomment-169412588.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
