### ISSUE TITLE
[coor_refactor] lagged iterator n_chunks returns wrong result

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#668]
Currently it returns min(it.nchunks, it_lagged.nchunks), but sometimes the estimate for the lagged one is off by -1.

**Comment by clonker** [comment]
I added a unit test for this and it seems to be  working fine now, maybe you can have another look?

**Comment by marscher** [comment]
If I raise an exception during the update of a progress reporter in case the numerator gets bigger than the denominator, I'll get like 20 errors. The denominator is the return value of n_chunks in every case.

**Comment by marscher** [comment]
Now only one error like this remains:
pyemma/pyemma/coordinates/tests/test_tica.py", line 331, in test_skipped_trajs

2 chunks are expected (by n_chunks) and 3 are actually returned.

**Comment by marscher** [comment]
done
