### ISSUE TITLE
Transformer.transform deprecated or not?

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#670]
In the branch devel_refactor_transformer, Transformer.transform is marked as deprecated. This doesn't seem to be correct, because internally fit_transform() used transform().
Should transform() become deprecated or not? If not, how will it be replaced?
Right now I want to use it for cross-projecting data as described in issue #665. I guess this should still be possible in the new release. I also would like it if one could apply transform() (or is successor) to a data source.

**Comment by marscher** [comment]
I think you're right, we should keep this.

**Comment by franknoe** [comment]
No, transform() is the essence of the Transformer. I don't know or 
remember why it's marked as depr.

Am 11/01/16 um 14:23 schrieb fabian-paul:

> In the branch devel_refactor_transformer, Transformertransform is 
> marked as deprecated This doesn't seem to be correct, because 
> internally fit_transform() used transform()
> Should transform() become deprecated or not? If not, how will it be 
> replaced?
> Right now I want to use it for cross-projecting data as described in 
> issue #665 https://github.com/markovmodel/PyEMMA/issues/665 I guess 
> this should still be possible in the new release I also would like it 
> if one could apply transform() (or is successor) to a data source
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/670.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
