### ISSUE TITLE
[coor_refactor] write performance tests and compare measures with last release 

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#674]
We need to have tests for:
- io operations (FeatureReader, NumPyReader, ...)
- estimators (Clustering, TICA, PCA, ...)
- pipelining operations (chunked vs full-file/traj mode)

The data sets should lie on a local hard disk to avoid fluctuations due to network access. All tests should be long running and deterministic (eg. use the same random seed).

Which data sets should we use (eg. they have to fit on the hard drive of the testing system)?

We can think about automatizing this via our Jenkins service as soon we have defined these things. I'll suggest to store these tests in a separate repo to easily test against multiple versions of PyEMMA.

**Comment by franknoe** [comment]
In addition: featurization, in particular distances and contacts

Am 15/01/16 um 17:14 schrieb Martin K. Scherer:

> We need to have tests for:
> - io operations (FeatureReader, NumPyReader, ...)
> - estimators (Clustering, TICA, PCA, ...)
> - pipelining operations (chunked vs full-file/traj mode)
> 
> The data sets should lie on a local hard disk to avoid fluctuations 
> due to network access. All tests should be long running and 
> deterministic (eg. use the same random seed).
> 
> Which data sets should we use (eg. they have to fit on the hard drive 
> of the testing system)?
> 
> We can think about automatizing this via our Jenkins service as soon 
> we have defined these things. I'll suggest to store these tests in a 
> separate repo to easily test against multiple versions of PyEMMA.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/674.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
This is the last open issue in the coordinate refactor project which is completed I think. Is that done, and is it documented how to run these tests?

**Comment by marscher** [comment]
I have a repository containing these tests, yes. But one needs dedicated system connected our IT infrastructure to run these in order to generate reproducible results. These tests copy test data from the group home and run for ~3 hours. Because the testsuite uses Python unittest framework, it is as easy as using nosetests to run them. Where should I publish this repo? Private repos are not possible for this organisation.

**Comment by franknoe** [comment]
I don't think we need to publish this, but pls document for us 
developers how to use / access / analyze these tests.

Am 22/03/16 um 12:17 schrieb Martin K. Scherer:

> I have a repository containing these tests, yes. But one needs 
> dedicated system connected our IT infrastructure to run these in order 
> to generate reproducible results. These tests copy test data from the 
> group home and run for ~3 hours. Because the testsuite uses Python 
> unittest framework, it is as easy as using nosetests to run them. 
> Where should I publish this repo? Private repos are not possible for 
> this organisation.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/674#issuecomment-199765191

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I think this is done. Is there a developer documentation for it yet?

**Comment by marscher** [comment]
I can quickly wrap these things up. Where do prefer to store them? In the wiki?

**Comment by franknoe** [comment]
The Wiki is more of a brainstorming place. What about a "cmb-internal" 
section in the developer docs?

Am 09/05/16 um 11:57 schrieb Martin K. Scherer:

> I can quickly wrap these things up. Where do prefer to store them? In 
> the wiki?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/674#issuecomment-217823645

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 09.05.2016 um 11:59 schrieb Frank Noe:

> The Wiki is more of a brainstorming place. What about a "cmb-internal"
> section in the developer docs?
> "internal" public domain? :)

**Comment by franknoe** [comment]
I know, but the Wiki is public too. BTW, we could at least publish the 
results of these tests and over time we can work towards making the 
tests publishable (once they don't rely on non-publishable data anymore).

Am 09/05/16 um 12:00 schrieb Martin K. Scherer:

> Am 09.05.2016 um 11:59 schrieb Frank Noe:
> 
> > The Wiki is more of a brainstorming place. What about a "cmb-internal"
> > section in the developer docs?
> > "internal" public domain? :)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/674#issuecomment-217824166

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Thats true. At the moment the tests rely heavily on data stored in house so. For the next release we can sort this out. At the moment the tests are executed on the cluster and the results are compared between specified versions. The results are currently on my private Jenkins instance, but I should move them - or publish the results to some yet unspecified location.

**Comment by franknoe** [comment]
Yes. I think for pure performance tests it might also be OK to just 
generate synthetic data, and that could be done with very little code. 
After all the performance should just depend on things like number of 
trajectories, number of samples, number of dimensions, storage format 
when reading from files etc. I think when properly generalizing this we 
could even sample some of these properties automatically to get a broad 
performance test coverage without investing too much time.

Am 09/05/16 um 12:06 schrieb Martin K. Scherer:

> Thats true. At the moment the tests rely heavily on data stored in 
> house so. For the next release we can sort this out. At the moment the 
> tests are executed on the cluster and the results are compared between 
> specified versions. The results are currently on my private Jenkins 
> instance, but I should move them - or publish the results to some yet 
> unspecified location.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/674#issuecomment-217825556

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
