### ISSUE TITLE
msmtools.flux.ReactiveFlux.coarse_grain gives coarsed states in random order

### ISSUE THREAD

**Issue by ismaelresp** [markovmodel/PyEMMA#677]
``` python
    import pyemma.msm as pymsm
    tpte=pymsm.tpt(msmmodel,msmmodel.metastable_sets[4],msmmodel.metastable_sets[1])
    sets,cg_tpt=tpte.coarse_grain(msmmodel.metastable_sets)
    cg_tpt.stationary_distribution

    array([ 0.45738065,  0.035176  ,  0.04630047,  0.34120639,  0.11993649])

    np.sum(stationary_distribution(model.P)[msmmodel.metastable_sets[0]])

    0.035175995105509048

    np.sum(stationary_distribution(model.P)[msmmodel.metastable_sets[1]])

    0.11993648852314229

    np.sum(stationary_distribution(model.P)[msmmodel.metastable_sets[2]])

    0.046300471480295848

    np.sum(stationary_distribution(model.P)[msmmodel.metastable_sets[3]])

    0.34120639335897757

    np.sum(stationary_distribution(model.P)[msmmodel.metastable_sets[4]])

    0.45738065153207519

    [sets[1] == set(msmmodel.metastable_sets[0]),
    sets[2] == set(msmmodel.metastable_sets[2]), 
    sets[3] == set(msmmodel.metastable_sets[3]),
    sets[4] == set(msmmodel.metastable_sets[1]),
    len(sets) == len(msmmodel.metastable_sets), 
    len(sets)]

    [True, True, True, True, True, 5]
```

So, if it is not possible to fix this, it would be good, at least, warning the user at documentation that it has to check the output of "sets".

**Comment by franknoe** [comment]
I think the convention is to order by committor. In your case it seems more reasonable to keep the order in the input (msmmodel.metastable_sets). However in general, this is not possible. If you coarse-grain to sets that cross the boundary to the A/B endstates, these sets must be split, and then the number of output sets will not be identical to the number of sets to be coarse-grained. So it's generally not possible to keep the sequence.
Not sure about a warning, because the behavior is systematic. What about just noting this in the docs?

**Comment by franknoe** [comment]
BTW, the very reason to return the sets is that you don't get what you input. Otherwise we wouldn't need this return.

**Comment by ismaelresp** [comment]
OK, I think just clarifying this on documentation and tutorials would be enough. For example, just saying that sets might be coincident to input or not, but if they are, they can be still in different order.

**Comment by franknoe** [comment]
sure. @marscher, can you include a sentence on this in your next PR, and 
then close this issue?

thanks.

Am 20/01/16 um 15:04 schrieb Ismael Rodriguez Espigares:

> OK, I think just clarifying this on documentation and tutorials would 
> be enough. For example, just saying that sets might be coincident to 
> input or not, but if they are, they can be still in different order.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/677#issuecomment-173213118.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
