### ISSUE TITLE
TICA partial fit

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#682]
Hello, I was wondering if you could make a [`partial_fit`](http://scikit-learn.org/stable/modules/scaling_strategies.html#incremental-learning) method for the `TICA` class (or if it exists already). So that I can feed it trajectory projections in a for loop and fit it incrementally, without having to give the whole dataset at once.

**Comment by stefdoerr** [comment]
I know it accepts `reader` objects and then does that internally but at the moment I don't want to have to subclass from pyemma classes to use the partial fitting.

Any suggestions also on how to hack it in until the method is eventually implemented (if it is) are welcome.

**Comment by franknoe** [comment]
Generally our strategy to deal with RAM problems has been 6.1.1 on that 
page (we stream the data).

As to incremental learning: We could easily do something incremental, 
especially with the new code to compute covariance matrices. However, in 
order to be efficient I think one needs to accumulate data first and 
then trigger the computation of the Eigenvectors. Doing that in one step 
would cause a recalculation of the Eigenvectors for every data chunk fed 
to the estimator. So as I understand partial_fit it would do exactly 
that. Do you know if there is a preferred way of handling this in sklearn?

I could see several options:
1. Not using sklearn nomenclature here and using two methods such as 
`add_data()` and `finalize()`
2. Using `partial_fit(X, y=None, sample_weight=None, 
compute_evd=False)` with an extra argument `compute_evd=False` 
(does that break the API?)
3. Changing the Role of the estimator such that it only does estimate 
the covariance matrices, and making `get_tica_transform()` an extra 
analysis function one can call afterwards.

I'm between 1. and 2. Is there any standard solution to this problem?

Am 04/02/16 um 17:04 schrieb Stefan:

> Hello, I was wondering if you could make a 
> (|partial_fit|)[http://scikit-learn.org/stable/modules/scaling_strategies.html#incremental-learning] 
> method for the |TICA| class (or if it exists already). So that I can 
> feed it trajectory projections in a for loop and fit it incrementally, 
> without having to give the whole dataset at once.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/682.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by mpharrigan** [comment]
We use a flag `_is_dirty` that we set every time new data is added

https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/decomposition/tica.py#L155

Any time you use the eigenvectors, it checks this flag and recomputes the eigensystem if necessary

https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/decomposition/tica.py#L198

**Comment by franknoe** [comment]
That's an option, thanks!

Am 04/02/16 um 19:01 schrieb Matthew Harrigan:

> We use a flag |_is_dirty| that we set every time new data is added
> 
> https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/decomposition/tica.py#L155
> 
> Any time you use the eigenvectors, it checks this flag and recomputes 
> the eigensystem if necessary
> 
> https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/decomposition/tica.py#L198
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/682#issuecomment-179969681.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
@marscher , @clonker and @fabian-paul , we should discuss if we can find 
a general way to handle this in the new data processing development 
branch. In principle all streamable Estimators can be treated this way.

My feeling is that generally estimation consists of steps
1. initialize or reset estimation.
2. add (part of) data X.
3. finalize estimation / compute results.

The sklearn nomenclature appears to suggest to do combinations of these 
(1-3 or 2-3) together using fit() or partial_fit(). One can work around 
that and do 3 lazily as suggested by Matthew with a flag. We could 
implement a slightly more general API that allows to do 1-3 separately 
and expose the sklearn API on top of that. Then it would nice to have a 
way that avoids to reimplement lazy result calculation for every 
streamable Estimator separately and rather standartize this.

Am 04/02/16 um 19:01 schrieb Matthew Harrigan:

> We use a flag |_is_dirty| that we set every time new data is added
> 
> https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/decomposition/tica.py#L155
> 
> Any time you use the eigenvectors, it checks this flag and recomputes 
> the eigensystem if necessary
> 
> https://github.com/msmbuilder/msmbuilder/blob/master/msmbuilder/decomposition/tica.py#L198
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/682#issuecomment-179969681.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
There is a bug in partial_fit. If the trajectory is shorter than the lag time it crashes at the following code because n_chunks = 0

``` python
al_fit, n_chunks)
    217 
    218     def _init_covar(self, partial_fit, n_chunks):
--> 219         nsave = int(max(log(n_chunks, 2), 2))
    220         # in case we do a one shot estimation, we want to re-initialize running_covar
    221         if not hasattr(self, '_covar') or not partial_fit:

ValueError: math domain error
```

**Comment by marscher** [comment]
Thanks for reporting.

**Comment by marscher** [comment]
Is this RC3 or latest devel?

**Comment by stefdoerr** [comment]
Latest devel. Just pulled from the git

**Comment by stefdoerr** [comment]
Hm. When I ran `setup.py install` though it created a folder called: pyEMMA-2.1rc3+72.g53199f1

**Comment by marscher** [comment]
On 22.03.2016 14:14, Stefan wrote:

> Hm. When I ran setup.py though it created a folder called:
> pyEMMA-2.1rc3+72.g53199f1
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/682#issuecomment-199807656
> 
> Thats fine. Im just wondering why you were able to pass a too short traj
> to estimate (or partial fit which just calls estimate), because we are
> already checking for this case.

Can you please provide some details about the lag time and traj lengths
you are feeding in? Or at best, provide a minimal breaking example.

**Comment by stefdoerr** [comment]
[data.npy.zip](https://github.com/markovmodel/PyEMMA/files/184203/data.npy.zip)

``` python
import numpy as np
data = np.load('data.npy')
from pyemma.coordinates.transform.tica import TICA 
tic = TICA(20)
for d in data: tic.partial_fit(d)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-fced6c1be5f1> in <module>()
----> 1 for d in data: tic.partial_fit(d)

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg/pyemma/coordinates/transform/tica.py in partial_fit(self, X)
    211         iterable = source(X)
    212 
--> 213         self._estimate(iterable, partial=True)
    214         self._estimated = False
    215 

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg/pyemma/coordinates/transform/tica.py in _estimate(self, iterable, **kw)
    259         with it:
    260             self._progress_register(it._n_chunks, "calculate mean+cov", 0)
--> 261             self._init_covar(partial_fit, it._n_chunks)
    262             for X, Y in it:
    263                 self._covar.add(X, Y)

/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg/pyemma/coordinates/transform/tica.py in _init_covar(self, partial_fit, n_chunks)
    217 
    218     def _init_covar(self, partial_fit, n_chunks):
--> 219         nsave = int(max(log(n_chunks, 2), 2))
    220         # in case we do a one shot estimation, we want to re-initialize running_covar
    221         if not hasattr(self, '_covar') or not partial_fit:

ValueError: math domain error
```

**Comment by stefdoerr** [comment]
I also wanted to ask, what class do I need to subclass (or methods need implementing) so that I can feed a data streamer to TICA instead of using the partial_fit method?

**Comment by stefdoerr** [comment]
Also another question: How can I change the number of tica dimensions after doing a partial_fit? The only way I know is doing it at the constructor (which I don't want). Like, can I set some internal TICA attribute which `tica.transform()` will honor? I tried `tica._dim` which `get_outputs()` seems to use but `tica.transform()` does not.

**Comment by franknoe** [comment]
I'm not sure if this is implemented, but since TICA is an estimator it 
should always be possible to do that by means of set_params(...).

On the other hand the number of dimensions is at least in the current 
implementation not really an estimation parameter, so there's nothing 
against being able to set it explicitly later on.

Am 22/03/16 um 15:46 schrieb Stefan:

> Also another question: How can I change the number of tica dimensions 
> after doing a partial_fit? The only way I know is doing it at the 
> constructor (which I don't want). Like, can I set some internal TICA 
> attribute which |tica.transform()| will honor? I tried |tica._dim| 
> which |get_outputs()| seems to use but |tica.transform()| does not.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/682#issuecomment-199848175

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
@franknoe Worked like a charm! Thanks :) It happens quite often that our users want to test different numbers of dimensions so it spares lots of time just doing the projection step instead of redoing the whole covar calculations.

**Comment by marscher** [comment]
So we should provide a setter for dimension

**Comment by stefdoerr** [comment]
Another problem I encountered. Happens both with partial_fit and the normal `tica` function

[debug.npy.zip](https://github.com/markovmodel/PyEMMA/files/185863/debug.npy.zip)

``` python
import numpy as np
from pyemma.coordinates.transform.tica import TICA
tica = TICA(20)
for d in data: tica.partial_fit(d)
a = tica.transform(data[0])
```

```
  File "/shared/sdoerr/Work/htmd/htmd/projections/tica.py", line 107, in project
    proj.append(self.tic.transform(d))

  File "/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg/pyemma/coordinates/transform/transformer.py", line 71, in transform
    mapped = self._transform_array(X)

  File "/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg/pyemma/coordinates/transform/tica.py", line 306, in _transform_array
    Y = np.dot(X_meanfree, self.eigenvectors[:, 0:self.dimension()])

  File "<decorator-gen-142>", line 2, in eigenvectors

  File "/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg/pyemma/coordinates/transform/tica.py", line 51, in _lazy_estimation
    tica_obj._diagonalize()

  File "/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg/pyemma/coordinates/transform/tica.py", line 279, in _diagonalize
    eigenvalues, eigenvectors = eig_corr(self.cov, self.cov_tau, self.epsilon)

  File "/shared/sdoerr/Software/anaconda3/lib/python3.5/site-packages/pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg/pyemma/util/linalg.py", line 151, in eig_corr
    assert np.allclose(C0.T, C0), 'C0 is not a symmetric matrix'

AssertionError: C0 is not a symmetric matrix
```

Any idea what can cause this? The arrays look fine to me

**Comment by stefdoerr** [comment]
Actually scratch that. There seems to be something wrong in the first array. Wait till I find out what it is

**Comment by stefdoerr** [comment]
Okay, it has some NaNs which obviously the TICA estimator doesn't like. I will find the source of my NaNs. If you really feel like it you can put a check in as well, although in this case it's obviously my fault for feeding crap to TICA :)
