### ISSUE TITLE
impl/enable random access for csvreader

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#691]
@clonker can you do this please once #687 is merged?

**Comment by clonker** [comment]
Sure. Maybe one can also think about enabling it in general for all readers that return a traj-info with non-empty offsets?

**Comment by marscher** [comment]
The latter sounds like a great idea :+1:

**Comment by marscher** [comment]
I'm not sure if this is really worth the effort... what do you think @clonker?

**Comment by clonker** [comment]
Hmm I think if the stride-based random access in the csv reader was properly implemented using offsets and seek, it would be essentially the same as in the feature reader where the random access strategies get converted into the stride-based thing. What I dont know right away is how it should behave if the trajectory info cache is switched off. Assuming it always being on, implementing it is probably a matter of one or two days. The DataInMemory/HDF5 readers could be specialized to use fancy indexing.

If it is worth the effort depends on whether it would be used... I am not sure about that one.

**Comment by marscher** [comment]
agreed with @clonker, that this is not worth the effort.
