### ISSUE TITLE
dummy progressbar object gets "printed":

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#697]
a line appears screen when a progressbar is instantiated:

``` python
<pyemma._base.progress.reporter.ProgressReporter._progress_register.<locals>.dummy object at 0x7f477d048358>
```

is this new? Is this wanted? Related with #696? See this image for more info:
![new_tmd1](https://cloud.githubusercontent.com/assets/7518004/13178707/a1e7608c-d720-11e5-8ae7-e74d670f4c93.png)

**Comment by marscher** [comment]
I've also increased the threshold to at least two chunks.
