### ISSUE TITLE
tica.fit() does not return a model

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#699]

**Comment by marscher** [comment]
but estimate does...

**Comment by marscher** [comment]
This is not an issue- scikit-learn Estimator.fit method does not return the model

**Comment by franknoe** [comment]
It is - in sklearn, fit() returns the parametrized estimator (usually 
just self). In fact this is a mistake in our own Estimator, i.e. the 
return is missing.

Nothing we need to fix in rc, but we should do that before the full release.

Am 21/02/16 um 14:08 schrieb Martin K. Scherer:

> This is not an issue- scikit-learn Estimator.fit method does not 
> return the model
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/699#issuecomment-186820236.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
