### ISSUE TITLE
dependencies feature_coortransforms

### ISSUE THREAD

**Issue by trendelkampschroer** [markovmodel/PyEMMA#70]
This branch has psutil and sklearn as dependency. Is that already accounted for in setup.py?

**Comment by franknoe** [comment]
We should avoid the sklearn dependency at this point. Why do we need it?

Am 20/02/15 um 11:11 schrieb Benjamin Trendelkamp-Schroer:
>
> This branch has psutil and sklearn as dependency. Is that already 
> accounted for in setup.py?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/70>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 20.02.2015 um 11:21 schrieb Frank Noe:
> We should avoid the sklearn dependency at this point. Why do we need it?
its temporarily there for kmeans support. Since its encapsulated in its
own class it will be easy to add your own impl in the future.
> 
> Am 20/02/15 um 11:11 schrieb Benjamin Trendelkamp-Schroer:
>>
>> This branch has psutil and sklearn as dependency. Is that already
>> accounted for in setup.py?
yes.
