### ISSUE TITLE
inconsistency in TICA documentation 

### ISSUE THREAD

**Issue by cclementi** [markovmodel/PyEMMA#704]
I found an inconsistency in the TICA documentation. In the function header it states that the option kinetic_map is set to True by default:

_Signature: coor.tica(data=None, lag=10, dim=-1, var_cutoff=0.95, kinetic_map=True, stride=1, force_eigenvalues_le_one=False, mean=None)_ 

However, in the parameter explanation it says: 

_kinetic_map : bool, optional, default False_

**Comment by marscher** [comment]
good spot! Thank you!
