### ISSUE TITLE
Replace long with int datatype

### ISSUE THREAD

**Issue by dominikwille** [markovmodel/PyEMMA#705]
The long and int datatypes  in python are unified in versions since ~2001: https://www.python.org/dev/peps/pep-0237/. The long datatype was removed in 3 phases. And is now completely removed in Python 3.5. 

Especially the usage of the long datatype in pyemma/thermo/util/util.py causes errors using pyEMMA with python 3.5.

**Comment by marscher** [comment]
Thanks for your report. Python 2.7 still distinguishes these types and unfortunately this particular function in thermo has only been blackbox tested on 2.7. Fixed via #706
