### ISSUE TITLE
lag time input in the implied timescale command in pyemma.msm 

### ISSUE THREAD

**Issue by cclementi** [markovmodel/PyEMMA#707]
In both the function and the object for calculating the implied timescale in pyemma.msm there is no documentation on the feature that, if a single lag time is provided as input, a sequence of different lag times smaller than the provided value will also be used

**Comment by franknoe** [comment]
True. Thanks!

Am 24/02/16 um 20:29 schrieb Cecilia Clementi:

> In both the function and the object for calculating the implied 
> timescale in pyemma.msm there is no documentation on the feature that, 
> if a single lag time is provided as input, a sequence of different lag 
> times smaller than the provided value will also be used
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/707.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
