### ISSUE TITLE
WARNING:pyemma.msm.estimators.implied_timescales

### ISSUE THREAD

**Issue by Sawrz** [markovmodel/PyEMMA#708]
The warning message 
"WARNING:pyemma.msm.estimators.implied_timescales.ImpliedTimescales[1]:Estimation has failed at lagtimes: [ 10  20  50 100 200 250 300 350 400]. Run single-lag estimation at these lags to track down the error."
is in my opinion not specific enough. Would be great if this message could track the lagtime where the problem appears down.

Picture:
![error](https://cloud.githubusercontent.com/assets/9134364/13322666/c49d5c94-dbd5-11e5-90fd-ce4aa6c747c4.PNG)

**Comment by franknoe** [comment]
Yes. We are planning to store the Exceptions thrown at each lag time 
individually.

This error looks like something has seriously failed though.

Am 25/02/16 um 15:42 schrieb Sandro Wrzalek:

> The warning message
> "WARNING:pyemma.msm.estimators.implied_timescales.ImpliedTimescales[1]:Estimation 
> has failed at lagtimes: [ 10 20 50 100 200 250 300 350 400]. Run 
> single-lag estimation at these lags to track down the error."
> is in my opinion not specific enough. Would be great if this message 
> could track the lagtime where the problem appears down.
> 
> Picture:
> error 
> https://cloud.githubusercontent.com/assets/9134364/13322666/c49d5c94-dbd5-11e5-90fd-ce4aa6c747c4.PNG
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/708.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
