### ISSUE TITLE
Tutorial on http://www.emma-project.org/v2.0/generated/MSM_BPTI.html has a wrong example

### ISSUE THREAD

**Issue by ismaelresp** [markovmodel/PyEMMA#712]
On the scatter contour with clusters and membership probabilities the attribute that must be used is pyemma.markov_model.metastable_memberships, not metastable_distributions acording to the text:

> Now we want to coarse-grain our system to get a simpler description. The PCCA method [5] uses the eigenvectors in order to perform a spectral clustering. This clustering is fuzzy, i.e. each of our k-means clusters is linked to one of the metastable states with a certain probability or membership. Here we plot the Bayesian inverse, i.e. the probability to be in a small state given that we are in a metastable state. We choose three metastable states, so we have three distributions:

```
M.pcca(3)
-- pcca_dist = M.metastable_distributions
++pcca_dist = M.metastable_memberships 
f, (ax1,ax2,ax3) = subplots(ncols=3)
f.set_size_inches(15,5)
cmap=plt.cm.Blues
mplt.scatter_contour(cc_x, cc_y, pcca_dist[0], fig=f, ax=ax1, colorbar=False, cmap=cmap)
mplt.scatter_contour(cc_x, cc_y, pcca_dist[1], fig=f, ax=ax2, colorbar=False, cmap=cmap)
mplt.scatter_contour(cc_x, cc_y, pcca_dist[2], fig=f, ax=ax3, colorbar=False, cmap=cmap)
```

metastable_distributions cointains "Probability of metastable states to visit an MSM state by PCCA++" acording to documentation http://www.emma-project.org/v2.0/api/generated/pyemma.msm.markov_model.html#pyemma.msm.markov_model.

**Comment by franknoe** [comment]
Hmm, no the text says "Here we plot the Bayesian inverse, i.e. the 
probability to be in a small state given that we are in a metastable 
state". This is exactly metastable_distributions.

Am 26/02/16 um 17:02 schrieb Ismael Rodriguez Espigares:

> On the scatter contour with clusters and membership probabilities the 
> attribute that must be used is 
> pyemma.markov_model.metastable_memberships, not 
> metastable_distributions acording to the text:
> 
> ```
> Now we want to coarse-grain our system to get a simpler
> description. The PCCA method [5] uses the eigenvectors in order to
> perform a spectral clustering. This clustering is fuzzy, i.e. each
> of our k-means clusters is linked to one of the metastable states
> with a certain probability or membership. Here we plot the
> Bayesian inverse, i.e. the probability to be in a small state
> given that we are in a metastable state. We choose three
> metastable states, so we have three distributions:
> ```
> 
> |M.pcca(3) -- pcca_dist = M.metastable_distributions ++pcca_dist = 
> M.metastable_memberships f, (ax1,ax2,ax3) = subplots(ncols=3) 
> f.set_size_inches(15,5) cmap=plt.cm.Blues mplt.scatter_contour(cc_x, 
> cc_y, pcca_dist[0], fig=f, ax=ax1, colorbar=False, cmap=cmap) 
> mplt.scatter_contour(cc_x, cc_y, pcca_dist[1], fig=f, ax=ax2, 
> colorbar=False, cmap=cmap) mplt.scatter_contour(cc_x, cc_y, 
> pcca_dist[2], fig=f, ax=ax3, colorbar=False, cmap=cmap) |
> 
> metastable_distributions cointains "Probability of metastable states 
> to visit an MSM state by PCCA++" acording to documentation 
> http://www.emma-project.org/v2.0/api/generated/pyemma.msm.markov_model.html#pyemma.msm.markov_model.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/712.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by ismaelresp** [comment]
Ah, Ok, the Bayesian inverse of the probability in the previous sentence.
