### ISSUE TITLE
object.timescales: method or array? 

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#715]
I'd vote for unifying this, but is it possible without breaking people's code? 

``` python
print(type(TICA.timescales))
print(type(its.timescales))
print(type(iMSM.timescales))
# <class 'numpy.ndarray'>
# <class 'numpy.ndarray'>
# <class 'method'>
```

**Comment by franknoe** [comment]
We have discussed this issue previously for eigenvalues, and no, we 
can't avoid changing the API behavior if we unify this. We can only 
offer both options if we use different names for attributes and methods 
(Sklearn uses tailing underscores to denote attributes, e.g. 
"timescales_". But if we don't systematically do that everywhere I think 
it's even more confusing).

The reason why the MSM object has a timescales function is that you may 
still have to do the eigenvalue decomposition and that could take long 
for a large transition matrix. TICA and ITS have the timescales already 
computed after estimation, so it's just an attribute. So the difference 
makes sense, but I agree if you just compare their behavior like you 
did, it is confusing.

I think this is a minor annoyance and would opt for not changing the API 
at this point. It is one of the things to keep in mind for the next 
major release.

Am 01/03/16 um 10:18 schrieb Guillermo Pérez-Hernández:

> I'd vote for unifying this, but is it possible without breaking 
> people's code?
> 
> print(type(TICA.timescales))
> print(type(its.timescales))
> print(type(iMSM.timescales))
> 
> # <class 'numpy.ndarray'>
> 
> # <class 'numpy.ndarray'>
> 
> # <class 'method'>
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/715.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by gph82** [comment]
got it, thanks!

On 03/01/2016 10:33 AM, Frank Noe wrote:

> We have discussed this issue previously for eigenvalues, and no, we
> can't avoid changing the API behavior if we unify this. We can only
> offer both options if we use different names for attributes and methods
> (Sklearn uses tailing underscores to denote attributes, e.g.
> "timescales_". But if we don't systematically do that everywhere I think
> it's even more confusing).
> 
> The reason why the MSM object has a timescales function is that you may
> still have to do the eigenvalue decomposition and that could take long
> for a large transition matrix. TICA and ITS have the timescales already
> computed after estimation, so it's just an attribute. So the difference
> makes sense, but I agree if you just compare their behavior like you
> did, it is confusing.
> 
> I think this is a minor annoyance and would opt for not changing the API
> at this point. It is one of the things to keep in mind for the next
> major release.
> 
> Am 01/03/16 um 10:18 schrieb Guillermo Pérez-Hernández:
> 
> > I'd vote for unifying this, but is it possible without breaking
> > people's code?
> > 
> > print(type(TICA.timescales))
> > print(type(its.timescales))
> > print(type(iMSM.timescales))
> > 
> > # <class 'numpy.ndarray'>
> > 
> > # <class 'numpy.ndarray'>
> > 
> > # <class 'method'>
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/markovmodel/PyEMMA/issues/715.
> 
> ## 
> 
> ---
> 
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> 
> ## Mail: Arnimallee 6, 14195 Berlin, Germany
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/715#issuecomment-190632992.

## 

Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75776
