### ISSUE TITLE
hmm.cktest fails

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#716]
```
HMM  <class 'pyemma.msm.estimators.maximum_likelihood_hmsm.MaximumLikelihoodHMSM'>
3
Traceback (most recent call last):
  File "scripts/msm_feature_coarse_grain.py", line 162, in <module>
    hmm_ck = hmm.cktest(mlags=10,conf=0.95,err_est=False,show_progress=True)
  File ".../miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.py",
line 317, in cktest
    ck.estimate(self._dtrajs_full)
  File "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py",
line 342, in estimate
    self._model = self._estimate(X)
  File "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/msm/estimators/lagged_model_validators.py",
line 137, in _estimate
    n_jobs=self.n_jobs)
  File "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py",
line 300, in estimate_param_scan
    res = pool(task_iter)
  File "./miniconda/lib/python2.7/site-packages/joblib/parallel.py",
line 653, in __call__
    self.dispatch(function, args, kwargs)
  File "./miniconda/lib/python2.7/site-packages/joblib/parallel.py",
line 400, in dispatch
    job = ImmediateApply(func, args, kwargs)
  File "./miniconda/lib/python2.7/site-packages/joblib/parallel.py",
line 138, in __init__
    self.results = func(*args, **kwargs)
  File "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py",
line 132, in _estimate_param_scan_worker
    model = estimator.estimate(X, **params)
  File "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py",
line 342, in estimate
    self._model = self._estimate(X)
  File "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.py",
line 189, in _estimate
    assert _types.is_int(self.nstates) and self.nstates > 1 and
self.nstates <= msm_init.nstates, \
  File "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/msm/models/msm.py",
line 202, in nstates
    return self._nstates
AttributeError: 'MaximumLikelihoodMSM' object has no attribute '_nstates'
```

**Comment by franknoe** [comment]
Please update. Perhaps you have a mix of a older PyEMMA version (2.0.3) 
and a newer bhmm version...

Am 04/03/16 um 12:23 schrieb fabian-paul:

> |HMM <class 
> 'pyemma.msm.estimators.maximum_likelihood_hmsm.MaximumLikelihoodHMSM'> 
> 3 Traceback (most recent call last): File 
> "scripts/msm_feature_coarse_grain.py", line 162, in <module> hmm_ck = 
> hmm.cktest(mlags=10,conf=0.95,err_est=False,show_progress=True) File 
> ".../miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.py", 
> line 317, in cktest ck.estimate(self._dtrajs_full) File 
> "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py", 
> line 342, in estimate self._model = self._estimate(X) File 
> "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/msm/estimators/lagged_model_validators.py", 
> line 137, in _estimate n_jobs=self.n_jobs) File 
> "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py", 
> line 300, in estimate_param_scan res = pool(task_iter) File 
> "./miniconda/lib/python2.7/site-packages/joblib/parallel.py", line 
> 653, in __call__ self.dispatch(function, args, kwargs) File 
> "./miniconda/lib/python2.7/site-packages/joblib/parallel.py", line 
> 400, in dispatch job = ImmediateApply(func, args, kwargs) File 
> "./miniconda/lib/python2.7/site-packages/joblib/parallel.py", line 
> 138, in **init** self.results = func(_args, *_kwargs) File 
> "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py", 
> line 132, in _estimate_param_scan_worker model = estimator.estimate(X, 
> **params) File 
> "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/_base/estimator.py", 
> line 342, in estimate self._model = self._estimate(X) File 
> "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.py", 
> line 189, in _estimate assert _types.is_int(self.nstates) and 
> self.nstates > 1 and self.nstates <= msm_init.nstates, \ File 
> "./miniconda/lib/python2.7/site-packages/pyEMMA-2.0.3-py2.7-linux-x86_64.egg/pyemma/msm/models/msm.py", 
> line 202, in nstates return self._nstates AttributeError: 
> 'MaximumLikelihoodMSM' object has no attribute '_nstates' |
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/716.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
@fabian-paul has this been caused by an old version?

**Comment by franknoe** [comment]
I think this might be the issue of not getting a bhmm update with the 
release candidate.

Am 10/03/16 um 18:23 schrieb Martin K. Scherer:

> @fabian-paul https://github.com/fabian-paul has this been caused by 
> an old version?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/716#issuecomment-194965482.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
BTW, when can we release 2.1 normally? I guess that might fix this problem.

Am 10/03/16 um 18:23 schrieb Martin K. Scherer:

> @fabian-paul https://github.com/fabian-paul has this been caused by 
> an old version?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/716#issuecomment-194965482.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I fear it won't solve the problem:

```
marscher@area51:~/workspace/pyemma/doc$ conda install pyemma=2.0.3
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: ...........

Package plan for installation in environment /home/marscher/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numexpr-2.4.6              |      np110py34_0         334 KB
    scikit-learn-0.17.1        |      np110py34_0         8.8 MB
    pyemma-2.0.3               |           py34_0         692 KB
    ------------------------------------------------------------
                                           Total:         9.8 MB

The following packages will be UPDATED:

    numexpr:      2.4.4-np110py34_p0 [mkl] --> 2.4.6-np110py34_0
    scikit-learn: 0.17-np110py34_p1  [mkl] --> 0.17.1-np110py34_0

The following packages will be DOWNGRADED:

    bhmm:         0.6.1-np110py34_0  --> 0.5.2-np110py34_0
    pyemma:       2.0.4-py34_1       --> 2.0.3-py34_0

Proceed ([y]/n)? y

Fetching packages ...
numexpr-2.4.6- 100%
|######################################################################################################################|
Time: 0:00:00 429.82 kB/s
scikit-learn-0 100%
|######################################################################################################################|
Time: 0:00:11 805.95 kB/s
pyemma-2.0.3-p 100%
|######################################################################################################################|
Time: 0:00:01 653.47 kB/s
Extracting packages ...
[      COMPLETE
]|#########################################################################################################################################|
100%
Unlinking packages ...
[      COMPLETE
]|#########################################################################################################################################|
100%
Linking packages ...
[      COMPLETE
]|#########################################################################################################################################|
100%
marscher@area51:~/workspace/pyemma/doc$ conda install pyemma=2.0.4
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
Solving package specifications: ...........

Package plan for installation in environment /home/marscher/miniconda:

The following packages will be UPDATED:

    pyemma: 2.0.3-py34_0 --> 2.0.4-py34_1

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE
]|#########################################################################################################################################|
100%
Linking packages ...
[      COMPLETE
]|#########################################################################################################################################|
```

**Comment by marscher** [comment]
However I'd expect that we can close the bug fixing window at end of this week.
