### ISSUE TITLE
bhmm not updated

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#723]
I have just installed PyEMMA2.1rc3 on a Mac using conda. This has itself not triggered a bhmm update from 0.5.3 to 0.6.1, resulting in a failure of the HMM code. After manual update of bhmm, it works fine, but I don't see why bhmm is not automatically updated. The meta.yaml looks good to me. Any ideas?

**Comment by marscher** [comment]
is it reproducible?

**Comment by marscher** [comment]
how did you invoke conda?

**Comment by marscher** [comment]
`conda install -c omnia/label/pre -c omnia pyemma`  should do the trick, but it doesn't. IMHO this a another bug in conda (channel handling/overriding).

Even if one does not try to install the RC version, bhmm is not going to be updated, if it was installed already - very strange.

**Comment by franknoe** [comment]
Just tested on Cecilia's Mac:

Resetting...

```
1) conda uninstall pyemma
2) conda uninstall bhmm
```

Installing PyEMMA 2.0.4. BHMM is installed as version 0.5.2, as it should be:

```
3) conda install pyemma
4) conda list | grep 'bhmm'
bhmm                      0.5.2               np110py27_0    http://conda.binstar.org/omnia/osx-64/bhmm-0.5.2-np110py27_0.tar.bz2
```

Installing PyEMMA2.1rc3. BHMM is not updated, although it should:

```
5) conda install -c omnia/label/pre pyemma
6) conda list | grep 'bhmm'
bhmm                      0.5.2               np110py27_0    http://conda.binstar.org/omnia/osx-64/bhmm-0.5.2-np110py27_0.tar.bz2
```

This leads to problems because PyEMMA2.1 can't work with bhmm 0.5.2. A subsequent update of bhmm fixes it:

```
7) conda install bhmm
bhmm                      0.6.1               np110py27_0    http://conda.binstar.org/omnia/osx-64/bhmm-0.6.1-np110py27_0.tar.bz2
```

**Comment by franknoe** [comment]
Maybe requirements as "<x.x" don't lead to updates but just need to be 
satisfied?

Can we do something like ">=0.6 <0.7"?

Am 08/03/16 um 18:28 schrieb Martin K. Scherer:

> |conda install -c omnia/label/pre -c omnia pyemma| should do the 
> trick, but it doesn't. IMHO this a another bug in conda (channel 
> handling/overriding).
> 
> Even if one does not try to install the RC version, bhmm is not going 
> to be updated, if it was installed already - very strange.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-193879323.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
We can try to enforce the second clause on the version. But actually conda should notice that there is a newer version of bhmm and install it, because this is the default behaviour.

**Comment by marscher** [comment]
https://github.com/conda/conda/issues/2011 seems to be related.

**Comment by franknoe** [comment]
One option would be to fix the bhmm version. That would force us to release a PyEMMA patch whenever we have a bhmm patch, which is annoying, but at least this should generate a functional pair.

With the next bhmm release I think we can move to something like >=0.7 which should solve the problems, but we'll have to wait for that version.

**Comment by marscher** [comment]
I think this problem arises on how conda calculates update priorities,
which has already been reported upstream (during the update of X the
dependency Y has not been updated). So there is hope, that this issue
will be fixed soon.

In the meantime I'd vote against creating rigid version pairs to
circumvent this behavior, since it will most likely create more head
ages than it will solve problems. We can add a FAQ question with error
messages already reported, so people able to google/reading the doc will
be able to solve this manually (until this is fixed upstream).

**Comment by franknoe** [comment]
Well I think at the moment many or all people doing an update will run 
into this problem, because they don't get the bhmm version that works 
for them and that's certainly worse than what fixing a version number 
would do.

Never assume that anyone can fix an issue by reading the docs. The 
exceptions are unfortunately not such that someone who is not a Python 
pro knows what to do or where to look for a fix. IMO, user-friendliness 
implies that we avoid any kind of exception. I know that's practically 
not achievable in all cases, but all cases that we can avoid should be 
avoided.

Am 11/03/16 um 13:03 schrieb Martin K. Scherer:

> I think this problem arises on how conda calculates update priorities,
> which has already been reported upstream (during the update of X the
> dependency Y has not been updated). So there is hope, that this issue
> will be fixed soon.
> 
> In the meantime I'd vote against creating rigid version pairs to
> circumvent this behavior, since it will most likely create more head
> ages than it will solve problems. We can add a FAQ question with error
> messages already reported, so people able to google/reading the doc will
> be able to solve this manually (until this is fixed upstream).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-195341160.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
You're right, we can not enforce users to read the documentation for things which worked out of the box before. I've noticed that the change of dependency calculation in conda was introduced recently with a version higher than 3.19. So downgrading conda actually helps, but the standard behaviour of conda to update everything will break this again very soon.

Maybe we should stick to a "stable" conda version for the whole omnia channel via a minimal meta-pkg or even within pyemmas dependencies (which is also a bad thing todo, but it seems we only have choice between pest and cholera here...)

**Comment by franknoe** [comment]
That's very annoying. conda should have a way to allow for stable fixed 
version combinations, the greedy upgrading strategy is bound to break 
things all the time for packages with large dependency trees.

Anyway, let's fix bhmm for now. BTW, when can we release 2.1?

Am 13/03/16 um 13:36 schrieb Martin K. Scherer:

> You're right, we can not enforce users to read the documentation for 
> things which worked out of the box before. I've noticed that the 
> change of dependency calculation in conda was introduced recently with 
> a version higher than 3.19. So downgrading conda actually helps, but 
> the standard behaviour of conda to update everything will break this 
> again very soon.
> 
> Maybe we should stick to a "stable" conda version for the whole omnia 
> channel via a minimal meta-pkg or even within pyemmas dependencies 
> (which is also a bad thing todo, but it seems we only have choice 
> between pest and cholera here...)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-195948729.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by mcg1969** [comment]
What are the dependency requirements here, as built into the package itself? You can see this with `conda info pyemma`. If the packages own dependencies don't require an update, then of course conda cannot be expected to update it. Yes, the update behavior has changed, but in fact it was broken in significant ways before. At worst we have traded other significant bugs for this one. But more likely, conda is still respecting the metadata, but in a different manner.

**Comment by mcg1969** [comment]
> Maybe requirements as "<x.x" don't lead to updates but just need to be satisfied?

That is right. If the currently installed version satisfies this dependency already, it will not be updated, unless you explicitly ask it to.

**Comment by franknoe** [comment]
The requirement in pyemma is defined as bhmm<0.7, which made us expect 
that bhmm would be upgraded to the highest version under 0.7. However 
this is not the case - a user with bhmm 0.5.3 doesn't get an upgrade, 
although 0.6 exists. This is what's causing the problem, because 
actually we would need 0.6<=bhmm<0.7.
Is this a bug or an intended change of policy? How do we enforce the 
right policy in our case?

Am 13/03/16 um 14:06 schrieb Michael C. Grant:

> What are the dependency requirements here, as built into the package 
> itself? You can see this with |conda info pyemma|. If the packages own 
> dependencies don't require an update, then of course conda cannot be 
> expected to update it. Yes, the update behavior has changed, but in 
> fact it was broken in significant ways before. At worst we have traded 
> other significant bugs for this one. But more likely, conda is still 
> respecting the metadata, but in a different manner.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-195954054.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by mcg1969** [comment]
Yes, your second inequality pair is what you need. Dependencies are strict satisfaction requirements and nothing more. The do not necessarily trigger updates.

**Comment by marscher** [comment]
So we would need a minimum requirement of our dependencies then.

**Comment by marscher** [comment]
Thank you @mcg1969 for your help!

**Comment by mcg1969** [comment]
This is not a change in "policy". It is a change of behavior, yes, but it was never intended for people to depend on dependency upgrades in the way you are. I'm sorry this is biting you.

**Comment by franknoe** [comment]
Well they did before. Anyway, how do we write this, and can you point us 
to where this is documented?
Do we simply need two lines, one with the maximum and one with the 
minimum requirement?

Am 13/03/16 um 14:10 schrieb Michael C. Grant:

> Yes, your second inequality pair is what you need. Dependencies are 
> strict satisfaction requirements and nothing more. The do not 
> necessarily trigger updates.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-195954739.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by mcg1969** [comment]
Here's the relevant documentation: http://conda.pydata.org/docs/spec.html#build-version-spec

**Comment by franknoe** [comment]
Thanks Michael. Would you recommend a different approach in a situation 
when package1 depends on package2, but package2 is still immature and 
subject to API changes?

Am 13/03/16 um 14:12 schrieb Michael C. Grant:

> This is not a change in "policy". It is a change of behavior, yes, but 
> it was never intended for people to depend on dependency upgrades in 
> the way you are. I'm sorry this is biting you.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-195954799.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
ok, so we need `bhmm>=0.6,<0.7`

Am 13/03/16 um 14:14 schrieb Michael C. Grant:

> Here's the relevant documentation: 
> http://conda.pydata.org/docs/spec.html#build-version-spec
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-195955476.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by mcg1969** [comment]
Frank,  your question is a good one, and I will have to think about it. I have to leave right now but when I get back I will offer my thoughts.

**Comment by franknoe** [comment]
Thanks! Any many thanks again for your help.

Am 13/03/16 um 14:42 schrieb Michael C. Grant:

> Frank, your question is a good one, and I will have to think about it. 
> I have to leave right now but when I get back I will offer my thoughts.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-195959206.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by mcg1969** [comment]
Generally speaking, `conda` dependency specifications should be as _relaxed_ as possible. This is particularly important for dependencies that are very common, like `python` itself. That's because `conda` has to make sure that every package in an environment has its dependencies satisfied; so the tighter the dependencies, the harder that is going to be. 

I noticed in your `bhmm` conda recipe that you have no version specifications at all, which is perfect---_if_ you intend to make sure that it is compatible with all of the likely versions of those packages people are trying to use.

On the other hand, dependencies must also be tight enough to ensure that the package will work. So if `bhmm 0.5*` breaks the current version of `pyemma`, then it _definitely_ needs to be accounted for in the dependencies. So you really do need the `bhmm>=0.6` spec. After all, someone might have other reasons to depend on an older version of `bhmm`, so you need to communicate to `pyemma` users that this is a problem. 

(This situation might not be so common here, because of how specialized these packages are. But I assure you that this exact thing _does_ happen with other packages that rely on, say, `pandas` and `numpy`. We've seen some strange version requirements...)

As for `bhmm<0.7`. As far as I can tell, the latest version available is `0.6.1`. So it seems like this spec is defensive more than anything. It probably won't hurt anything, but I'm not sure it's needed, either---_if_ you are sure that `pyemma` users will have updated their packages to a newer version too by the time `bhmm 0.7` drops.

So I think what I'm saying is that `bhmm>=0.6` is essential here, and `bhmm<0.7` is not necessary. For less specialized packages I'd probably recommend against that second one, but because the two package maintainers are in reasonably close contact, it's fine.

**Comment by franknoe** [comment]
I understand the general philosphy, and agree. In this example, I am 
fairly confident that both restrictions are needed, because
we are planning to make API-changes in bhmm 0.7 that will not be 
backward compatible. So without the restriction bhmm<0.7,
people updating pyemma will get an bhmm update that breaks their pyemma 
code.

I know it's not ideal to have dependencies on a package with a changing 
API, but we are aware that this package is still premature, while we 
still want to use it in the process of developing it.

Am 13/03/16 um 17:19 schrieb Michael C. Grant:

> Generally speaking, |conda| dependency specifications should be as 
> /relaxed/ as possible. This is particularly important for dependencies 
> that are very common, like |python| itself. That's because |conda| has 
> to make sure that every package in an environment has its dependencies 
> satisfied; so the tighter the dependencies, the harder that is going 
> to be.
> 
> I noticed in your |bhmm| conda recipe that you have no version 
> specifications at all, which is perfect---/if/ you intend to make sure 
> that it is compatible with all of the likely versions of those 
> packages people are trying to use.
> 
> On the other hand, dependencies must also be tight enough to ensure 
> that the package will work. So if |bhmm 0.5*| breaks the current 
> version of |pyemma|, then it /definitely/ needs to be accounted for in 
> the dependencies. So you really do need the |bhmm>=0.6| spec. After 
> all, someone might have other reasons to depend on an older version of 
> |bhmm|, so you need to communicate to |pyemma| users that this is a 
> problem.
> 
> (This situation might not be so common here, because of how 
> specialized these packages are, but I assure you that this exact thing 
> /does/ happen with other packages that rely on, say, |pandas| and 
> |numpy|).
> 
> As for |bhmm<0.7|. As far as I can tell, the latest version available 
> is |0.6.1|. So it seems like this spec is defensive more than 
> anything. It probably won't hurt anything, but I'm not sure it's 
> needed, either---/if/ you are sure that |pyemma| users will have 
> updated their packages to a newer version too by the time |bhmm 0.7| 
> drops.
> 
> So I think what I'm saying is that |bhmm>=0.6| is essential here, and 
> |bhmm<0.7| is not necessary. For less specialized packages I'd 
> probably recommend against it, but because the two package maintainers 
> are in reasonably close contact, it's fine.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-195989364.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by mcg1969** [comment]
Ah, very good. So one of the nice things about `bhmm<0.7` in this case is that if someone tries to update `bhmm` to 0.7.1, it will force `conda` to look for an updated version of PyEmma that can handle it, or produce an "Unsatisfiable specifications" error if one does not exist.

**Comment by franknoe** [comment]
I see. Thank Michael, this discussion was really helpful!

Am 13/03/16 um 18:12 schrieb Michael C. Grant:

> Ah, very good. So one of the nice things about |bhmm<0.7| in this case 
> is that if someone tries to update |bhmm| to 0.7.1, it will force 
> |conda| to look for an updated version of PyEmma that can handle it, 
> or produce an "Unsatisfiable specifications" error if one does not exist.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-196003262.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by mcg1969** [comment]
I should note that previous versions of `conda` would happily update `bhmm` by itself _without checking that it would break PyEmma_!

**Comment by franknoe** [comment]
By what? `tools/conda_recipe/meta.yaml` isn't changed yet.

Am 19/03/16 um 16:15 schrieb Martin K. Scherer:

> Closed #723 https://github.com/markovmodel/PyEMMA/issues/723.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#event-595882651

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Which is not the recipe we release from.

**Comment by franknoe** [comment]
So what's the relevance of that file?

Am 19/03/16 um 17:24 schrieb Martin K. Scherer:

> Which is not the recipe we release from.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-198742546

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Travis testing.

**Comment by franknoe** [comment]
So it should be updated too, shouldn't it?

Am 19/03/16 um 17:27 schrieb Martin K. Scherer:

> Travis testing.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-198743559

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Any way, if the file is there it should be fully consistent. Otherwise 
it's confusing.

Am 19/03/16 um 17:27 schrieb Martin K. Scherer:

> Travis testing.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-198743559

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
@franknoe: done. Did you actually receive an email for this issue being referenced by my commit?

**Comment by franknoe** [comment]
No. There was no PR, was it? Looks like you committed directly.

Am 23/03/16 um 13:17 schrieb Martin K. Scherer:

> @franknoe https://github.com/franknoe: done. Did you actually 
> receive an email for this issue being referenced by my commit?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/723#issuecomment-200325546

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
