### ISSUE TITLE
doesn't install prerelease on Linux

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#724]
on shark.imp.fu-berlin.de, the command

```
conda install -c omnia/label/pre pyemma
```

Seems not to find the 2.1 pre-release: 

```
# All requested packages already installed.
# packages in environment at /home/mi/noe/miniconda2:
#
pyemma                    2.0.4                    py27_1    omnia
```

Maybe we should just release 2.1 now? Do you think this will also resolve the problem that bhmm is not updated when installing the pre-release?

**Comment by marscher** [comment]
I can not reproduce this.
