### ISSUE TITLE
Handle situations in which logfile can't be written

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#725]
Importing PyEMMA (at least for the first time, maybe later too...) within a directory that is not writable by the user leads to the following error. This need to be avoided.

```
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File
"/home/mi/noe/miniconda2/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-linux-x86_64.egg/pyemma/__init__.py",
line 27, in <module>
     from . import coordinates
   File
"/home/mi/noe/miniconda2/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-linux-x86_64.egg/pyemma/coordinates/__init__.py",
line 107, in <module>
     from .api import *
   File
"/home/mi/noe/miniconda2/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-linux-x86_64.egg/pyemma/coordinates/api.py",
line 24, in <module>
     from pyemma.util.log import getLogger as _getLogger
   File
"/home/mi/noe/miniconda2/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-linux-x86_64.egg/pyemma/util/log.py",
line 110, in <module>
     setupLogging()
   File
"/home/mi/noe/miniconda2/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-linux-x86_64.egg/pyemma/util/log.py",
line 93, in setupLogging
     dictConfig(D)
   File "/home/mi/noe/miniconda2/lib/python2.7/logging/config.py", line
794, in dictConfig
     dictConfigClass(config).configure()
   File "/home/mi/noe/miniconda2/lib/python2.7/logging/config.py", line
576, in configure
     '%r: %s' % (name, e))
ValueError: Unable to configure handler 'rotating_files': [Errno 13]
Permission denied: <DIRNAME>
```

**Comment by marscher** [comment]
I'd not consider this a bug, because the user will end up with a non-functional logging system, if we would just ignore the fact that log files can not be written. Maybe we should change the default location of the logfile from current working directory to ~/.pyemma/pyemma.log?

**Comment by franknoe** [comment]
Why is this not a bug? It crashes!

Am 09/03/16 um 15:20 schrieb Martin K. Scherer:

> I'd not consider this a bug, because the user will end up with a 
> non-functional logging system, if we would just ignore the fact that 
> log files can not be written. Maybe we should change the default 
> location of the logfile from current working directory to 
> ~/.pyemma/pyemma.log?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/725#issuecomment-194314247.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
As it should

**Comment by marscher** [comment]
We can handle this exception and just silently disable file logging (and trigger a warning) - for people too lazy to take a look and the runtime config.

**Comment by franknoe** [comment]
Sorry, this is not about being lazy. I bet that except for handful of 
people no-one looks at or uses the runtime config. Moreover this crash 
is completely cryptic, so I bet that almost nobody will have an idea how 
to fix this in practice.

Am 09/03/16 um 15:24 schrieb Martin K. Scherer:

> We can handle this exception and just silently disable file logging 
> (and trigger a warning) - for people to lazy to take a look and the 
> runtime config.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/725#issuecomment-194316720.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
I'll take care of this in my next PR
