### ISSUE TITLE
TICA._skipped_trajs bug

### ISSUE THREAD

**Issue by thempel** [markovmodel/PyEMMA#738]
@clonker 
There is a small bug in TICA when using a lag time that is too large for some of the used trajectories. The output of tica_object._skipped_trajs contains redundant information, e.g. in the minimal example shown below I get array([ 2,  2, 12, 12, 22, 22]) for three skipped trajectories.  (This example is not necessarily physically meaningful.) The number of repetitions seems to depend on the stride, by the way.

```
inp = coor.source(filelist)
tica = coor.tica(lag=20000, kinetic_map=True, dim=21)
pipe = coor.pipeline([inp, tica], stride=100)

18-03-16 14:15:14 pyemma.coordinates.transform.tica.TICA[1] WARNING  Had to skip 6 trajectories for being too short. Their indexes are in self._skipped_trajs.

```

**Comment by marscher** [comment]
The skipped_trajs (hidden) feature has been removed in 2.1. As it seems this was a good decision. If you or somebody else desire this feature, I'm happy to accept a PR.

**Comment by gph82** [comment]
Hi @clonker , out of curiosity, can you put the output of the trajectory lengths?

**Comment by clonker** [comment]
Hey, it was @thempel's example.. but maybe he can output them?

**Comment by thempel** [comment]
Hi @gph82 ,
the output does make sense, the trajectories that are skipped are all shorter than the given 20,000 steps. 
`print(inp.trajectory_lengths()[tica._skipped_trajs])`
`[10001 10001 10001 10001 15001 15001]`
(From example above, each trajectory length appears twice.)
