### ISSUE TITLE
Test suite completes but then exits with a logfile error on MacOS

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#739]
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/noe/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/noe/data/software_projects/pyemma/pyemma/util/log.py", line 108, in clean_empty_log_files
    if f is not None and os.stat(f).st_size == 0:
OSError: [Errno 2] No such file or directory: '/Users/noe/.pyemma/pyemma.log'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/Users/noe/anaconda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/Users/noe/data/software_projects/pyemma/pyemma/util/log.py", line 108, in clean_empty_log_files
    if f is not None and os.stat(f).st_size == 0:
OSError: [Errno 2] No such file or directory: '/Users/noe/.pyemma/pyemma.log'
```

**Comment by marscher** [comment]
This does not happen on OSX build on travis: https://travis-ci.org/markovmodel/PyEMMA/jobs/117663633

Can you please update your Python installation? The exit handler is only registered once, but in your case it is called twice. How did you invoke the testsuite?

**Comment by franknoe** [comment]
Am 22/03/16 um 12:52 schrieb Martin K. Scherer:

> This does not happen on OSX build on travis: 
> https://travis-ci.org/markovmodel/PyEMMA/jobs/117663633
> 
> Can you please update your Python installation?
> 
> It's up to date.
> 
> The exit handler is only registered once, but in your case it is 
> called twice. How did you invoke the testsuite?
> 
> `nosetests --with-doctest 
> --doctest-options="+NORMALIZE_WHITESPACE,+ELLIPSIS"`

Using the following lines for 108 and following avoids the problem for 
me. How about that?

``` python
             if f is not None and os.path.exists(f):
                 try:
                     if os.stat(f).st_size == 0:
                         os.remove(f)
                 except OSError as o:
                     print("during removal of empty logfiles there was a 
problem: ", o)
```

> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/739#issuecomment-199777316

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
