### ISSUE TITLE
representation of cluster centers in kmeans, regspace is inconsitent

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#74]
```python
import numpy as np
from pyemma.coordinates.api import kmeans, regspace
traj = np.array([[1.2,3.4],[5.6,7.8],[9.0,1.2]])
clustering = regspace(dmin=7,data=traj)
print clustering.centroids # list of 1-D ndarrays
clustering = kmeans(k=2,data=traj)
print clustering.clustercenters # 2-D ndarray
```
No big problem but a bit annoying if you try to switch the clustering algorithm.
The naming is also reversed. k-means computes centroids. In regspatial the points are not centroids.

**Comment by marscher** [comment]
regspace has changed api : data is first argument as in other clustering api functions

**Comment by marscher** [comment]
we're having the attribute clustercenters for all cluster algorithms, so we should not distinguish between them.

**Comment by marscher** [comment]
renamed regspace.centroids to regspace._clustercenters
