### ISSUE TITLE
import shortcuts module

### ISSUE THREAD

**Issue by lancsa** [markovmodel/PyEMMA#746]
Dear Users,

I'm just working with the "Markov state model for BPTI" iPython tutorial from
http://www.emma-project.org/latest/generated/MSM_BPTI.html

The tutorial import shortcuts module, which is described as: "The shortcuts module is a bunch of functions specific to this workshop - they help us to visualize some of our results. Some of them might become part of the pyemma package once they are more mature."

My problem is I can not import the shortcuts module and thus I can not go on some parts of the tutorial. I could not find any information about this module. Can You suggest me any information about shortcuts module?

Thank You in advance!

**Comment by franknoe** [comment]
This should indeed be fixed. You will get this module when you download 
the notebook example package, but if you just copy the code from the 
website this is not gonna work. In shortcuts, we had defined a few 
functions in the shortcuts module to make plotting easier, but most of 
these plotting functions are now in pyemma.plots. the avg_by_state and 
avg_by_set functions that are still used in this notebook can be easily 
defined within the notebook that you're running. Here's the code to give 
you a solution for now. @gph82 or @marscher, can one of you please fix this?

``` python
def average_by_state(dtraj, x, nstates):
     assert(len(dtraj) == len(x))
     N = len(dtraj)
     res = np.zeros((nstates))
     for i in range(nstates):
         I = np.argwhere(dtraj == i)[:,0]
         res[i] = np.mean(x[I])
     return res

def avg_by_set(x, sets):
     # compute mean positions of sets. This is important because of some 
technical points the set order
     # in the coarse-grained TPT object can be different from the input 
order.
     avg = np.zeros(len(sets))
     for i in range(len(sets)):
         I = list(sets[i])
         avg[i] = np.mean(x[I])
     return avg
```

Am 25/03/16 um 10:18 schrieb lancsa:

> Dear Users,
> 
> I'm just working with the "Markov state model for BPTI" iPython 
> tutorial from
> http://www.emma-project.org/latest/generated/MSM_BPTI.html
> 
> The tutorial import shortcuts module, which is described as: "The 
> shortcuts module is a bunch of functions specific to this workshop - 
> they help us to visualize some of our results. Some of them might 
> become part of the pyemma package once they are more mature."
> 
> My problem is I can not import the shortcuts module and thus I can not 
> go on some parts of the tutorial. I could not find any information 
> about this module. Can You suggest me any information about shortcuts 
> module?
> 
> Thank You in advance!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/746

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by lancsa** [comment]
Thank You, with these function definitions it works!

**Comment by marscher** [comment]
@lancsa How did you obtain your copy of the notebooks? The provided download link in the documentation points to a working version (it contains shortcuts.py).

**Comment by franknoe** [comment]
@marscher , look at the link @lancsa  posted:
   http://www.emma-project.org/latest/generated/MSM_BPTI.html
There is the shortcuts module. So maybe this site hasn't been properly updated.

**Comment by franknoe** [comment]
Just to make clear: To solve issue, the dependency on the shortcuts module should be removed.

**Comment by marscher** [comment]
Yes. It would be better if the notebooks are self-contained. However it 
will work, if users get the notebooks like suggested.

**Comment by franknoe** [comment]
True, but that's not explicitly written in this notebook, so you can't 
assume visiting this site knows this. Anyway, it's our job to make 
things easily usable.

Am 26/03/16 um 16:15 schrieb Martin K. Scherer:

> Yes. It would be better if the notebooks are self-contained. However it
> will work, if users get the notebooks like suggested.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/746#issuecomment-201854929

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 26.03.2016 um 16:20 schrieb Frank Noe:

> True, but that's not explicitly written in this notebook, so you can't
> assume visiting this site knows this. Anyway, it's our job to make
> things easily usable.
> Indeed! Happy Easter.
