### ISSUE TITLE
TICA Error: No array given

### ISSUE THREAD

**Issue by stefdoerr** [markovmodel/PyEMMA#752]
I used to be able to pass to `Tica.fit_transform()` a list of `np.ndarrays`. Did something change?

``` python
    178     def estimate(self, X, **kwargs):
    179         # TODO: X is either Iterable of an array
    180         if not isinstance(X, Iterable):
    181             if isinstance(X, np.ndarray):
    182                 X = DataInMemory(X, self.chunksize)
    183                 self.data_producer = X
    184             else:
--> 185                 raise ValueError("no array given")
    186 
    187         model = None
    188         # run estimation
    189         try:
    190             model = super(StreamingTransformer, self).estimate(X, **kwargs)
    191         except NotConvergedWarning as ncw:
    192             self._logger.info(
    193                 "Presumely finished estimation. Message: %s" % ncw)
    194         # memory mode? Then map all results. Avoid recursion here, if parametrization
    195         # is triggered from get_output
    196         if self.in_memory and not self._mapping_to_mem_active:
    197             self._map_to_memory()
    198 
    199         self._estimated = True
    200 
    201         return model
    202 

ipdb> not isinstance(X, Iterable)
True
ipdb> type(X)
<class 'list'>
ipdb> type(X[0])
<class 'numpy.ndarray'>
ipdb> X[0].shape
(1200, 595)
```

**Comment by franknoe** [comment]
That is supposed to work. Is this the devel version?

@clonker/@marscher: please comment. If this is not tested, please add a 
test.

Am 31/03/16 um 15:14 schrieb Stefan:

> I used to be able to pass to |Tica.fit_transform()| a list of 
> |np.ndarrays|. Did something change?
> 
> ```
>  178      def  estimate(self,X,**kwargs):
>  179          # TODO: X is either Iterable of an array
>  180          if  not  isinstance(X, Iterable):
>  181              if  isinstance(X, np.ndarray):
>  182                  X  =  DataInMemory(X,self.chunksize)
>  183                  self.data_producer=  X
>  184              else:
> ```
> 
> -->  185                  raise  ValueError("no array given")
>      186  
>      187          model=  None
>      188          # run estimation
>      189          try:
>      190              model=  super(StreamingTransformer,self).estimate(X,**kwargs)
>      191          except  NotConvergedWarningas  ncw:
>      192              self._logger.info(
>      193                  "Presumely finished estimation. Message: %s"  %  ncw)
>      194          # memory mode? Then map all results. Avoid recursion here, if 
> parametrization
>      195          # is triggered from get_output
>      196          if  self.in_memoryand  not  self._mapping_to_mem_active:
>      197              self._map_to_memory()
>      198  
>      199          self._estimated=  True
>      200  
>      201          return  model
>      202  
> 
> ipdb>  not  isinstance(X, Iterable)
> True
> ipdb>  type(X)
> <class  'list'>
> ipdb>  type(X[0])
> <class  'numpy.ndarray'>
> ipdb>  X[0].shape
> (1200,595)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/752

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
It's the latest github version (I think) pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg

Not the conda one.

**Comment by franknoe** [comment]
So with 2.0.4 this works, right?

Am 31/03/16 um 15:20 schrieb Stefan:

> It's the latest github version (I think) 
> pyEMMA-2.1rc3+72.g53199f1.dirty-py3.5-linux-x86_64.egg
> 
> Not the conda one.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/752#issuecomment-203933567

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by stefdoerr** [comment]
Actually, sorry, it _was_ the latest a week ago or so. Maybe I should do another pull and try again.

**Comment by stefdoerr** [comment]
Yes, tested on 2.0.4 and it works

**Comment by clonker** [comment]
This is not only a problem of tica but a general problem for all StreamTransformers when estimate gets called with a list of np.ndarrays instead of a single ndarray. I will shortly create a PR with a fix

**Comment by franknoe** [comment]
thanks a lot Moritz! Please add a test case. Since this was possible in 
2.0.4, we should merge this before releasing, otherwise we would break 
people's codes.

Am 31/03/16 um 16:48 schrieb Moritz Hoffmann:

> This is not only a problem of tica but a general problem for all 
> StreamTransformers when estimate gets called with a list of 
> np.ndarrays instead of a single ndarray. I will shortly create a PR 
> with a fix
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/752#issuecomment-203971919

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
@stefdoerr please check if your problem is solved by #735

**Comment by marscher** [comment]
It was fixed by #753

**Comment by marscher** [comment]
Since there has been no response for 9 days, I assume it has been fixed.

**Comment by stefdoerr** [comment]
I guess. I don't have time to check it these days, sorry.

**Comment by marscher** [comment]
No problem. Please feel free to re open, if something does not work yet.
