### ISSUE TITLE
Conda update from 2.0.1 release to 2.0.4 breaks pyemma import (OSX)

### ISSUE THREAD

**Issue by psolsson** [markovmodel/PyEMMA#754]
```
import pyemma
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version a but this version of numpy is 9

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-e542aa3daeae> in <module>()
----> 1 import pyemma

/Users/solsson/miniconda/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-macosx-10.5-x86_64.egg/pyemma/__init__.py in <module>()
     25 from .util import config
     26 
---> 27 from . import coordinates
     28 from . import msm
     29 from . import util

/Users/solsson/miniconda/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/__init__.py in <module>()
    105 
    106 """
--> 107 from .api import *

/Users/solsson/miniconda/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/api.py in <module>()
     25 from pyemma.util import types as _types
     26 
---> 27 from pyemma.coordinates.pipelines import Discretizer as _Discretizer
     28 from pyemma.coordinates.pipelines import Pipeline as _Pipeline
     29 # io

/Users/solsson/miniconda/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/pipelines.py in <module>()
     18 
     19 from __future__ import absolute_import
---> 20 from pyemma.coordinates.clustering.interface import AbstractClustering
     21 from pyemma.coordinates.transform.transformer import Transformer
     22 from pyemma.coordinates.data.feature_reader import FeatureReader

/Users/solsson/miniconda/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/clustering/__init__.py in <module>()
     34 """
     35 
---> 36 from .assign import AssignCenters
     37 from .kmeans import KmeansClustering
     38 from .kmeans import MiniBatchKmeansClustering

/Users/solsson/miniconda/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/clustering/assign.py in <module>()
     26 @author: marscher
     27 '''
---> 28 from pyemma.coordinates.clustering.interface import AbstractClustering
     29 import numpy as np
     30 

/Users/solsson/miniconda/lib/python2.7/site-packages/pyEMMA-2.0.4-py2.7-macosx-10.5-x86_64.egg/pyemma/coordinates/clustering/interface.py in <module>()
     31 import os
     32 
---> 33 from pyemma.coordinates.clustering import regspatial
     34 from six.moves import range
     35 from six.moves import zip

ImportError: numpy.core.multiarray failed to import

import numpy as np
print np.__version__
'1.9.3'
```

**Comment by psolsson** [comment]
Also just realized that the conda package: 2.0.1-py27_2 gives me the same error, while 2.0.1-py27_0 works fine.

**Comment by franknoe** [comment]
I haven't had that problem. Can you try upgrading numpy?

Am 01/04/16 um 11:06 schrieb Simon Olsson:

> Also just realized that the conda package: 2.0.1-py27_2 gives me the 
> same error, while 2.0.1-py27_0 works fine.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/754#issuecomment-204321263

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by psolsson** [comment]
That solves it! Thanks.

```
>>> import pyemma
>>> import numpy as np
>>> np.__version__
'1.10.4'
```

Maybe adding numpy 1.10.4 as an explicit dependency in conda would be an idea?

**Comment by franknoe** [comment]
Sure. I am still wondering why (1) your numpy was not updated 
automatically by conda (is some other package requiring numpy<1.10?) and 
(2) If we do require 1.10 functionality, shouldn't we ask for numpy>1.10 
in the conda recipe?
@marscher - any ideas?

Am 01/04/16 um 15:53 schrieb Simon Olsson:

> That solves it! Thanks.
> 
> |>>> import pyemma >>> import numpy as np >>> np.**version** '1.10.4' |
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/754#issuecomment-204404536

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
prior 2.1 we didn't use the "numpy x.x" pattern in conda recipe which means that we haven't pinned the numpy version. This is now fixed. Maybe we should add this to the FAQ.
