### ISSUE TITLE
Making figures with pyemma without an X server ?

### ISSUE THREAD

**Issue by jmichel80** [markovmodel/PyEMMA#755]
Hi, 

I would like to run pyemma 2.0.4 (conda install) remotely on a workstation with no X server. The instructions below

(...)
import pyemma.msm as msm
import pyemma.plots as mplt
(...)
dtrajsY = cluster.dtrajs
itsY = msm.its(dtrajsY, lags=lags, errors='bayes', nits=20)
mplt.plot_implied_timescales(itsY, outfile="its.png")

generate the following error:
": cannot connect to X server localhost:10.0"

The issue is the matplotlib backend. A solution has been proposed here:

http://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined

However it isn't clear to me how the above mentioned solution can be implemented in the current API. 

Please let me know if you have suggestions ! 

Best wishes, 

Julien

**Comment by franknoe** [comment]
Hi Julien. I have written the plotting tools with interactive usage in 
mind, so honestly I don't think it currently works without X-server. The 
current workaround would be to save this data and plot it on your 
machine. But this is an easy change, and I'm happy to do it, so let's 
leave the issue open.

Am 01/04/16 um 12:53 schrieb jmichel80:

> Hi,
> 
> I would like to run pyemma 2.0.4 (conda install) remotely on a 
> workstation with no X server. The instructions below
> 
> (...)
> import pyemma.msm as msm
> import pyemma.plots as mplt
> (...)
> dtrajsY = cluster.dtrajs
> itsY = msm.its(dtrajsY, lags=lags, errors='bayes', nits=20)
> mplt.plot_implied_timescales(itsY, outfile="its.png")
> 
> generate the following error:
> ": cannot connect to X server localhost:10.0"
> 
> The issue is the matplotlib backend. A solution has been proposed here:
> 
> http://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined
> 
> However it isn't clear to me how the above mentioned solution can be 
> implemented in the current API.
> 
> Please let me know if you have suggestions !
> 
> Best wishes,
> 
> Julien
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/755

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Just to be more clear: You can of course run remotely without X-server, just calls to pyemma.plots won't work, as they currently assume that plotting is possible.

**Comment by marscher** [comment]
@jmichel80 You can choose the "Agg" backend of matplotlib to create figures in a headless environment. You have several options to set this. One option is to set it directly in your script (which might be annoying, since you need to adapt every script):

``` python
import matplotlib
matplotlib.use('Agg')
```

Or you can set this permanently on the headless machine via creating a matplotlib config file in your home directory:

``` bash
mkdir $HOME/.matplotlib
echo "backend: agg" > $HOME/.matplotlib/matplotlibrc
```

I think if this file lies next to where you've just started the Python process it is also respected.
Hope this is useful.

**Comment by franknoe** [comment]
Maybe we could set the Agg renderer in out plotting library if figures 
are not requested to be shown? (and add a flag such as show=True).

Am 07/04/16 um 16:04 schrieb Martin K. Scherer:

> @jmichel80 https://github.com/jmichel80 You can choose the "Agg" 
> backend of matplotlib to create figures in a headless environment. You 
> have several options to set this. One option is to set it directly in 
> your script (which might be annoying, since you need to adapt every 
> script):
> 
> import  matplotlib
> matplotlib.use('Agg')
> 
> Or you can set this permanently on the headless machine via creating a 
> matplotlib config file in your home directory:
> 
> mkdir$HOME/.matplotlib
> echo  "backend: agg"  >  $HOME/.matplotlib/matplotlibrc
> 
> I think if this file lies next to where you've just started the Python 
> process it is also respected.
> Hope this is useful.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/755#issuecomment-206922389

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 07.04.2016 um 16:09 schrieb Frank Noe:

> Maybe we could set the Agg renderer in out plotting library if figures
> are not requested to be shown? (and add a flag such as show=True).
> No, because the backend can only be set once. We can not just switch it 
> upon a flag the user gives to our function.
