### ISSUE TITLE
Make util.statistics.confidence_interval and util.statistics._confidence_interval_1d robust

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#756]
The confidence interval functions crash in pathological cases (for some inf or nan inputs). This code should be tested and I suggest to make the confidence intervals behave similarly as the np.mean function. 

``` python
>>> import numpy as np
>>> np.mean([0.0, 1.0, np.inf])
inf
>>> np.mean([0.0, 1.0, np.nan])
nan
>>> np.mean([0.0, 1.0, np.inf, -np.inf])
nan
```

This will lead to infs and nans for confidence intervals on pathological data, but will not generate an exception. When plotting data this seems like the most desirable behavior, because if single datapoints have such problems, they will simply not be plotted, but the program doesn't raise an exception. We can log a warning if such a case occurs.

**Comment by marscher** [comment]
There is a "Bayesian confidence intervals for the mean, var, and std." in SciPy, maybe we should use that:
https://github.com/scipy/scipy/blob/v0.17.0/scipy/stats/morestats.py#L43-L139

**Comment by franknoe** [comment]
that's interesting, I will have a look at it.

Am 17/05/16 um 15:54 schrieb Martin K. Scherer:

> There is a "Bayesian confidence intervals for the mean, var, and std." 
> in SciPy, maybe we should use that:
> https://github.com/scipy/scipy/blob/v0.17.0/scipy/stats/morestats.py#L43-L139
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/756#issuecomment-219724609

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I checked that - that's not doing what we want. This function computes 
the standard error of moments like mean and std dev using a Bayesian 
model. Check e.g.:

```
 https://en.wikipedia.org/wiki/Standard_error
```

What we want is to compute the confidence intervals, i.e. what is the 
interval within which 95% of the data lies:

```
 https://en.wikipedia.org/wiki/Confidence_interval
```

Am 17/05/16 um 15:54 schrieb Martin K. Scherer:

> There is a "Bayesian confidence intervals for the mean, var, and std." 
> in SciPy, maybe we should use that:
> https://github.com/scipy/scipy/blob/v0.17.0/scipy/stats/morestats.py#L43-L139
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/756#issuecomment-219724609

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
