### ISSUE TITLE
protein-ligand binding tutorial giving wrong dimension

### ISSUE THREAD

**Issue by jmondal1** [markovmodel/PyEMMA#758]
Hi
  I was trying to walk through the protein-ligand binding tutorial present in the pyemma website ( http://www.emma-project.org/latest/generated/trypsin_benzamidine_hmm.html)
 pyemma 2.0.2 version using Ipython_4.1.2 

However, At the stage before doing TICA , when checking the number of dimensions, I am always finding 233_233 in stead of 233 as reported by the tutorial . As a result the tica part is also getting stuck.
I tried several times. But, issuing following section, as shown in tutorial,is always resulting in a dimension of 233_233 in stead of 233.
Is there any issue with version ? My program is running on linux environment.

  feat = coor.featurizer(topfile)
n_res = 223 # number of residues
ben_ind = 225 # benzamidine index (with residues starting at 1)
ind_arr = np.zeros((n_res,2))
for i in range(n_res):
    ind_arr[i][0] = ben_ind-1
    ind_arr[i][1] = i
feat.add_residue_mindist(residue_pairs=ind_arr, scheme='closest-heavy', threshold=0.5)
inp = coor.source(traj_list, feat)
X = inp.get_output()

**Comment by franknoe** [comment]
How have you indented this code. Is `feat.add_residue_mindist` 
perhaps inside the loop?

Am 05/04/16 um 18:52 schrieb jmondal1:

> Hi
> I was trying to walk through the protein-ligand binding tutorial 
> present in the pyemma website ( 
> http://www.emma-project.org/latest/generated/trypsin_benzamidine_hmm.html)
> pyemma 2.0.2 version using Ipython_4.1.2
> 
> However, At the stage before doing TICA , when checking the number of 
> dimensions, I am always finding 233/233 in stead of 233 as reported by 
> the tutorial . As a result the tica part is also getting stuck.
> I tried several times. But, issuing following section, as shown in 
> tutorial,is always resulting in a dimension of 233/233 in stead of 233.
> Is there any issue with version ? My program is running on linux 
> environment.
> 
> feat = coor.featurizer(topfile)
> n_res = 223 # number of residues
> ben_ind = 225 # benzamidine index (with residues starting at 1)
> ind_arr = np.zeros((n_res,2))
> for i in range(n_res):
> ind_arr[i][0] = ben_ind-1
> ind_arr[i][1] = i
> feat.add_residue_mindist(residue_pairs=ind_arr, 
> scheme='closest-heavy', threshold=0.5)
> inp = coor.source(traj_list, feat)
> X = inp.get_output()
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/758

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jmondal1** [comment]
Hi
  Is feat.add_residue_mindist supposed to be outside the loop ?  I was mainly using the Ipython software in the interactive manner where I was mainly copying the lines from the tutorial website and pasting it in ipython. So, might have the feat.add_residue_mindist been part of the same loop?

Should I put the entire program inside a single file and run it as a python program ?  

Jagannath

**Comment by franknoe** [comment]
You have to copy the right indentation then:

```

feat  =  coor.featurizer(topfile)
n_res  =  223  # number of residues
ben_ind  =  225  # benzamidine index (with residues starting at 1)
ind_arr  =  np.zeros((n_res,2))
for  i  in  range(n_res):
     ind_arr[i][0]  =  ben_ind-1
     ind_arr[i][1]  =  i
feat.add_residue_mindist(residue_pairs=ind_arr,  scheme='closest-heavy',  threshold=0.5)

```

If add_residue_mindist is in the loop, you will repeat adding the same 
features many times. In a more recent PyEMMA version, repetitive adding 
of the same features will be ineffective, so you should upgrade.

You can download the full notebooks and execute them without having to 
copy line-by-line here:
https://github.com/markovmodel/PyEMMA_IPython/archive/devel.zip

Otherwise I think your question is related to basic usage of 
Python/IPython. Sorry, but this is not a PyEMMA issue, so I'm closing this.

Am 05/04/16 um 19:32 schrieb jmondal1:

> Hi
> Is feat.add_residue_mindist supposed to be outside the loop ? I was 
> mainly using the Ipython software in the interactive manner where I 
> was mainly copying the lines from the tutorial website and pasting it 
> in ipython. So, might have the feat.add_residue_mindist been part of 
> the same loop?
> 
> Should I put the entire program inside a single file and run it as a 
> python program ?
> 
> Jagannath
> 
> On Apr 5, 2016, at 10:56 PM, Frank Noe notifications@github.com wrote:
> 
> > How have you indented this code. Is `feat.add_residue_mindist`
> > perhaps inside the loop?
> > 
> > Am 05/04/16 um 18:52 schrieb jmondal1:
> > 
> > > Hi
> > > I was trying to walk through the protein-ligand binding tutorial
> > > present in the pyemma website (
> > > 
> > > http://www.emma-project.org/latest/generated/trypsin_benzamidine_hmm.html)
> > > pyemma 2.0.2 version using Ipython_4.1.2
> > > 
> > > However, At the stage before doing TICA , when checking the number of
> > > dimensions, I am always finding 233/233 in stead of 233 as 
> > > reported by
> > > the tutorial . As a result the tica part is also getting stuck.
> > > I tried several times. But, issuing following section, as shown in
> > > tutorial,is always resulting in a dimension of 233/233 in stead of 
> > > 233.
> > > Is there any issue with version ? My program is running on linux
> > > environment.
> > > 
> > > feat = coor.featurizer(topfile)
> > > n_res = 223 # number of residues
> > > ben_ind = 225 # benzamidine index (with residues starting at 1)
> > > ind_arr = np.zeros((n_res,2))
> > > for i in range(n_res):
> > > ind_arr[i][0] = ben_ind-1
> > > ind_arr[i][1] = i
> > > feat.add_residue_mindist(residue_pairs=ind_arr,
> > > scheme='closest-heavy', threshold=0.5)
> > > inp = coor.source(traj_list, feat)
> > > X = inp.get_output()
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/markovmodel/PyEMMA/issues/758
> > 
> > ## 
> > 
> > ---
> > 
> > Prof. Dr. Frank Noe
> > Head of Computational Molecular Biology group
> > Freie Universitaet Berlin
> > 
> > Phone: (+49) (0)30 838 75354
> > Web: research.franknoe.de
> > 
> > ## Mail: Arnimallee 6, 14195 Berlin, Germany
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/758#issuecomment-205909813

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
