### ISSUE TITLE
Discretizer's dtraj property should return list of ndarrys of integer, not float

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#76]
This is annoying when you try to use the disctraj to index into another array. Then numpy gives a warning.

**Comment by marscher** [comment]
Am 20.02.2015 um 20:58 schrieb fabian-paul:
> This is annoying when you try to use the disctraj to index into another
> array. Then numpy gives a warning.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/76>.
>
dtrajs are coming directly from a cluster algo, which did you use?

**Comment by marscher** [comment]
done
