### ISSUE TITLE
Dimension selection in transformers / estimators

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#761]
Transfomers / Estimators working with multidimensional input data should get an option to work with only selected dimensions of the input. Suggested names were `usecols=None` as in `numpy.loadtxt`. As it is just our convention to use columns for the dimensions, I slightly prefer something like `usedims=None` which expresses what the indexes are referring to, but perhaps there are other ideas.

**Comment by franknoe** [comment]
I'm actually going to split this issue...

**Comment by marscher** [comment]
During iterator creation one can pass the "cols" parameter to selection dimensions.
