### ISSUE TITLE
problem with HMM in a protein-ligand system

### ISSUE THREAD

**Issue by jmondal1** [markovmodel/PyEMMA#765]
Hi
  I am using pyemma_2.0.2 on a protein-ligand system to
a) develop a network of important coarse-grained states using  Bayesian Hidden Markov models and 
b) then obtain the flux using transition path theory.

The major problem is: somehow the bound and unbound states are coming out to be same state, as a result the free energy change is zero and onrate is infinite.

 I have  a set of quite a few long trajectories which shows successful binding and so I thought of using them for MSM through pyemma.

I was mainly following the tutorial on protein-ligand system present in the pyemma website for my own system as well. Here is my experiences so far: I have attached  a zipped files with the python code and pictures. 

1) First I plotted the free energy along first two independent components which showed different basins.

2) Then the clustering of the trajectories ( using contacts) went fine as it could show a separate cluster with large number of states with no contacts ( unbound one) apart from a bunch of other clusters. 

3) Then I tried to analyze the implied time scale with 5 states with lagtimes of 1,2,3,4,5 ns. From the plot it seemed 2 ns might be a good lag time .
4) However, the binding free energy contribution from bound and unbound state is coming to be zero ( excluding the standard molar correction term)
5) Now If I try BHMM using any models of ITS , *_both the unbound and bound states are coming to be same. *_
6) then the both network and flux (from TPT) is not working.

Any suggestions after looking at my plots and python scripyts will be useful. 

Thanks
Jagannath
[figs_skip_first_1ms.zip](https://github.com/markovmodel/PyEMMA/files/211401/figs_skip_first_1ms.zip)

**Comment by franknoe** [comment]
The HMM Code has changed quite a lot in the recent versions, in 
particular there have been improvements in 2.1. Please upgrade and try 
again. I am closing this issue for now, feel free to open a new one if 
you are still having problems with 2.1.

Am 09/04/16 um 19:53 schrieb jmondal1:

> Hi
> I am using pyemma_2.0.2 on a protein-ligand system to
> a) develop a network of important coarse-grained states using Bayesian 
> Hidden Markov models and
> b) then obtain the flux using transition path theory.
> 
> The major problem is: somehow the bound and unbound states are coming 
> out to be same state, as a result the free energy change is zero and 
> onrate is infinite.
> 
> I have a set of quite a few long trajectories which shows successful 
> binding and so I thought of using them for MSM through pyemma.
> 
> I was mainly following the tutorial on protein-ligand system present 
> in the pyemma website for my own system as well. Here is my 
> experiences so far: I have attached a zipped files with the python 
> code and pictures.
> 
> 1) First I plotted the free energy along first two independent 
> components which showed different basins.
> 
> 2) Then the clustering of the trajectories ( using contacts) went fine 
> as it could show a separate cluster with large number of states with 
> no contacts ( unbound one) apart from a bunch of other clusters.
> 
> 3) Then I tried to analyze the implied time scale with 5 states with 
> lagtimes of 1,2,3,4,5 ns. From the plot it seemed 2 ns might be a good 
> lag time .
> 4) However, the binding free energy contribution from bound and 
> unbound state is coming to be zero ( excluding the standard molar 
> correction term)
> 5) Now If I try BHMM using any models of ITS , */both the unbound and 
> bound states are coming to be same. */
> 6) then the both network and flux (from TPT) is not working.
> 
> Any suggestions after looking at my plots and python scripyts will be 
> useful.
> 
> Thanks
> Jagannath
> figs_skip_first_1ms.zip 
> https://github.com/markovmodel/PyEMMA/files/211401/figs_skip_first_1ms.zip
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/765

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
