### ISSUE TITLE
kmeans issue

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#767]
Calling k-means clustering to a large in-memory array (list of ndarrays) results in this error. The immediate error is that the attribute `self._oom_strategy` doesn't exist, but I think it shouldn't even go into this code branch, because the data are already in memory and don't need to be loaded.

``` python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-0ef322ffb797> in <module>()
      1 # cluster the full state space
----> 2 kmeans = coor.cluster_kmeans(data=X, k=2000)

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/api.pyc in cluster_kmeans(data, k, max_iter, tolerance, stride, metric, init_strategy, fixed_seed)
   1281     res = KmeansClustering(n_clusters=k, max_iter=max_iter, metric=metric, tolerance=tolerance,
   1282                             init_strategy=init_strategy, fixed_seed=fixed_seed)
-> 1283     return _param_stage(data, res, stride=stride)
   1284 
   1285 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/api.pyc in _param_stage(previous_stage, this_stage, stride)
    813     this_stage.data_producer = input_stage
    814     this_stage.chunksize = input_stage.chunksize
--> 815     this_stage.estimate(X=input_stage, stride=stride)
    816     return this_stage
    817 

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/transform/transformer.pyc in estimate(self, X, **kwargs)
    187         # run estimation
    188         try:
--> 189             super(StreamingTransformer, self).estimate(X, **kwargs)
    190         except NotConvergedWarning as ncw:
    191             self._logger.info(

/Users/noe/data/software_projects/pyemma/pyemma/_base/estimator.pyc in estimate(self, X, **params)
    341         if params:
    342             self.set_params(**params)
--> 343         self._model = self._estimate(X)
    344         self._estimated = True
    345         return self

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/kmeans.pyc in _estimate(self, iterable, **kw)
    133 
    134     def _estimate(self, iterable, **kw):
--> 135         self._init_estimate()
    136 
    137         with iterable.iterator(return_trajindex=True, stride=self.stride) as iter:

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/kmeans.pyc in _init_estimate(self)
    216                                     description="initialize kmeans++ centers", stage=0)
    217         self._progress_register(self.max_iter, description="kmeans iterations", stage=1)
--> 218         self._init_in_memory_chunks(total_length)
    219         if self.init_strategy == 'uniform':
    220             # gives random samples from each trajectory such that the cluster centers are distributed percentage-wise

/Users/noe/data/software_projects/pyemma/pyemma/coordinates/clustering/kmeans.pyc in _init_in_memory_chunks(self, size)
    106                                               order='C', dtype=np.float32)
    107         else:
--> 108             if self._oom_strategy == 'raise':
    109                 self._logger.warning('K-means failed to load all the data (%s required, %s available) into memory. '
    110                                   'Consider using a larger stride or set the oom_strategy to \'memmap\' which works '

AttributeError: 'KmeansClustering' object has no attribute '_oom_strategy'
```

**Comment by marscher** [comment]
This code branch has not been properly tested (since this test-case would require to eat up all system memory to provoke a MemoryError to be thrown.

The kmeans-c-extension is not capable of chunk-processing, so it copies all the data, which is a sub-optimal solution, but fast in case that the data fits into memory. Probably we should reconcile this implementation in favor of a chunk based one (eg. pass an Iterable Python instance to the extension which can drag chunks in the kmeans loops).

**Comment by franknoe** [comment]
But why is a copy made when the data already is in memory? isn't it 
possible to just get a reference in this case.

Am 11/04/16 um 11:45 schrieb Martin K. Scherer:

> This code branch has not been properly tested (since this test-case 
> would require to eat up all system memory to provoke a MemoryError to 
> be thrown.
> 
> The kmeans-c-extension is not capable of chunk-processing, so it 
> copies all the data, which is a sub-optimal solution, but fast in case 
> that the data fits into memory. Probably we should reconcile this 
> implementation in favor of a chunk based one (eg. pass an Iterable 
> Python instance to the extension which can drag chunks in the kmeans 
> loops).
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/767#issuecomment-208259240

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Closed? The issue that a copy is made although no copy is needed is not addressed. Please comment.

**Comment by marscher** [comment]
Auto-closed by a merged commit. The github workflow does not really suite Email only workflow - sorry.

Of course there is a follow-up issue about unnecessary copies made in kmeans.

**Comment by franknoe** [comment]
I see.
