### ISSUE TITLE
Saving data to disk (clustering, tica)

### ISSUE THREAD

**Issue by giopina** [markovmodel/PyEMMA#772]
Hello,
## I was wondering what is the best way to store processed data (i.e. cluster centers and assignment) to disk. I'm using cPickle to save msm and hmm objects but it seems to have problems with the clustering output:

TypeError                                 Traceback (most recent call last)
<ipython-input-49-ded47764466e> in <module>()
----> 1 pickle.dump(cl_prova,open('prova.cl','w'))

/u/sbp/giopina/software/miniconda/lib/python2.7/copy_reg.pyc in _reduce_ex(self, proto)
     68     else:
     69         if base is self.__class__:
---> 70             raise TypeError, "can't pickle %s objects" % base.**name**
     71         state = base(self)
     72     args = (self.**class**, base, state)

TypeError: can't pickle instancemethod objects

I'm now saving centers, indexes and discrete trajectories as simple arrays, but it doesn't look optimal.
I have the same problem with tica.
Is there some way to pickle this objects? Or can I reconstruct a clustering object starting from arrays containing centers, indexes, discrete trajectories, etc?

Thanks,
Giovanni

**Comment by marscher** [comment]
You could try another pickling library which is capable of serializing instancemethods.

**Comment by franknoe** [comment]
We are planning to have an efficient support of that. Right now, why I mostly do is to create npzfiles and store the relevant attributes with corresponding keynames.
Direct pickling runs into the problems of the sort you have described. I think Guillermo also has constructed a pickle workaround.

**Comment by marscher** [comment]
I have a feature branch for this since a couple of weeks, but it is not yet mature.

**Comment by franknoe** [comment]
ok, we can discuss it next week.

Am 17/05/16 um 21:19 schrieb Martin K. Scherer:

> I have a feature branch for this since a couple of weeks, but it is 
> not yet mature.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/772#issuecomment-219824751

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
fixed by #867
