### ISSUE TITLE
Implied timescale plots fails with a single timescale 2.1

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#781]
`plots.plot_implied_timescales` seems to have a problem in that it omits one timescale. As a consequence, for a 2-state trajectory that only has a single timescale, nothing will be printed. This problem is new - probably since 2.1. 

As an example, this will plot nothing:

``` python
d = [0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1]
its = msm.timescales_msm(d, lags = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
plots.plot_implied_timescales(its)
```

Whereas this will plot a single timescale:

``` python
d = [0, 1, 2, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 1, 2, 1, 2, 2, 1]
its = msm.timescales_msm(d, lags = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
plots.plot_implied_timescales(its)
```

**Comment by gph82** [comment]
Hi, haven't  looked yet, but is it possible this is related to this https://github.com/markovmodel/PyEMMA/pull/728 ?

**Comment by gph82** [comment]
It does, working on a patch now
