### ISSUE TITLE
IPython notebooks are not updated / integration test problems in 2.1

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#782]
The IPython notebooks on pyemma.org do not seem to have been updated since 2.0.2. Moreover, at least since the 2.1 releases, the outputs of these notebooks seem to not have been checked. For example the notebook

http://www.emma-project.org/latest/generated/model_selection_validation.html

suffers from issue #781 which is a functional failure, although no exception is raised. It is essential to rerun the notebooks with every new release and update the output on pyemma.org. Additionally we need to check visually the notebook outputs for sanity in those cases that cannot easily be checked automatically.

I hope we still run the IPython notebook tests on Travis to catch exceptions?

**Comment by marscher** [comment]
The notebooks run too long on Travis, eg. they hit the maximum wall time of 40 minutes. I've tested the notebooks for 2.1 locally and there was no problem.

**Comment by franknoe** [comment]
1. This is a change in policy that we haven't discussed. I think 
   automatic testing of the notebooks is important, we need to find some 
   way to do this. They don't need to be run for every PR, but at least we 
   need to make sure that the tests are run before the release.
2. Clearly there _is_ a problem, at least due to issue #781. This issue 
   doesn't lead to an exception, but it is obvious when looking at the 
   notebook output. One reason for overlooking this is that the IPython 
   notebook outputs on pyemma.org aren't updated. If this is done for devel 
   before the release it is easy to check everything for consistency.

Am 25/04/16 um 13:24 schrieb Martin K. Scherer:

> The notebooks run too long on Travis, eg. they hit the maximum wall 
> time of 40 minutes. I've tested the notebooks for 2.1 locally and 
> there was no problem.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/782#issuecomment-214272621

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 25.04.2016 um 13:32 schrieb Frank Noe:

> 1. This is a change in policy that we haven't discussed. I think
>    automatic testing of the notebooks is important, we need to find some
>    way to do this. They don't need to be run for every PR, but at least we
>    need to make sure that the tests are run before the release.
>    There is no change in policy. The notebooks are tested:

https://travis-ci.org/markovmodel/PyEMMA_IPython/builds/119287802

However these tests are only run, only if there is a change on the PyEMMA_IPython repository.
I've changed that now via nightly.es, so there will be a nightly test on basis of PyEMMA dev.

> 1. Clearly there _is_ a problem, at least due to issue #781. This issue
>    doesn't lead to an exception, but it is obvious when looking at the
>    notebook output. One reason for overlooking this is that the IPython
>    notebook outputs on pyemma.org aren't updated. If this is done for devel
>    before the release it is easy to check everything for consistency.
>    The output of the notebooks is stored in the notebook itself, so we need to re-run them locally
>    before a release to get "updated" contents in the documentation.

So we should add this step to the release procedure.

**Comment by franknoe** [comment]
Am 25/04/16 um 13:37 schrieb Martin K. Scherer:

> Am 25.04.2016 um 13:32 schrieb Frank Noe:
> 
> > 1. This is a change in policy that we haven't discussed. I think
> >    automatic testing of the notebooks is important, we need to find some
> >    way to do this. They don't need to be run for every PR, but at least we
> >    need to make sure that the tests are run before the release.
> >    There is no change in policy. The notebooks are tested:
> 
> https://travis-ci.org/markovmodel/PyEMMA_IPython/builds/119287802
> 
> However these tests are only run, only if there is a change on the 
> PyEMMA_IPython repository.
> That is a change of policy compared to previously (I guess during 2.0) 
> when we triggered
> the IPython tests in every PR. I wasn't aware that we are running into 
> the timeout problem.
> I've changed that now via nightly.es, so there will be a nightly test 
> on basis of PyEMMA dev.
> Thanks, nightly is good.
> 
> > 1. Clearly there _is_ a problem, at least due to issue #781. This issue
> >    doesn't lead to an exception, but it is obvious when looking at the
> >    notebook output. One reason for overlooking this is that the IPython
> >    notebook outputs on pyemma.org aren't updated. If this is done for devel
> >    before the release it is easy to check everything for consistency.
> >    The output of the notebooks is stored in the notebook itself, so we 
> >    need to re-run them locally
> >    before a release to get "updated" contents in the documentation.
> 
> So we should add this step to the release procedure.
> It would be good to have an up-to-date output for the devel version too, 
> in order to see problems before we release. Can we do that 
> automatically, e.g. nightly?

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 25.04.2016 um 13:48 schrieb Frank Noe:

> Am 25/04/16 um 13:37 schrieb Martin K. Scherer:
> 
> > Am 25.04.2016 um 13:32 schrieb Frank Noe:
> > 
> > > 1. This is a change in policy that we haven't discussed. I think
> > >    automatic testing of the notebooks is important, we need to find some
> > >    way to do this. They don't need to be run for every PR, but at least we
> > >    need to make sure that the tests are run before the release.
> > >    There is no change in policy. The notebooks are tested:
> > 
> > https://travis-ci.org/markovmodel/PyEMMA_IPython/builds/119287802
> > 
> > However these tests are only run, only if there is a change on the
> > PyEMMA_IPython repository.
> > That is a change of policy compared to previously (I guess during 2.0)
> > when we triggered
> > the IPython tests in every PR. I wasn't aware that we are running into
> > the timeout problem.
> > I've changed that now via nightly.es, so there will be a nightly test
> > on basis of PyEMMA dev.
> > Thanks, nightly is good.
> > 
> > > 1. Clearly there _is_ a problem, at least due to issue #781. This issue
> > >    doesn't lead to an exception, but it is obvious when looking at the
> > >    notebook output. One reason for overlooking this is that the IPython
> > >    notebook outputs on pyemma.org aren't updated. If this is done for devel
> > >    before the release it is easy to check everything for consistency.
> > >    The output of the notebooks is stored in the notebook itself, so we
> > >    need to re-run them locally
> > >    before a release to get "updated" contents in the documentation.
> > 
> > So we should add this step to the release procedure.
> > It would be good to have an up-to-date output for the devel version too,
> > in order to see problems before we release. Can we do that
> > automatically, e.g. nightly?
> > The evaluation can be done automatically via nighly, but we have to define or
> > store the "wanted" contents beforehand in the repository, so the testsuite can
> > compare the output with the stored content.

**Comment by marscher** [comment]
I've now implemented nightly tests of the notebooks against pyemma-dev and automatic doc updates upon commits to pyemma repo.
The results are always visible in Travis and on http://www.emma-project.org/vdevel/ipython.html

**Comment by franknoe** [comment]
Thanks!

Am 03/05/16 um 17:21 schrieb Martin K. Scherer:

> Closed #782 https://github.com/markovmodel/PyEMMA/issues/782.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/782#event-648990958

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
