### ISSUE TITLE
most updated PyEMMA (devel) now requires thermotools

### ISSUE THREAD

**Issue by j3mdamas** [markovmodel/PyEMMA#787]
Hi,

I wanted to test your fix to a problem we were having with PyEMMA on HTMD (#764), but it seems like the devel branch now requires `thermotools` (in the new TRAM_estimator.py at least), while the previous release we were using (2.1.1) did not. Can you confirm this to me? Otherwise, I may be doing some mistake importing the module.

Thanks,
João

**Comment by marscher** [comment]
Hi,

you're right, devel now has this dependency.
The setup.py and conda packages reflects this new requirement.

**Comment by j3mdamas** [comment]
I updated the conda `thermotools` version and it's now working. Thanks Martin!

**Comment by marscher** [comment]
You can also use the new conda package pyemma-dev

**Comment by j3mdamas** [comment]
yeah, I saw that on a conda search. Thanks!

**Comment by j3mdamas** [comment]
Thanks a lot Martin, the pyemma-dev is really useful and easy!

**Comment by marscher** [comment]
Am 29.04.2016 um 15:32 schrieb João M. Damas:

> Thanks a lot Martin, the pyemma-dev is really useful and easy!
> You're welcome. Just note that these builds are performed by travis and not the Omnia build pipeline (so they might not run everywhere).

**Comment by j3mdamas** [comment]
I see. Well, it ran on my machine and I could test that the issue we had is gone with the current dev. That's enough.
