### ISSUE TITLE
GLIBC problem

### ISSUE THREAD

**Issue by rafwiewiora** [markovmodel/PyEMMA#792]
So this is on our cluster (all ok on my Macbook), `pyemma-dev` throws this on clustering:

```

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-857ab256efd2> in <module>()
      1 # trying a larger number of states
----> 2 uniform_time_clustering_500 = pyemma.coordinates.cluster_uniform_time(Y,k=500)

/cbio/jclab/home/rafal.wiewiora/anaconda/lib/python2.7/site-packages/pyEMMA-2.1.1+94.g0a4d0d3-py2.7-linux-x86_64.egg/pyemma/coordinates/api.pyc in cluster_uniform_time(data, k, stride, metric, n_jobs, chunk_size)
   1358 
   1359     """
-> 1360     from pyemma.coordinates.clustering.uniform_time import UniformTimeClustering
   1361     res = UniformTimeClustering(k, metric=metric, n_jobs=n_jobs)
   1362     return _param_stage(data, res, stride=stride, chunk_size=chunk_size)

/cbio/jclab/home/rafal.wiewiora/anaconda/lib/python2.7/site-packages/pyEMMA-2.1.1+94.g0a4d0d3-py2.7-linux-x86_64.egg/pyemma/coordinates/clustering/__init__.py in <module>()
     34 """
     35 
---> 36 from .assign import AssignCenters
     37 from .kmeans import KmeansClustering
     38 from .kmeans import MiniBatchKmeansClustering

/cbio/jclab/home/rafal.wiewiora/anaconda/lib/python2.7/site-packages/pyEMMA-2.1.1+94.g0a4d0d3-py2.7-linux-x86_64.egg/pyemma/coordinates/clustering/assign.py in <module>()
     27 import six
     28 
---> 29 from pyemma.coordinates.clustering.interface import AbstractClustering
     30 import numpy as np
     31 

/cbio/jclab/home/rafal.wiewiora/anaconda/lib/python2.7/site-packages/pyEMMA-2.1.1+94.g0a4d0d3-py2.7-linux-x86_64.egg/pyemma/coordinates/clustering/interface.py in <module>()
     29 from pyemma._base.model import Model
     30 from pyemma._ext.sklearn.base import ClusterMixin
---> 31 from pyemma.coordinates.clustering import regspatial
     32 from pyemma.coordinates.transform.transformer import StreamingTransformer
     33 from pyemma.util.discrete_trajectories import index_states, sample_indexes_by_state

ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /cbio/jclab/home/rafal.wiewiora/anaconda/lib/python2.7/site-packages/pyEMMA-2.1.1+94.g0a4d0d3-py2.7-linux-x86_64.egg/pyemma/coordinates/clustering/regspatial.so)
```

while if I install from the repo - all ok. Tagging @jchodera

**Comment by jchodera** [comment]
`pyemma-dev` is built by travis using the docker infrastructure, which currently uses ubuntu 14.04.  Because of this, it's only usable on systems with a more recent GLIBC. Our CentOS 6.5 cluster doesn't have a recent GLIBC.

Solutions:
- You can `conda remove --yes pyemma-dev` and install it from the github repo source with `python setup.py install`
- You can wait for them to cut an official release and update the `pyemma` recipe, which will be built by a docker framework on a maximally compatible `holy-build-box` derivative
- The `pyemma` folks could change [this line](https://github.com/markovmodel/PyEMMA/blob/devel/.travis.yml#L6) to `sudo: true` to force travis tests/dev builds on the older travis precise penguin architecture

**Comment by franknoe** [comment]
The third solution sounds simple enough, but I'm pinging @marscher and 
@clonker who are likely to have a more educated opinion on this than I do.

Am 01/05/16 um 18:21 schrieb John Chodera:

> |pyemma-dev| is built by travis using the docker infrastructure, which 
> currently uses ubuntu 14.04. Because of this, it's only usable on 
> systems with a more recent GLIBC. Our CentOS 6.5 cluster doesn't have 
> a recent GLIBC.
> 
> Solutions:
> - You can |conda remove --yes pyemma-dev| and install it from the
>   github repo source with |python setup.py install|
> - You can wait for them to cut an official release and update the
>   |pyemma| recipe, which will be built by a docker framework on a
>   maximally compatible |holy-build-box| derivative
> - The |pyemma| folks could change this line
>   https://github.com/markovmodel/PyEMMA/blob/devel/.travis.yml#L6
>   to |sudo: true| to force travis tests/dev builds on the older
>   travis precise penguin architecture
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/792#issuecomment-216053191

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
@jchodera wouldn't it also be easy to use the docker images of holy-build-box to just perform the build inside the image and perform the testing in the base travis image? Of course this would require some changes to the build-box image (move built packages to the mounted location).

like described here:
https://linuxconfig.org/how-to-share-data-between-a-docker-container-and-host-system-using-volumes

By doing it that way, we can provide our dev builds with maximum compatibility and testing flexibility.

**Comment by jchodera** [comment]
That could work too if the overhead of downloading the image (which sometimes takes a few minutes) is acceptable. That reminds me that we also should be testing on OSX when possible.

I could experiment with this and take a stab at updating the devtools guidelines at http://github.com/omnia-md/devtools once I get something working, but it may not happen for a week or two. Let me know if you guys get something worked out sooner (presumably based on what happens inside the conda-recipes repo Travis).

**Comment by marscher** [comment]
Am 02.05.2016 um 14:01 schrieb John Chodera:

> That could work too if the overhead of downloading the image (which sometimes takes a few minutes) is acceptable.
> I guess Travis would cache this download, so it would take a couple of seconds to get this image.

  That reminds me that we also should be testing on OSX when possible.

> I could experiment with this and take a stab at updating the devtools guidelines at http://github.com/omnia-md/devtools https://github.com/omnia-md/devtools once I get something working, but it may not happen for a week or two. Let me know if you guys get something worked out sooner (presumably based on what happens inside the conda-recipes repo Travis).
> 
> I think that the basic infrastructure is already there in omnia-conda-recipes travis yaml. We only need to mount the path to conda-bld to the host system, so we can access the images.

**Comment by marscher** [comment]
to change this it would require to change a lot of mission critical things, so I refuse this. 

Use pip install git+https://github.com/markovmodel/pyemma@devel, if you install on the CentOs systems (as you probably already do since months).

**Comment by jchodera** [comment]
I concur that this is a simple alternative that works well for me.

We _could_ also add pyemma to the http://github.com/omnia-md/conda-dev-recipies nightly builds. Do we think that would be valuable?

**Comment by marscher** [comment]
Yes, that would do it. But I guess we need to change something in the recipe for that?

**Comment by marscher** [comment]
I'll add the recipe there, thank you!

**Comment by marscher** [comment]
omnia-md/conda-dev-recipes/pull/37
