### ISSUE TITLE
Allow featurizer to take Topology argument in addition to PDB files?

### ISSUE THREAD

**Issue by jchodera** [markovmodel/PyEMMA#799]
Would it be possible for `pyemma.coordinates.featurizer()` to accept a `Topology` object as a substitute for a PDB file?  The current API suggests only a filename is permitted right now:

https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/api.py#L67

**Comment by gph82** [comment]
@jchodera you can:
https://github.com/markovmodel/PyEMMA/blob/8c695c5dcf78eba7176fea21a770b0925e7c66c5/pyemma/coordinates/data/featurization/featurizer.py#L55

it's just not actually documented...

**Comment by franknoe** [comment]
I think that's already possible, see

https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/data/featurization/featurizer.py#L54

but should be documented.

Am 12/05/16 um 18:06 schrieb John Chodera:

> Would it be possible for |pyemma.coordinates.featurizer()| to accept a 
> |Topology| object as a substitute for a PDB file? The current API 
> suggests only a filename is permitted right now:
> 
> https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/api.py#L67
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/799

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
Thanks!  Looks like you just need to [update the docstring](https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/api.py#L72-L73) then.

**Comment by jchodera** [comment]
Closed via #800
