### ISSUE TITLE
RegularSpaceClustering doesn't work with multiple trajectories

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#80]
code from coordinates/clustering/regspace.py
```Python
            if t == 0:
                assert len(self._clustercenters) >= 1
                # create numpy array from clustercenters list
                self.clustercenters = np.array(self._clustercenters)
                del self._clustercenters  # delete temporary
```
This seems to chause a failure when the second trajectory is processed. 
Error message "AttributeError: 'RegularSpaceClustering' object has no attribute '_clustercenters'"

**Comment by marscher** [comment]
Am 21.02.2015 um 18:57 schrieb fabian-paul:
> code from coordinates/clustering/regspace.py
> 
>             if t == 0:
>                 assert len(self._clustercenters) >= 1
>                 # create numpy array from clustercenters list
>                 self.clustercenters = np.array(self._clustercenters)
>                 del self._clustercenters  # delete temporary
> 
> This seems to chause a failure when the second trajectory is processed.
> Error message "AttributeError: 'RegularSpaceClustering' object has no
> attribute '_clustercenters'"
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/80>.
> 
fixed.
