### ISSUE TITLE
pyemma.plots.plot_markov_model doesn't accept arrow_labels=None anymore

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#808]
In `pyemma.plots.plot_markov_model`, `arrow_labels=None` used to work before, but now leads to the following failure. I guess this is due to #793 that I unfortunately merged. I think we will have to add tests for the plots as well - not necessarily test the output as that is visual, but at least test for non failing using the Agg backend.

``` python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-26-3574d4368b3c> in <module>()
----> 1 plots.plot_markov_model(Pplot, arrow_labels=None)

/Users/noe/data/software_projects/pyemma/pyemma/plots/networks.pyc in plot_markov_model(P, pos, state_sizes, state_scale, state_colors, state_labels, minflux, arrow_scale, arrow_curvature, arrow_labels, arrow_label_format, max_width, max_height, figpadding, show_frame, **textkwargs)
    417                            max_width=max_width, max_height=max_height,
    418                            figpadding=figpadding, xticks=False, yticks=False, show_frame=show_frame,
--> 419                            **textkwargs)
    420     return ax, plot.pos
    421 

/Users/noe/data/software_projects/pyemma/pyemma/plots/networks.pyc in plot_network(self, state_sizes, state_scale, state_colors, state_labels, arrow_scale, arrow_curvature, arrow_labels, arrow_label_format, max_width, max_height, figpadding, xticks, yticks, show_frame, **textkwargs)
    250                     self._draw_arrow(self.pos[i, 0], self.pos[i, 1],
    251                                      self.pos[j, 0], self.pos[j, 1], Dx, Dy,
--> 252                                      label=arrow_label_format%L[i, j],
    253                                      width=arrow_scale * self.A[i, j],
    254                                      arrow_curvature=arrow_curvature,

TypeError: float argument required, not str
```

**Comment by marscher** [comment]
Damn and I just pressed the release button...

**Comment by gph82** [comment]
Hi @franknoe , i think this was me. Can you please post the code that lead to the error?

**Comment by franknoe** [comment]
that's ok, it's a minor thing and probably easy to fix. It's fine to put 
it in the next patch.

Am 18/05/16 um 17:18 schrieb Martin K. Scherer:

> Damn and I just pressed the release button...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/808#issuecomment-220060267

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
Just run plot_network with arrow_labels=None, the rest doesn't matter.

Am 18/05/16 um 17:21 schrieb Guillermo Pérez-Hernández:

> Hi @Frank https://github.com/Frank, i think this was me. Can you 
> please post the code that lead to the error?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/808#issuecomment-220061214

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany
