### ISSUE TITLE
serialization of models and estimators

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#810]
During working on the serialization branch, I noticed that there is a little inconsistency for this attribute.

@franknoe is this intended or can I safely change this?

**Comment by franknoe** [comment]
No, both are hidden variables, there is no intentional difference between them.

For the serialization, I think it is important to not simple store and load everything but to only store / save stuff that is important to reconstruct the model. I think the estimator and model parameters are probably a good start here. So let's discuss this before investing much in the implementation of this feature.

**Comment by marscher** [comment]
The prototype already contains model and estimator parameters serialization, plus some hidden fields for MSM and MLMSM. This is actually needed for the use case 
of restoring an estimated estimator, which is quite common. For instance a lot of methods in MLMSM rely on hidden fields set during estimation or even in 
constructor. If would simply omit their serialization, the restored object will behave very bad.

Classes carry a version field now, comparable to the serialVersionUID in Java. With that one could even think of supporting restoring objects from an older 
version, in which the actual class has some renamed fields. For this purpose one needs to define a mapping between the renamed fields and define some 
interpolation for missing fields.

The storage format is currently defined as compressed JSON dictionary. This way it is still partially human-readable (numpy arrays aren't, because they are 
stored binary). Because it is a dictionary, other people can easily obtain arbitrary attributes from it, making it possible to interchange data easily.

So far it works pretty well, the times for save/load are in a good regime. (The default pickle protocol and jsonpickle take ages for arrays).

Of course we can now define the desired user API (currently a Model/Estimator provides a save(filename) method and pyemma package got a "load" function) and 
other critical things like how to deal with the problem of refactoring.

**Comment by franknoe** [comment]
ok, let's discuss it soon. My idea was that we definitely have to revise 
some of the estimator / model objects, because most of them (especially 
the ones written by me) are a little bit sloppy with respect to how 
internal attributes are defined and named. A save/load protocol forces 
us to think about these things more explicitly.

Am 25/05/16 um 20:09 schrieb Martin K. Scherer:

> The prototype already contains model and estimator parameters 
> serialization, plus some hidden fields for MSM and MLMSM. This is 
> actually needed for the use case
> of restoring an estimated estimator, which is quite common. For 
> instance a lot of methods in MLMSM rely on hidden fields set during 
> estimation or even in
> constructor. If would simply omit their serialization, the restored 
> object will behave very bad.
> 
> Classes carry a version field now, comparable to the serialVersionUID 
> in Java. With that one could even think of supporting restoring 
> objects from an older
> version, in which the actual class has some renamed fields. For this 
> purpose one needs to define a mapping between the renamed fields and 
> define some
> interpolation for missing fields.
> 
> The storage format is currently defined as compressed JSON dictionary. 
> This way it is still partially human-readable (numpy arrays aren't, 
> because they are
> stored binary). Because it is a dictionary, other people can easily 
> obtain arbitrary attributes from it, making it possible to interchange 
> data easily.
> 
> So far it works pretty well, the times for save/load are in a good 
> regime. (The default pickle protocol and jsonpickle take ages for arrays).
> 
> Of course we can now define the desired user API (currently a 
> Model/Estimator provides a save(filename) method and pyemma package 
> got a "load" function) and
> other critical things like how to deal with the problem of refactoring.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/810#issuecomment-221658113

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
btw, can you make this a public branch, so we can review and discuss it 
while in progress?

Am 25/05/16 um 20:09 schrieb Martin K. Scherer:

> The prototype already contains model and estimator parameters 
> serialization, plus some hidden fields for MSM and MLMSM. This is 
> actually needed for the use case
> of restoring an estimated estimator, which is quite common. For 
> instance a lot of methods in MLMSM rely on hidden fields set during 
> estimation or even in
> constructor. If would simply omit their serialization, the restored 
> object will behave very bad.
> 
> Classes carry a version field now, comparable to the serialVersionUID 
> in Java. With that one could even think of supporting restoring 
> objects from an older
> version, in which the actual class has some renamed fields. For this 
> purpose one needs to define a mapping between the renamed fields and 
> define some
> interpolation for missing fields.
> 
> The storage format is currently defined as compressed JSON dictionary. 
> This way it is still partially human-readable (numpy arrays aren't, 
> because they are
> stored binary). Because it is a dictionary, other people can easily 
> obtain arbitrary attributes from it, making it possible to interchange 
> data easily.
> 
> So far it works pretty well, the times for save/load are in a good 
> regime. (The default pickle protocol and jsonpickle take ages for arrays).
> 
> Of course we can now define the desired user API (currently a 
> Model/Estimator provides a save(filename) method and pyemma package 
> got a "load" function) and
> other critical things like how to deal with the problem of refactoring.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/810#issuecomment-221658113

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
The branch is visible on my fork:
https://github.com/marscher/PyEMMA/tree/models_estimators_serializeable

You're right, should tidy up before we establish naming conventions.

**Comment by franknoe** [comment]
Can you push it to a feature branch in the public repo? This way we can 
both commit or PR to it.

Am 25/05/16 um 20:51 schrieb Martin K. Scherer:

> The branch is visible on my fork:
> https://github.com/marscher/PyEMMA/tree/models_estimators_serializeable
> 
> You're right, should tidy up before we establish naming conventions.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/810#issuecomment-221671034

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 25.05.2016 um 21:26 schrieb Frank Noe:

> Can you push it to a feature branch in the public repo? This way we can
> both commit or PR to it.
> PRs are also possible to forks btw. But I see you want to have all in place.

**Comment by marscher** [comment]
same name, just in this repo.

**Comment by franknoe** [comment]
yeah, makes it easier to find it without remembering on whose feature 
branch it was. thanx.

Am 25/05/16 um 21:29 schrieb Martin K. Scherer:

> same name, just in this repo.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/810#issuecomment-221681174

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I've looked at the serialization code. I don't understand it in great detail, but two general comments:
1. I agree we should save objects by `obj.save(filename)`. I think it would be good to have load in a central place, so that the user doesn't have to guess which object type they want to load, e.g. simply `pyemma.load(filename)`. I guess that the `load` function in your serialization module can do that and would just need to be imported in the main `__init__` to do that. Correct?
2. The current save/load seems to be saving/loading all attributes of the object (I guess it just stores the dict?) I think it's important that this can be customized and we must customize this. Not everything that is referenced by the dict really belongs to the object, and in some cases we only want to save parts in order to avoid huge files. So I think we should not just reproduce a pickle-type save+load everything but a selection mechanism what are primary quantities that are essential to store and what are secondary / derived quantities or just links to foreign objects that do not need to be stored. How would such a customization work?

**Comment by marscher** [comment]
On 27.05.2016 13:18, Frank Noe wrote:

> I've looked at the serialization code. I don't understand it in great
> detail, but two general comments:
> 1. I agree we should save objects by |obj.save(filename)|. I think it
> would be good to have load in a central place, so that the user doesn't
> have to guess which object type they want to load, e.g. simply
> |pyemma.load(filename)|. I guess that the |load| function in your
> serialization module can do that and would just need to be imported in
> the main |**init**| to do that. Correct?
> There is such a load method already in pyemma/**init**.py, which simply
> invokes the load method in serialization.py
> 1. The current save/load seems to be saving/loading all attributes of
>    the object (I guess it just stores the dict?) I think it's important
>    that this can be customized and we must customize this. Not everything
>    that is referenced by the dict really belongs to the object, and in some
>    cases we only want to save parts in order to avoid huge files. So I
>    think we should not just reproduce a pickle-type save+load everything
>    but a selection mechanism what are primary quantities that are essential
>    to store and what are secondary / derived quantities or just links to
>    foreign objects that do not need to be stored. How would such a
>    customization work?
>    This is exactly what has been done so far.

It does not store all attributes, but only the relevant (eg. defined)
ones. For estimators the estimator parameters will be stored, for models
the model parameters. Now for specialized subclasses one can define a
static field "_serialize_fields", which is a tuple of attribute names,
which will be tried to store (eg. in case the estimation has not
happened during serialization, most internal variables defined there,
are not yet defined, so they will be ignored).

The getstate methods will be called from the child classes throughout
their parents and the state dictionary will be extended in the child.

However we still need to define a mapping of internal variable names to
"serialized" names in order to maintain compatibility with older
versions of the already stored classes.

For this purpose I suggest to define a dictionary the following way:

{ "$version" : {
    "serialized_name" : "internal_variable_name"
    }
}

The version of the class has then to be incremented everytime we change
field names (insertion, deletion, renames).

**Comment by franknoe** [comment]
OK, you need to look in the subclasses. Thanks, I'll have a closer look 
into those.

Am 27/05/16 um 13:28 schrieb Martin K. Scherer:

> On 27.05.2016 13:18, Frank Noe wrote:
> 
> > I've looked at the serialization code. I don't understand it in great
> > detail, but two general comments:
> > 1. I agree we should save objects by |obj.save(filename)|. I think it
> > would be good to have load in a central place, so that the user doesn't
> > have to guess which object type they want to load, e.g. simply
> > |pyemma.load(filename)|. I guess that the |load| function in your
> > serialization module can do that and would just need to be imported in
> > the main |**init**| to do that. Correct?
> > There is such a load method already in pyemma/**init**.py, which simply
> > invokes the load method in serialization.py
> > 1. The current save/load seems to be saving/loading all attributes of
> >    the object (I guess it just stores the dict?) I think it's important
> >    that this can be customized and we must customize this. Not everything
> >    that is referenced by the dict really belongs to the object, and in some
> >    cases we only want to save parts in order to avoid huge files. So I
> >    think we should not just reproduce a pickle-type save+load everything
> >    but a selection mechanism what are primary quantities that are essential
> >    to store and what are secondary / derived quantities or just links to
> >    foreign objects that do not need to be stored. How would such a
> >    customization work?
> >    This is exactly what has been done so far.
> 
> It does not store all attributes, but only the relevant (eg. defined)
> ones. For estimators the estimator parameters will be stored, for models
> the model parameters. Now for specialized subclasses one can define a
> static field "_serialize_fields", which is a tuple of attribute names,
> which will be tried to store (eg. in case the estimation has not
> happened during serialization, most internal variables defined there,
> are not yet defined, so they will be ignored).
> 
> The getstate methods will be called from the child classes throughout
> their parents and the state dictionary will be extended in the child.
> 
> However we still need to define a mapping of internal variable names to
> "serialized" names in order to maintain compatibility with older
> versions of the already stored classes.
> 
> For this purpose I suggest to define a dictionary the following way:
> 
> { "$version" : {
> "serialized_name" : "internal_variable_name"
> }
> }
> 
> The version of the class has then to be incremented everytime we change
> field names (insertion, deletion, renames).
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/810#issuecomment-222123719, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQvpuvv7QkdCnrs8cXP7plU4CO3riks5qFtVDgaJpZM4ImphD.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Currently it is implemented for MSM and MLMSM
