### ISSUE TITLE
kmeans minRMSD bug

### ISSUE THREAD

**Issue by thempel** [markovmodel/PyEMMA#814]
There seems to be a bug in the kmeans clustering algorithm if used with minRMSD metric. What happens is that the ipython kernel dies without an error message. This problem occurred first with an aligned MD trajectory but can be reproduced with the following minimal example. 

`import numpy as np`
`import pyemma.coordinates as coor`
`test_data = np.random.rand(500, 3)`
`test_clustering = coor.cluster_kmeans(test_data, 10, metric='minRMSD')`

**Comment by marscher** [comment]
confirmed. Expect a fix soon.
