### ISSUE TITLE
http://www.emma-project.org/ is not updated to include version 2.2 and doesn't have documentation for tram 

### ISSUE THREAD

**Issue by cclementi** [markovmodel/PyEMMA#817]
Hi, I have just noticed that the online documentation of pyemma has not been updated to include version 2.2, and there is no documentation on tram in the thermo package. 
Also, in the documentation that is available for the estimate_umbrella_samplng function right now (see http://www.emma-project.org/latest/api/generated/pyemma.thermo.estimate_umbrella_sampling.html#pyemma.thermo.estimate_umbrella_sampling) there is no information on what is available inside the estimator object that is returned by this function. It would be useful to have a list of the object's attributes. 
Thanks!

**Comment by marscher** [comment]
Hi,

sorry, the trigger hasn't been pulled yet. The docs are currently building. Thank you!

**Comment by marscher** [comment]
done
