### ISSUE TITLE
chain information in featurizer _describe_atom function?

### ISSUE THREAD

**Issue by sstolzenberg** [markovmodel/PyEMMA#821]
Hi,

it would be great to have some chain ID information in the _describe_atom method in 

pyemma.coordinates.data.featurization.util

As far as I understand, the only way to retrieve this information with mdtraj is via
at.residue.chain.index
where "at" is an atom object, and the type of "index" is an integer

Is it possible to change this myself? (Guille found out 70 usages for this function)

Thanks,
Seb

**Comment by gph82** [comment]
@sstolzenberg , the function returns one single string anyway, so he extensions would be much easier than expected. If we're for this, I can implement it

**Comment by sstolzenberg** [comment]
OK, fine by me

Thanks,
Seb

On 01.06.2016 17:04, Guillermo Pérez-Hernández wrote:

> @sstolzenberg https://github.com/sstolzenberg , the function returns
> one single string anyway, so he extensions would be much easier than
> expected. If we're for this, I can implement it
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/markovmodel/PyEMMA/issues/821#issuecomment-223021935,
> or mute the thread
> https://github.com/notifications/unsubscribe/ALAYFgINJ7pK8nj9Pbg3x-r1pdMYL_z_ks5qHZ-KgaJpZM4IrolE.

## 

---

Sebastian Stolzenberg, Ph.D.
PostDoc, Computational Molecular Biology group
Freie Universität Berlin

Phone: (+49) (0)30 838 75153

## Mail:  Arnimallee 6, 14195 Berlin, Germany
