### ISSUE TITLE
tiny issue on  Jupyter Notebook Tutorials

### ISSUE THREAD

**Issue by cclementi** [markovmodel/PyEMMA#824]
Hi, I am looking at the tutorial: 
http://www.emma-project.org/latest/generated/PyEMMA.thermo.estimate_umbrella_sampling_-_asymmetric_double_well.html
and I noticed that in the "Performance" section there is some text that has not been rendered correctly (from a LaTeX input, I guess):

Now, we compare mean first passage times (MFPT, kinetics) for MSM, dTRAM, and TRAM; reference values are 370$30stepsand230030stepsand2300$200 steps. We observe that dTRAM and TRAM are comparably close to the reference while the MSM is off (for the slow process) by a factor of two.

I don't know what "370$30stepsand230030stepsand2300$200" should read like.

Thanks!

**Comment by marscher** [comment]
ping @cwehmeyer

**Comment by marscher** [comment]
The $\pm$ setting is recognized correctly in Jupyter notebook itself but during the conversion to RST it brakes. Since this is an upstream bug, we could only replace the std deviation symbol with something else.

```
Now, we compare mean first passage times (MFPT, kinetics) for MSM,
dTRAM, and TRAM; reference values are 370 :math:`\pm` 30 steps and 2300
:math:`\pm` 200 steps.
```

My guess is that something during the conversion from rst to html is bogus.

**Comment by marscher** [comment]
Tested locally, with some spaces around the math string it renders correctly. Please stand by the online docs will be updated soon.
