### ISSUE TITLE
devel version of pyemma.thermo.estimate_umbrella_sampling requires us_centers and us_force_constants to be list

### ISSUE THREAD

**Issue by cclementi** [markovmodel/PyEMMA#827]
Hi,

I have installed the pyemma devel version because of a problem I was having running wham with version 2.2 (see issue #826, now closed). However, I have noticed that the format of the input is now different. In particular, if I define us_centers and us_force_constants as arrays (as in the documentation at http://www.emma-project.org/latest/api/generated/thermo-api/pyemma.thermo.estimate_umbrella_sampling.html#pyemma.thermo.estimate_umbrella_sampling) it fails because it now wants us_centers and us_force_constants to be lists. If I define them as lists, it seems to work fine. 

Thanks!

**Comment by cwehmeyer** [comment]
That should not (yet) be part of the development version. Have you installed via pip or the pyemma-dev via conda?

**Comment by franknoe** [comment]
I think both versions should work. Is this perhaps a side-effect of the 
changes you made to make the umbrella sampling input more robust?

Am 06/06/16 um 20:46 schrieb Christoph Wehmeyer:

> That should not (yet) be part of the development version. Have you 
> installed via pip or the pyemma-dev via conda?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/827#issuecomment-224051015, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQjmxYSIeH3Jd4QAOnz7ecWhICJHJks5qJGshgaJpZM4IvMFP.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by cclementi** [comment]
I've installed the pyemma-dev via conda (upon Frank suggestion :)

**Comment by cwehmeyer** [comment]
That is indeed a side effect which I am currently working on.

The reason I was asking is that I saw an error message while running @cclementi's script on shark which I had not yet merged into devel. So I guess, there is an issue with the pyemma-dev version.

**Comment by franknoe** [comment]
weird

Am 06/06/16 um 20:55 schrieb Christoph Wehmeyer:

> That is indeed a side effect which I am currently working on.
> 
> The reason I was asking is that I saw an error message while running 
> @cclementi https://github.com/cclementi's script on shark which I 
> had not yet merged into devel. So I guess, there is an issue with the 
> pyemma-dev version.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/827#issuecomment-224053278, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQheFhhTpRbguREb1kMilce3IJHBpks5qJG0FgaJpZM4IvMFP.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by cwehmeyer** [comment]
For clarification: I installed pyemma-dev today on shark, saw the error message, and checked that the relevant code was not yet on the devel branch. Hence, pyemma-dev might point the the most recent version across all branches.

pinging @marscher

**Comment by cwehmeyer** [comment]
As for the original reason of this issue: I tried to support single trajectories in the high level API without the need to put the numpy.ndarray in a list or tuple, but that apparently backfired. Thanks for spotting, I will fix this before merging.

**Comment by marscher** [comment]
@cwehmeyer deployments for pyemma-dev are only done for the devel branch, as it is obviously defined in the script devtools/ci/travis/after_success.sh ;)

Which commit does this specific version you are talking about point to?

**Comment by cwehmeyer** [comment]
@marscher, I am not particularly sure about the commit. But look at the traceback of the exception:

``` python
Traceback (most recent call last):
  File "WHAM_fisDNA_all.py", line 127, in <module>
    maxiter=maxiter, maxerr=maxerr, save_convergence_info=50, estimator='wham')
  File "/group/ag_cmb/scratch/schiffm/miniconda/lib/python2.7/site-packages/pyEMMA-2.2+25.gb5fa199-py2.7-linux-x86_64.egg/pyemma/thermo/api.py", line 150, in estimate_umbrella_sampling
    us_trajs, us_centers, us_force_constants, md_trajs=md_trajs, kT=kT)
  File "/group/ag_cmb/scratch/schiffm/miniconda/lib/python2.7/site-packages/pyEMMA-2.2+25.gb5fa199-py2.7-linux-x86_64.egg/pyemma/thermo/util/util.py", line 271, in get_umbrella_sampling_data
    us_trajs, us_centers, us_force_constants, md_trajs=md_trajs, kT=kT)
  File "/group/ag_cmb/scratch/schiffm/miniconda/lib/python2.7/site-packages/pyEMMA-2.2+25.gb5fa199-py2.7-linux-x86_64.egg/pyemma/thermo/util/util.py", line 140, in _get_umbrella_sampling_parameters
    % (len(us_trajs), len(us_centers)))
ValueError: Unmatching number of umbrella sampling trajectories and centers: 96!=1
```

If you refer to the pyemma.thermo.util module on the devel branch, you will not find anything that raises a ValueError anywhere around line 140. I made sure that only pyemma-dev was installed.

Afterwards, I uninstalled pyemma-dev and reinstalled via pip from the devel branch and the exception disappeared.

And, correct me if I am wrong, the version number seems to indicate that pyemma-dev is 25 commits ahead of pyemma-2.2. When I install via pip, I get pyemma-2.2+9.gf766d3e.

**Comment by cwehmeyer** [comment]
Update: the relevant code was introduced in commit be3f399e10863b24294b65ab4a6692cb0323f7af (latest commit on robust_us).

**Comment by marscher** [comment]
what is the version hash of conda's pyemma-dev?

**Comment by cwehmeyer** [comment]
2.2+25.gb5fa199

**Comment by marscher** [comment]
@cwehmeyer this version is a normal merge of a PR of yours (#813), so maybe you mixed your branches locally?

**Comment by marscher** [comment]
I've fixed the script which decides whether a devel version should be uploaded.
