### ISSUE TITLE
estimate_hidden_markov_model not working

### ISSUE THREAD

**Issue by giopina** [markovmodel/PyEMMA#832]
After upgrading to the latest pyemma version  pyemma.msm.estimate_hidden_markov_model() is not working anymore. The same error is encoutered when using the method coarse_grain() on an msm object.

This is the error the program gives when calling msm.estimate_hidden_markov_model(dtrajs,4,100)

---

AttributeError                            Traceback (most recent call last)
<ipython-input-20-b43ba4297b80> in <module>()
----> 1 msm.estimate_hidden_markov_model(ctrajs,4,100)

/home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/msm/api.pyc in estimate_hidden_markov_model(dtrajs, nstates, lag, reversible, stationary, connectivity, mincount_connectivity, separate, observe_nonempty, stride, dt_traj, accuracy, maxit)
   1034                               accuracy=accuracy, maxit=maxit)
   1035     # run estimation
-> 1036     return hmsm_estimator.estimate(dtrajs)
   1037 
   1038 

/home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/estimator.pyc in estimate(self, X, **params)
    346         if params:
    347             self.set_params(**params)
--> 348         self._model = self._estimate(X)
    349         self._estimated = True
    350         return self

/home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.pyc in _estimate(self, dtrajs)
    191 
    192         # LAG AND STRIDE DATA
--> 193         dtrajs_lagged_strided = bhmm.lag_observations(dtrajs, self.lag, stride=self.stride)
    194 
    195         # OBSERVATION SET

AttributeError: 'module' object has no attribute 'lag_observations'

**Comment by franknoe** [comment]
Is this the 2.2 conda release, or are you working on the devel version?

Am 13/06/16 um 12:12 schrieb giopina:

> After upgrading to the latest pyemma version 
> pyemma.msm.estimate_hidden_markov_model() is not working anymore. The 
> same error is encoutered when using the method coarse_grain() on an 
> msm object.
> 
> This is the error the program gives when calling 
> msm.estimate_hidden_markov_model(dtrajs,4,100)
> 
> ---
> 
> AttributeError Traceback (most recent call last)
> in ()
> ----> 1 msm.estimate_hidden_markov_model(ctrajs,4,100)
> 
> /home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/msm/api.pyc 
> in estimate_hidden_markov_model(dtrajs, nstates, lag, reversible, 
> stationary, connectivity, mincount_connectivity, separate, 
> observe_nonempty, stride, dt_traj, accuracy, maxit)
> 1034 accuracy=accuracy, maxit=maxit)
> 1035 # run estimation
> -> 1036 return hmsm_estimator.estimate(dtrajs)
> 1037
> 1038
> 
> /home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/estimator.pyc 
> in estimate(self, X, _params)
> 346 if params:
> 347 self.set_params(_params)
> --> 348 self._model = self._estimate(X)
> 349 self._estimated = True
> 350 return self
> 
> /home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.pyc 
> in _estimate(self, dtrajs)
> 191
> 192 # LAG AND STRIDE DATA
> --> 193 dtrajs_lagged_strided = bhmm.lag_observations(dtrajs, 
> self.lag, stride=self.stride)
> 194
> 195 # OBSERVATION SET
> 
> AttributeError: 'module' object has no attribute 'lag_observations'
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/832, or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQlaDWivFJtwBIEwb_r1DNRgRhA1jks5qLS0dgaJpZM4I0LkQ.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
PS, pls also report which bhmm version you have and try upgrading. We 
used to have a problem with the conda updating of bhmm, so maybe that's 
the issue here.

Am 13/06/16 um 12:12 schrieb giopina:

> After upgrading to the latest pyemma version 
> pyemma.msm.estimate_hidden_markov_model() is not working anymore. The 
> same error is encoutered when using the method coarse_grain() on an 
> msm object.
> 
> This is the error the program gives when calling 
> msm.estimate_hidden_markov_model(dtrajs,4,100)
> 
> ---
> 
> AttributeError Traceback (most recent call last)
> in ()
> ----> 1 msm.estimate_hidden_markov_model(ctrajs,4,100)
> 
> /home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/msm/api.pyc 
> in estimate_hidden_markov_model(dtrajs, nstates, lag, reversible, 
> stationary, connectivity, mincount_connectivity, separate, 
> observe_nonempty, stride, dt_traj, accuracy, maxit)
> 1034 accuracy=accuracy, maxit=maxit)
> 1035 # run estimation
> -> 1036 return hmsm_estimator.estimate(dtrajs)
> 1037
> 1038
> 
> /home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/estimator.pyc 
> in estimate(self, X, _params)
> 346 if params:
> 347 self.set_params(_params)
> --> 348 self._model = self._estimate(X)
> 349 self._estimated = True
> 350 return self
> 
> /home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.pyc 
> in _estimate(self, dtrajs)
> 191
> 192 # LAG AND STRIDE DATA
> --> 193 dtrajs_lagged_strided = bhmm.lag_observations(dtrajs, 
> self.lag, stride=self.stride)
> 194
> 195 # OBSERVATION SET
> 
> AttributeError: 'module' object has no attribute 'lag_observations'
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/832, or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQlaDWivFJtwBIEwb_r1DNRgRhA1jks5qLS0dgaJpZM4I0LkQ.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I checked the latest devel version, and it's passing all tests:

```
 https://travis-ci.org/markovmodel/PyEMMA/builds/135857326
```

This feature is definitely tested and the function `lag_observations` 
is part of bhmm since a while ago. My guess is that you had an older 
bhmm version on your machine and for some reason the updating didn't 
work properly or there are multiple competing installations of this 
package and the wrong version gets imported. I suggest to remove your 
bhmm install, make sure that none is left, and fetch a new version.

My impression is that many errors on the user side are based on version 
inconsistencies between dependencies. Since these can be installed in 
various ways it is not really under our control to ensure consistent 
versioning on the user side. We are working on a better way to do this 
in the near future.

@clonker, do you have time to discuss this this week?

Am 13/06/16 um 12:12 schrieb giopina:

> After upgrading to the latest pyemma version 
> pyemma.msm.estimate_hidden_markov_model() is not working anymore. The 
> same error is encoutered when using the method coarse_grain() on an 
> msm object.
> 
> This is the error the program gives when calling 
> msm.estimate_hidden_markov_model(dtrajs,4,100)
> 
> ---
> 
> AttributeError Traceback (most recent call last)
> in ()
> ----> 1 msm.estimate_hidden_markov_model(ctrajs,4,100)
> 
> /home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/msm/api.pyc 
> in estimate_hidden_markov_model(dtrajs, nstates, lag, reversible, 
> stationary, connectivity, mincount_connectivity, separate, 
> observe_nonempty, stride, dt_traj, accuracy, maxit)
> 1034 accuracy=accuracy, maxit=maxit)
> 1035 # run estimation
> -> 1036 return hmsm_estimator.estimate(dtrajs)
> 1037
> 1038
> 
> /home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/estimator.pyc 
> in estimate(self, X, _params)
> 346 if params:
> 347 self.set_params(_params)
> --> 348 self._model = self._estimate(X)
> 349 self._estimated = True
> 350 return self
> 
> /home/mi/giopina/miniconda/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/msm/estimators/maximum_likelihood_hmsm.pyc 
> in _estimate(self, dtrajs)
> 191
> 192 # LAG AND STRIDE DATA
> --> 193 dtrajs_lagged_strided = bhmm.lag_observations(dtrajs, 
> self.lag, stride=self.stride)
> 194
> 195 # OBSERVATION SET
> 
> AttributeError: 'module' object has no attribute 'lag_observations'
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/832, or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQlaDWivFJtwBIEwb_r1DNRgRhA1jks5qLS0dgaJpZM4I0LkQ.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by giopina** [comment]
Fixed.
I removed everything and installed pyemma and bhmm again. Apparently as you said there was some old bhmm version competing.
Thanks

**Comment by franknoe** [comment]
cool, thanks
