### ISSUE TITLE
Ipython/Jupyter help shows docstring of base estimator's method instead of the subclass method.

### ISSUE THREAD

**Issue by fabian-paul** [markovmodel/PyEMMA#834]
Help form the Python-OO gurus in fixing this would be appreciated.

```
In [1]: import pyemma

In [2]: tram = pyemma.thermo.TRAM(1)

In [3]: tram.estimate?
Signature: tram.estimate(X, **params)
Docstring:
Estimates the model given the data X

Parameters
----------
X : object
    A reference to the data from which the model will be estimated
params : dict
    New estimation parameter values. The parameters must that have been
    announced in the __init__ method of this estimator. The present
    settings will overwrite the settings of parameters given in the
    __init__ method, i.e. the parameter values after this call will be
    those that have been used for this estimation. Use this option if
    only one or a few parameters change with respect to
    the __init__ settings for this run, and if you don't need to
    remember the original settings of these changed parameters.

Returns
-------
estimator : object
    The estimated estimator with the model being available.
File:      ~/git/PyEMMA/pyemma/_base/estimator.py
Type:      instancemethod
```

**Comment by marscher** [comment]
This is totally expected as the TRAM estimator does not override 
"estimate" but "_estimate".

So you can override estimate in TRAM, set the docstring there and call 
Estimator.estimate via super.

**Comment by franknoe** [comment]
I don't think you should override estimate in the subclass, but you can 
still set the docstring, right?

Am 19/06/16 um 16:13 schrieb Martin K. Scherer:

> This is totally expected as the TRAM estimator does not override
> "estimate" but "_estimate".
> 
> So you can override estimate in TRAM, set the docstring there and call
> Estimator.estimate via super.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/834#issuecomment-226999485, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQm7L10lOVsYzgqZgm-MI3ydXzhryks5qNU52gaJpZM4I2Tp7.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by franknoe** [comment]
I see, that's not an option then. OK, then Martin's option seems better, 
if you feel you have to set the docstring in the estimate of the class.
We should think about the design here. Seems we need to do something 
unnatural to achieve something simple.

Am 19/06/16 um 16:23 schrieb Martin K. Scherer:

> On 19.06.2016 16:18, Frank Noe wrote:
> 
> > I don't think you should override estimate in the subclass, but you can
> > still set the docstring, right?
> > This was also my first thought, but unfortunately this also sets the
> > docstring of the parent class for all new instances...
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/834#issuecomment-226999984, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQmRxK_u_dqlrY53dG5VZJnbTBqkiks5qNVDKgaJpZM4I2Tp7.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
It is very ugly - I agree. Maybe it is possible to override the 
docstring in a different manner.

**Comment by jhprinz** [comment]
A little comment, because I had some troubles with setting docstrings in OPS. What I found about setting docstrings is that you cannot. At least not for objects that are generated using the default metaclass. As soon as you use another metaclass (in my case I used the package abc for abstract base classes) you can use `class.__doc__ = ...`. Not sure if that helps with the problems of subclasses. This will affect all subclasses down from the one where you set the docstring. Unless one of the classes overrides it.
