### ISSUE TITLE
problem with minRMSD assignment to clustercenters

### ISSUE THREAD

**Issue by nsplattner** [markovmodel/PyEMMA#835]
The assignment of trajectories to clustercenters (obtained from the same trajectories) using a minRMSD metric produces a completely different result for PyEMMA 2.2 than for previous PyEMMA versions and leaves about 15 % of all centers with no frames assigned. This is most likely an error.

**Comment by jchodera** [comment]
Are you using the parallel version? Can you quickly try comparing the serial version with the parallel version (I think you can specify the number of threads) and see if the serial version works correctly?

I may have messed something up in my parallelizarion fix.

**Comment by nsplattner** [comment]
I have now tested different numbers of threads (1, 2, 4) using the n_jobs variable. The problem persists for all these choices and the assignment looks identical in all cases. Is there a serial version of the code accessible by a lower level API function or are all these choices of n_jobs using the same code anyway?

**Comment by jchodera** [comment]
The relevant C-level code is [here](https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/clustering/src/clustering.c#L46-L177).  There's only a parallel codepath right now, but reducing this to one thread should eliminate any issues that might involve unsynchronized data or race conditions. It's possible the issue is outside of this C code block then.

**Comment by franknoe** [comment]
Do you have a suggestion for a commit that could be checked out to see 
whether it was working before the last major change on this code?

Am 17/06/16 um 17:51 schrieb John Chodera:

> The relevant C-level code is here 
> https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/clustering/src/clustering.c#L46-L177. 
> There's only a parallel codepath right now, but reducing this to one 
> thread should eliminate any issues that might involve unsynchronized 
> data or race conditions. It's possible the issue is outside of this C 
> code block then.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/835#issuecomment-226806913, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQjll-nwzmAzWUb0mvmJyQzIbjYm3ks5qMsKGgaJpZM4I3i27.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by jchodera** [comment]
I think [this commit](https://github.com/markovmodel/PyEMMA/commit/eeafe71fb7035ac186e93e27ba1b84056e01c148#diff-caca5449251e2d740e0259924f0bb7f1) before _any_ parallelization was done might be a good one to check.

**Comment by franknoe** [comment]
OK, Nuria, can you check out that commit and see if it behaves better?

Am 17/06/16 um 21:38 schrieb John Chodera:

> I think this commit 
> https://github.com/markovmodel/PyEMMA/commit/eeafe71fb7035ac186e93e27ba1b84056e01c148#diff-caca5449251e2d740e0259924f0bb7f1 
> before /any/ parallelization was done might be a good one to check.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/835#issuecomment-226862884, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQokyblSJ_yz_TwgIt5kqvZCBZKX-ks5qMvelgaJpZM4I3i27.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by nsplattner** [comment]
Using commit eeafe71fb7035ac186e93e27ba1b84056e01c148 the assignment is different and looks somewhat more reasonable, however, there are still clustercenters with no frames assigned. So I think the problem already existed at this point and is getting worse in later code versions.

**Comment by marscher** [comment]
confirmed... we need to inspect this in more detail.
