### ISSUE TITLE
A small issue with pyemma.coordinates.featurizer  add_backbone_torsions() function

### ISSUE THREAD

**Issue by OleksandraQ** [markovmodel/PyEMMA#843]
Dear PyEmma Developers,
I faced a small issue with pyemma.coordinates.featurizer selecting add_backbone_torsions(deg = True). The .describe() output is 
['PHI 0 GLU 2 ',
 'PHI 0 GLU 3 ',
 'PHI 0 GLU 4 ',
 'PHI 0 GLU 5 ',
 'PHI 0 GLU 6 ',
 'PHI 0 GLU 7 ',
 'PHI 0 GLU 8 ',
 'PSI 0 GLU 1 ',
 'PSI 0 GLU 2 ',
 'PSI 0 GLU 3 ',
 'PSI 0 GLU 4 ',
 'PSI 0 GLU 5 ',
 'PSI 0 GLU 6 ',
 'PSI 0 GLU 7 ']
But actual output from .get_output() is in the next order (in some of the previous versions of pyemma it was like it is shown above in describe(), but not any more):
['PHI 0 GLU 2 ',
 'PSI 0 GLU 1 ',
 'PHI 0 GLU 3 ',
 'PSI 0 GLU 2 ',
 'PHI 0 GLU 4 ',
 'PSI 0 GLU 3 ',
 'PHI 0 GLU 5 ',
 'PSI 0 GLU 4 ',
 'PHI 0 GLU 6 ',
 'PSI 0 GLU 5 ',
 'PHI 0 GLU 7 ',
 'PSI 0 GLU 6 ',
 'PHI 0 GLU 8 ',
 'PSI 0 GLU 7 ']
It’s not an issue for further analysis like PCA or TICA, but if one what to make some simple Ramachandran plot, it’s really a challenge to guess, where is which angle, especially if one is used to gromacs tools.

**Comment by franknoe** [comment]
So you're saying describe and actual ordering are inconsistent? That's 
definitely a bug.

Am 24/06/16 um 18:15 schrieb OleksandraQ:

> Dear PyEmma Developers,
> I faced a small issue with pyemma.coordinates.featurizer selecting 
> add_backbone_torsions(deg = True). The .describe() output is
> ['PHI 0 GLU 2 ',
> 'PHI 0 GLU 3 ',
> 'PHI 0 GLU 4 ',
> 'PHI 0 GLU 5 ',
> 'PHI 0 GLU 6 ',
> 'PHI 0 GLU 7 ',
> 'PHI 0 GLU 8 ',
> 'PSI 0 GLU 1 ',
> 'PSI 0 GLU 2 ',
> 'PSI 0 GLU 3 ',
> 'PSI 0 GLU 4 ',
> 'PSI 0 GLU 5 ',
> 'PSI 0 GLU 6 ',
> 'PSI 0 GLU 7 ']
> But actual output from .get_output() is in the next order (in some of 
> the previous versions of pyemma it was like it is shown above in 
> describe(), but not any more):
> ['PHI 0 GLU 2 ',
> 'PSI 0 GLU 1 ',
> 'PHI 0 GLU 3 ',
> 'PSI 0 GLU 2 ',
> 'PHI 0 GLU 4 ',
> 'PSI 0 GLU 3 ',
> 'PHI 0 GLU 5 ',
> 'PSI 0 GLU 4 ',
> 'PHI 0 GLU 6 ',
> 'PSI 0 GLU 5 ',
> 'PHI 0 GLU 7 ',
> 'PSI 0 GLU 6 ',
> 'PHI 0 GLU 8 ',
> 'PSI 0 GLU 7 ']
> It’s not an issue for further analysis like PCA or TICA, but if one 
> what to make some simple Ramachandran plot, it’s really a challenge to 
> guess, where is which angle, especially if one is used to gromacs tools.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/843, or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQvopKvWdwXXtBENOIiai9cStXaOwks5qPAK1gaJpZM4I96bG.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by OleksandraQ** [comment]
Yes, but it was not a case for some previous versions. I've check it for 2.2., 2.1 and 2.0: the order in describe and output are different.

**Comment by franknoe** [comment]
Thanks Oleksandra! Weird - which commit could have affected this 
functionality?

Am 24/06/16 um 18:22 schrieb OleksandraQ:

> Yes, but it was not a case for some previous versions. I've check it 
> for 2.2., 2.1 and 2.0: the order in describe and output are different.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/843#issuecomment-228391653, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AGMeQl75KzX3YP03dAPyFXUlAn8prycpks5qPARAgaJpZM4I96bG.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
The order of the output is indeed different from the returned description. The order of the indices passed to mdtraj for the angle calculation is:

 (phi_1, psi_1, ..., phi_n, psi_n)

while the order of the description list is
(phi_1, ... phi_n, psi_1, ..., psi_n)

I'll open up a PR for this.
