### ISSUE TITLE
Question about TICA tutorial 

### ISSUE THREAD

**Issue by Vron-Vron** [markovmodel/PyEMMA#847]
Hi 

I am new to python and have been trying to follow your online PyEMMA tutorial on TICA analysis. I have managed to generate the graph with the states mapped to the free energy and I was wondering if it is possible to create a number of representative sample structures and save them? The python keeps recommending random_sample() but how would I then be able to match the conformation to the state mapped onto the free energy graph?

**Comment by fabian-paul** [comment]
Hi and welcome to PyEMMA!

In short: I would recommend following the tutorial the end, it's explained there (in the PCCA section):
http://www.emma-project.org/latest/generated/pentapeptide_msm.html

If I try to read a bit between the lines of you question, I can only assume that you want to get the representative structures directly from TICA without builing an MSM. Is there any reason not to build the MSM?

In any case, you might extract representative structures for the "extremes" of a TICA dimension, that is, the frames with the lowest/highest values of independent component number i.
To extract the 100 frames with the lowest value if TIC#0, you could do (assuming that `tica` is your current tica object and that `pdb` holds the name of your topology file):

``` Python
tics = tica.get_output(dimensions=[0])
order = np.argsort(np.concatenate(tics)[:,0])[0:100]
per_traj_indices = np.concatenate([np.array((np.ones(l, dtype=int)*i, np.arange(l))).T for i,l in enumerate(tica.trajectory_lengths())])
pyemma.coordinates.save_traj(tica.filenames, per_traj_indices[order], 'TIC0_extreme_negative.xtc', top=pdb)
```

The trick is done with `pyemma.coordinates.save_traj` http://www.emma-project.org/latest/api/generated/pyemma.coordinates.save_traj.html#pyemma.coordinates.save_traj and some index magic.

**Comment by Vron-Vron** [comment]
Hi, 

Thank you for your response. Yes, I was trying to get representative structures without having to build the MSM.
