### ISSUE TITLE
[coor.util.frames_from_file] wrong error message?

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#856]
Please @marscher take a look at the following behavior:

``` python
print(istride)
print(isample[:5])
#50 # this is the stride
## How index looks like (only first 5 entries)
#[[4694    0]
#[4735    0]
#[6920  269]
#[8528   64]
#[4585   21]
```

Now, look at this error message:

``` python
pyemma.coordinates.save_traj(ilist, isample, None, top=ifeat.topology, stride=istride)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-44-66958fda1986> in <module>()
      1 pyemma.coordinates.save_traj(ilist, isample, None, top=ifeat.topology,
----> 2                              stride=istride)

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/api.py in save_traj(traj_inp, indexes, outfile, top, stride, chunksize, image_molecules, verbose)
    656                          % (len(trajfiles), indexes[:,0].max()))
    657 
--> 658     traj = frames_from_files(trajfiles, top, indexes, chunksize, stride, reader=reader)
    659 
    660     # Avoid broken molecules

/home/mi/gph82/programs/PyEmma/pyemma/coordinates/data/util/frames_from_file.py in frames_from_files(files, top, frames, chunksize, stride, verbose, copy_not_join, reader)
    109                              (largest_ind_in_traj/stride, largest_ind_in_traj/stride,
    110                               stride, largest_ind_in_traj, reader.filenames[itraj],
--> 111                               length))
    112 
    113     # we want the FeatureReader to return mdtraj.Trajectory objects

ValueError: largest specified index (5 * stride=5 * 50=250) is larger than trajectory length './LEOS_tmp/10197_rhodopsin_ip_extended/RUN182/CLONE73/frames0-0.Prot-Masses_PLM.xtc' = 201
```

So, in principle, the file  './LEOS_tmp/10197_rhodopsin_ip_extended/RUN182/CLONE73/frames0-0.Prot-Masses_PLM.xtc' does not have **5** \* stride = 250 frames. 

Let's take a look at the entries of `isample` that are responsible for this error:

``` python
nfile = np.argwhere(['./LEOS_tmp/10197_rhodopsin_ip_extended/RUN182/CLONE73/frames0-0.Prot-Masses_PLM.xtc' == ff for ff in ilist])
nfile = nfile.squeeze()
print(nfile)
#13195
print(isample[isample[:,0]==nfile])
#array([[13195,     2],
# [13195,     1]])
```

Frame nr. **5** was never asked for. Since save_traj works otherwise fine and produces the right frames (that, we've checked extensively), i think the "sanity checks " for the indices are just not working. 

Since this has been heavily rewritten to be reader-based, I cannot now find the error in those checks. Can you, @marscher?

**Comment by gph82** [comment]
What's even weirder, this works (and produces the right frames):

``` python
pyemma.coordinates.save_traj(ilist, isample[isample[:,0]==nfile], None, top=ifeat.topology, stride=istride)
# <mdtraj.Trajectory with 2 frames, 5226 atoms, 328 residues, and unitcells at 0x7f4e2e46fa20>
```

**Comment by gph82** [comment]
yep, commenting  out the "sanity checks"  avoids this error and retrieves the right frames. Perhaps some of the variables are not tracking what you think are tracking?

**Comment by marscher** [comment]
It seems the stride argument is missing here: https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/data/util/frames_from_file.py#L105

**Comment by gph82** [comment]
I don't think so, because the frame indices have already multiplied by the stride here:
https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/coordinates/data/util/frames_from_file.py#L77 

BTW, i think we can clean my code a bit and leave the "verbose" argument out. Also the case if stride!=1, and just always multiply by stride. I mean completely exchange this code

``` python
    if stride != 1:
        frames[:, 1] *= int(stride)
        if verbose:
            log.info('A stride value of = %u was parsed, '
            'interpreting "indexes" accordingly.' % stride)
```

for

``` python
frames[:, 1] *= int(stride)
```

Doesn't really affect the issue but makes things clearer

**Comment by marscher** [comment]
Could not reproduce. Waiting for input
