### ISSUE TITLE
[doc] Document get_output(self, dimensions=slice(0, None), stride=1, skip=0, chunk=None)

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#859]
Surprisingly, this does not appear documented anywhere in the api or in these files...
./pyemma/coordinates/transform/transformer.py:    def get_output(self, dimensions=slice(0, None), stride=1, skip=0, chunk=None):
./pyemma/coordinates/data/_base/iterable.py:    def get_output(self, dimensions=slice(0, None), stride=1, skip=0, chunk=None):

Any way we can "pull up" the doc from here automatically? (https://github.com/markovmodel/PyEMMA/blob/582e923a141d61bbb092c3eb5d6cfb30b6b82b63/pyemma/coordinates/data/_base/iterable.py#L255)

``` python
    def _create_iterator(self, skip=0, chunk=0, stride=1, return_trajindex=True, cols=None):
        """
        Should be implemented by non-abstract subclasses. Creates an instance-independent iterator.
        :param skip: How many frames to skip before streaming.
        :param chunk: The chunksize.
        :param stride: Take only every stride'th frame.
        :param return_trajindex: take the trajindex into account
        :return: a chunk of data if return_trajindex is False, otherwise a tuple of (trajindex, data).
        """
```

**Comment by marscher** [comment]
We have a decorator for this ("doc_inherit") and we should use it here. Thanks for spotting!
