### ISSUE TITLE
dimensionality  for tram estimator's inputs (btrajs)

### ISSUE THREAD

**Issue by juanmit** [markovmodel/PyEMMA#871]
Hi PyEMMA,

I am working on getting the tram algorithm work for my own project, and I met an issue do not know how to solve. Please give me some suggestions. Thanks a lot.

Basically, I have run simulations with different thermodynamic conditions with different length(different number of total frames). And when I tried to make the input btrajs, it always gave me an error saying ValueError: setting an array element with a sequence, which normally about setting an array from a list that isn't shaped like a multi-dimensional array, such as numpy.array([[1,2], [2, 3, 4]]). So I am wondering how tram works for this dimension, and are there any things I need to do to solve this issue?

Thanks a lot. 
--Hongbin

**Comment by fabian-paul** [comment]
Hi Hongbin,

just keep the outmost dimension as a Python list. TRAM accepts a list of btrajs where every element corresponds to the bias energies from one simulation trajectory. 

Best,
Fabian

**Comment by juanmit** [comment]
Hi Fabian,

Thanks for replying. I will keep working on the a "multi-length_element" list for TRAM. Once TRAM can recognize the dimensions, it should work in the end. Thanks.  
--Hongbin

**Comment by marscher** [comment]
I guess this question has been answered.
