### ISSUE TITLE
Featurizer does not support preprocessing steps like remove waters, centering etc.

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#89]
This could be done by letting the user define a simple function getting a trajectory object and should return a trajectory

    def preprocess(traj):
         traj = mdtraj.remove_solvent(traj)
         ....
         return traj

this function is being called in map.

Main Problem is how to calculate output dimensions, since they would be first known if first frame is preprocessed. Also we can not simply load and use the input topology, since its being changed during preprocessing.

**Comment by franknoe** [comment]
It should be possible to determine the output dimension once the 
topology file has been loaded. In principle that could be done before 
reading any coordinate.

This is one of the things we can discuss next week. Should we strip 
waters or should we rather select subsets of interest, e.g. "select 
protein", which would also include the possibility to do something like 
"select (not WAT)" in the pseudolanguage that mdtraj supports. This is a 
very common thing for MD people who are used to work with VMD etc.

Am 25/02/15 um 12:24 schrieb Martin K. Scherer:
>
> This could be done by letting the user define a simple function 
> getting a trajectory object and should return a trajectory
>
> |def preprocess(traj):
>       traj = mdtraj.remove_solvent(traj)
>       ....
>       return traj
> |
>
> this function is being called in map.
>
> Main Problem is how to calculate output dimensions, since they would 
> be first known if first frame is preprocessed. Also we can not simply 
> load and use the input topology, since its being changed during 
> preprocessing.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/89>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
