### ISSUE TITLE
TypeError in _draw_arrow() with newer versions of numpy

### ISSUE THREAD

**Issue by kai687** [markovmodel/PyEMMA#907]
Using numpy 1.11, I tried to plot a Hidden Markov Model with _plot_markov_model()_, explicitly providing the positions of the states with with an array. I received the following error:

`TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''`

I replaced the offending line in _plots/network.py_:
`vnorm /= math.sqrt(np.dot(vnorm,vnorm))`
with:
`vnorm = np.divide(vnorm, np.linalg.norm(vnorm))`
or, if you insist in performing the normalization explicitly
`vnorm = np.divide(vnorm, np.sqrt(np.dot(vnorm, vnorm))`
and everything works as advertised.

**Comment by marscher** [comment]
are you passing the positions as an integer array?

**Comment by kai687** [comment]
I guess I did.

**Comment by marscher** [comment]
The cast warning (which is triggered as an exception due to the safe-cast rule) indicates, that the input wasn't floating point.

Can you show us how you've set the positions please? Anyhow we should cast the input accordingly and throw an error, which is not that misleading.

**Comment by kai687** [comment]
Sure. I used the following line, which throws the above mentioned error: 
`mplt.plot_markov_model(hmm, pos=np.array([ [0,0], [5,0], [5,-5] ]))`
(hmm is a hidden markov model, same procedure as in your examples) 
The network plots as expected, when I perform the above mentioned 
change in the normalization.
