### ISSUE TITLE
propagate function of msm.models.msm and hmsm returns complex values

### ISSUE THREAD

**Issue by greenTara** [markovmodel/PyEMMA#909]
When the number of propagation steps k is one or more, the return value from propagate is a vector of complex values. Although the imaginary part is 0.j, this cause unexpected results when using this function. If the input is real and k is a nonnegative integer, then I believe there is no reason the output should be anything but real-valued.

**Comment by marscher** [comment]
I guess you have a dense matrix there. The only thing which could introduce complex values here are the eigenvalues/vectors of P during the propagation. I think we wanted to cut the dtype to float, if the imaginary parts are all zero in msmtools.analysis.rdl_decomposition (it is on the issue list in msmtools)

**Comment by marscher** [comment]
Is your model reversible? (since non-reversible matrices can have a non-real spectrum).

**Comment by greenTara** [comment]
The model is not reversible. This is coming up in testing. I constructed a
transition matrix from a decomposition, so I know the eigenvalues are
supposed to be real.

I just checked on what the .eigenvalues() method returns - they are complex
values, but with 0.j as imaginary part.

So yes, this is probably where the complex part is coming in.

However, I would have expect the propagate function to return only the real
part (deleting the 0.j) if the input probability distribution is real (not
sure what a complex probability distribution would mean!) and "k" is a
positive integer (conceivably, non-integer values of k are possible ...).

Tara

On Wed, Aug 24, 2016 at 3:57 PM, Martin K. Scherer <notifications@github.com

**Comment by marscher** [comment]
for dense matrices this code branch is being executed:

``` python
 pk = mdot(p0.T, self.eigenvectors_right(), np.diag(np.power(self.eigenvalues(), k)), self.eigenvectors_left())
```

This is cheaper to compute than raising P to the power of k. So this case is not handled explicitly, which needs to be done.

As a workaround you could do something like this:

``` python
model._R = np.real(model._R)
model._D = np.real(model._D)
model._L = np.real(model._L)
```

before invoking the propagate method.

**Comment by marscher** [comment]
@franknoe Do you think we should add a check in the decomposition method on PyEMMAs side to discard the imaginary part, if all parts are zero?

**Comment by greenTara** [comment]
I was just looking at the input assertions - k is only allowed to be a
non-negative integer.
So there should be no need to check if the imaginary part is zero - the
imaginary part should always come out to be zero, if the input is real.
There is not currently an input assertion for that.

Tara

On Thu, Aug 25, 2016 at 2:44 PM, Martin K. Scherer <notifications@github.com

**Comment by trendelkampschroer** [comment]
@marscher: The result of 

``` python
mdot(p0.T, self.eigenvectors_right(), np.diag(np.power(self.eigenvalues(), k)), self.eigenvectors_left())
```

can be safely cast to real if a full set of eigenvalues and eigenvectors of a transition matrix have been used. I assume that is always the case here.

**Comment by marscher** [comment]
thanks for clarifying.
