### ISSUE TITLE
Bug in PCCA

### ISSUE THREAD

**Issue by trendelkampschroer** [markovmodel/PyEMMA#91]
If the PCCA method is given eigenvectors with complex entries it issues a warning but does not produce any return value. It should either raise an Error or raise a Warning and return the correct things.

**Comment by franknoe** [comment]
thanks, I'll handle it.

**Comment by franknoe** [comment]
resolved by the following actions:
* pcca-internal methods are not hidden by a preceding '_', including functions accepting eigenvectors
* when calling pcca with non-reversible matrices a ValueError is raised. Susanna mentioned that she has a potential fix for this by replacing each complex conjugate pair by the real and imaginary components of one of the two vectors. We could use this but would then need to orthonormalize all eigenvectors e.g. using Gram-Schmidt orthonormalization. Currently there is no theoretical foundation for this, so I'll skip it for now.
