### ISSUE TITLE
PCCA opt_soft memberships incorrect

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#92]
will try to gather more details (numpy/scipy was a bit out of date, but this should not lead to this issue).

**Comment by marscher** [comment]
in msm/analysis/dense/pcca.py each membership vector gets scaled by its sum. Thereby a division by zero might occur (I guess its not being catched because the author of the algo thought he excluded this case already). Since there are different ways Numpy handles div by zero on different systems/plattforms this might raise or not, but anyway leads to wrong results.

So would a simple check for zero sums avoid this already or shall we dig in deeper to find the source of empty rows?

**Comment by franknoe** [comment]
This may have been me, but at least it's in the code that I have worked 
on, so I'll handle it.

Am 25/02/15 um 18:36 schrieb Martin K. Scherer:
>
> in msm/analysis/dense/pcca.py each membership vector gets scaled by 
> its sum. Thereby a division by zero might occur (I guess its not being 
> catched because the author of the algo thought he excluded this case 
> already). Since there are different ways Numpy handles div by zero on 
> different systems/plattforms this might raise or not, but anyway leads 
> to wrong results.
>
> So would a simple check for zero sums avoid this already or shall we 
> dig in deeper to find the source of empty rows?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/92#issuecomment-76013530>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 25.02.2015 um 18:38 schrieb Frank Noe:
> This may have been me, but at least it's in the code that I have worked
> on, so I'll handle it.

btw: there is also no test for disconnected input.

**Comment by franknoe** [comment]
There are tests for disconnected input, here:

ls pyemma/pyemma/msm/analysis/dense/pcca_test.py

perhaps this test is not run?

Am 25/02/15 um 18:39 schrieb Martin K. Scherer:
> Am 25.02.2015 um 18:38 schrieb Frank Noe:
> > This may have been me, but at least it's in the code that I have worked
> > on, so I'll handle it.
>
> btw: there is also no test for disconnected input.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/92#issuecomment-76014169>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 25.02.2015 um 18:43 schrieb Frank Noe:
> There are tests for disconnected input, here:
> 
> ls pyemma/pyemma/msm/analysis/dense/pcca_test.py
> 
> perhaps this test is not run? 
> 
Alright. This file is being executed during tests, but we've not set
that division by zero will raise, which IMHO should be always the case.

**Comment by franknoe** [comment]
yes

Am 25/02/15 um 18:45 schrieb Martin K. Scherer:
> Am 25.02.2015 um 18:43 schrieb Frank Noe:
> > There are tests for disconnected input, here:
> >
> > ls pyemma/pyemma/msm/analysis/dense/pcca_test.py
> >
> > perhaps this test is not run?
> >
> Alright. This file is being executed during tests, but we've not set
> that division by zero will raise, which IMHO should be always the case.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/92#issuecomment-76015404>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
opt_soft method works correctly now that eigenvectors are guaranteed to be orthogonal. This resolved this issue.
