### ISSUE TITLE
Mapping back PCA & TICA Dimensions to Input Data Set

### ISSUE THREAD

**Issue by Sawrz** [markovmodel/PyEMMA#924]
Hey there,
I'm trying to figure out a way, where i can find out which of the given dimensions survived TICA or PCA. All I got is the already projected data set, where i can't map the dimensions back to the data set I did PCA or TICA on. 
Is there an already build in function or a work around for getting the index of the input dataset of the survived dimension where i could easily map it back?

I hope my question is not too confusing...

**Comment by gph82** [comment]
Hi, not confusing at all. Your question is very meaningful...if you change the word "survived" with "most correlated to". We've implemented exactly that here: 
http://www.emma-project.org/latest/api/generated/pyemma.coordinates.transform.TICA.html#pyemma.coordinates.transform.TICA.feature_TIC_correlation

The PCA equivalent is not yet there, but will be soon. Not to high prio for now
