### ISSUE TITLE
pcca bug: encountered only on windows on day3 excercise

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#93]
# exercise: compute PCCA memberships
    
    membership=pcca(T, 4)
    
    ---------------------------------------------------------------------------
    
    ValueError                                Traceback (most recent call last)
    
    <ipython-input-6-4285d193089a> in <module>()
    
          1 # exercise: compute PCCA memberships
    
    ----> 2 membership=pcca(T, 4)
    
    
    
    C:\Miniconda\lib\site-packages\pyEMMA-1.1-py2.7-win-amd64.egg\pyemma\msm\analysis\api.pyc in pcca(T, n)
    
       1389         return dense.pcca.pcca(T.toarray(), n)
    
       1390     elif isdense(T):
    
    -> 1391         return dense.pcca.pcca(T, n)
    
       1392     else:
    
       1393         _type_not_supported
    
    
    
    C:\Miniconda\lib\site-packages\pyEMMA-1.1-py2.7-win-amd64.egg\pyemma\msm\analysis\dense\pcca.pyc in pcca(P, m)
    
        380         elif (m_by_component > 1):
    
        381             #print "submatrix: ",closed_components_Psub[i]
    
    --> 382             chi[component,ipcca:ipcca+m_by_component] = pcca_connected(closed_components_Psub[i], m_by_component)
    
        383             ipcca += m_by_component
    
        384         else:
    
    
    
    C:\Miniconda\lib\site-packages\pyEMMA-1.1-py2.7-win-amd64.egg\pyemma\msm\analysis\dense\pcca.pyc in pcca_connected(P, n, return_rot)
    
        256
    
        257     # create initial solution using PCCA+. This could have negative memberships
    
    --> 258     (chi, rot_matrix) = pcca_connected_isa(evecs, n)
    
        259
    
        260     # optimize the rotation matrix with PCCA++.
    
    
    
    C:\Miniconda\lib\site-packages\pyEMMA-1.1-py2.7-win-amd64.egg\pyemma\msm\analysis\dense\pcca.pyc in pcca_connected_isa(evec, n_clusters)
    
         46
    
         47     """
    
    ---> 48     (n,m) = evec.shape
    
         49
    
         50     # do we have enough eigenvectors?
    
    
    
    ValueError: need more than 1 value to unpack

**Comment by franknoe** [comment]
opt_soft method works correctly now that eigenvectors are guaranteed to be orthogonal. This resolved this issue.
