### ISSUE TITLE
pyemma.coordinates.save_coor: obsolete outputs even with verbose=False

### ISSUE THREAD

**Issue by sstolzenberg** [markovmodel/PyEMMA#932]
Hi,

in the pyemma.coordinates.save_coor method, regardless of whether I set verbose=False or =True, I always get an output statement for each particular coordinate file that I just wrote out, e.g.:

9-09-16 18:26:38 pyemma.coordinates.api INFO     Created file WT.pcca2_100samples.bs_0.dcd
INFO:pyemma.coordinates.api:Created file WT.pcca2_100samples.bs_0.dcd

This can be quite cumbersome for a large number of coordinate files, but the "verbose" parameter should actually control this output behavior, correct?

Thanks,
Sebastian

**Comment by marscher** [comment]
@gph82 The log level of the "file created" message is info, which is too high in my opinion and anyway should only be fired if verbose is set.

**Comment by gph82** [comment]
@marscher: I find that the automatic behavior should be to inform the user by default if a file is being created. Also, it leaves the behavior of the API intact. 

Less important: from my experience in the workshops this is one of the features that inexperienced users use the most ("Finally, after all the model-building, I get to see some structures"), and it is nice that they're being informed about it. Experienced users can turn it off.
