### ISSUE TITLE
Need nontrivial automatic test cases for data pipeline

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#95]
Almost all of the "real-world" examples produced errors with the data pipeline or parts of it. Please use nontrivial test cases in order to make sure it is robust.

**Comment by marscher** [comment]
We can setup a jenkins job, which does integration testing on huge
datasets (maybe also performance tests to detect, if changes slow it down).

Do you have a suggestion which data to use? Most preferably with well
known results to check against.

For performance regression testing we would need an exclusive system
(maybe reserve a node in the cluster), which does not do any other job.

**Comment by franknoe** [comment]
This is identical to #210
