### ISSUE TITLE
plot_markov_model does not accept pos argument

### ISSUE THREAD

**Issue by pgromano** [markovmodel/PyEMMA#955]
Hello all, 

I've run into a new error using `pyemma.plots.plot_markov_model` inside the Jupyter Notebook, where it fails to plot if I use the pos=ndarray(n,2). The code is shown below.

```
def _get_positions(m):
    def _R(theta):
        R = np.array([[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])
        return R

    theta = 2*np.pi/m
    pos = np.squeeze([np.dot([0,1],_R(-n*theta)) for n in range(m)])
    return pos

plt.figure(figsize=(60,45))
msmplt.plot_markov_model(transitionMatrix, 
                         pos=_get_position(n_MacroStates),
                         minflux=1e-5, fontsize=25, 
                         arrow_label_format="%1.3f", 
                         state_colors=plt.cm.rainbow(np.linspace(0,1,n_MacroStates)), 
                         state_sizes=metastable_distributions[:,0], 
                         state_labels=[n+1 for n in range(n_MacroStates)], 
                         color='w');
plt.show()
```

Additionally, arbitrary positions, `pos=np.array([[-1,0],[1,0]])`, produce the same error. The plot tool works well if I remove the pos=ndarray(n,2) argument altogether. This code worked in the past, but however no longer works for several different simulations being analyzed. I've attached the error output in a file.

IPython 5.1.0 (conda 4.1.11)
PyEMMA 2.0.4

[plots_markov_model.error.txt](https://github.com/markovmodel/PyEMMA/files/516736/plots_markov_model.error.txt)

**Comment by marscher** [comment]
The error message suggests that the png backend produced an error, which matplotlib version are you using? Can you reproduce this using the lastest pyemma version (2.0.4 is fairly old). Also try the latest matplotlib version (1.5.3).

**Comment by pgromano** [comment]
The update to 1.5.3 didn't update `icu` and broke a lot of `pyplot`. It's discussed in issue [#30](https://github.com/conda-forge/matplotlib-feedstock/issues/30).

After incorporating the fixes discussed there, PyEMMA updated to 2.2.6, and matplotlib version 1.5.3, the problem still persists. I've attached an updated error file.
[error.txt](https://github.com/markovmodel/PyEMMA/files/520001/error.txt)

**Comment by marscher** [comment]
https://stackoverflow.com/questions/15697580/python-matplotlib-and-libpng-incompatibility-issue Maybe it is an related issue. Can you please try to use the jpeg backend? If this solves the problem, you should check your installation. If libpng is used from the system library instead of Anacondas version this can cause trouble.

**Comment by marscher** [comment]
https://stackoverflow.com/questions/13817940/matplotlib-and-libpng-issues-with-ipython-notebook this otool call seems interesting too.

**Comment by marscher** [comment]
@pgromano What is the status on this? Did you have any luck fixing your matplotlib installation? Can you reproduce this error on another system? Alternatively you can provide the transition matrix as a npy file, so I could try to reproduce this locally.

**Comment by marscher** [comment]
Feel free to re-open, once you can provide more info
