### ISSUE TITLE
TRAM docs

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#957]
I just discussed with Oleksandra who is using TRAM for a multi-ensemble simulation. It's quite hard to understand how to use it, and I have convinced myself that I wouldn't be able to do it based on the documentation. Here's the problem:

Using `pyemma.thermo.tram` you get a TRAM object. The doc page:
http://www.emma-project.org/latest/api/generated/thermo-api/pyemma.thermo.tram.html#pyemma.thermo.tram
doesn't link anything in the "Return type", so this is a dead end. When looking up MEMM manually here:
http://www.emma-project.org/latest/api/generated/thermo-estimators/pyemma.thermo.MEMM.html#pyemma.thermo.MEMM
One finds most attributes undocumented. Things like the `msm` attribute exist, but don't seem to do anything. After a little playing around I found out that the `models` object is a list to the actual MSMs that allow the user to compute quantities of interest, but that doesn't appear to be documented.

All of these objects and their attributes need to be fully documented and links between objects should work. Also a few code examples in the object docs would help. See MSM object as an example. I guess similar issues exist for other objects in the thermo package, but I haven't checked.

**Comment by franknoe** [comment]
@cwehmeyer , whenever you have a chance, please have a look at this.

**Comment by marscher** [comment]
By looking at the documentation this is fixed.
