### ISSUE TITLE
Pipeline processing speed

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#96]
TICA (and perhaps other pipeline steps) are super-slow in streaming mode and very fast in memory mode. There should only be a factor of 2 difference because of the two processing steps, but otherwise the speeds should be similar, because the data needs to be processed anyway.

**Comment by marscher** [comment]
this is related to the random chunksize estimation which yields sometimes very small values (huge pythonic overhead).

**Comment by marscher** [comment]
What may also cause slowdowns is the preparation of chunks, which copies alot of memory around.

**Comment by marscher** [comment]
until we have some machinery to reliably measure speeds, this issue remains a meta issue - we can not describe any progress.

**Comment by franknoe** [comment]
OK, I will try to make more specific issues. Moreover, users should 
point out bottlenecks - it makes sense to work always on the slowest 
step of the pipeline.

Am 13/03/15 um 11:50 schrieb Martin K. Scherer:
>
> until we have some machinery to reliably measure speeds, this issue 
> remains a meta issue - we can not describe any progress.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/96#issuecomment-78914554>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
