### ISSUE TITLE
Is there deviation between tica_ojb.get_output() and pca_obj.get_output() calculation?

### ISSUE THREAD

**Issue by funnybomb** [markovmodel/PyEMMA#965]
I have a start pdb file named "a.pdb", and a corresponding simulation file named "a.xtc", I want to mark the point of the pdb structure on the first two PCs. So when I test the projection, I got different results by manually calculated projection via np.dot(dev,eigenvectors)[:2] when using TICA, but same result when using PCA

``` python
traj='a.xtc'
feat = coor.featurize('a.pdb')
feat.add_backbone_torsions(cossin=True）
inp = coor.load(traj, feat)
inp.shape
(50000,872)
tica_obj = coor.tica(inp)
tica_Y = tica_obj.get_output()[0]
pca_ojb = coor.pca(inp)
pca_Y = pca_obj.get_output()[0]
manual_tica_f0 = np.dot( (inp[0,:] - tica_obj.mean), tica_obj.eigenvectors )
manual_pca_f0 = np.dot( (inp[0,:] - pca_obj.mean), pca_obj.eigenvectors )
manual_tica_f0[:2] - tica_Y[0,:2]
Out[47]: array([-0.00618514,  0.00866887])
manual_pca_f0[:2] - pca_Y[0,:2]
Out[48]: array([ -2.79164256e-08,   1.37719329e-08])
```

**Comment by franknoe** [comment]
If you use TICA with `kinetic_map=True` (default), there is an additional scaling of eigenvectors by eigenvalues:

``` python
        X_meanfree = X - self.mean
        Y = np.dot(X_meanfree, self.eigenvectors[:, 0:self.dimension()])
        if self.kinetic_map:  # scale by eigenvalues
            Y *= self.eigenvalues[0:self.dimension()]
return Y.astype(self.output_type())
```

If you initialize tica with kinetic_map=False I would expect the line `out[47]` to show near zeros. Differences on the order of 1e-8 are numerical errors.
