### ISSUE TITLE
[msmtools.flux.ReactiveFlux.coarse_grain] sorted by commitor? 

### ISSUE THREAD

**Issue by gph82** [markovmodel/PyEMMA#981]
AFAIK:
   * the order of the coarse sets does not reflect the order of the input and 
   * they be sorted by committor: 

(https://github.com/markovmodel/PyEMMA/issues/677#issuecomment-172962243 and https://github.com/markovmodel/PyEMMA/issues/677#issuecomment-172962562). 

However, I'm getting this (pyemma version 2.2.7+13.g05f5fc4)
```python
jMSM = pyemma.msm.markov_model(np.load('P.npy'))
set_A = np.load('A.npy')
set_B = np.load('B.npy')
jMSM.pcca(6)
jtpt = pyemma.msm.tpt(jMSM, set_A, set_B)
jtpt_coarse_sets, jtpt_coarse_reactive_flux = jtpt.coarse_grain(jMSM.metastable_sets)
jtpt_coarse_reactive_flux.committor
# array([ 0.        ,  0.64261339,  0.56212569,  0.79059808,  0.39101618,  1.        ])
```

I.e., clearly not sorted wrt. to q. 

I haven't taken a look at the code yet, but can someone confirm if we're only enforcing q[0]=0 and q[-1] = 1 and not touching the rest?

Here's a zipfile if you want to try the test
[issue.zip](https://github.com/markovmodel/PyEMMA/files/568918/issue.zip)

**Comment by gph82** [comment]
I guess this https://github.com/markovmodel/PyEMMA/blob/devel/pyemma/msm/models/reactive_flux.py#L377 is the place to sort wrt. the committor, right before instantiating the coarse ReactiveFlux object. 

One would instantiate after having sorted these variables, right? 
Fnet_coarse, pstat_coarse, backward_committor_coarse, forward_committor_coarse, F_coarse

**Comment by marscher** [comment]
have you figured this one out in the mean time?

**Comment by gph82** [comment]
nope
