### ISSUE TITLE
ITS can not call estimate twice with different lags parameter

### ISSUE THREAD

**Issue by marscher** [markovmodel/PyEMMA#999]
There is no setter for lags, which is needed for this sklearn pattern.

**Comment by gph82** [comment]
This would be really great, since adding longer (or shorter) lagtimes to an already estimated its object is impossible now (or involves huge amounts of monkey-patching)

**Comment by marscher** [comment]
Do you mind sharing this monkey-patching code with me? :)

**Comment by gph82** [comment]
he! I wish I had it, tried it and got too fuzzy. Gave up along the way. But we can sit together sometime, since I already looked into this

**Comment by marscher** [comment]
Actually one should have a partial_fit interface here and re-estimate only the lags which have not been computed yet. If we just implement the setter the models for all lag times will be recomputed.
